### ISSUE TITLE
Does sonar.cxx.includeDirectories accepts regexp

### ISSUE THREAD

**Issue by FloOows** [SonarOpenCommunity/sonar-cxx#1001]
I can't find any answer on documentation. I am wondering if the parameter of sonar-project.properties _sonar.cxx.includeDirectories_ is compatible with regexp ? 

For example for each of my two modules I defined like that
_Module1.sonar.cxx.includeDirectories=module1/include
Module2.sonar.cxx.includeDirectories=module2/include_

but _include_ contains several folder. Does all folder are parsed by sonarQube ? Does I need to write _Module2.sonar.cxx.includeDirectories=module2/include/*_ for each folder to be parsed ?

**Comment by guwirth** [comment]
Hi @FloOows regexp are not supported.

Following rules are applied:
</p>
<ul>
  <li>? matches single character</li>
  <li>* matches zero or more characters</li>
  <li>** matches zero or more 'directories'</li>
  <li>use always '/' as a directory separator</li>
  <li>there must always be a root directory</li>
</ul>

<p>
Some examples of patterns:
</p>
<ul>
  <li>/**/*.cpp - matches all .cpp files in all directories (you have to define the root directory '/'), e.g. org/Foo.cpp or org/foo/Bar.cpp or org/foo/bar/Baz.cpp</li>
  <li>/**/test/**/Foo.cpp - matches all 'Foo.cpp' files in directories with one 'test' directory in the path, e.g. org/test/Foo.cpp or org/bar/test/bar/Foo.cpp</li>
  <li>org/T?st.cpp - matches org/Test.cpp and also org/Tost.cpp</li>
  <li>org/*.cpp - matches all .cpp files in the org directory, e.g. org/Foo.cpp or org/Bar.cpp</li>
  <li>org/** - matches all files underneath the org directory, e.g. org/Foo.cpp or org/foo/bar.jsp</li>
  <li>org/**/Test.cpp - matches all Test.cpp files underneath the org directory, e.g. org/Test.cpp or org/foo/Test.cpp or org/foo/bar/Test.cpp</li>
  <li>org/**/*.cpp - matches all .cpp files underneath the org directory, e.g. org/Foo.cpp or org/foo/Bar.cpp or org/foo/bar/Baz.cpp</li>
</ul>

**Comment by FloOows** [comment]
Thanks a lot for your answer, it will help me removing warnings about missing include.

**Comment by icaro56** [comment]
My sonar does not recognize this pattern.

sonar.cxx.includeDirectories=Private, Public, Public/**/*.h

In Public/**/*.h the error occurs:

Start\Public\**\*.h'
java.io.IOException: Invalid argument
	at java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
	at java.io.File.getCanonicalPath(File.java:618)
	at java.io.File.getCanonicalFile(File.java:643)
	at org.sonar.cxx.preprocessor.SourceCodeProvider.setIncludeRoots(SourceCodeProvider.java:53)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.<init>(CxxPreprocessor.java:249)
	at org.sonar.cxx.preprocessor.CxxPreprocessor.<init>(CxxPreprocessor.java:235)
	at org.sonar.cxx.parser.CxxParser.create(CxxParser.java:66)
	at org.sonar.cxx.CxxAstScanner.create(CxxAstScanner.java:101)

**Comment by guwirth** [comment]
@icaro56 please create new issues and do not add comments to closed issues. Think the problem are the blanks after the comma.
