### ISSUE TITLE
Sonarqube 6.1 would not start with latest snapshot

### ISSUE THREAD

**Issue by 1605200517** [SonarOpenCommunity/sonar-cxx#1004]
JAR was not recognized as plugin? Git clone before half an hour from now. Running a default standalone (filesystem DB) configuration for evaluation purposes.

2016.12.08 16:55:25 ERROR web[][o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.web.PlatformServletContextListener
org.sonar.api.utils.MessageException: File is not a plugin. Please delete it and restart: /data/lab/sonarqube-6.1/extensions/plugins/sslr-cxx-toolkit-0.9.7-SNAPSHOT-sources.jar

**Comment by jmecosta** [comment]
The toolkit and sources jar are not supposed to go to plugins.  Only the
jar of the plugin

**Comment by guwirth** [comment]
Hi @1605200517 looking here https://travis-ci.org/SonarOpenCommunity/sonar-cxx it's working with SQ 6.1?

**Comment by guwirth** [comment]
@1605200517 please reopen if still an issue.

**Comment by 1605200517** [comment]
thx, obviously I used wrong file.
