### ISSUE TITLE
Sonarqube 5.6.3 shows no rules set in C++ sonar way profile

### ISSUE THREAD

**Issue by Fergus-Murray** [SonarOpenCommunity/sonar-cxx#1005]
When I'm running the sonar community plugin in Sonar 5.6.3, I'm not getting any rules showing up when i run an analysis.

When i look at the profile on the sonar profile page, it shows 0 rules are set for this "sonar way" profile, however if I go in and try and activate more, I can see that there are actually rules enabled, just sonar doesnt realise.

I've tried 0.9.6 and 0.9.7-SNAPSHOT and both have the same issue

Any ideas on what I can do to get the rules working?

**Comment by Fergus-Murray** [comment]
Looks like the display of this was due to corrupted ES indexes (having rebuild and recreated it is now displaying ok), so not to do with the community plugin.

I still am unable to get any rules to fail in the default sonar way profile for a 175,000 loc project though

**Comment by jmecosta** [comment]
Have you enable rules from the cxx repository? Otherwise you need to run
all external tools and feed the reports to the analysis. See wiki for more
details

**Comment by guwirth** [comment]
@Fergus-Murray please reopen if still an issue.
