### ISSUE TITLE
Add Cognitive Complexity

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1006]
**Abstract**
Cyclomatic Complexity was initially formulated as a measurement of the “testability and
maintainability” of the control flow of a module. While it excels at measuring the former, its
underlying mathematical model is unsatisfactory at producing a value that measures the
latter. This white paper describes a new metric that breaks from the use of mathematical
models to evaluate code in order to remedy Cyclomatic Complexity’s shortcomings and
produce a measurement that more accurately reflects the relative difficulty of understanding,
and therefore of maintaining methods, classes, and applications.

source: https://www.sonarsource.com/docs/CognitiveComplexity.pdf

**Comment by guwirth** [comment]
Java sample: https://github.com/SonarSource/sonar-java/blob/master/java-frontend/src/main/java/org/sonar/java/ast/visitors/CognitiveComplexityVisitor.java

**Comment by nathanaelg** [comment]
I'm keen for this and will have a go at implementing (despite being new to Sonar and Java... so we will see). Just thought I'd check nobody else had already made a start?

**Comment by guwirth** [comment]
Hello @nathanaelg, thanks for contributing to this add-on.
I'm not aware that someone else is working on this.

**Comment by guwirth** [comment]
@nathanaelg did you have some time to have a look to it?

**Comment by nathanaelg** [comment]
@guwirth Sorry I haven't had much time for this yet - it definitely looked like it was going to be a bit of a learning curve understanding the structure of the project and where things should go.

**Comment by guwirth** [comment]
@nathanaelg this is the last missing bigger feature for 0.9.8. We like to close feature development in two weeks. Do you think you can provide a solution by then? Did you already have a first solution?

@all can someone else support?

**Comment by guwirth** [comment]
A good starting point could be https://github.com/SonarSource/sonar-python/blob/master/python-checks/src/main/java/org/sonar/python/checks/CognitiveComplexityFunctionCheck.java

**Comment by nathanaelg** [comment]
I haven't really been working on it but have spent a bit of time in the last couple of days - I'll see how I get on this weekend and at least post what I've done in case that is useful or someone else wants to do it a bit faster!

**Comment by guwirth** [comment]
@nathanaelg yes makes sense to create a PR with your current state.  Makes it also easier for others to give you hints.

**Comment by valdiz777** [comment]
I can pick things up wherever you get it

**Comment by nathanaelg** [comment]
https://github.com/SonarOpenCommunity/sonar-cxx/pull/1245

**Comment by guwirth** [comment]
@all cognitive complexity is available for testing. Please try and give feedback.
