### ISSUE TITLE
#include for files without extension are not handled correctly

### ISSUE THREAD

**Issue by sreeramk08** [SonarOpenCommunity/sonar-cxx#1009]
Sonar-cxx plugin complains that iostream is missing while the problem really is that the developer forgot to add the .h to iostream.  I've already verified that iostream.h exists in one of the include paths.  

Is there a way to tell Sonarqube not to flag that as a missing header file?

**Comment by guwirth** [comment]
@sreeramk08 Which error message do you get? Normally you can ignore missing includes.

**Comment by sreeramk08** [comment]
There are lot of Warnings like this
WARN: [/home/skrishna/jenkins/workspace/Sonarqube/full-xcipio-sonar-analysis/xcipio/LIS/inc/CORE/common/GMOSHelper.H:37]: cannot find the sources for '#include <string>'

WARN: [/home/skrishna/jenkins/workspace/Sonarqube/full-xcipio-sonar-analysis/xcipio/LIS/inc/CORE/common/GMOSHelper.H:39]: cannot find the sources for '#include <cnfg.h>'

As you can see the first warning is something I don't want because string.h is very much available.  The code has been written without a .h. 

But the second warning is a legitimate one which means a .h file is missing and the team is building applications without realizing it.

**Comment by sreeramk08** [comment]
For the moment since I'm not including the rule which says 'flag missing include files' the analysis does not show these missing includes.  But the scan log on jenkins is full of them.

**Comment by jmecosta** [comment]
And you have all include paths defined for the cxx analysis in the sonar.props file?

**Comment by sreeramk08** [comment]
That is correct.  I took one, for example string.h, then ran a find command from the top level of the checkout directory...and it found it in a path.  Then I made sure the path was included in the sonar's include directories list. 

And like I mentioned above, some are legitimate missing header files which sonar is correctly flagging which I could not find as expected.

**Comment by jmecosta** [comment]
i think we are missing this fallback in the search function

https://github.com/SonarOpenCommunity/sonar-cxx/blob/985c0d7849dffe25eff00aa692bcbd4a1d972e63/cxx-squid/src/main/java/org/sonar/cxx/preprocessor/CxxPreprocessor.java#L1120

**Comment by guwirth** [comment]
@jmecosta 

> i think we are missing this fallback in the search function

What exactly are we missing?

**Comment by sreeramk08** [comment]
Any updates on this?

**Comment by guwirth** [comment]
@sreeramk08 for me it's not clear what exactly is missing? Answer from @jmecosta is missing.

>i think we are missing this fallback in the search function

**Comment by jmecosta** [comment]
@guwirth i try to see if can create a pull request, if i understood. the header search function is able to find this

```#include <iostream.h>```

but not 
```#include <iostream>```

since there is no fallback to search from iostream.h or iostream.hpp in that function.

**Comment by guwirth** [comment]
@sreeramk08 ok thx understood now.

**Comment by jmecosta** [comment]
handled in #1021

**Comment by guwirth** [comment]
@sreeramk08 and @jmecosta sorry if I'm being slow on the uptake.

Using `#include <iostream>` should search for a file `iostream` only? The solution #1021 seems to search for:
* ìostream.h
* ìostream.hpp
* ìostream.hh

Which is wrong for my understanding?

**Comment by jmecosta** [comment]
@guwirth i think it should be ok now

**Comment by jmecosta** [comment]
@sreeramk08 please clarify if your include paths have been properly defined for string header.

string.h is likely a vendor specific version of string that comes from standard, be sure your system directories are included in order of it to be found.

providing a fallback might actually cause the wrong file to be included so its not recommended

**Comment by sreeramk08** [comment]
@jmecosta yes, I did a find for string.h in the entire checkout and found the path.  Then I made sure the path exists in the included directories list.  For sure, the path is available and so is the file.  the plugin is expecting a file called string as mentioned by the include statement and fails to see that string.h is the correct file.  

But @guwirth brings a valid point.  If the include statement blindly states 'string', what is the plugin expected to look for - string,h, string,hpp or something else?  

One way could be for the plugin to look for the extension as per the list of header extensions listed.  i.e if it comes across '#include string' and if the header extensions listed are .h, .hpp, then sonar should search for string.h and string.hpp and report as failure if either of those are not found.  I think this will open a bigger can of worms than expected to solve.  I am OK if you want to close this as a non-issue.  :)

**Comment by guwirth** [comment]
@sreeramk08 please read this http://stackoverflow.com/questions/441568/when-can-you-omit-the-file-extension-in-an-include-directive

Changing the filename and reading with/without other extensions is in any case wrong. Which compiler/tool is doing this?

**Comment by jmecosta** [comment]
Not sure what compiler allows this behaviour, however vc++ and intellisence
in visual studio in this case would dig string that exist in system
directories and not your string.h that exists in your checkout folder.

Are you sure you dont have a string in your system include paths, usually
those are available for all systems, you however have to configure those
system directories also for the plugin

**Comment by sreeramk08** [comment]
string.h is present.  No other file called string is present.  
[skrishna@XcipioBuildVM-135-27 xcipio]$ find . | grep -w string
./LIS/inc/linux/string.h

My file containing include paths has that path in it. 
[skrishna@XcipioBuildVM-135-27 xcipio]$ grep LIS/inc/linux ../final_includepaths
LIS/inc/linux
LIS/inc/linux/netinet

We are using GNU Make 3.82.  Sonarqube reported scanning about 1.5 million LOC.  We have custom wrappers that dives into each module, looks at the code, figures out all the include paths and writes dependency files using which paths are set for the compiler.  Probably one of those wrappers is making the judgement that an included file need not have an extension.  

I will close this issue.  The developers are not too worried about not finding an include file because those wrappers will flag an issue if an include file is indeed missing.  And its not correct to let the plugin assume that string means string.h.  Thanks for your time.

**Comment by jmecosta** [comment]
LIS/inc/linux is a subfolder likely in your home? you should search for string in /usr/include or /usr since its there usually the compiler installs those
