### ISSUE TITLE
API documentation on template function in template class with implementation

### ISSUE THREAD

**Issue by GMercat** [SonarOpenCommunity/sonar-cxx#1025]
Thanks for correction about #1000 issue, but i have a last issue 'Undocumented API' in a similar case.

It's the same case, but in `test.impl.h` file the `functionTest()` templated have implementation.

In test.h file:
```
/**
 * @brief DOCUMENTATION CLASS
 */
template <class U>
class TestClass {

[...]

public:
/**
 * @brief DOCUMENTATION FUNCTION
 */
template <class T>
void functionTest();
};

#include "test.impl.h"
```

In test.impl.h file:
```
[...]

/**
 * @brief DOCUMENTATION FUNCTION
 */
template <class U>
template <class T>
void TestClass::functionTest()
{
    // Do something
    ...
}
```

In this case, i have "Undocumented API: functionTest" on TestClass::functionTest in "test.impl.h". If a remove implementation, i haven't issue.

Can you fix this in the 0.9.7 version or it's too late ? 

sonarqube : v5.6.3
sonar-cxx : v0.9.7-SNAPSHOT (git commit: ac3d1d9021e0e6b1d89ea00dcf1298922d0a3a01)

**Comment by guwirth** [comment]
@GMercat thx for reporting the issue. Do you have other problems using the public API sensor or is this the last issue you have?

**Comment by GMercat** [comment]
@guwirth Thanks for your reactivity. No, this is really the last issue i have.

**Comment by guwirth** [comment]
@GMercat looking to your sample:
* it's an issue that you get 'Undocumented API' in test.impl.h
* it would be not an issue if comment is missing in In test.impl.h because normally only declaration is checked and not definition. In your sample functionTest is documented twice.
Is that also your understanding?

**Comment by GMercat** [comment]
@guwirth Yes that's it.

In my example, functionTest is documented twice. But whatever I do in `test.impl.h` I get `Undocumented API` on `void TestClass::functionTest()`line in `test.impl.h`.

**Comment by guwirth** [comment]
@GMercat please try with latest snapshot. 

To be consistent you have to document ’TestClass::functionTest’. The sensor is currently not able to distinguish between declaration and definition and to detect if the one or the other has a documentation.

**Comment by GMercat** [comment]
@guwirth It's tested and it works ! Thanks again for your reactivity.
