### ISSUE TITLE
Error in macro expansion

### ISSUE THREAD

**Issue by BrenMcGuire** [SonarOpenCommunity/sonar-cxx#1026]
Hi,

I get a parsing error when expanding this macro (I'm using version 0.9.6 with Sonarqube 5.6.4):

``#define DEFINE_OPERATORS(T) inline T &operator ^= (T &a, T b) { return (T &)(((int &)a) ^= ((int)b)); }``

This macro definition is not the original one (it is actually used to define several bit operators for enum types), it contains only the operator which seems to cause the problem (`operator^=`), there is no error for example for `operator&=`.

**Comment by guwirth** [comment]
@BrenMcGuire should be solved with #1028. Please test and give us feedback.
