### ISSUE TITLE
Run an analysis

### ISSUE THREAD

**Issue by ridi-mz** [SonarOpenCommunity/sonar-cxx#1027]
Hello, 
I want to run an analysis on a c/c++ program using sonar-cxx plugin. I have tried to follow the steps on the wiki without success. Is there a minimalistic example? Is there a build wrapper to use ? 
Furthermore, I want to look for security/vulnerabilities in my program, am I using the right plugin?

**Comment by guwirth** [comment]
Hi @ridi-mz,

> I want to run an analysis on a c/c++ program using sonar-cxx plugin. I have tried to follow the steps on the wiki without success. Is there a minimalistic example?

There are several samples in the folder https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata.

> Is there a build wrapper to use ?

For which build environment? See also https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers

> Furthermore, I want to look for security/vulnerabilities in my program, am I using the right plugin?

The plugin itself is not analysing your code. You have to run other tools beforehand and import the report files then (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-tools).

Regards,
