### ISSUE TITLE
Display measures per input file

### ISSUE THREAD

**Issue by notlistening** [SonarOpenCommunity/sonar-cxx#1030]
SonarQube : v6.2
Cxx Community Plugin: 0.9.7 SNAPSHOT

I have install the latest Plugin under the latest version of SQ and am finding that I can upload my pclint XML output and the total number of issues is being reported however on the web interface under the project Measures->PC-Lint errors I am able to see the total number of errors listed as 213 however underneath in the List / Tree there are no result and 0 of 0 entries. 

On running sonar-scanner I get the following:
Sensor CxxPCLintSensor
INFO: Searching reports by relative path with basedir '/home/tom/workspace/xxxxx' and search prop 'sonar.cxx.pclint.reportPath'
INFO: Scanner found '1' report files
INFO: Parser will parse '1' report files
INFO: Processing report '/home/tom/workspace/xxxxxx/lint.report'
WARN: Cannot find the file '/usr/include/json-c/json_object.h', skipping violations
WARN: Cannot find the file '/home/tom/workspace/xxxxx/xxxxx/xxxxx/xxxxx.h', skipping violations
INFO: PC-Lint errors processed = 213
INFO: Sensor CxxPCLintSensor (done) | time=588ms

Even with the current warnings I would expect the errors to be reported. 

Also these files are in this location if I cat by copying the location their contents is displayed. 

format of XML
<issue file ="src/Project/xxxxx.c" line = "435" number = "793" desc = "ANSI/ISO limit of 31 'significant characters in an external identifier', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx(void)', exceeded -- processing is unaffected"/>

Can I get some pointers on how to debug/fix this for you guys?

**Comment by jmecosta** [comment]
Can you try with sonar 6.1 to confirm it's not related with latest api
changes in the measures api

**Comment by guwirth** [comment]
Hi @notlistening,

* Would try with debug info on, maybe you get more information https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information
* Are the rules enabled in your profile?
* Are there issues for files except the two files with warnings in your report?
* Are the source files with the issues visible in the UI?
* With which version was your sample working before?

Regards

**Comment by notlistening** [comment]
Tried with 0.96 / 5.6.4 LTS however this issue [882](https://github.com/SonarOpenCommunity/sonar-cxx/issues/882) is preventing me from further testing.

The rules are enabled as far as I can tell. All C++ rules are eneabled.

The whole code base has warnings not just those two files.

The source files are not directly visible however other tools point to the source code. The source rote is stored locally on my development machine at the moment,

I have not had this working yet :).

Thanks,

Tom

**Comment by notlistening** [comment]
Unable to find a release package for 6.1 any clues?

**Comment by guwirth** [comment]
@notlistening can you provide a source file and a sample pclint report. My idea is to extend the integration test with such a sample for testing and avoid regression in future.

Sample: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/cppcheck_project

Best would be:
* one small source file
* one pclint report
* config file

**Comment by jmecosta** [comment]
@guwirth if I understood the reports are being imported. It's just that
there is no brakedown of the measures for this pc lint. And actually for
none of the sensors since we only save the total value.

I think this is a expected behavior I wanted just to confirm with earlier
versions.

To get this brakedown we would need to save the metric for each file.

**Comment by guwirth** [comment]
@jmecosta currently we are using only SQ5.6, is this a new SQ6.2 API?

**Comment by notlistening** [comment]
Of course I will put one together for you :).

I have just done the same for drmemory and after tweaking the commandline options from the wiki I have generated the reports. 

However and this might be telling I have the same behavior as with PCLINT. There are 20 issues reported but no details included on the List / Tree. 

Log:
INFO: Sensor CxxDrMemorySensor
INFO: Searching reports by relative path with basedir '/home/tom/workspace/CDUwatchdog' and search prop 'sonar.cxx.drmemory.reportPath'
INFO: Scanner found '2' report files
INFO: Parser will parse '2' report files
INFO: Processing report '/home/tom/workspace/xxxxxx/logs/DrMemory-xxxxx.11197.000/results.txt'
INFO: Processing report '/home/tom/workspace/CDUwatchdog/logs/DrMemory-xxxxx.11196.000/results.txt'
INFO: Dr Memory errors processed = 20
INFO: Sensor CxxDrMemorySensor (done) | time=28ms

![image](https://cloud.githubusercontent.com/assets/14096341/21858490/3ad50482-d821-11e6-9c70-51eac8ca0926.png)

**Comment by jmecosta** [comment]
@guwirth it should be for all the versions, see https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/utils/CxxReportSensor.java#L96 this only saves to total. 

@notlistening i dont think we need sample, since this should be current behaviour. there is no regression
If we want that breakdown then we would need to cache the results for each report, since multiple reports can report issues against same file and in the end save the total for each file.

what is the main benefict of having this brakedown, in the issue page you can already play with the filters so you can get the relevant information

**Comment by guwirth** [comment]
Verified with SQ5.6, same behaviour.
=> Could be an enhancement for the future to set also measures per input file.

**Comment by guwirth** [comment]
> However and this might be telling I have the same behavior as with PCLINT. There are 20 issues reported but no details included on the List / Tree.

@notlistening & @jmecosta please verify it with latest snapshot. Should be fixed with #1241.
