### ISSUE TITLE
alternative to XPath rule

### ISSUE THREAD

**Issue by mettizik** [SonarOpenCommunity/sonar-cxx#1033]
Hello!
I wonder if there is any alternative for the XPath rules in sonar 6.2+ ?
This is quite important feature in our use case, so it would be great if you could give any tips about this template in newer versions of cxx plugin

**Comment by guwirth** [comment]
@mettizik maybe better to ask first in SonarQube forum what their idea is.

**Comment by mettizik** [comment]
Thanks, i created a thread there. http://forum.cakewalk.com/Altrernative-to-XPath-API-m3548730.aspx#3548730

**Comment by Bertk** [comment]
Hi, please use this forum: https://groups.google.com/forum/m/#!forum/sonarqube

**Comment by guwirth** [comment]
@mettizik any answers?

**Comment by guwirth** [comment]
@mettizik with latest snapshot XPath should be available again. But I'm still not sure how long we are able to support it?

**Comment by mettizik** [comment]
@guwirth , I'm sorry for such a long delay with answer. This week I'll try out XPath on the latest snapshot, thanks!
Can you please tell me, if there is still a need to ask on forum about XPath API deprecation?
