### ISSUE TITLE
syntax error: cast operator

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1034]
Have a syntax error with code below. Is working with VS2015:

```C++
void test()
{
 short a;
 unsigned short b;

 b = unsigned short(a); // syntax error
}
```
Below version is working:
```C++
 b = (unsigned short)(a);
```

**Comment by amai2012** [comment]
Well, here Microsoft is quite generous in accepting this, see https://stackoverflow.com/questions/2144012/explicit-type-conversion-and-multiple-simple-type-specifiers

**Comment by guwirth** [comment]
Microsoft specific code and not standard conform. Think it's easier (and better) to fix in source code.
