### ISSUE TITLE
cppcheck 1.75 WARN: Cannot find the file

### ISSUE THREAD

**Issue by sreeramk08** [SonarOpenCommunity/sonar-cxx#1036]
I am at a loss what to do next.  I have manipulated the paths in whichever way possible.  Sonar scanner is simply not reading the cpp_report.xml file and complaining that it cannot find the files listed in the report.  The report is read fine by Jenkins but Sonarqube is just not reporting the bugs even though the report has 'severity="errors"' in it.  Here are the details.  please help! 

I am running this to get the cppcheck report
cppcheck --xml-version=2  xcipio/LIS/src/CLIENTLIB 2> xcipio/cpp_clientlib.xml

I have tried with xml version 1 as well

Sonar project properties is like this:
sonar.projectKey=my:full-xcipio-Xcipio_Feature_Dev_master-CLIENTLIB
sonar.projectVersion=1.0
sonar.projectName=full-xcipio-Xcipio_Feature_Dev_master-CLIENTLIB
sonar.sources=xcipio/LIS/src/CLIENTLIB
sonar.cxx.includeDirectories=ACEROOT/inc/ace,ACEROOT/inc/ace/os_include
sonar.sourceEncoding=UTF-8
sonar.profile=xcipio-sonar-way-rules
sonar.cxx.cppcheck.reportPath=/home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/cpp_clientlib.xml
sonar.exclusions=**/CtapMediationMsg.C,**/EIMSValidationTestSuite.H

Analysis is successful but sonar scanner reports that it cannot find the files.  When I do a 'ls' on the file, its very much there.    
INFO: Searching reports by relative path with basedir '/home/support/jenkins/jenkins20/workspace/xcipio-workspace' and search prop 'sonar.cxx.cppcheck.reportPath'
INFO: Scanner found '1' report files
INFO: Parser will parse '1' report files
INFO: Processing report '/home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/cpp_clientlib.xml'
WARN: Cannot find the file '/home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/LIS/src/CORE/GENMSG/lib/GenericMessageClass.C', skipping violations
WARN: Cannot find the file '/home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/LIS/src/CORE/GENMSG/lib/Generic_BearerCapability.C', skipping violations
WARN: Cannot find the file '/home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/LIS/src/CORE/GENMSG/lib/Generic_EncryptionInformation.C', skipping violations
WARN: Cannot find the file '/home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/LIS/src/CORE/GENMSG/lib/Generic_NotificationDataList.C', skipping violations
WARN: Cannot find the file '/home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/LIS/src/CORE/GENMSG/lib/Generic_OctetString.C', skipping violations
WARN: Cannot find the file '/home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/LIS/src/CORE/GENMSG/lib/Generic_PacketInformation.C', skipping violations
WARN: Cannot find the file '/home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/LIS/src/CORE/GENMSG/lib/Generic_Payload.C', skipping violations
WARN: Cannot find the file '/home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/LIS/src/CORE/GENMSG/lib/Generic_TargetIdentity.C', skipping violations
WARN: Cannot find the file '/home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/LIS/src/CORE/GENMSG/lib/IS41C_Class.C', skipping violations
INFO: Added report '/home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/cpp_clientlib.xml' (parsed by: CppcheckParserV2)
INFO: CppCheck Errors processed = 0
INFO: Sensor CxxCppCheckSensor (done) | time=70ms

The files are there:

[support@10.0.156.73 xcipio-workspace]$ ls /home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/LIS/src/CORE/GENMSG/lib/GenericMessageClass.C
/home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/LIS/src/CORE/GENMSG/lib/GenericMessageClass.C

[support@10.0.156.73 xcipio-workspace]$ ls /home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/LIS/src/CORE/GENMSG/lib/Generic_Payload.C
/home/support/jenkins/jenkins20/workspace/xcipio-workspace/xcipio/LIS/src/CORE/GENMSG/lib/Generic_Payload.C

There are valid errors in the cpp report as well

<error id="arrayIndexOutOfBounds" severity="error" msg="Array &apos;printablePayloadStr[28]&apos; accessed at index 35, which is out of bounds." verbose="Array &apos;printablePayloadStr[28]&apos; accessed at index 35, which is out of bounds." cwe="119">
            <location file="xcipio/LIS/src/CLIENTLIB/GENVOIP/GenClientLib/src/Generic_Payload.C" line="493"/>
</error>

**Comment by sreeramk08** [comment]
Turns out the files under CLIENTLIB folder are actually soft links with relative paths pointing to the ones under CORE.   the report generated for CORE is read fine by the plugin.  Is this a bug or expected behavior?

**Comment by jmecosta** [comment]
At least core does not allow to import stuff outside src dir so at least
this is consistent
