### ISSUE TITLE
sonarscanner seems only to report code smells but no bug and no vulnerabilities

### ISSUE THREAD

**Issue by wilnauem** [SonarOpenCommunity/sonar-cxx#1040]
Hello again!

Sorry for having another question ;-)
We experience that Sonarqube is only showing code smells but neither bugs nor vulnerabilities.

Please see also https://snag.gy/CYkWtr.jpg (cut the code smell numbers off but they exist )

Do you have any idea why that might be...

- Is it a misconfig of cxx ?
- Is it a missing plugin?
...

Best regards and thank you very much for assistance
Marc

**Comment by jmecosta** [comment]
bug is available for all rules that have the tag bug, you perhaps dont have any rules enabled that have this tag. or you dont have any bugs :)

**Comment by guwirth** [comment]
As @jmecosta was saying:
* are rules activated in your profile?
* do you provide report files with bugs (e.g. from cppcheck)?
