### ISSUE TITLE
Objective C plugin for sonarqube 6.0

### ISSUE THREAD

**Issue by puneetsoni1** [SonarOpenCommunity/sonar-cxx#1046]
Hi Please anyone can suggest me objective c language plugin for sonarqube 6.0. As I already tried with sonar-objective-c-plugin-0.4.0 in setup. Please tell me

**Comment by guwirth** [comment]
@puneetsoni1 seems to have no one experience with Objective C?
So I close this issue...

**Comment by puneetsoni1** [comment]
Can you assign this issue to another person who know about that

**Comment by jmecosta** [comment]
you have this: https://www.sonarsource.com/why-us/products/languages/objectivec.html 

if you also search in github you can find many alternatives: https://github.com/search?utf8=%E2%9C%93&q=sonar+objective+c&type=Repositories&ref=searchresults 

good luck
