### ISSUE TITLE
PC-Lint xml misra 2012 report integration

### ISSUE THREAD

**Issue by MarcAntoineCRUE** [SonarOpenCommunity/sonar-cxx#1055]
Hi everyone,

For project which need to be compliant to MISRA C 2012 I'm using PC-Lint and Sonar-cxx.
The fist step is done correctly, I'm able to create a XML file with all MISRA C 2012 issue returned by PC-Lint. This file should correspond to the template provide by sonar-cxx, however I have some troubles with some descriptions of the issues.
The program I'm trying to analyse is a test i did for various static analysis tool, which means i need to test various mistakes which could be made by the an user.
When I'm starting sonarqube on windows with powershell I'm obtaining this : cf attached file.
[execution-report.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/774805/execution-report.txt)
After a check on the xml file I see various problematic lines. The following code only reference the problematic lines  

```
<?xml version="1.0" ?>
<results>
<issue file ="D:\Workspace\misra_rules_compliance_tests\src\misra04_02.c" line = "5" number = "584" desc = "Trigraph sequence (??<) detected [MISRA 2012 Rule 4.2, advisory]"/>
<issue file ="D:\Workspace\misra_rules_compliance_tests\src\misra20_03.c" line = "3" number = "12" desc = "Need < or " [MISRA 2012 Rule 20.3, required]"/>
<issue file ="D:\Workspace\misra_rules_compliance_tests\src\misra12_02.c" line = "8" number = "522" desc = "Highest operation, operator '<<', lacks side-effects [MISRA 2012 Rule 2.2, required]"/>
<issue file ="D:\Workspace\misra_rules_compliance_tests\src\misra12_02.c" line = "8" number = "522" desc = "Highest operation, operator '<<', lacks side-effects [MISRA 2012 Rule 2.2, required]"/>
</results>
```

As you can see in the desc part, the chevron (< or > ) is referenced in order to describe what's exactly wrong in my code.
The use of this chevron is not correct with xml extraction and is problematic for sonar-cxx integration.
I absolutely need to keep those issues on PC-Lint activated to be sure my code is compliant with MISRA C 2012.

Is there a solution to integrate those messages to sonar-cxx?

**Comment by guwirth** [comment]
@MarcAntoineCRUE your XML file must be 'valid'. Eaisiest is always to drag & drop it into a browser like Firefox to verify it.

Solutions:
* replace '<' with `&lt;`, '>' with `&gt;` and so one
* or use CDATA (https://en.wikipedia.org/wiki/CDATA)

**Comment by MarcAntoineCRUE** [comment]
Thanks for your quick answer.
And thanks for drag and drop in browser solution, it is really useful, I did not know it,

As the xml file is automatically generated using pclint, an could generate a large number of lines with this kind of error, finding each < or > which is not expected for XML file is not easy. When I'm using CDATA like in the following example the line is not taken in consideration by sonar cxx.
`<issue file ="D:\Workspace\misra_rules_compliance_tests\src\misra04_02.c" line = "5" number = "584" desc = <![CDATA["Trigraph sequence (??<) detected [MISRA 2012 Rule 4.2, advisory]"]]>/>`
Maybe I'm not doing it right, and maybe I should try to find how to remove this part of PC-Lint messages returns (If you know how to do it :) )

**Comment by guwirth** [comment]
@MarcAntoineCRUE I'm not a PC-Lint user so can' tell you how others are doing it? Maybe a newer version of the tool or a post analyse step fixing the XML?

**Comment by ametselaar** [comment]
The construct with CDATA cannot be used with attributes (name-value pairs
between < and >), therefore you'll need to replace < and > within
descriptions with &lt; and &gt;. It should be possible to do so
automatically using regular expressions.

2017-02-15 18:11 GMT+01:00 Günter Wirth <notifications@github.com>:

**Comment by guwirth** [comment]
@MarcAntoineCRUE: description is here https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers#pc-lint

**Comment by guwirth** [comment]
@MarcAntoineCRUE it depends a little bit what and how you wanna do it. You have two choices:
1. Add it over 'External' rules (other). You have to use `set sonar.cxx.other.rules` in WEB UI use `sonar.cxx.other.reportPath=reports/cxx-*.xml` for report files. Following this description for the XML formats: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis
2. Use `sonar.cxx.pclint.customRules`. Extend it with your rules. Use then `sonar.cxx.pclint.reportPath` to read your report creates as described here:  https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers#pc-lint. The PC-Lint sensor is doing an additional mapping (https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/pclint/CxxPCLintSensor.java#L133) for messages containing `MISRA 2004`,  `MISRA 2008`, `MISRA C++ 2008` or `MISRA C++ Rule` (https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/pclint/CxxPCLintSensor.java#L98). For some messages the message number is used, for some others the MISRA number M.x.y (https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/resources/pclint.xml).

In both cases the `key` has to match for rules and report file!
