### ISSUE TITLE
New custom rules not working

### ISSUE THREAD

**Issue by MarcAntoineCRUE** [SonarOpenCommunity/sonar-cxx#1057]
Hi,

I've tried to implement new rules in the program in order to have misra c 2012 reported in sonarqube.
In order to create rules matching with expected format I've used the template provided.
This permitted me to define some new rules like in attached file.
[sonarcxxPC-LintRulesMisraC2012.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/777797/sonarcxxPC-LintRulesMisraC2012.txt)
After addint thoses rules to the right quality profile, I'm loading the report file containing 
```
<?xml version="1.0" ?>
<results>
<issue file ="D:\Workspace\misra_rules_compliance_tests\src\misra02_06.c" line = "13" number = "438" desc = "Last value assigned to variable 'x' (defined at line 7) not used [MISRA 2012 Rule 2.2, required]"/>
<issue file ="D:\Workspace\misra_rules_compliance_tests\src\misra02_06.c" line = "11" number = "718" desc = "Symbol 'use_int16' undeclared, assumed to return int [MISRA 2012 Rule 17.3, mandatory]"/>
<issue file ="D:\Workspace\misra_rules_compliance_tests\src\misra02_06.c" line = "11" number = "746" desc = "call to function 'use_int16()' not made in the presence of a prototype"/>
<issue file ="D:\Workspace\misra_rules_compliance_tests\src\misra02_06.c" line = "14" number = "563" desc = "Label 'label1' (line 10) not referenced [MISRA 2012 Rule 2.6, advisory]"/>
<issue file ="D:\Workspace\misra_rules_compliance_tests\src\misra02_06.c" line = "10" number = "830" desc = "Location cited in prior message"/>
<issue file ="D:\Workspace\misra_rules_compliance_tests\src\misra02_06.c" line = "11" number = "526" desc = "Symbol 'use_int16()' (line 11, file D:\Workspace\misra_rules_compliance_tests\src\misra02_06.c) not defined"/>
<issue file ="D:\Workspace\misra_rules_compliance_tests\src\misra02_06.c" line = "11" number = "628" desc = "no argument information provided for function 'use_int16()' (line 11, file D:\Workspace\misra_rules_compliance_tests\src\misra02_06.c)"/>
<issue file ="D:\Workspace\misra_rules_compliance_tests\src\misra01_03.c" line = "1" number = "1923" desc = "macro '__DBL_MIN_EXP__' could become const variable [MISRA C++ Rule 16-2-2]"/>
</results>
```
The only rule which is issued is the last one (hopefully it's present in sonar cxx), could you help me with this error and maybe what should be done to have issue matching with a rule?

**Comment by guwirth** [comment]
@MarcAntoineCRUE please read this: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis
1. Create a new rule file, see https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/resources/pclint.xml for a sample
2. add it to other as descriped in wiki
3. restart server
4. activate rules in your profile
5. add pc-lint reports

If everything is working you can share file with us, we can add it to plugin.

**Comment by MarcAntoineCRUE** [comment]
To be sure it is corresponding to the template I already followed [https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/resources/pclint.xml](url)
As it is rules for PC-Lint I put it into PC-lint custom rules and I also tried to move the rules in External rules but nothing was working?
Sorry I'm a little bit lost.
I've restarted the server of course and activated everything and restarted the analysis of the project
Sonarqube said me I have 8 PC-Lint errors but it was not matching with the rules. 

I've probably misunderstood how to create the rules. Which part of the xml rule is used to match with the right error of the PC-Lint report? How the rule is identified with the PC-Lint report?

**Comment by guwirth** [comment]
@MarcAntoineCRUE 
1. Please add your rules to 'External rules' (other) and not 'PC-lint custom rules' otherwise you are overwriting the existing pc-lint rules.
2. restart server: do you see the new rules in the server UI?
3. did you add the rules to your profile and activated them?
4. analysing your project: are you using the right profile?
5. reading report: add something like 'sonar.cxx.other.reportPath=reports/pclint-*.xml' to your 'sonar-project.properties' to read your report file
6. running the analysis: sonar-scanner ...

In case of problems turn debug logging on to see what happens: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

> Which part of the xml rule is used to match with the right error of the PC-Lint report? How the rule is identified with the PC-Lint report?

The key in rules.xml and report.xml must match.

**Comment by MarcAntoineCRUE** [comment]
Ok new rules are now in External Rules, server is restarted, rules are present in the UI, assigned to a custom profile and working on the project.
For testing I'um using this line in my xml report :
`<issue file ="D:\Workspace\misra_rules_compliance_tests\src\misra01_03.c" line = "1" number = "1923" desc = "macro '__DBL_MIN_EXP__' could become const variable [MISRA C++ Rule 16-2-2]"/>`
When adding the correct pclint sonar cxx error this is perfectly matching, but not for the others.

Using the -X command make me realise than some text from one error is remapped 
`11:41:50.486 DEBUG: Remap MISRA rule 16-2-2 to key M16-2-2`
This is not happening with my others rules, so I suppose it need to be implemented in the file :
[https://github.com/SonarOpenCommunity/sonar-cxx/blob/985c0d7849dffe25eff00aa692bcbd4a1d972e63/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/pclint/CxxPCLintSensor.java](url)

So i need to do adjust to create an another remap function (with if statment) to match with my errors and after I need to build everything I suppose?

**Comment by MarcAntoineCRUE** [comment]
Ok now I got another problem, I don't know if it's better to open a new issue or post here.
I'm trying to build the project without any modification first, to be sure i'm doing it well, however I got a problem with Cxx :: Squid when "mvn clean install -X" as you can see on the following report line 4075
[report.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/780899/report.txt)

What's could be wrong in my build?

**Comment by guwirth** [comment]
@MarcAntoineCRUE 

> Using the -X command make me realise than some text from one error is remapped
11:41:50.486 DEBUG: Remap MISRA rule 16-2-2 to key M16-2-2

You can decide if you want to use the `number`or like to remap it to a MISRA rule.
