### ISSUE TITLE
Third party library files producing warnings

### ISSUE THREAD

**Issue by chunter2** [SonarOpenCommunity/sonar-cxx#1059]
It seems like if there are warnings in the build.log file generated from a Visual Studio compile log or in the cppcheck results file that point to third party library files that are part of the sonar.cxx.includeDirectories but not part of the sonar.sources I get the following error.  This is an example of the build.log file.  

[INFO] Scanner found '1' report files
[INFO] Parser will parse '1' report files
[INFO] Processing report 'build.log'
[INFO] Scanner 'Visual C++' initialized with report 'build.log', CharSet= 'UTF-8'
[INFO] Parsing 'Visual C++' format (UTF-8)
[INFO] Using pattern : '^(.*)\((\d+)\):\x20warning\x20(C\d+):\x20(.*)$'
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[WARNING] Cannot find the file 'library include.h', skipping violations
[INFO] C++ compiler Warnings processed = 0
[INFO] Sensor CxxCompilerSensor (done) | time=156ms

If I add the third party library files as part of the sonar.sources I get the following but the plugin also tries to process the third party library files as well.  

[INFO] Scanner found '1' report files
[INFO] Parser will parse '1' report files
[INFO] Processing report 'build.log'
[INFO] Scanner 'Visual C++' initialized with report 'build.log', CharSet= 'UTF-8'
[INFO] Parsing 'Visual C++' format (UTF-8)
[INFO] Using pattern : '^(.*)\((\d+)\):\x20warning\x20(C\d+):\x20(.*)$'
[INFO] C++ compiler Warnings processed = 36
[INFO] Sensor CxxCompilerSensor (done) | time=62ms

Is there a way to get the second output without adding the third party library files to the sonar.sources?  If this doesn't make sense and I need to provide more information, let me know.  

Thanks

**Comment by jmecosta** [comment]
No you can only raise issues against files imported into sonar.  This is a
expected behavior
