### ISSUE TITLE
VS compiler warnings are detected but aren't listed in Sonar label:question

### ISSUE THREAD

**Issue by pjwhams** [SonarOpenCommunity/sonar-cxx#1066]
I've been trying to get Sonar-scanner to report all the errors found in my Visual Studio 2015 build. I'm using parallel builds (msbuild /m) and I've used a suitable regex (tweaked from the one mentioned in the docs). The regex and sample parsing of some warnings shown here: https://regex101.com/r/RboXwX/2

In SonarQube, in the All Measures / C++ Compiler warning section it correctly lists the number of warnings, but the List and Tree sections are empty: 'No results - 0 out of 0 shown'.

The sonar-scanner log appears to show that it has parsed the warnings correctly:

    09:41:12.834 DEBUG: Scanner-matches file='d:\source\devdorico\steam\source\core\util\stringnumberconverter.h' line='47' id='C6031' msg=Return value ignored: 'snprintf'.
    09:41:12.834 DEBUG: Scanner-matches file='d:\source\devdorico\steam\source\core\util\stringnumberconverter.h' line='65' id='C6031' msg=Return value ignored: 'snprintf'.
    09:41:12.834 DEBUG: Scanner-matches file='d:\source\devdorico\boost\geometry\geometries\concepts\point_concept.hpp' line='114' id='C6011' msg=Dereferencing NULL pointer 'p'. 
    ...
    09:41:12.941 DEBUG: C++ compiler Warnings processed = 7
    09:41:12.941 INFO: C++ compiler Warnings processed = 7
    09:41:12.941 INFO: Sensor CxxCompilerSensor (done) | time=109ms

But it doesn't show any further errors. Is there anything else that I need to do to make the warnings visible in SonarQube?

**Comment by jmecosta** [comment]
are the compiler rules enabled in the quality profile you are using for this project?

**Comment by pjwhams** [comment]
I _think_ so. I've created a new Quality Profile copied from the default 'sonar way', clicked 'activate more' rules, and in the Quality Profile section on the left panel, the c++ rules are showing as 'active'.  Do the rules for VS need to be explicitly added somehow?

**Comment by jmecosta** [comment]
![image](https://cloud.githubusercontent.com/assets/1041352/23257897/7063a0c6-f9ce-11e6-8407-d53a88b246eb.png)

how many of the vc compiler rules do you have in this profike? for example i have 700 rules for the compiler enabled.

if you have those enable, i suggest you check if the ids that are in the log are found in the rules, for example from my instance i can see C6031 is there andthat one is in your log

**Comment by pjwhams** [comment]
Ah thanks, I didn't know the rules had to be enabled there (couldn't find any mention of that in the docs).  Ok, so after enabling the compiler-VC++ rules I'm now getting these showing up in the Issues list as Code Smells.  They're not showing up in the Measures tab though. Maybe they aren't supposed to?

The analysis results are showing up in the Issues list now though, so that's what I needed. Thanks!

**Comment by jmecosta** [comment]
The measures tab is not there, I think there is another issue open to
provide those for files. Since each measure needs to be saved per file and
that we don't have atm
