### ISSUE TITLE
Support for a new sensor Bauhaus Axivion Stylchecker

### ISSUE THREAD

**Issue by stefanweiser** [SonarOpenCommunity/sonar-cxx#1077]
This would be a great benefit, because it enables sonar-cxx and SonarQube (great user interface) to get used in safety critical Projects e.g. in automotive or medical. The main reason for this is, that Axivion lacks a "usable" user Interface.

The Stylechecker tool will output a XML file, which could get read by sonar-cxx. I have access to Axivion and would implement, test and use that sensor.

Open for questions.

**Comment by guwirth** [comment]
@stefanweiser some questions to 'Bauhaus Axivion Stylchecker'
* Is it open source / for free or a commercial tool?
* Is the tool for C++ only or also for other languages?
* If there is an XML output: why not using our `external/other` sensor (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis#usage-of-unsupported-code-checkers)?

**Comment by jmecosta** [comment]
@guwirth i think you put it really nicely, perhaps something in wiki about what is good to be in sensor and what is good to be provided as external sensor.

**Comment by stefanweiser** [comment]
1. Is it important to you, that its open source?
2. It does support C and C++.
3. It outputs XML, but not in a external sensor compatible format.

**Comment by jmecosta** [comment]
1. the question about if its oss or not comes after this particular sensor is merged. For example imagine if you leave the company you are working. There are many possibilities that no one will be able to maitain the  rule set for the new sensor. if its oss and readily available its less likely that this will be unmaintained. 

3.  its likely less work for you to create the xml converter, for example there are many tools that can help with that http://www.freeformatter.com/xsl-transformer.html. 

im more than happy to increase the ammount of external tools that can be imported, see https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis#resources ive have there cpplint and that is open source and its not a big deal to have it there

**Comment by stefanweiser** [comment]
1. We are users of the tool and I would like to add ability for Sonarqube, because the dashboard software they deliver is a bit "old school". If we would support that here, then we would ensure, that there would be replacement developer.
2. An converter tool would add a dependency to building a project (propably a main disadvantage of the external sensor feature) and some projects are on windows here, where such dependency management is just pain...

**Comment by jmecosta** [comment]
1. things change. you might even replace the tool etc. 
2. what about allow the external sensor the define a transformation script for this kind of cases: http://stackoverflow.com/questions/4604497/xslt-processing-with-java then you would code the xsl only and the external sensor will convert and import?

**Comment by stefanweiser** [comment]
2. Does the external sensor support this kind of convert and import?

**Comment by jmecosta** [comment]
nop but it would be a nice addition :) i supose from the issue you would be willing to contribute with the implementation?

**Comment by stefanweiser** [comment]
Guess, that then a property sonar.cxx.other.transformXsltScript is needed. I'm willing to start an experiment on that...

**Comment by jmecosta** [comment]
yes thanks, that would be a great addition

**Comment by guwirth** [comment]
Hi @stefanweiser 
>  Is it important to you, that its open source?

It depends. Sometimes the license conditions do not allow to add/copy the rules. Another point is that in case of a commercial tool would be better the tool producer would do it.

> It does support C and C++.

Looking on their homepage they are supporting Ada, C, C++, C# and Java. So I think would be better to create a 'Axivion Bauhaus' plugin and not add it to our plugin only (https://www.axivion.com/en).

> It outputs XML, but not in a external sensor compatible format. Propably it would be possible to convert it.

Like the idea of adding a xslt transformation to our tool as a 'pre-analyze' step. Will add an enhancement request.

Regards,

**Comment by jmecosta** [comment]
#1080

**Comment by stefanweiser** [comment]
@guwirth: Actually they also have some kind of webserver in its product, but I can attest it a very crappy user experience. No technical debt analysis, no issue tracking or user assignment. Well, yes, I could write an own plugin, but this would be an overkill, because there is a nice plugin like that. I worked with your plugin at my previous employer. I was very impressed what is possible.

I'll go for the xslt tranformation issue, but I need some time to test it well.

**Comment by guwirth** [comment]
@stefanweiser if you provide an solution please have also a look to #1080. Because the other/XML sensor can be used for different tools it's important that we can execute more then one XSLT. (tool1 using XSLT1, tool2 using XSLT2, ...)

**Comment by guwirth** [comment]
No direct support do #1080 instead.
