### ISSUE TITLE
Add an XSLT pre-analyse step

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1080]
Hi,

would be useful to have an build-in XSLT transformation converting XML files to the format needed by our plugin.
* the XSLT transformation should be executed prior to any other steps
* should support more then one transformation for the case different inputs should be supported
* should support source and output with placeholder in the name

Sample:
```
sonar.cxx.xslt.1.stylesheet=MyStylesheets1.xslt
sonar.cxx.xslt.1.source=tool1/reports/xxx-*.xml
sonar.cxx.xslt.1.output=reports/other-tool1-*.xml

sonar.cxx.xslt.2.stylesheet=MyStylesheets2.xslt
sonar.cxx.xslt.2.source=tool2/reports/xxx-*.xml
sonar.cxx.xslt.2.output=reports/other-tool2-*.xml
```
What are you thinking?

Regards,

**Comment by jmecosta** [comment]
this applies to the external sensor right? @stefanweiser please look at @guwirth suggestion. i think its good approach
