### ISSUE TITLE
How to use Google Test XML report

### ISSUE THREAD

**Issue by MattSom** [SonarOpenCommunity/sonar-cxx#1097]
Hi, the documentation only says :

> Googletest is a C++ testing framework written by Google. To create XUnit compatible output use it this way:
> `<test executable> --gtest_output=xml:<filename>`

But how can I use the XML by SonarQube?

**Comment by guwirth** [comment]
@MattSom you have to use the Xunit sensor to read the generated report.
For a sample see https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/googletest_project

**Comment by Warchant** [comment]
@guwirth I reviewed `googletest_project` and did not find  `xunit-report.xml` in `build` folder. How to generate it?
`make` does not generate xml report.

**Comment by guwirth** [comment]
@MattSom the plugin is not creating the reports. You have to run the tests to create the reports by your own.  https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Test-runners

**Comment by Surendranath99** [comment]
How to generate xml report for google test output in visual studio 2019?

**Comment by guwirth** [comment]
> How to generate xml report for google test output in visual studio 2019?

Hi @Surendranath99,

think that is the wrong community to ask. Maybe you better ask in a VisualStudio or Google Test community.

Regards,

**Comment by Surendranath99** [comment]
Thank you @guwirth

**Comment by Warchant** [comment]
Run any test with flag and see `xunit.xml` in current dir
```
./test --gtest_output=xml:xunit.xml
```

**Comment by Surendranath99** [comment]
Hi Bohdan,

I don't know how to set up that flag because I'm new to this google test
and generate the xml report in visual studio 2019.

Thanks and regards,
Surendranath.
