### ISSUE TITLE
US: Continuous Code Quality as a Service for cxx-plugin

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1107]
SonarSource provides SonarQube.com for open source projects, free of charge. 
https://about.sonarqube.com/get-started/

@jmecosta maybe we can add this to AppVeyor. Think is easier as Travis because with Travis we are checking different versions in parallel and with AppVeyor only one.

**Comment by jmecosta** [comment]
@guwirth does not look that it works:

INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: Insufficient privileges
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
Command exited with code 1

you can login however to upload results it gives insufficient privileges. Or are you perhaps refering to this plugin: https://docs.sonarqube.org/display/PLUG/GitHub+Plugin

**Comment by jmecosta** [comment]
@guwirth after a bit more diffing, seems appveyour does not work really well with. http://laedit.net/2016/09/29/integrate-sonarqube-in-a-dotnet-project-with-appveyor.html in principle the only way this would work is if all pull requests are created from the main repository. not sure if travis provides different way of handling secure tokens, but appveyour does not allow those for our workflow.

**Comment by SonarOpenCommunityAdmin** [comment]
@all: First version is here available. Update is triggered with every AppVeyor build of master.
https://sonarcloud.io/organizations/sonaropencommunity/projects

**Comment by Bertk** [comment]
@guwirth Perfect :smiley: but is it possible to customize the quality profile? I have one which I use since years and add new rules whenever the SQ Java plugin is updated.
[java-my-java-profile-69454.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/1393561/java-my-java-profile-69454.zip)

**Comment by guwirth** [comment]
@Bertk at the moment the default "Sonar way" ruleset and quality gate is used. This has the advantage that we are using always the latest rules coming with the plugins without any effort.

What is different/better using your ruleset?

By the way: Do you know how to create coverage data with Maven? That's currently missing...

**Comment by Bertk** [comment]
@guwirth Please use 
```
mvn org.jacoco:jacoco-maven-plugin:prepare-agent clean install -Pcoverage-per-test
mvn sonar:sonar
```
 to add the code coverage data.
You can declare a parent of the active, customized quality profile and therfore all new active rules from sonar way will be available.
![parent](https://user-images.githubusercontent.com/2315215/31790121-b076a076-b514-11e7-819b-08d61cf58331.PNG)

**Comment by guwirth** [comment]
> add the code coverage data.

@Bertk thx, we have now also coverage: https://sonarcloud.io/organizations/sonaropencommunity/projects

> You can declare a parent of the active, customized quality profile and therfore all new active rules from sonar way will be available.

The question was: what is different/better using your ruleset? :-)
The advantage of the default one is that there is no maintenance effort. We have always the latests one...

**Comment by Bertk** [comment]
@guwirth my Java quality profile uses more rules e.g. findbug rules are activates. An analysis will show of course more issues (my fork has: 46 bugs, 65 vulnerabilities and 3.6k code smells).
Sonar way:
![sonarway-rules](https://user-images.githubusercontent.com/2315215/31848934-f9f94f6a-b63a-11e7-829d-0fb4161252d1.PNG)
my Java quality :
![my-java-profile](https://user-images.githubusercontent.com/2315215/31848935-fcc5192c-b63a-11e7-9285-346d009381e3.PNG)

**Comment by guwirth** [comment]
@Bertk on SonarCloud are only the repositories SonarAnalyzer Java & Common Java Java available.

**Comment by Bertk** [comment]
@guwirth Yes, this is correct but some additional rules from repositories **_Common Java_** and **_SonarAnalyzer_** can be added e.g. squid:S2699 (see #1263)

**Comment by guwirth** [comment]
@Bertk please try to login on https://sonarcloud.io/ with your github account. I tried to add you to the group.

**Comment by Bertk** [comment]
@guwirth I created a Java profile [SonarOpenCommunity way](https://sonarcloud.io/organizations/sonaropencommunity/quality_profiles/show?language=java&name=SonarOpenCommunity+way). 
Please review and set it as default Java profile.

**Comment by guwirth** [comment]
> @guwirth I created a Java profile SonarOpenCommunity way. Please review and set it as default Java profile.

@Bertk is ok for me thx. Is default now.

**Comment by Bertk** [comment]
@guwirth Looks great. The only missing step is the analysis for the PRs with the [GitHub plugin](https://docs.sonarqube.org/display/PLUG/GitHub+Plugin) :relaxed:

**Comment by guwirth** [comment]
@Bertk do you know how PR support is working? Is there somewhere a description for Github integration?

**Comment by Bertk** [comment]
@guwirth I do not have experiance with this but read the description for the GitHub plugin. I think the challange will be the techn. user GitHub account with limited access.
 
_Given the GitHub plugin is available on [SonarCloud](https://sonarcloud.io/organizations/sonaropencommunity/projects)
And the correct configuration for the scanner is used
And the technical user has commit rights (GitHub)
When  the analysis (in previewmode) is successful
Then the analysis results will be shown in the PR review summary section_

```
sonar-scanner -Dsonar.analysis.mode=preview \
              -Dsonar.github.pullRequest=$PULL_REQUEST_ID \
              -Dsonar.github.repository=myOrganisation/myProject \
              -Dsonar.github.oauth=$GITHUB_ACCESS_TOKEN \
              -Dsonar.host.url=https://server/sonarqube \
              -Dsonar.login=$SONARQUBE_ACCESS_TOKEN
```

**Comment by Bertk** [comment]
There is also a example for travis (https://github.com/SonarSource/sonarqube/blob/master/travis.sh)
but unfortunatly not for appveyor :unamused:
```
  elif [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ -n "${GITHUB_TOKEN:-}" ]; then
    echo 'Build and analyze internal pull request'

    mvn org.jacoco:jacoco-maven-plugin:prepare-agent deploy \
        $MAVEN_ARGS \
        -Dsource.skip=true \
        -Pdeploy-sonarsource

    # analysis to decorate GitHub pull request
    # (need support of standard analysis mode in GH plugin)

    mvn sonar:sonar \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.analysis.mode=preview \
        -Dsonar.github.pullRequest=$TRAVIS_PULL_REQUEST \
        -Dsonar.github.repository=$TRAVIS_REPO_SLUG \
        -Dsonar.github.oauth=$GITHUB_TOKEN

    mvn sonar:sonar \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.branch.name=$TRAVIS_PULL_REQUEST_BRANCH \
        -Dsonar.branch.target=$TRAVIS_BRANCH \
        -Dsonar.analysis.buildNumber=$TRAVIS_BUILD_NUMBER \
        -Dsonar.analysis.pipeline=$TRAVIS_BUILD_NUMBER \
        -Dsonar.analysis.sha1=$TRAVIS_PULL_REQUEST_SHA \
        -Dsonar.analysis.prNumber=$TRAVIS_PULL_REQUEST \
        -Dsonar.analysis.repository=$TRAVIS_REPO_SLUG
```

**Comment by guwirth** [comment]
Travis https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
AppVeyor https://www.appveyor.com/docs/environment-variables/

**Comment by Bertk** [comment]
The PR failed and I do not know how to create a functional GitHub account :unamused: 
```
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:
3.3.0.603:sonar (default-cli) on project cxx: Failed to execute project builder:
org.sonar.plugins.github.PullRequestProjectBuilder: Unable to perform GitHub WS operation: 
Server returned HTTP response code: 401, message:
'Unauthorized' for URL: https://api.github.com/user
```

**Comment by Bertk** [comment]
@guwirth Please remove the secrets from the appveyor.yml file and **create new secrets** in a 
[secure file](https://www.appveyor.com/docs/how-to/secure-files/) with the appropriate permissions.

> However, secure variables are not decoded during Pull Request builds which prevents someone from submitting PR with malicious build script displaying those variables. In more controlled environment through with a trusted team and private GitHub repositories there is an option on General tab of project settings to allow secure variables for PRs.

**Comment by guwirth** [comment]
> ... remove the secrets from the appveyor.yml f

@Bertk what's wrong with this? It is  encrypted configuration data?

From description: This form allows you to encrypt sensitive data before saving it into appveyor.yml file. Secure strings are currently supported in environment, deploy and notifications sections.

**Comment by Bertk** [comment]
@guwirth There is nothing wrong but it does not work for the PRs and the appveyor.yml should be write protected.

https://www.appveyor.com/docs/build-configuration/#secure-variables
> However, **secure variables are not decoded during Pull Request builds** which prevents someone from submitting _PR with malicious build script displaying those variables_. In more controlled environment through with a trusted team and private GitHub repositories there is an option on General tab of project settings to allow secure variables for PRs.

**Comment by guwirth** [comment]
@Bertk 

> create new secrets in a secure file with the appropriate permissions.

Think there is the same problem, docu is saying: Note that file won’t be decrypted on Pull Request builds as secure variables are not set during PR build.

**Comment by Bertk** [comment]
@guwirth, @jmecosta  Thank you for this hints. The analysis of PR fails because the AppVeyor configuration does not use the secrets for the PR yet. Who can update this configuration for the Community plug-in AppVeyor build script?

> **Allowing Secure Variables in Pull Requests**
> Normally AppVeyor will not decrypt secure variables in Pull Requests, as in this case a Hacker could send you a PR and then read all of your secure data. However, for SonarQube to analyze Pull Requests, it is necessary. You need to decide whether you can live with this.
> If you can, go to AppVeyor, click on your project, click “Settings”, tick “Enable secure variables in Pull Requests from the same repository only” and click “Save”.

**Comment by guwirth** [comment]
@Bertk please try again

**Comment by Bertk** [comment]
@guwirth The analysis of PR is still not working but we need this PR feature and we should have zero bugs/vulnerbilities :wink:
![bugs](https://user-images.githubusercontent.com/2315215/32806551-2e5c27b8-c98d-11e7-8a6d-2d2b210d9ae9.PNG)

**Comment by guwirth** [comment]
PR supports seems currently not possible?

**Comment by guwirth** [comment]
Basic support in SonarCloud available. PRs are not supported yet.
