### ISSUE TITLE
Support request: flawfinder

### ISSUE THREAD

**Issue by mehmetcodes** [SonarOpenCommunity/sonar-cxx#1115]
Somewhat unique tool that seeks vulns for C++

https://www.dwheeler.com/flawfinder/

Please consider integration.  Also would be good to know how I might be able to develop a tool to integrate it within C++ community edition

**Comment by jmecosta** [comment]
@mehmetcodes you can use https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis#usage-of-unsupported-code-checkers to support this tool.

you need to generate a xml report that complies with the required format and create a rule set for the tool. After that it should work

**Comment by mehmetcodes** [comment]
@david-a-wheeler Can you help with this?  I would love flawfinder in SonarQube

**Comment by kumbasar** [comment]
@mehmetcodes checkout this: https://github.com/arthepsy/sonar-tools
