### ISSUE TITLE
What metrics does sonar-cxx support?

### ISSUE THREAD

**Issue by fkromer** [SonarOpenCommunity/sonar-cxx#1116]
What metrics does sonar-cxx provide out-of-the-box? What metrics can be added using additional sensors?

A quick search for "metrics" in the issues lead to:

- [complexity in classes](https://github.com/SonarOpenCommunity/sonar-cxx/pull/788) (but how is this metric calculated from basic metrics like efferent coupling, etc. ?)
- [complexity in functions](https://github.com/SonarOpenCommunity/sonar-cxx/pull/788) (but how is this metric calculated from basic metrics like cyclometric dependency, etc. ?)
- [McCabe complexity of functions](https://github.com/SonarOpenCommunity/sonar-cxx/pull/397)
- [cyclic dependencies in header files](https://github.com/SonarOpenCommunity/sonar-cxx/issues/559)
- [technical debt](https://github.com/SonarOpenCommunity/sonar-cxx/issues/464) (but how is this metric calculated from basic metrics?)

**Comment by jmecosta** [comment]
all metrics are calculated according with guidelines set by the Core, for complexity see https://blog.sonarsource.com/discussing-cyclomatic-complexity/ 

technical debt is also part of internal model of sonar, we only categorize the rules and give them a value of debt. After that the core takes care to do all the calculations. So you need to check in google groups if you want a more precise answer.

cycle dependcies and provided by means of issues, so when cycles are detect between multiple files issues are created there.

**Comment by fkromer** [comment]
> all metrics are calculated according with guidelines set by the Core, for complexity see https://blog.sonarsource.com/discussing-cyclomatic-complexity/

They mention just cyclomatic complexity in the hyperlink which is a critical metric for sure. But I am interested in all metrics on method/function and class/component level which impact the production code testability. On the method level I consider the afferent/efferent coupling, # of parameters, etc. important as well (like [provided on the method level by some non-free tools like CppDepend](http://cppdepend.com/Metrics#MetricsOnMethods) ).

> technical debt is also part of internal model of sonar, we only categorize the rules and give them a value of debt. After that the core takes care to do all the calculations. So you need to check in google groups if you want a more precise answer.

Thanks for the hint. (I consider the weighting of single metrics for the calculation of the technical debt not that important. But I am interested in which metrics are included in the calculation at all.)

> cycle dependcies and provided by means of issues, so when cycles are detect between multiple files issues are created there.

Great to have this application/project level measure as well...

**Comment by jmecosta** [comment]
It seems to me then sonar is not the tool you are looking for, their
central model is to use technical debt as means of issues.  In past they
have been more open to have such metrics available but removed.  Cppdepend
as you see in website is not relevant to new versions of sonar  6.3. The
features there are all for really old version, unless they develop their
own visualizers I'm a afraid sonar will not provide what you are after.
But feel free to contact the cppdend guys, maybe they are working on
support of 6.3
