### ISSUE TITLE
Which visual dependency represenations are supported?

### ISSUE THREAD

**Issue by fkromer** [SonarOpenCommunity/sonar-cxx#1117]
[Dependency Structure Matrix (DSM)](https://github.com/SonarOpenCommunity/sonar-cxx/issues/509) seem to be suppoorted. Are also other representations like [Conceptual Architecture Diagram (CAD)](http://lattix.com/dependency-structure-matrix) supported?

**Comment by jmecosta** [comment]
DSM is supported only at issue level, so dont expect any fancy graph in Sonar ui. Those have been removed some time ago by people developing the core of Sonar.

in the cxx plugin we dont provide any means of displaying diagrams.

**Comment by guwirth** [comment]
@fkromer maybe you can also have a look here http://www.cppdepend.com/sonarplugin

**Comment by fkromer** [comment]
@jmecosta 
> DSM is supported only at issue level, so dont expect any fancy graph in Sonar ui. Those have been removed some time ago by people developing the core of Sonar.

What a pity!

@guwirth That would be one of my favorite alternatives but it is always about money 😉
