### ISSUE TITLE
Parsing gcc output from autotools-based project

### ISSUE THREAD

**Issue by kguilbert** [SonarOpenCommunity/sonar-cxx#1119]
I have a project with source files organized into a number of subdirectories off 'src', e.g. 'src/foo/', 'src/bar/', 'src/baz/xyz' and it's built using the autotools toolchain using g++. When g++ generates warnings (which I capture to a gcc.log), the file name it prints is relative to the current directory, since GNU make does its 'make: Entering directory 'src/baz/xyz' thing.

The result is that the sonar-cxx plugin can't find the files containing compiler warnings generated by g++. The scanner log says "WARN: Cannot find the file '<incorrect path here>', skipping violations" for each of these files. It's looking for those files in the project root directory, presumably because it doesn't know about the make changing the working directory.

Is there some workaround for this?

**Comment by guwirth** [comment]
@kguilbert please have a look here https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers

**Comment by kguilbert** [comment]
@guwirth Thank you, I have read that page but I didn't find an answer. I see you added this to the 0.9.8 milestone; does that mean you'll consider it as a new feature?

**Comment by guwirth** [comment]
@kguilbert no should also work with older version. I'm not familiar with g++ but I think there must be an option to create absolute paths for the reports/log file.

**Comment by guwirth** [comment]
@kguilbert please reopen if still an issue. In case you found a solution you are welcome to update our wiki.

**Comment by fukanchik** [comment]
@kguilbert have you found the solution for this problem?
