### ISSUE TITLE
Sonar Qube AstScanner parser error in Apex class

### ISSUE THREAD

**Issue by NazareenaS** [SonarOpenCommunity/sonar-cxx#1151]
Sonar Qube AstScanner parser error in Apex class

While running sonar-runner in Apex class I am getting below error.

ERROR: Unable to parse file: .....cls
ERROR: Parse error at line 20 column 105:

   18: == 0){
   19:   }
  -->    List<List<SObject>> searchList = [FIND 'SFDC' IN ALL FIELDS RETURNING Account(Name), Contact(FirstName)];
   21: 
   22:  }
   23: 
   24: }EOF
   22:  }
   23: 

Request help to solve this error basically whenever we have SOSL in the apex class, it throws the above error

**Comment by guwirth** [comment]
@NazareenaS think you are in the wrong user group. This group is about C++ not Apex, try it here https://www.sonarqube.org/community/.
