### ISSUE TITLE
SonarQube : Bugs & Vulnerabilities 0 Code Smells 0

### ISSUE THREAD

**Issue by djihan** [SonarOpenCommunity/sonar-cxx#1152]
I use SonarQube 6.0, with the plugin sonar-cxx-plugin 0.9.7 and sonar-scanner 2.8, but when I execute it only the information about numbers of lines and duplication. Bugs and Vulnerabilities and code smells is 0. I modified rules bu default used to include MISRA rules (this profile is used well)

I execute sonar by the following command :
`sonar-scanner -e -Dsonar.host.url=XXX -Dsonar.language=c++ -Dsonar.sources=./ -Dsonar.projectKey=YYY -Dsonar.projectName=TEST`

I cannot copy the log of the execution, but in here is the information which seem to me the most important (if ever is needed more detail I shall indicate you what you wish to see)
`main.c:1] cannot find the source for "#include <iostream>"
undefined report path 'sonar.cxx.rats.reportPath'
undefined report path 'sonar.cxx.cppcheck.reportPath'
undefined report path 'sonar.cxx.pclint.reportPath'
undefined report path 'sonar.cxx.drmemory.reportPath'
undefined report path 'sonar.cxx.compiler.reportPath'
undefined report path 'sonar.cxx.veron.reportPath'
undefined report path 'sonar.cxx.valgrind.reportPath'
Analysis Success`

As to indicate apparently the analysis is takes place without error, however I always have 0 for Bugs Vulnerabilities and Code Smells in 0.

Would know you how I can adjust it concerns please? Thank you.

**Comment by jmecosta** [comment]
hi

please check the wiki: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-the-analysis there are detailed instructions on how to start using the plugin.

``` quote
The C++ Community plugin won't execute neither test runners nor coverage tracers nor static checkers itself. All this data has to be provided in form of reports. See Running tools.```

**Comment by djihan** [comment]
Hahaha OK, so I have just needed to configure the cppcheckreportpath to obtain the results of MISRA's rules?

**Comment by jmecosta** [comment]
if you have the reports yes.

**Comment by djihan** [comment]
All reports are empty I think I need to configure rules to include MISRA's rules

**Comment by jmecosta** [comment]
you need to check the documentation of the cppcheck, report generation we dont document from our side.  once you get a report from cppcheck with issues then they should be imported into sonar. but from our side we cant do much to help you.

**Comment by djihan** [comment]
OK thank you for your help :-)

**Comment by jmecosta** [comment]
No prob
