### ISSUE TITLE
CxxCoverageSensor not able to get the covergae property sonar.cxx.coverage.reportPath

### ISSUE THREAD

**Issue by jlanchares** [SonarOpenCommunity/sonar-cxx#1156]
Using plugin sonar-cxx 0.9.7 with SonarQube Version 6.3 (build 19869), I was not able to get the coverage in the SonarQube. It just show 0% all time. Same configuration with same xml file generated with gcov/gcovr shows a valid coverage % in SonarQube Version 4.5.7. 

The configuration is:

```
# we want this set explicitly
sonar.cxx.coverage.forceZeroCoverage=True

# paths to the reports
sonar.cxx.coverage.reportPath=/sonar/coverage.xml
sonar.cxx.xunit.reportPath=sonar/xunit-reports/xunit-reports.xml
sonar.cxx.xunit.provideDetails=True
sonar.cxx.cppcheck.reportPath=sonar/cppcheck-report.xml
sonar.cxx.rats.reportPath=sonar/rats-report.xml
```

And the log from SonarQube 6.3 says (See the part related to CxxCoverageSensor):

```
00:06:54.131 17:02:02.805 INFO: Sensor CxxRatsSensor [cxx] (done) | time=1145ms
00:06:54.131 17:02:02.805 INFO: Sensor CxxXunitSensor [cxx]
00:06:54.131 17:02:02.805 DEBUG: Runs unit test import sensor only at top level project skip : Module Key = 'king:phoenix-toolbelt-sonar:phoenix-social-facebook'
00:06:54.131 17:02:02.805 INFO: Sensor CxxXunitSensor [cxx] (done) | time=0ms

00:06:54.131 17:02:02.805 INFO: Sensor CxxCoverageSensor [cxx]
00:06:54.131 17:02:02.805 INFO: Searching reports by relative path with basedir '/workspace/toolbelt_osx_sonar/mobile' and search prop ''
00:06:54.131 17:02:02.805 INFO: Undefined report path value for key ''
00:06:54.131 17:02:02.805 INFO: Issues processed = 0
00:06:54.131 17:02:02.805 INFO: Sensor CxxCoverageSensor [cxx] (done) | time=0ms

00:06:54.131 17:02:02.805 INFO: Sensor CxxCppCheckSensor [cxx]
00:06:54.131 17:02:02.805 INFO: Searching reports by relative path with basedir '/workspace/toolbelt_osx_sonar/mobile' and search prop 'sonar.cxx.cppcheck.reportPath'
00:06:54.131 17:02:02.805 DEBUG: Normalized report includes to '[/workspace/toolbelt_osx_sonar/mobile/sonar/cppcheck-report.xml]'
00:06:54.131 17:02:02.806 INFO: Scanner found '1' report files
00:06:54.131 17:02:02.806 INFO: Parser will parse '1' report files
00:06:54.131 17:02:02.806 INFO: Processing report '/workspace/toolbelt_osx_sonar/mobile/sonar/cppcheck-report.xml'
00:06:54.131 17:02:02.806 DEBUG: Parsing 'Cppcheck V2' format
00:06:54.131 17:02:02.807 DEBUG: Parsing 'Cppcheck V1' format
```

While other properties as cppcheck are found and executed, the one from the coverage is not found and is not processed.

Any idea about this?

**Comment by guwirth** [comment]
@jlanchares please have a look to https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-Instructions and https://github.com/SonarOpenCommunity/sonar-cxx/releases to see if they were any changes.

**Comment by jlanchares** [comment]
Thnak you @guwirth. I know that 0,9,7 is compatible with SonarQube 6.2 and that 6.3 is not in the list until 0.9.8. We were testing moving to a new SonarQube version I everything looks like working fine except the Coverage and I was not able to configure it. I read the notes and I removed the 
sonar.cxx.coverage.itReportPath and sonar.cxx.coverage.overallReportPath because they are not mor supported and left just the sonar.cxx.coverage.reportPath as our overall, but it looks like in the SonarQube 6.3, it is not working as expected. Just asking to know if someone was having the same issue.

**Comment by guwirth** [comment]
@jlanchares 

`00:06:54.131 17:02:02.805 INFO: Undefined report path value for key ''`

Why is there a backslash at the beginning?

`sonar.cxx.coverage.reportPath=/sonar/coverage.xml`

**Comment by jlanchares** [comment]
@guwirth, The real one is sonar.cxx.coverage.reportPath=sonar/coverage.xml... the one on the comment is not just a copy/paste edited by me. The one failing is 

`sonar.cxx.coverage.reportPath=sonar/coverage.xml.`

Thank you.

**Comment by guwirth** [comment]
@jlanchares sorry no ideas. Maybe have a look to our integration test sample https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/coverage_project

**Comment by tegoo** [comment]
I have faced exectly the same issue.

**Comment by tegoo** [comment]
Seems the problem is in CxxCoverageSensor class - it doesn't override method for getting report path.

**Comment by guwirth** [comment]
Hi, please
* turn debug info on and try again https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information
* read this, maybe a path issue https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues
* on Windows use a tool like SysInterals ProcessMonitor to see where the scanner tries to read your file https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx

Regards

**Comment by guwirth** [comment]
@tegoo which method in which class do you mean? Where is the base method defined? Can you point to the code please.

**Comment by guwirth** [comment]
@jlanchares should be fixed, please test again with latest snapshot.

**Comment by jlanchares** [comment]
Ok, I will try. Thank you!

**Comment by vincentjourdon** [comment]
Hello, 
I used 0.9.7 with a sonarqube 5.6.6. As I had the same issue I have tested last snapshot as you suggested. But there is still a problem. Now I have
```
INFO: Searching coverage reports by path with basedir '/var/lib/jenkins/workspace/test-dev_TEST_SONARQUBE' and search prop 'sonar.cxx.coverage.reportPath'
INFO: Searching for coverage reports '[]'
INFO: Coverage BaseDir '/var/lib/jenkins/workspace/test-dev_TEST_SONARQUBE' 
```
And no coverage in sonarqube

I have configured sonar.properties with 
`sonar.cxx.coverage.reportPath=gcov.xml`

Any idea ?
Vincent

**Comment by jlanchares** [comment]
Hi @guwirth, are you thinking to launch the fix in a release to download?. Last time I downloaded the last release and the fix is in master I think.

**Comment by guwirth** [comment]
Hi @jlanchares you will find latest build artefacts always here:
* https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

Regards,

**Comment by jlanchares** [comment]
Thank you @guwirth !
