### ISSUE TITLE
not being able to import correctly my reports

### ISSUE THREAD

**Issue by vpereira** [SonarOpenCommunity/sonar-cxx#1159]
Hi,

I'm running cppcheck 1.77, sonarqube-6.4, sonar-scanner-3.03 and sonar-cxx-plugin-0.9.7

```
sonar-scanner is able to find my reports and import it. It's log shows:

INFO: Searching reports by relative path with basedir '/home/foo/socket-programming-examples-c' and search prop 'sonar.cxx.rats.reportPath'
INFO: Scanner found '1' report files
INFO: Parser will parse '1' report files
INFO: Processing report '/home/foo/socket-programming-examples-c/rats-report.xml'
INFO: RATS issues processed = 21
```
and
 
```
INFO: Searching reports by relative path with basedir '/home/foo/socket-programming-examples-c' and search prop 'sonar.cxx.cppcheck.reportPath'
INFO: Scanner found '1' report files
INFO: Parser will parse '1' report files
INFO: Processing report '/home/foo/socket-programming-examples-c/cppcheck-report.xml'
INFO: Added report '/home/foo/socket-programming-examples-c/cppcheck-report.xml' (parsed by: CppcheckParserV2)
INFO: CppCheck Errors processed = 18
```

and in the UI I'm able to see that it ran as well:
![screenshot from 2017-06-12 09-39-19](https://user-images.githubusercontent.com/37418/27023678-e4cfb6a4-4f53-11e7-99cd-2631e5675691.png)
![screenshot from 2017-06-12 09-39-47](https://user-images.githubusercontent.com/37418/27023686-ec56f108-4f53-11e7-9629-f14df16069d0.png)

however if you can see in the screenshot, I'm not able to "list" them. And in the metrics appears as well "0" vulnerabilities:
![screenshot from 2017-06-12 09-40-06](https://user-images.githubusercontent.com/37418/27023725-15e56658-4f54-11e7-971a-f58609ce2906.png)

so my question is: is that a known problem? configuration error? Am I missing something to be enabled?

**Comment by vpereira** [comment]
Ouch, looking into the Matrix, it looks like the version 0.97 doesn't work together with 6.4? Is the version 0.98 working with that or does it need to be tested?

**Comment by guwirth** [comment]
@vpereira Looking to #1157 and #1124 it's *nearly* working with 0.9.8. You are welcome to find the remaining issues. The solution is going the other way by removing the deprecated code:

remove deprecated DependencyAnalyzer
- remove DuplicatedInclude check
- remove CycleBetweenPackages check

**Comment by vpereira** [comment]
hi @guwirth, I went back to 0.9.7 and sonarqube 6.2. However I'm still have the same problem. I have my cppcheck report, with 18 errors, however I don't see it in my project..

**Comment by guwirth** [comment]
@vpereira not sure but think this 18 means only that there was issues in the cppcheck report but not that issues could be assigned to a source file. Or maybe rules are turned off in the profile. Please check also path issues: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues

**Comment by vpereira** [comment]
hi @guwirth  thank you,

looking my sonar-scanner (-X) output, everything is fine:

```
05:49:34.879 INFO: Searching reports by relative path with basedir '/root/test_code' and search prop 'sonar.cxx.cppcheck.reportPath'
05:49:34.879 DEBUG: Normalized report includes to '[/root/test_code/cppcheck-report.xml]'
05:49:34.880 INFO: Scanner found '1' report files
05:49:34.880 INFO: Parser will parse '1' report files
05:49:34.880 INFO: Processing report '/root/test_code/cppcheck-report.xml'
05:49:34.880 DEBUG: Parsing 'Cppcheck V2' format
05:49:34.991 INFO: Added report '/root/test_code/cppcheck-report.xml' (parsed by: CppcheckParserV2)
05:49:34.992 DEBUG: CppCheck Errors processed = 7
05:49:34.992 INFO: CppCheck Errors processed = 7
```

so cppcheck found 7 issues. But none of them appears as "vulnerability" or "bugs".. some issues found:

```
 <error id="nullPointer" severity="warning" msg="Possible null pointer dereference: p" verbose="Possible null pointer dereference: p" cwe="476">
            <location file="2.cpp" line="2"/>
        </error>
        <error id="unusedAllocatedMemory" severity="style" msg="Variable &apos;p&apos; is allocated memory that is never used." verbose="Variable &apos;p&apos; is allocated memory that is never used." cwe="563">
            <location file="5.cpp" line="3"/>
        </error>
        <error id="unusedAllocatedMemory" severity="style" msg="Variable &apos;q&apos; is allocated memory that is never used." verbose="Variable &apos;q&apos; is allocated memory that is never used." cwe="563">
            <location file="5.cpp" line="7"/>
        </error>

```

I created a project with some bad c++ code, exactly to see it being triggered, some kind of positive test, however my project still with 0 vulnerabilites? AFAICS I have all C++ rules enabled: 3102 in the "Sonar way" Quality profile..  any idea?

**Comment by vpereira** [comment]
a extract from my "rats" report:

```
<vulnerability>
  <severity>Medium</severity>
  <type>lstat</type>
  <message>
    A potential TOCTOU (Time Of Check, Time Of Use) vulnerability exists.
    This is the first line where a check has occured.
    The following line(s) contain uses that may match up with this check:
    104 (open)    , 200 (open)
  </message>
  <file>
    <name>src/fic.cc</name>
    <line>81</line>
  </file>
</vulnerability>
<vulnerability>
  <severity>Low</severity>
  <type>fixed size local buffer</type>
  <message>
    A potential race condition vulnerability exists here.  Normally a call
    to this function is vulnerable only when a match check precedes it.  No
    check was detected, however one could still exist that could not be
    detected.
  </message>
  <file>
    <name>src/main.cc</name>
    <line>199</line>
    <line>205</line>
  </file>
  <file>
    <name>src/binding.cc</name>
    <line>84</line>
  </file>
</vulnerability>

```

Shouldn't it appear among the vulnerabilities?

**Comment by Bertk** [comment]
SonarQube will look for source files below the base directory which is ```basedir '/root/test_code' ```. I assume the ```sonar-project.properties``` is located in this folder.

a) The paths from CppCheck report do not use sub-folders and therefore the source files should be available in ```'/root/test_code'```.
b) The Vera++ report uses paths pointing to src and the source files should be located in ```'/root/test_code/src'```.

Please check whether the source file paths within the reports fit to the base dir.

See details here:
https://docs.sonarqube.org/display/SONAR/Analysis+Parameters

**Comment by vpereira** [comment]
Hi, yes your gess is right. sonar-project.properties is in the /root/test_code.
so inside "test_code", I have the following directories:

- reports (where my reports are)
- src (where my source files are

After run sonarqube-scanner, I realized the following:

![screenshot from 2017-06-13 17-11-47](https://user-images.githubusercontent.com/37418/27089716-773b0fcc-505b-11e7-8d34-dba1d5591a2f.png)

It has 7 "Bugs"

however looking into the bugs, they are all classified as "Bugs" but, because of the CWE I was expecting to see it under "Vulnerabilities" 

Specially a CWE-788: Access of Memory Location After End of Buffer, I was expecting to see it under "Vulnerabilities".. is that something that I have to configure or bug in the plugin?

**Comment by Bertk** [comment]
Please read this - https://blog.sonarsource.com/bugs-and-vulnerabilities-are-1st-class-citizens-in-sonarqube-quality-model-along-with-code-smells/

A rule can only be declared as a 'bug' or a 'vulnerability' and this reflects the priority for fixing the issue.
