### ISSUE TITLE
trying to get c++ pc-lint reports into sonar

### ISSUE THREAD

**Issue by Alex66955** [SonarOpenCommunity/sonar-cxx#116]
Hey,

When I run the sonar-runner, my PcLint (flexLint)
output xml file will ignored.

_My Configuration:_
- FlexLint Version 9.0
- SonarQube Version 4.1.2
- sonar-cxx-plugin 0.9
- sonar-runner 2.3

_My sonar-project.properties:_

```
# required metadata
sonar.projectKey=CxxPlugin:FlexLintSample
sonar.projectName=FlexLintSample
sonar.projectVersion=0.0.1
sonar.language=c++

# path to source directories (required)
sonar.sources=src
#sonar.tests=tests/unittests

# path to the build artifact
sonar.artifact.path=build/a.out

# paths to the reports
sonar.cxx.pclint.reportPath=build/pclint-report.xml
```

How can I adjust the quality profile from SonarQube with PcLint/Misra Rules,
I have only the profile "Sonar Way" (C++)? And what are the settings to run
the sonar-runner with my generated report file (Actually this file will
ignored)?

Best Regards
Alex

**Comment by Lenegred** [comment]
@Alex66955 hey,
I have find this question in my pc-lint report analyzer.

> > jmecosta commented 3 days ago Collaborator
> > You need to copy the default profile and then enable the rules.
> 
> After that, it works!
> 
> Thanks ;)

Would you tell me where can I find the  default profile ?I can not find the file in my Sonar folder.
