### ISSUE TITLE
Remove WARN message: ...is ignored because it doesn't belong to the forced language ...

### ISSUE THREAD

**Issue by kohldampfer** [SonarOpenCommunity/sonar-cxx#1160]
During the process of running sonar-scanner, I get a lot of messages like this:

> WARN: File '/path/to/some/file.zip' is ignored because it doens't belong to the forced langauge 'c++'

These are files, which are part of the project. Due to history reasons, in some projects, there is no difference between where the source files are and e.g. this archive file, e.g. some are mixed.

Is there an option where you can deactivate such warnings? I did not found any in the github Wiki. If there isn't such an option, maybe it would be an idea, to add it, like

> sonar.cxx.printIgnoredFiles = [on|off]

Standard could be off.

**Comment by guwirth** [comment]
@kohldampfer as far as I know this is a core feature. Maybe you should ask directly in a SonarQube forum.
