### ISSUE TITLE
Trailing comma is not removed in complex macro with empty variadic arguments

### ISSUE THREAD

**Issue by tomassdepakin** [SonarOpenCommunity/sonar-cxx#1167]
Example:
```
#define MACRO(s, ...) do { printf(s, __VA_ARGS__); } while (false)
int main() { MACRO(\"error\"); }
```
Parser doesn't remove comma on empty \_\_VA_ARGS__ and resolves macro as
```
int main() { do { printf(\"error\", ); } while (false) }
```

**Comment by guwirth** [comment]
@tomassdepakin there are already some tests: https://github.com/SonarOpenCommunity/sonar-cxx/search?utf8=✓&q=variadic_macros
Think should work?

**Comment by tomassdepakin** [comment]
Yep, it works unless there is another `)` after VA_ARGS. And tests don't cover this case.

This code seems to be working only if macro ends with `,)` sequence:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/src/main/java/org/sonar/cxx/preprocessor/CxxPreprocessor.java#L1021
