### ISSUE TITLE
Update gcc rules

### ISSUE THREAD

**Issue by gena01** [SonarOpenCommunity/sonar-cxx#1173]
INFO: Parsing 'GCC' format
ERROR: Could not add the issue 'The rule 'compiler-gcc:-Wliteral-suffix' does not exist.', skipping issue
ERROR: Could not add the issue 'The rule 'compiler-gcc:-Wliteral-suffix' does not exist.', skipping issue

**Comment by guwirth** [comment]
@gena01 hi could be. Don't know when gcc rules are last time updated. Which gcc version are you using?

**Comment by guwirth** [comment]
@gena01 our current list is here https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/compiler-gcc.xml

**Comment by gena01** [comment]
@guwirth yes, i checked that file before opening this issue.

g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)

**Comment by gena01** [comment]
Was looking through https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html and found some more possible missing rules:
-Wbool-compare  
-Wbool-operation
-Wcatch-value (C++ and Objective-C++ only)  
-Wduplicate-decl-specifier (C and Objective-C only) 
-Wint-in-bool-context
-Wmisleading-indentation
-Wnonnull-compare 
-Wopenmp-simd
-Wsizeof-pointer-div 
-Wsizeof-pointer-memaccess 
-Wtautological-compare
-Wimplicit-fallthrough
-Wshift-negative-value (in C++03 and in C99 and newer)

**Comment by guwirth** [comment]
@gena01 would be perfect if you could update the xml file with the latest warnings/rules.

**Comment by guwirth** [comment]
@all someone using GCC and time to update the ruleset?
