### ISSUE TITLE
sonar.cxx.jsonCompilationDatabase is not documented

### ISSUE THREAD

**Issue by gena01** [SonarOpenCommunity/sonar-cxx#1175]
So I found sonar.cxx.jsonCompilationDatabase on https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers page, but it's not listed https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties

**Comment by guwirth** [comment]
@vesajaaskelainen maybe you can add some more docu in our wiki?

**Comment by guwirth** [comment]
@vesajaaskelainen yes thanks
