### ISSUE TITLE
C++ Parser can't read code. Declaration is skipped. With correct code.

### ISSUE THREAD

**Issue by PawelKm** [SonarOpenCommunity/sonar-cxx#1181]
I have cpp file where I have function:
```C++
bool ConfigurationLoader::LoadSetting(
    const std::pair<std::string, const boost::property_tree::basic_ptree<std::string, std::string>> &inTree,
    const std::string &setting,
    std::pair<std::string,
                   boost::property_tree::basic_ptree<
                  std::string, std::string, std::less<std::string>>> &retVal)
```

and also hpp file where I have declaration:
```C++
static bool LoadSetting(
      const std::pair<std::string, const boost::property_tree::basic_ptree<std::string, std::string>> &inTree,
      const std::string &setting,
      std::pair<std::string,
                boost::property_tree::basic_ptree<
                    std::string, std::string, std::less<std::string>>> &retVal);
```
in both files I have `#include <boost/property_tree/xml_parser.hpp>` 
what includes
`#include <boost/property_tree/ptree.hpp>`
what includes 
`#include <boost/property_tree/ptree_fwd.hpp>` what contains the forward declaration:
```C++
template < class Key, class Data, class KeyCompare = std::less<Key> >
    class basic_ptree;
```
But still using `const boost::property_tree::basic_ptree<std::string, std::string>>` causes 5 issues reported with declarations skipped up to first namespace level.

Usage of `const boost::property_tree::basic_ptree<std::string, std::string, std::less<std::string>>>` fixes the problem for now.

**Comment by guwirth** [comment]
@PawelKm thanks for your feedback. 

* The cxx plugin is only parsing the grammar. So problem should occur with or without header files.
* Which cxx plugin version are you using?
* Is your compiler supporting the code? Which compiler?
* Please try to narrow down the problem with our sslr-toolkit:
  * https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-0.9.7/sslr-cxx-toolkit-0.9.7.jar
  * or with latest https://ci.appveyor.com/api/buildjobs/tqoyv1u2fq6kttb9/artifacts/sslr-cxx-toolkit%2Ftarget%2Fsslr-cxx-toolkit-0.9.8-SNAPSHOT.jar
  * Play around with the code and provide a minimal example to reproduce the issue.
  * Does this issue only occur when template is a function parameter or also if you try to create a global variable?

**Comment by PawelKm** [comment]
This I can provide now: I will try to narrow down problem whenever I find free time.
- Which cxx plugin version are you using?
-- 9.7.0 release version
- Is your compiler supporting the code? Which compiler?
-- yes I use VS2015 C++, Visual Studio2017 C++, gcc 4.9.2, gcc 4.9.4

I will try to narrow down problem whenever I find free time.

**Comment by guwirth** [comment]
Hi @PawelKm 

reduced sample:
```C++
bool ok1(templateName1<templateName<string>> declarator); // without const
bool ok2(templateName1<const templateName<string> > declarator); // blank between >>

bool failure(templateName1<const templateName<string>> declarator); // failure
```
As a workaround you can add a blank between `>>`.

Regards

**Comment by PawelKm** [comment]
Thanks @guwirth that helped also!

**Comment by guwirth** [comment]
@ametselaar we need your help. We have a hard grammar nut to crack.
Do you have some time to have a look to this issue?

**Comment by guwirth** [comment]
see #1685

**Comment by zdg123456** [comment]
@guwirth 您好
我这边也碰到C++ Parser can't read code.Declaration is skipped这个报错
具体报错：
ERROR: Undefined functionlike macro '__has_attribute' assuming 0 
ERROR: Undefined functionlike macro '__has_attribute' assuming 0 
ERROR: Undefined functionlike macro '__has_extension' assuming 0 
ERROR: Undefined functionlike macro 'KERNEL_VERSION' assuming 0 
ERROR: Undefined functionlike macro 'RHEL_RELEASE_VERSION' assuming 0 
C插件版本：sonar-c-plugin-1.3.2.1853.jar
C++插件版本：sonar-cxx-plugin-2.0.7.3119.jar

**Comment by guwirth** [comment]
Hi @zdg123456,

please have a look to  https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces

Regards,
