### ISSUE TITLE
"Coverage on New Code" property is always "—" 

### ISSUE THREAD

**Issue by summerzhou2** [SonarOpenCommunity/sonar-cxx#1183]
Environment:
plugin sonar-cxx-plugin-0.9.5 
SonarQube Version 5.3 
sonar-scanner-2.5
windows x86-64bit
Chrome version 59
c++
bullseye coverage

Issue:
After analyse,"Coverage on New Code" property is always "—"  in the SonarQube, but has coverage info for c++ code, coverage ratio is 71.4%. So why "Coverage on New Code" property is always missing?

sonar-project.properties:
sonar.projectKey=org.sonarqube:cpp-bullseye-sq-scanner
sonar.projectName=C++ :: BullseyeCoverage :: SonarQube Scanner
sonar.projectVersion=1.0
sonar.sources=example.c
sonar.sourceEncoding=UTF-8
sonar.cxx.coverage.reportPath=report.xml

example.c:
int main(int a){
if(a==0)
  {
     return 0;
  }
  else{
     return 1;
  }
}

Would you please tell me is there anything wrong with such configuration which caused "Coverage on New Code" property is always shown as "—" ?

Thanks a lot!

**Comment by summerzhou2** [comment]
> <?xml

 version="1.0" encoding="UTF-8"?>
<BullseyeCoverage name="coverage.cov" dir="/covSample/" buildId="532cbc332015-05-11 11:43:46" version="4" xmlns="http://www.bullseye.com/covxml">
<src name="examples.c" mtime="1431336404" fn_cov="1" fn_total="1" cd_cov="1" cd_total="2" d_cov="1" d_total="2">
<fn name="main(int)" fn_cov="1" fn_total="1" cd_cov="1" cd_total="2" d_cov="1" d_total="2">
<probe line="1" column="3" kind="function" event="full"/>
<probe line="2" kind="decision" event="false"/>
<probe line="6" kind="decision" event="false"/>
</fn>
</src>
</BullseyeCoverage>

> 

- [ ] 

- @1.

**Comment by guwirth** [comment]
@summerzhou2 think "Coverage on New Code" is only displayed if you are using / activating SCM support (SVN. Git, ...).

`sonar.scm.disabled=false`

**Comment by summerzhou2** [comment]
Hi guwirth,

Thanks for your suggestion,but when I want to enable scm perforce,there's another question:
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 2.510s
INFO: Final Memory: 42M/228M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: SCM provider was set to "perforce" but no SCM provider found for this key
. Supported SCM providers are svn,git


Here is my sonar-project.properties:
sonar.scm.disabled=false
sonar.scm.provider=perforce
sonar.perforce.port=shxgcompany:2666
sonar.perforce.username=user
sonar.perforce.password.secured=user123
sonar.perforce.clientName=summerzhou_sonarqube

It seems perforce plugin is missing. But for sonarqube5.3,I don't know where can I download perforce plugin?Can you tell me?

**Comment by guwirth** [comment]
@summerzhou2 think you should ask this in the SonarQule group: https://groups.google.com/forum/#!forum/sonarqube
