### ISSUE TITLE
c++ community can't extract msbuild warnings for SonarQube

### ISSUE THREAD

**Issue by VallotLuc** [SonarOpenCommunity/sonar-cxx#1184]
Hi,

I want export warning from c++ msbuild.log file to sonarqube, using c++ community plugin,
after exporting, sonarqube has no result except duplications informations

I'm using this process

**SonarQube.Scanner.MSBuild.exe begin /k:"LV" /n:"LV" /v:"1.0" /s:"C:\Program Files (x86)\Jenkins\workspace\sonarqube.analysis.xml" /d:sonar.cxx.compiler.regex="^.*>(?<filename>.*)\((?<line>[0-9]+)\):\x20warning\x20(<id>C\d\d\d\d):(?<message>.*)$"
"C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /t:Clean,Build /p:PlatformToolset=v140  /p:Configuration=Release;WarningLevel=3 /p:RunCodeAnalysis=True;CodeAnalysisRuleSet=AllRules.ruleset;verbosity=normal /filelogger /fileLoggerParameters:Verbosity=detailed;Encoding=UTF-8
SonarQube.Scanner.MSBuild.exe end**

the end process display this
**INFO: Sensor CxxCompilerSensor [cxx]
INFO: Searching reports by relative path with basedir 'C:\Program Files (x86)\Jenkins\workspace\Test_C' and search prop 'sonar.cxx.compiler.reportPath'
INFO: Scanner found '1' report files
INFO: Parser will parse '1' report files
INFO: Processing report 'C:\Program Files (x86)\Jenkins\workspace\Test_C\msbuild.log'
INFO: Scanner 'Visual C++' initialized with report 'C:\Program Files (x86)\Jenkins\workspace\Test_C\msbuild.log', CharSet= 'UTF-8'
INFO: Parsing 'Visual C++' format (UTF-8)
INFO: Using pattern : '^.*>(?<filename>.*)\((?<line>[0-9]+)\):\x20warning\x20(<id>C\d\d\d\d):(?<message>.*)$'
INFO: C++ compiler Warnings processed = 0
INFO: Sensor CxxCompilerSensor [cxx] (done) | time=359ms**

as you can see, no warnings are processed, but why ? , the msbuild.log contain many

I'm using c++ plugin 0.9.7 and all rules are activated

msbuild.log and qonarqube.analysis.xml in this zipfile
[SonarQube.Analysis.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/1121949/SonarQube.Analysis.zip)

Can you help me ?

Best regards

Luc

**Comment by guwirth** [comment]
@VallotLuc some questions:
* Which SQ version are you using?
* Which SonarQube.Scanner.MSBuild.exe are you using?
* Have you read this: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers#microsofts-visual-studio-compiler

Regards,

**Comment by VallotLuc** [comment]
Hi guwirth,

SQ : 6.4
SQ.Scanner.MSBuild : 3.0.0.629
MsBuild : 14.0.25420.1

thanks for the link, the problem is solved
the reason was the regex expression (I do not use the good one)

One related question : 
what is the right syntax to record the regex expression inside the SonarQube.Analysis.xml file ?

regards

Luc

**Comment by guwirth** [comment]
@VallotLuc good to hear.

Our settings are documented here: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties

**Comment by VallotLuc** [comment]
Thanks Günter,
but last problem was: the exact syntax for the regex value in the xml file 
(for example,  ^(.*)\((\d+)\)\x20*:\x20warning\x20(C\d+):(.*)$  , how to code this ?
If I wrote " ^(.*)\((\d+)\)\x20*:\x20warning\x20(C\d+):(.*)$ ", this can't be read

thanks

Luc

**Comment by Bertk** [comment]
Please read discussion #616. There you find a sample properties file for visual studio 'SonarQube.StaticAnalysis.props'. Here I use 
```XML
<SQCompilerRegEx>^(.*)\((\d+)\)\x20*:\x20warning\x20(C\d+):\x20(.*)\x20\[$(SQProjectFile)\]$</SQCompilerRegEx>
```

and a message shows the regular expression:

```XML
<Target Name = "SQEnvCheck" AfterTargets="Build">
<Message Text="sonar.cxx.compiler.regex      = $(SQCompilerRegEx)"/>
</Target>
```

**Comment by VallotLuc** [comment]
thanks for the syntax,

I have a related question

my msbuild.log file contain duplicates warning lines (same file, same line , same warning-code), 
but they are not exactly duplicated, the file path speeling is not the same
(for example, I can find 
c:\program files (x86)\jenkins\workspace\test_c\calcul\Types.h 
and 
c:\program files (x86)\jenkins\workspace\test_c\fichiercommunrglt\../calcul/Types.h
the same file named differently)

is it possible to force Msbuild to generate the same value, or is it possible to write a script to replace the path by a normalized one ?

regards

Luc

**Comment by Bertk** [comment]
I think the second path is not correct and the plug-in does not handle the relative path starting with '..\\' correctly. 
**A separator '/' or '\\' is missing at the end of the project root folder.  This should be added if the path starts with '..\\'**
Hint: Better solution is to replace all '\\' with '/' anyway. 

So this issue has to be solved in the C++ community plug-in. 

The usage of "../calcul/Types.h" is a bad practice and shall be avoided anyway.
Please read the rule ```cxx:UseCorrectInclude```  **_#include directive shall not use relative path_**
