### ISSUE TITLE
New property property sonar.cxx.other.rulesPaths

### ISSUE THREAD

**Issue by stefanweiser** [SonarOpenCommunity/sonar-cxx#1185]
I'd like to add a new property, which contains paths to files, that contain the custom rules. It would quiet be the same as the property sonar.cxx.other.rules, but do not contain the rules directly. What do you think?

**Comment by guwirth** [comment]
@stefanweiser could you describe the use case / benefit please. 

Current behaviour of `sonar.cxx.other.reportPath` is: Ant pattern describing the path to other reports. Path can be relative or absolute. **Single path or comma separated list of paths is supported.**

**Comment by guwirth** [comment]
... name is confusing `sonar.cxx.other.reportPath` should be `sonar.cxx.other.reportsPaths`

**Comment by stefanweiser** [comment]
Sorry, not reportPaths but rulesPaths, because it would ease the automation of SonarQube installation if custom rules are involved. The benefit would be, that the other rule repository could be updated by some files you simply would place at the server side. The current option sonar.cxx.other.rules reads the value as a string. This is not very useful for those rule texts often get very long and contain newlines in case of Markdown rule descriptions. It would be beneficial when you not need to update the custom rules by copying them to the web frontend. That way (by providing files for the custom rules) you cannot crash your configuration (and then have to fiddle around in the database) if the rules contain parser errors, because you can change those data before starting Sonarqube.

**Comment by jmecosta** [comment]
Why don't you use the rest api to batch create those.  Like that you don't
have to fiddle with the server at all and its way better approach since
rules are then under sonar configuration control

**Comment by guwirth** [comment]
@stefanweiser agree with @jmecosta that for installation automation the SQ REST API is the better choice.
