### ISSUE TITLE
ask for detailed usage for clang-tidy feature support

### ISSUE THREAD

**Issue by xstarcto** [SonarOpenCommunity/sonar-cxx#1186]
hello all,

may i know when the 0.9.8 is officially released because i would like to use clang-tidy related feature ?

meanwhile, i try to build the plugin as 0.9.8-snapshot and try to use it as below steps 
a, i use clang-tidy command first ： > clang-tidy diveByZero.cpp 1 > result.txt
b, add sonar.cxx.clangtidy.reportPath=result.txt;
c, sonar-scanner

the command run successfully but no warning/error showed in sonarqube portal although result1.txt did have some.

would you please provide me some official steps (like what is the correct format of clang-tidy to be parsed by the plugin)  to run the clang-tidy feature through ? really appreciate!

**Comment by jmecosta** [comment]
Have you enable the rules in the quality profile?

**Comment by guwirth** [comment]
@xstarcto is it working now? Can we close this?
