### ISSUE TITLE
Supporting/reporting "generated_lines" SonarQube Metric

### ISSUE THREAD

**Issue by gena01** [SonarOpenCommunity/sonar-cxx#1187]
So I am poking through some of the metrics I am getting with the plugin and I noticed that I am not seeing "generated_lines" metric. 

Is there anything missing on the configuration side or is this not currently supported? If it's not currently supported can this be turned into RFE?

**Comment by guwirth** [comment]
@gena01 seems to be only in use by COBOL https://docs.sonarqube.org/plugins/servlet/mobile#content/view/8520869. How should C++ use this?

**Comment by gena01** [comment]
@guwirth I am using a framework that generates both .h and .cpp files. Ideally i want to ignore those files as well as exclude them from coverage. Another interesting metric is to know how much of my code is generated. The support for this seems to be available in the core of SonarQube and API. It would also potentially simplify coverage exclusion rules if we had some specific option(s) for generated files.

**Comment by guwirth** [comment]
@gena01 how should the plugin find out what is generated code? For something like this `sonar.exclusions=...` is the right choice.
