### ISSUE TITLE
Provide additional verbosity levels for logging/output

### ISSUE THREAD

**Issue by wenns** [SonarOpenCommunity/sonar-cxx#120]
Currently, we have two verbosity levels for the output of the sonar analysis: 
normal and debug (-X). This doesnt suffice, however. Quite often, to analyse a error situation in users environment, we need more output (especially from the preprocessor). However, we cannot just produce more output in  the 'normal' -X mode, because it would produce huge amount of data for bigger project. 

The solution can be additional verbosity levels, switchable from the user interface via sonar.cxx.verbosity=<number> or something. The commercial C++ from plugin used SonarSource sonar.verbose=<bool>, BTW.

**Comment by guwirth** [comment]
no contributors, close this
