### ISSUE TITLE
Rule templates disabled when using organizations 

### ISSUE THREAD

**Issue by mswebb** [SonarOpenCommunity/sonar-cxx#1208]
With organizations enabled (yes I know its not supported by SQ - but I have a strong use case for them), web.log identifies that the sonar-cxx rules are being ignored when SonarQube service starts

e.g. 
```
2017.08.16 14:02:54 INFO  web[][o.s.s.r.RegisterRules] Template rule cppcheck:CustomRuleTemplate will not be imported, because organizations are enabled.
2017.08.16 14:02:54 INFO  web[][o.s.s.r.RegisterRules] Template rule rats:CustomRuleTemplate will not be imported, because organizations are enabled.
2017.08.16 14:02:54 INFO  web[][o.s.s.r.RegisterRules] Template rule compiler-gcc:=CustomRuleTemplate will not be imported, because organizations are enabled.
2017.08.16 14:02:55 INFO  web[][o.s.s.r.RegisterRules] Template rule vera++:CustomRuleTemplate will not be imported, because organizations are enabled.
2017.08.16 14:02:55 INFO  web[][o.s.s.r.RegisterRules] Template rule valgrind:=CustomRuleTemplate will not be imported, because organizations are enabled.
2017.08.16 14:02:55 INFO  web[][o.s.s.r.RegisterRules] Template rule cxx:LineRegularExpression will not be imported, because organizations are enabled.
2017.08.16 14:02:55 INFO  web[][o.s.s.r.RegisterRules] Template rule cxx:UseCorrectType will not be imported, because organizations are enabled.
2017.08.16 14:02:55 INFO  web[][o.s.s.r.RegisterRules] Template rule cxx:XPath will not be imported, because organizations are enabled.
2017.08.16 14:02:55 INFO  web[][o.s.s.r.RegisterRules] Template rule cxx:FileRegularExpression will not be imported, because organizations are enabled.
2017.08.16 14:02:55 INFO  web[][o.s.s.r.RegisterRules] Template rule cxx:CommentRegularExpression will not be imported, because organizations are enabled.
2017.08.16 14:02:56 INFO  web[][o.s.s.r.RegisterRules] Template rule pclint:CustomRuleTemplate will not be imported, because organizations are enabled.
2017.08.16 14:02:57 INFO  web[][o.s.s.r.RegisterRules] Template rule compiler-vc:CustomRuleTemplate" will not be imported, because organizations are enabled.
```

See https://github.com/SonarSource/sonarqube/blob/master/enable-organizations.sh

**Comment by Bertk** [comment]
@guwirth I want to have the organizations support as well :+1

**Comment by guwirth** [comment]
Don't understand this feature? What is it doing? How can we support it? Is there somewhere a description?

**Comment by mswebb** [comment]
Internally to SoanrQube, organizations can be enabled to provide another level of hierarchy above projects. 

They can be enabled on an instance with the API `curl -XPOST -u admin:admin "http://localhost:9000/api/organizations/enable_support"`

The specific error message is displayed here : 
https://github.com/SonarSource/sonarqube/blob/3ccd84ac94178c482f78644630d623b92adf6e49/server/sonar-server/src/main/java/org/sonar/server/rule/RegisterRules.java#L104

**Comment by guwirth** [comment]
@mswebb but seems to be only an info and not an error? Saying that organisation and templates are not possible. Still don't understand what we can do in the plugin to avoid this?

**Comment by mswebb** [comment]
Understood - let me dig deeper and see what I can determine

**Comment by mswebb** [comment]
This is not as critical as originally observed... only rules templates are affected. Closing
