### ISSUE TITLE
CxxClangTidySensor expects UTF8 report - not configurable

### ISSUE THREAD

**Issue by apriori** [SonarOpenCommunity/sonar-cxx#1213]
As seen in:

https://github.com/SonarOpenCommunity/sonar-cxx/blob/007a34eb1be0be776f6b5bccad0408252cfc5e82/cxx-sensors/src/main/java/org/sonar/cxx/sensors/clangtidy/CxxClangTidySensor.java#L66

In general I suggest to make encoding configurable for all reports, like it is done for e.g. sonar.cxx.compiler.charset. This is a valid issue, because e.g. clang-tidy also works for windows and usually its reports are gathered by console piping. Console piping in windows (for the powershell) is done in UCS2/UTF-16 by default which results in issues when providing sonar-cxx with such reports.

**Comment by guwirth** [comment]
@apriori thx for the hint. Are you familiar with Java? You are welcome to contribute to the project....

**Comment by apriori** [comment]
Yes I am, let me see whether I can find time to fix this. Should actually be quite easy.

**Comment by guwirth** [comment]
@apriori please try with latest snapshot.
