### ISSUE TITLE
JsonCompilationDatabase class does not handle @CMakeFiles/$file argument file indicators

### ISSUE THREAD

**Issue by apriori** [SonarOpenCommunity/sonar-cxx#1214]
CMake under some circumstances outputs @CMakeFiles markers into the compiler commandline, indicating it shall read further commandline arguments from there. This case is not handled by the parser of the JsonCompilationDatabase class. This scenario occurs for example when making CMake output the compile_commands.json while using the scan-build wrapper.

**Comment by apriori** [comment]
Easiest solution would be to pre-process the json, expanding all "@CMakeFiles" markers by reading the referenced files (using the base directory as indicated by the json "directory" attribute of the object) before the actual json processing logic.

**Comment by guwirth** [comment]
@apriori could you provide a reduced sample file please.

**Comment by guwirth** [comment]
@vesajaaskelainen do you have some time to have a look to this?

**Comment by vesajaaskelainen** [comment]
Not using cmake myself too much an example (simplified) project would be in place to test it out. Don't like the idea of preprocessing `@file` values outside as integrating such functionality in code should be easy.
