### ISSUE TITLE
JSON Compilation Database class does not handle "-isystem" include path references

### ISSUE THREAD

**Issue by apriori** [SonarOpenCommunity/sonar-cxx#1215]
Title should be self-explanatory

**Comment by guwirth** [comment]
@vesajaaskelainen do you have some time to have a look to this?

**Comment by guwirth** [comment]
Not sure if adding system include paths is a good idea. This will slow down the parser and is typically not needed. Better and much faster is typically to provide the macros creating syntax errors with defines or force include (see https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces). 

@Bertk @jmecosta how are you doing this with your VS analysis?

**Comment by jmecosta** [comment]
we have system headers, both in server and local analysis the time spend on
analysis is not that significant for us so that we could consider disabling
those headers.

**Comment by vesajaaskelainen** [comment]
Compiler's headers are more or less mandatory in order to get good level of analysis. Even thou the analysis is rather slow it is better to analyze correctly than incorrectly. Aka. I would sacrifice speed over accuracy. 

Making it configurable for user I suppose is OKish.

**Comment by vesajaaskelainen** [comment]
Link to -isystem documentation in case someone was wondering:
https://gcc.gnu.org/onlinedocs/gcc-7.2.0/gcc/Directory-Options.html#Directory-Options

I suppose -isystem would need more in-depth support to handle different classes of headers.

Minimal compatible version probably would be to treat -isystem <path> as -i <path> but it is slightly incorrect.

**Comment by guwirth** [comment]
Hi @tisoft, you seems to be familiar with JSON Compilation Database. Do we need the -isystem support?

**Comment by tisoft** [comment]
I have a local fork with isystem enabled and it helps. Still testing though.

**Comment by guwirth** [comment]
@tisoft If that works, it would be nice if you could provide the solution as PR.
