### ISSUE TITLE
Report only code coverage information

### ISSUE THREAD

**Issue by masaeedu** [SonarOpenCommunity/sonar-cxx#1216]
I have a folder with generated `*.gcov` reports and a corresponding `gcovr` generated Cobertura-format XML file. I simply want to report these code coverage statistics to SonarQube, without doing any expensive analysis on our thousands of source files. What options can I set to simply report code coverage analysis, and do nothing else?

My configuration currently looks like this:

```
sonar.projectKey=...
sonar.sources=.
sonar.cxx.coverage.itReportPath=gcov_report/report.xml
sonar.language=c++
sonar.inclusions=agent/main/ClientSource/**/*.cpp
```

Once the scanner is started up it chews through C++ files for about half an hour, reporting lots of include warnings (include paths are specified via cmake and hard to recreate manually). Eventually it gets around to reporting the coverage information from the gcovr report, which is the only task I need it to perform.

**Comment by masaeedu** [comment]
I also tried creating a quality profile for C++ called "none" with no rules, and activated it for this project. I was hoping this would make it zip through whatever analysis it is doing on the C++ source, but it doesn't seem to have any impact on the speed.

**Comment by guwirth** [comment]
Hi @masaeedu it's a little bit more complicated. To assign issues or other reports SonarQube needs always first a source file. Means first the squid sensor has to read all sources. To speed up this step you can try to use less/no include paths settings.

https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties#sonarcxxincludedirectories

In the settings you can turn the missing include setting off: missingIncludeWarnings

Also turn error recovery on

https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties#sonarcxxerrorrecoveryenabled

**Comment by masaeedu** [comment]
@guwirth Can I just get it to read the source files and send them without trying to find and preprocess includes? You can see from my configuration above I am already not specifying `sonar.cxx.includeDirectories`. 

Does turning error recovery on mean setting `sonar.cxx.errorRecoveryEnabled` to `false`? If not, I probably already have it on, since the link you provided indicates the default value is `true` and I am not explicitly specifying it.

**Comment by guwirth** [comment]
@masaeedu turn debug info on to see where time get lost. https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

* You can't turn preprocessor off. You can only set no includeDirectories or set it to =.
* sonar.cxx.errorRecoveryEnabled should be true

How big is you project? How many LOC we are talking about?

**Comment by guwirth** [comment]
@masaeedu its this still an issue or can we close it?

**Comment by masaeedu** [comment]
It's still an issue AFAICT but I'll close it since I'm not using the tool anymore and can't debug.

**Comment by mmatrosov** [comment]
Sorry for the necroposting, but I have exactly the same problem. Can we have this issue reopened? Or do I rather create a new one?

**Comment by guwirth** [comment]
Hi @mmatrosov, think it's better to open a new issue.

**Comment by mmatrosov** [comment]
Ok, see #1770
