### ISSUE TITLE
JSON compile commands database - but still includes not found.

### ISSUE THREAD

**Issue by mgerhardy** [SonarOpenCommunity/sonar-cxx#1229]
Still getting includes not found even though I provide my whole compile_commands.json.

Btw. I'm just trying to upload a cppcheck result - can I someone just do the uploading without doing any other parsing/analysing/whatever?

Not setting sonar.sources e.g. leads to an error. Basically I only want to set sonar.cxx.cppcheck.reportPath and run sonar-scanner to just take that file.

**Comment by mgerhardy** [comment]
```
# required metadata
sonar.projectKey=@CMAKE_PROJECT_NAME@
sonar.projectName=@CMAKE_PROJECT_NAME@
sonar.projectVersion=@VERSION@
sonar.language=c++

# TODO: get this from a data bag or something similar
sonar.host.url=http://myurl:9000
sonar.login=loginname
sonar.password=nypassword

# disable SCM support
#sonar.scm.disabled=true

# path to source directories (required)
sonar.sources=@PROJECT_SOURCE_DIR@
#sonar.cxx.clangsa.reportPath=analyzer_reports/*/*.plist
#sonar.cxx.xunit.reportPath=
#sonar.cxx.valgrind.reportPath=valgrind-report.xml
#sonar.findbugs.reportPath=.sonar/findbugs-result.xml
sonar.cxx.cppcheck.reportPath=cppcheck-report.xml
sonar.cxx.jsonCompilationDatabase=@PROJECT_BINARY_DIR@/compile_commands.json
#sonar.cxx.scanOnlySpecifiedSources=true
#sonar.cxx.errorRecoveryEnabled=true

```

**Comment by guwirth** [comment]
@mgerhardy 

> Btw. I'm just trying to upload a cppcheck result - can I someone just do the uploading without doing any other parsing/analysing/whatever?

That's not possible. The SQ core has to read the source file first to be able to assign issues. Means the SQUID sensor have to run first. Providing no or less includes can speed up reading the sources.

**Comment by guwirth** [comment]
@mgerhardy 

> Still getting includes not found even though I provide my whole compile_commands.json.

Could you provide a complete sample please.
* Which include in the source file is not working?
* Is the include a relative or an absolute path?
* Is the include quoted form or angle-bracket form?
* In case of relative path: is the absolute part defined in the `compile_commands.json` file?
   * Could you provide `compile_commands.json` sample

**Comment by mgerhardy** [comment]
We include without directories. Just `#include <Foo.h>` and configured include paths via compiler arguments.

```
[...]
{
  "directory": "/home/mgerhardy/dev/myproject/build/a/b",
  "command": "clang++ -I/usr/include/apr-1 -I/usr/local/include -I/usr/include/httpd -I/home/mgerhardy/dev/myproject/src/a/. -I/home/mgerhardy/dev/myproject/src/a/b/. -I/home/mgerhardy/dev/myproject/src/a/b/../../lib/c/d -I/home/mgerhardy/dev/myproject/src/a/b/../../lib/d/e -I/home/mgerhardy/dev/myproject/src/a/b/../../lib/f/g -fsigned-char -std=c++11 -Wall -Werror -Wno-c++14-compat -Wno-invalid-source-encoding -Wno-overloaded-virtual -Wno-self-assign -Wno-deprecated-register -Wno-deprecated-declarations -Wno-undefined-bool-conversion -Wno-unused-private-field -DTRACE -DDEVELOPMENT -g -fPIC   -o CMakeFiles/myproject.dir/source.cc.o -c /home/mgerhardy/dev/myproject/src/a/b/source.cc",
  "file": "/home/mgerhardy/dev/myproject/src/a/b/source.cc"
},
[...]
```

**Comment by guwirth** [comment]
@mgerhardy is there a with `-I` defined path to the `foo.h` file in the `compile_commands.json`file?

**Comment by guwirth** [comment]
@mgerhardy its this still an issue or can we close it?

**Comment by guwirth** [comment]
@vesajaaskelainen do you have some time to have a look to this?

**Comment by guwirth** [comment]
No feedback I close this. Please reopen if still an issue.
