### ISSUE TITLE
NullPointerException when passing empty coverage report

### ISSUE THREAD

**Issue by dutiona** [SonarOpenCommunity/sonar-cxx#1231]
Hello,
When passing an empty (yet valid) coverage report to the plugin, sonar scanner crashes with the following stack-trace : 

> WARN: Coverage report /path/to/coverage/empty-report.xml result is empty (parsed by VisualStudioParser)
> ERROR: Error during SonarQube Scanner execution
> java.lang.NullPointerException
> 	at java.util.HashMap.putMapEntries(HashMap.java:500)
> 	at java.util.HashMap.putAll(HashMap.java:784)
> 	at org.sonar.cxx.sensors.coverage.CxxCoverageSensor.processReports(CxxCoverageSensor.java:249)
> 	at org.sonar.cxx.sensors.coverage.CxxCoverageSensor.execute(CxxCoverageSensor.java:135)
> 	at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:182)
> 	at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
> 	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
> 	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
> 	at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
> 	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
> 	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
> 	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
> 	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:234)
> 	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
> 	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
> 	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
> 	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
> 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
> 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
> 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
> 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
> 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
> 	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
> 	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
> 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

I'm attaching you the empty coverage report you can use to reproduce.

I must precise that I have this bug after "upgrading" to a snapshot of the master as of today. It previously worked fine with the release 0.9.7 version ("worked fine" means that the report was ignored without crashing the scanner).

Thanks
-dutiona

[empty-report.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/1296265/empty-report.zip)

**Comment by guwirth** [comment]
@dutiona please give latest PR a try.

**Comment by dutiona** [comment]
@guwirth I confirm it now works with the latest PR. Thanks.
