### ISSUE TITLE
How to run the code analyzis for C++

### ISSUE THREAD

**Issue by skalaiyarasan** [SonarOpenCommunity/sonar-cxx#1233]
Hi,

We are going to use the sonar-cxx plugin for C++ code analysis.  I able to get a coverage report (Bullesye) in SonarQube dashboard.

Here i need a help that how to run the code analyzis for C++ lang to get Bugs & Vulnerabilities and Code Smells.

Thanks,
Kalaiyarasan

**Comment by guwirth** [comment]
@skalaiyarasan please have a look here:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-the-analysis
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers

Sample: 
* https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/cppcheck_project
