### ISSUE TITLE
single small file takes 3 minutes to scan

### ISSUE THREAD

**Issue by megaloni** [SonarOpenCommunity/sonar-cxx#1242]
Just trying to run sonar scanner using the 0.9.7 version of the c++ community plugin with SQ 6.0 on this single file takes several minutes (the full-fledged file from our code base takes 8 minutes).

Full file:

```
#ifndef PROJECT_PARSINGTEST_H
#define PROJECT_PARSINGTEST_H

#include <boost/optional.hpp>

class FOO_BAR_CLASS
{
private:
   FOO_BAR_CLASS(
      boost::optional<std::string> && a,
      boost::optional<std::string> && b,
      boost::optional<std::string> && c,
      boost::optional<std::string> && d,
      boost::optional<std::string> && e)
   {
      //
   }

public:
   void create(
      boost::optional<std::string> && a,
      boost::optional<std::string> && b,
      boost::optional<std::string> && c,
      boost::optional<std::string> && d,
      boost::optional<std::string> && e)
   {
      new FOO_BAR_CLASS(
         std::forward<boost::optional<std::string>>(a),
         std::forward<boost::optional<std::string>>(b),
         std::forward<boost::optional<std::string>>(c),
         std::forward<boost::optional<std::string>>(d),
         std::forward<boost::optional<std::string>>(e));
   }
};

#endif   // PROJECT_PARSINGTEST_H
```

**Comment by guwirth** [comment]
Hi @megaloni ,

What are your setting? Do you include the path to boost? That could be one reason. In general I would not recommend to add paths to system includes. 

You can also try to turn debug information on to see where you are loosing time. https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

Another thing you can try is to use our latest 0.9.8 snapshot. You can download it from here https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts. 

Regards

**Comment by megaloni** [comment]
No, `sonar.cxx.includeDirectories=.`  I can try turning on more debug logging. If I remove any of those parameters the time drops dramatically (to just a few seconds) - I need all five to hit 3 minutes.

**Comment by guwirth** [comment]
@megaloni can you try with 0.9.8?

**Comment by guwirth** [comment]
@megaloni other idea could be to try with https://ci.appveyor.com/api/buildjobs/a75b68aijx0puejs/artifacts/sslr-cxx-toolkit%2Ftarget%2Fsslr-cxx-toolkit-0.9.8-SNAPSHOT.jar. Just start it and copy your sample into it to see how long it takes there (copy & paste code first to notepad and then into tool to ensure ASCII charset).

**Comment by guwirth** [comment]
No feedback I close this. Please reopen if still an issue.
