### ISSUE TITLE
US: SonarLint support

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1243]
As an user I like to use SonarLint in connected mode to get server results in VisualStudio.

---
SonarLint for VS does not support C++ community plugin.
Add support for SonarSource SonarLint.

In my opinion it would be sufficient to get messages from server inside of VS to fix it. Local analysis makes typically under C++ less sense because of long analysis time.

**Comment by guwirth** [comment]
Looking to SonarSource code I found https://github.com/SonarSource/sonarlint-visualstudio/commit/411177247169acbd09a87ba81fc5858e7f7c0ef2#diff-e5cb84d85d3c26f3c44e9d9f1006df57R131 (sqLanguage = "cpp"). Maybe this is the problem because our plugin is using `cxx` . Maybe we should also use `cpp`? Both plugins in parallel are anyway not possible because file extensions can only be assigned to one plugin. 

Second thing which seem to be missing is https://github.com/SonarSource/sonar-python/blob/master/sonar-python-plugin/pom.xml#L85.

**Comment by Bertk** [comment]
The SonarLint setting in the manifest will be set this way:
```
  <properties>
    <sonar.artifact.path>target/${project.artifactId}-${project.version}.jar</sonar.artifact.path>
    <sonar.pluginClass>org.sonar.plugins.cxx.CxxPlugin</sonar.pluginClass>
    <sonar.pluginName>C++ (Community)</sonar.pluginName>    
    <sonar.pluginName>C++ (Community)</sonar.pluginName>
    <sonar.sonarLintSupported>true</sonar.sonarLintSupported>
  </properties>
```
Updating the language key to `cpp` is a breaking change and I guess all cxx rule profiles and issues are affected.

**Comment by guwirth** [comment]
@Bertk have you tried if setting the properties alone helps.

> Updating the language key to cpp is a breaking change and I guess all cxx rule profiles and issues are affected.

Yes, would be for sure a breaking change.

**Comment by Bertk** [comment]
I will check this on next Saturday and also look into the details for a SonarLintProfileImporter() for VC++ or derived ruleset.

**Comment by jmecosta** [comment]
@guwirth @Bertk have you consider using my https://github.com/TrimbleSolutionsCorporation/VSSonarQubeExtension/releases? all sensors include the cxx-linter are currently supported for local analysis? among many other intersting things.

**Comment by guwirth** [comment]
@jmecosta will try it. But my feeling is that it would be easier if official tool would ssupport our plugin. Would be also easier to maintain on the long run...

**Comment by jmecosta** [comment]
@guwirth server side is something that does not fall under the scope of SonarLint, so i would not expect anything on that side. the only level of integration i can see happening at that level is if you are able to run the cxx-linter on the fly. But since the cxx-plugin is mostly based on external tools i dont see how this is going to be usefull. 

my extension, does all the above. So it syncs issues from server only, and you can run the linter and all the external sensors in a locally.

also remember official support for the cxx plugin at that level will never be possible because the c++ support in the SonarLint is to support the paid c++ plugin

**Comment by guwirth** [comment]
@jmecosta thanks for explanation. 

Personally I see less usage of a lint tool with C++. That's because in our case static code analysis, running the tests, coverage, ... needs about 30 min and developer are blocked during this time. That's the reason why we are doing it on servers in the background.

The point our developers are complaining is that they have to check the results in SQ and must switch to VS to fix it. 

The thing we are looking for is a possibility to display the SQ issues from the server inside of VS and be able to jump to the issue location with a double click.

**Comment by guwirth** [comment]
@jmecosta thanks for explanation. 

Personally I see less usage of a lint tool with C++. That's because in our case static code analysis, running the tests, coverage, ... needs about 30 min and developer are blocked during this time. That's the reason why we are doing it on servers in the background.

The point our developers are complaining is that they have to check the results in SQ and must switch to VS to fix it. 

The thing we are looking for is a possibility to display the SQ issues from the server inside of VS and be able to jump to the issue location with a double click.

**Comment by jmecosta** [comment]
@guwirth importing server side issues, you can do with my extension. it does exactly what you need.

but from experience here this hardly not enough. i will explain a bit own our process is now set.

1. Coverage, we use OpenCppCoverage and Google test (with gtest adapter) to quickly find coverage, this cover the use case where developer needs to see what is left to be covered. Tests are run in build farm using feature branch. So the SQ analysis has no meaning at this point.
2. Static code analysis, we have all tools integrated locally so the issues appear when you are typing. So they tend not to even reach the server. 
3.  we have nightly SQ builds and gate checks every iteration, where we detect points were coverage is lacking and tackle all issues that have not been addressed.

Before we had that kind of approach, but it just created unnecessary work, when ticket is done and needs to be open again to check the quality and fix the issues. so there is always double work for each ticket. People started complaining about that. So the linter during development solves this problem nicely.

Looking at dotnet, thats how all visual studio is setup currently. And this works really well.

If you are looking for server side issues in visual studio, then SonarLint is not the solution. Luckly i have that already in my extension :)

**Comment by guwirth** [comment]
@jmecosta thanks for sharing these internals.

We are doing it more or less similar but our main problem is the static code analysis. We are doing already an incremental analysis but this still takes about 30 minutes. My experience is that good/deep analysis takes about 10x compiling the code. Which tools are you using here?

Second question: why are you using OpenCppCoverage and not the VS coverage tool? What are the advantages?

**Comment by jmecosta** [comment]
@guwirth we are using, cppcheck, cpplint, vera, rats and the cxx-linter. analysis time per file is ok,  we have nightly also intel inspector, but that is impossible to get it running locally because of time. The tool also integrates clang, but i was not able to run it for each save of file, because it really is slow. So you can press a button and it gives the results

VS coverage comes with entreprise edition, we only have professional licenses ;)

**Comment by Bertk** [comment]
@guwirth, @jmecosta We use MS C++ compiler analysis and therefore a local analysis is not required but I like to see existing other issues from the SQ server. These issues should be visible at the exact source code line using [Light Bulb Suggestions. ](https://msdn.microsoft.com/en-us/library/dn903708.aspx) - such kind of lightweight solution would be perfect for now.
SonarLint does not support this for C++ community plugin and the integration will anyway only be possible if the SQ 6.0 APIs or newer are used.

**Comment by jmecosta** [comment]
@Bertk thanks for the links, i think i might add the light bulb provider (although i personally feel squiggle line and hover less clicks to get the information)

the link to the sq group mentions sonarlint for eclipse, that is a bit different than visual studio. Im am still unclear what are the integrations plans for this in visual studio.

**Comment by guwirth** [comment]
SonarLint supports only a limited  number of programming languages, an alternative is [SonarLink](https://github.com/etas/SonarLink).
