### ISSUE TITLE
C++ file skipped

### ISSUE THREAD

**Issue by kohldampfer** [SonarOpenCommunity/sonar-cxx#1253]
I have a small C++ file, which has this content:
```
int main(int argc, char **argv) {
    int[10] a;
    a[10] = 5;
    
    return 0;
}
```
After running sonar-scanner, on the SonarQube server, I do not see any vulnerabilities. But this file has one (Array out of index).

When looking into my C++ file, I see this Warning:

`WARN: [C:\svn\sonarqubetest\unsafe.cpp:1]: skip declarartion: int main ( int argc , char * * argv ) {`

Why is SonarQube skipping this file?

**Comment by SonarOpenCommunityAdmin** [comment]
@kohldampfer is this valid C++?

Think should be
```C++
int main(int argc, char **argv) {
    int a[10];
    a[10] = 5;
    
    return 0;
}
```
See also https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Error-Recovery

**Comment by kohldampfer** [comment]
I changed that and the warning has gone. But SonarQube still tells me that there are no issues.

![sonarqube-unsafe-cpp-1](https://user-images.githubusercontent.com/20419801/31711921-ed040da6-b3f9-11e7-8cf2-8ac05af5bd6d.png)

And I have the latest C++ Community Plugin installed

![sonarqube-unsafe-cpp-2](https://user-images.githubusercontent.com/20419801/31711944-fe4d1bf2-b3f9-11e7-8119-a4bd4171264b.png)

**Comment by guwirth** [comment]
@kohldampfer the plugin itself is doing no (less) checks. In case of static code analysis you have to run a static code analyser first outside of the tool and then import the resulting report. That's one major difference to the commercial one which has own checks. On the other side you can integrate your own already existing tool chain.

* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-the-analysis
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers
* sample: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/cppcheck_project

**Comment by kohldampfer** [comment]
Ah OK, that explains a lot. Thank you for your time. You can close this ticket now.
