### ISSUE TITLE
SonarQube.Scanner.MSBuild.exe /d:sonar.cxx.includeDirectories not working

### ISSUE THREAD

**Issue by DanielHWe** [SonarOpenCommunity/sonar-cxx#1257]
Hi,

I have mixed C#/C++ Visual Studio projects. Sonar-cxx works fine as long as I use sonar-scanner.bat, but new versions of C# Plugin requires to use the msbuild scanner.
In this case it seams the Sonar-cxx plugin does not support full path like C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\include.
Sample, I want to scan E:\src\ProjectA\ProjectA.vcxproj Call:
E:\src>SonarQube.Scanner.MSBuild.exe /d:sonar.cxx.includeDirectories="C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\include"
But includes are not found.
So I try:
E:\src>SonarQube.Scanner.MSBuild.exe /d:sonar.cxx.includeDirectories="'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\include'"
Now I got an additional error:
Can not get canonical form of: 'E:\src\ProjectA''C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\include'

So it seams project path and include path are just added to each other.
I checked also the SonarQubeAnalysisConfig.xml file, generated by SonarQube.Scanner.MSBuild.exe and here the sonar.cxx.includeDirectories is like set.

**Comment by guwirth** [comment]
@DanielHWe maybe @jmecosta or @Bertk can help you?

**Comment by guwirth** [comment]
@DanielHWe Goggling a little bit I think there are two variants to set parameters:
```
/d:property=value
```
or (!!! property **and** value are inside of apostrophes !!!)
```
/d:"property=value"
```
Second problem is typically that you have to try out if you have to use slash or backslash (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues).

So in your case I would try slash, backslash and double backslash
```
/d:"property=C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/include"
/d:"property=C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include"
/d:"property=C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\include"
```

I'm interested in the result. So keep us in the loop.

**Comment by Bertk** [comment]
Please check also discussion #616. _SonarQube.StaticAnalysis.props_ uses information from MSBuild to set SQ properies for the analysis and more ...

**Comment by jmecosta** [comment]
yeah i think those are a bit tricky to get working with parameters. you can use also if you want this wrapper:  https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/releases it will reuse the properties from your properties files and patch everything you need in the generated files that the msbuild runner uses.  this is a step only, so there is no begin or end

    Usage: CxxSonarQubeMsbuidRunner [OPTIONS]
    Runs MSbuild Runner with Cxx Support
    
    Options:
        /A|/a:<amd64, disabled>
        /B|/b:<parent_branch  : in multi branch confiuration. Its parent branch>
        /C|/c:<Permission template to apply when using feature branches>
        /D|/d:<property to pass : /d:sonar.host.url=http://localhost:9000>
        /E|/e reuse reports mode, cxx  static tools will not run. Ensure reports are placed in default locations.
        /F|/f disable code analysis in solution.
        /G|/g enable verbose mode.
    
        /I|/i wrapper will install tools only. No analysis is performed
        /J|/j:<number of processor used for msbuild : /m:1 is default. 0 uses all processors /m>
        /K|/k:<key : key>
    
        /M|/m:<solution file : mandatory>
        /N|/n:<name : name>
    
        /P|/p:<additional settings for msbuild - /p:Configuration=Release>
        /Q|/q:<SQ msbuild runner path>
        /R|/r:<msbuild sonarqube runner -> 1.1>       
        /S|/s:<additional settings filekey>
        /T|/t:<msbuild target, default is /t:Rebuild>
    
        /V|/v:<version : version>
        /X|/x:<version of msbuild : vs10, vs12, vs13, vs15, default is vs15>
