### ISSUE TITLE
SonarQube preview analysis mode

### ISSUE THREAD

**Issue by deadloko** [SonarOpenCommunity/sonar-cxx#1259]
Hi, first of all, thank's for great plugin.
In our ci we use SonarQube for reporting issues directly to commits comments with help of gitlab plugin. However, gitlab plugin works only when sonar analysis mode is set to `preview`. Unfortunately cxx community plugin not finding any reports in this mode, even though report files exists in correct paths (log below). If i run analisys in publish mode on same project, cxx plugin working correctly. 

We using SonarQube Version 6.5.0.27846
Cxx community plugin version 0.9.8-SNAPSHOT

Help would be appreciated.
```
16:08:51.590 DEBUG: 'c++ SquidSensor' skipped because there is no related file in current project
16:08:51.609 DEBUG: 'c++ RatsSensor' skipped because there is no related file in current project
16:08:51.627 DEBUG: 'c++ CppCheckSensor' skipped because there is no related file in current project
16:08:51.643 DEBUG: 'c++ PCLintSensor' skipped because there is no related file in current project
16:08:51.659 DEBUG: 'c++ DrMemorySensor' skipped because there is no related file in current project
16:08:51.675 DEBUG: 'c++ CompilerSensor' skipped because there is no related file in current project
16:08:51.691 DEBUG: 'c++ VeraxxSensor' skipped because there is no related file in current project
16:08:51.707 DEBUG: 'c++ ValgrindSensor' skipped because there is no related file in current project
16:08:51.722 DEBUG: 'c++ ClangTidySensor' skipped because there is no related file in current project
16:08:51.737 DEBUG: 'c++ ClangSASensor' skipped because there is no related file in current project
16:08:51.763 DEBUG: 'c++ ExternalRulesSensor' skipped because there is no related file in current project
16:08:51.778 DEBUG: 'c++ CoverageSensor' skipped because there is no related file in current project
```

**Comment by guwirth** [comment]
Hi @deadloko 

* How do you call the cxx plugin - with which scanner / command line?
* Do you know which API we have to support?

Regards

**Comment by deadloko** [comment]
@guwirth 
* I tried executing scanner from jenkins pipeline (jenkins plugin) and from command line. 
* In commit that i trying to analyze there is no c/cpp files modified only added reports for compiler warnings.
* As far as i can see from [this](https://github.com/SonarSource/sonarqube/blob/ef2ca5b33e5795b841d45e0b20fef3cb90391719/sonar-scanner-engine/src/main/java/org/sonar/scanner/sensor/SensorOptimizer.java), sensors for given language not executing at all if there is no language files changed (method `fsCondition`). However Sensor c++ XunitSensor gets executed. The only difference i see between xunit sensor and other sesnsor is that `execute()` method is implemented instead of returning `super()` (sorry if misunderstood, i am not java programmer). 
* If i modify some c/cpp file, sensors gets executed and i can see issues, but only for the file i have modified.

As conclusion, this is, as i see it, proper SonarQube behavior, not a plugin problem, maybe, it should be represented in docs?

**Comment by guwirth** [comment]
@deadloko maybe we should override `shouldExecuteOnProject`:

https://github.com/SonarSource/sonar-python/blob/a68e22b3bf9f47b84e974d251e3b1bec911cd038/sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonReportSensor.java#L49

**Comment by deadloko** [comment]
@guwirth yes, i think, that should do

**Comment by guwirth** [comment]
@deadloko 

> ... and from command line. 

With which scanner (sonar-scanner)?

> In commit that i trying to analyse there is no c/cpp files modified only added reports for compiler warnings.

Think there must be an update if a source file is changing or a report file is changing. The sensors are not able to find out if something is modified so they analyse always.  The only think they can find out is if there are corresponding files/reports. Don't know how this gitlab/github plugins are working. Maybe they forward only changed files to the plugin?

In the latest documentation I found: [DEPRECATED FROM SQ 6.6
sonar.analysis.mode](https://docs.sonarqube.org/display/SONAR/Analysis+Parameters#AnalysisParameters-ParametersspecifictoIntegration)

> As far as i can see from [this](https://github.com/SonarSource/sonarqube/blob/ef2ca5b33e5795b841d45e0b20fef3cb90391719/sonar-scanner-engine/src/main/java/org/sonar/scanner/sensor/SensorOptimizer.java), sensors for given language not executing at all if there is no language files changed (method `fsCondition`). 

Think `fsCondition `checks only if there is a file for a sensor?

> If i modify some c/cpp file, sensors gets executed and i can see issues, but only for the file i have modified.

What do you mean with this? Is everything working if you are changing a source code file and `mode=preview`?

**Comment by deadloko** [comment]
> What do you mean with this? Is everything working if you are changing a source code file and mode=preview?

Yes. If i commit this changes and provide hash as sonar parameter.

> With which scanner (sonar-scanner)?

With [this](https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner) scanner (linux 64bit)

> Think there must be an update if a source file is changing or a report file is changing. The sensors are not able to find out if something is modified so they analyse always. The only think they can find out is if there are corresponding files/reports. Don't know how this gitlab/github plugins are working. Maybe they forward only changed files to the plugin?

>In the latest documentation I found: DEPRECATED FROM SQ 6.6
sonar.analysis.mode

Yes i saw it too, they deprecated it, but not deleted. I think they will provide some way to run `preview` analysis instead. As i see it gitlab/github plugins only provide files that changed to sonarqube server, it is server that decides to run or not sensors.

> Think fsConditionchecks only if there is a file for a sensor?

Yes it is, but what if i, for example, created a branch in our project, where i update ci to generate clang compiler reports and provide them to sonarqube. I didn't changed any sources (and reports aren't in vcs), but my branch analysis now reports almost 10k new bugs. `Preview` analysis mode, in the same time, not reporting any new bugs as i didn't changed any sources. I think, instead, it should report that there is 10k new bugs that wasn't assosiated with commit lines.

**Comment by guwirth** [comment]
@deadloko 

> ... branch analysis now reports almost 10k new bugs

In the past a branch was like a new project. If you add issues the first time to a branch they are "new". Think SQ like to improve this with 6.7. Maybe you should ask them in the SQ forum.
