### ISSUE TITLE
Parsing VS2017 warnings

### ISSUE THREAD

**Issue by NinjaDanz3r** [SonarOpenCommunity/sonar-cxx#1264]
Hello!
I'm currently trying to parse a msbuild log produced with msbuild for Visual Studio 2017, but while I am able to find the log file Sonar won't parse the warnings.

Output from build server:
```
INFO: Sensor CxxCompilerSensor [cxx]
INFO: Searching reports by relative path with basedir 'Path to basedir' and search prop 'sonar.cxx.compiler.reportPath'
INFO: Scanner found '1' report files
INFO: Parser will parse '1' report files
INFO: Processing report 'Path to log'
INFO: Scanner 'Visual C++' initialized with report 'Path to log', CharSet= 'UTF-8'
INFO: Parsing 'Visual C++' format (UTF-8)
INFO: Using pattern : '^.*>(.*)((d+))x20*:x20warningx20(Cd+):(.*)$'
INFO: C++ compiler Warnings processed = 0
INFO: Sensor CxxCompilerSensor [cxx] (done) | time=16ms
```
As you see, no warnings are processed, and I have abbreviated full file paths to 'Path to x'

I've tried the different regex's listed under 'Running the analysis' compiler section, but can't get it to work.

Sample warning from the build log:
```
Path to file(32): warning C4244: '=': conversion from 'float' to 'int', possible loss of data [Path to project]
```

How can I make this work?

**Comment by Bertk** [comment]
Please check the Wiki [Microsofts Visual Studio Compiler](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers#microsofts-visual-studio-compiler). 
Here you find the regular expression for single and multiple (concurrent) project builds. 

> /maxcpucount[:number]  Specifies the maximum number of concurrent processes to use when building.

This is the one for single process builds. Please use this one.
```
^(.*)\((\d+)\)\x20*:\x20warning\x20(C\d+):(.*)$
``` 
Maybe you want to remove the project path from the issue text using this regular expression
```
^(.*)\((\d+)\)\x20*:\x20warning\x20(C\d+):(.*)\x20\[.*\]$
```

**Comment by NinjaDanz3r** [comment]
I've tried both of those but it still says that 0 compiler warnings were processed.
Another piece of information is that I use the following options to generate the log from MSBuild:
` /t:rebuild /p:Configuration=Release;WarningLevel=3 /fileLogger /fileLoggerParameters:WarningsOnly;LogFile=PathToLog\VSerror.log;Verbosity=detailed;Encoding=UTF-8`

**Comment by Bertk** [comment]
Please check the following:
a) compiler rules are activated in the default C++ quality profile
b) setting for the file encoding (UTF-8 or UTF-16) of the log file

**Comment by NinjaDanz3r** [comment]
Checked both, compiler rules were not activated (I wrongly assumed that they would be activated by default in the default c++ profile.) and the log is in UTF-8-BOM.
Still no processed errors.

**Comment by Bertk** [comment]
Please create a UTF-8 log file without BOM and tray again.

You can also find some more information here: [https://github.com/Bertk/cpptesting](https://github.com/Bertk/cpptesting).
The CI build for this project reports compiler errors.

![build-result](https://user-images.githubusercontent.com/2315215/32095239-cb1fe092-bb02-11e7-982c-68480109ec5e.PNG)
and I use the following configuration

![build-conf4](https://user-images.githubusercontent.com/2315215/32095277-e81b154a-bb02-11e7-8060-94847a07923d.PNG)

**Comment by NinjaDanz3r** [comment]
I use about the same configuration (most importantly, UTF-8 encoding) but it still saves the log as UTF-8 BOM. I managed to resolve it by saving as ASCII and then converting it to UTF-8.
Still no processed warnings.

**Comment by Bertk** [comment]
Please provide a small excerpt of the log file. I can check the regular expression and you should try to get some information from the analysis log file.

The scanner settings for an analysis are available on the SQ server (Administration->background tasks)
Sample **Scanner Context: CppTest [Project Analysis]** for a TFS vNext build:
```
Settings for module: CppTest:CppTest:D6CF9655-E063-4F39-9401-FB0B77AC3347
  - sonar.cs.vscoveragexml.reportsPaths=C:\agent\_work\1\s\TestResults\TFS-Build_TEAM-BUILD 2017-11-02 16_55_20\In\TEAM-BUILD\TFS-Build_TEAM-BUILD 2017-11-02 16_55_05.coveragexml
  - sonar.cxx.compiler.charset=UTF-8
  - sonar.cxx.compiler.parser=Visual C++
  - sonar.cxx.compiler.regex=^\x20+(.*)\((\d+)\)\x20*:\x20warning\x20(C\d+):\x20(.*)\x20\[C:\\agent\\_work\\1\\s\\Source\\SQCxxTestData\\SQCxxTestData.vcxproj\]$
  - sonar.cxx.compiler.reportPath=C:\agent\_work\1\s\CppTesting.sln.log
```
