### ISSUE TITLE
condition coverage not shown as covered/uncovered in sonarqube

### ISSUE THREAD

**Issue by tovishwendra** [SonarOpenCommunity/sonar-cxx#1266]
I am trying to import bullseye coverage report using sonar cxx community plugin. In sonar qube i am not able to see which of the conditions are covered/uncovered, even though it shows the percent of the condition coverage. For line coverage it shows which of the functions are covered/uncovered by highlighting the covered ones with green color and uncovered ones with red color, but same difference its not showing for condition coverage.

**Comment by guwirth** [comment]
Hi @tovishwendra,
* Which SQ version do you use?
* Which plugin version?
* Which Bullseye file format?
* Have you tried to turn debug info on to get more information https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information?

Regards

**Comment by tovishwendra** [comment]
Hi guwirth, 
Please find the answers to your question below.

Which SQ version do you use?
SQ version is 6.1
Which plugin version?
We are using Sonar cxx community plugin version 0.9.7
Which Bullseye file format?
Bullseye version is 8.9.94

Regards,
Vishwendra
