### ISSUE TITLE
How to check the result of Cppcheck on the SQ server?

### ISSUE THREAD

**Issue by dg-w36** [SonarOpenCommunity/sonar-cxx#1267]
Hello,
I install the SQ server, cxx plugin, and run code analysis on this [sample project](https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/sonar-cxx-plugin/src/samples/SampleProject2). I do get the report locally, such as this:
``` cppcheck report file
<?xml version="1.0" encoding="UTF-8"?>
<results>
<error file="src/lib/component1.cc" line="17" id="unusedVariable" severity="style" msg="Unused variable: x"/>
<error file="src/lib/component1.cc" line="37" id="unreadVariable" severity="style" msg="Variable 'i' is assigned a value that is never used."/>
<error file="src/lib/component1.cc" line="47" id="deallocDealloc" severity="error" msg="Deallocating a deallocated pointer: ip"/>
<error file="src/lib/component1.cc" line="47" id="doubleFree" severity="error" msg="Memory pointed to by 'ip' is freed twice."/>
<error file="src/lib/component1.cc" line="32" id="uninitvar" severity="error" msg="Uninitialized variable: a"/>
<error file="src/lib/component2.cc" line="16" id="unusedVariable" severity="style" msg="Unused variable: x"/>
<error file="src/lib/component2.cc" line="36" id="unreadVariable" severity="style" msg="Variable 'i' is assigned a value that is never used."/>
<error file="src/lib/component2.cc" line="46" id="deallocDealloc" severity="error" msg="Deallocating a deallocated pointer: ip"/>
<error file="src/lib/component2.cc" line="46" id="doubleFree" severity="error" msg="Memory pointed to by 'ip' is freed twice."/>
<error file="src/lib/component2.cc" line="31" id="uninitvar" severity="error" msg="Uninitialized variable: a"/>
<error file="src/lib/component1.cc" line="24" id="unusedFunction" severity="style" msg="The function 'do_valgrind_errors' is never used."/>
<error id="missingInclude" severity="style" msg="Cppcheck cannot find all the include files. Cppcheck can check the code without the include files found. But the results will probably be more accurate if all the include files are found. Please check your project's include directories and add all of them as include directories for Cppcheck. To see what files Cppcheck cannot find use --check-config."/>
</results>
```
The result on the SQ server like this:
![result](https://github.com/dg-w36/pic_server/raw/master/report_cppcheck.png)
and can see there are 12 cppcheck errors, BUT when i click the cppcheck there is no result display, like this:
![result2](https://github.com/dg-w36/pic_server/raw/master/no_error.png)
**How can i get the error massage in the cppcheck error page on the SQ server just like the Code Smells page:**
![Code_smells](https://github.com/dg-w36/pic_server/raw/master/code_smells.PNG)

**Comment by guwirth** [comment]
Hi @dg-w36,
* Which SQ version are you using?
* Which plugin version are you using?

Regards

**Comment by dg-w36** [comment]
hi @guwirth ,
I use the SQ 5.6.7 Lts, and the cxx plugin is 0.9.7 which is download from the release page.
Another question, How to use the **sslr-cxx-toolkit.jar** ? 
Thanks.

**Comment by guwirth** [comment]
@dg-w36 please try with 0.9.8-snaphshot this should be fixed with #1030.
Please give us feedback.

[Downloads](https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts)

**Comment by dg-w36** [comment]
Thinks @guwirth ,I will have a try.

**Comment by dg-w36** [comment]
Hello, @guwirth 
I install the 0.9.8-snaphshot . 
**There is no "C++" item in the "Measures page" after change the plugin**, see below:
![](https://github.com/dg-w36/pic_server/raw/master/0_9_7.png)
Except this change, I also find that the massage in report XML file (such as the cppcheck-report.xmlvalgrind-report.xml ) is integrated with the **Bugs** and **Code smell**. That's good!
Could you give a sample analysis results of the [sample project](https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/sonar-cxx-plugin/src/samples/SampleProject2) for new user to compare with.
Thanks.

**Comment by guwirth** [comment]
@dg-w36 please try again with release 0.9.8.
