### ISSUE TITLE
SQ community C++  plug-in shall use SQ API 6.5 or later 

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx#1272]
The C++ community plug-in uses SQ API 5.6 but the latest features e.g. SonarLint (#1243) are only supported with SQ API 6.5.

@guwirth I already started to adapt the java sources but have some issues with the sensor unit tests.

**Comment by guwirth** [comment]
@Bertk if you want we can start this on a second branch in parallel?

**Comment by Bertk** [comment]
@guwirth Yes another branch for the next version will be very helpful for the transition to SQ 6.5 API.
Maybe we should support both SQ version for the next 6 months anyway.

**Comment by guwirth** [comment]
@Bertk the biggest problem I see is the maintenance effort. I would like to support only one version. Think 6.7 LTS is planned for 7th November (not far away) and then we can start with the next version. Next version means for me support only 6.7++.
Other point I see is I don't know how to handle different branches in the CI. It's for sure also some work to rework it?
So my idea with the second branch was only intended to be a short term solution in case you can't wait another week till 0.9.8 release.

**Comment by Bertk** [comment]
@guwirth I am fine with this proposal. Meanwhile I synced the branch with the updates
https://github.com/Bertk/sonar-cxx/tree/SQAPI6.5

- 2 coverage unit tests are failing (now disabled)
- sslr-cxx-toolkit build fails (see below)
- integration tests not checked

```
Error reading org/sonar/api/web/page/Page.class: INVOKESPECIAL/STATIC on interfaces require ASM 5
Error reading org/sonar/api/scan/filesystem/FileExclusions.class: INVOKESPECIAL/STATIC on interfaces require ASM 5
Error reading org/sonar/api/config/PropertyDefinition$Builder.class: INVOKESPECIAL/STATIC on interfaces require ASM 5 
```

**Comment by Bertk** [comment]
SQ V6.6 API shows 2 more errors.
```
SQ6.6
Error reading org/sonar/api/resources/ResourceTypes.class: INVOKESPECIAL/STATIC on interfaces require ASM 5
Error reading org/sonar/api/utils/UriReader.class: INVOKESPECIAL/STATIC on interfaces require ASM 5
Error reading org/sonar/api/web/page/Page.class: INVOKESPECIAL/STATIC on interfaces require ASM 5
Error reading org/sonar/api/scan/filesystem/FileExclusions.class: INVOKESPECIAL/STATIC on interfaces require ASM 5
Error reading org/sonar/api/config/PropertyDefinition$Builder.class: INVOKESPECIAL/STATIC on interfaces require ASM 5
SQ6.5
Error reading org/sonar/api/web/page/Page.class: INVOKESPECIAL/STATIC on interfaces require ASM 5
Error reading org/sonar/api/scan/filesystem/FileExclusions.class: INVOKESPECIAL/STATIC on interfaces require ASM 5
Error reading org/sonar/api/config/PropertyDefinition$Builder.class: INVOKESPECIAL/STATIC on interfaces require ASM 5

```

**Comment by Bertk** [comment]
@guwirth Ready to merge :blush: Should I create a PR (main) or should this go into a branch?
```
git push  <REMOTENAME> <BRANCHNAME> 
```

**Comment by guwirth** [comment]
@Bertk sounds good. Would prefer a PR.

**Comment by guwirth** [comment]
@Bertk I close this, there are more detailed issues with remaining topics.
