### ISSUE TITLE
ERROR: Cannot save Conditions Hits for Line 'nnn' , ignoring measure.

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1278]
Hi,

Testing 0.9.8 with SQ 5.6.4 I get:

```
ERROR: Cannot save Conditions Hits for Line '114' , ignoring measure. 
java.lang.IllegalStateException: Line 114 is out of range in the file xxx\yyy.cpp (lines: 113)
	at org.sonar.api.internal.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[sonar-scanner-engine-shaded-5.6.4.jar:na]
```

There is a problem if no empty newline is at the end.
Maybe also a problem with line number calculation (starting with 0 or 1)?

Regards,

**Comment by Bertk** [comment]
@guwirth Has the source file an empty line at the end of the file? This is also a problem which I discovered in the past.

**Comment by guwirth** [comment]
@Bertk there is no empty line at the end of the file. But looking to the report there is an item for line 114. It's code from a global variable dtor. So seems to be a coverage tool error.
