### ISSUE TITLE
ERROR: Cannot save Line Hits for Line 'xxx.cpp' : '{}', ignoring measure

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1279]
Hi,

Testing with 0.9.8 and SQ 5.6.4 I get:

```
ERROR: Cannot save Line Hits for Line 'xxx\yyy.cpp' : '{}', ignoring measure
java.lang.IllegalStateException: Line 88 is out of range in the file xxx/yyy.cpp (lines: 85)
	at org.sonar.api.internal.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[sonar-scanner-engine-shaded-5.6.4.jar:na]
```

Line number in error message missing?

Regards,

**Comment by Bertk** [comment]
@guwirth Please check the number of lines in the source file. Maybe you add 3 empty lines as a workaround. 
I saw this behavior before and therefor this is not a regression. Until now we do not know whether the coverage tool or SQ counts the lines of a file precisely.
