### ISSUE TITLE
sonar.cxx.coverage.forceZeroCoverage=true no more working with 5.6 LTS

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1281]
Hi,

Analysing a project with 0.9.7 and 0.9.8 I get a big difference in a project with less coverage and setting `sonar.cxx.coverage.forceZeroCoverage=true`. With 0.9.7 it's 5% and with 0.9.8 50%?

Regards,

**Comment by Bertk** [comment]
@guwirth The current LTS is V5.6.7. Did you compare the values in SQ with the coverage report? I am not aware of any update on the V5.6.7 and the last updates were done for V6.2 and later which calculates the executable code lines and the covered lines in a different way.

**Comment by guwirth** [comment]
@Bertk I'm doing the first test with a bigger code base now. On our productive servers we are still using 0.9.7 and SQ 5.6.4. Means this is the first 'big' test with 0.9.8:

Problems seems to be that not all files are zeroed out.
* in case of 5% I get in the coverage list wit 0.9.7:  100 of 715 shown
* in case of 50% I get in the coverage list with 0.9.8: 53 of 53 shown

No idea why not working. LOG file shows message `INFO: Zeroing coverage information for untouched files`.

**Comment by guwirth** [comment]
turning debug info on (-X) I get:
```
22:03:52.407 INFO: Zeroing coverage information for untouched files
22:03:52.407 DEBUG: Zeroing UNIT coverage measures for file 'xxx/yyy.h'
22:03:52.408 DEBUG: Zeroing UNIT coverage measures for file 'xxx/yyy.cpp'
... (715 files)
```

So `zeroMeasuresWithoutReports `and `saveZeroValueForResource` are called but I can't see results in UI. Seems to be a problem in `saveZeroValueForResource`?

**Comment by guwirth** [comment]
extending the logging I get:
```
22:03:52.407 INFO: Zeroing coverage information for untouched files
22:03:52.407 DEBUG: Zeroing UNIT coverage measures for file 'xxx/yyy.h' : linesOfCode='0'
22:03:52.408 DEBUG: Zeroing UNIT coverage measures for file 'xxx/yyy.cpp' : linesOfCode='0'
...
22:03:53.956 DEBUG: zeroMeasuresWithoutReports: total=1081 / unit=1081 / it=0 / overall=0
```
Problem is that all linesOfCode are 0?

**Comment by guwirth** [comment]
@Bertk think I found the problem.

The map is using a reference to set (linesOfCode):
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/visitors/CxxFileLinesVisitor.java#L206

But with every new file there is a clear of linesOfCode:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/visitors/CxxFileLinesVisitor.java#L184

As a result for all items in the map the linesOfCode is empty. How can I fix this?
