### ISSUE TITLE
Using sonar-cxx in sonarcloud.io

### ISSUE THREAD

**Issue by BotellaA** [SonarOpenCommunity/sonar-cxx#1302]
Hello,

I am new at Sonar. I managed to configure sonarcloud.io and Travis-CI.
I am wondering if there is a way to use sonar-cxx in sonarcloud.io?
Or if it works only with my own Sonar instance (which I do not have).

Thank you for your answer

**Comment by guwirth** [comment]
Hello @BotellaA,

we are already in SonarCloud, see https://sonarcloud.io/dashboard?id=org.sonarsource.sonarqube-plugins.cxx%3Acxx. It's currently working only for the master branch, would be great if you could support how to add it also to PRs.

Regards,

**Comment by BotellaA** [comment]
Thanks for your answer but I did not well explain my situation...

I want to use sonar-cxx in my own project but I only have access to sonarcloud.io. I am guessing that sonar-cxx has to be installed on sonarcloud.io to be able to use it but it does not seem to be installed (https://sonarcloud.io/api/plugins/installed).

So, is there a way to use your sonar-cxx with sonarcloud.io for my project?

**Comment by guwirth** [comment]
Hi @BotellaA , I'm sorry but SonarSource is only supporting there own plugins in SonarCloud. There is no way to use other plugins there.

**Comment by BotellaA** [comment]
Ok, too bad. Thanks for your time.

**Comment by IvanBoyko** [comment]
@BotellaA ,
don't give up, support OpenSource :)
You can easily start a SonarQube server in container: `https://hub.docker.com/_/sonarqube/`

**Comment by BotellaA** [comment]
I will take a look at this as soon as possible. Thank you for the link.
