### ISSUE TITLE
No issues shown after update to 0.9.8 and Sonarqube 6.7

### ISSUE THREAD

**Issue by stefansta** [SonarOpenCommunity/sonar-cxx#1305]
I have updated to the cxx plugin 0.9.8 and from Sonarqube 6.3.2 to 6.7. After the update no issues for my project are shown any more.

**Comment by guwirth** [comment]
@stefansta please turn debug info on and have a look to the resulting LOG file.
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

**Comment by phcouton** [comment]
I was faced with a similar problem. I was using the default profile (Sonar Way), and when I switched to SQ 6.7, all the C ++ rules were disabled in the default profile.

The default profile is read-only, so rules cannot be enabled. I had to copy the default profile into a new one, and manually enable the C ++ rules in it. This works for me now.
