### ISSUE TITLE
SonarSource Plugin and Sonar-CXX Plugin in parallel

### ISSUE THREAD

**Issue by niecore** [SonarOpenCommunity/sonar-cxx#1328]
Hello dear Community,

Is there a official guideline on how to use the SonarSource Plugin and the Sonar-CXX Plugin in parallel?

Currently we archive the result by removing all file extensions from the Sonar-CXX Plugin responsibility. When a user wants to use the  Sonar-CXX Plugin he has to force the language to `c++` and set his file extensions via the option `sonar.lang.patterns.c++`.

This works fine so far. Unfortunately it seems a little bit confusing to have now Rules for `c++` and `C++`. 

 Is there an option to change the language key of the  Sonar-CXX Plugin from 'c++' to i.e. 'C++ (Community Plugin)'?

**Comment by guwirth** [comment]
> Is there a official guideline on how to use the SonarSource Plugin and the Sonar-CXX Plugin in parallel?

Hi @niecore,

As far as I know there is no way to use them in parallel. This is because file extensions (e.g. .cpp) has to be unique assigned to **one** plugin.

> When a user wants to use the Sonar-CXX Plugin he has to force the language to c++ and set his file extensions via the option sonar.lang.patterns.c++.

Don't understand this. For my understanding you have to set properties below.  How exactly you are doing this?

```INI
sonar.language=c++
sonar.cxx.suffixes.sources=...
```

> Unfortunately it seems a little bit confusing to have now Rules for c++ and C++.

Each plugin has a unique name and key. We are using `c++` for name and key and `cxx` as property key.
What is the commercial plugin using?

> Is there an option to change the language key of the Sonar-CXX Plugin from 'c++' to i.e. 'C++ (Community Plugin)'?

Changing the language key would mean that all current users are loosing there history. So has to be discussed...

A general question: Why do you need both plugins in parallel. What's missing in the one or in the other?

Regards,

**Comment by niecore** [comment]
Thanks for you answer @guwirth .

First of all I must state, that a user has to decide which of the two plugins he wants to use. By using them in parallel I mean that both plugins are available on the SonarQube instance and the user can somehow determine which plugin he wants to run.

> As far as I know there is no way to use them in parallel. This is because file extensions (e.g. .cpp) has to be unique assigned to one plugin.

To bypass that restriction I remove all file extensions from the Sonar-CXX Plugin responsibility in the global configuration. 

When a user wants to use the Sonar-CXX Plugin he has to do two things:

1. Force the language to c++
`sonar.language=c++`
2. Set/Overwrite the file extensions for the language
`sonar.lang.patterns.c++=**/*.c,**/*.h,**/*.C,**/*.H`

When a user wants to use the SonarSource Plugin no special configuration is needed.

> A general question: Why do you need both plugins in parallel. What's missing in the one or in the other?

Reason behind this is, that each of the plugins as advantages. The Sonar-CXX Plugin i.e. supports xUnit reports, the SonarSource Plugin does not.

> What is the commercial plugin using?

The SonarSource Plugin uses `C` and `C++` as the names.

> Changing the language key would mean that all current users are loosing their history. So has to be discussed...

Maybe there is way to have this name configurable?

**Comment by guwirth** [comment]
> When a user wants to use the Sonar-CXX Plugin he has to do two things:
>    Force the language to c++
>    sonar.language=c++
>    Set/Overwrite the file extensions for the language
>    sonar.lang.patterns.c++=**/*.c,**/*.h,**/*.C,**/*.H

For my understanding setting no `sonar.language` means multi language support.
```INI
sonar.language=c++ // using community plugin
sonar.language=C++ // using commercial plugin?
```
So setting/ deleting the `sonar.cxx.suffixes.sources` should be sufficient? Problem I see is that using key `C++` for both plugins it would no more be possible to use them both?

> Reason behind this is, that each of the plugins as advantages. The Sonar-CXX Plugin i.e. supports xUnit reports, the SonarSource Plugin does not.

Means you don't need the whole plugin you need only some sensors of it? I also thought about turning specific sensors of the community plugin on or off to run it in parallel. Normally it should be possible to read the source files with one plugin and add e.g. unit test reports, coverage results, ... with another sensor in another plugin. In your case it would be like this that the Commercial Plugin would read the files and in parallel you would use the Community Plugin sensors for e.g. xUnit (without reading the files into DB again).

**Comment by guwirth** [comment]
@niecore what do you see in the rules section from the commercial plugin?

![grafik](https://user-images.githubusercontent.com/6077367/33031257-0665a15e-ce1e-11e7-862e-65414b16828e.png)

**Comment by niecore** [comment]
![grafik](https://user-images.githubusercontent.com/5686845/33066661-34895100-ceac-11e7-94b1-aae755574cf0.png)

Everything is working fine so far but here we see the confusing part for the user.  It's inconvenient that there the two languages 'c++' and 'C++'. That also leads to my core question:

> Is there an option to change the language key of the Sonar-CXX Plugin from 'c++' to i.e. 'C++ (Community Plugin)'?

But it seems like that there is no option.

**Comment by guwirth** [comment]
Hi @niecore,

Think it's a little bit more complicated, there is more than one label. Below a comparison between community and commercial plugin (C & C++):

**C++** property | community | commercial 
 --- | --- | ---
plugin key | cxx | cpp
plugin name | c++ | C++
config property key | sonar.cxx... | ???
repository key | cxx | cpp

**C** property | community | commercial 
 --- | --- | ---
plugin key | c | c
plugin name | c | C
config property key | sonar.c... | ???
repository key | c | c

* First of all I think **plugin key** must be unique. Think here we have already a problem with the C plugin? To try that out you can try to install C pugin together with commercial one on one server. Fear you get an error during server start. We also though about make this also **cpp** to have SonarLint support. The tool from SonarSource is supporting key cpp only. But this would prevent installing both in parallel.
* Second the **property name** is just a label. In your concrete case it would help that we change it to uppercase C++. That would mean that all rules are below this one label. Inside the **repository key** is then still different. Means commercial rules are in `cpp:...` and community in `cxx:...` repository. Think this makes sense to avoid an overlap.
* Think makes sense that **config properties in sonar-project.properties** have a different key. To have both in parallel in one file?
* **repository key** is the label you see in the upper right corner of a rule, e.g. `cpp:PPBadIncludeForm`.

Feedback is welcome.

Regards,

**Comment by niecore** [comment]
This makes things much clearer now. I think changing the **plugin name** to a common value would be great since it is mapped to the language. If you think that this will not affect any of the existing projects I would like to do the changes.

But in overall it seems like that a parallel support was never considered during the design.

I don't know which effect it might have to change the **plugin keys** in this state. If it will have low effect, it could also be considered to change the keys of the community plugins to something like `cpp_community` and `c_community` to be completely collision free.

**Comment by guwirth** [comment]
@niecore because we are not using the commercial plugin: can you give us a sample how the configuration of the commercial plugin looks like.

> This makes things much clearer now. I think changing the plugin name to a common value would be great since it is mapped to the language.

For my understanding this should be possible without impact.

> But in overall it seems like that a parallel support was never considered during the design.

It was by intention that we have an unique/different key. But yes parallel usage was up to know not an use case. And I think we have to decide: same key and maybe some tools from SonarSource are also working with our plugin __OR__ different key and parallel usage.

> I don't know which effect it might have to change the plugin keys in this state...

History of current users got lost.

**Comment by guwirth** [comment]
@niecore please try with latest snapshot. Please keep in mind that 0.9.9 is working with SQ 6.7 only.

**Comment by niecore** [comment]
I'll do so. Thanks for your help.

**Comment by niecore** [comment]
Hello @guwirth,
we now tried to used the snapshot version on SQ 6.7. in parallel with the commercial Plugin.
Unfortunately the results were disappointing. As you can see in the screenshots, SQ had even more troubles with two plugins which use the same name. 

1. Language Rules are not aggregated
![test](https://user-images.githubusercontent.com/5686845/33887541-5c66cdc0-df4a-11e7-946f-2ae2b8456c84.png)

We decided now, that we will keep a fork of your plugin and patch the language key to "C++ Community"

Thanks for your help anyhow!

**Comment by guwirth** [comment]
@niecore interesting that this is not working. Needs further investigation. Don't know if there is a way to merge it? Maybe you can ask in the SQ forum for a solution?

**Comment by guwirth** [comment]
@Bertk and @other don’t know what we should do with this one? Undo or keep? To show it under same I think we have to change also the repository key. This would be a incompatible change. Also see the risk that message keys from commercial and community plugin overlapp?

**Comment by Bertk** [comment]
@guwirth Please roll back PR **#1342** *cxx language name*. We should stay with the key and name for the community plug-in.

**Comment by guwirth** [comment]
duplicate see #1400
