### ISSUE TITLE
CppCheck file list when using SonarQube Scanne for MSBuild

### ISSUE THREAD

**Issue by taalas** [SonarOpenCommunity/sonar-cxx#1336]
Hi,
I am currently trying to integrate CppCheck analysis for a Visual Studio project using a TFS Build Agent. The runner is called via a "SonarQube Scanner for MSBuild" task and generates file lists from VS solution and project files (not using a sonar-project file).
The instructions to integrate CppCheck into the analysis state to make sure, that the files to analyse match the ones in the sonar project. Since those are dynamically generated from the solution files I don't have access to what is analyzed though. What is the correct way to generate the CppCheck results in this case?
Thanks!

**Comment by guwirth** [comment]
Hi @taalas,

Don't have experience with TFS Build Agent but maybe @Bertk can help you?

Point is that file path on system you are running the scanner must match with the path inside of the Cppcheck report. I guess that you have to integrate the Cppcheck tool somehow into the TFS build chain? Others are patching the paths inside the report with a search & replace tool.

https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues

Regards,

**Comment by taalas** [comment]
Hi @guwirth,
thanks for taking the time to answer.
I have found a solution for the file list. cppcheck can read VS solution and project files now (for some reason I had missed that completely). When using those the evaluated files should match those from the SonarQube runner. I still have some problems with cppcheck not producing the sames results as locally (when called on the agent), but that is most likely unrelated to this issue.
Sorry for the confusion.

**Comment by Bertk** [comment]
@taalas Maybe this helps for analysis tool integration. Please check:

- https://github.com/Bertk/cpptesting
- #616

**Comment by taalas** [comment]
@Bertk That looks very interesting indeed, thanks!

Is it possible to only include these additional props when building on a TFS agent? Sorry if this should be trivial, I just recently started to use this environment.
