### ISSUE TITLE
"Remove this useless assignment to local variable" doesn't recognize usage in Designated Initializers

### ISSUE THREAD

**Issue by y92ding** [SonarOpenCommunity/sonar-cxx#1351]
Example:

StructA a = aFunctionThatReturnsStructA(args); // Remove this useless assignment to local variable a
......
StructB b = {.field1 = a.field1};

**Comment by guwirth** [comment]
@y92ding thanks for the feedback. The original idea of the plugin was to use external tools for static code analysis. In the past there found some 'internal' checks their way into the plugin. In my opinion we should remove them (not fix it).
