### ISSUE TITLE
No statistics for Clang-tidy

### ISSUE THREAD

**Issue by ryosa** [SonarOpenCommunity/sonar-cxx#1352]
Working with SQ6.7 and CXX0.9.8, the statistics for Clang-tidy doesn't appear. Regarding the analysis reports, the properties are:

> sonar.cxx.clangtidy.reportPath=clang-tidy-report.txt
sonar.cxx.cppcheck.reportPath=cppcheck.xml
sonar.cxx.clangsa.reportPath=a.plist

Any suggestions?

![image](https://user-images.githubusercontent.com/22584333/33977094-7ed88efa-e0dc-11e7-9b8a-1c19751c613a.png)

**Comment by guwirth** [comment]
@ryosa some hints what it could be:
* Please ensure that the clang-tidy rules are enabled in your profile. Seems you are using ‚c++ Sonar Way‘ where these are not enabled per default. Default profile is readonly. So create a copy and activate it there. 
* path in reports must match to files/path on the machine you are running the analysis https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues
* turn debug info on to get more information https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

**Comment by ryosa** [comment]
@guwirth Thank you for your advice. You're right, the rules hadn't been activated. Now the analysis results appear in _Code Smells._

I'm not sure if this is a matter of sonar-cxx, but I wonder how _Issues_ or the summary of analysis can be seen  as in the custom dashboard of SQ5.6. It seems Dashboard is no longer available in SQ6.7. Can the summary be displayed by setting sonar-cxx?

**Comment by guwirth** [comment]
> I'm not sure if this is a matter of sonar-cxx, but I wonder how Issues or the summary of analysis can be seen as in the custom dashboard of SQ5.6. 

I'm sorry but SonarSource removed the custom dashboards. Having a look to their forum a lot of people complaining about this. Maybe you can do the same to get it back...

Maybe you can get what you want using the 'Issues' or 'Measures' or 'Activity' page with the right filter.
