### ISSUE TITLE
Cobertura coverage source tag not supported

### ISSUE THREAD

**Issue by barsan-ds** [SonarOpenCommunity/sonar-cxx#1353]
Hi, I try to analyze a cmake project using kcov (which can output a cobertura.xml file) but the coverage is never taken into account.

My sonar-project.properties file is:
```properties
sonar.projectKey = ds:tree
sonar.projectName = TreeDS
sonar.projectVersion = 1.0
sonar.sources = ./include
sonar.cxx.includeDirectories = ./include
sonar.cxx.coverage.reportPath = /home/user/Documenti/GitHub/TreeDS/build/coverage/main/cobertura.xml
```
I tried to use in the reportPath the absolute path, the relative to .properties  file path, the path enclosed by double quotes, nothing seems to work.
SonarQube is called using `sonar-scanner` command. The project is analyzed as the date corresponds.

The structure of the project is like this
```
build/
├── coverage/
│   ├── cobertura.xml
│   └── ....
├── main
└── ...

include/
└── TreeDS/
    └── ...cpp

test/
├── main.cpp
└── ...

CMakeLists.txt

sonar-project.properties
```

CmakeLists.txt (if it can help)
```cmake
cmake_minimum_required(VERSION 2.6)
project(TreeDS)
set(PROJECT_VERSION 1.0)
set(CMAKE_VERBOSE_MAKEFILE on)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -std=c++17 --coverage")
include_directories("./include")
include(CTest)
enable_testing(true)

add_executable(main "./test/main.cpp")
add_test("tree test" main)

add_custom_target(
    SonarQube
    # coverage generation
    COMMAND kcov --include-path=${CMAKE_SOURCE_DIR}/include ${CMAKE_BINARY_DIR}/coverage ${CMAKE_BINARY_DIR}/main
    # sonar scan
    COMMAND sonar-scanner
    DEPENDS main
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
)
```

**Comment by guwirth** [comment]
@barsan-ds thanks for your feedback.

* First of all I’m not sure if `sonar.sources` Is correct? Are in this folder really the source files?
* Second problem in such cases is typically that the paths inside the coverage report file do not match with the location of the files where the analyzer is running. Please read also this: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues. 
* To get more information turn debug info on and have a look to the LOG file: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information.

**Comment by barsan-ds** [comment]
Thank you, the debug logging helped.
There is a problem with cobertura file parsing, more specifically, the value
```xml
<sources>
    <source>/home/user/Documenti/GitHub/TreeDS/include</source>
</sources>
```
is ignored from the sonar plugin, I solved by launching `kcov --include-path=${CMAKE_SOURCE_DIR} ${CMAKE_BINARY_DIR}/coverage ${CMAKE_BINARY_DIR}/main` (withouth the /include)

Previously the xml file was similar to this
```xml
<coverage line-rate="0.000" version="1.9" timestamp="1513448842">
	<sources>
		<source>/home/user/Documenti/GitHub/TreeDS/include/TreeDS/</source>
	</sources>
	<packages>
		<package name="main" line-rate="0.000" branch-rate="1.0" complexity="1.0">
			<classes>
				<class name="post_order_hpp" filename="iterator/post_order.hpp" line-rate="1.000">
```
Now is similar to this
```xml
<coverage line-rate="0.000" version="1.9" timestamp="1513448941">
	<sources>
		<source>/home/user/Documenti/GitHub/TreeDS/</source>
	</sources>
	<packages>
		<package name="main" line-rate="0.000" branch-rate="1.0" complexity="1.0">
			<classes>
				<class name="in_order_hpp" filename="include/TreeDS/iterator/in_order.hpp" line-rate="1.000">
```
Please note that in both cases the path reported in cobertura.xml was correct. The plugin don't take into consideration the prefix between `<source> </source>`

**Comment by guwirth** [comment]
@barsan-ds looking to the sources `<source>` is really not handled: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CoberturaParser.java#L79. The sensor is always using the baseDir. Looking to the integration sample `<source>.</source>` is used: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/integration-tests/testdata/coverage_project/ut-coverage.xml.

Right behavior should be:
* baseDir
   * in case `<source>` is absolute use this as baseDir
   * in case `<source>` is relative then relative to current context.baseDir
* filename
   * if `<filename>` is absolute ignore baseDir
   * if `<filename>` is relative then relative to baseDir

**Comment by gena01** [comment]
@guwirth should we update/rename the issue? 

Also I've ran into this scenario before and tweaked things to work for my side of it., but ideally a proper fix would be nice to have.

**Comment by guwirth** [comment]
@gena01 will fix it after Xmas.

**Comment by guwirth** [comment]
@barsan-ds & @gena01 please try again with latest snapshot.
