### ISSUE TITLE
 C-Compiler parser : Cannot feed the data into sonar, details: 'java.lang.NullPointerException'

### ISSUE THREAD

**Issue by GOMSPACEMartin** [SonarOpenCommunity/sonar-cxx#1359]
Using gcc compiler to compile code and directing output to 'build.log', trying to have the CompilerCensor read the input results in NullPointerException and no results in SonarQube.

Versions:
* gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609)
* SonarQube (Version 6.7 (build 33306))
* C (Community) 0.9.8
* SonarQube Scanner 3.0.3.778
* Java 1.8.0_131 Oracle Corporation (64-bit)

```
14:07:36.546 INFO: Sensor c CompilerSensor [c]
14:07:36.546 INFO: Searching reports by relative path with basedir '/var/lib/jenkins/workspace/libutil-develop-martin' and search prop 'sonar.c.compiler.reportPath'
14:07:36.546 DEBUG: Normalized report includes to '[/var/lib/jenkins/workspace/libutil-develop-martin/build.log]'
14:07:36.546 INFO: Scanner found '1' report files
14:07:36.546 INFO: Parser will parse '1' report files
14:07:36.546 INFO: Processing report '/var/lib/jenkins/workspace/libutil-develop-martin/build.log'
14:07:36.546 INFO: C-Compiler parser: 'sonar.c.sonar.c.Visual C++'
14:07:36.546 ERROR: Cannot feed the data into sonar, details: 'java.lang.NullPointerException'
14:07:36.546 INFO: Sensor c CompilerSensor [c] (done) | time=0ms
```

**Comment by guwirth** [comment]
@GOMSPACEMartin thanks for the feedback. Can you please turn debug info on to show us the stack trace: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

**Comment by GOMSPACEMartin** [comment]
Hi @guwirth, thank you for the fast reply 👍 

I am already running the sonar-runner with debug information, but I am not getting any more information in my console, I even tried TRACE logging:

> sonar-scanner -X --debug -Dsonar.verbose=true -Dsonar.log.level=TRACE

Also you can see a single DEBUG log entry in the snippet above.

Are there anywhere else I could look for more detailed loginfo? - maybe on the sonarQube server itself?

**Comment by Bertk** [comment]
Please set compiler parser ```sonar.c.compiler.parser=GCC```. 
I am not sure whether this solves the issue but the reported parser is not correct 
``` 14:07:36.546 INFO: C-Compiler parser: 'sonar.c.sonar.c.Visual C++' ```

**Comment by GOMSPACEMartin** [comment]
Weird ... adding `sonar.c.compiler.parser=GCC` solved the nullpointer exception, but doing the setting in the GUI is not recognized, which might be the real issue here.

![image](https://user-images.githubusercontent.com/34163567/34292687-131d9a44-e702-11e7-8500-1f67f1e8d081.png)

**Comment by GOMSPACEMartin** [comment]
I ran into the next problem though, and is still not able to parse the analysis, but I will raise another issue.

thnx for support on this matter 👍

**Comment by Bertk** [comment]
You should not use ```sonar.c.GCC``` but ```GCC```.

**Comment by GOMSPACEMartin** [comment]
I would love to, but I an constrained to two options in a drop-down box

![image](https://user-images.githubusercontent.com/34163567/34297878-f3a52e20-e71a-11e7-9e64-c43ba56cd8f5.png)

**Comment by Bertk** [comment]
This is a bug.
