### ISSUE TITLE
WARN: Cannot find the file ...., skipping violations

### ISSUE THREAD

**Issue by GOMSPACEMartin** [SonarOpenCommunity/sonar-cxx#1360]
Hi!

At the end of parsing a single file in my buildlog I get this warning:
`11:49:01.576 WARN: Cannot find the file '/var/lib/jenkins/workspace/src/zip/miniz/miniz.c', skipping violations `

How do I tell the C-Compiler parser that `/var/lib/jenkins/workspace/src/zip/miniz/miniz.c` is located at `/var/lib/jenkins/workspace/`**libutil-develop-martin**`/src/zip/miniz/miniz.c` - where does the parser get the path from?

This might be an issue related to how [Jenkins](https://jenkins-ci.org/) handles workspaces and buildjobs, but I would like to see I can configure the C-Compiler parser to look beyond this.

Versions:
* gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609)
* SonarQube (Version 6.7 (build 33306))
* C (Community) 0.9.8
* SonarQube Scanner 3.0.3.778
* Java 1.8.0_131 Oracle Corporation (64-bit)
* Jenkins ver. 2.89.2

**Log**
`11:49:01.512 INFO: Sensor c CompilerSensor [c]
11:49:01.513 INFO: Searching reports by relative path with basedir '/var/lib/jenkins/workspace/libutil-develop-martin' and search prop 'sonar.c.compiler.reportPath'
11:49:01.513 DEBUG: Normalized report includes to '[/var/lib/jenkins/workspace/libutil-develop-martin/build.log]'
11:49:01.513 INFO: Scanner found '1' report files
11:49:01.513 INFO: Parser will parse '1' report files
11:49:01.513 INFO: Processing report '/var/lib/jenkins/workspace/libutil-develop-martin/build.log'
11:49:01.513 INFO: C-Compiler parser: 'GCC'
11:49:01.513 INFO: Scanner 'GCC' initialized with report '/var/lib/jenkins/workspace/libutil-develop-martin/build.log', CharSet= 'UTF-8'
11:49:01.513 INFO: Parsing 'GCC' format
11:49:01.513 DEBUG: Using pattern : '^(.*):([0-9]+):[0-9]+: warning: (.*)\[(.*)\]$'
11:49:01.527 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='3316' id='-Wimplicit-function-declaration' msg=implicit declaration of function 'utime' 
11:49:01.527 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='6958' id='-Wcast-align' msg=cast increases required alignment of target type 
11:49:01.528 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1364' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.528 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1381' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.528 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1382' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.528 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1383' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.528 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1407' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.529 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='5253' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.529 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1364' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.529 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1381' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.529 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1382' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.529 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1383' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.529 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1407' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.529 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='5253' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.536 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='3316' id='-Wimplicit-function-declaration' msg=implicit declaration of function 'utime' 
11:49:01.536 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='6958' id='-Wcast-align' msg=cast increases required alignment of target type 
11:49:01.536 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='3316' id='-Wimplicit-function-declaration' msg=implicit declaration of function 'utime' 
11:49:01.536 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='6958' id='-Wcast-align' msg=cast increases required alignment of target type 
11:49:01.538 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='3316' id='-Wimplicit-function-declaration' msg=implicit declaration of function 'utime' 
11:49:01.538 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='6958' id='-Wcast-align' msg=cast increases required alignment of target type 
11:49:01.539 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1364' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.540 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1381' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.540 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1382' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.540 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1383' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.540 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1407' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.540 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='5253' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.540 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1364' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.540 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1381' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.540 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1382' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.540 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1383' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.540 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1407' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.540 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='5253' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.541 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='3316' id='-Wimplicit-function-declaration' msg=implicit declaration of function 'utime' 
11:49:01.542 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='6958' id='-Wcast-align' msg=cast increases required alignment of target type 
11:49:01.542 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='3316' id='-Wimplicit-function-declaration' msg=implicit declaration of function 'utime' 
11:49:01.542 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='6958' id='-Wcast-align' msg=cast increases required alignment of target type 
11:49:01.545 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='3316' id='-Wimplicit-function-declaration' msg=implicit declaration of function 'utime' 
11:49:01.545 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='6958' id='-Wcast-align' msg=cast increases required alignment of target type 
11:49:01.545 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1364' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.545 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1381' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.546 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1382' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.546 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1383' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.546 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1407' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.546 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='5253' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.546 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1364' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.546 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1381' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.546 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1382' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.546 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1383' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.547 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='1407' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.547 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='5253' id='-Wstrict-aliasing' msg=dereferencing type-punned pointer will break strict-aliasing rules 
11:49:01.547 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='3316' id='-Wimplicit-function-declaration' msg=implicit declaration of function 'utime' 
11:49:01.548 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='6958' id='-Wcast-align' msg=cast increases required alignment of target type 
11:49:01.548 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='3316' id='-Wimplicit-function-declaration' msg=implicit declaration of function 'utime' 
11:49:01.548 DEBUG: Scanner-matches file='../src/zip/miniz/miniz.c' line='6958' id='-Wcast-align' msg=cast increases required alignment of target type 
11:49:01.576 WARN: Cannot find the file '/var/lib/jenkins/workspace/src/zip/miniz/miniz.c', skipping violations
11:49:01.576 DEBUG: C-COMPILER processed = 0
11:49:01.576 INFO: C-COMPILER processed = 0
11:49:01.576 INFO: Sensor c CompilerSensor [c] (done) | time=64ms`

**Comment by Bertk** [comment]
You can use the [projectBaseDir ](https://docs.sonarqube.org/display/SONAR/Analysis+Parameters)setting. 

sonar.projectBaseDir | Use this property when you need analysis to take place in a directory other than the one from which it starts. E.G. analysis begins from jenkins/jobs/myjob/workspace but the files to be analyzed are in ftpdrop/cobol/project1. The path may be relative or absolute.Specify not the the source directory, but some parent of the source directory. The value specified here becomes the new "analysis directory", and other paths are then specified as though the analysis were starting from the new sonar.projectBaseDir.Note that the analysis process will need write permissions in this directory; it is where the sonar.working.directory will be created.
-- | --




see also:
https://stackoverflow.com/questions/31945819/sonarqube-source-is-not-present-in-module-base-directory

There is also the  [SQ Jenkins Scanner](https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Jenkins) which might be helpful.

**Comment by GOMSPACEMartin** [comment]
Hi @Bertk - thank you for suggesting, but I did not think of changing the basedir as everything else (apparently) works fine.,

Anyway, I changed the basedir and it gave me the same result for the c-compiler parser but there was added a new path (Searching reports by relative path with basedir ) to e.g. the valggrind sensor:

`14:02:13.629 INFO: Sensor c ValgrindSensor [c]
14:02:13.629 INFO: Searching reports by relative path with basedir '/var/lib/jenkins/workspace/libutil-develop-martin' and search prop 'sonar.c.valgrind.reportPath'
14:02:13.629 DEBUG: Normalized report includes to '[/var/lib/jenkins/workspace/libutil-develop-martin/tst/*/build/valgrind_*.xml]'
14:02:13.675 INFO: Scanner found '23' report files
14:02:13.675 INFO: Parser will parse '23' report files`

So it does not look like that the same path (basedir) is affecting the C-Compiler parser.

**Comment by guwirth** [comment]
@GOMSPACEMartin please have also a look to https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues

**Comment by GOMSPACEMartin** [comment]
Ah sorry for not responding to this, I tried what @guwirth suggested, but (unfortunately) developers removed libs and thereby compiler warnings in the meantime, so had no time to validate solution. Again sorry about this.
