### ISSUE TITLE
RFF CXX Plugin v0.9.9 Release

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1371]
Hi,

This is the remaining context for 0.9.9. Help and feedback is welcome. 
https://github.com/SonarOpenCommunity/sonar-cxx/milestone/10

If you are already using 0.9.9 like to hear your experience or at least ‚everything fine - working‘. 

Regards,

**Comment by Bertk** [comment]
@guwirth Why we are not use a time-boxed approach and assign the remaining issue to the next release?
I do not see an urgent issue which blocks a release.

**Comment by guwirth** [comment]
After merge of final two issues test of 0.9.9 can start.
https://github.com/SonarOpenCommunity/sonar-cxx/milestone/10

Please give feedback by 14.01.2018.

**Comment by guwirth** [comment]
Draft of release notes:
---

We are pleased to announce the SonarQube C++ Community Plugin version 0.9.9.
See lists below for features added and bugs fixed in this release.

# SonarQube compability

- tested and released for **SonarQube 6.7 LTS**<br>see also [SonarQube compatibility matrix](https://github.com/wenns/sonar-cxx/wiki/SonarQube-compatibility-matrix)
- [Installation Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Installation)
- [Upgrade Instructions](https://github.com/wenns/sonar-cxx/wiki/Upgrade-Instructions)

# Enhancements

* minimal supported SQ API is 6.7 #1317
   * Refactoring: remove conditional code for older SQ versions #1318
   * Refactoring: mark deprecated API #1329
* update parent POM to 41 #1316
* Cppcheck 1.82 support #1370 #1373 
* support C++ Core Check improvements in Visual Studio 2017 15.5 #1309 #1375
* improve parser LOG file regex for MSVC 14.11 #1356
* Metrics #1339
   * Refactoring: FILE_COMPLEXITY_DISTRIBUTION metric is deprecated - remove it #1333
   * Refactoring: COMPLEXITY_IN_FUNCTIONS metric is deprecated - remove it #1332
   * Refactoring: COMPLEXITY_IN_CLASSES metric is deprecated - remove it #1331
   * Refactoring: FUNCTION_COMPLEXITY_DISTRIBUTION metric is deprecated - remove it #1330
* Coverage
   * Refactoring: remove `sonar.cxx.coverage.overallReportPath` support #1322
   * Refactoring: remove `sonar.cxx.coverage.itReportPath` support #1321
   * Refactoring: remove `sonar.cxx.coverage.forceZeroCoverage` support #1320
   * Refactoring: remove CxxCoverageSensor from CxxSquidSensor #1335 #1327
   * Refactoring: CxxPlugin::testingAndCoverageProperties #1324
* Refactoring: cleanup CxxFileLinesVisitor visitor #1323
* Refactoring: Remove no more supported use cases from integration tests #1319
* fix technical debt quality flaws, make quality gate green: #1369 #1368 #1362 #1358 #1357 #1354 #1349

# Bugfixes

* fix ERROR: `sonar.cxx.other.xslt.1.inputs` file is not defined #1367
* Cobertura coverage source tag support #1364 #1353
* fix selection options for compiler.parser #1361
* C-Compiler parser : Cannot feed the data into sonar, details: 'java.lang.NullPointerException' #1359
* fix CxxLint with and add unit tests #1355
* fix custom rules support #1308 #1347 #1346 #1343
* remove warning: CPD error in file - debug info now #1338 #1307

# Know Issues

For an up to date list of known issues see the issue tracker.
- V0.9.8 is not compatible with Java 9
- Starting with SQ 6.2 there are some new metrics and some are no more available. Please have a look to the SonarQube release notes.
- Symlinks are not supported.

# Thanks ....

go to all contributors (in alphabetical order):

@Bertk
@guwirth
@rufinio

... and all people which were active on the issue tracker!

**Comment by guwirth** [comment]
@all ready for final testing

**Comment by Bertk** [comment]
@guwirth Please add a hint for the missing [test execution metrics](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-test-execution-metrics). The current Wiki information is only valid for SQ5.7
SQ 6.7 has some support for test metrics ([Seeing Tests](https://docs.sonarqube.org/display/SONAR/Seeing+Tests)) but I am not sure whether this works with the C++ Community plug-in.

**Comment by guwirth** [comment]
> Please add a hint for the missing test execution metrics. T

@Bertk is this a known issue or new with 0.9.9?

**Comment by Bertk** [comment]
@guwirth This issue exists already in former releases and might only be related to Visual Studio tests "*.trx" (see also CSharp plugin issue #886). Did anybody check the [Seeing Tests](https://docs.sonarqube.org/display/SONAR/Seeing+Tests) feature with xunit reports?

**Comment by guwirth** [comment]
@all I did some tests with
* plugin 0.9.9 and SQ 6.7 LTS on Windows 7:
* tools: Cppcheck, VS 2015 warnings, Boost.Test, Bullseye Coverage and some others....

**Tests are successful.**

```
# required metadata (parameter for sonar-runner)
#sonar.projectKey=XXX
#sonar.projectName=XXX

# required metadata
sonar.projectVersion=a.b.c
sonar.language=c++

#links
sonar.links.ci=XXX

# disable SCM support
sonar.scm.disabled=true

# path to source directories (parameter for sonar-runner)
#sonar.sources=.
#sonar.tests=.

# global cxx plugin settings
sonar.cxx.errorRecoveryEnabled=true
sonar.cxx.coverage.forceZeroCoverage=true

# duplicate detection
sonar.cxx.cpd.ignoreLiterals=false
sonar.cxx.cpd.ignoreIdentifiers=false

# include directories
sonar.cxx.forceIncludes=VS10Macros.h
sonar.cxx.includeDirectories=.

# supported file extensions and exclusions
sonar.cxx.suffixes.sources=.c,.cpp
sonar.cxx.suffixes.headers=.h,.hh,.hpp,.inl
sonar.exclusions=XXXX

# paths to the reports
sonar.cxx.cppcheck.reportPath=.reports/cppcheck.xml
sonar.cxx.other.reportPath=.reports/cxx-*.xml
sonar.cxx.coverage.reportPath=.reports/coverage-*.xml
sonar.cxx.xunit.reportPath=.reports/*.test.boostd.exe.log.xml

# unit tests: simple mode, boost
sonar.cxx.xunit.provideDetails=false
sonar.cxx.xunit.xsltURL=boosttest-1.x-to-junit-1.0.xsl
```

**Comment by guwirth** [comment]
@all test from my side are green. 0.9.9 can be released.
