### ISSUE TITLE
Cyclomatic Complexity per Function

### ISSUE THREAD

**Issue by ericlemes** [SonarOpenCommunity/sonar-cxx#1372]
Hi there,

I'm looking for a simple way of identifying methods with more than 10 cyclomatic complexity (and lines of code, but this is a different discussion). 

As far as I'm aware, Sonar doesn't support any method related metric (only file related metric). I was looking to the database or other possible ways of getting this numbers.

Something not ideal, but interesting is the org.sonar.cxx.checks.FunctionComplexityCheck, but it doesn't seem to be working properly on my setup because I'm not getting any violation. 

Is there any special tweaks to enable this check?

Cheers,

Eric

**Comment by guwirth** [comment]
Hi @ericlemes,

We have some checks going into this direction:
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/FunctionComplexityCheck.java
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/FunctionCognitiveComplexityCheck.java
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/TooManyLinesOfCodeInFunctionCheck.java

If they are not working check if they are activated. You have to create an own profile (derive from default) to do this. And don’t forget to thank SQ for this great idea that default profiles are read only :-). 

Regards

**Comment by ericlemes** [comment]
Hi @guwirth,

I don't know exactly how to create my own profile, but you gave me very precious information that opens a lot of new options. Thank you very much!

I personally don't like the idea of creating an "issue" for each of those violations, but as a short term solution, will definitely help.

Regards
