### ISSUE TITLE
gcovr xml coverage report not published on sonar server

### ISSUE THREAD

**Issue by Vazzilena** [SonarOpenCommunity/sonar-cxx#1381]
Hey,

We are using the c++ community plug-in with sonar server version 6.7.1 (build 35068). We tried version 0.9.8 of the plugin and 0.9.9-SNAPSHOT (downloaded from https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts)
gcovr version is 3.3

We have the gcovr coverage report generated and submitted to sonar server. 
The log indicates the report has been detected:

20:56:30 [sonar:sonar] Searching for coverage reports '[CodeCoverageReport.xml]'
20:56:30 [sonar:sonar] Coverage BaseDir 'C:\jenkins\workspace\10.2.S_sonar\prod\cpp' 
20:56:30 [sonar:sonar] Access to the multi-values/property set property 'sonar.cxx.coverage.reportPath' should be made using 'getStringArray' method. The SonarQube plugin using this property should be updated.
20:56:30 [sonar:sonar] Scanner found '1' report files
20:56:30 [sonar:sonar] Parser will parse '1' report files
20:56:31 [sonar:sonar] Added coverage report 'C:\jenkins\workspace\10.2.S_sonar\prod\cpp\CodeCoverageReport.xml' (parsed by: CoberturaParser)

When the run is over there is no coverage data on server side. Any idea what is wrong and how to fix this? 
![server_side](https://user-images.githubusercontent.com/25956109/34763563-52a915ca-f5f4-11e7-87a3-2ba56871b897.jpg)

Full output:
[full_output_all_projects.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/1618105/full_output_all_projects.txt)

**Comment by guwirth** [comment]
Hi,

* How do you call gcovr: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Coverage-tracers?
* Are the paths correct https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues?
* Which configuration properties for coverage are you using in `sonar-project.properties`?
* Try again with debug info to get more feedback: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

Regards,

**Comment by Vazzilena** [comment]
1) gcovr command for xml generation is: 
gcovr -k -r /FS/fslocal/jenkins_slave/workspace/10.2.S_release_test_cpp_linux/prod/cpp/client/Nirvana /FS/fslocal/jenkins_slave/workspace/10.2.S_release_test_cpp_linux/prod/cpp/client/Nirvana/CMakeFiles/Nirvana.dir --xml-pretty -o /FS/fslocal/jenkins_slave/workspace/10.2.S_release_test_cpp_linux/reports/CodeCoverageReport.xml

2) Throughout the entire setup I use only "/". Invocation is done using ANT SONAR tasks.

3) Please see configuration_properties.txt:
[configuration_properties.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/1618716/configuration_properties.txt)

4) sonar.log.level is DEBUG. The full output is attached in the original defect.

**Comment by guwirth** [comment]
@Vazzilena looking to configuration_properties.txt the paths are:
```INI
sonar.projectBaseDir=C:\jenkins\workspace\10.2.S_sonar\prod\cpp
sonar.sources=C:\jenkins\workspace\10.2.S_sonar/prod/cpp/client/Nirvana
```
* Means scanner is running on a Windows machine?
* Sensor "Sensor c++ SquidSensor" is also reading the files from a Windows system?

LOG items:
```
[sonar:sonar] Searching coverage reports by path with basedir 'C:\jenkins\workspace\10.2.S_sonar\prod\cpp' and search prop 'sonar.cxx.coverage.reportPath'
[sonar:sonar] Searching for coverage reports '[CodeCoverageReport.xml]'
[sonar:sonar] Coverage BaseDir 'C:\jenkins\workspace\10.2.S_sonar\prod\cpp' 
[sonar:sonar] Access to the multi-values/property set property 'sonar.cxx.coverage.reportPath' should be made using 'getStringArray' method. The SonarQube plugin using this property should be updated.
[sonar:sonar] Scanner found '1' report files
[sonar:sonar] Parser will parse '1' report files
[sonar:sonar] Added coverage report 'C:\jenkins\workspace\10.2.S_sonar\prod\cpp\CodeCoverageReport.xml' (parsed by: CoberturaParser)
```
* Looking to gcovr you seems to run it on a Linux system?

Does paths in reports fit exactly to the paths the scanner is running on (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues)? How does the paths look like in CodeCoverageReport.xml?

**Comment by Vazzilena** [comment]
@guwirth 
It is a distributed build/test system - gcovr data is collected from unix systems and then passed to sonar using a separate virtual machines. That is why sonar jobs turned out to run on windows, while test jobs run on unix. 
I have got plenty of "/" slashes in the xml report. Here it is (renamed to txt): 
[CodeCoverageReport.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/1621684/CodeCoverageReport.txt)

**Comment by guwirth** [comment]
@Vazzilena SQ scanner is reading dource files and reports. Paths must match 1:1 on scanner machine otherwise report content is ignored.
```XML
<source>
/FS/fslocal/jenkins_slave/workspace/10.2.S_release_test_cpp_linux/prod/cpp/client/Nirvana
</source>
...
<class ... filename="client/EventSink.cpp" ... name="EventSink_cpp">
```
You must patch the report somehow to match the paths on your scanner machine:
```INI
sonar.projectBaseDir=C:\jenkins\workspace\10.2.S_sonar\prod\cpp
sonar.sources=C:\jenkins\workspace\10.2.S_sonar/prod/cpp/client/Nirvana
```
Maybe it's enough to replace the source tag?
/FS/fslocal/jenkins_slave/workspace/10.2.S_release_test_cpp_linux/prod/cpp/client/**Nirvana**
==> C:\jenkins\workspace\10.2.S_sonar/prod/cpp/client/**Nirvana**

**Comment by Vazzilena** [comment]
@guwirth 
Thanks a lot for your input - it looks like just a singe tag that needs adjusting....
<source>
/FS/fslocal/jenkins_slave/workspace/10.2.S_release_test_cpp_linux/prod/cpp/client/Nirvana
</source>

I will make a change and see if it works now...

**Comment by Vazzilena** [comment]
Fixing the paths in the xml report solved my issue. Many thanks for your support!
![cov](https://user-images.githubusercontent.com/25956109/34832755-6def522e-f6f6-11e7-831d-a6e730cc800e.jpg)

**Comment by guwirth** [comment]
@Vazzilena good to hear.
