### ISSUE TITLE
Not seeing cognitive complexity measures with 0.9.8

### ISSUE THREAD

**Issue by sawatts** [SonarOpenCommunity/sonar-cxx#1385]
I am not seeing a **cognitive complexity** measure for any of our _C++_ projects -- which include pre-existing (before 0.9.8) and newly added projects.  This metric is present on Java projects.  All projects have been rebuilt and analyzed multiple times since upgrading to 0.9.8.

Assuming the metric is in 0.9.8 -- is there something that has to be done to active it?

I upgraded our SonarQube installation from 5.6LTS to 6.7.1LTS at the start of the year, along with updates to all plugins including sonar-cxx.

**Comment by guwirth** [comment]
Hi @sawatts please check if the rule is enabled in your profile. In newer versions of SQ the default profile is read only. You have to derive an own one to activate a rule.

**Comment by Bertk** [comment]
@guwirth I activated the rule ```cxx:FunctionCognitiveComplexity``` but the metric is not available in Measures. Can you please check this with your SQ instance? Unfortunately I do not have access to a large C++ project right now and my sample project does not have a single issue related to ```cxx:FunctionCognitiveComplexity```.

![measures-complextity-c](https://user-images.githubusercontent.com/2315215/34959817-6e2bb4ea-fa38-11e7-9ce2-26dc50b6594a.PNG)

The Measures for the Java has some data 
<img width="200" alt="measures-complextity-java" src="https://user-images.githubusercontent.com/2315215/34959349-6c942c86-fa36-11e7-95f9-b52004df9cff.PNG">

**Comment by guwirth** [comment]
@Bertk we need #1297 to see this. By the way: see no sense in this metric. It's only the accumulation of FunctionCognitiveComplexity per file. What can you derive from this value?

**Comment by guwirth** [comment]
Known issue: #1297
