### ISSUE TITLE
RATS: Errors when processing reports

### ISSUE THREAD

**Issue by stefanes** [SonarOpenCommunity/sonar-cxx#1395]
When processing RATS reports (version 2.3) we get the following errors:
```
ERROR: Could not add the issue 'The rule 'rats:strcpy' does not exist.', skipping issue
ERROR: Could not add the issue 'The rule 'rats:strcat' does not exist.', skipping issue
ERROR: Could not add the issue 'The rule 'rats:fread' does not exist.', skipping issue
ERROR: Could not add the issue 'The rule 'rats:program_name' does not exist.', skipping issue
```

I have noted that `strcpy` and `strcat` are available here but with a different case:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/rats.xml

**Comment by stefanes** [comment]
Oh, and we are on **SQ 6.7** with **C++ (Community) 0.9.8**.

**Comment by Bertk** [comment]
Hi, thank you for the information.
The RATS rules were not updated for a long time and I did not use RATS for the last 5 years.
Which version of RATS to you use? I am not sure but the current rule set might be defined for V2.3.

https://security.web.cern.ch/security/recommendations/en/codetools/rats.shtml

**Comment by stefanes** [comment]
We are using **RATS 2.3**, these are the rules that seems to be of interest: 
[rats-2.3.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/1651119/rats-2.3.zip)

**Comment by guwirth** [comment]
@stefanes please have a look to #1419

**Comment by guwirth** [comment]
@stefanes rats:program_name is not part of RATS 2.4. Which exact message do you get here?

**Comment by stefanes** [comment]
It looks like that rules comes from here:
https://github.com/andrew-d/rough-auditing-tool-for-security/blob/master/rats-openssl.xml#L218

**Comment by guwirth** [comment]
@stefanes don't know if we should add OpenSSL rules?
