### ISSUE TITLE
RATS: Strange entries in SQ after adding RATS reports

### ISSUE THREAD

**Issue by stefanes** [SonarOpenCommunity/sonar-cxx#1396]
As seen int the provided screenshot, importing RATS reports adds issues to SQ with the wrong subject (**SQ 6.7** with **C++ (Community) 0.9.8**).

In the displayed case the true issue is `rats:printf` but the subject in the issues list is "A function call is not being made here..." instead of "Check to be sure that the non-constant format string...".

![image](https://user-images.githubusercontent.com/5484354/35153865-6ca8dcfe-fd28-11e7-87b9-62f53a8a58c0.png)

**Comment by Bertk** [comment]
Hi, can you please check the RATS report whether there is a RATS issue on line 924 for printf rule.
excerpt from RATS rule file:
```xml
  <rule>
    <key>printf</key>
    <name>printf</name>
    <description>
      Check to be sure that the non-constant format string passed as
      argument 1 to this function call does not come from an untrusted
      source that could have added formatting characters that the code is
      not prepared to handle.
    </description>
    <tag>security</tag>
    <internalKey>config/printf</internalKey>
    <severity>MAJOR</severity>
    <type>CODE_SMELL</type>
    <remediationFunction>LINEAR</remediationFunction>
    <remediationFunctionGapMultiplier>5min</remediationFunctionGapMultiplier>
  </rule>
```

The displayed message is created for a unsafe function reference issue (excerpt from report.c RATS 2.4):
```c
    case Reference:
      printf("  <type>%s</type>\n",
	     ptr->data->Name);
      printf("  <message>\n");
      printf("    A function call is not being made here, but a reference is being made to\n");
      printf("    a name that is normally a vulnerable function.  It could be being\n");
      printf("    assigned as a pointer to function.\n\n");
      printf("  </message>\n");
      break;

```

We use a sample reports for unit tests and the RATS report is here:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/test/resources/org/sonar/cxx/sensors/reports-project/rats-reports/rats-result-SAMPLE.xml
Can you please provide a sample report to reproduce the issue.

**Comment by stefanes** [comment]
We do have `printf` in our rules, but on line **457**.
```
  <Vulnerability>
    <Name>printf</Name>
    <FSProblem>
      <Arg>1</Arg>
      <Severity>High</Severity>
    </FSProblem>
  </Vulnerability>
```
https://github.com/SonarOpenCommunity/sonar-cxx/issues/1395#issuecomment-359348305

**Comment by stefanes** [comment]
Will re-run the project we have set up from scratch and get back to you. We run RATS with `--references` on the command line witch then seems to be the cause of this issue.

**Comment by stefanes** [comment]
When using `--references` most of the messages in the report seems to get the message `A function call is not being made here,...`. The info. you display in details seems to stem from `<type>link</type>` (`The function can be part of a TOCTOU...`).

Example:
```
...
BasLinkedBase link( *i);
...
```
:arrow_down:
```
<vulnerability>
  <severity>Medium</severity>
  <type>link</type>
  <message>
    A function call is not being made here, but a reference is being made to
    a name that is normally a vulnerable function.  It could be being
    assigned as a pointer to function.

  </message>
  <file>
    <name>./path/to/file.cpp</name>
    <line>1142</line>
    <line>1143</line>
    <line>1146</line>
  </file>
</vulnerability>
```

**Comment by guwirth** [comment]
>  `<type>link</type>`

@stefanes don't know how the RATS tool is exactly working. But maybe it interprets:

```
BasLinkedBase link( *i);
```
as a function call and `link` as function (pointer)?
