### ISSUE TITLE
add PR and issue templates

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx#1412]
We need template to avoid query for additional information.

see issue template use by C# plugin
https://github.com/SonarSource/sonar-csharp/blob/master/.github/ISSUE_TEMPLATE.md

sample for PR template
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/
- a short description of what the PR does so the maintainer doesn’t have to guess,
- the status of the PR on if it should be ready to be merged or if it’s still in development but ready for some review,
- a link to the ticket/issue to which the PR is relevant.

**Comment by guwirth** [comment]
issue template: https://github.com/SonarOpenCommunity/sonar-cxx/commit/7161a9945c39566abf53a7fd433a0520c4aa5379
