### ISSUE TITLE
Installation docs confusing about which jars to install

### ISSUE THREAD

**Issue by amai2012** [SonarOpenCommunity/sonar-cxx#1416]
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Installation says:
> Download one of the released jar packages into the SONARQUBE_HOME/extensions/plugins directory

However e.g. https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-0.9.8 offers 3 jars
- sonar-c-plugin-0.9.8.jar
- sonar-cxx-plugin-0.9.8.jar
- sslr-cxx-toolkit-0.9.8.jar 

and it's not obvious which to choose.

**Comment by guwirth** [comment]
Hi @amai2012,

* `sonar-cxx-plugin-0.9.8.jar`: is the c++ plugin
* `sonar-c-plugin-0.9.8.jar`: is a first draft for a c plugin
* `sslr-cxx-toolkit-0.9.8.jar`: is an additional tool to create an AST from source code. Helpful to create XPath checks.

Regards,

**Comment by amai2012** [comment]
Thanks. Should this be added to the wiki as well?

**Comment by guwirth** [comment]
@amai2012 I added a hint: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Installation

**Comment by amai2012** [comment]
Thank you.
