### ISSUE TITLE
US: Optimize Sensor usage with SensorDescriptor

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1420]
Optimize Sensor usage over SensorDescriptor: Describe what a Sensor is doing. Information may be used by the platform to log interesting information or perform some optimization.

Possible filter:
* onlyOnLanguage / onlyOnLanguages
* onlyOnFileType
* createIssuesForRuleRepository / createIssuesForRuleRepositories
* requireProperty
* onlyWhenConfiguration

https://github.com/SonarSource/sonarqube/blob/c0d2705e610d771b8c66ef22e64530c7bca4f538/sonar-plugin-api/src/main/java/org/sonar/api/batch/sensor/SensorDescriptor.java

**Comment by guwirth** [comment]
@Bertk & @jmecosta looking at Python some sensors are for MAIN or TEST only:

https://github.com/SonarSource/sonar-python/blob/088d9da9ec3dcd6349b105bad73ee560899fb879/sonar-python-plugin/src/main/java/org/sonar/plugins/python/PythonReportSensor.java#L45

**Question**: How do you handle this today with static code analysis.
* Are static code analysis results are only valid for productive code and not for unit tests?
* Or for both?

**Comment by Bertk** [comment]
@guwirth IMO issues shall be created for production and test code but I am not interested in certain metrics for test code e.g. duplication, coverage. I want also to analyze test code and use checker to detect problematic or flaky unit tests. Today there are only checks available for Java.

- Unit tests should include an assert
- Assertions should be complete
- Unit Test Contains Too Many Asserts

**Comment by jmecosta** [comment]
and also not all issues should be created, would be nice to have the possibility to have a profile for tests and another for production code
