### ISSUE TITLE
US: Separate profiles for test and production code

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1422]
Would be nice to have the possibility to have a profile for tests and another for production code.
See also #1420.

**Comment by Bertk** [comment]
@guwirth Hi, I guess this is issue for the SonarQube platform and everybody should vote for this 
feature
 [When activating a rule it should be possible to define the scope : unit test code, source code or both](https://jira.sonarsource.com/browse/SONAR-3748)
