### ISSUE TITLE
sslr-cxx-toolkit-0.9.8 has problem with parsing switch-case-break c++

### ISSUE THREAD

**Issue by prepas** [SonarOpenCommunity/sonar-cxx#1429]
Please [turn debug info on](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information) and reproduce your issue.
The debug info in the log file could help to solve or locate the issue.

### Description

break/return has level position on the same level as 'case' if 'case' does not have any code

### Steps to reproduce the problem

Please provide the steps required to reproduce the problem

1. Write c++ code

`void func(int param)
{
    switch(param)
    {
       case 0:
           int a = 0;
       case 1:
          b = 0;
          v = 0;
          c = 0;
          break;
       case 2:
          return;
       case 3:
          string str;
          break;
       case 4:
           int a;
      case 5:
           int a;
           return;
    }
}`

2. Click Parse source code

### Expected behavior

break/return has level position inside in 'case'

### Actual behavior

break/return has level position on the same level as 'case' if 'case' does not have any code

### LOG file

http://joxi.ru/KAg8OQgS4lp55r

### Related information

* cxx plugin version 0.9.8

**Comment by guwirth** [comment]
@prepas not really an answer but first links:

1. Link to C++17 spec we are using: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/dox/2016-11-28_cpp17_n4618.pdf
2. Grammar: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/dox/2016-11-28_cpp17_grammar.txt
3. Grammar Imp: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java

jumpStatement:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java#L888

labeledStatement:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java#L823

First impression: it's correct?

**Comment by prepas** [comment]
Why do you detect break/continute/etc. like first item after 'case'?
> b.firstOf(
> b.sequence(CxxKeyword.BREAK, ";"), // C++
> b.sequence(CxxKeyword.CONTINUE, ";"), // C++
case can consist c++ code with curly braces and after it can be break/continute/etc.
For instance:
`case:
myValue = 10;
break;`
My opinion that break must be under of case, not on the same level with case.

**Comment by guwirth** [comment]
@prepas we use the C++ grammar from the standard as it is. Or see you any deviation to the standard?
