### ISSUE TITLE
Missing rule configuration for "Track lack of copyright and license headers"  on SonarCloud

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx#1432]
### Description
202 SonarQube issues are created because the rule squid:S1451 is not configured.

### Steps to reproduce the problem
Check https://sonarcloud.io/project/issues?facetMode=effort&id=org.sonarsource.sonarqube-plugins.cxx%3Acxx&resolved=false&severities=BLOCKER&types=CODE_SMELL

### Expected behavior

Disable rule or use the correct license header for rule squid:S1451

**Comment by guwirth** [comment]
@Bertk think the header in the sources is correct? It’s more to configure S1451, or?

**Comment by guwirth** [comment]
Done
