### ISSUE TITLE
Not getting new lines of code modified/changed/added in sonar server

### ISSUE THREAD

**Issue by tovishwendra** [SonarOpenCommunity/sonar-cxx#1438]
Hi, I am not able to get the new lines of code modified/changed/added in sonar server.
In the section coverage on new lines of code. i am getting the percent and lines added only for 
the new functions added but not if we modify/change/add any if statement or anything else other than function.

Versions of softwares we are using:
sonarcxxplugin: 0.9.7
sonar qube server: 6.3.1
Bullseye version: 8.9.94

Thanks for the help in advance.

**Comment by guwirth** [comment]
@tovishwendra this data for ‘new/changed’ comes from the SCM sensor which is part of the SQ core.
* Is SCM enabled and working?
* Is there new code in your repository?

**Comment by tovishwendra** [comment]
@guwirth below is the answer to your queries.
Is SCM enabled and working?
Its enabled because if i am adding a new function then it shows under "New lines to cover" section with the code coverage percentage, but if i am adding/changing new condition (if else, switch) then it does not show under "New lines to cover" section.

Is there new code in your repository?
Yes we do have new code in our repository.
