### ISSUE TITLE
Cppcheck addons' rules support

### ISSUE THREAD

**Issue by begarco** [SonarOpenCommunity/sonar-cxx#1439]
### Description

It would be interesting to add rules from official Cppcheck addons in the plugin. Cppcheck is provided with addons for MISRA, CERT, etc ; but cxx is unable to load them without configuration.

### Steps to reproduce the problem

1. cppcheck --dump file.c
2. python $CPPCHECK_HOME/addons/addon.py file.c.dump

### Expected behavior

The sonar-cxx plugin natively  load issues discovered by official Cppcheck addons.

### Actual behavior

No addons' rule is integrated in the plugin.

### Known workarounds

Add all rules as XML.

### Related information

* cxx plugin version: all
* SonarQube version: all

**Comment by guwirth** [comment]
@begarco thanks for the feedback. 

Think this add on rules are hard to maintain. Where do we get a complete list of these rules? On the other hand seems to be less effort for you to add it with a customized XML?

**Comment by begarco** [comment]
I would say we can find checked rules directly in python scripts:
* CERT https://github.com/danmar/cppcheck/blob/master/addons/cert.py
  * EXP05-C: do not attempt to cast away const
  * EXP42-C: do not compare padding data
  * EXP46-C: Do not use a bitwise operator with a Boolean-like operand
  * INT31-C: Ensure that integer conversions do not result in lost or misinterpreted data
* MISRA https://github.com/danmar/cppcheck/blob/master/addons/misra.py
  * misra_3_1
  * misra_4_1
  * misra_5_1
  * misra_5_3
  * misra_5_4
  * misra_5_5
  * misra_7_1
  * misra_7_3
  * misra_8_11
  * misra_8_12
  * misra_8_14
  * misra_9_5
  * misra_10_4
  * misra_10_6
  * misra_10_8
  * misra_11_3
  * misra_11_4
  * misra_11_5
  * misra_11_6
  * misra_11_7
  * misra_11_8
  * misra_11_9
  * misra_12_1_sizeof
  * misra_12_1
  * misra_12_2
  * misra_12_3
  * misra_12_4
  * misra_13_1
  * misra_13_3
  * misra_13_4
  * misra_13_5
  * misra_13_6
  * misra_14_1
  * misra_14_2
  * misra_14_4
  * misra_15_1
  * misra_15_2
  * misra_15_3
  * misra_15_5
  * misra_15_6
  * misra_15_7
  * misra_16_2
  * misra_16_3
  * misra_16_4
  * misra_16_5
  * misra_16_6
  * misra_16_7
  * misra_17_1
  * misra_17_6
  * misra_17_8
  * misra_18_5
  * misra_18_8
  * misra_19_2
  * misra_20_1
  * misra_20_2
  * misra_20_3
  * misra_20_4
  * misra_20_5
  * misra_21_3
  * misra_21_4
  * misra_21_5
  * misra_21_7
  * misra_21_8
  * misra_21_9
  * misra_21_11
* Thread safety https://github.com/danmar/cppcheck/blob/master/addons/threadsafety.py
  * warn about static local objects
* Naming conventions https://github.com/danmar/cppcheck/blob/master/addons/naming.py
* Findcasts https://github.com/danmar/cppcheck/blob/master/addons/findcasts.py
  * Locate casts in the code

**Comment by ivangalkin** [comment]
@begarco the (core) cppcheck has a CLI argument, which allows to export all implemented checks with corresponding messages and other information. The fact, that it's a machine-readable format allows its (more or less) automatic import as SonarQube rules.

Addons miss this ability at the moment. Somebody has to file a feature request.

MISRA addon seems to be some special case. Cppcheck doesn't provide any quotes from the MISRA standard because of legal restrictions. I assume, that sonar-cxx wont be able to have any meaningful support for MISRA rules from the same reason (I'm not the lawyer though). Please read more here https://github.com/danmar/cppcheck/commit/b4924e59da6acdab4dcdead9ed197bda8c5ffe28

**Comment by ivangalkin** [comment]
@begarco on second thought I believe, that **technically** it's possible to follow the same strategy as cppcheck: if user provides the MISRA standard as input file, the sonar-cxx plugin could import it

* at the server side (while initialization, update etc) in form of the rules or
* at the worker side at least in form of error messages

(still not sure if it's acceptable from the legal point of view)

BUT I see the reliable listing of checks (with id, msg, maybe severity etc) as an important prerequisite, which addons unfortunately do not implement.
