### ISSUE TITLE
clangsa report is not uploaded into sonar because of NullPointerException

### ISSUE THREAD

**Issue by fukanchik** [SonarOpenCommunity/sonar-cxx#1442]
### Description
clangsa report is not uploaded into sonar. Enabling debug does not produce full stack trace in sonar-runner.

### Steps to reproduce the problem

1. Step A
Add `sonar.cxx.clangsa.reportPath=cpp/src/analyzer_reports/*/*.plist`

2. Step B
clang version 3.5.1
Run a build with `scan-build -plist --intercept-first --analyze-headers -o analyzer_reports make`
Run `sonar-runner -X -Dsonar.verbose=true -Dsonar.log.level=TRACE`
I also tried latest `sonar-scanner` with the same result: NPE+no stack trace even with DEBUG enabled.

### Expected behavior
clangsa report is uploaded to sonar

### Actual behavior

NullPointerException happens and report is not uploaded

### Known workarounds

I do not know workarounds

### LOG file

sonar-runner log:
```
11:02:51.394 INFO  - Processing report '/tmp/cpp/src/analyzer_reports/scan-build-2018-03-27-11-59-21-275517-dlfe8oko/report-8kay5uvd.plist'
11:02:51.394 DEBUG - Processing clangsa report 'report-8kay5uvd.plist''
11:02:51.424 ERROR - Cannot feed the data into sonar, details: 'java.lang.NullPointerException'
11:02:51.424 INFO  - Sensor c++ ClangSASensor [cxx] (done) | time=31ms
```
sonar log:
no NPE in sonar logs

### Related information

* cxx plugin version: 0.9.8
* SonarQube version: 6.5

**Comment by guwirth** [comment]
@fukanchik first question is always if clangsa rules are activated?

**Comment by guwirth** [comment]
@fukanchik second question is why not using 6.7 LTS?

**Comment by guwirth** [comment]
@fukanchik is there no exception stacktrace in the log file to get more details?
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

Maybe you can provide the stacktrace?

**Comment by fukanchik** [comment]
> @fukanchik first question is always if clangsa rules are activated?

I followed instructions from wiki pages `Installation` and `Running-the-analysis`. Do I need to do something else?

How do I distinguish `Clang Static Analyzer` rules from the list of 3712 rules in the sonar server? This page does not say anything about rules: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers#clang-static-analyzer

Anyway not enabled rules should not lead to  NPE.

I followed instructions from the page `Get-debug-information` no stack trace even with `-X` and `sonar.verbose=true`.

**Comment by fukanchik** [comment]
I am attaching the plist. Also, I enabled the `deadcode.DeadStores` in my profile. Problem is still there.

[report-0omkdyvv.plist.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/1856919/report-0omkdyvv.plist.txt)

**Comment by guwirth** [comment]
@fukanchik the stacktrace is logged on stderror and not stdout, mavbe you have to log also stderror
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

Microsoft Windows command line:
```
sonar-runner -X -Dsonar.verbose=true ... > sonar-runner.log 2>&1
```
Linux bash:
```
sonar-runner -X -Dsonar.verbose=true ... &> sonar-runner.log
```

**Comment by fukanchik** [comment]
No stacktrace on stderr. The only few lines printed to STDERR are related to coverage parsing:
```/tmp/2/cpp/src/cxx-library-sample/foo_test.cpp:source file is newer than notes file '/tmp/2/usr/src/cxx-library-sample/foo_test.gcno'
(the message is only displayed one per source file)
```

**Comment by fukanchik** [comment]
I upgraded Sonar to `Version 7.0 (build 36138)`, c++ plugin to `0.9.9`, sonar-scanner `3.2-SNAPSHOT`.

Result is the same: NPE and no stack trace anywhere.

This is how execution logged in sonarqube_ce.log:
```
2018.04.03 11:40:59 INFO  ce[AWKMKyAVy_M_lKvJp8nB][o.s.c.t.CeWorkerImpl] Execute task | project=org.codehaus.sonar:cxx-library-sample:master | type=REPORT | id=AWKMKyAVy_M_lKvJp8nB | submitter=fukanchi
2018.04.03 11:41:01 ERROR ce[AWKMKyAVy_M_lKvJp8nB][c.h.s.m.SonargraphMeasureComputer] Not processing for module: org.codehaus.sonar:cxx-library-sample:master
2018.04.03 11:41:01 ERROR ce[AWKMKyAVy_M_lKvJp8nB][c.h.s.m.SonargraphMeasureComputer] Not processing for module: org.codehaus.sonar:cxx-library-sample:master
2018.04.03 11:41:01 ERROR ce[AWKMKyAVy_M_lKvJp8nB][c.h.s.m.SonargraphMeasureComputer] Not processing for module: org.codehaus.sonar:cxx-library-sample:master
2018.04.03 11:41:01 ERROR ce[AWKMKyAVy_M_lKvJp8nB][c.h.s.m.SonargraphMeasureComputer] Not processing for module: org.codehaus.sonar:cxx-library-sample:master
2018.04.03 11:41:10 INFO  ce[AWKMKyAVy_M_lKvJp8nB][o.s.c.t.CeWorkerImpl] Executed task | project=org.codehaus.sonar:cxx-library-sample:master | type=REPORT | id=AWKMKyAVy_M_lKvJp8nB | submitter=fukanchi | time=10954ms
```

**Comment by fukanchik** [comment]
[This catch block](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxReportSensor.java#L121) by itself is not expected to produce stack trace. Therefore increasing verbosity and adding other debug options won't help producing a stack trace.

Next `CxxUtils.validateRecovery()` could print the stack trace, however on [this line](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxUtils.java#L122) 
```
throw new IllegalStateException(ex.getMessage(), ex.getCause());
```
`ex.getCase()` tries to get `cause` of NPE instead of NPE itself, which of course is missing since NPE in this case if the original exception. Therefore even with `sonar.cxx.errorRecoveryEnabled=false` NPE stack trace is not printed:
```
11:29:23.899 INFO: Recovery is disabled, failing analysis : 'java.lang.NullPointerException'
11:29:23.952 INFO: ------------------------------------------------------------------------
11:29:23.952 INFO: EXECUTION FAILURE
11:29:23.952 INFO: ------------------------------------------------------------------------
11:29:23.952 INFO: Total time: 10.206s
11:29:24.026 INFO: Final Memory: 40M/2222M
11:29:24.026 INFO: ------------------------------------------------------------------------
11:29:24.026 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException
    at org.sonar.cxx.sensors.utils.CxxUtils.validateRecovery(CxxUtils.java:122)
    at org.sonar.cxx.sensors.utils.CxxReportSensor.execute(CxxReportSensor.java:128)
    at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
    at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
    at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
    at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
    at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
    at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
    at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
    at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
    at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
    at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
    at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
    at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
    at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
    at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
    at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
    at com.sun.proxy.$Proxy0.execute(Unknown Source)
    at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
    at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
    at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
    at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
    at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

**Comment by fukanchik** [comment]
This is because I am using clang 3.5.0 which does not produce `check_name`.

Check name was added here: https://reviews.llvm.org/D6841 (see also [this commit](https://github.com/llvm-mirror/clang/commit/8a73552a68f88a4765385b4ea5e6d5b77c62bd24#diff-a70864058675600dc834d8940dfc91d2R390) )

Addition of `check_name` was never mentioned in clang release notes. So I had to verify versions from this page: http://releases.llvm.org/download.html The earliest version of clang which produces `check_name` is `clang version 3.7.0 (tags/RELEASE_370/final)`.

Because of the missing field, NPE in clangsa sensor happens [on this line](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/clangsa/CxxClangSASensor.java#L91).

I think it makes sense to add this information to https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers#clang-static-analyzer plus add version check to clang sa sensor code.

**Comment by ivangalkin** [comment]
I am not an expert in this particular XML format, but at least...
* ruleId (check_name)
* issue text (description)

... are mandatory in terms of SonarQube issue API. So we have to check their existence during the parsing process at latest.

```diff
diff --git a/cxx-sensors/src/main/java/org/sonar/cxx/sensors/clangsa/CxxClangSASensor.java b/cxx-sensors/src/main/java/org/sonar/cxx/sensors/clangsa/CxxClangSASensor.java
index 2c9d66d..318ab99 100644
--- a/cxx-sensors/src/main/java/org/sonar/cxx/sensors/clangsa/CxxClangSASensor.java
+++ b/cxx-sensors/src/main/java/org/sonar/cxx/sensors/clangsa/CxxClangSASensor.java
@@ -85,9 +85,19 @@ public class CxxClangSASensor extends CxxReportSensor {
       for (NSObject diagnostic : diagnostics) {
         NSDictionary diag = (NSDictionary) diagnostic;
 
+        if (!diag.containsKey("description"))
+        {
+          LOG.warn("Array element from \"diagnostics\" doesn't contain mandatory key \"description\". Skip current entry. ");
+          continue;
+        }
         NSString desc = (NSString) diag.get("description");
         String description = desc.getContent();
 
+        if (!diag.containsKey("check_name"))
+        {
+          LOG.warn("Array element from  \"diagnostics\" doesn't contain mandatory key \"check_name\". Skip current enetry. ");
+          continue;
+        }^M
         String checkerName = ((NSString) diag.get("check_name")).getContent();
 
         NSDictionary location = (NSDictionary) diag.get("location");
```

Checking of the report version would be even better, but it requires some kind of fuzzy regexp, since it's not split into major/minor version, but is represented as the build info of clang

```xml
<plist version="1.0">
   <dict>
      <key>clang_version</key>
      <string>clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)</string>
      ...
   </dict>
</plist>
```

**Comment by ivangalkin** [comment]
@guwirth I would like to provide a fix/workaround for the reported bug. What is the correct and consistent error handling w.r.t. the wrong XMLs in sonar-cxx?

At the first glance I see at least 3 possible solutions:

a. Warn and ignore: (see patch above). The disadvantage of this strategy is that such error could be overseen
b. Abort the sensor. That would terminate the complete worker. Might be unfortunate, because e.g. nightly [Java-]Analysis will be missing too
c. Introduce of some generic rule with a key like "clangsa_uncategorized". If "check_name" is missing (which seems to be possible in the older formats) we could map the finding to this rule. Rule description will contain a  warning about the old format. Missing of both "check_name" and  "description" is a symptom of a broken XML and we could again decide between terminating or ignoring.

**Comment by ivangalkin** [comment]
@guwirth 

thank you for the information. After research about the clang SA XML format I think there is one more solution if we want to support clang SA < 3.7:

d. we have to duplicate all the existing rules, but use less distinct property "category" instead of "check_name" as a rule ID. [Diff](https://reviews.llvm.org/rL228624#change-K0_0gMuGRVbe) shows the difference between "category" and "check_name"

```diff
// CHECK-NEXT:   <key>description</key><string>Memory allocated by &apos;new[]&apos; should be deallocated by &apos;delete[]&apos;, not &apos;delete&apos;</string>
// CHECK-NEXT:   <key>category</key><string>Memory Error</string>
// CHECK-NEXT:   <key>type</key><string>Bad deallocator</string>
+ // CHECK-NEXT:   <key>check_name</key><string>unix.MismatchedDeallocator</string> 
```

So the general question is whether sonar-cxx officially supports clang SA < 3.7 or only versions >= 3.7 are supported.
If we support it we have options 
c) dummy rule-id, no sorting, no filtering for the user
d) use "category" as rule IDs, which requires additional rules

If we don't support the older versions we still have
a) or b) which are ignore or terminate the XML import respectively

I don't have a strong opinion about which solution is the best, but b) or d) seem to be the most consistent ones.
