### ISSUE TITLE
import cmake ctest results

### ISSUE THREAD

**Issue by fpruvost** [SonarOpenCommunity/sonar-cxx#1451]
Hi,

For my project I do not rely on a specific unit testing framework such as boosttest, cpptestunit, cppunit, etc but on cmake ctest only.

I would like to know if it's possible to import cmake ctest tests results generated for example with 
```
ctest --no-compress-output -T Test
```
It generates a `Test.xml` file which seems not compatible with what expects the plugin.

Reading the section of the [wiki](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-test-execution-metrics) there is no mention of cmake ctest xml reports. 
Do you have any idea, is it possible ?

sonarqube 6.7.2
sonar-cxx v0.9.9
cmake 3.5.1

**Comment by fpruvost** [comment]
ok, thank you for your prompt response

**Comment by guwirth** [comment]
Hi @fpruvost,

ctest supports a new output option creating JUnit reports, please try with #2404 and give feedback in that issue. In case it is not working attach a sample report please. 

Regards

**Comment by fpruvost** [comment]
Hi @guwirth thanks for your udpate.
It works partially, I have no error but the tests are not displayed (I just get the number of tests), see the result here : https://sonarqube.inria.fr/sonarqube/dashboard?id=sed-bso%3Aheat%3Agitlab

I have tested using `ctest --output-junit report.xml` 
```
sonar.cxx.xunit.reportPath=report.xml
```

and also using xslt transform:
```
sonar.cxx.xunit.xsltURL=https://raw.githubusercontent.com/rpavlik/jenkins-ctest-plugin/master/ctest-to-junit.xsl
sonar.cxx.xunit.reportPath=build/Testing/**/Test.xml
```
for same result.

[sonar.log](https://github.com/SonarOpenCommunity/sonar-cxx/files/9151805/sonar.log)

**Comment by guwirth** [comment]
Hi @fpruvost,

thanks for your investigation. 

First of all I saw that you are still using an old SQ and plugin version. If possible upgrade to latest SQ 8.9 and cxx 2.x:
```
17:56:49.511 DEBUG: Community 7.9.5.38598
17:56:49.984 DEBUG:   * C++ (Community) 1.3.2.1853 (cxx)
```
Second thing I’m wondering is why you need an XSL? For my understanding XUnit sensor should understand the JUnit, or what’s different with CTest? Can you provide a sample report **without** XSL?
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.xunit.reportPaths#supported-versions

To get more than only the test numbers `sonar.tests` must be set. The indexed test files (source code files with unit tests) must fit with the path in your report. Code reading it is here:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/c5229cd7b92dfcf468957aba3324837a5ed5d4c3/cxx-sensors/src/main/java/org/sonar/cxx/sensors/tests/xunit/CxxXunitSensor.java#L117

Regards,

**Comment by guwirth** [comment]
Hi @fpruvost,

is it working for you now?
Can you provide
* the command line you use
* a sample report file from ctest

I like to extend the docu. 

Regards,

**Comment by fpruvost** [comment]
Hi,

I have upgraded sonarqube to 8.9 LTS with sonar-cxx 2.0.7.
Here is the [result](https://sonarqube.inria.fr/sonarqube/component_measures?id=sed-bso%3Aheat%3Agitlab&metric=tests&view=list).
We can read that there are 3 unit tests but with empty results (don't know there status and no source code).

`sonar.tests` can be used for C/C++ projects ? If I read [this](https://community.sonarsource.com/t/has-sonar-tests-an-effect-on-c-sonarscanner-projects/53330/5) I'm not sure.

I attach the sonar-scanner log :
[sonar.log](https://github.com/SonarOpenCommunity/sonar-cxx/files/9280047/sonar.log)

the sonar-project.properties
```
sonar.host.url=https://sonarqube.inria.fr/sonarqube
sonar.projectKey=sed-bso:heat:gitlab
sonar.branch.name=master
sonar.links.homepage=https://gitlab.inria.fr/sed-bso/heat
sonar.links.scm=https://gitlab.inria.fr/sed-bso/heat.git
sonar.projectDescription=Solve the heat propagation equation
sonar.projectVersion=2.0
sonar.scm.disabled=false
sonar.scm.provider=git
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusions=build/CMakeFiles/**,cmake_modules/**,doc/**,formation/**,tools/**,**/*.html,**/*.xml,**/*.css
sonar.cxx.file.suffixes=.h,.c
sonar.cxx.errorRecoveryEnabled=true
sonar.cxx.includeDirectories=/usr/lib/gcc/x86_64-linux-gnu/9/include,/usr/local/include,/usr/include/x86_64-linux-gnu,/usr/include,/usr/lib/x86_64-linux-gnu/openmpi/include,include,.
sonar.cxx.gcc.encoding=UTF-8
sonar.cxx.gcc.regex=(?<file>.*):(?<line>[0-9]+):[0-9]+:\\\x20warning:\\\x20(?<message>.*)\\\x20\\\[(?<id>.*)\\\]
sonar.cxx.gcc.reportPaths=build/heat-build.log
sonar.cxx.clangsa.reportPaths=build/analyzer_reports/*/*.plist
sonar.cxx.clangtidy.reportPaths=clang-tidy-report
sonar.cxx.cobertura.reportPaths=heat-coverage.xml
sonar.cxx.cppcheck.reportPaths=heat-cppcheck.xml
sonar.cxx.rats.reportPaths=heat-rats.xml
sonar.cxx.vera.reportPaths=heat-vera.xml
sonar.cxx.valgrind.reportPaths=heat-valgrind.xml
sonar.cxx.xunit.reportPaths=heat-junit.xml
```
and the junit report generated with a `cmake --output-junit ../heat-junit.xml`

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Linux-amd64-cc-mpi"
	tests="3"
	failures="0"
	disabled="0"
	skipped="0"
	hostname="esthar"
	time="0"
	timestamp="2022-08-08T09:51:26"
	>
	<testcase name="heat_seq_usage" classname="heat_seq_usage" time="0.000872568" status="run">
		<system-out>Usage: /home/florent/git/heat/build/heat_seq nx ny iter_max save
	nx       number of discretisation points in X
	ny       number of discretisation points in Y
	iter_max maximal number of iterations in temporal loop
	save     boolean flag (1 or 0) for recording states
	print    boolean flag (1 or 0) for printing the states matrix to the standard output
</system-out>
	</testcase>
	<testcase name="heat_seq_err_10" classname="heat_seq_err_10" time="0.000996883" status="run">
		<system-out>heat: it = 0, t = 0.000e+00, err = 1.732e+00
heat: 
[heat: 1.000000,heat: 1.000000,heat: 1.000000,heat: 1.000000,heat: 1.000000,heat: 1.000000,heat: 1.000000,heat: 1.000000,heat: 1.000000,heat: 1.000000,heat: 1.000000,heat: 1.000000
heat: 1.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 1.000000
heat: 1.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 1.000000
heat: 1.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 1.000000
heat: 1.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 1.000000
heat: 1.000000,heat: 0.000000,heat: 0.000000,heat: 0.000000,heat: 0.000...
The rest of the test output was removed since it exceeds the threshold of 1024 bytes.
</system-out>
	</testcase>
	<testcase name="heat_par_4" classname="heat_par_4" time="0.382706" status="run">
		<system-out>Invalid MIT-MAGIC-COOKIE-1 keyheat: it = 0, t = 0.000e+00, err = 1.732e+00
heat: it = 10, t = 2.500e-02, err = 2.518e-01
heat: it = 20, t = 5.000e-02, err = 1.562e-01
heat: it = 30, t = 7.500e-02, err = 1.031e-01
heat: it = 40, t = 1.000e-01, err = 6.815e-02
heat: it = 50, t = 1.250e-01, err = 4.507e-02
heat: it = 60, t = 1.500e-01, err = 2.980e-02
heat: it = 70, t = 1.750e-01, err = 1.971e-02
heat: it = 80, t = 2.000e-01, err = 1.304e-02
heat: it = 90, t = 2.250e-01, err = 8.621e-03
heat: it = 100, t = 2.500e-01, err = 5.701e-03
heat: it = 110, t = 2.750e-01, err = 3.770e-03
heat: it = 120, t = 3.000e-01, err = 2.493e-03
heat: it = 130, t = 3.250e-01, err = 1.649e-03
heat: it = 140, t = 3.500e-01, err = 1.091e-03
heat: it = 150, t = 3.750e-01, err = 7.212e-04
heat: it = 160, t = 4.000e-01, err = 4.769e-04
heat: it = 170, t = 4.250e-01, err = 3.154e-04
heat: it = 180, t = 4.500e-01, err = 2.086e-04
heat: it = 190, t = 4.750e-01, err = 1.380e-04
</system-out>
	</testcase>
</testsuite>
```

Thanks

**Comment by guwirth** [comment]
Hi @fpruvost,

thanks for providing the input.

Looking to your LOG file the XUnit sensor is reading one file `heat-junit.xml` with three tests:
```
09:53:32.339 INFO: Sensor CXX xUnit Test report import [cxx]
09:53:32.339 DEBUG: Searching 'sonar.cxx.xunit.reportPaths' files with Ant pattern '[heat-junit.xml]'
09:53:32.339 DEBUG: Search files(s) in path(s): '/home/florent/git/heat/heat-junit.xml'
09:53:32.339 DEBUG: Found '1' file(s)
09:53:32.340 INFO: Processing xUnit report '/home/florent/git/heat/heat-junit.xml'
09:53:32.346 DEBUG: Saving xUnit report data: tests=3, errors=0, failure=0, skipped=0, time=382
09:53:32.348 INFO: Sensor CXX xUnit Test report import [cxx] (done) | time=9ms
```
This fits to:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Linux-amd64-cc-mpi"
	tests="3"
	failures="0"
	disabled="0"
	skipped="0"
...
```
Because there is no `filename` attribute in the report, you see only an overall metric and not metrics per test file. The report file format is described here:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.xunit.reportPaths

In case you wanna use `filename` attribute the referenced file(s) must be indexed as test file. For this you have to set the path to the test cases with `sonar.tests`.

Regards,

**Comment by guwirth** [comment]
Hi @fpruvost,

one more remark
```
<testcase name="heat_seq_err_10" classname="heat_seq_err_10" time="0.000996883" status="run">
```
Seems that ctest creates only `classname` attribute. SonarQube can't resolve class names (find out corresponding test file). Maybe there is also an ctest option to create the `filename` atrribute?

Regards,

**Comment by guwirth** [comment]
Hi @fpruvost,

> `sonar.tests` can be used for C/C++ projects ? If I read [this](https://community.sonarsource.com/t/has-sonar-tests-an-effect-on-c-sonarscanner-projects/53330/5) I'm not sure.

There are at least two C++ plugins, commercial and community (cxx plugin). They are talking about the commercial C++ plugin from SonarSource.

 Regards,

**Comment by fpruvost** [comment]
> Maybe there is also an ctest option to create the `filename` atrribute?

Looking into the [cmake code](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Source/CTest/cmCTestTestHandler.cxx#L2507) , the `filename` attribute seems not be handled at all unfortunately.

So ok, the number of unit tests in success/failure is captured by the plugin but without the list of tests (neither test name nor link to the source file) for now because ctest does not set the `filename` or `file` like attribute.

If I add the filename attribute by myself I can see the source files in the Test.
What is missing is the list of tests by name because here what I can see is just the number of tests and how many tests are related to each test file, see [this example](https://sonarqube.inria.fr/sonarqube/component_measures?id=sed-bso%3Aheat%3Agitlab&metric=tests&view=list). Is this relevant for ctest and c++ ? I mean, what we could expect here is a list of unit tests, using the `name` attribute and see the status of each test (success/failure), no ?

Thanks

**Comment by guwirth** [comment]
> What is missing ...

The possibilities for visualization in the _SonarQube_ UI are unfortunately very limited, we can only use the existing APIs. There was also a statement from _SonarSource_ about this issue: https://community.sonarsource.com/t/generic-test-where-can-i-find-message-and-stacktrace-in-the-sq-ui/68696

> SonarSource: I’ll be honest & say that as an organization we’ve never really believed in those test metrics. Why? Because we feel that if you’ve got failing tests, the pipeline should stop then & there. You shouldn’t just count the failures & move on. That’s why we’ve slowly but surely been moving away from these metrics.

Maybe you can give feedback there to motivate improvements in the future.

**Comment by fpruvost** [comment]
Ok thanks for the support about this feature. I think we can close this issue.
Best regards
