### ISSUE TITLE
Deprecation warnings while parsing of .properties

### ISSUE THREAD

**Issue by ivangalkin** [SonarOpenCommunity/sonar-cxx#1463]
Usage of deprecated API

* cxx plugin version -> HEAD
* SonarQube version -> 7.0, 7.1

Warning: Access to the multi-values/property set property 'sonar.cxx.coverage.reportPath' should be made using 'getStringArray' method. The SonarQube plugin using this property should be updated.

**Comment by guwirth** [comment]
Duplicate #1384

**Comment by ivangalkin** [comment]
duplicate #1384
