### ISSUE TITLE
Not able to detect Code Smells

### ISSUE THREAD

**Issue by amitkumar2283** [SonarOpenCommunity/sonar-cxx#1466]
Please [turn debug info on](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information) and reproduce your issue.
The debug info in the log file could help to solve or locate the issue.

### Description

We are evaluating the CXX plugin for use in our project which consists **only** of C Files. We have install the plugin, created a Quality Profile "demoC" while enabling *all* the rules. We have deliberately added couple of "bad" statements in our C file which are expected to be caught by Sonar Analysis. Please note that the analysis runs on Windows machine.
 
### Steps to reproduce the problem

Attached is a Zip file with our Demo C file and the sonar-project.properties.
The Quality Profile is configured with all rules. Here is an SS:
![image](https://user-images.githubusercontent.com/17488415/39228454-eea2bb00-487b-11e8-9186-b203a095b9cf.png)

Just execute the analysis with Sonar-scanner on windows.
### Expected behavior

The Below Code smells are expected.
* Division by zero (on line 16 of sonarDemo.c)
    	`firstNumber = 24/0;`
* Missing 'return' statement in non-void function causes undefined behavior (on line 17 of sonarDemo.c)
       ` // return 0;`

### Actual behavior

No Expected Code Smells. We do get some code smells, but the absence of above mentioned ones are deal breakers.
Here is the SS of the Code Analysis:

![image](https://user-images.githubusercontent.com/17488415/39228386-94a13fbe-487b-11e8-8d9d-1182aa552247.png)

### Known workarounds

None
### LOG file

Attached Log File. No errors or warnings
[Sonar_C-Scan_demo.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/1945636/Sonar_C-Scan_demo.zip)
[sonar-runner.log](https://github.com/SonarOpenCommunity/sonar-cxx/files/1945637/sonar-runner.log)

### Related information

* cxx plugin version : 0.9.8
* SonarQube version : 5.6 LTS

**Comment by guwirth** [comment]
Hi @amitkumar2283, the plugin is doing no own static code analysis. You have to run an external tool first and provide the resulting reports.

* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-the-analysis
* e.g. Cppcheck: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers
   * https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties#sonarcxxcppcheckreportpath

**Comment by amitkumar2283** [comment]
Hi @guwirth,
Thanks for the response.
Can you please let me understand where do the reported Code Smells come from, if there is no analysis done by Sonar itself.

**Comment by guwirth** [comment]
@amitkumar2283 have you read this?

* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-the-analysis
* e.g. Cppcheck: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers
   * https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties#sonarcxxcppcheckreportpath

Sample project: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/cppcheck_project
