### ISSUE TITLE
RFF cxx plug-in 1.0 release

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1472]
Hi,

like to release the 1.0 version.
Last features/fixes are #1449 and #1447. 
Any comments?

Regards

**Comment by Bertk** [comment]
:+1

**Comment by ivangalkin** [comment]
Hi All, #1447 was updated w.r.t. to the latest comments. Please review. Thank you!

**Comment by guwirth** [comment]
I try to release on Sunday evening.

**Comment by guwirth** [comment]
Draft for release nodes: complete? Feedback is welcome.


---
We are pleased to announce the SonarQube C++ Community Plugin version 1.0.0.
See lists below for features added and bugs fixed in this release.

# SonarQube compability

- tested and released for **SonarQube 6.7 LTS, 7.0, 7.1**<br>see also [SonarQube compatibility matrix](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix)
- [Installation Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Installation)
- [Upgrade Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-Instructions)

# Enhancements

* minimal supported SQ API is 6.7 #1317
* updated parent POM to 44
* set an unique name to distinguish between community and commercial plugin in UI  #1433
* optimize Sensor usage with SensorDescriptor #1421 #1434 #1420
* implement support for multiple locations in CxxReportSensor #1447
* Cppcheck 1.83 support  #1455 #1450
* Cppcheck support external library issues #1445
* CppcheckParserV2: allow multiple issue locations #1436
* Visual Studio 2017 15.6 & 15.7 support #1454  #1453 #1399 
* CxxValgrindSensor: allow multiple <stack> nodes #1440  #1461 #1440 
* RATS 2.4 support #1419 #1395
* remove `scanOnlySpecifiedSources` #1476
* travis.yml: execute automatic HTML checks for rules files #1467 #1456
* fix quality flaws #1448 #1473 #1471 #1470 #1469 #1464 #1461 #1452 #1441 #1432 #1426 #1414 #1408 
* test with new SQ versions #1462 #1459 #1430 #1428 #1417 #1413
* test with sonar-scanner-cli-3.1.0.1141 #1460

# Bugfixes

* problem with sonar.cxx.jsonCompilationDatabase when it includes testcode you don't want to scan #1474 #1476
* clangsa report is not uploaded into sonar because of NullPointerException #1442 #1477
* fix squid:S2259 #1431
* wrong code coverage for empty line, constexpr, method declaration #1425

# Know Issues

For an up to date list of known issues see the issue tracker.
- not compatible with Java 9
- Ensure that a rule is enabled if you get no results. In new SQ versions the default profile is read-only. The cxx plugin does not enable all rules per default.
- Starting with SQ 6.2 there are some new metrics and some are no more available. Please have a look to the SonarQube release notes.
- [test execution metrics](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-test-execution-metrics) are not supported
- The [Cppckeck plugin](https://github.com/SonarQubeCommunity/sonar-cppcheck) is deprecated and not working in parallel to this plugin. This plugin provides an own Cppcheck sensor.
- C plugin and JSON Compilation Database support are experimental only
- Symlinks are not supported.

# Thanks ....

go to all contributors (in alphabetical order):

@Bertk
@guwirth
@ivangalkin

... and all people which were active on the issue tracker!
