### ISSUE TITLE
gcovr coverage results not updated in the SonarQube dashboard

### ISSUE THREAD

**Issue by freeeyes** [SonarOpenCommunity/sonar-cxx#1483]
### Description

gcovr coverage results not updated in the SonarQube dashboard

### Steps to reproduce the problem
I use travis-ci to integrate sonarcloud, and code coverage reports have been unable to submit to sonar pages.code coverage is 0.0%
I wonder if I have a problem with my parameters?
Please ask anyone who knows to help me with one or two，thanks.

### Expected behavior

gcovr coverage results updated in the SonarQube dashboard

### Actual behavior

gcovr coverage results not updated in the SonarQube dashboard

### Known workarounds

==========================================
sonar-project.properties:

sonar.projectKey=freeeyes
sonar.organization=freeeyesgithub
sonar.projectName=PSS
sonar.projectVersion=1.0
sonar.sources=./
sonar.cfamily.build-wrapper-output=./Linux_Bin/bw-output
sonar.exclusions=**TinyXML/**,**Mail/**,**Windows_Bin/**,**Linux_Bin/**,**lib/**
sonar.coverage.reportPath=report.xml

### LOG file

travis-ci log:

08:18:13.259 DEBUG: 'gcov' skipped because one of the required properties is missing
08:18:13.260 DEBUG: 'llvm-cov' skipped because one of the required properties is missing
08:18:13.261 DEBUG: 'cppunit' skipped because one of the required properties is missing
08:18:13.261 DEBUG: 'VisualStudioCoverage' skipped because one of the required properties is missing
08:18:13.262 DEBUG: 'bullseye' skipped because one of the required properties is missing

travis-ci script:
- gcovr -r ../ -o ../../report.xml --xml-pretty
- sonar-scanner -X

### Related information

sonarcloud

**Comment by guwirth** [comment]
Hello @freeeyes,

Are you sure you are using the cxx-plugin? Asking because I saw `sonar.cfamily.build-wrapper-output` in your configuration.

Settings for coverage tools:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Coverage-tracers

Mostly there are problems with paths:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues

Regards,

**Comment by freeeyes** [comment]
thanks for your answer. 
I use sonarcloud as if I could not install cxx plugin.
I try some other way.
