### ISSUE TITLE
sslr-cxx-toolkit-1.0.0.jar is not a plugin

### ISSUE THREAD

**Issue by nehk018** [SonarOpenCommunity/sonar-cxx#1500]
I'm trying to install the plugin with this steps: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Installation

I moved the download files to /opt/sonar/extensions/plugins.
When I try to start sonarquebe, in the web-log I have the next error message:

2018.06.19 12:37:57 ERROR web[][o.s.s.p.Platform] Web server startup failed: File is not a plugin. Please delete it and restart: /opt/sonar/extensions/plugins/sslr-cxx-toolkit-1.0.0.jar

My plugin version is: 1.0.0
My Sonar version is: 6.7.4

Thank you.
Jorge

**Comment by guwirth** [comment]
@nehk018 sslr-cxx-toolkit is not a plugin. It's a tool to verify the C++ syntax, create an AST and create and verify XPath queries.
