### ISSUE TITLE
Version 1.1.0 is Untagged - Leading to URL Issues

### ISSUE THREAD

**Issue by sethmccombs** [SonarOpenCommunity/sonar-cxx#1515]
### Description

The latest release, 1.1.0 is untagged, leading to a download URL - https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/untagged-7d983a13a285903217b5  
As opposed to the previous 1.0.0 release - 
https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-1.0.0  

### Steps to reproduce the problem

Please provide the steps required to reproduce the problem

1. Package building script is searching for repos in the https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-x.x.x format

2. Script searches for latest - https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-1.1.0 and is unable to find it, leading to build script to fail

### Expected behavior

Version 1.1.0 should have URL - 
https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-1.1.0  

### Actual behavior
Latest version has URL - 
https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/untagged-7d983a13a285903217b5  

Version 1.1.0 has URL 
### Known workarounds

Hard code broken URL into build script

### LOG file

Any warnings/errors in the LOG file?

### Related information

* cxx plugin version?
* SonarQube version?

**Comment by ivangalkin** [comment]
@guwirth for your information: during my first attempt to fix the issue I tagged the `HEAD` with `cxx-1.1.0` by mistake; the second re-release tags the original commit of 1.1.0 https://github.com/SonarOpenCommunity/sonar-cxx/commit/6a44b2479f82465afa48345f9ca857bc0289fb7e

By the way: I've used `git push upstream :refs/tags/untagged-7d983a13a285903217b5`, which changed the status of the release from **Latest release** to **Draft**. Afterwards I re-released it with correct tag [and commit].

**Comment by sethmccombs** [comment]
Thanks @ivangalkin! 

I should have been more specific in my use case. I have an AWS CodeDeploy package that bundles some sonar stuff stuff, including sonar-cxx. It's looking for that specific tag format, and that's what broke, nothing on your end in terms of build, it was just that tag throwing my package script off!

**Comment by sethmccombs** [comment]
I was able to successfully run my scripts to pull in this package, now that that tag is updated. If you want any elaboration, feel free to ask, but I'mm close as my issue is all good! Thanks team!

**Comment by ivangalkin** [comment]
Hi @sethmccombs! I am happy that your script works again.
