### ISSUE TITLE
rules repositories: solve inconsistent rules activation

### ISSUE THREAD

**Issue by ivangalkin** [SonarOpenCommunity/sonar-cxx#1527]
make all rules disabled by default
see #1521

**Comment by guwirth** [comment]
@ivangalkin agree: make all rules disabled by default

**Comment by guwirth** [comment]
The default rules are defined in the default-profile.xml files:
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-c-plugin/src/main/resources/default-profile.xml
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/resources/default-profile.xml

They are activated in:
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CxxDefaultProfile.java#L54
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-c-plugin/src/main/java/org/sonar/plugins/c/CDefaultProfile.java#L54

I will keep the files (mechanism) but remove all items. Default is then that all rules from external checkers are off per default.
