### ISSUE TITLE
sonarqube not showing any issues(c++), and I have issue with covearge too

### ISSUE THREAD

**Issue by palavaianoop** [SonarOpenCommunity/sonar-cxx#1531]
Please [turn debug info on](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information) and reproduce your issue.
The debug info in the log file could help to solve or locate the issue.

### Description
I am unable to see the issues in C++
Please provide a succinct description of your issue.
I have nearly 700 active rules!
->Right know I am planning to install CPPCheck plugin 
### Actual behavior
[
![image](https://user-images.githubusercontent.com/29358331/43502464-43e806a4-9518-11e8-9603-87b0d0279268.png)
![image 1](https://user-images.githubusercontent.com/29358331/43502482-57aa5534-9518-11e8-937a-86c8b77ef1f5.png)

](url)

* cxx plugin version?  - C++ (Community) 0.9.9 (cxx)
* SonarQube version?6.7.1

**Comment by guwirth** [comment]
@palavaianoop 

The community plugin is using mainly external tools to detect issues. This is a two step process:
1. Run your external tool and create a report the plugin is able to read
2. Run the sonar scanner to read and forward the issues to SQ

For cppcheck:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-the-analysis
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers#cppcheck

Hope this helps!

**Comment by palavaianoop** [comment]
I have requested CPPCheck plugin to install
**Steps to reproduce**: https://github.com/SonarQubeCommunity/sonar-cppcheck.git
If you go through the above link, in sonarqube Community 
Results:
 
![image](https://user-images.githubusercontent.com/29358331/43742394-001eee1c-998f-11e8-8710-d4a8f5738cac.png)

**Expected results**
Same as above result, includes Code coverage
**Suspected root cause**:
Existed C++ Plugin( C++ (Community) 0.9.9 (cxx)) not analyzing Code Coverage 
**Proposed solution alternatives:**
Installing CPPCheck Plugin in SonarQube Server for analyzing Code Coverage for CPP File
----------------------------------
**Sonarqube Admin**:
I don't think the issue or proposed solution are well understood to make a server environment change.

The requested plugin is a Cppcheck report importer: https://github.com/SonarQubeCommunity/sonar-cppcheck
The production http://sonarqube/ server includes sonar-cxx: https://github.com/SonarOpenCommunity/sonar-cxx

**Comment by ivangalkin** [comment]
Hello @palavaianoop,

a couple of comments from my side:

1. https://github.com/SonarQubeCommunity/sonar-cppcheck is obsolete.
* it doesn't recognize the latest cppcheck rules
* it doesn't recognize the newest cppcheck XML format and
* (most important) it won't run with the modern versions of SonarQube

So I would recommend you to use sonar-cxx instead. If you observe some problems please activate debug traces and submit us the log (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information)

2. please make sure that the rules for cppcheck are activated on the server: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Activate-quality-rules and please don't forget to associate your project with the corresponding code profile.

3. Coverage reports have to be imported separately. There is no correlation between cppcheck and coverage reports. You might want to read the list of supported coverage formats (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Coverage-tracers) and use one of them (e.g. cobertura, which is gcov postprocessed by gcovr).

Again, if there will be some issues, please create a debug trace and attach it to the ticket. Thank you.

@guwirth @rufinio: looks like we are missing Testwell CTC++ in the list of coverage formats (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Coverage-tracers). Just for your information.

Regards,

**Comment by palavaianoop** [comment]
@ivangalkin  Thanks for your valuable response 
As per your word i will try Coverage-tracers 
I will keep you Posted When I done with Code Coverage for C++.

**Comment by guwirth** [comment]
@ivangalkin

>  looks like we are missing Testwell CTC++ in the list of coverage formats 

Saw you added it. More information as linked on:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-code-coverage-metrics

But agree. Biggest issues of the cxx plugin is the wiki....
