### ISSUE TITLE
US: Clang-Tidy 8 support (update clangtidy.xml)

### ISSUE THREAD

**Issue by nathanaelg** [SonarOpenCommunity/sonar-cxx#1536]
### Description

https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/clangtidy.xml is a bit out of date with http://clang.llvm.org/extra/clang-tidy/checks/list.html

### Questions for implementation

Most of the required data is pulled straight from clang.llvm.org with a couple of exceptions:
- we seem to only have a subset of the more relevant ones (I'm happy to make a call on selecting the more generic C/C++ rules rather than random specific project rules like `abseil-string-find-startswith`)
- severity (INFO, MINOR, MAJOR, CRITICAL) and type (BUG or CODE_SMELL) is where I come unstuck - is this decided just fairly arbitrarily?

**Comment by ivangalkin** [comment]
Hi @nathanaelg, @guwirth,

I figured out how to convert an original clang tidy documentation to the perfectly looking SonarQube rules:
1. Checkout the https://github.com/llvm-mirror/clang-tools-extra/tree/master/docs/clang-tidy/checks
2. Convert reStructuredText to HTML by means of [pandoc](https://github.com/jgm/pandoc)
3. Write a similar script to [cppcheck_createrules.py](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/tools/cppcheck_createrules.py) for the generation and DIFF of XML rule files

I'll automatize this process and submit the rules updates.

**Comment by nathanaelg** [comment]
@ivangalkin I had a bit of a look at something similar but the point that I got stuck on was how to allocate the severity or type, because there didn't seem to be something equivalent in the clang-tidy documentation?

**Comment by ivangalkin** [comment]
@nathanaelg @guwirth  as long as there is no differentiation at the tool's side, I would let the user decide on the severity. I was thinking about marking all rules equally severe (e.g. "Major Bug" or "Major Code Smell"). If it doesn't suit the user's taste, he/she can always make a copy of the quality profile and tweak the severity of each and every single rule. I believe it's a good compromise. What do you think?

**Comment by nathanaelg** [comment]
I think having severity set to sane values out of the box is of value, and I think most of clang tidy's checks should probably be code smells rather than bugs. Maybe default to minor code smell and then have a file which the `createrules` script uses to assign higher severity for specific cases? 

It would still certainly be less work to manually maintain just that file with `rule name` <=> `severity` mapping than the current XML file with all the documentation about the rule.

**Comment by ivangalkin** [comment]
@nathanaelg 

> Maybe default to minor code smell...

Clang-Tidy deals mainly with code smells, so "code smell" as default issue type seems reasonable to me. I prefer "major" because it lays in the middle of the severity scale ("info -> minor -> major -> critical -> blocker"), which again has a touch of default-value .

>...and then have a file which the createrules script uses to assign higher severity for specific cases

Having some sane default values would be comfortable, I agree with it. However I'm not sure, that we can please all users. E.g. in the issue description you suspect, that the existing mapping is "just fairly arbitrarily". IMHO agreeing on some default severity would be consistent and comprehensible. 

I'll start with the implementation of the automation script (probably there will be some unification with the existing generation logic for cppcheck). So we can come back to the severity discussion when PR is ready.

**Comment by guwirth** [comment]
> as long as there is no differentiation at the tool's side, I would let the user decide on the severity.

The classification of rules is the main value of SonarQube. Most users like to use SQ and this plugin out of the box.
* We have the same problem with Visual Studio rules (static code analyzer, CoreGuidlineChecker).
* With another tool I solved this by searching for words like `critical`, `memory leak`, ... in the text to classify it.
* Looking to the SQ description the default is Code Smell / Info.
* Looking to https://www.sonarqube.org/sonarqube-7-2/ External Analyzers the main drawback of this new interface is that all users have to classify there tools/rules by their own.

My proposal: add them with a default and then goes through it manually and rate them with the description of type/severity above. This is typically only once a bigger effort. Changes in new versions are mostly small.

**Comment by ivangalkin** [comment]
@guwirth I shouldn’t have added “closes #1536” to the merged pull request. Sorry.  I’ll reopen the issue and provide a pull request with reviewed severities for the new clang-tidy rules (all auto-generated ones are rated as major code smells).

**Comment by nathanaelg** [comment]
I've gone through and done an initial attempt at some severities. One thing I would note is that in the list of rules in https://github.com/SonarOpenCommunity/sonar-cxx/pull/1555 there are some which are duplicates (aliases) of the same rule. Hopefully I've categorized those the same!

Smell, info:
```abseil-no-internal-dependencies
abseil-no-namespace
android-cloexec-creat
bugprone-suspicious-enum-usage
cert-dcl59-cpp
cppcoreguidelines-avoid-magic-numbers
cppcoreguidelines-no-malloc
fuchsia-default-arguments
fuchsia-header-anon-namespaces
fuchsia-multiple-inheritance
fuchsia-overloaded-operator
fuchsia-restrict-system-includes
fuchsia-trailing-return
fuchsia-virtual-inheritance
google-objc-avoid-throwing-exception
google-objc-global-variable-declaration
google-readability-braces-around-statements
google-readability-function-size
hicpp-braces-around-statements
hicpp-deprecated-headers
hicpp-exception-baseclass
hicpp-function-size
hicpp-named-parameter
hicpp-new-delete-operators
hicpp-no-array-decay
hicpp-no-assembler
hicpp-no-malloc
hicpp-signed-bitwise
hicpp-use-auto
hicpp-use-emplace
hicpp-use-equals-default
hicpp-use-equals-delete
hicpp-use-noexcept
hicpp-use-nullptr
hicpp-use-override
modernize-replace-random-shuffle
modernize-return-braced-init-list
modernize-unary-static-assert
modernize-use-default-member-init
modernize-use-equals-default
modernize-use-equals-delete
modernize-use-noexcept
modernize-use-transparent-functors
modernize-use-uncaught-exceptions
objc-property-declaration
portability-simd-intrinsics
readability-delete-null-pointer
readability-implicit-bool-conversion
readability-magic-numbers
readability-misleading-indentation
readability-misplaced-array-index
readability-non-const-parameter
readability-redundant-declaration
readability-redundant-function-ptr-dereference
readability-redundant-member-init
readability-simplify-subscript-expr
readability-static-accessed-through-instance
readability-string-compare
```

Smell, minor:
```abseil-faster-strsplit-delimiter
abseil-redundant-strcat-calls
abseil-str-cat-append
abseil-string-find-startswith
cert-dcl03-c
cert-dcl54-cpp
cert-oop11-cpp
cppcoreguidelines-c-copy-assignment-signature
fuchsia-statically-constructed-objects
hicpp-move-const-arg
hicpp-static-assert
performance-implicit-conversion-in-loop
performance-inefficient-algorithm
performance-inefficient-string-concatenation
performance-inefficient-vector-operation
performance-move-const-arg
performance-move-constructor-init
performance-noexcept-move-constructor
performance-type-promotion-in-math-fn
```

Smell, major:
```abseil-duration-division
bugprone-fold-init-type
bugprone-misplaced-widening-cast
bugprone-parent-virtual-call
bugprone-sizeof-expression
bugprone-suspicious-missing-comma
bugprone-terminating-continue
bugprone-unused-raii
bugprone-unused-return-value
bugprone-virtual-near-miss
cert-dcl21-cpp
cert-dcl58-cpp
cert-fio38-c
cppcoreguidelines-avoid-goto
cppcoreguidelines-interfaces-global-init
cppcoreguidelines-narrowing-conversions
cppcoreguidelines-owning-memory
cppcoreguidelines-slicing
cppcoreguidelines-special-member-functions
hicpp-avoid-goto
hicpp-explicit-conversions
hicpp-member-init
hicpp-multiway-paths-covered
hicpp-noexcept-move
hicpp-special-member-functions
hicpp-vararg
mpi-buffer-deref
```

Bug, minor
```android-comparison-in-temp-failure-retry
bugprone-argument-comment
bugprone-assert-side-effect
bugprone-bool-pointer-implicit-conversion
bugprone-copy-constructor-init
bugprone-exception-escape
bugprone-forward-declaration-namespace
bugprone-forwarding-reference-overload
bugprone-inaccurate-erase
bugprone-integer-division
bugprone-macro-parentheses
bugprone-macro-repeated-side-effects
bugprone-move-forwarding-reference
bugprone-multiple-statement-macro
bugprone-sizeof-container
bugprone-string-constructor
bugprone-string-integer-assignment
bugprone-suspicious-memset-usage
bugprone-suspicious-string-compare
bugprone-swapped-arguments
bugprone-throw-keyword-missing
bugprone-undelegated-constructor
cert-err09-cpp
cert-err61-cpp
hicpp-undelegated-constructor
mpi-type-mismatch
objc-avoid-nserror-init
objc-forbidden-subclassing
```

Bug, major:
```bugprone-dangling-handle
bugprone-incorrect-roundings
bugprone-lambda-function-name
bugprone-misplaced-operator-in-strlen-in-alloc
bugprone-string-literal-with-embedded-nul
bugprone-suspicious-semicolon
bugprone-undefined-memory-manipulation
bugprone-use-after-move
hicpp-invalid-access-moved
objc-avoid-spinlock
zircon-temporary-objects
```

Vulnerability, info:
```cert-msc30-c
cert-msc32-c
cert-msc50-cpp
cert-msc51-cpp
```

Vulnerability, minor:
```android-cloexec-accept
android-cloexec-accept4
android-cloexec-dup
android-cloexec-epoll-create
android-cloexec-epoll-create1
android-cloexec-fopen
android-cloexec-inotify-init
android-cloexec-inotify-init1
android-cloexec-memfd-create
android-cloexec-open
android-cloexec-socket
```

**Comment by ivangalkin** [comment]
Hello @nathanaelg and thank you for your efforts! I've applied your suggestion as-is in #1558 
@ALL please review

**Comment by sigiesec** [comment]
Was this issue closed by #1558? When is there going to be a new release (candidate) containing the change?

**Comment by ivangalkin** [comment]
@sigiesec I'll provide the rules for clang-tidy compiler-diagnostics (the ones mentioned in #1560) as part of this issue/US too 
you can download the SNAPSHOT build right now: https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts
@guwirth could you please give some insights into the release date?

**Comment by ivangalkin** [comment]
@guwirth #1566 was meant to close this issue (I've made a typo by using of `fixes` annotation). I think we can close this user story (feature request) manually now.
