### ISSUE TITLE
US: Cppcheck 1.85 support

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1545]
Support upcoming Cppcheck 1.85 version: http://cppcheck.sourceforge.net/. 
Update rules file: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/cppcheck.xml

**Comment by ivangalkin** [comment]
I volunteer for this US: as soon as there will be a new [release](https://github.com/danmar/cppcheck/releases/), I'll submit the support for the version 1.85
