### ISSUE TITLE
Support for alternative operator representations

### ISSUE THREAD

**Issue by moriarty** [SonarOpenCommunity/sonar-cxx#1569]
### Description

I'm starting to introduce sonar into a code base, there are a lot of "skip declaration" warnings.
It seems, the keywords ```not```, ```or``` and ```and``` are responsible for most of the warnings.
https://en.cppreference.com/w/cpp/language/operator_alternative

Here is an example of the warning
```
WARN: [/somepath/somefile.cpp:66]: skip declaration: while ( not cancelled_ ) {
```
Replacing it with the standard ```!``` makes the warning go away.

### Steps to reproduce the problem

Please provide the steps required to reproduce the problem

1. have a condition with a ```not``` ```or``` or ```and```

### Expected behavior

I would expect these operator alternatives to be parsed as if they were the usual operators.

### Actual behavior

skip declaration warning

### Known workarounds

replace them with ```!```, ```||``` or ```&&```.

### LOG file

```
WARN: [/somepath/somefile.cpp:66]: skip declaration: while ( not cancelled_ ) {
```

### Related information

SONAR_VERSION=7.3
SONAR_OPEN_CXX_VERSION=1.1.0

**Comment by moriarty** [comment]
https://github.com/SonarOpenCommunity/sonar-cxx/blob/040a94a2104f7cd9ad7e0d0cb4d8935052264720/cxx-squid/src/main/java/org/sonar/cxx/api/CxxKeyword.java#L105-L116

https://github.com/SonarOpenCommunity/sonar-cxx/blob/040a94a2104f7cd9ad7e0d0cb4d8935052264720/cxx-squid/src/main/java/org/sonar/cxx/api/CppPunctuator.java#L98-L109

Looks like these are know and need to be added to a few different places in this file, for example:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/040a94a2104f7cd9ad7e0d0cb4d8935052264720/cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java#L491-L494

**Comment by guwirth** [comment]
@moriarty there was already a discussion with #778. Proposed solution there was to use `iso646.h` header file.

**Comment by moriarty** [comment]
I will continue this discussion in #1572.
