### ISSUE TITLE
unit test success density is not shown in sonarqube

### ISSUE THREAD

**Issue by quanke89** [SonarOpenCommunity/sonar-cxx#1578]
Please [turn debug info on](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information) and reproduce your issue.
The debug info in the log file could help to solve or locate the issue.

### Description

Please provide a succinct description of your issue.

### Steps to reproduce the problem

Please provide the steps required to reproduce the problem

1. Step A

2. Step B

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

Please provide a description of the actual behavior you observe.

### Known workarounds

Please provide a description of any known workarounds.

### LOG file

Any warnings/errors in the LOG file?

### Related information

* cxx plugin version?
1.1.0
* SonarQube version?
6.7.5

**Comment by ivangalkin** [comment]
hi @quanke89 and thank you for reaching out
@guwirth I believe this is a duplication for #1390
