### ISSUE TITLE
RFF: cxx plugin v1.2 & SQ7.4

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1579]
Hi all,

would like to release v1.2 as fast as SQ7.4 is available and working with it?
From my point of view only #1577 and #1544 should be closed.

Any other points/hints?

Regards,

**Comment by ivangalkin** [comment]
I agree. Thank you.

**Comment by DzmitryB** [comment]
Could you please provide some ETA if possible?

**Comment by guwirth** [comment]
@DzmitryB normally it should already work you can download snapshot always from here: https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts
Missing parts are release notes and update of wiki.
Expect to have everything in place by Sunday.

**Comment by guwirth** [comment]
Hi, first draft of release notes. Please review. Hope I forgot nothing? Other rdwiki pages are still not up to date.
---

We are pleased to announce the SonarQube C++ Community Plugin version 1.2.0.
See lists below for features added and bugs fixed in this release.

# SonarQube compability

- tested and released for **SonarQube 6.7 LTS, 7.0, 7.1, 7.2, 7.3, 7.4**<br>see also [SonarQube compatibility matrix](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix)
- [Installation Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Installation)
- [Upgrade Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-Instructions)

# Enhancements

- SQ 7.3 and SQ 7.4 support #1541 #1581
- minimal supported SQ API is 6.7 #1317 
- Complexity metrics are performed on original source code now #1547 #1552
  - In the past we were first preprocessing the code and were calculating the complexity metrics on base of the preprocessed code. This could lead to confusing metric numbers because macro code is counted multiple times and could also be from external libraries. **We are calculating the complexity metrics without preprocessing the code now. This could lead to diverging but easier understandable metric numbers.**
- GCC and MSVC compiler sensor can be used at the same time now  #1533 #1180
  - **BREAKING CHANGE :** `sonar.cxx.compiler` settings are no more supported!
     - use `sonar.cxx.vc` to read MSVC reports
     - use `sonar.cxx.gcc` to read GCC reports
     - use `sonar.cxx.msbuild` to read includes and defines from MSBuild log file
- implement explanation for cyclomatic and cognitive complexity checks #1494 #1551 #1546 #1537 #1535
- Clang-Tidy 8 support #1536 #1555 #1558 #1566 
- Cppcheck 1.85 support #1545 #1576
- make default logging less verbose (move some parts to debug info) #1563 #1565 #1567
- refactoring #1526 #1529 #1530 #1532 #1582 #1562

# Bugfixes

- Sensors have problem to import results because of symbolic links and path normalization #1574 #1575
- C++: support alternative operators #1569 #1572 #1577
- MethodName check fails on constructor of nested class #1557 #1559
- API check: Method defined in header file, but out of class, marked as undocumented / Public API: ignore methods outside of class #1543 #1544 #1580
- Complete support of alternative operators #1577
- xUnit sensor not run on maven projects #1523 #1524
- C-Plugin: sensors use wrong rules repository keys / rules repository ignored the language specific repository suffix #1521 #1522
- java.lang.StackOverflowError during parse of source file / protect ExpressionEvaluator from self-referential macros #1516 #1517
- cppcheck sensor: wrong handling of warnings with multiple locations #1511 #1512
- sonar-cxx custom metrics are not displayed/saved #1509 #1514
- Property 'sonar.cxx.coverage.reportPath' should be made using 'getStringArray' method. The SonarQube plugin using this property should be updated #1384
- cppcheck.xml fix name and description of unmatchedSuppression #1564
- Implement explanation for cognitive complexity checks #1551
- [Travis/AppVeyor] Updates SQ distribution URL #1571
- make all sensors 'reportPath' properties multi-value #1568
- cannot find include files #1230

# Known Issues

For an up to date list of known issues see the issue tracker.
- not compatible with Java 9
- Ensure that a rule is enabled if you get no results. In new SQ versions the default profile is read-only. The cxx plugin does not enable all rules per default.
- Starting with SQ 6.2 there are some new metrics and some are no more available. Please have a look to the SonarQube release notes.
- [test execution metrics](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-test-execution-metrics) are not supported
- The [Cppcheck plugin](https://github.com/SonarQubeCommunity/sonar-cppcheck) is deprecated and not working in parallel to this plugin. This plugin provides an own Cppcheck sensor.
- C plugin and JSON Compilation Database support are experimental only
- Symlinks are not supported.

# Thanks ....

go to all contributors (in alphabetical order):

@guwirth
@ivangalkin
@moriarty

... and all people which were active on the issue tracker!

**Comment by guwirth** [comment]
@ivangalkin thx, second draft:
---

We are pleased to announce the SonarQube C++ Community Plugin version 1.2.0.
See lists below for features added and bugs fixed in this release.

# SonarQube compability

- tested and released for **SonarQube 6.7 LTS, 7.0, 7.1, 7.2, 7.3, 7.4**<br>see also [SonarQube compatibility matrix](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix)
- [Installation Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Installation)
- [Upgrade Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-Instructions)

# Enhancements

- SQ 7.3 and SQ 7.4 support #1541 #1581
- minimal supported SQ API is 6.7 #1317 
- Complexity metrics are performed on original source code now #1547 #1552
  - In the past we were first preprocessing the code and were calculating the complexity metrics on base of the preprocessed code. This could lead to confusing metric numbers because macro code is counted multiple times and could also be from external libraries. **Generated code (among others macro expansions) doesn't affect the calculation of cognitive / cyclomatic complexity now. This could lead to diverging but provides easier understandable metric numbers.**
- GCC and MSVC compiler sensor can be used at the same time now  #1533 #1180
  - **BREAKING CHANGE :** `sonar.cxx.compiler` settings are no more supported!
     - use `sonar.cxx.vc` to read MSVC reports
     - use `sonar.cxx.gcc` to read GCC reports
     - use `sonar.cxx.msbuild` to read includes and defines from MSBuild log file
- implement explanation for cyclomatic and cognitive complexity checks #1494 #1551 #1546 #1537 #1535
- Clang-Tidy 8 support #1536 #1555 #1558 #1566 
- Cppcheck 1.85 support #1545 #1576
- make default logging less verbose (move some parts to debug info) #1563 #1565 #1567
- refactoring #1526 #1529 #1530 #1532 #1582 #1562

# Bugfixes

- Sensors have problem to import results because of symbolic links and path normalization #1574 #1575
- C++: support alternative operators #1569 #1572 #1577
- MethodName check fails on constructor of nested class #1557 #1559
- API check: Method defined in header file, but out of class, marked as undocumented / Public API: ignore methods outside of class #1543 #1544 #1580
- xUnit sensor not run on maven projects #1523 #1524
- C-Plugin: sensors use wrong rules repository keys / rules repository ignored the language specific repository suffix #1521 #1522
- java.lang.StackOverflowError during parse of source file / protect ExpressionEvaluator from self-referential macros #1516 #1517
- cppcheck sensor: wrong handling of warnings with multiple locations #1511 #1512
- sonar-cxx custom metrics are not displayed/saved #1509 #1514
  - enable code metrics for public API
  - support multi-module projects
  - reduce memory footprint by moving of metric aggregation to the  computation engine
- Property 'sonar.cxx.coverage.reportPath' should be made using 'getStringArray' method. The SonarQube plugin using this property should be updated #1384 #1568
- cppcheck.xml fix name and description of unmatchedSuppression #1564
- [Travis/AppVeyor] Updates SQ distribution URL #1571
- cannot find include files #1230
- Symlink support #1574 #1575

# Known Issues

For an up to date list of known issues see the issue tracker.
- not compatible with Java 9
- Ensure that a rule is enabled if you get no results. In new SQ versions the default profile is read-only. The cxx plugin does not enable all rules per default.
- Starting with SQ 6.2 there are some new metrics and some are no more available. Please have a look to the SonarQube release notes.
- [test execution metrics](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-test-execution-metrics) are not supported
- The [Cppcheck plugin](https://github.com/SonarQubeCommunity/sonar-cppcheck) is deprecated and not working in parallel to this plugin. This plugin provides an own Cppcheck sensor.
- C plugin and JSON Compilation Database support are experimental only

# Thanks ....

go to all contributors (in alphabetical order):

@guwirth
@ivangalkin
@nathanaelg
@moriarty

... and all people which were active on the issue tracker!

**Comment by ivangalkin** [comment]
@guwirth thx! I've sorted the contributors wrong in my diff, but all the rest looks good to me.

**Comment by guwirth** [comment]
Update of https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix done

**Comment by guwirth** [comment]
Update of https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-Instructions done

**Comment by guwirth** [comment]
Update of https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties done

**Comment by guwirth** [comment]
@all: Ready for final testing https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

Deadline Friday 9th November 2018

**Comment by Kochise** [comment]
Shouldn't be the informations be updated after availability of 1.2.0 ?

**Comment by guwirth** [comment]
> Is issue #1550 took into account ?

@Kochise you mean add it to know issues?

**Comment by Kochise** [comment]
Known issue ? No, I meant the issue being resolved into 1.2.0.

**Comment by guwirth** [comment]
@Kochise I'm sorry, I still don't get it: can I close #1550 ? Still don't see which PR was fixing it?

**Comment by Kochise** [comment]
Oh, sorry, misunderstood. Currently it's still present in 1.1.0 so I wait for official release of 1.2.0 to see if it is solved :3

**Comment by guwirth** [comment]
@Kochise you can download it from here:  https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts. That's planned to be 1.2.

**Comment by ivangalkin** [comment]
hi @guwirth 

> Ready for final testing

looks good to me, can recommend

**Comment by guwirth** [comment]
Hi, did some tests and for our environment v1.2 it's working fine. As expected cyclomatic complexity is lower.
- VS 2015 & VS2017
- cppcheck & other sensor
- Boost.Test
- Bullseye coverage

**Comment by guwirth** [comment]
@ivangalkin thx for testing. Which setup did you test?

**Comment by ivangalkin** [comment]
multi-module project with cppcheck, json compilation database (generated by bear), cobertura coverage (generated from gcov by gcovr) + cxx:FunctionCognitiveComplexity enabled

**Comment by guwirth** [comment]
It's released!

@ivangalkin special thanks to you for your contribution!

**Comment by ivangalkin** [comment]
@guwirth the pleasure is all mine
