### ISSUE TITLE
how independent is the imported coverage report  from the scanned code 

### ISSUE THREAD

**Issue by eramm** [SonarOpenCommunity/sonar-cxx#1583]
have a requirement to provide coverage reports via SonarQube 6.7.5.38563 for a project that has mostly C code but some C++ code as well Since the tests run in a distributed environment and there is no way to merge the .gcov files afterwards and use the CFammily plugin thus I am taking a lcov .info file and converting it to cobertura XML (there is a python module that does this) and importing it using the CXX plugin

My question is how independent is the coverage report from the code is that is actually scanned since most of the C code is skipped by the CXX plugin ?

**Comment by guwirth** [comment]
Hi @eramm,

that is an interesting question. I never tried it.

SQ is working like this:
1. If you are starting a new analysis the sensors are first collecting all **source code files** (this is called indexing). For each language you have to define file extensions which are associated with this language (e.g. `sonar.cxx.suffixes.sources`). As far as I know it's not allowed that two languages are indexing the same file. You also have to keep in mind that the commercial and community plugin are using different language keys for C and C++. (To also answer this: Why not using the same language key? SQ does not allow to run two plugins with same language key.)
2. Second step is then to read report files with sensors. In your case the coverage report files. The coverage sensors iterates then over all found files in the report and try to match it with an indexed source file from step 1. If a files is found the coverage metrics are assigned to the source file. Here are sometimes problems with the file items in the reports, read: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues.

So in general it should work. Problems could be
* configuration of file extensions
* order how the sensors in different plugins are executed
* path items in report files

To understand a little bit more what's going on I recommend you to turn debug info on: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

Regards,
