### ISSUE TITLE
sonar CXX plugin lost cyclomatic complexity when update to sonar 7.3

### ISSUE THREAD

**Issue by liucc52** [SonarOpenCommunity/sonar-cxx#1586]
Please [turn debug info on](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information) and reproduce your issue.
sonar CXX plugin lost cyclomatic complexity when update to sonar 7.3

### Description

sonar CXX plugin lost cyclomatic complexity when update to sonar 7.3

### Steps to reproduce the problem
when we use sonar CXX plugin 1.1.0 and sonar 6.3, we can get cyclomatic complexity metrics to find complexity files, but we when update sonar to sonar 7.3, we can't get metrics for  cyclomatic complexity

**Comment by guwirth** [comment]
Hi @liucc52, cxx plugin 1.1 is not released for SQ 7.2, see https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix. Please try with cxx 1.2 snapshot we are releasing soon: https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts.

**Comment by guwirth** [comment]
@liucc52 Did a test with cxx 1.2 and SQ 7.3: working in my projects. Please try again and reopen if still a problem.
