### ISSUE TITLE
WARN: Metric 'test_success_density' is an internal metric computed by SonarQube

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1622]
Get warning in V1.2.0 LOG file:
```
WARN: Metric 'test_success_density' is an internal metric computed by SonarQube. Provided value is ignored.
```
Remove metric from plug-in.

**Comment by ivangalkin** [comment]
@guwirth yes, some of standard metrics are calculated automatically by computation engine (CE). The implementation is normally done in the generic way, so both single-module and multi-module projects are supported.

For the `TEST_SUCCESS_DENSITY_KEY` the flowing computation step is responsible: [UnitTestMeasuresStep](https://github.com/SonarSource/sonarqube/blob/master/server/sonar-ce-task-projectanalysis/src/main/java/org/sonar/ce/task/projectanalysis/step/UnitTestMeasuresStep.java)

**Comment by guwirth** [comment]
Remove:
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/8b0a1b6f5a182c3c36e71db491c2076b6fb444c4/cxx-sensors/src/main/java/org/sonar/cxx/sensors/tests/xunit/CxxXunitSensor.java#L150
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/8b0a1b6f5a182c3c36e71db491c2076b6fb444c4/cxx-sensors/src/main/java/org/sonar/cxx/sensors/tests/xunit/CxxXunitSensor.java#L197
