### ISSUE TITLE
cppcheck missing "nullPointerArithmeticRedundantCheck" rule

### ISSUE THREAD

**Issue by VirtualTim** [SonarOpenCommunity/sonar-cxx#1636]
### Description
Sonarqube cppcheck is missing the "nullPointerArithmeticRedundantCheck" rule. I believe it should be under https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/cppcheck.xml

The following is logged (filenames removed):

```
ERROR: Could not add the issue 'CxxReportIssue [ruleRepoKey=cppcheck, ruleId=nullPointerArithmeticRedundantCheck, locations=CxxReportLocation [file=C:████/████.cpp, line=448, info=Either the condition '!████' is redundant or there is pointer arithmetic with NULL pointer.], CxxReportLocation [file=C:████/████.cpp, line=448, info=Null pointer addition], CxxReportLocation [file=C:████/████.cpp, line=450, info=Assuming that condition '!████' is not redundant]]':The rule 'cppcheck:nullPointerArithmeticRedundantCheck' does not exist.
', skipping issue
```

If it helps here is an exert from the cppcheck xml report:
```
<results version="2">
<cppcheck version="1.84"/>
  <errors>
    <error id="nullPointerArithmeticRedundantCheck" severity="warning" msg="Either the condition '!████' is redundant or there is pointer arithmetic with NULL pointer." verbose="Either the condition '!████' is redundant or there is pointer arithmetic with NULL pointer." cwe="682">
      <location file0="C:████/████.cpp" file="C:████/████.cpp" line="448" info="Null pointer addition"/>
      <location file0="C:████/████.cpp" file="C:████/████.cpp" line="450" info="Assuming that condition '!████' is not redundant"/>
    </error>
  </errors>
</results>
```

**Comment by guwirth** [comment]
Hi @VirtualTim, thx for your feedback.

**Comment by ivangalkin** [comment]
Hi @VirtualTim & @guwirth,

cppcheck has a CLI switch, which allows to list all accessible rules. Unfortunately from time to time they miss one or another ID there. In our rules repository we use only officially published rules, which I believe makes sense.

I've (kind of) reported the missing rule by cppcheck. Please see the thread https://github.com/danmar/cppcheck/pull/1292.

Regards,

**Comment by ivangalkin** [comment]
Btw. I changed the subject, because it's not only the version 1.84 of cppcheck.
cppcheck 1.86 still doesn't publish this mentioned rule (see https://github.com/danmar/cppcheck/blob/0f4eac657d411c28ac2f93a26563f39841eb765f/lib/checknullpointer.cpp#L588 for more details)
