### ISSUE TITLE
V1.2.1 draft

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1639]
Hi, draft for 1.2.1 release below. Any feedback?

---

We are pleased to announce the SonarQube C++ Community Plugin version 1.2.1.
See lists below for features added and bugs fixed in this release.

# SonarQube compability

- tested and released for **SonarQube 6.7 LTS, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5**<br>see also [SonarQube compatibility matrix](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix)
- [Installation Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Installation)
- [Upgrade Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-Instructions)

# Enhancements

- SQ 7.5 support #1635
- minimal supported SQ API is 6.7 #1317 
- use SSLR 1.23 #1630
- use POM 48 #1590 
- Cppcheck 1.86 support #1616 #1620
- Mark static code analysis checks deprecated #1613
- optimize logging #1619 #1621 #1622 #1623 #1624 #1626 #1627 #1628
- clean-up POMs #1591 #1593 #1631 #1632 #1633 #1634
- refactoring #1584 #1594 #1592 #1600 #1602 #1603 #1605 #1606 #1607 #1608 #1610 #1611 #1614 #1617 #1618 #1629

# Bugfixes

- xUnit sensor couldn't parse test report with 0 testsuite tag #1595 #1599

# Known Issues

For an up to date list of known issues see the issue tracker.
- not compatible with Java 9
- Ensure that a rule is enabled if you get no results. In new SQ versions the default profile is read-only. The cxx plugin does not enable all rules per default.
- Starting with SQ 6.2 there are some new metrics and some are no more available. Please have a look to the SonarQube release notes.
- `duplicated_lines_density` values are different with SQ 7.5
- [test execution metrics](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-test-execution-metrics) are not supported
- The [Cppcheck plugin](https://github.com/SonarQubeCommunity/sonar-cppcheck) is deprecated and not working in parallel to this plugin. This plugin provides an own Cppcheck sensor.
- C plugin and JSON Compilation Database support are experimental only

# Thanks ....

go to all contributors (in alphabetical order):

@guwirth
@ivangalkin

... and all people which were active on the issue tracker!

**Comment by ivangalkin** [comment]
@guwirth 

> Ensure that a rule is enabled if you get no results. In new SQ versions the default profile is read-only. The cxx plugin does not enable all rules per default.

You could reference the corresponding wiki page somewhere in this sentence: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Activate-quality-rules

The release note looks good to me :+1:

**Comment by ivangalkin** [comment]
@guwirth please consider adding #1641 to 1.2.1. It's also about the logging optimization.
