### ISSUE TITLE
Upgrade to 1.2.2 breaks complexity and size metrics history

### ISSUE THREAD

**Issue by ericlemes** [SonarOpenCommunity/sonar-cxx#1656]
### Description

After upgrading from 1.1.0 to 1.2.2, the Complex Functions (%), Big Functions (%) and similar metrics looses history.

This happens because the metric_key has been changed without upgrade path specified.

### Steps to reproduce the problem

Run a C++ analysis with 1.1.0. Observe the Complex Functions (%) metric. Upgrade to 1.2.2 and re-run the analysis. The previous analysis isn't displayed in SonarQube. (when clicking in the trend icon).

### Expected behavior

Keep history

### Actual behavior

Breaks history

### Known workarounds

I didn't test this, but potentially renaming the metric, updating the database, before upgrade may solve the problem.

### LOG file

N/A

### Related information

* cxx plugin version: 1.2.2
* SonarQube version: 6.7.5

**Comment by ivangalkin** [comment]
@ericlemes the change https://github.com/SonarOpenCommunity/sonar-cxx/commit/6e08f1c4fa1c2f669dd83140fae5f65ad0db7e07 was introduced in 1.2.0. It rewrites and refactors the metrics. Among others it introduces the uniform generation, naming and post-procession of metrics (aggregation and percentage calculation are done in computation engine).

You might be interested in the discussion: #1514.

Apropos naming. There were the following changes:

```
perc_complex_functions -> CXX-PERC_COMPLEX_FUNCTIONS
loc_in_complex_functions -> LOC_IN_COMPLEX_FUNCTIONS
perc_loc_in_complex_functions -> CXX-PERC_LOC_IN_COMPLEX_FUNCTIONS
big_functions -> CXX-BIG_FUNCTIONS
loc_in_big_functions -> CXX-LOC_IN_BIG_FUNCTIONS
perc_big_functions -> CXX-PERC_BIG_FUNCTIONS
perc_loc_in_big_functions -> CXX-PERC_LOC_IN_BIG_FUNCTIONS
loc_in_functions -> CXX-LOC_IN_FUNCTIONS
```
This change was already released in 1.2.0 and 1.2.1. So changing them will potential break someones workflow, too. I don't like the idea of duplication. I would suggest to let the new naming and post some kind of update note.

**Comment by ericlemes** [comment]
@ivangalkin, I don't disagree we the change. It is very good. In fact, I should use the proper naming convention in first place, but I didn't and my history is different.

I'm not sure if there's something in place regarding database changes in the upgrade process. This would be my first choice, doing the updates before the first run. If this isn't possible, at least adding some breaking changes in the release notes would be a good idea.

I'll test now what happens if I rename the metric.

**Comment by ericlemes** [comment]
So, I can confirm that running:

update dbo.metrics set name = upper('CXX-' + name) where name in 
('complex_functions', 
'perc_complex_functions', 
'big_functions', 
'perc_big_functions', 
'loc_in_complex_functions', 
'perc_loc_in_complex_functions', 
'loc_in_big_functions', 
'perc_loc_in_big_functions', 
'loc_in_functions')

In the database before upgrading to 1.2.x fixes the issue. @guwirth can we document this on the release notes?

Cheers!

**Comment by guwirth** [comment]
done, see https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-Instructions

**Comment by ericlemes** [comment]
Thanks!
