### ISSUE TITLE
Parser error when including a path set by a #define

### ISSUE THREAD

**Issue by BeWaterMyFriendd** [SonarOpenCommunity/sonar-cxx#1658]
Hello people,

Im currently working on a C++ project that needs to be analysed with SonarQube 5.6.7 and the sonar-cxx plugin version 0.9.8 . The project is quite large and includes multiple libraries, e.g Boost.

In my sonar-project.properties file Ive used the sonar.cxx.includeDirectories property to set the include files.Also I used the sonar.cxx.defines property to set the macros of my build environment.

At some point during the analysis, the plugin will go into the Boost library folder, because it is set in the sonar.cxx.includeDirectories property and analyse the content.

The problem occurs with this piece of code:

```
#if !defined(BOOST_USER_CONFIG) && !defined(BOOST_NO_USER_CONFIG) 
#    define BOOST_USER_CONFIG <boost/config/select_stdlib_config.hpp>
#endif

#ifdef BOOST_USER_CONFIG
#    include BOOST_USER_CONFIG
#endif
```

The plugin isnt able to resolve BOOST_USER_CONFIG with the path that it is assigned to it,
so I get the following error:

`WARN: [C:\Users\hge\Documents\Literatur_und_Notizen\VW_QM\sonar_vw\src\Tools\Externals\boost\boost\config.hpp:26]: cannot find the sources for '#  include BOOST_USER_CONFIG'`

Because of the fact that boost is used by many files in the project. I get the repeated error a lot of times.
I tried to add this macro to the sonar.cxx.defines and also tried adding more include directories to the sonar.cxx.includeDirectories property but nothing worked.

Ive noticed that similar issues have been discussed here in the past but I couldnt get a proper solution from them.
I would really appreciate your help in fixing this issue with me.

**Comment by guwirth** [comment]
@BeWaterMyFriendd did you also try it with latest 1.2.1? We don't fix issues in old versions.

**Comment by BeWaterMyFriendd** [comment]
The issue can be closed now.
I was able to fix the error by adjusting the sonar.cxx.defines property.
