### ISSUE TITLE
Scans fail with java.nio.charset.MalformedInputException in ReservedNamesCheck.visitFile

### ISSUE THREAD

**Issue by gjd6640** [SonarOpenCommunity/sonar-cxx#1671]
### Description

Scan fails with error:  ERROR: Error during SonarQube Scanner execution
org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: /my/company/somefile.H

This error comes from here: org.sonar.cxx.checks.**ReservedNamesCheck**.visitFile(ReservedNamesCheck.java:64)

See the attached text file for the stack trace that printed when I used the "-X" option.

Character set the scanner expects is UTF-8. It appears that my file actually conforms to the "CP 1252" character set and the scan chokes on the "left quote" (0x223) and "right quote" (0x224) characters.

### Steps to reproduce the problem

Please provide the steps required to reproduce the problem

1. Create a text file that contains the 0x223 and 0x224 characters
2. Scan that text file with the sonarqube scanner and using the default UTF-8 encoding
3. Observe that the scan exits with the error message given at the top of this issue.

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

This rule should just skip past any non-translatable characters instead of exiting. There's another rule to raise an issue when bytes that don't map to characters.

### Actual behavior

Scan stops / fails.

### Known workarounds

I specified the correct character set by setting the options `-Dsonar.sourceEncoding=CP1252 -Dsonar.cxx.gcc.charset=CP1252`. I'm still seeing the warning text below BUT the error message has gone away and the scan does complete. Probably that WARN output is written by some other check class.

> "WARN: Invalid character encountered in file /myprojectpath/MySourceFile.C at line 7 for encoding UTF-8. Please fix file content or configure the encoding to be used using property 'sonar.sourceEncoding'."

### Related information

This looks similar to issue #371 but isn't the exact same issue.

* sonar-cxx-plugin-1.2.2-SNAPSHOT (source cloned from master around 4:30pm on 1/22/2019)
* SonarQube version:  Version 6.7.3 (build 38370)

**Comment by gjd6640** [comment]
[sonar_scan_console_output.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/2784966/sonar_scan_console_output.txt)

**Comment by gjd6640** [comment]
Note that this behavior appears to have been introduced since the latest release. Version 1.2.1 doesn't break in this manner. Looks like what triggered this change is that we switched from "com.google.common.io.Files" to Java's NIO which behaves differently in this regard.

**Comment by guwirth** [comment]
Hi @gjd6640, thanks for the feedback. Must be fixed.

**Comment by guwirth** [comment]
`
new BufferedReader(new InputStreamReader(new FileInputStream("a.txt"),"utf-8"));
`
seems to use:
`
cs.newDecoder().onMalformedInput(CodingErrorAction.REPLACE).onUnmappableCharacter(CodingErrorAction.REPLACE)
`
https://stackoverflow.com/questions/26268132/all-inclusive-charset-to-avoid-java-nio-charset-malformedinputexception-input

**Comment by guwirth** [comment]
Please try again with latest snapshot.
