### ISSUE TITLE
The plugin does not support SonarLint

### ISSUE THREAD

**Issue by zhankangbao** [SonarOpenCommunity/sonar-cxx#1680]
Run SonarLint Analyze in Eclipse CDT,SonarLint Console ouput log like below:
Available languages:
  * Python => "py"
  * Java => "java"
  * Kotlin => "kotlin"
  * PHP => "php"
  * TypeScript => "ts"
  * JavaScript => "js"
  * Ruby => "ruby"
### Description
The plugin does not allow SonarLint to support language C 

### Steps to reproduce the problem

Run SonarLint Analyze in Eclipse CDT,get log from SonarLint Console

### Expected behavior

The plugin can support language C

### Related information

* cxx plugin version 1.1.0 and 1.2.2
* SonarQube version 7.4

**Comment by guwirth** [comment]
Hi @zhankangbao,

I think SonarLint support is for several reasons not possible:
* SonarLint  is from SonarSource and they support their own plugins only.
* For C/C++ there are two plugins (commercial and community). To work on the same server they need an unique language key: commercial =cpp/community=cxx. The community language keys are not supported.
* Last and most important point: The idea of the community plugin is to do **no** own analysis. The plugin use other tools and forward only the resulting reports to SonarQube. This means there is no need to support SonarLint.
* There is an own linter https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-cxx-plugin-before-committing-code you can try, but I never tried it.

Regards,
