### ISSUE TITLE
Draft for 1.2.2 release

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1683]
Please review:

We are pleased to announce the SonarQube C++ Community Plugin version 1.2.2.
See lists below for features added and bugs fixed in this release.

# SonarQube compability

- tested and released for **SonarQube 6.7 LTS, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5, 7.6**<br>see also [SonarQube compatibility matrix](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix)
- [Installation Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Installation)
- [Upgrade Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-Instructions)

# Enhancements

- SQ 7.6 support #1674
- minimal supported SQ API is 6.7 #1317 
- lowercase filenames in sensors are supported #1651, #1653, #1678, #1682, #1679, #1682
- {Aggregate|Density} MeasureComputer: reduce and soften the logging #1640 #1641
- improved preprocessor: performance, include and macro handling #1637, #1645, #1650, #1660, #1665
- optimized lexer and AST: remove some nodes from AST. Please check in user defined checks and XPath if they are still working #1664, #1646 #1667
- use of scanner 3.3.0.1492 #1676
- use of Maven 3.5.4 #1649
- Google Guava dependencies removed #1647
- refactoring #1644 #1659 #1677

# Bugfixes

# Known Issues

For an up to date list of known issues see the issue tracker.
- not compatible with Java 9
- [Ensure that a rule is enabled](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Activate-quality-rules) if you get no results. In new SQ versions the default profile is read-only. The cxx plugin does not enable all rules per default.
- Starting with SQ 6.2 there are some new metrics and some are no more available. Please have a look to the SonarQube release notes.
- `duplicated_lines_density` values are different with SQ 7.5
- [test execution metrics](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-test-execution-metrics) are not supported
- The [Cppcheck plugin](https://github.com/SonarQubeCommunity/sonar-cppcheck) is deprecated and not working in parallel to this plugin. This plugin provides an own Cppcheck sensor.
- C plugin and JSON Compilation Database support are experimental only

# Thanks ....

go to all contributors (in alphabetical order):

@guwirth
@ivangalkin

... and all people which were active on the issue tracker!

**Comment by ivangalkin** [comment]
:+1: thank you!

**Comment by guwirth** [comment]
I will release 1.2.2 today. 

Seems that next SQ 7.7 version will also be next LTS? For our next version I see the main focus in removing deprecated API and updating the wiki.

Some other points I have in mind:
- Do we need the c plug-in? Or can we remove it?
- Someone using our lint tool (part of cxx plug-in)? Or can we remove it?
- Who is using XPath?
- Who is using custom checks?
- I would like to remove checks marked deprecated

Any other ideas/comments?
I would tend to set the version number to 1.3?

**Comment by ivangalkin** [comment]
Hi @guwirth,

does it make sense to provide support for cppcheck 1.87 as part of 1.2.2? It was released today and I plan to integrate it during this weekend.

Regards,

**Comment by guwirth** [comment]
Hi @ivangalkin,

Yes makes sense. I will wait for it. One other comment to Cppcheck. There are some Vulnerability. Think following the SQ definition a tool like Cppcheck don’t create Vulnerability? Maybe you can set it to Bug or Code Smell?

Regards
