### ISSUE TITLE
External tool or SSLR based custom rule?

### ISSUE THREAD

**Issue by muzehyun** [SonarOpenCommunity/sonar-cxx#1684]
I built a script which use libclang to do some checks with AST.
And it works perfectly and I can also use other tools with it. (cppcheck)
I'm satisfied but someone says "sonar-cxx provides this facility(sslr) for custom rules. It's better to use it"

I read some issues here and all indicating that the external tool is the better choice than internal.

Are there any pros for SSLR based solution?
- It's sonar-cxx specific - not portable
- clang is better and more up-to-date

**Comment by guwirth** [comment]
Hi @muzehyun,

I would always recommend you to contribute to bigger open source projects like Cppcheck or Clang. We have this build-in SSLR but on the long run it seems to be a dead end. Our main focus is also to read reports from other tools. Build-in static code analysis will be removed. 

Regards,
