### ISSUE TITLE
Clang-tidy integration issue

### ISSUE THREAD

**Issue by mfenjiro** [SonarOpenCommunity/sonar-cxx#1692]
Hi there,
I hope you are feeling great. I try to integrate clang-tidy/Jenkins to our project. There seems to be a problem with how clang-tidy is integrated with sonar-cxx. I have read everything linked to Path issues and it doesn't seem to come from that. 
I run the commands on my machine (lots of WARN: cannot find file but still some results) and on Jenkins (more WARN: cannot find file but 150 less results).

The program says that it doesn't find a file when it is indeed located inside the folder and BaseDir.

### Steps to reproduce the problem

1. run-clang-tidy.py -p . 1>clang-tidy-report.txt

2. sonar-scanner -X -Dsonar.verbose=true &> sonar-scanner.log

You can find attached a zip file with the logs and sonar-project.properties.

### Expected behavior
Sonar-cxx to find all the files and report to the server the almost 200 code smells. 

### Related information

* latest cxx plugin version
* SonarQube version= 6.7.6

[ISSUE_CLANG_TIDY_CXX.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/2938500/ISSUE_CLANG_TIDY_CXX.zip)

**Comment by guwirth** [comment]
Hi @mfenjiro,

looking into the LOG file I found:

```
C++ (Community) 1.2.2.1653 (cxx)
...
16:44:24.828 INFO: Sensor C++ (Community) ClangTidySensor [cxx]
16:44:24.828 INFO: Searching reports by relative path with basedir '/home/mfenjiro/ring/ring-project/daemon' and search prop 'sonar.cxx.clangtidy.reportPath'
16:44:24.830 DEBUG: Normalized report includes to '[/home/mfenjiro/ring/ring-project/daemon/clang-tidy-report.txt]'
16:44:24.830 DEBUG: Scanner uses normalized report path(s): '/home/mfenjiro/ring/ring-project/daemon/clang-tidy-report.txt'
16:44:24.842 INFO: Parser will parse '1' report file(s)
16:44:24.843 INFO: Processing report '/home/mfenjiro/ring/ring-project/daemon/clang-tidy-report.txt'
16:44:24.843 DEBUG: Parsing 'clang-tidy' report, CharSet= 'UTF-8'
...
16:44:24.859 DEBUG: Unable to get the real path: module 'jami:daemon', baseDir '/home/mfenjiro/ring/ring-project/daemon', path './audio/audiobuffer.h', exception '/home/mfenjiro/ring/ring-project/daemon/audio/audiobuffer.h'
16:44:24.859 WARN: Cannot find the file './audio/audiobuffer.h' in module 'jami:daemon' base dir '/home/mfenjiro/ring/ring-project/daemon', skipping violations.
...
16:44:24.892 ERROR: Could not add the issue 'CxxReportIssue [ruleId=clang-analyzer-optin.cplusplus.VirtualCall, locations=CxxReportLocation [file=/home/mfenjiro/ring/ring-project/daemon/src/media/video/video_rtp_session.cpp, line=69, info=Call to virtual function during destruction]]':The rule 'ClangTidy:clang-analyzer-optin.cplusplus.VirtualCall' does not exist.
', skipping issue
...
16:44:24.913 DEBUG: CXX-CLANG-TIDY processed = 185
16:44:24.913 INFO: CXX-CLANG-TIDY processed = 185
16:44:24.916 INFO: Sensor C++ (Community) ClangTidySensor [cxx] (done) | time=87ms
...
```
* parser found 185 issues, if you can't see them in SQ you should check if the rules are enabled in your quality profile
* There are some `ERROR: Could not add the issue` which means rule is not supported in current version of plugin. Other reason for less issues.
* The `WARN: Cannot find the file` seems to be all header files. You have to set `sonar.cxx.includeDirectories` property to find them all. Typically you can take them from your make file
One sample, file is:
  16:44:11.533 DEBUG: 'src/media/audio/audiobuffer.h' indexed with language 'c++'
  16:44:15.228 DEBUG: [/home/mfenjiro/ring/ring-project/daemon/src/sip/sip_utils.h:26]: cannot find include file '#include "media/audio/audiobuffer.h"'
   searching in /home/mfenjiro/ring/ring-project/daemon/audio/audiobuffer.h
   baseDir '/home/mfenjiro/ring/ring-project/daemon'

Regards,

**Comment by mfenjiro** [comment]
Hi there @guwirth,

Thank you for your quick response, I really appreciate your work withe the Open Source Community. I have found out that the version that we run on the build machines are too old and uses LLVM 3.8. We are upgrading it and hopefully, it will activate more checks. The rules are enabled and everything runs well, if you see the attached sonar-project properties file, you 'll find our config we the appropriate Include Directories set. Unfortunatly, even on my personal machine, it still have some problems finding Headers and files with Bear Compile Commands generated.

Have a great week !

**Comment by guwirth** [comment]
Hi @mfenjiro,

for the sample:
```
16:44:11.533 DEBUG: 'src/media/audio/audiobuffer.h' indexed with language 'c++'
16:44:15.228 DEBUG: [/home/mfenjiro/ring/ring-project/daemon/src/sip/sip_utils.h:26]: cannot find include file '#include "media/audio/audiobuffer.h"'
searching in /home/mfenjiro/ring/ring-project/daemon/audio/audiobuffer.h
baseDir '/home/mfenjiro/ring/ring-project/daemon'
```
Could you please provide the absolute path for `audiobuffer.h`?

Regards,

**Comment by mfenjiro** [comment]
It is: /home/mfenjiro/ring/ring-project/daemon/src/media/audio/audiobuffer.h

**Comment by guwirth** [comment]
absolute path: `/home/mfenjiro/ring/ring-project/daemon`/src/media/audio/audiobuffer.h
baseDir `/home/mfenjiro/ring/ring-project/daemon`
relative: src/media/audio/audiobuffer.h
#include "media/audio/audiobuffer.h"
searching in `/home/mfenjiro/ring/ring-project/daemon`/audio/audiobuffer.h
```
/home/mfenjiro/ring/ring-project/daemon/src/media/audio/audiobuffer.h
/home/mfenjiro/ring/ring-project/daemon          /audio/audiobuffer.h
```
think you should add:
sonar.cxx.includeDirectories=contrib/x86_64-linux-gnu/include/`;src` or `src/media`

**Comment by mfenjiro** [comment]
Attached here are the compile commands generated by Bear, everything looks fine on that end

[compile_commands.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/2954255/compile_commands.zip)

**Comment by mfenjiro** [comment]
Hi there,

Attached here are the log after adding src/media to the included directories in sonar properties.
Thanks!

![Capture du 2019-03-12 12-31-33](https://user-images.githubusercontent.com/48298990/54217875-d0446c00-44c2-11e9-9892-ed43558b8138.png)

**Comment by rudolfgrauberger** [comment]
@mfenjiro Can you please provide the latest version of a full log (as text file) and your .properties file?

**Comment by mfenjiro** [comment]
H there @rudolfgrauberger,

of course, there you go. You will find the .properties file in the zip. Thank you for your help
[full_log.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/2967010/full_log.txt)

[sonar-project.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/2967012/sonar-project.zip)

**Comment by rudolfgrauberger** [comment]
Hi @mfenjiro,

I looked at the source of the CxxClangTidySensor class and noticed that this sensor reads the path to the file from the report and passes it unchanged and not validated to CxxReportIssue. 

In the CxxIssuesReportSensor there are checks for the validation of the paths. At this point, however, this class knows nothing about include directories. Therefore this class cannot find the files, because the path is not relative to the base path or absolute.

I guess if the paths in the report are absolute or relative to the baseDir (/home/mfenjiro/ring/ring-project/daemon) then it should work.

Could you please try what happens if:
1. if the paths in the report file are absolute
2. if the paths in the report file are relative to baseDir

@guwirth Wouldn't it be better to normalize the paths after reading them and then continue working with them? At the moment not only the log/report readers have to be able to handle the different paths, but also the internal logics. That doesn't seem right to me...

**Comment by mfenjiro** [comment]
Hey there @rudolfgrauberger and @guwirth ,

Thank you for your response. I took some time back to respond, I am sorry about that. We tested putting the absolute and relative path, the issue was the same. The job is running via a build machine but the behaviour was the same inside our dev's computers. It is at a point that the clang-tidy plugin is almost unusable. A lot of issues end up not showing up in gerrit (because files are not found) and bad methods keep getting inside our code. You could check our logs and configuration on : https://jenkins.ring.cx/job/daemon-sonar/

I hope this issue will be resolved as we are trying hard to implement sonar-cxx to all of our projects. Thank you so much for your help and I hope to hear from you guys soon hopefully. 

Have a great day !

**Comment by mfenjiro** [comment]
should I close this issue ?

**Comment by guwirth** [comment]
> should I close this issue ?

@mfenjiro if it is solved yes?

**Comment by mfenjiro** [comment]
Hey there @guwirth,

The issue is still not solved. I was thinking about closing it as I didn't receive a clear answer since the opening on this issue (1 month). What do you think ?

**Comment by guwirth** [comment]
@mfenjiro keep it open, we have to look at it.

**Comment by guwirth** [comment]
Hi @mfenjiro do you have some time to look to it?

**Comment by guwirth** [comment]
Paths in reports have to be absolute or relative to root folder, see:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues
