### ISSUE TITLE
Improve regular expression for the Visual Studio/MSBuild compiler log file

### ISSUE THREAD

**Issue by rudolfgrauberger** [SonarOpenCommunity/sonar-cxx#1694]
### Description
Corrects and improves the regular expression for the Visual Studio/MSBuild compiler log file.

Fixed issues: #1264, #1678

### Steps to reproduce the problem

None of the regular expressions in the [Microsoft Visual Studio Compiler](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers#microsofts-visual-studio-compiler) section work in any of the examples in the section.

The result of the following regular expression is empty (see [result](https://regex101.com/r/j8sbhg/1))
`(.*>)?(?<file>.*)\((?<line>\d+)\)\x20:\x20warning\x20(?<id>C\d+):(?<message>.*)`

#### First issue
The issue with this regular expression is the \x20 after the <line> group.

Fixed regular expression (see [result](https://regex101.com/r/z1cOHA/2)):
`(.*>)?(?<file>.*)\((?<line>\d+)\):\x20warning\x20(?<id>C\d+):(?<message>.*)`

#### Second issue
Now we can see the second issue, the <file> group can start with a whitespace (see #1678).

Fixed regular expression (see [result](https://regex101.com/r/RA0p2D/2)):
`(.*>)?\x20*(?<file>.*)\((?<line>\d+)\):\x20warning\x20(?<id>C\d+):(?<message>.*)`

#### First optimization
Message can start with a whitespace

Fixed regular expression (see [result](https://regex101.com/r/mOyPa8/2)):
`(.*>)?\x20*(?<file>.*)\((?<line>\d+)\):\x20warning\x20(?<id>C\d+):\x20*(?<message>.*)`

#### Second optimization
Robust handling of whitespaces

Fixed regular expression (see [result](https://regex101.com/r/vq06OK/2)):
`(.*>)?\x20*(?<file>.*)\((?<line>\d+)\):\x20*warning\x20*(?<id>C\d+):\x20*(?<message>.*)`

### Known workarounds

This is my "fork" of the wiki: https://github.com/rudolfgrauberger/sonar-cxx-wiki

***Hint:*** I decided against the \s because the log file is read line by line. This expression is applied to each line individually.

@guwirth @ivangalkin Please review and merge my changes from my fork. Or should I just make these changes directly in the wiki?

**Comment by Bertk** [comment]
Hi, sorry for the late reply but some of the statements are not correct and unfortunately some information was removed from the vc compiler sensor sources or wiki.
The VC compiler sensor uses regular expression to gather the compiler warnings and the format of the warning messages can be configured for different VS versions e.g. VS2010 (HTML file UTF-16, VS2012 has with additional whitespace, VS2013, VS2015, VS2017.
A single regular expression for all VS version might have an performance impact and the configuration option was the preferred solution.
see PRs for some historical information
https://github.com/SonarOpenCommunity/sonar-cxx/pull/414
https://github.com/SonarOpenCommunity/sonar-cxx/pull/1356
Best regards
Bert

**Comment by rudolfgrauberger** [comment]
Hi @Bertk,

thank you for your feedback. I will read the information in the links. After that I will check the different formats of the log files and if necessary adjust the post.

Since the regular expression are executed on each line separately, I can not imagine that the performance impact is noticeable. I will also check that.

**Comment by guwirth** [comment]
@rudolfgrauberger think also specific regular expressions for different VS versions is the better (more performant) choice?
