### ISSUE TITLE
SQ analysis task fails (SQ7.7, Azure DevOps Server Express) 

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx#1698]
SonarQube analysis of sample project fails with `java.lang.IllegalStateException`.
- Sonarqube V7.7
- Azure DevOps Server Express
- Visual Studio 2017 Enterprise
- C++ Community plugin 1.2.1-SNAPSHOT

### Description
Analysis fails with:
`Recovery is disabled, failing analysis : 'java.lang.IllegalStateException: Line 15732480 is out of range in the file Tests/MotorControllerTests/unittest1.cpp (lines: 82)'`

### Steps to reproduce the problem

Start build pipeline (was working with older C++ plugin version).

### Expected behavior

Correct line numbers are used.

### Actual behavior

see attached log files and coverage trx file.

### Known workarounds

none.

### LOG file

Any warnings/errors in the LOG file?

### Related information

![SonarQube-analysis-error](https://user-images.githubusercontent.com/2315215/55173059-52978600-517b-11e9-8ec0-14a95eb1d63a.png)
[8.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/3018976/8.zip)
[TFS-Build_TEAM-BUILD_2019-03-28_11_35_03.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/3019014/TFS-Build_TEAM-BUILD_2019-03-28_11_35_03.zip)

**Comment by guwirth** [comment]
Hello @Bertk,

have you also tried with last snapshot 1.3? We don't fix issues in old versions.
```
Recovery is disabled, failing analysis : 'java.lang.IllegalStateException: Line 15732480 is out of range in the file Tests/MotorControllerTests/unittest1.cpp (lines: 82)'
```
Means file unittest1.cpp has 82 lines and report tries to access line 15732480.

Regards,

**Comment by Bertk** [comment]
Hallo @guwirth,

I repeated the check using the latest jar `sonar-cxx-plugin-1.3.0.1678.jar` but the error still occur.

Best regards
Bert
![SonarQube-analysis-error2](https://user-images.githubusercontent.com/2315215/55223299-29740580-520e-11e9-8da2-043f0f4597b1.png)

**Comment by guwirth** [comment]
Hello @Bertk,

the exception is thrown here:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CxxCoverageSensor.java#L208

Depending on [validateRecovery](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxUtils.java#L84) the behaviour is different.

Did you `set sonar.cxx.errorRecoveryEnabled` to True?
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties#sonarcxxerrorrecoveryenabled

Regards,

**Comment by Bertk** [comment]
Hallo @guwirth,

after enabling the recovery setting the analysis continued.

Nevertheless this was working before with disabled recovery and the source line number 15732480 is weird. This smells like a regression ...
`ERROR: Cannot save Conditions Hits for Line '15732480' , ignoring measure.`

Regards
Bert
<img width="1115" alt="SonarQube-analysis-error3" src="https://user-images.githubusercontent.com/2315215/55322666-3c404180-547d-11e9-877a-6af6d0e2c8a7.png">

**Comment by guwirth** [comment]
Hi @Bertk,

>> he source line number 15732480 is weird. 

Agree, but I think this number is in your report file? Your ZIP files do not contain the coverage reports. Can you have a look into the coverage file please if you can find the line with number 15732480 ?

Regards,

**Comment by Bertk** [comment]
Hi, @guwirth,

you are right. The line number is available in the coveragexml file and generated by the Microsoft VS2017 coverage tool. I will close this issue. 

Regards
Bert

[TFS-Build_TEAM-BUILD 2019-04-02 08_12_12.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/3032626/TFS-Build_TEAM-BUILD.2019-04-02.08_12_12.zip)

**Comment by Bertk** [comment]
see also https://developercommunity.visualstudio.com/content/problem/411331/vstest-coveragexml-with-wrongout-of-range-line-num.html
