### ISSUE TITLE
System library header file inclusion issue.

### ISSUE THREAD

**Issue by sresheno** [SonarOpenCommunity/sonar-cxx#170]
I have the following in my sonar-runner.properties file
sonar.cfamily.library.directories=/usr/include/,/usr/include/c++/4.8.2/
sonar.cxx.include-directories=/usr/include/,/usr/include/c++/4.8.2/
sonar.cxx.library.directories=/usr/include/,/usr/include/c++/4.8.2/
sonar.c.library.directories=/usr/include/,/usr/include/c++/4.8.2/

Despite the above properties, I see the logs where Sonar is unable to find files as 
map, string, openssl/x509.h etc.

05:20:16.187 WARN  - [/opt/sonar-runner-2.3/bin/data/saworkspacecc/pki/src/pki/utils/CryptoUtils.cpp:15]: cannot find the sources for '#include  iostream'
05:20:16.188 WARN  - [/opt/sonar-runner-2.3/bin/data/saworkspacecc/pki/src/pki/utils/CryptoUtils.cpp:21]: cannot find the sources for '#include  openssl/x509v3.h'

Please let me know how can I fix this

Version Details (for Fedora19)

> > sonar-runner -v
> > SonarQube Runner 2.3
> > Java 1.7.0_51 Oracle Corporation (64-bit)
> > Linux 3.11.6-200.fc19.x86_64 amd64

**Comment by jmecosta** [comment]
What version of the plugin are you using ?

**Comment by pmalek** [comment]
v0.9.3 with sonarqube-5.1

**Comment by jmecosta** [comment]
Can you run with -X, in the beginning you can check what folders are being
used as search path.

**Comment by pmalek** [comment]
What should I look for there?

**Comment by jmecosta** [comment]
Should be the same as what you define in your property file

**Comment by pmalek** [comment]
What do you mean by search path though?

**Comment by jmecosta** [comment]
Actually are you using also the sonar source plugin? For the directories,
when running in debug mode the plugin will print the folders used to search
header files, its in the same location where macro translation occurs. You
should see of the directories you define in you properties file are
correctly printed by the plugin.

**Comment by gyllidor** [comment]
Hi!

 How can I include directories recursive? 
For example if I have header with #include "/home/a/someheader.h" and option sonar.cxx.includeDirectories=/home then plugin will not find this file "someheaeder.h". I am right?
I have a big project with many different path of includes, should I add all of them to sonar.cxx.includeDirectories or only root folder for this includes?

Thanks!

**Comment by guwirth** [comment]
Easy saying: you have to provide same includes as you do for the compiler. For VS these are e.g. all *Additional Includes*.
