### ISSUE TITLE
sonar xml does not scan new template rule created.

### ISSUE THREAD

**Issue by sodeshpa** [SonarOpenCommunity/sonar-cxx#1706]
I have configured a new rule for .config file.

**temp.config**
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.web>
    <sessionState mode="InProc" customProvider="DefaultSessionProvider" />
  </system.web>
</configuration>  

**XPATH Expression:**
/configuration/system.web/sessionState[@mode="InProc"]@customProvider

* SonarQube version? 7.4

I have created default xml profile and activated this rule.

While my other .net profile is default, active , with Sonarscanner MSbuild commands when the project is getting built I am hoping that it will also pick up the xml profile and scan the project for .config file
But the code smell is not reported

**Comment by guwirth** [comment]
Hi @sodeshpa,

this is the cxx forum. Think you are wrong with your XML issue here?
Think you should use: https://community.sonarsource.com/

Regards,
