### ISSUE TITLE
Clang Static Analyzer: add support for full path/flow to a given issue

### ISSUE THREAD

**Issue by romanek-adam** [SonarOpenCommunity/sonar-cxx#1707]
The goal of this task is to extend Clang Static Analyzer support in sonar-cxx plugin with the full path to a given issue (which can be found under the "path" key in CSA's *.plist files; it's also called "flow" in SQ terms).

**Comment by romanek-adam** [comment]
I have a working solution on my desk which I'm about to upload shortly.

**Comment by guwirth** [comment]
Hi @romanek-adam,

we are interested to see you solution.

Regards,

**Comment by romanek-adam** [comment]
Hi @guwirth ,
Have you seen my PR? Please see my comment in it.

**Comment by guwirth** [comment]
@romanek-adam yes, see comments there.
