### ISSUE TITLE
does sonar cxx plugin support cppcheck v1.87 all errors and warnnings?

### ISSUE THREAD

**Issue by zhankangbao** [SonarOpenCommunity/sonar-cxx#1712]
does sonar cxx plugin support cppcheck v1.87 all errors and warnnings?

* cxx plugin version 1.2.2
* SonarQube version Community Edition 7.4

**Comment by guwirth** [comment]
Hi @zhankangbao,

see release notes https://github.com/SonarOpenCommunity/sonar-cxx/releases.

Regards,
