### ISSUE TITLE
Clang-tidy question

### ISSUE THREAD

**Issue by mfenjiro** [SonarOpenCommunity/sonar-cxx#1713]
Hey there !

Quick question : does the clang-tidy plugin with sonar-cxx are compatible with the Jenkins plugin: ' Post Sonar Issues as Gerrit Comment ? '

thank you for your amazing work

https://wiki.jenkins.io/display/JENKINS/Sonar+Gerrit

**Comment by guwirth** [comment]
Hi @mfenjiro,

sorry, never tried it. But I see no reason why it should not work. But I fear you have to try it by your own...

Regards,

**Comment by mfenjiro** [comment]
Oh ok thank you !
