### ISSUE TITLE
SonarScanner: Need to understand where Quality Profile is being loaded from and how to specify any other quality profile.

### ISSUE THREAD

**Issue by aatmankothari** [SonarOpenCommunity/sonar-cxx#1717]
$ ./sonar-analysis.sh
INFO: Scanner configuration file: C:\localAnalysis\sonar-scanner-3.0.3.778\conf\sonar-scanner.properties
INFO: Project root configuration file: C:\IBM\<user>\tools\localAnalysis\sonar-project-unix.properties
INFO: SonarQube Scanner 3.0.3.778
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Windows 7 6.1 amd64
INFO: SONAR_SCANNER_OPTS=-Xmx1024m
INFO: User cache: C:\Users\<user>\.sonar\cache
INFO: Publish mode
INFO: Load global settings
INFO: Load global settings (done) | time=1007ms
INFO: Server id: 15323a874858ec5
INFO: User cache: C:\Users\<user>\.sonar\cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=111ms
INFO: Load/download plugins
INFO: Load/download plugins (done) | time=107895ms
INFO: SonarQube server 7.1.0
INFO: Default locale: "en_GB", source code encoding: "UTF-8"
INFO: Process project properties
INFO: Execute project builders
INFO: Execute project builders (done) | time=1ms
INFO: Load project branches
INFO: Load project branches (done) | time=56ms
INFO: Load project pull requests
INFO: Load project pull requests (done) | time=37ms
INFO: Load branch configuration
INFO: Load branch configuration (done) | time=2ms
INFO: Load project repositories
INFO: Load project repositories (done) | time=39ms
**INFO: Load quality profiles
INFO: Load quality profiles (done) | time=70ms**
INFO: Load active rules
INFO: Load active rules (done) | time=1690ms
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=213ms
INFO: Project key: SVOC:MDMApp:Unix:<hostname>-<user>-Local
INFO: Project base dir: C:\IBM\<user>
INFO: -------------  Scan SVOC:MDMApp:Unix:<hostname>-<user>-Local
INFO: Base dir: C:\IBM\<user>
INFO: Working dir: c:\localAnalysis\working\sonar\Unix
INFO: Source paths: Aviva/Source/Unix
INFO: Source encoding: UTF-8, default locale: en_GB
INFO: Load server rules
INFO: Load server rules (done) | time=571ms
WARN: Property 'sonar.abap.file.suffixes' is not declared as multi-values/property set but was read using 'getStringArray' method. The SonarQube plugin declaring this property should be updated.
INFO: Index files
INFO: Included sources:
INFO:   **/src/**/*.java
INFO:   **/ejbModule/**/*.java
INFO: 275 files indexed
INFO: 514 files ignored because of inclusion/exclusion patterns
INFO: Quality profile for java: Sonar way
INFO: Sensor JavaSquidSensor [java]
INFO: Configured Java source version (sonar.java.source): none
INFO: JavaClasspath initialization
WARN: Bytecode of dependencies was not provided for analysis of source files, you might end up with less precise results. Bytecode can be provided using sonar.java.libraries property
INFO: JavaClasspath initialization (done) | time=14ms
INFO: JavaTestClasspath initialization
INFO: JavaTestClasspath initialization (done) | time=1ms
INFO: Java Main Files AST scan
INFO: 275 source files to be analyzed
INFO: 3/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\A1SuspectCollapse\src\com\uklife\bp\createsuspects\A1CreateSuspectsUtil.java
INFO: 5/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\AutoRegistration\src\main\java\com\aviva\util\FileToXMLConverter.java
INFO: 31/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\AvivaDeleteClientAndContracts\src\com\uklife\dpa\extractContractAndClient\DetermineContractAndClientForDeletion.java
INFO: 41/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\AvivaFTPBatchXMLFormat\src\com\aviva\mdm\Coder.java
INFO: 93/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\AvivaMDMEventPublish\src\main\java\com\aviva\mdm\taxation\Customer.java
INFO: 129/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\CommissionMDM\src\InvokeShell.java
INFO: 155/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\CommissionMDM\src\TestCaddPartyAlert.java
INFO: 181/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\ExtractAML\src\com\uklife\aml\contractextract\ContractDetails.java
INFO: 201/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\MIReports\src\com\uklife\cvh\mireports\ContactMethodCombination.java
INFO: 207/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\MIReports\src\com\uklife\cvh\mireports\PartyDataQulaity.java
INFO: 222/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\MIReports\src\com\uklife\ssp\mireports\HitboxCustomerDetails.java
INFO: 237/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\MyMoneyBatchProcessor\src\main\java\com\aviva\mdm\util\MyMoneyBatchBuilder.java
INFO: 240/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\ReportGenerator\src\com\nu\cvh\reportGenerator\ContactHistoryReport.java
INFO: 242/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\ReportGenerator\src\com\nu\cvh\reportGenerator\EmployeeMaintenanceReport.java
INFO: 245/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\ReportGenerator\src\com\nu\cvh\reportGenerator\StartErrorReport.java
INFO: 266/275 files analyzed, current file: C:\IBM\<user>\Aviva\Source\Unix\policy-status-updater\src\main\java\com\aviva\mdm\policystatus\PolicyStatusUpdater.java
INFO: 275/275 source files have been analyzed
INFO: Java Main Files AST scan (done) | time=161790ms
INFO: Java Test Files AST scan
INFO: 0 source files to be analyzed
INFO: Java Test Files AST scan (done) | time=0ms
INFO: Sensor JavaSquidSensor [java] (done) | time=163654ms
INFO: Sensor Embedded CSS Analyzer Sensor [css]
INFO: 0/0 source files have been analyzed
INFO: 0 source files to be analyzed
INFO: Sensor Embedded CSS Analyzer Sensor [css] (done) | time=1097ms
INFO: Sensor SurefireSensor [java]
INFO: parsing [C:\IBM\<user>\target\surefire-reports]
INFO: Sensor SurefireSensor [java] (done) | time=2ms
INFO: Sensor JaCoCoSensor [java]
INFO: Sensor JaCoCoSensor [java] (done) | time=2ms
INFO: Sensor SonarJavaXmlFileSensor [java]
INFO: Sensor SonarJavaXmlFileSensor [java] (done) | time=2ms
INFO: Sensor HTML [web]
INFO: 0/0 source files have been analyzed
INFO: Sensor HTML [web] (done) | time=18ms
INFO: Sensor SmellMeasuresSensor [smells]
INFO: Sensor SmellMeasuresSensor [smells] (done) | time=1033ms
INFO: Sensor FindBugs Sensor [findbugs]
INFO: Loading findbugs plugin: c:\localAnalysis\working\sonar\Unix\findbugs\findsecbugs-plugin.jar
INFO: Findbugs output report: c:\localAnalysis\working\sonar\Unix\findbugs-result.xml
INFO: Sensor FindBugs Sensor [findbugs] (done) | time=12138ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=298ms
INFO: Sensor CPD Block Indexer
INFO: Sensor CPD Block Indexer (done) | time=1241ms
INFO: SCM provider for this project is: git
INFO: 275 files to be analyzed
INFO: 132/275 files analyzed
INFO: 274/275 files analyzed
WARN: Missing blame information for the following files:
WARN:   * Aviva/Source/Unix/ReportGenerator/src/com/nu/cvh/reportGenerator/EmployeeMaintenanceReport.java
WARN: This may lead to missing/broken features in SonarQube
INFO: 21 files had no CPD blocks
INFO: Calculating CPD for 254 files
INFO: CPD calculation finished
INFO: Analysis report generated in 35025ms, dir size=3 MB
INFO: Analysis reports compressed in 5039ms, zip size=1 MB
INFO: Analysis report uploaded in 1641ms
INFO: ANALYSIS SUCCESSFUL, you can browse https://sonarqube.avivaaws.com/dashboard/index/SVOC:MDMApp:Unix:<hostname>-<user>-Local
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at https://sonarqube.avivaaws.com/api/ce/task?id=AWqMiO5AkhURJJ1S6jSF
INFO: Task total time: 4:22.816 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 7:27.243s
INFO: Final Memory: 73M/574M
INFO: ------------------------------------------------------------------------
2019-05-06 10:45:51 GMTDT | Analysis completed, reports are generated in https://sonarqube.avivaaws.com/dashboard. Please search your project analysis dashboard and bookmark it for future reference.

**Comment by guwirth** [comment]
Hello @aatmankothari,

this is a SonarQube core functionality. Please ask here: https://community.sonarsource.com/

Regards,
