### ISSUE TITLE
cppcheck: No way to debug version 2 parser failures

### ISSUE THREAD

**Issue by HannesFranke-smartoptics** [SonarOpenCommunity/sonar-cxx#1718]
Please [turn debug info on](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information) and reproduce your issue.
The debug info in the log file could help to solve or locate the issue.

### Description

If the cppcheck version 2 parser fails there is no way to get the error output.
This happened to me because we are post-processing the xml output before passing it to sonar.

This happens because any errors produced are logged with `TRACE` level:  
https://github.com/SonarOpenCommunity/sonar-cxx/blob/0a618baad869b24e1fff82b7f16fcc3d7b129bcb/cxx-sensors/src/main/java/org/sonar/cxx/sensors/cppcheck/CxxCppCheckSensor.java#L79
and there doesn't seem to be a way to se the debug level to `TRACE` from the outside (at least https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information doesn't mention any).

### Steps to reproduce the problem

1. Create a cppcheck xml output file which cannot be parsed by the [CppcheckParserV2.java](https://github.com/SonarOpenCommunity/sonar-cxx/blob/0a618baad869b24e1fff82b7f16fcc3d7b129bcb/cxx-sensors/src/main/java/org/sonar/cxx/sensors/cppcheck/CppcheckParserV2.java)
  This can be done by e.g. adding an empty `<error />` element.
2. Pass the file to sonar scanner.
3. Observe how the version1 parser is used, without any indication why the version2 parser failed, even if using `--debug` cmdline.

### Possible Solution

The log level on parsing failure should probably be `DEBUG` instead of `TRACE`. This would mean it is still normally hidden but parsing failures can be debbuged easily.
```
        LOG.debug("Report {} cannot be parsed by {}", report, parser, e);
```

Alternatively provide an example how to enable `TRACE` debug level in the wiki, if this log level is necessary to get all debug output from the plugins.

**Comment by guwirth** [comment]
Hi @HannesFranke-smartoptics,

thanks for your feedback. First of all I can't remember why this message is TRACE and not DEBUG. WE will have a look to it.

Did you try: `-Dsonar.log.level=TRACE|DEBUG`?
see:
- https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information
- https://docs.sonarqube.org/latest/analysis/analysis-parameters/ ==> Analysis Logging
- https://docs.sonarqube.org/latest/instance-administration/system-info/

Regards,

**Comment by HannesFranke-smartoptics** [comment]
Thanks for the quick reply.

Yes, I tried `-Dsonar.log.level=TRACE|DEBUG` but this doesn't seem to get passed down to the plugin itself (using https://github.com/SonarSource/sonar-scanner-cli/releases v. 3.3.0.1492, which is the latest release).

**Comment by guwirth** [comment]
Change message to debug
