### ISSUE TITLE
clang-tidy: modernize-use-nodiscard check message breaks regex

### ISSUE THREAD

**Issue by jspam** [SonarOpenCommunity/sonar-cxx#1719]
### Sample file

```cpp
class A {
  bool empty() const;
};
```

### clang-tidy output

`clang-tidy --extra-arg=-std=c++17 -checks=modernize-use-nodiscard nodiscard.cpp`

```
1 warning generated.
/tmp/nodiscard.cpp:2:3: warning: function 'empty' should be marked [[nodiscard]] [modernize-use-nodiscard]
  bool empty() const;
  ^
  [[nodiscard]] 
```

### Expected behavior

The clang-tidy sensor adds a new finding with ID `ClangTidy:modernize-use-nodiscard`

### Actual behavior

clang-tidy sensor fails to add the issue with an error message
```
07:59:32.406 ERROR - Could not add the issue 'CxxReportIssue [ruleId=[nodiscard, locations=CxxReportLocation [file=/tmp/nodiscard.cpp, line=2, info=function 'empty' should be marked]]':The rule 'ClangTidy:[nodiscard' does not exist.
', skipping issue
```

**Comment by guwirth** [comment]
Current regex is parsing for first string in square brackets.
Here we have two: [[nodiscard]] [modernize-use-nodiscard]
- change it to use last string in square brackets as ruleId => #1742

**Comment by guwirth** [comment]
Hi @jspam you can try with the snapshot https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts. Regards.
