### ISSUE TITLE
clang-tidy: Support diagnostic notes

### ISSUE THREAD

**Issue by jspam** [SonarOpenCommunity/sonar-cxx#1720]
clang-tidy often provides additional context for its diagnostic in the form of notes. These are currently lost when parsing a clang-tidy log file.

SonarQube supports issue flows, which seem like the appropriate way to display that information. See https://docs.sonarqube.org/display/SONARQUBE67/Issues , section "Understanding issue context"

Example 1:

```cpp
#include <cstdio>
  
int X;

int main(int argc, char** argv)
{
    int* x = nullptr;
    if (argc > 1) {
        x = &X;
    }
    printf("%d", *x);
}
```

clang-tidy output:

```
1 warning generated.
/tmp/static-analyzer.cpp:11:18: warning: Dereference of null pointer (loaded from variable 'x') [clang-analyzer-core.NullDereference]
    printf("%d", *x);
                 ^
/tmp/static-analyzer.cpp:7:5: note: 'x' initialized to a null pointer value
    int* x = nullptr;
    ^
/tmp/static-analyzer.cpp:8:9: note: Assuming 'argc' is <= 1
    if (argc > 1) {
        ^
/tmp/static-analyzer.cpp:8:5: note: Taking false branch
    if (argc > 1) {
    ^
/tmp/static-analyzer.cpp:11:18: note: Dereference of null pointer (loaded from variable 'x')
    printf("%d", *x);
                 ^
```

Example 2:

```cpp
struct A {
    void foo(int bar);
};

void A::foo(int baz) {
}
```

clang-tidy output:

```
/tmp/name-mismatch.cpp:2:10: warning: function 'A::foo' has a definition with different parameter names [readability-inconsistent-declaration-parameter-name]
    void foo(int bar);
         ^
/tmp/name-mismatch.cpp:5:9: note: the definition seen here
void A::foo(int baz) {
        ^
/tmp/name-mismatch.cpp:2:10: note: differing parameters are named here: ('bar'), in definition: ('baz')
    void foo(int bar);
         ^
```

**Comment by mfenjiro** [comment]
Hey there,

I see you are using almost the same setup as me. I am trying to use clang-tidy, Jenkins, sonarqube and gerrit as a combo for my project. What is your experience with them ? What is your compile_commmands.json generator tool ? Have you find problems with it, clang-tidy and the parser of sonarscanner ?
Thank you in advance.

Best regards,

**Comment by guwirth** [comment]
Hi @jspam you can try with the snapshot https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts. Regards.
