### ISSUE TITLE
Using sonar-cxx With SonarQube Developer Edition

### ISSUE THREAD

**Issue by esduran** [SonarOpenCommunity/sonar-cxx#1721]
Please [turn debug info on](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information) and reproduce your issue.
The debug info in the log file could help to solve or locate the issue.

### Description

I am utilizing the SonarQube Developer Edition to analyze my C++ projects. 
While the paid edition does provide built-in support for C++ analysis, I wanted to extend it by adding the sonar-cxx plugin. I have the plugin installed and it shows up on my Administration page.

When I execute sonar-scanner, I get an error stating:

` Language of file 'main.cpp' can not be decided as the file matches patterns of both sonar.lang.patterns.c++ : **/*.cxx,**/*.cpp,**/*.cc,**/*.c,**/*.hxx,**/*.hpp,**/*.hh,**/*.h and sonar.lang.patterns.cpp : **/*.cc,**/*.cpp,**/*.cxx,**/*.c++,**/*.hh,**/*.hpp,**/*.hxx,**/*.h++,**/*.ipp`

**Is there a way I can force it to use the paid SonarSource plugin instead of the open-source one?**

**Comment by guwirth** [comment]
Hi @esduran,

each file extension must be unique assigned to one language (plugin). To deactivate that the cxx plugin is reading (indexing) the files set a dummy file extension: 

e.g. `sonar.cxx.suffixes.sources=.dummy`

Regards,

**Comment by esduran** [comment]
Thank you for your prompt and informative response @guwirth. This solved my problem combined with the addition of `sonar.cxx.suffixes.headers-.dummy`
