### ISSUE TITLE
Exclude switch statement from complexity

### ISSUE THREAD

**Issue by 0ge** [SonarOpenCommunity/sonar-cxx#1722]
### Description

I have some C++ code that looks like the following:

    void MyClass::MyFunction(ErrorSource source) {    
        switch (source) {
            case ErrorSource::kSensorA:
                HandleA();
                break;
            case ErrorSource::kSensorB:
                HandleB();
                break;
        }
        // And so on...
    }

There are more than 10 cases, and thus SonarQube flags the section as having too high complexity. (_"The Cyclomatic Complexity of this function is x which is greater than y authorized."_) In my opinion this is less error prone and more clear than splitting in separate functions handling a subset of errors (which is the only 'workaround' that I've figured out).

We exclusively use switch statements for enums in our project and we always have a case for each value.
We would like to remove switch statements from the complexity analysis, but I cannot find any way to do this?

### Related information

cxx: 0.9.7
SonarQube: 6.6

**Comment by guwirth** [comment]
Hello @0ge,

thanks for your feedback.

But I think we can't change that, we follow the SonarSource guidlines: https://docs.sonarqube.org/latest/user-guide/metric-definitions/.

By the way: that was the reason they introduced the "Cognitive Complexity": https://docs.codeclimate.com/docs/cognitive-complexity.

Regards,

**Comment by 0ge** [comment]
Thank you,

Very nice information. For me its unfortunate, but I understand the distinction and the need to keep cyclomatic complexity as is. I'll just keep manually marking them as Won't fix.
