### ISSUE TITLE
Typo in CxxHighlighterVisitor.java: "Highligthing error in file"

### ISSUE THREAD

**Issue by streetster** [SonarOpenCommunity/sonar-cxx#1723]
Creating a ticket to tie a PR to...

### Description

Highlighting is spelled incorrectly:

```
WARN: Highligthing error in file '/home/ansible/workspace/Test_Babylon/src/tools/clientTest.cpp' at line:496, column:29
WARN: Highligthing error in file '/home/ansible/workspace/Test_Babylon/src/tools/heliumDBTest.cpp' at line:259, column:23
WARN: Highligthing error in file '/home/ansible/workspace/Test_Babylon/src/tools/levelDBTest.cpp' at line:301, column:23
WARN: Highligthing error in file '/home/ansible/workspace/Test_Babylon/src/tools/testClient.cpp' at line:297, column:33
```

### Steps to reproduce the problem

Scan a file that has some incorrect Highlighting (perhaps a bug in it's own right):

```
foo = bar(123, "\
this is my string
blah blah
  ");
```

### Expected behavior

Highlighting spelled correctly

### Actual behavior

Highlighting spelled incorrectly (Highligthing)

### Known workarounds

n/a

### LOG file

n/a

### Related information

latest

**Comment by guwirth** [comment]
@streetster thanks for providing this fix!
