### ISSUE TITLE
Support Visual Studio 2019 With v142 Platform Toolset

### ISSUE THREAD

**Issue by nebulous999** [SonarOpenCommunity/sonar-cxx#1725]
### Description

I am new to SonarQube and sonar-cxx, and I am attempting to set up analysis for a analyze a Visual Studio Solution, which is currently built with MSBuild on a [Build Tools for Visual Studio 2019](https://visualstudio.microsoft.com/downloads/) command prompt.  The PlatformToolset is currently the 'v142' version that ships with Visual Studio 2019 C++ workloads.  The VS solution is mixed with mainly C++ projects, with a few C# ones.

Looking though the log, I see a warning identical to the one in #1311
> 14:48:26.745 INFO: Could not assign VS platform toolset - use default: V120

It appears that [setPlatformToolsetFromLine](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/src/main/java/org/sonar/cxx/CxxVCppBuildLogParser.java#L197) will currently set the toolset to no more than "V141".

### Steps to reproduce the problem

The commands we're running (redacted with 'XXXX') are:
> > SET _CL_=/permissive- /analyze:WX-
> >"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" .\XXXX.sln -target:Rebuild -maxCpuCount -nodeReuse:false -verbosity:minimal -property:Configuration=Debug;Platform=Win32;TreatWarningAsError=false;RunCodeAnalysis=true;EnableFXCop=true -fileLogger -fileLoggerParameters:LogFile=msbuild-detailed.log;Verbosity=detailed;Encoding=UTF-8  1>msbuild-minimal.log
> > sonar-scanner.bat -D"sonar.projectKey=XXXX" -D"sonar.sources=." -D"sonar.host.url=http://XXXX:9000" -D"sonar.login=XXXX" -D"sonar.language=c++" -D"sonar.verbose=true" -X

Then we have sonar-cxx configured as follows:
sonar.cxx.msbuild.reportPath=msbuild-detailed.log
sonar.cxx.vc.reportPath=msbuild-minimal.log
sonar.cxx.cppcheck.reportPath=cppcheck.xml
sonar.exclusions=...

Here's a typical cl.exe command line:
> 14:48:25.963 DEBUG: build log parser cl.exe line='         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\bin\HostX86\x86\CL.exe /c /Ixxxx /Zi /nologo /W3 /WX /diagnostics:column /Od /Oy- /D CODE_ANALYSIS /D _LIB /D _DEBUG /D WIN32 /D _USE_STRING_NO_LOCALE_WRAPPER /D _WIN32_WINNT=_WIN32_WINNT_VISTA /D _MBCS /Gm- /EHa /RTC1 /MTd /GS /fp:precise /permissive- /Zc:wchar_t- /Zc:forScope /Zc:inline /GR- /Yc"stdafx.h" /Fp"XXXX" /Fo"Debug\\" /Fd"XXXX.pdb" /Gd /TP /analyze /analyze:quiet /analyze:plugin"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.21.27702\bin\HostX86\x86\EspXEngine.dll" /FC /errorReport:queue  /analyze:ruleset"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Team Tools\Static Analysis Tools\Rule Sets\AllRules.ruleset" /analyze:projectdirectory"XXXX" /analyze:rulesetdirectory";C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Team Tools\Static Analysis Tools\\Rule Sets" stdafx.cpp'

### Expected behavior

sonar-cxx will set appropriate properties for v142, e.g. VS2019 Build Tools version 16.0.0, such as:
* _MSC_VER=1920
* _MSC_FULL_VER=192027508

Or it should at least use the V141 toolset properties, because it's closer to V142 than V120 is.

### Actual behavior

Analysis is taking quite a while on our project, so I'm unsure of the full consequences of using V120 (VS2013?) toolset definitions, rather than V141 or V142.

### Known workarounds

Install the v141 tool chain, modify the solution with the PlatformToolset properties all set to 'v141', and rebuild

### Related information

* cxx plugin version 1.2.2.1653
* SonarQube Scanner 3.3.0.1492 (sonar-scanner-cli)

In other news, I think that the sonar.cxx.vc.regex property may need to change for VS2019.
The [Compilers Wiki Page](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers) lists:
`sonar.cxx.vc.regex=(.*>)?(?<file>.*)\\((?<line>\\d+)\\)\\x20:\\x20warning\\x20(?<id>C\\d+):(?<message>.*)`

This one wasn't matching for me when tested with v142, so I think we may need:
`sonar.cxx.vc.regex=(.*>)?(?<file>.*)\\((?<line>\\d+)\\)\\:\\x20warning\\x20(?<id>C\\d+):\\x20(?<message>.*)`

It seems they may have removed a space from before the first colon, and added a space following the colon before the message.

**Comment by Bertk** [comment]
Hi,
I updated CxxVCppBuildLogParser.java and added VS2019 support. Please share your feedback and I will create  a PR and add a test.
 
https://github.com/Bertk/sonar-cxx/blob/534d13812d2554c467c4e25b1b9b3620f8264d80/cxx-squid/src/main/java/org/sonar/cxx/CxxVCppBuildLogParser.java

**Comment by nebulous999** [comment]
That [change](https://github.com/Bertk/sonar-cxx/commit/534d13812d2554c467c4e25b1b9b3620f8264d80#diff-28ae1d1c5ab1cae3cb5cae7c6dbf932b) looks like it should work just fine.  Thanks!

Can anyone confirm whether sonar.cxx.vc.regex needs to change for V142?  I'm still not quite sure about that...

**Comment by nebulous999** [comment]
OK never mind on the regex.  I just had a problem because I was entering it into the web interface, not because of the V142 toolset.  It seems that you don't need the double backslash in the web interface, so there you should enter:
`(.*>)?(?<file>.*)\((?<line>\d+)\):\x20warning\x20(?<id>C\d+):\x20(?<message>.*)`
But in sonar-project.properties, you would still need:
`sonar.cxx.vc.regex=(.*>)?(?<file>.*)\\((?<line>\\d+)\\):\\x20warning\\x20(?<id>C\\d+):\\x20(?<message>.*)`
