### ISSUE TITLE
Support SonarQube 7.9.x LTS version

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1732]
Support SonarQube 7.9.x LTS version:
https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.9.zip

**Comment by guwirth** [comment]
Bigger change update to Java 11 necessary.

**Comment by CharmWang** [comment]
Now, can 1.3 support sonar7.9.x ?
Sorry that when you plan to release sonar-cxx1.4 plugin? We have Upgraded sonar,but not know if we can use 1.3
