### ISSUE TITLE
Plugin 1.3 release

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1740]
Hi all,

like to release the V1.3 plugin first for SQ 7.7 and SQ 7.8 together with some improvements. This includes SQ 6.7 LTS compatibility.

Because we have to switch to **Java 11** for SQ 7.9 LTS I moved this step to V1.4. With Java 11 we have to stop the support of older versions then.

Regards,

**Comment by lg2de** [comment]
Just now I've tested sonar-cxx-plugin-1.3.0.1710.jar with SQ 7.9.1.
It was **running fine**!
I think, Java 11 is required for the server, but may be not for the client running the analysis (build server).

I would be happy to see 1.3.0 to be released (for SQ 7.X) very soon.
Version 1.4.0 may switch to Java 11.

**Comment by guwirth** [comment]
Hi @lg2de,

thanks for your feedback. Could you give some more information what you exactly did test:
* on Windows / Linux?
* which sensors?
* ...

Regards,

**Comment by lg2de** [comment]
Windows Server 2016
Cppcheck 1.86
Java 1.8.0_212 Azul Systems, Inc. (64-bit)

**Comment by guwirth** [comment]
@lg2de thanks for your feedback. Cppcheck test is a little bit less to say 7.9 is working. Our CI on AppVeyor is currently not working, investigation is ongoing (#1734). But 1.3 should be releasable latest end of next week.

**Comment by lg2de** [comment]
Version 1.3 is compatible with the new SQ API.
Version 1.2.X is not compatible with SQ 7.7 and above.
This is what I mean with "the plugin is compatible".

Nice to hear that the release date is near. I wondering about the (new) issues assigned to milestone 1.3...

**Comment by guwirth** [comment]
Hi @lg2de currently these are the points label 1.3:
https://github.com/SonarOpenCommunity/sonar-cxx/issues?utf8=%E2%9C%93&q=milestone%3A1.3.0+is%3Aclosed+

**Comment by lg2de** [comment]
> Hi @lg2de currently these are the points label 1.3:
> https://github.com/SonarOpenCommunity/sonar-cxx/issues?utf8=%E2%9C%93&q=milestone%3A1.3.0+is%3Aclosed+

Yes, but I'm wondering about the new OPEN enhancements getting tagged with 1.3.0.

**Comment by guwirth** [comment]
>  OPEN enhancements

@lg2de think #1720 will make it. No sure how complicated #1697 is?

**Comment by guwirth** [comment]
Draft release notes:
---
We are pleased to announce the SonarQube C++ Community Plugin version 1.3.0.
See lists below for features added and bugs fixed in this release.

# SonarQube compability

- tested and released for **SonarQube 6.7 LTS, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8**<br>see also [SonarQube compatibility matrix](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix)
- [Installation Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Installation)
- [Upgrade Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-Instructions)

# Enhancements

- SQ 7.7 support #1696 #1695
- SQ 7.8 support #1731 #1738
- minimal supported SQ API is 6.7 #1317 
- Cppcheck 1.88 support #1733 #1739 #1741
- Clang-Tidy:
  - update rules (Clang 8.0) #1730
  - support diagnostic notes #1742 #1720
- Clang Static Analyzer
  - add path/flow support for .plist reports #1710 #1707
- GCC
  - support warnings without rule id #1708 #1703
- PC-Lint
  - support PC-Lint plus V1.2 messages #1716
  - support supplemental messages #1728
- Visual Studio / Msbuild LOG file analysis:
  - support Visual Studio 2019 with v142 platform toolset #1725 #1726
  - improve analysis #1668
- use of scanner 4.0 #1736
- use of parent POM 51
- static code analysis checks are removed #1704
  - BooleanEqualityComparisonCheck, CollapsibleIfCandidateCheck, CommentedCodeCheck, HardcodedAccountCheck, HardcodedIpCheck, MagicNumberCheck, MissingCurlyBracesCheck, NestedStatementsCheck, ReservedNamesCheck, SafetyTagCheck, StringLiteralDuplicatedCheck, SwitchLastCaseIsDefaultCheck, UnnamedNamespaceInHeaderCheck, UseCorrectIncludeCheck, UseCorrectTypeCheck, UselessParenthesesCheck, UsingNamespaceInHeaderCheck
  - use external tools like CppCheck, Clang, .... instead
- seperate cxx-lint tool into own JAR (no more part of cxx plugin) #1705
- refactoring #1737 #1691 #1690 #1689

# Bugfixes

- fixing OpenCppCoverage coverage report: not working since upgrade to 1.2.x #1669 #1709
- fixing typo Highligthing => Highlighting #1724 #1723
- support real paths in coverage sensor for C++/CLI #1701 #1688
- Clang-Tidy: modernize-use-nodiscard check message breaks regex #1719 #1742
- Clang-Tidy: missing rule [clang-diagnostic-warning] #1702

# Known Issues

For an up to date list of known issues see the issue tracker.
- not tested with Java 9, 10, 11
- not tested with SonarQube 7.9.x LTS
- [Ensure that a rule is enabled](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Activate-quality-rules) if you get no results. In new SQ versions the default profile is read-only. The cxx plugin does not enable all rules per default.
- Starting with SQ 6.2 there are some new metrics and some are no more available. Please have a look to the SonarQube release notes.
- `duplicated_lines_density` values are different with SQ 7.5
- project's duplication density value will likely rise with SQ 7.8 (SONAR-12188)
- [test execution metrics](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-test-execution-metrics) are not supported
- The [Cppcheck plugin](https://github.com/SonarQubeCommunity/sonar-cppcheck) is deprecated and not working in parallel to this plugin. This plugin provides an own Cppcheck sensor.
- C plugin and JSON Compilation Database support are experimental only

# Thanks ....

go to all contributors (in alphabetical order):

@Bertk
@bloodlee
@guwirth
@ivangalkin
@romanek-adam
@rudolfgrauberger
@stalb

... and all people which were active on the issue tracker!

**Comment by guwirth** [comment]
@all: released - feedback welcome

**Comment by lg2de** [comment]
Wondering why you explicit state "not tested with SQ 7.9". I tested successful!
I recommend: "Not *fully* tested with..."

**Comment by guwirth** [comment]
> Wondering why you explicit state "not tested with SQ 7.9".

@lg2de problem is that our CI (Travis/Appveyor #1734) is not running with SQ 7.9. Like to avoid that we get a bunch of issues...
