### ISSUE TITLE
JsonCompilationDatabase not handling array arguments

### ISSUE THREAD

**Issue by zanettea** [SonarOpenCommunity/sonar-cxx#1745]
Arguments in JsonCompilationDatabase are only handled as strings, but usually are arrays.

See specification: https://clang.llvm.org/docs/JSONCompilationDatabase.html  :

> arguments: The compile command executed as list of strings. Either arguments or command is required.

See also `clang -MJ fragment.json main.cpp` output as reference

**Comment by guwirth** [comment]
Hi @zanettea,

Thanks for your feedback. To fix this issue it would be helpful to provide a sample. Could you add a small Jason sample to this issue please.

Regards,

**Comment by guwirth** [comment]
Thanks to @tisoft for solving this!
