### ISSUE TITLE
Syntax error while trying to parse regex in raw string

### ISSUE THREAD

**Issue by Korny0301** [SonarOpenCommunity/sonar-cxx#1748]
### Description

Sonar-scanner can't parse a specific regular expression that is defined in a raw string. When using capturing groups with round brackets <code>()</code> inside the regular expression, the closing bracket of a capturing group can not be placed just in front of the very last closing bracket of the raw string.

### Steps to reproduce the problem

Create c++ file with regular expression:

```Cpp
#include <regex>
constexpr auto rgxStr = R"(([A-Z\d]))";
```

Run sonar-scanner with this file as inclusion (e.g. sonar-scanner -Dsonar.inclusion=test.cpp).

### Expected behavior

Line with defined regular expression in raw string should be parsed without syntax error.

### Actual behavior

Expression can't be parsed. Sonar-scanner resolves in error:
C++ skip parser error
C++ Parser can't read code. Declaration is skipped.

### Known workarounds

Avoid closing bracket immediately before the very last closing bracket that is used to finish the raw string. You could e.g. use a dollar sign before the very last closing bracket:
```Cpp
constexpr auto rgxStr = R"(([A-Z\d])$)";
```

### LOG file

10:27:42.924 DEBUG: finished preprocessing '/opt/wsp/project/test.cpp'
10:27:42.935 DEBUG: [/opt/wsp/project/test.cpp:2]: syntax error: const auto rgxStr = R "(([A-Z\d]\d{4}))"

### Related information

cxx plugin version: 1.2.0
SonarQube version: 7.2.1 (14109)

**Comment by guwirth** [comment]
Hi @Korny0301,

thanks for your feedback

Raw string literal. Used to avoid escaping of any character. Anything between the delimiters becomes part of the string:

`R "delimiter( raw_characters )delimiter"`
* delimiter: A character sequence made of any source character but parentheses, backslash and spaces (can be empty, and at most 16 characters long)

Your sample: `R"(([A-Z\d]))"`
* empty / delimiter
* detection of `)"` seems to be wrong in this case (maybe we have to count opening / closing brackets)
* other possible workaround should be to set delimiter e.g. `R"regex(([A-Z\d]))regex"`

Code reading raw strings is here: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/src/main/java/org/sonar/cxx/channels/StringLiteralsChannel.java#L90

Regards,

**Comment by Korny0301** [comment]
Hi @guwirth,

thanks for your response.

I already tried to use an additional delimiter but without success. The raw string ```R"regex(([A-Z\d]))regex"``` results in a syntax error as well.

Best regards

**Comment by guwirth** [comment]
Hi @Korny0301, fixed! You can try with https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts. Regards

**Comment by Korny0301** [comment]
I tried the new version and it works now. Thanks for fixing!!
