### ISSUE TITLE
Problem scanning with Leak Period

### ISSUE THREAD

**Issue by chenbe** [SonarOpenCommunity/sonar-cxx#1763]
Hi ,

### Description
When I scan my C/C++ code with Leak Period , I have a problem at the 3 scan: First Scan is the basic with the Leak Period Second scan is with the current code , I see the results well Third scan like the second , but I don’t see Coverage and new lines
I tried at 6.7.2 and 7.4 version of SOnarQube. I tried to scan with Leak Period at every scan , but didn’t work. Then scanned the first time with Leak Period , the second time without and it was OK , at the Third scan I have the same problem.

### Steps to reproduce the problem
I scan with the following command: /opt/sonar-scanner-3.0.3.778/bin/sonar-scanner -Dsonar.login=XXXXX -Dsonar.password=XXXXX -Dsonar.scm.forceReloadAll=true -Dsonar.sources=/var/lib/jenkins/workspace/DEBUG_Client_Scan_Code_By_SonarQube/vdm-11.7 -Dsonar.cxx.includeDirectories=sdk/source/engine/restapi/ -Dsonar.exclusions= /external/ , /dma/app/linux2/client/ , /dma/scripts/ , /dma/app/linux2/ec_client/client/peripheral/rb/ -Dsonar.language=c++ -Dsonar.projectKey=vdm-11.7
1. Scan the first code and update after if finished the Leak Period
2. Scan the new code without attaching Leak Period to the first scanned project
3. Scan the new code without attaching Leak Period to the first scanned project

### Expected behavior
When I scan the new code at the first time it works fine and I see the "Coverage %" and "New lines to Cover"
I expect that after the first scan , every scan for the same project will show the “Coverage %” and “New lines to Cover” witht the right valuesenter image description here 1

### Actual behavior
When I scan the new code at the first time it works fine and I see the "Coverage %" and "New lines to Cover"
If I scan again it doesn't compare the code to the Leak Period code , so if there is no change from the last scan the "Coverage %" become "-" and "New lines to Cover" is 0 

### Known workarounds
None 

Attached screenshots from all the steps

cxx plugin version - 0.9.7
SonarQube version  - 6.7.5

Thanks :)
Chen

**Comment by chenbe** [comment]
![sonar_problem_first_scan](https://user-images.githubusercontent.com/48548015/64761231-43976b00-d544-11e9-880a-0f1daf2920de.PNG)
![sonar_problem_second_scan](https://user-images.githubusercontent.com/48548015/64761232-44300180-d544-11e9-8f20-15b12bcfa2fa.PNG)
![sonar_problem_third_scan](https://user-images.githubusercontent.com/48548015/64761233-44300180-d544-11e9-851d-1104fcc78ce8.PNG)

**Comment by guwirth** [comment]
Hello @chenbe, 

the Leak Period information is derived from the connected SCM: https://docs.sonarqube.org/latest/user-guide/fixing-the-water-leak/. For SCM integration see: https://docs.sonarqube.org/latest/analysis/scm-integration/. You find more about "New" here https://docs.sonarqube.org/latest/user-guide/issues/#header-3.

Think you should ask SonarSource in there community. For my understanding issue has less todo with the cxx-plugin it's SonarQube core functionality.

Regards,

**Comment by chenbe** [comment]
I'll check.
Thanks :)
