### ISSUE TITLE
Remove deprecated property sonar.language from documentation

### ISSUE THREAD

**Issue by Str0mfresser** [SonarOpenCommunity/sonar-cxx#1765]
### Description
The documentation at [Running the analysis](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-the-analysis) suggests using the property `sonar.language=c++` which is deprecated since SonarQube 7.7 (see [SONAR-11449](https://jira.sonarsource.com/browse/SONAR-11449)).

As this property was deprecated a long time and is now silently ignored, it should not be used any more in examples.
Existing projects using sonar-cxx that contain files of other languages might suddenly fail analysis after an upgrade to SonarQube >=7.7 because these other languages used to be ignored.

### Example
- SonarQube <7.7 ignored `.java` files because of `sonar.language=c++`, resulting in a log entry like this:
```
WARN: File 'java/src/main/Foo.java' is ignored because it doesn't belong to the forced language 'c++'
```
- SonarQube >=7.7 does not ignore any files by default, therefore tries to analyze Java files, but then might lack required configuration parameters for Java analysis, resulting in a build error like this:
```
INFO: ------------- Run sensors on module FOO.BAR
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=15ms
INFO: Sensor JavaSquidSensor [java]
INFO: Configured Java source version (sonar.java.source): none
INFO: JavaClasspath initialization
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 36.404s
INFO: Final Memory: 22M/75M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: Please provide compiled classes of your project with sonar.java.binaries property
```

**Comment by guwirth** [comment]
todo for 1.4.0
