### ISSUE TITLE
comment_lines_data is deprecated

### ISSUE THREAD

**Issue by StanleySweet** [SonarOpenCommunity/sonar-cxx#1766]
Hello there,

### Description

I'm using your plugin to analyze regularly 0 A.D. (https://github.com/0ad/0ad) and I always get 
`WARN: Metric 'comment_lines_data' is deprecated. Provided value is ignored.` It also gets stuck on that line for like 10 mins but I guess that's unrelated.

### Steps to reproduce the problem

Just run an analysis on a cpp project.

### Expected behavior

There shouldn't be a warning about missing metrics

### Related information

* cxx plugin version? 1.3.2
* SonarQube version? 7.7

**Comment by guwirth** [comment]
Hi @StanleySweet,

Because 1.3.x is still supporting SQ 6.7 LTS it is still there, just ignore it.

The metric was dropped from SonarQube 7.3 and should stop providing values (related to: https://jira.sonarsource.com/browse/SONAR-11064).

We should remove it with cxx 1.4.

Regards

**Comment by StanleySweet** [comment]
Thanks for the fast reply !

**Comment by guwirth** [comment]
removed with cxx plugin 2.0
