### ISSUE TITLE
Usage of external code checkers

### ISSUE THREAD

**Issue by KhvalIvanl** [SonarOpenCommunity/sonar-cxx#1767]
### Description

Can't add issues from xml report using [unsupport code checker report parser](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis#usage-of-unsupported-code-checkers) - sonar.cxx.other.reportPath is literally ignored during the scan.

### Steps to reproduce the problem

1) placed xml report (test.xml) in the root of the scanned project directory;
2) added "sonar.cxx.other.reportPath=test.xml" to sonar-project.properties file;
3) run sonar-scanner in project directory.

### Expected behavior

Scan log displays information about test.xml parse, new issue is added to source file in SonarQube project.

### Actual behavior

No information regarding scan process in scan log + no new issues from xml report were added to SonarQube.

### Related information

* cxx plugin version - 1.2.0 and 1.3.2.1814
* SonarQube version - 6.7.6 and 6.7.7 (Community editions)

### LOG file
sonar-project.properties content:
```
sonar.projectKey=sample
sonar.projectName=sample  
sonar.projectVersion=0.0.1-SNAPSHOT
sonar.language=c++
sonar.sources=.
sonar.cxx.other.reportPath=test.xml
```
Log file [content](https://github.com/SonarOpenCommunity/sonar-cxx/files/3667318/test.log)

**Comment by guwirth** [comment]
Hi @KhvalIvanl,

first of all you should put the report outside root. SonarQube projects are meanwhile (SQ 7.9 LTS) always **multi-language** projects and SonarQube XML plugin tries to read the XML. You seems to use an older SQ version where `sonar.language=c++` is still supported:
```
WARN: File 'C:\test\spdlog-1.x\spdlog-1.x\test.xml' is ignored because it doesn't belong to the forced 
language 'c++'
```
The 'other'  Sensor works like this:
* You first have to define the rules in the WEB UI and restart the server to activate it.
* You can forward reports. Keys in rules must match to definitions.
* see https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis

In case you like to forward issues without rule definitions SQ core provides a new interface you could also use: https://docs.sonarqube.org/latest/analysis/generic-issue/

Hope this helps.

Regards

**Comment by KhvalIvanl** [comment]
Hi @guwirth,

yes, you are right, we are still using old version of SonarQube (as I already mentioned in Related information), so we can't use Generic Import mechanism from SQ 7.2+.

Moving report out of the project root doesn't helped me, rules are defined in SQ (but not in this plugins settings but were imported usin other plugin), keys are matching to definitions. The problem is when I, for example, try to import cppCheck xml report I could see information about import via logs while 'other' import log is empty (see previously attached log file).

**Comment by vhuynh4thalesgroup** [comment]
Hello,
having the same kind of issue with SonarQube 7.9.2 and sonar-cxx 1.3.1.
I cannot find any trace of sonar-cxx sensor for "other" rules.
What kind of logs should be expected ?
How cn we know that the plugin started doing anything ?
@KhvalIvanl, did you find a solution ?
Regards,

**Comment by vhuynh4thalesgroup** [comment]
Hello,
having the same kind of issue with SonarQube 7.9.2 and sonar-cxx 1.3.1.
I cannot find any trace of sonar-cxx sensor for "other" rules.
What kind of logs should be expected ?
How can we know that the plugin started doing anything ?
@KhvalIvanl, did you find a solution ?
Regards,

**Comment by vhuynh4thalesgroup** [comment]
Hello,
having the same kind of issue with SonarQube 7.9.2 and sonar-cxx 1.3.1.
I cannot find any trace of sonar-cxx sensor for "other" rules.
What kind of logs should be expected ?
How can we know that the plugin started doing anything ?
@KhvalIvanl, did you find a solution ?
Regards,

**Comment by vhuynh4thalesgroup** [comment]
Hello,
having the same kind of issue with SonarQube 7.9.2 and sonar-cxx 1.3.1.
I cannot find any trace of sonar-cxx sensor for "other" rules.
What kind of logs should be expected ?
How can we know that the plugin started doing anything ?
@KhvalIvanl, did you find a solution ?
Regards,

**Comment by vhuynh4thalesgroup** [comment]
Hello,
having the same kind of issue with SonarQube 7.9.2 and sonar-cxx 1.3.1.
I cannot find any trace of sonar-cxx sensor for "other" rules.
What kind of logs should be expected ?
How can we know that the plugin started doing anything ?
@KhvalIvanl, did you find a solution ?
Regards,

**Comment by vhuynh4thalesgroup** [comment]
Hello,
having the same kind of issue with SonarQube 7.9.2 and sonar-cxx 1.3.1.
I cannot find any trace of sonar-cxx sensor for "other" rules.
What kind of logs should be expected ?
How can we know that the plugin started doing anything ?
@KhvalIvanl, did you find a solution ?
Regards,

**Comment by vhuynh4thalesgroup** [comment]
Hello,
having the same kind of issue with SonarQube 7.9.2 and sonar-cxx 1.3.1.
I cannot find any trace of sonar-cxx sensor for "other" rules.
What kind of logs should be expected ?
How can we know that the plugin started doing anything ?
@KhvalIvanl, did you find a solution ?
Regards,

**Comment by guwirth** [comment]
@vhuynh4thalesgroup turn debug loggin on, see SonarQube scanner docu or https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information
