### ISSUE TITLE
Reading XML reports with sonar-cxx Quality Profile 

### ISSUE THREAD

**Issue by Gontxu** [SonarOpenCommunity/sonar-cxx#1772]
### Description

I am trying to read XML reports that have been generated by _Cppcheck_ and _Vera++_ in order to display code statistics with SonarQube. For doing so, I created a custom Quality Profile based in _C++ Community_, just adding the rules from _Cppcheck_ and _Vera++_ sensors as specified in [sonar-cxx documentation](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Activate-quality-rules).

The execution of sonar-scanner fails with _The "build-wrapper-dump.json" file was found empty_. As far as I understand, the build-wrapper is aimed for compilation stuff; I don't want SonarQube to compile the code, but just to read the report files, so I do not really get the meaning of the exception and whether the build-wrapper is required to read external XML reports.

 The log file reveals that _.cpp_ files are actually being found and indexed with language _cpp_, but nothing about XML reports appears. What am I missing to be able to read 3rd party reports with sonar-cxx?

Maybe it's a silly question, but I'm totally newbie with both SonarQube and sonar-cxx plugin. Hope somebody can throw some light on this topic.

### LOG file
`11:39:04.502 INFO: Indexing files...
11:39:04.502 INFO: Project configuration:
11:39:04.533 DEBUG: 'libs\RcmScadaObject.ctl' indexed with language 'cpp'
11:39:04.533 DEBUG: 'libs\test_file_nok.cpp' indexed with language 'cpp'
11:39:04.549 DEBUG: 'libs\test_file_ok.cpp' indexed with language 'cpp'
11:39:04.549 INFO: 3 files indexed
11:39:04.549 INFO: Quality profile for cpp: Sonar way
11:39:04.549 INFO: ------------- Run sensors on module MyTestProject
11:39:05.064 INFO: Load metrics repository
11:39:05.079 DEBUG: GET 200 http://localhost:9000/api/metrics/search?f=name,description,direction,qualitative,custom&ps=500&p=1 | time=15ms
11:39:05.111 INFO: Load metrics repository (done) | time=47ms
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.cglib.core.ReflectUtils$1 (file:/C:/Users/ADMINISTRADOR/.sonar/cache/a89f1943fc75b65becd9fb4ecab8d913/sonar-tsql-plugin.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of net.sf.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
11:39:14.299 DEBUG: 'JavaSquidSensor' skipped because there is no related file in current project
11:39:14.299 DEBUG: 'Import external issues report' skipped because one of the required properties is missing
11:39:14.299 DEBUG: 'SonarCSS Metrics' skipped because there is no related file in current project
11:39:14.299 DEBUG: 'SonarCSS Rules' skipped because there is no related file in current project
11:39:14.299 DEBUG: 'C# Properties' skipped because there is no related file in current project
11:39:14.299 DEBUG: 'Import of Checkstyle issues' skipped because there is no related file in current project
11:39:14.299 DEBUG: 'JaCoCoSensor' skipped because there is no related file in current project
11:39:14.299 DEBUG: 'XML Sensor' skipped because there is no related file in current project
11:39:14.315 DEBUG: 'C++ (Community) SquidSensor' skipped because there is no related file in current project
11:39:14.315 DEBUG: 'C++ (Community) RatsSensor' skipped because there is no related file in current project
11:39:14.315 DEBUG: 'C++ (Community) CppCheckSensor' skipped because there is no related file in current project
11:39:14.315 DEBUG: 'C++ (Community) PCLintSensor' skipped because there is no related file in current project
11:39:14.315 DEBUG: 'C++ (Community) DrMemorySensor' skipped because there is no related file in current project
11:39:14.315 DEBUG: 'C++ (Community) CxxCompilerGccSensor' skipped because there is no related file in current project
11:39:14.315 DEBUG: 'C++ (Community) CxxCompilerVcSensor' skipped because there is no related file in current project
11:39:14.315 DEBUG: 'C++ (Community) VeraxxSensor' skipped because there is no related file in current project
11:39:14.315 DEBUG: 'C++ (Community) ValgrindSensor' skipped because there is no related file in current project
11:39:14.315 DEBUG: 'C++ (Community) ClangTidySensor' skipped because there is no related file in current project
11:39:14.315 DEBUG: 'C++ (Community) ClangSASensor' skipped because there is no related file in current project
11:39:14.315 DEBUG: 'C++ (Community) ExternalRulesSensor' skipped because there is no related file in current project
11:39:14.315 DEBUG: 'C++ (Community) CoverageSensor' skipped because there is no related file in current project
11:39:14.315 DEBUG: 'gcov' skipped because one of the required properties is missing
11:39:14.315 DEBUG: 'llvm-cov' skipped because one of the required properties is missing
11:39:14.315 DEBUG: 'cppunit' skipped because one of the required properties is missing
11:39:14.315 DEBUG: 'bullseye' skipped because one of the required properties is missing
11:39:14.315 DEBUG: 'Python Squid Sensor' skipped because there is no related file in current project
11:39:14.346 DEBUG: 'Generic Coverage Report' skipped because one of the required properties is missing
11:39:14.346 DEBUG: 'Generic Test Executions Report' skipped because one of the required properties is missing
11:39:14.346 DEBUG: 'C#' skipped because there is no related file in current project
11:39:14.346 DEBUG: 'C# Tests Coverage Report Import' skipped because there is no related file in current project
11:39:14.346 DEBUG: '[Deprecated] C# Integration Tests Coverage Report Import' skipped because there is no related file in current project
11:39:14.346 DEBUG: 'C# Unit Test Results Import' skipped because there is no related file in current project
11:39:14.346 DEBUG: 'VB.NET' skipped because there is no related file in current project
11:39:14.346 DEBUG: 'VB.NET Tests Coverage Report Import' skipped because there is no related file in current project
11:39:14.346 DEBUG: '[Deprecated] VB.NET Integration Tests Coverage Report Import' skipped because there is no related file in current project
11:39:14.346 DEBUG: 'VB.NET Unit Test Results Import' skipped because there is no related file in current project
11:39:14.346 DEBUG: 'C++ (Community) XunitSensor' skipped because one of the required properties is missing
11:39:14.346 DEBUG: 'C++ (Community) Unit Test Results Import' skipped because there is no related file in current project
11:39:14.346 DEBUG: Sensors : JavaXmlSensor -> HTML -> JaCoCo XML Report Importer -> CFamily -> JavaSecuritySensor -> CSharpSecuritySensor -> PhpSecuritySensor
11:39:14.346 INFO: Sensor JavaXmlSensor [java]
11:39:14.361 INFO: Sensor JavaXmlSensor [java] (done) | time=15ms
11:39:14.361 INFO: Sensor HTML [web]
11:39:14.361 INFO: Sensor HTML [web] (done) | time=0ms
11:39:14.361 INFO: Sensor JaCoCo XML Report Importer [jacoco]
11:39:14.361 DEBUG: No reports found
11:39:14.361 INFO: Sensor JaCoCo XML Report Importer [jacoco] (done) | time=0ms
11:39:14.361 INFO: Sensor CFamily [cpp]
11:39:14.361 INFO: Using build-wrapper output: C:\Users\ADMINISTRADOR\Desktop\MyTestProject\build_wrapper_output_dir\build-wrapper-dump.json
11:39:14.361 INFO: Available processors: 1
11:39:14.361 INFO: Using 1 thread for analysis according to value of "sonar.cfamily.threads" property.
11:39:14.361 DEBUG: Unpacking analyzer to: C:\Users\ADMINISTRADOR\Desktop\MyTestProject\.scannerwork\.sonartmp\2857878780246349335
11:39:15.719 INFO: Load project repositories
11:39:15.734 DEBUG: GET 200 http://localhost:9000/batch/project.protobuf?key=MyProjKey| time=15ms
11:39:15.750 INFO: Load project repositories (done) | time=31ms
11:39:15.750 DEBUG: 'libs/test_file_ok.cpp' generated metadata with charset 'UTF-8'
11:39:15.765 DEBUG: Not enough content in 'libs/test_file_ok.cpp' to have CPD blocks, it will not be part of the duplication detection
11:39:15.875 DEBUG: 'libs/RcmScadaObject.ctl' generated metadata with charset 'UTF-8'
11:39:15.953 DEBUG: 'libs/test_file_nok.cpp' generated metadata with charset 'UTF-8'
11:39:15.968 INFO: 0 compilation units analyzed
11:39:15.999 INFO: ------------------------------------------------------------------------
11:39:15.999 INFO: EXECUTION FAILURE
11:39:15.999 INFO: ------------------------------------------------------------------------
11:39:15.999 INFO: Total time: 25.942s
11:39:16.062 INFO: Final Memory: 21M/79M
11:39:16.062 INFO: ------------------------------------------------------------------------
11:39:16.062 ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: The "build-wrapper-dump.json" file was found empty. Please make sure that:
  * you are using the latest version of the build-wrapper and the SonarCFamily analyzer
  * your compiler is supported
  * you are wrapping your build correctly
  * you are wrapping a full/clean build
	at com.sonar.cpp.plugin.CFamilySensor.execute(CFamilySensor.java:239)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:62)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:387)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:383)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:346)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)`

### sonar-project.properties
```
sonar.projectKey=MyProjKey
sonar.projectName=MyTestProject
sonar.projectVersion=1.0
sonar.sources=libs
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.cfamily.build-wrapper-output=build_wrapper_output_dir
sonar.cxx.cppcheck.reportPath=cppcheck_report.xml
sonar.cxx.vera.reportPath=build/verapp_report.xml
#sonar.cxx.compiler.parser=MSBuild
#sonar.cxx.compiler.reportPath=*.log
#sonar.cxx.compiler.charset=UTF-8

# Added to avoid the failure with sonar.lang.patterns matching c++ and cpp
sonar.cxx.suffixes.headers=.dummy
sonar.cxx.suffixes.sources=.dummy
```

### Related information

* cxx plugin version 1.3.1.1807
* SonarQube version 8.0

Thank you in advance.

**Comment by guwirth** [comment]
Hi @Gontxu,

seems you are trying to use the `CFamily` and `C++ (Community)` plugins side by side. Don't know if this is intended?

The message below is from the commercial CFamily plugin. Please ask in their community: https://community.sonarsource.com/

```
11:39:14.361 INFO: Sensor CFamily [cpp]
11:39:14.361 INFO: Using build-wrapper output: C:\Users\ADMINISTRADOR\Desktop\MyTestProject\build_wrapper_output_dir\build-wrapper-dump.json
```

Regards,

**Comment by Gontxu** [comment]
Hi @guwirth,

I'm trying to use only the `C++ (Community)` plugin. Don't actually know how to disable the influence of `CFamily` so that it is not applied anymore.

**Comment by guwirth** [comment]
Hi @Gontxu,

you have to remove `sonar.cfamily.build-wrapper-output=build_wrapper_output_dir`.
For cfamily you can also set the assigned file extension. Assign a dummy file extension to read the sources with the community plugin only.

Regards,

**Comment by Gontxu** [comment]
Hello @guwirth,

Thank you for your guidelines. By modifying the `sonar-project.properties` as suggested, I managed to run a successful execution. 
```
sonar.projectKey=MyProjKey
sonar.projectName=MyTestProject
sonar.projectVersion=1.0
sonar.sources=libs
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.cxx.cppcheck.reportPath=build/cppcheck_report.xml
sonar.cxx.vera.reportPath=build/verapp_report.xml
sonar.cxx.compiler.parser=MSBuild
sonar.cxx.compiler.reportPath=*.log
sonar.cxx.compiler.charset=UTF-8
sonar.cpp.file.suffixes=.dummy
```

As per the following trace, it looks like the _Cppcheck_ sensor is working properly:
```
12:35:20.655 INFO: Sensor C++ (Community) CppCheckSensor [cxx]
12:35:20.655 INFO: Searching reports by relative path with basedir 'C:\Users\ADMINISTRADOR\Desktop\MyTestProject' and search prop 'sonar.cxx.cppcheck.reportPath'
12:35:20.655 DEBUG: Normalized report includes to '[C:\Users\ADMINISTRADOR\Desktop\MyTestProject\build\cppcheck_report.xml]'
12:35:20.655 DEBUG: Scanner uses normalized report path(s): 'C:\Users\ADMINISTRADOR\Desktop\MyTestProject\build\cppcheck_report.xml'
12:35:20.686 INFO: Parser will parse '1' report file(s)
12:35:20.686 INFO: Processing report 'C:\Users\ADMINISTRADOR\Desktop\MyTestProject\build\cppcheck_report.xml'
12:35:20.686 DEBUG: Parsing 'Cppcheck V2' format
12:35:20.795 DEBUG: 'libs/RcmScadaObject.ctl' generated metadata with charset 'UTF-8'
12:35:20.842 INFO: Added report 'C:\Users\ADMINISTRADOR\Desktop\MyTestProject\build\cppcheck_report.xml' (parsed by: CppcheckParserV2)
12:35:20.842 DEBUG: CXX-CPPCHECK processed = 8
12:35:20.842 INFO: CXX-CPPCHECK processed = 8
12:35:20.842 INFO: Sensor C++ (Community) CppCheckSensor [cxx] (done) | time=187ms
```

But the Vera++ report is ignored. Do you think this might have something to do with the following trace?

`12:35:20.280 DEBUG: 'C++ (Community) VeraxxSensor' skipped because there is no related rule activated in the quality profile`

**Comment by guwirth** [comment]
> But the Vera++ report is ignored. Do you think this might have something to do with the following trace?

Yes, you have to enable the Vera rules in your Quaity Profile first. Vera rules are disabled per default.
