### ISSUE TITLE
How to make PCLint Sensor work with Sonarqube SonarCFamily plugin?

### ISSUE THREAD

**Issue by bloodlee** [SonarOpenCommunity/sonar-cxx#1774]
Sorry, actually, this is not an issue. It's a question from me.

I would like to know if it's possible to make PCLint sensor work with SonarCFamily plugin. 
If the answer is yes, what should I do? May I extract PCLint sensor into a standalone plugin?

Many thanks in advance.

**Comment by guwirth** [comment]
Hello @bloodlee,

SonarQube works like this, that for every language are file extensions defined:
```
file extension => language => sensor => plugin
```
In case of community and SonarCFamily plugin are installed both on the same server they are using the same file extension for a language which results in an error.

What you can do is setting a dummy file extension for the community plugin:
```
sonar.cxx.suffixes.sources=.dummy
sonar.cxx.suffixes.headers=.dummy
```

With this trick it should be possible to read the source files with the SonarCFamily plugin and assign issues with the PCLint sensor.

Regards,

**Comment by bloodlee** [comment]
Thanks for your quick reply, @guwirth . 
I will try the trick in your comment.

**Comment by bloodlee** [comment]
Hi @guwirth ,

Just let you know some update.

I tried your way but it seems not working.
Both sonar-cxx and SonarCFamily provide the Language for C and C++ support. And there are conflicts (at least with SQ 7.9.1).

I commented more code and just kept the PCLint rule repo with issue sensor. Now, they seems can work together. I will do more testing.

The code change is here.
https://github.com/bloodlee/sonar-cxx/commit/329895db4c84e737e7cf3d9bca376429a2506091

Thanks a lot.

**Comment by guwirth** [comment]
Hi @bloodlee,

do you have all three plugins installed c, cxx and SonarCFamily?
If there is a unique assignment of extension to plugin it should work.
You should also get hints in the LOG file.

Regards,

**Comment by bloodlee** [comment]
@guwirth ,
Yes. I have all three installed and the Log did help me a lot to figure out the solution.

One question, what do you mean "a unique assignment of extension to plugin"? One plugin for a language?

Thanks.

**Comment by guwirth** [comment]
Hi @bloodlee,

> what do you mean "a unique assignment of extension to plugin"

Internally there is always: `file extension => language => sensor => plugin`
With all three plugins you have the languages (language keys): `c, c++ and cpp`
You have to assign an extension like .cpp to one of the languages otherwise you get an error message.
See also: https://github.com/SonarOpenCommunity/sonar-cxx/issues/1400

Regards,

**Comment by bloodlee** [comment]
Thanks very much for your messages. I made it work and am doing more testing.
Will let you know if there are new updates.

**Comment by guwirth** [comment]
Hello @bloodlee,

thinking about this I think creating an own plugin is the wrong way. A better solution would be to support both languages.

The sensor is using `.onlyOnLanguage(getLanguage().getKey())` to define the supported language:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/pclint/CxxPCLintSensor.java#L78

There is a second method `onlyOnLanguages` to define more than one language. Without `onlyOnLanguage(s)` all languages are supported.

So another possibility could be calling `onlyOnLanguages("c++", "cpp")`. A more generic way could be to add a new configuration property: `sonar.cxx.pclint.onlyOnLanguages=c++,cpp`.

Maybe we should do this for all sensors? What do you think.

Regards,
