### ISSUE TITLE
Flags to prevent a rule to be triggered

### ISSUE THREAD

**Issue by deadbird99** [SonarOpenCommunity/sonar-cxx#1788]
Hi.

I was searching for a possibility to deactivate some rules for a particular piece of code.

Here is an example. The `cxx:TooLongLine` is a controversial rule, but I try to abide by it whenever possible. But in some rare cases, it can be troublesome. 

In my latest project, I have to compose web pages using pieces of HTML, CSS and SVG pictures in particular. You guessed it: SVG pictures produce very long `const char *` strings, and there are a few of them.

So yes, one of my header files has plenty of `cxx:TooLongLine` violations, and I'm searching for a way to deactivate the rule, *one line at a time*.

I remember, back when I was coding in Java, that there was a inline flag that allowed to deactivate a rule for a specific piece of code, for example (might be wrong):

```
//@deactivate(java:TheRuleToDeactivate)
```

So my question is: is there a way to do something similar with sonar-cxx?

Thanks a lot for your help.

**Comment by guwirth** [comment]
Hi @deadbird99,

please try `//NOSONAR` (https://docs.sonarqube.org/latest/faq/).

Regards,

**Comment by deadbird99** [comment]
I saw this one before, but I found that's a "brutal" way to solve the problem, as it deactivates all the rules, not just the one that's causing the proble.

**Comment by guwirth** [comment]
This https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/ and `//NOSONAR` is all I know.

**Comment by guwirth** [comment]
There are only these solutions:
* turn rule off
* suppress with //NOSONAR
* some static code analyzer use special comments to suppress it

**Comment by deadbird99** [comment]
Pardon me for reopening the issue, but after fiddling around with Sonar exception, I still think sonar-cxx should implement implement a way to deactivate a specific rule of code. //NOSONAR and exception are way too brutal ways.

Thanks in advance ;)

**Comment by guwirth** [comment]
@deadbird99 maybe you can make a proposal how this should work?

How is this working in other languages?
`//@deactivate(java:TheRuleToDeactivate) `: Is this suppressing an SonarQube rule or a rule of an external tool? 
Is this working for all languages/repositories? e.g. `//@deactivate(python:RuleKey) `

**Comment by deadbird99** [comment]
See [here](https://docs.codescan.io/hc/en-us/articles/360012109711-Ignoring-violations)

**Comment by guwirth** [comment]
Hi @deadbird99,

`@SuppressWarnings` is a Java annotation and has nothing to do with SQ (https://www.baeldung.com/java-suppresswarnings). For other compiler / static code analyser there are several other annotation formats to suppress their messages.  On the contrary `//NOSONAR` does not suppress the message creation, it suppresses only to add them to SQ.

Regards,
