### ISSUE TITLE
Valgrind repository disappears when adding the python 2.3 plugin

### ISSUE THREAD

**Issue by Tom3592** [SonarOpenCommunity/sonar-cxx#1794]
### Description

the cxx plugin sonar-cxx-plugin-1.3.1.1807.jar has been installed properly and the valgrind repository is available.
If the sonar-python-plugin-2.3.0.5351.jar is added (.jar file or via marketplace: same result) the valgrind repository disappears.

### Steps to reproduce the problem

the steps required to reproduce the problem

1. docker initialization:

`docker run -d --name sonarqube   -p 9000:9000   -e sonar.jdbc.username=sonar   -e sonar.jdbc.password=sonar   -v sonarqube_conf:/opt/sonarqube/conf   -v sonarqube_extensions:/opt/sonarqube/extensions   -v sonarqube_logs:/opt/sonarqube/logs   -v sonarqube_data:/opt/sonarqube/data   sonarqube`

2. install the cxx plugin:

```
$ sudo docker cp ./sonar-cxx-plugin-1.3.1.1807.jar sonarqube:/opt/sonarqube/extensions/plugins/sonar-cxx-plugin-1.3.1.1807.jar
 $ sudo docker restart sonarqube
```
=> all the plugins are available (valigrind included)

3. install the python  plugin:

```
sudo docker cp ./sonar-python-plugin-2.3.0.5351.jar sonarqube:/opt/sonarqube/extensions/plugins/sonar-python-plugin-2.3.0.5351.jar
 sudo docker restart sonarqube
```

=> valgrind is no longer preset :

```
PC-lintC++ (Community)1.9k
Clang-TidyC++ (Community)1.1k
Compiler-VCC++ (Community)888
CppcheckC++ (Community)516
PylintPython370
RATSC++ (Community)
313Compiler-GCCC++ (Community)
230Clang-SAC++ (Community)111
SonarAnalyzerPython88
c++ SonarQubeC++ (Community)28
```

### Known workarounds

it is possible the retrieve the last configuration (i.e. get valgrind) deleting the python plugin.

### LOG file

no warning in the log file:

```
docker logs sonarqube | grep -i community

2020.01.22 10:08:01 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin C++ (Community) / 1.3.1.1807 / 21428260155e9662780ff609319a9846d3c485af
2020.01.22 10:08:20 INFO  web[][o.s.s.p.p.PlatformLevelStartup] Running Community Edition
2020.01.22 10:08:25 INFO  ce[][o.s.c.c.ComputeEngineContainerImpl] Running Community edition
```

### Related information

* cxx plugin version : cxx-plugin-1.3.1.1807
* SonarQube Version 7.9.1 (build 27448)

**Comment by guwirth** [comment]
Hi @Tom3592 ,

I have not really an idea why this happens? Normally each repository has an own independent key.
Why you are installing the Python plugin? Though it's part of the SQ package?

Regards,

**Comment by Tom3592** [comment]
Hi,
thank you for your answer.
We want to work with only the cxx community and python plugins, in their latest releases (compliant with SonarQube 7.9.x).

So, from the default SonarQube image, we had to:

- remove all the plugins (old python plugin release)
- install the cxx plugin
- install the newest python plugin release

**Comment by guwirth** [comment]
Hi @Tom3592,

at the moment we are testing always the SQ installation "as is" with our plugin on top:
tested and released for SonarQube 6.7 LTS with Java 8 and SonarQube 7.9 LTS with Java 11. 

Don't know if there are "other" dependencies: OS, Java version, SQ API version, ...

I can only think of two points:
* overlapping repository / rule keys?
* too many rules (think there is a 10k limitation for the REST API)

Regards,

**Comment by prunier** [comment]
Hello, FYI I've re-installed SonarQube (version 7.9.2 (build 30863) with (only) the cxx community _and_ python plugins.
![rules](https://user-images.githubusercontent.com/5794315/73549953-f741be80-4443-11ea-9f67-d622ebc05d6b.png)
![plugins](https://user-images.githubusercontent.com/5794315/73550058-2fe19800-4444-11ea-9de1-1bda2fd056be.png)

Tom

**Comment by prunier** [comment]
...and if the python plugin is removed, the snapshot below shows that all the expected repositories are now available (eg valgrind):
![rules_without_py](https://user-images.githubusercontent.com/5794315/73550720-62d85b80-4445-11ea-8808-1554c818a510.png)

Thank you very much for any help.

**Comment by guwirth** [comment]
Hi @Tom3592,

Looking to the compatibility matrix they recommend v2.4: https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/

If I have some time I will try to reproduce it on one of our test servers. 

Regards,

**Comment by guwirth** [comment]
Or maybe they show only the top 10 repositories in this view?

**Comment by guwirth** [comment]
Please try to search for Valgrind:
![grafik](https://user-images.githubusercontent.com/6077367/73615587-703e4300-4609-11ea-9ec8-0f75139e433c.png)

**Comment by prunier** [comment]
OK, I have been too quick using the interface.
I'll try to add more checks next time...
Thank you for your time and checks.
