### ISSUE TITLE
API api/rules/search does not provide the expected rules (example with rats)

### ISSUE THREAD

**Issue by Tom3592** [SonarOpenCommunity/sonar-cxx#1795]
### Description

The Web api/rules/search seems not working on a given Quality profile.

### Steps to reproduce the problem

1. Put only one rule in a quality profile
example: the rule “rats:_cprintf”
I can see this (severity MAJOR) rule in the browser, clicking only in the name of the quality profile:
http://localhost:9000/coding_rules?activation=true&qprofile=AW_M90DXwqWeLO4WzNs3

if I do a backup of the quality profile, I can check that the XML file contains only this rule.

2. use the Rest api "api/rules/search"

put this commande in the brwoser (changing the profile key...):
http://localhost:9000/api/rules/search?qprofile=AW_M90DXwqWeLO4WzNs3&name

…and this command displays a lot of rules …but not the expected rule (“rats:_cprintf”)

### Expected behavior

As the XML profile output, the Rest api should display only one rule.

### Actual behavior

The current Api rest displays a lot of rules of the qualty profile .

### Known workarounds

XML profile file output.

### LOG file

no error in the log traces:

```
$ docker logs sonarqube_sgs | grep -i community

2020.01.22 11:10:24 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin C++ (Community) / 1.3.1.1807 / 21428260155e9662780ff609319a9846d3c485af
2020.01.22 11:10:42 INFO  web[][o.s.s.p.p.PlatformLevelStartup] Running Community Edition
2020.01.22 11:10:47 INFO  ce[][o.s.c.c.ComputeEngineContainerImpl] Running Community edition
```

### Related information

* cxx plugin version 7.9.2
* SonarQube version 1.3.1

**Comment by guwirth** [comment]
Hi @Tom3592 

reading the docu you need parameter qprofile & activation

**GET api/rules/search**
* **activation**: Filter rules that are activated or deactivated on the selected Quality profile. Ignored if the parameter 'qprofile' is not set. 
* **qprofile**: Quality profile key to filter on. Used only if the parameter 'activation' is set.

Regards,
