### ISSUE TITLE
V1.3.2 release 

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1805]
Hi, like to release 1.3.2. Please review and test (use snapshot link)...

___

We are pleased to announce the SonarQube C++ Community Plugin version 1.3.2.
See lists below for features added and bugs fixed in this release.

# SonarQube compability

- tested and released for **SonarQube 6.7 LTS** with Java 8 and  **SonarQube 7.9 LTS** with Java 11
   - see also [SonarQube compatibility matrix](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix)
- [Installation Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Installation)
- [Upgrade Instructions](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-Instructions)

# Enhancements

- improved **JSON Compilation Database** support:
  - support -isystem -iquote -isystem -idirafter #1802 #1799 #1215
  - support relative paths #1797 #1790 #1791
  - support argument arrays #1789 #1745
- **Cppcheck 1.90** support #1783 #1778
- duplicate issues with different relative paths resulting in same absolute path are only added once now #1776 #1777
- **customRules** no more supported #1781 #1548
- **cxx-lint** no more supported #1780
- refactoring #1804

# Bugfixes

- fix syntax highlighting for Raw strings #1803 #1768
- parser fix: improved literal-operator-id support #1798 #1785
- fix multi-values/property warning #1782 #1775

# Known Issues

For an up to date list of known issues see the issue tracker.
- not tested with Java 9, 10 and 12
- [Ensure that a rule is enabled](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Activate-quality-rules) if you get no results. In new SQ versions the default profile is read-only. The cxx plugin does not enable rules for external tools per default.
- Starting with SQ 6.2 there are some new metrics and some are no more available. Please have a look to the SonarQube release notes.
- `duplicated_lines_density` values are different with SQ 7.5
- project's duplication density value will likely rise with SQ 7.8 (SONAR-12188)
- [test execution metrics](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-test-execution-metrics) are not supported
- The [Cppcheck plugin](https://github.com/SonarQubeCommunity/sonar-cppcheck) is deprecated and not working in parallel to this plugin. This plugin provides an own Cppcheck sensor.
- C plugin and JSON Compilation Database support are experimental only

# Thanks ....

go to all contributors (in alphabetical order):

@guwirth 
@tisoft 

... and all people which were active on the issue tracker!

**Comment by tisoft** [comment]
Looking good to me!

Tested it in Sonar 7.9.1 with our C++ project.
