### ISSUE TITLE
Next version will be a bigger one: V2.0

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1808]
- [X] ~~SQ 7.9 LTS support (no more support older versions)~~
- [X] SQ 8.x LTS support
- [X] remove c plugin, move it to cxx plugin
- [X] side by side support with CFamily plugin
- [x] report sensor support for CFamily
- [X] use OpenJDK 11
- [X] refactoring / remove deprecated APIs
- [x] C++20 support
- [x] improve wiki 

Any comments?

**Comment by kgiloo** [comment]
hi, what about support of sonarqube 8.x LTS?

**Comment by guwirth** [comment]
@kgiloo yes for sure, next LTS will be supported. Will add it...

**Comment by jmecosta** [comment]
we need documentation regarding upgrading from c++ to cxx key. So profiles have to exported keys replaced and imported back! its possible however this needs to be in bold letters otherwise users will loose some work

**Comment by guwirth** [comment]
@jmecosta yes you are right. Will be a longer release notes with 2.0...

**Comment by sourcedelica** [comment]
Any update on this?  8.x LTS is 8.4.1 now and we're stuck on 7.4.x because we need this plugin.

**Comment by guwirth** [comment]
@sourcedelica plan was to support next 8.x LTS and no intermediate versions.

**Comment by sourcedelica** [comment]
That’s great!  We’d like to go to the latest 8.x as soon as possible.

**Comment by p-vernaeckt** [comment]
@sourcedelica [don't rejoince too quickly...](https://www.sonarqube.org/roadmap/#:~:text=The%208.,%2C%20integration%2C%20and%20Python%20analysis.)

just like you I'm waiting for @guwirth to support SonarQube 8.x, and having to wait that much makes me despair.

**Comment by sourcedelica** [comment]
Ahh - thanks.  I didn't realize 8.x LTS was so far out.

**Comment by p-vernaeckt** [comment]
However, @guwirth told us 3 messages ago that the plan "was", not "is" to support only LTS versions...^^

**Comment by guwirth** [comment]
is = was = will be :-)

Effort to maintain versions between LTS versions is very high. SonarSource is typically changing/deprecating a lot of APIs. Other point is, that most companies are using anyway the LTS only. Currently we are working on the 2.0 of this plugin. This is mainly refactoring/ cleaning up. If this is done we can try to make it compatible with 8.x. 

Other hint: This is an open source plugin, you are all invited to contribute :-) ...

**Comment by guwirth** [comment]
New version 2.0 will support 8.x LTS only. There are too many changes in API / REST API to support both versions.

**Comment by guwirth** [comment]
First tests with SQ 8.6 successful. The version supports also C++20.

Most likely the next SonarQube version 8.7 will be the next LTS version. If the current release cycle is kept, this will be released on January 15, 2021. In the past, it was quite good to wait for the first bug fixes with SQ 8.7.1 LTS. Typically, this first patch appears 2 to 3 weeks after the release (around February 5). First tests can be done with the already available SQ 8.6. No major changes are expected anymore.

**Comment by guwirth** [comment]
Current version is supporting SonarCFamily #2018 now.

**Comment by guwirth** [comment]
Hi,

short update:
* we like to provide a first beta of cxx plugin 2.0 together with the 8.7 LTS release
* final version of 2.0 is planned with first 8.7.1 LTS service release
* it looks like cxx plugin 2.0 is compatible with 7.9 LTS and 8.7 LTS (to be verified with final versions)
* most parts of the wiki are up to date

Regards

**Comment by guwirth** [comment]
@jmecosta 

> we need documentation regarding upgrading from c++ to cxx key. So profiles have to exported keys replaced and imported back! its possible however this needs to be in bold letters otherwise users will loose some work

done https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-the-Plugin
