### ISSUE TITLE
How to check invalid iterator?

### ISSUE THREAD

**Issue by NickYang1988** [SonarOpenCommunity/sonar-cxx#1817]
### Description

I test the code below, and I wanna know how to check if `it` is valid.

```cpp
void test4(){
    //
    std::map<int, Data *> my_map;
    my_map.insert(std::make_pair(10, new Data(1)));
    my_map.insert(std::make_pair(20, new Data(2)));
    my_map.insert(std::make_pair(30, new Data(3)));
    my_map.insert(std::make_pair(40, new Data(4)));
    auto it = my_map.find(50);
    if(it != my_map.end()){
        it = my_map.end();
        it->second->getAge();
    }
    it->second->getAge();
}
```

### Expected behavior

The sonarqube can let me know the `it` may be invalid, let me fix this code with `return;`

### Actual behavior

sonar-cxx plugin cannot check it out.

![image](https://user-images.githubusercontent.com/3690738/75869813-1669ac80-5e45-11ea-96ad-bf2885465753.png)

* cxx plugin version? `1.3.2`
* SonarQube version? `Community Edition  8.1`

Could someone help me to let me know the result is OK or my mistake?

Thanks a lot.

**Comment by guwirth** [comment]
Hi @NickYang1988,

in the past we had own static code analysis checks in the plugin. We removed them all and make the recommendation to use external tools instead: cppcheck, clang, ...

Regards,

**Comment by NickYang1988** [comment]
@guwirth Thanks for your quick reply, I use clang-tidy and cppcheck, but still not find this bad smell, could you let me know which external tool can find this type with your experience?

Here are my opening check rules.
![image](https://user-images.githubusercontent.com/3690738/75946157-43ff3600-5ed7-11ea-92e9-b7ed8ff9bd7a.png)

Regards.
