### ISSUE TITLE
Import issues from infer

### ISSUE THREAD

**Issue by Kinokin** [SonarOpenCommunity/sonar-cxx#1851]
Is there any chance to import issues found by infer : https://github.com/facebook/infer

**Comment by guwirth** [comment]
Hello @Kinokin,

yes that should be possible. 
1. you can write an own sensor, sample:
  * https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/cppcheck
  * https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/rats
2. you can use the `sonar.cxx.other` sensor
  * define rules: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis
  * import XML reports: `sonar.cxx.other.reportPath`
 3. use the generic issue sensor: https://docs.sonarqube.org/latest/analysis/generic-issue/

Regards,
