### ISSUE TITLE
Import of compiler messages: first line of files with BOM is ignored

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1859]
In case the LOG file is a file with BOM the first line can't be read. This is a problem if the first line contains a warning (which is typically not the case).

Todo: Handle LOG files with BOM, possible solutions:
- ignore BOM
- interpret BOM and use it instead of charset

https://github.com/google/gdata-java-client/blob/master/java/src/com/google/gdata/util/io/base/UnicodeReader.java

**Comment by ysiw** [comment]
C/C++ source files with BOM also report `C++ Parser can't read code. Declaration is skipped.` for line 1.

![image](https://user-images.githubusercontent.com/18527938/83872494-b09f0080-a764-11ea-9c00-2d629b9ac9d9.png)

**Comment by guwirth** [comment]
Hello @ysiw,

that seems to be a different issue. The one here is about parsing reports, your one about parsing source code files. 

Seems you have to set the correct `sonar.sourceEncoding`?
https://docs.sonarqube.org/latest/analysis/analysis-parameters/

Regards,

**Comment by guwirth** [comment]
SQ API
https://github.com/SonarSource/sonarqube/blob/branch-8.6/sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/filesystem/CharsetDetector.java
