### ISSUE TITLE
SonarQube 8.x support?

### ISSUE THREAD

**Issue by henjovr** [SonarOpenCommunity/sonar-cxx#1862]
**Request for info:**

SonarQube is currently at version 8.3 (not yet LTS).
What is the strategy for this plugin? Will only LTS versions be supported? 
Or is support for 8.x planned as well?

If so, is this strategy documented somewhere?

**Comment by guwirth** [comment]
Hi @henjovr,

most of the people seems to use the commercial SQ version which is always the latest LTS. The other versions between two LTS has typically a lot of API changes and the effort to maintain it is high.

Therefore no: It is not planned to support non-LTS versions.

Regards,

**Comment by Necrontyr** [comment]
I'm using 8.3 presently for my code and would appreciate support, does it not make sense to support 8.X up and until a release 8 LTS version is made public ?

**Comment by guwirth** [comment]
@Necrontyr did you try it with released 1.3 plugin? Maybe it's working?
