### ISSUE TITLE
How could I use sslr-cxx-toolkit on my project to retrieve functions of a .c file?

### ISSUE THREAD

**Issue by digeo** [SonarOpenCommunity/sonar-cxx#1905]
The sslr-cxx-toolkit is really nice.
I would like to ask you: could I use it in my project in order to retrieve all the functions of a .c file?
Could you please provide me a code snippet as a starting point?
Thank you in advance!

**Comment by guwirth** [comment]
Hi @digeo,

the SSLR toolkit is only to verify the parser (created AST) and create XPath checks. The code is here https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/sslr-cxx-toolkit/src/main/java/org/sonar/cxx/toolkit. 

You can create an XPath for function declarations and add it as a new check. 
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Create-Custom-Rules

Regards,
