### ISSUE TITLE
How to get code coverage shown in SonarQube after Bamboo CI job

### ISSUE THREAD

**Issue by root-df** [SonarOpenCommunity/sonar-cxx#1932]
Hello,

I hope you are well and safe.

I have been working on trying to get report files in SonarQube for some time but didn’t succeed. 
I need assistance on the following issue please.

I am working on a C++ code and I have a Bamboo plan with a job that basically:
- Checks out the Git repo in Bitbucket
- Scans C++ code (Sonar for Bamboo plugin)
And I would like to have code coverage in SonarQube.
I have 2 gcov files in a reports/gcov/ directory in the code repo.
I included sonar.cxx.coverage.reportPath=reports/gcov/report.gcov in my sonar-project.properties files (which also sits in the project root).

Here are the logs: 
build	25-Aug-2020 14:45:24	INFO: Searching coverage reports by path with basedir 'D:\BAMBOO-HOME\xml-data\build-dir\APP' and search prop 'sonar.cxx.coverage.reportPath'
build	25-Aug-2020 14:45:24	INFO: Searching for coverage reports '[reports/gcov/report.gcov]'
build	25-Aug-2020 14:45:24	INFO: Coverage BaseDir 'D:\BAMBOO-HOME\xml-data\build-dir\APP' 
build	25-Aug-2020 14:45:24	INFO: Parser will parse '1' report file(s)

But unfortunately I still get 0% code coverage in SonarQube.

* cxx plugin version 1.3.1
* SonarQube version 7.9.1

Your help, guidance and suggestions on this matter would be highly appreciated!

**Comment by guwirth** [comment]
Hi @root-df,

please look here first:
* to get more info  https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information
* the source file should be indexed
* should find the report
* path of issues must match https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-code-coverage-metrics

Regards,
