### ISSUE TITLE
Can you use generic code coverage information when writing a new rule?

### ISSUE THREAD

**Issue by eraytufan** [SonarOpenCommunity/sonar-cxx#1941]
Hi all,
I’m trying to create a rule for a function and check if the function has been covered or not. If none of the lines are covered in the function, I want to create an issue. In SQ, which lines are covered can be seen but can you access the same information when writing a new rule check? Does such method exists in the library and how can I do it?

Thanks in advance.

**Comment by guwirth** [comment]
Hi @eraytufan,

> Does such method exists in the library and how can I do it?

With this plugin not, but in general you can write an own plugin doing this. The right place to ask is https://community.sonarsource.com/.

But wondering what the value of such a check is? You can already set a limit for minimal expected coverage and focus on new code only. Checking this e.g. at the end of a sprint is normally sufficient...

Regards,
Günter

**Comment by eraytufan** [comment]
Okay, thanks. Code coverage check is very useful, but in a big project there are some functions that hasn't been tested or will be tested later on with the integration test but missed, and finding non-covered functions or unused functions becomes a pain because file might have a good coverage in the end. Therefore, we wanted to implement such rule because it will show as code smell/bug and it will be easier to find those functions.

**Comment by guwirth** [comment]
Hi @eraytufan,

think is better to discuss this with SonarSource. If this metric makes sense it should be part of all languages and not only C++?

SonarQube is typically speaking about unit tests and coverage of the unit tests. Integration, product, system test is another level and I think here you wanna see more if a requirement or use case is tested/covered?

Regards,

**Comment by eraytufan** [comment]
First I thought there would be an API function that gives the coverage result and I asked to Sonarsource, and the reply was that if you want to write such a rule, the plugin has to support it. I don't know how to do add this functionality to the plugin.

We wanted to find uncovered functions by tests and add a rule for that with some specifications (such as function has to be longer than 30 lines, or check if all conditions are covered). I don't think adding it as a metric will cover our needs, because then we won't be able to customize the rule.
