### ISSUE TITLE
Possible to use sonar-cxx for unit test reports and cfamily for code coverage analysis?

### ISSUE THREAD

**Issue by capSAR273** [SonarOpenCommunity/sonar-cxx#1947]
### Description

I'm working with a C++ project that was originally using the SonarQube cfamily c++ plugin for report processing. While running sonar-scanner we can get code smell data/bugs, but no unit test coverage because the generic report format was not being read in. We started using sonar-cxx to process the Google Test reports, and it would work, except we would lose the smells and bug information.

### Current Setup

Properties file:
sonar.cfamily.build-wrapper-output=*build-wrapper log output*
sonar.sourceEncoding=UTF-8
sonar.cxx.coverage.reportPath=unittestcoverage.xml
sonar.tests=*unit test folder location*
sonar.language=**c++**
sonar.cxx.xunit.reportPath=gtestreport.xml
sonar.cfamily.threads=4

* cxx plugin version? 1.3.2
* SonarQube version? 6.7.5

Some log output:

`16:45:54.656 INFO: Sensor C++ (Community) XunitSensor [cxx]
16:45:54.656 DEBUG: Root module imports test metrics: Module Key = '[key=*projectName*]'
16:45:54.658 DEBUG: Normalized report includes to '[PATH\gtestreport.xml]'
16:45:54.658 DEBUG: Scanner uses normalized report path(s): 'PATH\gtestreport.xml'
16:45:54.675 INFO: Parser will parse '1' report file(s)
16:45:54.683 INFO: Processing report 'PATH\gtestreport.xml'
16:45:54.684 DEBUG: Transformation skipped: no xslt given
16:45:54.697 INFO: Parsing 'xUnit' format
16:45:54.706 INFO: Sensor C++ (Community) XunitSensor [cxx] (done) | time=50ms`

--the scanner processes the C++ files now for static analysis--

To me it looks like sonar-cxx looks at the unit test execution report (gtestreport.xml), but not the coverage one (named unittestcoverage.xml)

If I use sonar.language=cpp , it will use the cfamily scanner to process the static analysis reports only. Setting it to c++ will use sonar-cxx to process the unit test results only. I can't get both to perform their own functions to create a full report for SonarQube.

Is this possible? Thank you for your plugin, it has been very helpful. If I can provide more information please let me know.

**Comment by guwirth** [comment]
Hi @capSAR273,

the cxx plugin and cfamily c++ plugin handle both the C++ programming language but have to use different plugin and language keys to run side by side (see #1784). Currently you can't mix them. You have to use completely the one or the other.

The idea is to change this with V2.0. There we like to extend the sensors to support the language keys c++, cpp and c.
In case you like to patch the V1.3 you have to change `onlyOnLanguage`:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master-1.3.3/cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/CxxCoverageSensor.java#L100
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master-1.3.3/cxx-sensors/src/main/java/org/sonar/cxx/sensors/tests/xunit/CxxXunitSensor.java#L68

Regards,
