### ISSUE TITLE
allow underscore character in clang-tidy rules

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#1951]
from @elviiix, #1949

Can you allow underscore character in clang-tidy rules, it's allowed there by clang-tidy itself and warnings not importing in SonarQube was rather unexpected.

```
--- a/cxx-sensors/src/main/java/org/sonar/cxx/sensors/clangtidy/CxxClangTidySensor.java
+++ b/cxx-sensors/src/main/java/org/sonar/cxx/sensors/clangtidy/CxxClangTidySensor.java
@@ -101,7 +101,7 @@ public class CxxClangTidySensor extends CxxIssuesReportSensor {
                 ruleId = txt.substring(i + 1, txt.length() - 1);
                 break;
               }
-              if (!(Character.isLetterOrDigit(c) || c == '-' || c == '.')) {
+              if (!(Character.isLetterOrDigit(c) || c == '-' || c == '.' || c == '_')) {
                 break;
               }
             }
-- 

```

**Comment by guwirth** [comment]
@elviiix
* I had a look to Clang-Tidy, seems they do not use underscore (https://clang.llvm.org/extra/clang-tidy/checks/list.html)? Why do you need it?
* looking in the SQ code of RuleKey.java their seems to be no limitation for key name?

**Comment by elviiix** [comment]
For custom rule.
I had a rule mentioning size_t. It was successfully imported and activated in SonarQube, and then during log processing warning with this rule was left out and not imported in SonarQube project.
Underscore is quite common character in identifiers (and probably it would be good to at least inform somehow that warning was left out due to naming problems even with other characters).

**Comment by guwirth** [comment]
@elviiix means rule is: `file:line:column: warning: text [size_t]`?

> and probably it would be good to at least inform somehow that warning was left out due to naming problems even with other characters

To detect a warning parser is looking for `[...]` at the end. `[` or ` ]` could be also part of the text before the rule id. How would you like to detect "ignored line"?

**Comment by elviiix** [comment]
> To detect a warning parser is looking for `[...]` at the end. `[` or ` ]` could be also part of the text before the rule id. How would you like to detect "ignored line"?
Can't say for sure, but I think if you break out due to invalid character in rule name:
```
-              if (!(Character.isLetterOrDigit(c) || c == '-' || c == '.')) {
+              if (!(Character.isLetterOrDigit(c) || c == '-' || c == '.' || c == '_')) {
-->               break;
               }
```
it makes sense to issue warning at least.

**Comment by guwirth** [comment]
@elviiix I have a solution but without warning => #1952

Warning:
* still don't know how many errors/warnings exist without rule id. For all of them you would get a warning?
   sample: `This is a warning.`
* could be also a ] at the end which is part of the text (without rule id)
   sample: `Don't use ]`

In which cases should there be a warning?
What is the warning: `error/warning without rule id?`

**Comment by elviiix** [comment]
Not 100% sure, but looks ok for me.
