### ISSUE TITLE
Clang-Tidy: How to modify option value “NestingThreshold” with “readability-function-size” rule

### ISSUE THREAD

**Issue by FabienLafargue** [SonarOpenCommunity/sonar-cxx#1962]
Hi,

As the title of the topic indicate, I would like to modify the option value of a rule but I don’t find a way to do it. Concerning the rule, here is the description:
Rule repository = Clang-Tidy (C (Community))
Rule name = readability-function-size
![temp](https://user-images.githubusercontent.com/58036994/96150992-3b5dec00-0f0b-11eb-92c5-b9a7c96d57e3.png)

The “NestingThreshold” in red is the option I would like to activate.
To do that I have tried in Administration>Configuration>C(community)>Clang-Tidy custom rules, to put this :
![temp1](https://user-images.githubusercontent.com/58036994/96150974-36993800-0f0b-11eb-94bd-27015694160c.png)

But it dosen’t change anything when I run the analysis.

For your information I’m using:

    SonarQube 7.7;
    Sonar-scanner-cli-4.2.0.1873-windows;
    sonar-c-plugin-1.3.0.1746.jar

Sincerely,

Fabien Lafargue

**Comment by guwirth** [comment]
Hello @FabienLafargue,

The cxx plugin is reading only the resulting report from Clang-Tidy. You have to configure Clang-Tidy:

https://clang.llvm.org/extra/clang-tidy/
```
  --config=<string>              -
                                   Specifies a configuration in YAML/JSON format:
                                     -config="{Checks: '*',
                                               CheckOptions: [{key: x,
                                                               value: y}]}"
                                   When the value is empty, clang-tidy will
                                   attempt to find a file named .clang-tidy for
                                   each source file in its parent directories.
```
Sample: https://github.com/microsoft/clang-tools-extra/blob/master/test/clang-tidy/readability-function-size.cpp

Hope that helps.

Regards,

**Comment by FabienLafargue** [comment]
Hi Gunter,

Thanks for your help, but I'm not sure to know where I can put these instructions. In the sonar.properties file ?

Regards,

Fabien

**Comment by guwirth** [comment]
Hi @FabienLafargue,

The cxx is not executing external tools, you are doing this somewhere in your build chain. Add it there to the command line or add a .clang-tidy file to your folder. For details how to use Clang-Tidy their forum is the better place to ask. 

Regards,

**Comment by FabienLafargue** [comment]
Thanks for the answer. Do you know if there is a way to evaluate the nesting level (without this step in the compilation ), on the sonarqube interface ?

**Comment by guwirth** [comment]
> Do you know if there is a way to evaluate the nesting level (without this step in the compilation ), on the sonarqube interface ?

@FabienLafargue no there is no possibility. This is because SQ only reads the resulting report of the tool and does not execute the tool itself.

**Comment by FabienLafargue** [comment]
So I have a report with a nesting threshold warning. How can I read it with sonarqube now ?

**Comment by guwirth** [comment]
Hi @FabienLafargue,  https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers#clang-tidy

**Comment by FabienLafargue** [comment]
Hi Günter, 

Thanks for your support, I have now a report contening the readability-function-size warnings. I put the data bellow in a ".txt" in a sonarqube directory. And after, I add the path of this ".txt" in "sonar.cxx.clangtidy.reportPath". But when I start a sonarscanner this report isn't take into account...

`` C:\...\main.c:1137:13: warning: function 'rl_setCommand' exceeds recommended size/complexity thresholds [readability-function-size]
static void rl_setCommand(char* commandLine)
            ^
C:\...\main.c:1147:4: note: nesting level 4 starts here (threshold 3)
                        {
                        ^
C:\...\main.c:1160:4: note: nesting level 4 starts here (threshold 3)
                        {
``

**Comment by guwirth** [comment]
Hi @FabienLafargue,

have a look into the scanner log file.
* Mostly it a also help to turn debug info on: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information)
* Path on report must fit to index source files: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues

Regards,

**Comment by FabienLafargue** [comment]
Everything is working, thanks for your support !

**Comment by guwirth** [comment]
@FabienLafargue good to hear...
