### ISSUE TITLE
The pclint report

### ISSUE THREAD

**Issue by Lenegred** [SonarOpenCommunity/sonar-cxx#1983]
This is a question for external analyzer of PC-lint.

### Description

The project had imported the xml report,but I can not get any info at my Sonar platform.
The xml report has 5 properties,e.g.'file' 'line' 'type' 'code' 'desc'.
I wander if the Sonar need some other keyword?

### Version
The cxx version is 1.3.3.
The Sonar platform is 8.3.1.

Anyone can give me some advice?Please.

**Comment by guwirth** [comment]
Hello @Lenegred,

please have a look here:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers#pc-lint
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues

If there are still problems turn debug info on and see if you get some more hints:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

Regards,

**Comment by guwirth** [comment]
@Lenegred I saw you are using 8.x which is not tested up to now (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix)

**Comment by Lenegred** [comment]
@guwirth Hello,
I had resovled the question with you tips.
Thank you very much!!!
