### ISSUE TITLE
Storing measures on folders or modules is deprecated. Provided value of metric 'CXX-SQUID' is ignored.

### ISSUE THREAD

**Issue by kalgary** [SonarOpenCommunity/sonar-cxx#2024]
### Description
Cxx metrics with a multi-modules configuration are not available on Sonarqube.

### Steps to reproduce the problem
I have created a "main" property file:
```sonar.projectKey=multilaguange
sonar.projectName=multilaguange
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8

sonar.lang.patterns.c=-
sonar.lang.patterns.objc=-

# Modules list
sonar.modules=java-api,awesomecplus 
```

the modules configuration is in multiple properties files in the root folders of the module subfolders: e.g. awesomecplus

```sonar.projectKey=awesomecplus
sonar.projectName=awesomecplus
sonar.projectVersion=12.7.0
sonar.working.directory=.scannerwork

# Ignore c and objc lang pattern, only use c++ ruleset
sonar.lang.patterns.c=-
sonar.lang.patterns.objc=-
sonar.language=c++

# Project directories for base, source and include files
sonar.sources=aa.cpp,cache.cpp,proc.cpp,query.cpp,regexp.cpp,srvcon.cpp,trace.cpp,ucudb.cpp,aa.h,cache.h,cliqry.h,db_api.h
sonar.cxx.includeDirectories=,shared-c,/shared-c,/shared-c,shared-c/kernel,/shared-c/kernel,shared-c/_FsEvent
sonar.cxx.FileHeader=%
sonar.cxx.suffixes.sources=.c,.cpp,.C
sonar.cxx.suffixes.headers=.h,.H,.hpp

# Encoding of the source code.
sonar.sourceEncoding=UTF-8

#Add Cpp-check report
sonar.cxx.cppcheck.reportPath=awesomecplus-cppcheck-report.xml
```
SonarQube version: Community EditionVersion 8.1
SonarScanner 4.5.0.2216
C++ (Community) 1.3.2.1853 (cxx)

Cppcheck successfully creates a report XML:
```<?xml version="1.0" encoding="UTF-8"?>
<results version="2">
    <cppcheck version="2.3 dev"/>
    <errors>
        <error id="danglingLifetime" severity="error" msg="Non-local variable &apos;pStmnt&apos; will use pointer to local variable &apos;select_virt_tab&apos;." verbose="Non-local variable &apos;pStmnt&apos; will use pointer to local variable &apos;select_virt_tab&apos;." cwe="562" hash="12792016698167352556">
            <location file="aa.cpp" line="9487" column="5"/>
            <location file="aa.cpp" line="9475" column="10" info="Variable created here."/>
            <location file="aa.cpp" line="9487" column="14" info="Array decayed to pointer here."/>
        </error>
 </errors>
</results>
```

### Expected behavior
Issues are visible on Sonarqube.

### Actual behavior

WARN: Metric 'comment_lines_data' is deprecated. Provided value is ignored.

**WARN: Storing measures on folders or modules is deprecated. Provided value of metric 'CXX-SQUID' is ignored.**
INFO: Sensor C++ (Community) SquidSensor [cxx] (done) | time=5144ms
INFO: Sensor C++ (Community) CppCheckSensor [cxx]
INFO: Searching reports by relative path with basedir '/root/awesomecplus' and search prop 'sonar.cxx.cppcheck.reportPath'
INFO: Parser will parse '1' report file(s)
INFO: Processing report '/root/awesomecplus/awesomecplus-cppcheck-report.xml'
INFO: Added report '/root/awesomecplus/awesomecplus-cppcheck-report.xm' (parsed by: CppcheckParserV2)
**INFO: CXX-CPPCHECK processed = 411**
**WARN: Storing measures on folders or modules is deprecated. Provided value of metric 'CXX-CPPCHECK' is ignored.**

Metrics are not loaded on the server.

### Related information
Analysis of each single module separately works properly, violations in the cppcheck report are visible in the Sonoarqube issues.

**Comment by guwirth** [comment]
Hello @kalgary,

> WARN: Storing measures on folders or modules is deprecated. Provided value of metric 'CXX-CPPCHECK' is ignored.

the message is from SQ core. Starting with SQ 8.x they are no more supporting modules.
The cxx plugin 1.3 is [not released for SQ 8.x](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix) and is still using it.
Using cxx 1.3 with SQ 7.9 should still support modules.
In the cxx version 2.0 module support is removed.

Regards,
Günter

**Comment by kalgary** [comment]
Hallo @guwirth ,

I know that with SQ 8.x the modules logical visualization in the dashboard is not supported, but, will be still possible to aggregate the cppcheck issues/violations under the same project by using a multi configuration approach?

For example, by using the property files as explained above, is it still possible to have issues/violations correctly imported from the cppcheck report ? 

if yes, we can ignore this warning, I guess.

> WARN: Storing measures on folders or modules is deprecated. Provided value of metric 'CXX-CPPCHECK' is ignored.

 thanks.

**Comment by guwirth** [comment]
Hi @kalgary,

to be honest: I don’t know. That’s because cxx 1.3 is only tested with SQ 7.9 and cxx 2.0 with SQ 8.6. My feeling is it should work. 

Regards,

**Comment by kalgary** [comment]
Hi @guwirth ,

thanks for the information.

Regards.
