### ISSUE TITLE
Parsing functions with default template parameter fail with non-POD return types

### ISSUE THREAD

**Issue by srpgilles** [SonarOpenCommunity/sonar-cxx#2025]
As indicated in the title, providing a default template parameter for a template function of method does not work in specific cases:

````
#include <string>

template<bool T>
std::string Check1(); // correctly parsed
            
template<bool T = false>
int Check2(); // correctly parsed
            
template<bool T = false>
std::string Check3(); // not parsed correctly

struct Foo {};

template<bool T>
Foo Check4();  // ok

template<bool T = false>
Foo Check4();  // not ok
````

This behaviour is seen directly with sslr-cxx-toolkit-1.3.2.1853.jar.

**Comment by guwirth** [comment]
Hello @srpgilles,

Thanks for your example. 

I’m wondering if this is really valid C++ code? In templates T is normally the datatype and after = there is the default datatype https://en.cppreference.com/w/cpp/language/function_template. 

Regards,

**Comment by srpgilles** [comment]
Thanks for your readily answer!

You're right about the convention I used in the example: T is not the most inspired choice for a non-type parameter...

Nonetheless to my knowledge it is perfectly valid code and gcc and clang both happily accept it with the proper expected behaviour.

And it's really weird that the parser is ok with it with some return types and not others...

**Comment by guwirth** [comment]
Hi @srpgilles,

You are right, it’s `2) A non-type template parameter with an optional name and a default value.`:
https://en.cppreference.com/w/cpp/language/template_parameters#Non-type_template_parameter

Will have a look...

Regards,

**Comment by guwirth** [comment]
Issue is ambiguous `>` in this context. Needs a fix in the grammar. In case of `simpleTypeSpecifier `it works.

```C++
template<bool T = false>std::string ... // error
```

**Comment by guwirth** [comment]
Hi @srpgilles, you can test it with latest 2.0 snapshot Regards
