### ISSUE TITLE
Initialization of data attribute with braces is mistakenly considered as a method

### ISSUE THREAD

**Issue by srpgilles** [SonarOpenCommunity/sonar-cxx#2027]
If a data attribute is initialized with braces:

````
struct Foo
{
    int bar_ {};
};
````

you may end up with a (major by default) code smell that tells the naming convention for **methods** is not respected.

The obvious workaround is to use different way to set the default value (`int bar_ = 0` for instance) but some coding standards actually recommend using the braces

**Comment by guwirth** [comment]
Check: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/naming/MethodNameCheck.java

**Comment by guwirth** [comment]
@srpgilles fixed in 2.0

**Comment by srpgilles** [comment]
Thanks!
