### ISSUE TITLE
C/c++ project build using cmake ninja

### ISSUE THREAD

**Issue by shrinidhi09** [SonarOpenCommunity/sonar-cxx#2033]
I am using 8.6 version of Sonarqube community edition. I want to analyze c/c++ project
build using cmake ninja. Any help would be really appreciated.

**Comment by guwirth** [comment]
Hi @shrinidhi09,

not sure what you wanna do exactly? The cxx plugin is a plugin for SonarQube to analyse Technical Debt?
How does this match with "want to analyze c/c++ project build using cmake ninja"?

Regards,
