### ISSUE TITLE
Add old repository rule keys to not loose history: addDeprecatedRuleKey

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#2047]
Add old repository rule keys to not loose history. 

https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java#L807

**Comment by guwirth** [comment]
**cxx 1.3.x repositories:**

repository key | repository name | language key
-- | -- | --
ClangSA | Clang-SA | c++
ClangTidy | Clang-Tidy | c++
common-c++ | Common C++ (Community) | c++
compiler-gcc | Compiler-GCC | c++
compiler-vc | Compiler-VC | c++
cppcheck | Cppcheck | c++
cxx | c++ SonarQube | c++
drmemory | Dr Memory | c++
other | Other | c++
pclint | PC-lint | c++
rats | RATS | c++
valgrind | Valgrind | c++
vera++ | Vera++ | c++

**Comment by guwirth** [comment]
`cxx SonarQube` should be renamed to `SonarQube`

**Comment by romanek-adam** [comment]
@guwirth not sure if this is the right place, but I thought I should not create a new ticket (at least not yet). In the [Upgrade to 2.0.x](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-the-Plugin#upgrade-to-20x) page you should probably mention other conversions of `repositoryKey`s, e.g. `ClangSA` -> `clangsa`, same way as it's already described for `ClangTidy` but not for others.

**Comment by guwirth** [comment]
Hi @romanek-adam,

thx for the hint. I did an update of the page. The listed replacements should be all.

Regards,
