### ISSUE TITLE
C++ (Community) default (Sonar way) profile rules are not enabled in SonarQube 7.9.5 with Sonar-cxx plugin v1.3.3

### ISSUE THREAD

**Issue by jacobgeorgee** [SonarOpenCommunity/sonar-cxx#2060]
### Description

C++ (Community) default (Sonar way) profile rules are not enabled in SonarQube 7.9.5 LTS with Sonar-cxx plugin v1.3.3

### Steps to reproduce the problem

Please provide the steps required to reproduce the problem

1. Setup SonarQube Community Edition v7.9.5 server with sonar-cxx community plugin v1.3.3

2. Login to SonarQube as admin and check C++ (Community) default quality profile named 'Sonar way'

### Expected behavior

'Sonar way' quality profile rules are enabled.

### Actual behavior

'Sonar way' quality profile rules are not enabled.

### Known workarounds

Create a new quality profile extending the default one, then enable rules for that, and finally make it as the default quality profile for C++ (Community) to start using those rules.

### LOG file

Any warnings/errors in the LOG file? - Not sure.

### Related information

* cxx plugin version? 1.3.3
* SonarQube version? 7.9.5

**Comment by guwirth** [comment]
Hi @jacobgeorgee,

this is intentional: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles

Regards

**Comment by jacobgeorgee** [comment]
Ha ok! Thank you for the response @guwirth 

One quick question on the following mentioned in the Wiki -
"In order to enable some rules, administrator have to initially activate rules in a copy of 'Sonar way':"
Does extending the 'Sonar way' quality profile make more sense than copying if we plan to upgrade the plugin in the future; so any rules additions/removal in the new plugin version will be automatically available in the extended quality profile, or will those be available in all quality profiles irrespective of whether they are extended/copied?

**Comment by guwirth** [comment]
@jacobgeorgee there are two ways:
* extend: idea is that you extended a profile to have more rules (you can't remove existing rules from parent)
* copy: create a copy of the existing one. You can add and remove rules.

I case of an empty parent there is no difference.
https://docs.sonarqube.org/latest/instance-administration/quality-profiles/
