### ISSUE TITLE
Error during SonarScanner execution java.lang.IllegalStateException: Failed to index files

### ISSUE THREAD

**Issue by Emanueltotem** [SonarOpenCommunity/sonar-cxx#2061]
Hi guys, I am trying to execute the command below, but it is getting the error **Error during SonarScanner execution
java.lang.IllegalStateException: Failed to index files** and further down in the log it states that it was not possible to access a file by the system.

`sonar-scanner.bat -D"sonar.projectKey={projectKey}" -D"sonar.host.url=http://localhost:9000" -D"sonar.login={loginKey}"`

I'm running on

**Laravel** `6.20.1`
**PHP** `7.4`
**OS**: `Windows 10`

**Comment by guwirth** [comment]
Hi @Emanueltotem,

This is the cxx plugin community. Do you really have an issue with this plugin?
If not https://community.sonarsource.com/ is the better place to ask. 

Regards

**Comment by Emanueltotem** [comment]
sorry, I'm not using the package. I will register in the forum that informed me.
