### ISSUE TITLE
Can I use the sonar-cxx plugin with sonarqube developer edition

### ISSUE THREAD

**Issue by rsbandaru** [SonarOpenCommunity/sonar-cxx#2068]
Hi 
Thanks for this nice plugin. I used it with sonarqube community edition for exporting my cppcheck and valgrind reports. 
I installed the plugin and used the attributes sonar.cxx.valgrind.reportsPath. However, after I upgraded to sonarqube developer edition, the export is no more working.
I see that it is no more supported? Am I right? Is there a way to use the plugin with the developer edition?

Best Regards
Raja

**Comment by rsbandaru** [comment]
I understand it is not possible to apply two analyzers for a single file. Do you think it is possible to use both sonarcfamily and cxx together for the same source code? 
https://community.sonarsource.com/t/memory-leak-not-detected/39177/7

**Comment by guwirth** [comment]
Hi @rsbandaru,

which versions you are using?
- SQ 7.9, 8.x?
- cxx plugin 1.3 or 2.0?

Have you read this: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-the-Plugin ?

Regards,

**Comment by rsbandaru** [comment]
Hi @guwirth 
I am using SQ 8.4.2 and cxx plugin 1.3. The compatibility matrix says SQ 8.7 with cxx 2.0, so was not sure.
Shall I use cxx 2.0?
And can run sonar-scanner for both sonarcfamily (via their buildwrapper) and cxx plugin together?
Or do I have to run seperately?
Best Regards

**Comment by guwirth** [comment]
Hi @rsbandaru,

we are testing only with LTS versions:
- for SQ 7.9 LTS you have to use cxx plugin 1.3
- for SQ 8.x LTS the cxx plugin 2.0 (currently we are testing with SQ 8.7)
- only cxx plugin 2.0 sensor are supporting  SonarCFamily plugin

For other versions you have to try out yourself the compatibility.

> However, after I upgraded to sonarqube developer edition, the export is no more working.

See no reason why the plugin should not work with developer edition. Was community and developer edition the same SonarQube version?

> I understand it is not possible to apply two analyzers for a single file. 

More correct is that files (file extensions) are always unique assigned to one programming language.
There can't be two plugins defining the same programming language.
SonarCFamily plugin = language key cpp
cxx plugin = language key c++ (1.3) and cxx (2.0)

> Do you think it is possible to use both sonarcfamily and cxx together for the same source code?

Only one plugin can read the source code file (indexing).
Several sensors could read reports and assign them to an indexed file.
cxx plugin 2.0 can assign issues to cpp (SonarCFamily ) and cxx (cxx plugin).

> The compatibility matrix says SQ 8.7 with cxx 2.0, so was not sure. Shall I use cxx 2.0?

You have to try yourself if 2.0 is compatible to 8.4

> and can run sonar-scanner for both sonarcfamily (via their buildwrapper) and cxx plugin together?

With cxx 2.0 you can read (index) files with SonarCFamily and assign issues with cxx plugin sensors.
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cppcheck.reportPaths
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.valgrind.reportPaths

Mind that 2.0 is using parameter name: `reportPaths`!

Hope that helps.

Regards,

**Comment by rsbandaru** [comment]
Hi @guwirth 
Thanks for the detailed answer.
Where can I find the cxx 2.0 plugin download.
I only see 1.3.3 as the latest version on this page: https://github.com/SonarOpenCommunity/sonar-cxx/releases
Best Regards
Raja

**Comment by guwirth** [comment]
Hi @rsbandaru,

you can use https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts (Download latest snapshot)

![grafik](https://user-images.githubusercontent.com/6077367/109557499-7c305900-7ad8-11eb-8423-bd122151319b.png)

**Comment by guwirth** [comment]
@rsbandaru in case it’s working would be good to get some feedback...

**Comment by rsbandaru** [comment]
@guwirth Sure. But please expect some delay. Sorry for that.
Adding a new plugin takes time as it needs to be added to the common sonarqube remote server. Not sure if there is an easier way. I only have sonar-scanner running on my machine.

**Comment by rsbandaru** [comment]
@guwirth. One question. in the version matrix v2.0.0 is labeled as an upcoming release.
May I know when will it be officially released?

**Comment by guwirth** [comment]
@rsbandaru we will release cxx 2.0 together with next SQ 8.x LTS version. Up to now there is no release date communicated from SonarSource.
