### ISSUE TITLE
Cppcheck results

### ISSUE THREAD

**Issue by JuPrgn** [SonarOpenCommunity/sonar-cxx#2069]
Hi

Thank you for this wonderfull plugin !

I successfully configured the plugin to see C++ rules on my sonarqube test server but I do not see Cppcheck warnings on Sonarqube Issues page.

I also found something inconsistent and it seems your wiki needs an update  : 
- Sonarqube Key: `sonar.cxx.cppcheck.reportPath` : singular `path` without S
-  From your wiki : Key: `sonar.cxx.cppcheck.reportPaths` : plurial `pathS`
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cppcheck.reportPaths
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Report-Paths

With following configuration Cppcheck sensor is used but I do not see the 36 reports on Issues : 
```
sonar.projectKey=my:project
sonar.cxx.file.suffixes=.h,.c
sonar.cxx.cppcheck.reportPath=Cppcheck/report.xml
```

> 09:59:06.451 INFO: Sensor C++ (Community) CppCheckSensor [cxx]
> 09:59:06.451 INFO: Searching reports by relative path with basedir 'C:\Dev\Firmware\TestSonar' and search prop 'sonar.cxx.cppcheck.reportPath'
> 09:59:06.453 DEBUG: Normalized report includes to '[C:\Dev\Firmware\TestSonar\Cppcheck\report.xml]'
> 09:59:06.454 DEBUG: Scanner uses normalized report path(s): 'C:\Dev\Firmware\TestSonar\Cppcheck\report.xml'
> 09:59:06.465 INFO: Parser will parse '1' report file(s)
> 09:59:06.466 INFO: Processing report 'C:\Dev\Firmware\TestSonar\Cppcheck\report.xml'
> 09:59:06.466 DEBUG: Parsing 'Cppcheck V2' format
> 09:59:06.519 INFO: Added report 'C:\Dev\Firmware\TestSonar\Cppcheck\report.xml' (parsed by: CppcheckParserV2)
> 09:59:06.520 DEBUG: CXX-CPPCHECK processed = 36
> 09:59:06.521 INFO: CXX-CPPCHECK processed = 36
> 09:59:06.522 INFO: Sensor C++ (Community) CppCheckSensor [cxx] (done) | time=71ms

Is there something missing on my configuration ?

Any help would be apreciated =)

I am using sonar-cxx-plugin-1.3.3.2051 with SQ 8.7 (latest docker demo)

**Comment by JuPrgn** [comment]
Oh I just seen there is a v2.0 thanks to another issue I will give it a try.

**Comment by guwirth** [comment]
Hi @JuPrgn,

v1.3 is using `sonar.cxx.cppcheck.reportPath`
v2.0 `sonar.cxx.cppcheck.reportPaths`

Please read
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cppcheck.reportPaths
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-the-Plugin

You can download latest snapshot from here:
https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

Looking to your .log snippet maybe the paths in the report does not match.

Regards,

**Comment by JuPrgn** [comment]
Thank you for your links, I was reading the v2.0 doc but using the wrong plugin version.


With latest v2.0 snapshot I have the same issue everything is fine but I do not see the Cppcheck errors on Issue page.

My files are in `project directory` > `src` directory. I tried following paths but without success : 

- `<location file=".\src\main.c"`
- `<location file=".\\src\\main.c"`
- `<location file="src\main.c"`
- `<location file="src\\main.c"`
- `<location file="src/main.c"`
- `<location file="./src/main.c"`


I also tried with your example report : 
```
<?xml version="1.0" encoding="UTF-8"?>
<results version="2">
    <cppcheck version="2.20"/>
    <errors>
        <error id="someError" severity="error" msg="short error text" verbose="long error text" inconclusive="true">
            <location file="src/main.c" line="65"/>
        </error>
    </errors>
</results>
```

> INFO: Sensor CXX Cppcheck report import [cxx]
> INFO: Processing report 'C:\Dev\Firmware\TestSonar\Cppcheck\report.xml'
> INFO: Processing successful, saved new issues=1
> INFO: Sensor CXX Cppcheck report import [cxx] (done) | time=21ms

This detected issue is also not visible on my project page `http://localhost:9000/project/issues...`

My sonarqube instance is run from docker with integrated database not sure if this have any side effect.

**Comment by guwirth** [comment]
Hi @JuPrgn,

1. The rules for which you want to generate issue must be activated in the Quality Profile of your project. (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles)
2. Where is your `sonar-project.properties` file located? The file defines the **project base directory**.  All relative paths are resolved relative to this path. (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Troubleshooting-Reports). 

Regards,

**Comment by JuPrgn** [comment]
Thank you for your support.

1. I activated all the rules but I am not sure there are Cppcheck rules on the 5000+ rules if this is what you mean ?

2. `sonar-project.properties` is located at the base of my project directory where the `src` direcrory is located.

**Comment by guwirth** [comment]
Hi @JuPrgn,

here is a working project we are using for the integration tests:
https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/cppcheck_project

Is this working?

Regards,

**Comment by JuPrgn** [comment]
Hi @guwirth 

It works great ! I did not know that the rules detected by Cppcheck should also be known by Sonarqube, I thought it was additional rules.
I am using Cppcheck with the MISRA C plugin enabled and these rules are unknown, which is why I have not received these reports.

It would be great if I could add these rules to your plugin but I don't think misra rules can be added on an open source tool without legal issues. Cppcheck uses a workaround where the user adds the description of the rules in a text file.
I will look at how to add rules, if you have any tips that would be appreciated =)

**Comment by JuPrgn** [comment]
Misra C 2012 rules are already on your base and tagged for PCLINT, they are names as `M2012`... 
Cppcheck keys for these rules are `misra-c2012...`

**Comment by guwirth** [comment]
Hi @JuPrgn,

You could do it like this: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/CXX-Custom-Template-Rules. With custom template rules you can extend a rule repository. 

Regards,
