### ISSUE TITLE
How can update default value of sonarqube rule " Source files should have a sufficient density of comment lines"

### ISSUE THREAD

**Issue by rajesh174u** [SonarOpenCommunity/sonar-cxx#2078]
wanna update default value of rule "Source files should have a sufficient density of comment lines"
( minimumCommentDensity | Default Value:25 ) wanna update to 10 and wanna change severity to minor.

Is this possible?
How can achieve.

**Comment by guwirth** [comment]
Hi @rajesh174u,

you have to create an own Quality Profile and change the value of the rule in this copy. Ensure that your project is using this Quality Profile then. 

https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles
https://docs.sonarqube.org/latest/instance-administration/quality-profiles/

Regards,
