### ISSUE TITLE
PC-lint Plus v1.3 and v1.3.5 new messages (rules) are missing from PC-lint (C++) repository of sonar-cxx plugin

### ISSUE THREAD

**Issue by chswap** [SonarOpenCommunity/sonar-cxx#2085]
**Describe the bug**
PC-lint Plus v1.3 and v1.3.5 new messages (rules) are missing from PC-lint (C++) repository of sonar-cxx plugin

**Expected behavior**
There are new messages added by Gimpel in new versions of PC-lint Plus v1.3 and v1.3.5. These messages are missing from PC-lint (C++) repository of sonar-cxx plugin. Due to this issue, sonar-cxx plugin is not able to filter issues of these new messages. New messages list is attached. These new messages should be included in repsoisory so that issues related to these rules are filtered by SonarQube.

**Additional context**
Refer Release notes of PC-lint Plus for more details on new messages.
[PC-lint Plus 1.3 and 1.3.5 Rules.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/6161501/PC-lint.Plus.1.3.and.1.3.5.Rules.txt)

**Comment by guwirth** [comment]
Hello @chswap,

thanks for your feedback.

We don’t have the tool, so maybe easiest would be you add them to https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/pclint.xml and create a PR. 

Regards,

**Comment by chswap** [comment]
Hello Guntar,

Thanks for your quick feedback.
I will update the pclint resource file with all new messages and create a PR.

Regards,
Swapnil

**Comment by guwirth** [comment]
Hello @chswap,

thanks for your support, looking forward to your solution.
Please fix then also the unit test (number of rules):
https://github.com/SonarOpenCommunity/sonar-cxx/blob/4118becb2d4923b6e56a76a607233d752c7a57d2/cxx-sensors/src/test/java/org/sonar/cxx/sensors/pclint/CxxPCLintRuleRepositoryTest.java#L39

Regards,

**Comment by guwirth** [comment]
Hello @chswap,

still interest to extend the rules? End of April we will create the final 2.0 version.

Regards

**Comment by chswap** [comment]
Hi @guwirth 

We have started working on this issue and soon we will merge the code via PR. @vishal-gaikwad from my team will take this further.

Thanks,
Swapnil

**Comment by guwirth** [comment]
@chswap thx
