### ISSUE TITLE
Built-in c & c++ show 0 rules in quality profiles UI page

### ISSUE THREAD

**Issue by yuezhuangshi** [SonarOpenCommunity/sonar-cxx#2089]
**Describe the bug**
Built-in c & c++ show 0 rules in quality profiles UI page when plugin version >= 1.3.1
plugin version 1.3.0 works fine

**To Reproduce**
1. Use c and cxx plugin version >= 1.3.1
2. Start sonarqube  server 7.9.6
3. Go to quality profiles UI page
4. Find "C(Community), x profile(s)" and "C++(Community), x profile(s)" section.
5. See error

**Expected behavior**
Built-in c & c++ show non-zero rules in quality profiles UI page

**Screenshots**
[Screenshots](https://ftp.bmp.ovh/imgs/2021/03/0d37ee061ee1dc9c.jpeg)

**Desktop (please complete the following information):**
 - SonarQube version: 7.9.6
 - cxx plugin version: 1.3.1, 1.3.2, 1.3.3

**Comment by guwirth** [comment]
Hi @yuezhuangshi,

are the rules active? https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles

Regards,
