### ISSUE TITLE
Infer Rules not found within Sonarqube

### ISSUE THREAD

**Issue by olbrichj** [SonarOpenCommunity/sonar-cxx#2114]
**Describe the bug**
I'm trying to add infer rules to my current project, but going searching for rules within SonarQube doesn't show any results. 
There seems to be a ruleset: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/cxx-sensors/src/main/resources/infer.xml
and a scanner: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/infer

Searching in SonarQube for the rules listed within infer.xml doesn't yield any results. At the same time doing so with the rules e.g. for clang-tidy works fine.

Is there anything I specificly have to do to activate the rules for infer?

**Comment by guwirth** [comment]
Hi @olbrichj,

which version of the plugin are you using? Infer is supported with 2.0 only.
If you are using 2.0: Are the rules activated (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles)?

Regards,

**Comment by olbrichj** [comment]
Hi @guwirth,
ah that makes sense. We are currently using 1.3.3, as that seems to be the most current release. 
Do I assume correctly that the latest snapshot then contains Infer?

Thanks

**Comment by guwirth** [comment]
Hi @olbrichj,

the latest snapshot is 2.0 and includes Infer. We will do a final release with SQ 8.9 LTS which is coming soon...

Regards,

**Comment by olbrichj** [comment]
Thanks
