### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by lduparc** [SonarOpenCommunity/sonar-cxx#2123]
Hi,

Have you an idea when release 2.0 will be available ?

Thanks

**Comment by guwirth** [comment]
Hi @lduparc,

cxx plugin 2.0 is planned together with SQ 8.9 LTS release:
https://blog.sonarsource.com/sonarqube-lts-89-standby?utm_source=community&utm_medium=hello-bar&utm_campaign=lts

You can already use the latest snapshot. The 2.0 version is feature finished, we are working only on bugfixes. 

Regards,

**Comment by guwirth** [comment]
@lduparc cxx plugin 2.0 is released now
