### ISSUE TITLE
Code duplication issue in sonar-c-plugin-1.3.3.2051.jar

### ISSUE THREAD

**Issue by dhanushkc** [SonarOpenCommunity/sonar-cxx#2133]
Hello,

SonarQube version: 7.9.6 LTS
sonar scanner version : sonar-scanner-4.0.0.1744-windows

We are using **sonar-c-plugin-1.3.3.2051.jar** downloaded from your repository https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-1.3.3/sonar-c-plugin-1.3.3.2051.jar

Requirement: **We are interested in getting code duplications report >5 Lines**

1.We have changed the default value for duplications to 5
In sonar-project.properties, have set sonar.cpd.c.minimumLines=5

Behaviour: In some files duplicate code is detected and in many files even though duplications >5 is present but still not able to see in the SonarQube report generated after successful analysis

Concern is in some A tool, duplications are reported for the same file but plugin is failing to detect it

Am attaching  Sample_dup.txt(It is c file but while file uploading here .c extension is not supported hence uploading in .txt extension. Sample_dup.txt (3.0 KB) Kindly convert the extension of this file to .c ) **Sample_dup.c file it is small reproducing project where you expect duplication to be reported**

For the attached file Some tool is able to detect duplications **“Between lines 61 and 68” and “Between lines 10 and 17”**. But here **it is not able to detect [duplications] in this file .**

Can I know brief logic used by the plugin for cpd detection because even though n lines are duplicated and present in the file but plugin is failing to detect it

Is this is a bug or the logic for code duplications is different. Ideally logic for code duplication detection should be same using any other tools
[Sample_dup.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/6414195/Sample_dup.txt)

Can you please help
Appreciate your Support

Thanks and Regards,
Dhanush K C

**Comment by guwirth** [comment]
Hi @dhanushkc,

> Can I know brief logic used by the plugin for cpd detection because even though n lines are duplicated and present in the file but plugin is failing to detect it

The CPD detection in SQ is working like this:
- split the source code to tokens and forward a token stream to SQ core. The SQ core is detecting / calculating the CPD metric 
- this is the visitor forthe cxx plugin: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/src/main/java/org/sonar/cxx/visitors/CxxCpdVisitor.java

In case you get no/wrong results could also be that file is not/or only partly parsed. Turn debug info on during scanning and have a look if there is additional information available: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-Debug-Information

Regards,

**Comment by guwirth** [comment]
Hi @dhanushkc,

... and that's SQ definition: https://docs.sonarqube.org/latest/user-guide/metric-definitions/#header-3.

Regards,

**Comment by guwirth** [comment]
Hi @dhanushkc, I close this one. In case you need more information reopen it. Regards

**Comment by dhanushkc** [comment]
Hi @guwirth ,

Sure, Thanks for the Support.

Regards,
Dhanush K C
