### ISSUE TITLE
Wiki: Remove sidebar and add table of content instead

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#217]
Hi,

Would like to remove the side bar in the wiki. Using too much space and hides especially table content. Suggestion is to add a table of content (ToC) at the beginning of each page instead.

Regards,

**Comment by dorfsmay** [comment]
I created an empty _Sidebar.md, but we still have this huge sidebar on the right hand side, which, as @guwirth says make table absolutely unreadable. Sadly, we might have to use a different wiki because of this.

**Comment by dorfsmay** [comment]
Also, the sidebar doesn't show in the preview, which now renders the preview useless, since it doesn't show you how the page will be seen by users.

**Comment by alaniwi** [comment]
Have you got any further with this please? I would like to do the same thing. Thanks.

**Comment by sampierson** [comment]
+1
The GitHub wiki is useless for table data because of that damn pages list.

**Comment by christocracy** [comment]
+1 Tables are useless.  I need that vertical space consumed by the sidebar.
![](https://www.dropbox.com/s/ygn6a1ds5w8coq6/Screenshot%202015-10-02%2011.49.05.png?dl=1)

**Comment by jmecosta** [comment]
What about GitHub pages?

**Comment by christocracy** [comment]
I'm using github pages for the marketing front-end of my project.  The wiki is nice because it's easily editable with markdown.  Not so with github pages.

**Comment by christocracy** [comment]
"API Documentation" clearly is a valid usage of a Wiki.

**Comment by jmecosta** [comment]
There is no api documentation and we don't have a use for the github pages, for me its as good as anything else that does not cut the tables

**Comment by guwirth** [comment]
Not possible
