### ISSUE TITLE
C++ cannot be analyzed with current SonarQube edition. Please consider upgrading...

### ISSUE THREAD

**Issue by consulion** [SonarOpenCommunity/sonar-cxx#2172]
Hi, thanks for your great work! We've been using the previous version of this plugin with an older version of SQ, recently updated both SQ + this plugin to the most recent release (SQ Community Edition, Version 8.9 (build 43852)), Plugin version 2.0.2 (build 2734).

I followed the upgrade guidelines, and can see files are indexed and CXX-Scanner is working in the log, afterwards it shows
_05:47:31.313 INFO: Sensor CXX [cxx] (done) | time=766004ms_
 but after the report is generated, compressed and uploaded, no issues show up in SQ, and the following warning is shown:

_2466 unanalyzed C++ files were detected in this project during the last analysis. C++ cannot be analyzed with your current SonarQube edition. Please consider upgrading to Developer Edition to find Bugs, Code Smells, Vulnerabilities and Security Hotspots in this file._

Is this still supposed to work with SQ community edition? What could possibly cause this?

**Comment by guwirth** [comment]
Hi @consulion,

> Is this still supposed to work with SQ community edition? What could possibly cause this?

The cxx plugin 2.0 should work with SQ 8.9 LTS. We are doing several integration tests with it without problems.

Please read these two wiki pages, there are also LOG file samples and a description how to interpret it:
- https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code
- https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files

Please do a first small test with the **demo project**, is this working?
- https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/hello_world

Regards,

**Comment by consulion** [comment]
Hi @guwirth,

thanks for your answer,
it worked with 1.3.3 and a previous version of SQ (not exactly sure which), but stopped working after upgrading.
I read those pages already, also looked at all debug output but can't seem to find any errors.
Analyzing the demo project has same result, no issues found and the same warning about not being able to analyze C++ with the current edition (Community)...
We are using the sonarqube 8.9.0-community docker image, and there are no other C++ plugins active...
It doesn't seem to be a problem on the scanner side, but how the report is processed on the SQ host, but i don't see any errors in the SQ log either, is there some way to see what happens after the log is uploaded?

Cheers,

**Comment by guwirth** [comment]
Hi @consulion,

I found some hints, but have to dick deeper into it to understand what they are doing here? Also don't understand why our integrations test are running without problems and waht the difference is to your use case?

SONAR-13869 Add a flag in telemetry to know if there's some c/c++ unanalyzed code
* SONAR-13869 Compute number of unanalyzed C and C++ files measures
* SONAR-13869 Send unanalyzed C and C++ flags in Telemetry

https://github.com/SonarSource/sonarqube/commit/bc413ee3db73258a22059816bd4766bcea66a9ca#diff-23fc27f1064b266962e60af1215608f4773823edb6dbbc5058ddf35057afcb7f

Regards,

**Comment by consulion** [comment]
Hi @guwirth,

the warning seems to be misleading, I noticed I forgot to assign a quality profile to the hello_world project, after doing so, it detects 1 code smell through the cppcheck sensor (yet the warning is still shown).

The reason why our main project is not getting analyzed seems to be something else, we are using the Visual Studio report scanner,   maybe something went wrong while changing the sonar-project properties for 2.0.x, but build+analysis takes quite some time, I'll let you know tomorrow.

Thanks again

**Comment by guwirth** [comment]
Hi @consulion,

it seem that SonarSource added a message if the community edition is reading an input file with file extension **.c, .cc, .cpp, .cxx or .c++**:

https://github.com/SonarSource/sonarqube/blob/master/sonar-scanner-engine/src/main/java/org/sonar/scanner/scan/filesystem/InputComponentStore.java

![5E5A1545-75FE-4F1C-9C33-67768E96AFE0](https://user-images.githubusercontent.com/6077367/119886407-377b5900-bf33-11eb-85e0-17cb970183d7.jpeg)

What happens if you select “Dismiss permanently”?

Regards,
