### ISSUE TITLE
No C++ rules in quality profile 

### ISSUE THREAD

**Issue by samkhamk** [SonarOpenCommunity/sonar-cxx#2173]
Hello There,

We have sonarqube community edition 7.9.6 and we manually installed sonar-cxx-plugin-2.0.1.2678 , but when we check in quality profile we couldn’t see any rules for C++,

can you suggest what we need to do,We can see suggestions No C++ rules to select in a Quality Profile - #7 by Colin_SonarSource 1
but afraid of loosing data.

**To Reproduce**
1. install sonar-cxx-plugin-2.0.1.2678
2. restart sonarqube
3. go to quality profile tab 

can you please let us know if its default behavior or we need to perform some action to get rules enabled.

Regards,
Sam

**Comment by guwirth** [comment]
Hi @samkhamk,

In the wiki you fina a step by step instrucation:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki

Did you follow the update instructions?
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-the-Plugin

On a new server Quality Profile looks like this:
![grafik](https://user-images.githubusercontent.com/6077367/120162324-8efe1b00-c1f8-11eb-8e5f-436f9f452c00.png)

All rules are turned off by default:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles

Regards,

**Comment by samkhamk** [comment]
@guwirth 

Thank you for this information, helpful.  it resolved my issue.
