### ISSUE TITLE
Clang-Tidy: duplicate issues are not removed

### ISSUE THREAD

**Issue by dsakilesh** [SonarOpenCommunity/sonar-cxx#2174]
Hi Team,

For one of the file the duplicates are being up by sonarqube with sonar-cxx version 2.0.2 version. Please find the details below.

SonarQube count : 3 but expected count : 2
Jenkins warning ng count : 2 as expected

Warnings in SonarQube:
![image](https://user-images.githubusercontent.com/58210462/120291241-b9c39e80-c2e0-11eb-83fb-c0617237183a.png)

PFB the clang-tidy.log content:
```
/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/include/BrcStaticDataStore/BrcStaticDataStore/BrcStaticDataStore.hpp:122:32: warning: field '_identityFunction' is uninitialized when used here [clang-diagnostic-uninitialized]
                               _identityFunction,
                               ^
/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/include/BrcStaticDataStore/BrcStaticDataStore/BrcStaticDataStore.hpp:123:32: warning: field '_identityFunction' is uninitialized when used here [clang-diagnostic-uninitialized]
                               _identityFunction) {
                               ^
/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/include/BrcStaticDataStore/BrcStaticDataStore/BrcStaticDataStore.hpp:122:32: warning: field '_identityFunction' is uninitialized when used here [clang-diagnostic-uninitialized]
                               _identityFunction,
                               ^
/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/include/BrcStaticDataStore/BrcStaticDataStore/BrcStaticDataStore.hpp:123:32: warning: field '_identityFunction' is uninitialized when used here [clang-diagnostic-uninitialized]
                               _identityFunction) {
                               ^
```

PFB the metrics displayed by jenkins warnings ng plugin:
![image](https://user-images.githubusercontent.com/58210462/120291665-2dfe4200-c2e1-11eb-88ba-207236038e7c.png)

Warning ng plugin seems to ignore the duplicates but sonarQube seems to ignore one duplicate and displays one duplicate.

Line number, column number, warning message , rule id are all the same.

Let me know if you need more details. Thanks in advance!

Regards,
Akilesh D S

**Comment by guwirth** [comment]
Hi @dsakilesh, thx seems to be a bug...

**Comment by guwirth** [comment]
@dsakilesh I had a look to this issue again:

There is different code  at the same position in the same file: `_identityFunction,` and ` _identityFunction) {` ==> that can't be.
Reading the report below the plugin should report 1 issue because it reads only the message and not the line behind with the code snippet.

```
/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/include/BrcStaticDataStore/BrcStaticDataStore/BrcStaticDataStore.hpp:122:32: warning: field '_identityFunction' is uninitialized when used here [clang-diagnostic-uninitialized]
                               _identityFunction,
                               ^
/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/include/BrcStaticDataStore/BrcStaticDataStore/BrcStaticDataStore.hpp:123:32: warning: field '_identityFunction' is uninitialized when used here [clang-diagnostic-uninitialized]
                               _identityFunction) {
                               ^
/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/include/BrcStaticDataStore/BrcStaticDataStore/BrcStaticDataStore.hpp:122:32: warning: field '_identityFunction' is uninitialized when used here [clang-diagnostic-uninitialized]
                               _identityFunction,
                               ^
/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/include/BrcStaticDataStore/BrcStaticDataStore/BrcStaticDataStore.hpp:123:32: warning: field '_identityFunction' is uninitialized when used here [clang-diagnostic-uninitialized]
                               _identityFunction) {
                               ^
```

**Comment by dsakilesh** [comment]
Hi @guwirth 

Position is the same but the line numbers are different.

`_identityFunction,` is available in line 122
 and `_identityFunction) {` is available in line 123

PFB the code snippet. 

![image](https://user-images.githubusercontent.com/58210462/120780191-75850800-c545-11eb-8653-268c4a6b224c.png)


Regards,

**Comment by guwirth** [comment]
@yachoor, @dsakilesh please try with latest snapshot. Most Clang-Tidy issues should be solved now:
https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts
