### ISSUE TITLE
Clang-Tidy: skipped warnings

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#2175]
We have one small issue still.

```
/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/src/Util/String.cpp:16:1: warning: nested namespaces can be concatenated [modernize-concat-nested-namespaces]
namespace util {
^~~~~~~~~~~~~~~~
namespace util::str
/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/src/Util/String.cpp:21:29: warning: do not use pointer arithmetic [cppcoreguidelines-pro-bounds-pointer-arithmetic]
  for (; (i < maxLength) && str[i]; ++i)
                            ^
/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/src/Util/String.cpp:21:29: warning: implicit conversion 'char' -> bool [readability-implicit-bool-conversion]
  for (; (i < maxLength) && str[i]; ++i)
                            ^
                            (      != 0u)
/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/src/Util/String.cpp:21:41: warning: statement should be inside braces [google-readability-braces-around-statements]
  for (; (i < maxLength) && str[i]; ++i)
                                        ^
                                         {
/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/src/Util/String.cpp:21:41: warning: statement should be inside braces [hicpp-braces-around-statements]
  for (; (i < maxLength) && str[i]; ++i)
                                        ^
                                         {
/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/src/Util/String.cpp:21:41: warning: statement should be inside braces [readability-braces-around-statements]
  for (; (i < maxLength) && str[i]; ++i)
                                        ^

                                         {
```
The above lines of warning is counted as 6 warnings in Jenkins warning NG plugin. 

![grafik](https://user-images.githubusercontent.com/6077367/120435921-96e7c780-c37e-11eb-95db-ac7946430d3b.png)

But in sonarQube its considered as only 2 warnings

![grafik](https://user-images.githubusercontent.com/6077367/120435847-7f104380-c37e-11eb-942e-d5c6edc77e2b.png)

PFB the skipped warnings from sonarqube debug logs:

```
[2021-05-31T09:07:11.601Z] 09:07:11.407 WARN: Cannot save the issue 'CxxReportIssue [ruleId=google-readability-braces-around-statements, locations=CxxReportLocation [file=/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/src/Util/String.cpp, line=21, column=41, info=statement should be inside braces], flow=]', skipping
[2021-05-31T09:07:11.601Z] 09:07:11.407 WARN: Cannot save the issue 'CxxReportIssue [ruleId=hicpp-braces-around-statements, locations=CxxReportLocation [file=/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/src/Util/String.cpp, line=21, column=41, info=statement should be inside braces], flow=]', skipping
[2021-05-31T09:07:11.601Z] 09:07:11.408 WARN: Cannot save the issue 'CxxReportIssue [ruleId=readability-braces-around-statements, locations=CxxReportLocation [file=/var/jenkins/0/workspace/bes-brc3-common_clang-generation/src/src/Util/String.cpp, line=21, column=41, info=statement should be inside braces], flow=]', skipping
```

Why are the warnings skipped in Sonarqube?

**Comment by yachoor** [comment]
Seem like they're all pointing to a column after last one - could that be the reason they cannot be added?

**Comment by yachoor** [comment]
Other issues from clang-tidy are off by one column for me too - is one indexing from 0 and the other form 1?

**Comment by guwirth** [comment]
@yachoor thanks for the hint. That was also my first idea. Question is how Clang-Tidy is counting the columns: 0-n or 1-n?
If a sensor assigns a issue to a source file it checks if the position is available in the source, if not it ignores the issue.
Do you have a running Clang-Tidy and are able to create an issue at the first character position of a line?

**Comment by yachoor** [comment]
It's 1-n:
```
/home/jchorko/test/test.cpp:9:1: warning: namespace 'test' not terminated with a closing comment [llvm-namespace-comment]
}
^
```
for test.cpp:
```
namespace test {

struct Test {
        int x;
        int y;
        int z;
}

}
```

**Comment by guwirth** [comment]
@yachoor thx. Problem is here:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/a736837c6e8ea115b3af04fdb09ff95bd20454b2/cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxIssuesReportSensor.java#L135

1.3 version of plugin did support only lines. Because we have only one column number we have to decide if we like to mark (red underline) from position to position +1 or -1.
* SQ counting seems to be 0 to n
* +1 is wrong at the end of the line
* I don't know how long the line is
* -1 is a problem with first column but this is easy to detect

**Comment by yachoor** [comment]
@guwirth
Also seems like an issue can be generated with column that's not in the file, but should be - from same example:
```
/home/jchorko/test/test.cpp:7:2: error: expected ';' after struct [clang-diagnostic-error]
}
 ^
 ;
```

**Comment by guwirth** [comment]
@yachoor, @dsakilesh please try with latest snapshot. Most Clang-Tidy issues should be solved now:
https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

**Comment by yachoor** [comment]
Thank you @guwirth, works perfect - no ignored issues and indicates correct column where possible

**Comment by guwirth** [comment]
@yachoor thx for your feedback. Will wait what @dsakilesh is saying and if also positive do an official release.
