### ISSUE TITLE
No line coverage for files, which are not in the coverage report

### ISSUE THREAD

**Issue by chrissy25** [SonarOpenCommunity/sonar-cxx#218]
Hi,

I have the issue, that I do not have any coverage data, for the files which are not in the coverage report XML file (see the attached image)

![sonar-issue](https://cloud.githubusercontent.com/assets/7090420/3079686/e6b16ae6-e4a1-11e3-8948-43a52fa42cda.png)
. 

Would it be possible, that these files get a 0% coverage in Sonar per default?

**Comment by guwirth** [comment]
docu: https://github.com/wenns/sonar-cxx/wiki/Get-code-coverage-metrics
