### ISSUE TITLE
unable to display cppcheck results in sonarqube

### ISSUE THREAD

**Issue by chaithanyareddyk** [SonarOpenCommunity/sonar-cxx#2183]
Hi Team,
we want to import our cppcheck results to sonarqube, 
Issues1: our source code contains C/C++ and we are installed sonar cxx plugin, after installation we are tried scan our code we are able to see .C files but unable to display c projects, we  are created Quality profile for C++.

Issue2: we are unable to import cppcheck results in sonarqube.
sonar. properties
sonar.projectKey=test projectKey
sonar.cxx.file.suffixes=.cxx,.cpp,.cc,.c,.hxx,.hpp,.hh,.h
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
sonar.cxx.metric.api.file.suffixes=.hxx,.hpp,.hh
sonar.cxx.suffixes=.cxx,.cpp,.cc
sonar.cxx.cppcheck.reportPaths=report.xml
sonar.c.cppcheck.reportpaths=report.xml
Help us to resolve this  issue.

**Comment by guwirth** [comment]
Hi @chaithanyareddyk,

which version of the plugin you are using?

Hints for 2.0:
- https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code
- https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files
- https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.file.suffixes
- https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cppcheck.reportPaths

Regards,

**Comment by chaithanyareddyk** [comment]
> Hi @chaithanyareddyk,
> 
> which version of the plugin are you using?
> 
> Hints for 2.0:
> 
> * https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code
> * https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files
> * https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.file.suffixes
> * https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cppcheck.reportPaths
> 
> Regards,

Hi Guwirth
we are using  sonarcxx plugin version :  version is 2.0.1 (build 2678). cppcheck: 1.63

**Comment by chaithanyareddyk** [comment]
we are unable to display cppcheck results to sonarqube kindly help us

**Comment by guwirth** [comment]
Hi @ chaithanyareddyk,

did you try it with the sample project?
https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/hello_world
How to is here: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code

In case there are still problems we need more information. Turn debug info on and provide the resulting LOG file:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-Debug-Information

Regards,

**Comment by guwirth** [comment]
Hi @chaithanyareddyk, is it working? Can I close this issue?

**Comment by chaithanyareddyk** [comment]
Hi Sir

Thanks for your response, we can able to display cppcheck results to sonarqube. But i have one doubt, we are using this command to generate cppcheck report.xml file cppcheck --xml-version=2 . 2> report.xml, when we are verifying the report.xml file we found error message like 
<error id="toomanyconfigs" severity="information" msg="Too many #ifdef configurations - cppcheck only checks 12 configurations. Use --force to check all configurations. For more details, use --enable=information." verbose="The checking of the file will be interrupted because there are too many #ifdef configurations. Checking of all #ifdef configurations can be forced by --force command line option or from GUI preferences. However that may increase the checking time. For more details, use --enable=information."/>
Do we need to take any action here? i am new to cppcheck, is cppcheck analyze every thing? how can i check ?

**Comment by guwirth** [comment]
Hi @chaithanyareddyk,

the message you get is missing? For Cppcheck support ask in their forum please: http://cppcheck.sourceforge.net/.

Regards,

**Comment by chaithanyareddyk** [comment]
Thank you sir , For Support.
<error id="toomanyconfigs" severity="information" msg="Too many #ifdef configurations - cppcheck only checks 12 configurations. Use --force to check all configurations. For more details, use --enable=information." verbose="The checking of the file will be interrupted because there are too many #ifdef configurations. Checking of all #ifdef configurations can be forced by --force command line option or from GUI preferences. However that may increase the checking time. For more details, use --enable=information."/>

**Comment by chaithanyareddyk** [comment]
Thank you
