### ISSUE TITLE
unable to display cppcheck results to sonarqube

### ISSUE THREAD

**Issue by chaithanyareddyk** [SonarOpenCommunity/sonar-cxx#2187]
**Before you create a new issue**
- Is it really a _cxx-plugin_ issue or a general _SonarQube_ issue? To track _SonarQube_ issues use the [community from SonarSource](https://community.sonarsource.com/) please.
- Please read the [Wiki](https://github.com/SonarOpenCommunity/sonar-cxx/wiki) first, maybe you will find a solution there.
- Please [turn debug info on](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information) and reproduce your issue. The debug info in the log file could help to solve or locate the issue.
- Please check if there is not already a [bug report](https://github.com/SonarOpenCommunity/sonar-cxx/issues) for your issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - SonarQube version: [e.g. 8.7.0]
 - cxx plugin version: [e.g. 2.0.0]
 - sonar-scanner version: [e.g. 4.6.0.2311]
 
Hi Team
we are unable to display cppcheck results to sonarqube
OS: AIX
Sonarqube: 8.
Cxx plugin Version:  version is 2.0.1 (build 2678).
Sonarscanner:  4.6.0.2311
Cppcheck: 1.63

we installed cppcheck 1.63 on our Aix manchine, when we are try to cppcheck its asking for std.cfg file with the reference of this link https://github.com/danmar/cppcheck/blob/1.63.x/cfg/std.cfg.  we created a file in repository and created a copy job in bamboo, when we executed cppcheck --xml-version=2 . 2> report.xml, cppcheck can able to generate report.xml file, bt sonarcxx plugin unable to sensor the xml file. in sonarqube we are unable to see our c code issues. please help us to resolve this issue  I am new to cppcheck and sonarqube
Thanks in advance.

**Comment by guwirth** [comment]
same as #2183
