### ISSUE TITLE
 toomanyconfigs  Too many #ifdef configurations - cppcheck only checks 12 configurations.

### ISSUE THREAD

**Issue by chaithanyareddyk** [SonarOpenCommunity/sonar-cxx#2193]
Hi Team

cppcheck --xml-version=2 . 2> report.xml with using this command we generated report.xml file, when we are checking the report.xml file we found this last of the report. i am new to cppcheck, do i need to take any further action on this? need your advice to resolve this issue.
Could you please clarify why we get this error.
we are using cppcheck -1.63
 
</error>
<error id="toomanyconfigs" severity="information" msg="Too many #ifdef configurations - cppcheck only checks 12 configurations. Use --force to check all configurations. For more details, use --enable=information." verbose="The checking of the file will be interrupted because there are too many #ifdef configurations. Checking of all #ifdef configurations can be forced by --force command line option or from GUI preferences. However that may increase the checking time. For more details, use --enable=information."/>
</errors>
</results>

**Comment by guwirth** [comment]
Hi @chaithanyareddyk,

please ask Cppcheck questions in their forum: http://cppcheck.sourceforge.net/ we are not external tool experts.
In case of conditional code from the preprocessor Cppcheck tries to analyse all combinations. Think there are settings to define an upper limit?

Regards,
