### ISSUE TITLE
Sensor CXX performance

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#2206]
@MarcoWagner: i also have a wxWidgets based project with interesting stats.

~150k LoC
INFO: Sensor CXX [cxx] (done) | time=5.475.497ms

**Comment by guwirth** [comment]
Hi @MarcoWagner,

maybe you can turn on debug info and isolate the problem:
- due to a single cpp file?
- many include files / every cpp file slow?
- #2131?
- ....

Regards,

**Comment by MarcoWagner** [comment]
its #2131

**Comment by guwirth** [comment]
Hi @MarcoWagner,

could you provide a sample please?

Regards,

**Comment by MarcoWagner** [comment]
```c++

#include <iostream>
#include <string>
#include <sstream>

std::ostream& operator< (std::ostream& dest, const std::string& what) { 
   return dest;
}

int main () 
{
   std::string a, b, c, d, e, f;
   std::stringstream dest;
   
   dest < a < b < c < d < e < f;
}
```
Seems to be O(n!)

**Comment by guwirth** [comment]
Hi @MarcoWagner,

I’m wondering why someone creates an own streaming operator with <? Why not writing <<?

The problem is in the grammar where has to be decided if something like this is a condition expression or a cascaded template. This construct leads to a lot of backtracking and slow speed. Found up to now no solution to speed that up. The case where something like this ends up in a template is more likely and fast.

Ideas are welcome. 

Regards,

**Comment by MarcoWagner** [comment]
I also don't like that `operator<` and `operator>` "missuse". cppcheck is also detecting it as an suspicous operator usage und does sometimes alert it as uninitialized variable usage.... But that discussion is out of scope. ;-)

**Comment by guwirth** [comment]
duplicate #2131
