### ISSUE TITLE
how can we sure the plugin installed properly

### ISSUE THREAD

**Issue by michalliu** [SonarOpenCommunity/sonar-cxx#2207]
I scanned my cpp project, there is 0 bugs. unbelievable, Is there a sample cpp project and a sample scanning result to be comparing with?

**Comment by guwirth** [comment]
Hi @michalliu,

have you read the Wiki?
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files
* Demo project: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/hello_world
* problem is mostly https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles
  
Regards,

**Comment by michalliu** [comment]
> Hi @michalliu,
> 
> have you read the Wiki?
> 
> * https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code
> * https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files
> * Demo project: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/hello_world
> * problem is mostly https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles
> 
> Regards,

Thanks for the links. problem resolved.
