### ISSUE TITLE
find the failed unit test in the test code

### ISSUE THREAD

**Issue by OuyangBo717** [SonarOpenCommunity/sonar-cxx#2208]
**Before you create a new issue**
- Is it really a _cxx-plugin_ issue or a general _SonarQube_ issue? To track _SonarQube_ issues use the [community from SonarSource](https://community.sonarsource.com/) please.
- Please read the [Wiki](https://github.com/SonarOpenCommunity/sonar-cxx/wiki) first, maybe you will find a solution there.
- Please [turn debug info on](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information) and reproduce your issue. The debug info in the log file could help to solve or locate the issue.
- Please check if there is not already a [bug report](https://github.com/SonarOpenCommunity/sonar-cxx/issues) for your issue.
[sonar-scanner.log](https://github.com/SonarOpenCommunity/sonar-cxx/files/6724085/sonar-scanner.log)

**Describe the bug**
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/84835602/123595174-2ddf5c80-d823-11eb-8649-4a20bdc5cfd4.png)
![image](https://user-images.githubusercontent.com/84835602/123595270-4a7b9480-d823-11eb-9cee-0752b4245023.png)

**Desktop (please complete the following information):**
 - OS: centos 7
 - SonarQube version: 8.9.1.44547 LTS
 - cxx plugin version: 2.0.3.2771
 - sonar-scanner version: 4.6.2.2472
 
**Additional context**
When I execute "sonar-scanner" in the "hello_world" porject, sonarqube produce an issue as shown in the figure above.
May the latest cxx plugin still run on the latest sonarqube?

**Comment by OuyangBo717** [comment]
ok，I have get the current result. But I don't know how set the appropriate check rulers for clang-tidy or cppcheck, do you have any good advice? Moreover, I can't find the way that execute the "googletest_project", please you can provide the detailed operating instructions? thanks.

**Comment by guwirth** [comment]
Hello @OuyangBo717,

this two pages are a good starting point:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files

Regards,

**Comment by OuyangBo717** [comment]
Hi guwirth, when I run googletest_project in sonar-cxx/integration-tests/testdata/googletest_project, the test coverage is 0. the detailed info is below:
![image](https://user-images.githubusercontent.com/84835602/124086680-e0155f00-da83-11eb-9259-719d99df2fc0.png)
but the test code have covered the Bar::foo() function, what reason about this problem?  thank you very much for any help!

**Comment by OuyangBo717** [comment]
The report.xml content is as follows:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="11" failures="4" disabled="2" errors="0" time="0.102" timestamp="2021-06-30T00:08:45" name="AllTests">
  <testsuite name="Fixture2" tests="2" failures="1" disabled="0" errors="0" time="0.001" timestamp="2021-06-30T00:08:45" filename="trash">
    <testcase name="tc1_good" status="run" result="completed" time="0" timestamp="2021-06-30T00:08:45" classname="Fixture2">
<properties>
<property name="filename" value="tests/unittests//home/sonar/code/sonar-cxx/integration-tests/testdata/googletest_project/tests/unittests/test_fname_in_both.cc"/>
</properties>
    </testcase>
    <testcase name="tc1_good" status="run" result="completed" time="0.001" timestamp="2021-06-30T00:08:45" classname="Fixture2">
      <failure message="/home/sonar/install/googletest-1.10.x/googletest/src/gtest.cc:2332&#x0A;Failed&#x0A;All tests in the same test suite must use the same test fixture&#x0A;class, so mixing TEST_F and TEST in the same test suite is&#x0A;illegal.  In test suite Fixture2,&#x0A;test tc1_good is defined using TEST_F but&#x0A;test tc1_good is defined using TEST.  You probably&#x0A;want to change the TEST to TEST_F or move it to another test&#x0A;case." type=""><![CDATA[/home/sonar/install/googletest-1.10.x/googletest/src/gtest.cc:2332
Failed
All tests in the same test suite must use the same test fixture
class, so mixing TEST_F and TEST in the same test suite is
illegal.  In test suite Fixture2,
test tc1_good is defined using TEST_F but
test tc1_good is defined using TEST.  You probably
want to change the TEST to TEST_F or move it to another test
case.]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="ts_one" tests="1" failures="0" disabled="0" errors="0" time="0" timestamp="2021-06-30T00:08:45">
    <testcase name="tc_one_good" status="run" result="completed" time="0" timestamp="2021-06-30T00:08:45" classname="ts_one" />
  </testsuite>
  <testsuite name="Component1Test" tests="4" failures="2" disabled="1" errors="0" time="0.051" timestamp="2021-06-30T00:08:45">
    <testcase name="foo_successfull" status="run" result="completed" time="0.05" timestamp="2021-06-30T00:08:45" classname="Component1Test" />
    <testcase name="foo_failing" status="run" result="completed" time="0" timestamp="2021-06-30T00:08:45" classname="Component1Test">
      <failure message="/home/sonar/code/sonar-cxx/integration-tests/testdata/googletest_project/tests/unittests/test_component1.cc:17&#x0A;Expected equality of these values:&#x0A;  bar.foo()&#x0A;    Which is: 111&#x0A;  112" type=""><![CDATA[/home/sonar/code/sonar-cxx/integration-tests/testdata/googletest_project/tests/unittests/test_component1.cc:17
Expected equality of these values:
  bar.foo()
    Which is: 111
  112]]></failure>
    </testcase>
    <testcase name="foo_throwing" status="run" result="completed" time="0.001" timestamp="2021-06-30T00:08:45" classname="Component1Test">
      <failure message="unknown file&#x0A;Unknown C++ exception thrown in the test body." type=""><![CDATA[unknown file
Unknown C++ exception thrown in the test body.]]></failure>
    </testcase>
    <testcase name="DISABLED_foo_skipped" status="notrun" result="suppressed" time="0" timestamp="1969-12-31T16:00:00" classname="Component1Test" />
  </testsuite>
  <testsuite name="Fixture1" tests="3" failures="1" disabled="1" errors="0" time="0.05" timestamp="2021-06-30T00:08:45">
    <testcase name="test_successfull" status="run" result="completed" time="0.05" timestamp="2021-06-30T00:08:45" classname="Fixture1" />
    <testcase name="test_failing" status="run" result="completed" time="0" timestamp="2021-06-30T00:08:45" classname="Fixture1">
      <failure message="/home/sonar/code/sonar-cxx/integration-tests/testdata/googletest_project/tests/unittests/test_two_fixtures.cc:14&#x0A;Expected equality of these values:&#x0A;  1&#x0A;  12" type=""><![CDATA[/home/sonar/code/sonar-cxx/integration-tests/testdata/googletest_project/tests/unittests/test_two_fixtures.cc:14
Expected equality of these values:
  1
  12]]></failure>
    </testcase>
    <testcase name="DISABLED_test_skipped" status="notrun" result="suppressed" time="0" timestamp="1969-12-31T16:00:00" classname="Fixture1" />
  </testsuite>
  <testsuite name="TS" tests="1" failures="0" disabled="0" errors="0" time="0" timestamp="2021-06-30T00:08:45">
    <testcase name="test_successfull" status="run" result="completed" time="0" timestamp="2021-06-30T00:08:45" classname="TS">
<properties>
<property name="filename" value="tests/unittests//home/sonar/code/sonar-cxx/integration-tests/testdata/googletest_project/tests/unittests/test_fname_in_tc.cc"/>
</properties>
    </testcase>
  </testsuite>
</testsuites>

**Comment by OuyangBo717** [comment]
![image](https://user-images.githubusercontent.com/84835602/124088591-a9404880-da85-11eb-94f9-b2737adae940.png)

**Comment by guwirth** [comment]
Hello @OuyangBo717,

please follow the hints of https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cobertura.reportPaths

Regards,

**Comment by OuyangBo717** [comment]
Thank you for your answers, I have got the correct result. But why the number of the errors test is 0?  I think the rigth number is 2.
the first :
![image](https://user-images.githubusercontent.com/84835602/124098610-42c02800-da8f-11eb-917e-891937f711dd.png)
the second :
![image](https://user-images.githubusercontent.com/84835602/124098730-65ead780-da8f-11eb-8fe6-fb26ded1bf7a.png)
Is my understanding of errors unit test wrong?

**Comment by OuyangBo717** [comment]
![image](https://user-images.githubusercontent.com/84835602/124099192-dabe1180-da8f-11eb-8e1f-aa1c20aab614.png)

**Comment by guwirth** [comment]
Hi @OuyangBo717,

this is the code reading the test files:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/tests/xunit/XunitReportParser.java

Description is here:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.xunit.reportPaths

Maybe you can compare it with your report. 

Regards,

**Comment by OuyangBo717** [comment]
Thanks. @guwirth 

Hi guwirth, I just found another problem, the detailed infomation is below:
![image](https://user-images.githubusercontent.com/84835602/124210042-4ef2c680-db1d-11eb-9228-651d9242fe80.png)
When I see three failed unit tests, I want to find the failed unit test in the test code, but I can't find it.
can you tell me why? 

Regards

**Comment by guwirth** [comment]
Hi @OuyangBo717,

> I want to find the failed unit test in the test code, but I can't find it.
can you tell me why?

thanks for the hint, looks like a bug. 
Do you know if this is working in other programming languages?

Seems `Errors, Failures, Skipped` are displayed now, how did you solve it?

Regards,

**Comment by guwirth** [comment]
Hi @OuyangBo717,

did you have the time to look how this behaves in other from SonarSource maintained languages (e.g. Java)?
Would be interesting to know if this is a general or only a cxx issue?

Regards,

**Comment by guwirth** [comment]
How SonarQube is doing it https://github.com/SonarSource/sonarqube/blob/900af07a23832dc8357eb49c3dd997976686ff29/sonar-scanner-engine/src/main/java/org/sonar/scanner/genericcoverage/GenericTestExecutionReportParser.java
https://docs.sonarqube.org/latest/analysis/generic-test/

**Comment by guwirth** [comment]
Python: https://github.com/SonarSource/sonar-python/blob/master/sonar-python-plugin/src/main/java/org/sonar/plugins/python/xunit/PythonXUnitSensor.java

**Comment by guwirth** [comment]
Improved documentation, I think that's all we can do right now:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.xunit.reportPaths
