### ISSUE TITLE
Cppcheck 2.5 support

### ISSUE THREAD

**Issue by Nekto89** [SonarOpenCommunity/sonar-cxx#2214]
Cppcheck 2.5 was released 5 days ago.

Based on release notes it has new checks that aren't present in sonar-cxx:
https://github.com/danmar/cppcheck/releases/tag/2.5

> New checks:
>     suspicious container/iterator assignment in condition
>     rethrow without current handled exception

**Comment by guwirth** [comment]
Hi @Nekto89,

thanks for the feedback. We will add it with the next release. 

Regards,

**Comment by guwirth** [comment]
Hi @Nekto89, you can test it with latest snapshot…
