### ISSUE TITLE
Managed old deprected rules used on sonar 6.7.3

### ISSUE THREAD

**Issue by dbochard** [SonarOpenCommunity/sonar-cxx#2217]
I just ubgrade our sonar server from 6.7.3 with CXX plugin 1.2.2 to sonar 8.9.1 with CXX plugin 2.0.4 (build 2806)

Some rules used in 6.7.3 was deprecated and are no more available : 
- Magic-number should not be used
- Commented code not allowed
- Useless parenthesis around expressions...
- Control flow statement if/switch,try and iterators should not be nested too deeply
- if/else/for/while/do statements should always use curly brace

for `Magic-number should not be used` I found 2 rules : 
- `cppcoreguidelines-avoid-magic-numbers`
- `readability-magic-numbers`

I need to add an analysis `clangtidy` in my jenkins to use them ?

for `Commented code not allowed` `Control flow statement if/switch,try and iterators should not be nested too deeply` and `Useless parenthesis around expressions...`, I do not find new rules for this detection

for `if/else/for/while/do statements should always use curly brace` I found `Full block {} expected in the control structure` I need to add an analysis `vera++` in my jenkins to use it ?

**Comment by guwirth** [comment]
Hello @dbochard,

With the limited capacity we have here in the project, it is unfortunately not possible to recreate the multitude of checks that a CppCheck, Clang-Tidy, etc. offer. Even SonarSource has a hard time with their commercial plugin. We have therefore decided to remove all static code analysis checks and refer to external tools instead (we don't want to reinvent the wheel). If checks are missing I would recommend you to feed them into one of the external open source tools as a feature request.

Please ask in their forums for tool support.

Regards,
