### ISSUE TITLE
Plugin scan is failed sometimes

### ISSUE THREAD

**Issue by ranIlani** [SonarOpenCommunity/sonar-cxx#2219]
We are getting errors from CXX plugin says that Java version is incompatible, although we removed this java version from the machine.
the error occurs not all the time, but sometimes.
sonarQube version:  8.6.1 (build 40680)
sonar scan is running via Azure dev ops.

Can you help please?

##[error]java.lang.IllegalStateException: The plugin [cxx] does not support Java 1.8.0_291
java.lang.IllegalStateException: The plugin [cxx] does not support Java 1.8.0_291
##[error]at org.sonar.core.platform.PluginClassLoader.instantiatePluginClasses(PluginClassLoader.java:133)
	at org.sonar.core.platform.PluginClassLoader.instantiatePluginClasses(PluginClassLoader.java:133)
##[error]at org.sonar.core.platform.PluginClassLoader.load(PluginClassLoader.java:67)
	at org.sonar.scanner.bootstrap.ScannerPluginRepository.start(ScannerPluginRepository.java:65)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.sonar.core.platform.PluginClassLoader.load(PluginClassLoader.java:67)
	at org.sonar.scanner.bootstrap.ScannerPluginRepository.start(ScannerPluginRepository.java:65)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
##[error]at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)

**Comment by guwirth** [comment]
Hi @ranIlani,

you have to ensure to run the scanner with Java 11 (and not Java 8), see Wiki:

* tested and released for **SonarQube 7.9 LTS** and **SonarQube 8.9 LTS** with **Java 11** (other versions are not supported)
  - The plugin requires Java 11 on scanner and server side: install JDK 11 (e.g http://jdk.java.net/archive/) and update `JAVA_HOME` to point to the installation directory.
  
Regards,

**Comment by ranIlani** [comment]
Java 8 isn't installed on the machine.
only Java SE 16.0.1

**Comment by ranIlani** [comment]
another question - we scan the code on a huge project. the result was about 50k code smells, 
but not even 1 bug or vulnerability.
we think it's a bit weird, do you have any explanation?
should we use any additional plugin?

**Comment by guwirth** [comment]
Hi @ranIlani,

> the result was about 50k code smells,

Can't say much to this. Don't know which static code tools you are using?

First of all Technical Debt is mainly about Code Smells and not Bugs.
* The definition/classification of SonarQube is: https://docs.sonarqube.org/latest/extend/adding-coding-rules/#header-4
* In early days there where only violations and no split to Bugs, Vulnerabilities and Code Smells.
* Bugs leads always to failed Quality Gates, that's the main reason why we tend to define it Code Smell and not Bug.
* The classification for the different tools (Cppcheck, Clang-Tidy, ...) were done from different people in the past. In case you have proposals to classify rules different, we are always happy to receive suggestions.

Regards,
