### ISSUE TITLE
Analysis successful for c/c++ codebase with Java 8 version and fails for other languages EG: Maven build fails

### ISSUE THREAD

**Issue by alok347** [SonarOpenCommunity/sonar-cxx#2222]
I have currently installed Sonar-cxx plugin version 2.x on SonarQube-7.9 LTS version. The reason I am writing to you is because as per the documentation, Sonar-cxx supports only java-11 for analysis. However, i noticed that when i ran the analysis for my c/c++ codebase using sonar-cxx plugin it succeeded with Java-1.8 and javac-1.8 version. And subsequently analysis failed for my other maven project with error as below " Java version not supported"
![image](https://user-images.githubusercontent.com/5407529/127030371-99690b68-42dd-47e4-870a-31a5b1418d99.png)

Fix:

Updated the java and javac version to version 11 and analysis ran fine for all the languages.

I think its a bug in the current version. Let me know thoughts on the same.

Regards,
Alok Singh

**Comment by alok347** [comment]
Hi @guwirth ,

Thank you for the info. 

**So the intended behaviour is to successfully complete the c/c++ codebase analysis even with java -8 version? The reason i say so, is because the analysis of other languages using some other plugin(eg: a java code) fails with the error saying that **sonar-cxx** require java-11 for analysis. sonar-cxx plugin does not play any part in java or any other language code-base and still the analysis fails. But for C/C++ code where it actually should complaint about the java version 8 and fail the analysis, it succeeds in completing the analysis without any issue.** 

Recommendation: C/C++ project analysis should also fail if the java version on client is not java-11.

Let me know your thoughts on this.

Regards,
Alok Singh

**Comment by guwirth** [comment]
Hi @alok347,

no, the point is to use Java 11 for all languages. Java is backward compatible, means components written for Java 8 should also run under Java 11 (but not the other way around).

Regards,

**Comment by alok347** [comment]
Hi @guwirth ,

Got it. Thank you for taking time for answering my query.
Appreciate it!

Regards,
Alok
