### ISSUE TITLE
SonarQube not analyzing my cppcheck report.

### ISSUE THREAD

**Issue by esend7881** [SonarOpenCommunity/sonar-cxx#2226]
I wanted to link a SOF question related so SonarQube and sonar-cxx not analyzing my cpp-report file. All the details, including the commands to reproduce the issue are in the SOF page.

https://stackoverflow.com/questions/68657430/import-cppcheck-report-into-sonarqube

Posting here to get attention from any people who frequent these issue boards.

**Comment by guwirth** [comment]
Hi @esend7881,

please read 
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cppcheck.reportPaths

most likely it’s https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles

Regards,
