### ISSUE TITLE
C++ plugin compatibility issue with Java 8 version

### ISSUE THREAD

**Issue by vbhvjari** [SonarOpenCommunity/sonar-cxx#2239]
Hi,

We have recently migrated our SQ application from 7.1 to 7.9.6 LTS.
In older setup (SQ 7.1), we were using cxx plugin with version 1.0.0 and it was working as expected.
Since cxx 1.0.0 is not compatible with SQ version 7.9.6, we have updated cxx plugin version to 2.0.4.

Since we have updated plugin version, we are getting java compatibility issue as below:

```
2021-08-30T09:07:15.833754637Z [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar (default-cli) on project rc-pipeline: The plugin [cxx] does not support Java 1.8.0_181: org/sonar/plugins/cxx/CxxPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 -> [Help 1]
2021-08-30T09:07:15.833802573Z [ERROR]
```
Here, please note that source code is at JAVA 8 version and before plugin version update, we were not getting any error.
Even though we have disabled this plugin from UI, it’s still getting referenced during sonar analysis execution. Attaching snap of it for the reference.

We are getting this error for all java based projects in which cxx plugin is neither intended to be used nor to be considered during sonar analysis execution.
<img width="878" alt="Screenshot 2021-08-30 at 5 07 51 PM" src="https://user-images.githubusercontent.com/50916681/131448532-ead9f4b1-86b9-40f2-aa85-874dee39d397.png">

Can someone please help me resolve the issue ?

Thanks,
Vaibhav Jariwala

**Comment by guwirth** [comment]
Hi @vbhvjari,

that’s intended behavior. On scanner and server side you need Java 11 to use the plugin. Please have a look to release and upgrade notes. 

* https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-2.0.0
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-the-Plugin

Regards,
Günter

**Comment by vbhvjari** [comment]
Hi @guwirth ,
Thanks for replying back.

I do understand that java 11 is required at sonar scanner and sonar server level for cxx plugin 2.x.
However, I want to know that if source code is at java 8 and sonar scanner/sonar server is at java 11, does cxx plugin 2.x work ?

Thanks,
Vaibhav Jariwala

**Comment by guwirth** [comment]
Hi,

> I do understand that java 11 is required at sonar scanner and sonar server level for cxx plugin 2.x.

Yes. Java 11 should also work with other plugins because 11 is backward compatible to 8.

> However, I want to know that if source code is at java 8 and sonar scanner/sonar server is at java 11, does cxx plugin 2.x work ?

The SonarQube Java plugin should run under Java 11 and Java 8. The used Java VM has nothing to do with the supported source code versions. You have to read in the Java plugin manual from SonarQube which source code versions are supported.

Regards,

**Comment by vbhvjari** [comment]
Thanks for confirming it.
In short, for cxx plugin 2.x, sonar scanner and sonar server should have java 11 and source code of the project can be at java 8.

**Comment by guwirth** [comment]
Hi @vbhvjari,

for completeness: here is the link to the Java documentation https://docs.sonarqube.org/latest/analysis/languages/java/

Regards,
