### ISSUE TITLE
Does sonar-cxx support pull request decoration for a PR from forked repository?

### ISSUE THREAD

**Issue by neothenil** [SonarOpenCommunity/sonar-cxx#2249]
Hello,

I'm using sonarqube and sonar-cxx in my company. The pull request decoration functionality works well for PR from inner repository. But when the pull request is opened from a forked repository, this functionality seems do not work. I've googled similar questions, and the most related question is:
[How to use SonarCloud with a forked repository on GitHub?](https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363)
But it's SonarCloud, and the problem seems just a result of security concerns. I want to make sure whether sonar-cxx supports pull request decoration for a PR from forked repository and if so how to achieve it.

The platforms used in my company is: Bitbucket Server & Jenkins & SonarQube Community edition. I configured a Jenkins job to  execute sonar-scanner's pull request analysis. For a PR from forked repository, I added the forked repository as a remote and checked out the branch to be merged. And sonar-scanner is executed with `-Dsonar.pullrequest.key=${pr_id} -Dsonar.pullrequest.branch=${pr_from_branch}  -Dsonar.pullrequest.base=${pr_to_branch}`.

**Comment by guwirth** [comment]
Hi @neothenil,

think that is a SonarQube limitation: https://jira.sonarsource.com/browse/MMF-1371. 
Please ask SonarSource for help. That has nothing to do with the cxx plugin. 

Regards,

**Comment by neothenil** [comment]
@guwirth Does this mean sonar-cxx would support it only after sonarqube supports it?

**Comment by guwirth** [comment]
> Does this mean sonar-cxx would support it only after sonarqube supports it?

@neothenil yes. As this is a SonarQube requirement they have to solve it first.

**Comment by neothenil** [comment]
OK. Thanks for your reply. I'm closing this issue.
