### ISSUE TITLE
False positive/Won't fix issues are reset after upgrade from 1.x to 2.x

### ISSUE THREAD

**Issue by yuliym** [SonarOpenCommunity/sonar-cxx#2257]
**Describe the bug**
After we upgraded plugin from 1.3.1 to 2.0.5 issues resolution status reset 

**To Reproduce**
1. Upgrade plugin
2. Run sonar for existing project
3. All issues that previously were reviewed as False positive/Won't fix become Unresolved 

**Expected behavior**
Keep resolution state after upgrade

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - SonarQube version: 7.9
 - cxx plugin version: 2.0.5
 - PVS-Studio Plugin - 7.14

**Comment by guwirth** [comment]
Hi @yuliym,

thanks for your feedback. 

Think root cause is that we renamed the language id of the plugin. Did you follow the steps described in https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-the-Plugin?

Regards

**Comment by yuliym** [comment]
Hi @guwirth 
Yes I followed that steps before actual upgrade and restored fixed quality profile before new scan however all False Positive/Won't fix issues now marked as Unresolved. Any advise here ?
