### ISSUE TITLE
Analysing the project takes extremely long time

### ISSUE THREAD

**Issue by Artalus** [SonarOpenCommunity/sonar-cxx#2267]
**Describe the bug**
Basically, see #2228. I ran `sonar-scanner` on our project over night, and it did not finish after 18 hours. I used this command:
```
sonar-scanner
  -Dsonar.projectKey=trassir
  -Dsonar.sources=./source
  -Dsonar.host.url=****
  -Dsonar.login=****
  -Dsonar.password=****
  -Dsonar.pvs-studio.reportPath=./pvs/pvs-report.xml
  -Dsonar.pvs-studio.licensePath=./pvs/pvs.license
  -Dsonar.cxx.jsonCompilationDatabase=./build/compile_commands.json
  -Dsonar.inclusions='**/*.cpp,**/*.h,**/*.c'
  -Dsonar.exclusions='...some paths...'
```
From my understanding, the scanner completely ignores the `compile_commands.json` file and tries to analyze *everything* there is in working directory. Unless I provided `exclusions=`, I could see multiple parsing errors in unrelated files, like sources of ffmpeg that are checked our with our dependencies repo. It also does this in single-threaded mode.

When using `-Dsonar.cxx.squid.disabled=true`, the scanner finishes in about 1-2minutes, but does not provide any syntax highlighting (as expected).

Ways to improve the situation that I can see:
- optimize the scan process itself (preprocessing, etc.), as was mentioned in https://github.com/SonarOpenCommunity/sonar-cxx/issues/2228#issuecomment-898237352
- process files in parallel to utilize all cores available on the machine (16 in our case)
- process only the files mentioned in compilation database and ignore any thirdparty headers.

**To Reproduce**
Run scanner over several millions LOC, I guess?..

**Expected behavior**
The scan to complete in reasonable amount of time

**Desktop (please complete the following information):**
 - OS: Linux
 - SonarQube version: Community Edition 8.9.2 (build 46101)
 - cxx plugin version: 2.0.6 master snapshot `f267915ee0878040af16339f6e3e4bd4544ffe38`
 - sonar-scanner version: 4.6.2.2472

**Comment by guwirth** [comment]
Should be improved with #2410
