### ISSUE TITLE
any plan to support sonarqube 8.9.x LTS ?

### ISSUE THREAD

**Issue by zmoon460** [SonarOpenCommunity/sonar-cxx#2271]
I upgraded sonarqube the latest lts version 8.9, but it can't start normally. Is there a plan to support 8.9?

**Comment by guwirth** [comment]
Hi @guwirth,

SQ 8.9 is already supported. The two links provide more information:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Upgrade-the-Plugin
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compatibility-Matrix

Regards
