### ISSUE TITLE
Why do you decide to delete the rule Control flow statements \"if\", \"switch\", \"try\" and iterators should not be nested too deeply? What could be the replacement rule?

### ISSUE THREAD

**Issue by antoniorv75** [SonarOpenCommunity/sonar-cxx#2281]
Good bye

Fordward 1.2.2 version you decided to delete the rule "Control flow statements \"if\", \"switch\", \"try\" and iterators" ..., and I'm not able to find any replacement for this rule.
We are using this rule with an old sonarqube version that still being compatible , but the problem is we have to mantain two sonarqubes at once, because we doesn't able to integrate with sonar 8.9.2 LTS this rule already.
Could you give me an alternative solution?, does exists any substitution rule that replace the absence of this rule?. I don't understand the decision of deleting the rule becase in the development version this rule still exists, and we have to pass this rule because it is mandatory in order to accomplish with the client requirements contract.

Thank you in advance
Kind regards

**Comment by guwirth** [comment]
Hi @antoniorv75,

the decision with 2.x was to remove all static code analysis rules and use external tools instead. The main intension of the cxx plugin is: "This plugin adds C++ support to SonarQube with the focus on **integration of existing C++ tools**" - we don't like to reinvent the wheel.  Maybe Cppcheck or ClangTidy have a corresponding rule?

Regards,

**Comment by antoniorv75** [comment]
Hi @guwirth , thank you for your answer. Really I  don't know if cppcheck has this rule implemented. We are using cppcheck previously to sonarscanner in order to analyze the code and afterwards we pass generated report with cppcheck to sonnarscaner. Currently, we are not realise if this rule is having checked or not, or if there is a way to  indicate to cppcheck to check it. We will try to investigate it but I'm afraid could be a just a little complex, I guess.

Thank you for your answer, I appreciate it very much
