### ISSUE TITLE
Adding custom rules for cppcheck MISRA plugin

### ISSUE THREAD

**Issue by andrej-at-elaphe** [SonarOpenCommunity/sonar-cxx#2284]
My company wants to use sonar(-cxx) to check our code's MISRA compliance. We're using the [MISRA plugin](https://cppcheck.sourceforge.io/misra.php) for cppcheck.

Adding these rules on our own instance would work, but I can also contribute them here.
Since MISRA is copyrighted, we can't use the rule texts in any way here. The cppcheck MISRA plugin handles this by having you supply a misra.txt file with the rule messages/explanations. We'd have to find a similar solution if we were to include this into sonar-cxx.

The MISRA plugin doesn't implement rules for all MISRA checks, it relies on builtin cppcheck rules for some checks. For example, the MISRA rule 5.3 is covered by the *shadowVariable* check in cppcheck (*cppcheck:shadowVar*). I'd like to add this to the description of said rule, and tag it with misrac2012.

## XML output from cppcheck MISRA checks
Here's some example output:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<results version="2">
    <cppcheck version="2.6"/>
    <errors>
        <error id="misra-c2012-4.1" severity="style" msg="Octal and hexadecimal escape sequences shall be terminated" verbose="Octal and hexadecimal escape sequences shall be terminated" file0="thirdparty/Unity/src/unity.c">
            <location file="thirdparty/Unity/src/unity.c" line="29" column="62"/>
        </error>
        <error id="misra-c2012-4.1" severity="style" msg="Octal and hexadecimal escape sequences shall be terminated" verbose="Octal and hexadecimal escape sequences shall be terminated" file0="thirdparty/Unity/src/unity.c">
            <location file="thirdparty/Unity/src/unity.c" line="30" column="62"/>
        </error>
    </errors>
</results>
```

## On our own instance

Is there a programmatic way of adding custom cppcheck rules? How about tagging existing rules and adding comments? I wouldn't want to do this through the GUI or through crawling + sending requests. How would I go about this? Is there an xml file I can edit somewhere for the user-defined checks? Is this stored in a file or the database? Do you have a REST API?

## Contributing to sonar-cxx

If you'd accept this as a contribution, where can I get started with adding these rules? Just [here](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/cppcheck.xml), by id? Would this work:

```xml
  <rule>
    <key>misra-c2012-4.1</key>
    <name>MISRA C2012 rule 4.1</name>
    <description>
      <![CDATA[
      <p>
MISRA C2012 rule 4.1
</p>
]]>
    </description>
    <tag>cwe</tag>
    <type>BUG</type>
    <remediationFunction>LINEAR</remediationFunction>
    <remediationFunctionGapMultiplier>5min</remediationFunctionGapMultiplier>
  </rule>
```

What about the copyrighted rule texts?

**Comment by guwirth** [comment]
Hi @andrej-at-elaphe,

a lot of questions :-) , try to answer them...

> Is there a programmatic way of adding custom cppcheck rules?

Yes, you can use the WEB API or the Generic Issues Import Format:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/CXX-Custom-Template-Rules
* https://docs.sonarqube.org/latest/analysis/generic-issue/

> Is there an xml file I can edit somewhere for the user-defined checks?

The built-in rules of the cxx plugin for CppCheck are defined in the XML file below. You are welcome to extend this list:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/cppcheck.xml

**But as noted by yourself, we must be careful not to violate the copyright!**

Means there are three ways:
1. Creating the rules on the fly with Generic Issues Import Format.
2. Adding additional rules via WEB API to the cxx CppCheck rules via template rules.
3. Extending the list of built-in rules in the cxx plugin and release a new version.

Hope this helps!

Regards,
