### ISSUE TITLE
Analysis of Maven project failed due to Sonar-cxx plugin Java error

### ISSUE THREAD

**Issue by alok347** [SonarOpenCommunity/sonar-cxx#2285]
Hi Team,

We are planning to upgrade to **SonarQube 7.9/8.9** and have currently installed **Sonar-cxx plugin**(**2.0.4 version**) on demand of few customers on the QA environments.
Analysis of c/c++ projects completes successfully using sonar-cxx plugin with the java version 8 and java version 11. 

![image](https://user-images.githubusercontent.com/5407529/144973946-2d0ea4c3-4a51-4131-ad39-846af860ffb1.png)
![image](https://user-images.githubusercontent.com/5407529/144973971-60ba6c0e-444e-48fc-87fb-099beb2b537e.png)

However, the real issue arises when the analysis of a maven based project fails due to sonar-cxx plugin exception. If the customer has java 8 version installed on the client machine, this exception occurs for a java code-base, which does not require sonar-cxx plugin. 

![image](https://user-images.githubusercontent.com/5407529/144976342-18f530ce-e775-4dbf-83e0-8db41e3cb1f5.png)
![image](https://user-images.githubusercontent.com/5407529/144976453-d4fab29d-a7b4-4a02-8554-3c68d42593df.png)

**Customer cannot upgrade to java 11** on the client machine as his project's dependency is on java 8. This is a major blocker for us and for our upgrade plan to SonarQube 8.9 version.

Please suggest us a workaround if any available or some alternative to proceed further with this issue.
Also, i see that an old version of CXX plugin supports java 8 but it only supports SonarQube 7.9 and might support old rules and missing out in the new ones. Would you recommend using CXX plugin version 1.3.3 on SonarQube 7.9/8.9 application.

Regards,
Alok Singh

**Comment by guwirth** [comment]
Hi @alok347,

> Customer cannot upgrade to java 11 on the client machine as his project's dependency is on java 8

the cxx plugin needs Java 11 on scanner and server side. This is normally no issue because Java 11 is backward compatible. Also the Java plugin does support Java 8 analysis running the scanner with Java 11. 

* The plugin requires Java 11 on scanner and server side: install JDK 11 (e.g http://jdk.java.net/archive/) and update JAVA_HOME to point to the installation directory.

It’s possible to install Java 8 and Java 11 side by side on a machine and use Java 11 for the scanner only. Switch JAVA_HOME to Java 11 in your bash. 

Regards,

**Comment by alok347** [comment]
@guwirth Thanks for the details. However, I still have one question as to why doesnt the c/c++ analysis fails if the CXX plugin requires java 11 on the client side(has default java 8 version). The analysis of c/c++ works as expected with the default java 8 version. Note: i did not set the JAVA_HOME path. 

But the analysis of a java project fails with the same java 8 version and cxx plugin starts complaining about the it.

Please let me know more details about this certain behaviour. 


Or are we looking at a BUG here.


Regards,
Alok Singh

**Comment by guwirth** [comment]
Hi @alok347,

not sure if I understand your question.

Looking to your LOG file you get:
![grafik](https://user-images.githubusercontent.com/6077367/145167981-531b1780-fea3-4b4e-98d1-8d6f6e0f2523.png)
![grafik](https://user-images.githubusercontent.com/6077367/145167996-fe622de8-99e9-4bfd-9160-534a9c1299c0.png)

SonarQube is always loading all plugins independent if you are using them or not. Even if you analyse a Java project, the CXX plugin is still loaded. Already when loading the plugin the error is generated (without really using it). As far as I know SonarSource is working on it, that you can exclude plugins for an analysis.

Regards,

**Comment by alok347** [comment]
Hi @guwirth 

I am pointing to the below error:

![image](https://user-images.githubusercontent.com/5407529/145171234-7129539e-c5ba-41ff-a330-c85131dc0ca9.png)

My point is **c/c++ project** **analysis should also fail** with "**The Plugin [cxx] does not support Java 1.8.0_251" exception**. But to my surprise **the analysis completes successfully**. The SonarQube workflow of analyzing any project is similar in both the cases. However, CXX plugin only throws this exception during the analysis of Java/maven project. 

**_Let consider the below cases:_**

Client Side has only Java 8 version installed.

![image](https://user-images.githubusercontent.com/5407529/145182671-4c9f4154-3cb1-4e5b-a53e-b12798cc9e1a.png)


**Case 1**: **C/C++ Project**

Analysis is initiated for a C/C++ project on the client machine. SonarQube Loads all the plugins and the plugin corresponding to the language is automatically detected and the analysis completes. In this case CXX plugin is used for analysing the C/C++ project and the analysis is completed successfully. 

Note: In Case 1 CXX plugin does not throw the java 8 exception and the analysis of c/c++ project completes.

**Case 2**: **Maven Project(java code base)**

Analysis is initiated for a maven project on the client machine. SonarQube loads all the plugins and post the download of plugins , the analysis fails with the CXX plugin exception "**org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project axs-eclipseui-root-pom: The plugin [cxx] does not support Java 1.8.0_251**". 

Note: The CXX plugin interrupts and breaks the analysis complaining about the java version on the client machine.

Why would even CXX plugin complain or throw exception on a Java Project, when this plugin is not even used for the analysis of java project? This would have been the ideal case with the c/c++ project. However, seeing such behavior in  a java code base where this plugin should ideally ignore it, throws the exception.


![image](https://user-images.githubusercontent.com/5407529/145182075-25c7fd0e-dcb1-4846-87ab-934956b53805.png)


Please let me know your views on the same.

Regards,
Alok Singh

**Comment by alok347** [comment]
>

**Comment by guwirth** [comment]
Hi @alok347,

> Case 1

Can only work if there is a Java 11 somewhere in the path and used. In all other cases you get the Java 8 error messages. 

> Case 2 / Why would even CXX plugin complain or throw exception on a Java Project

Think this is because the SQ framework doesn't know anything about the plugin until it is loaded and some entry points are called. The framework must at least ask the plugin for which languages it is responsible and which sensors it contains. As far as I can see, it already fails here. That's also the reason why you get an error in a Java project in the cxx plugin, it's during asking "What kind of plugin are you?" at scanner start.

https://portal.productboard.com/sonarsource/3-sonarqube/c/158-remove-languages-from-an-instance

Regards,

**Comment by jcmendez-guerrero** [comment]
Similar issue was faced with perl community plugin https://github.com/sonar-perl/sonar-perl/issues/117 in case is helpful for this case.

According to sonar specification, both JDK should be accepted

**Comment by dlt-lee** [comment]
> Hi @alok347,
> 
> not sure if I understand your question.
> 
> Looking to your LOG file you get: ![grafik](https://user-images.githubusercontent.com/6077367/145167981-531b1780-fea3-4b4e-98d1-8d6f6e0f2523.png) ![grafik](https://user-images.githubusercontent.com/6077367/145167996-fe622de8-99e9-4bfd-9160-534a9c1299c0.png)
> 
> SonarQube is always loading all plugins independent if you are using them or not. Even if you analyse a Java project, the CXX plugin is still loaded. Already when loading the plugin the error is generated (without really using it). As far as I know SonarSource is working on it, that you can exclude plugins for an analysis.
> 
> Regards,

Do you konw hto xclude plugins for an analysis?

**Comment by guwirth** [comment]
Hello @alok347,

I don’t know a possibility that is the reason for:
https://portal.productboard.com/sonarsource/3-sonarqube/c/158-remove-languages-from-an-instance

Regards,
