### ISSUE TITLE
Plugin not picking up cppcheck reports anymore

### ISSUE THREAD

**Issue by theatricshrink** [SonarOpenCommunity/sonar-cxx#2298]
**Describe the bug**
I upgraded from sonarqube 7.9 with cxx 1.3.1 to Sonarqube 8.9.6 with cxx 2.0.6 and I'm now unable to import cppcheck reports. It worked in the previous configuration. I have a multi module project.

**To Reproduce**
1. Create cxx profile and select cppcheck rules
2. Assign to project
3. Set css file suffixes
4. Run analysis using Jenkins

**Expected behavior**
cppcheck reports getting imported

**Desktop (please complete the following information):**
 - OS: linux
 - SonarQube version: 8.9.6
 - cxx plugin version: 2.0.6
 - sonar-scanner version: 4.6.0
 
**Additional context**

Project Properties:
sonar.projectKey=NATIVE_PUBLIC
sonar.projectName=Native
sonar.projectVersion=1.0
sonar.cxx.errorRecoveryEnabled=True
sonar.modules=bg,fg
bg.sonar.projectName=bg
bg.sonar.projectBaseDir=./src/classic/bg
bg.sonar.sources=src
bg.sonar.cxx.cppcheck.reportPaths=cppcheck-report.xml
fg.sonar.projectName=fg
fg.sonar.projectBaseDir=./src/classic/fg
fg.sonar.sources=.
fg.sonar.cxx.cppcheck.reportPaths=cppcheck-report.xml

**Comment by guwirth** [comment]
Hi @theatricshrink,

looking to the 2.x release notes you will find:
https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-2.0.0
* #1822 

`SensorContext.module()` was deprecated by SonarSource in the SQ framework.
So I'm sorry to tell you that this feature is no more supported.

Regards,

**Comment by theatricshrink** [comment]
Oh no … I missed that, thanks for pointing it out.
