### ISSUE TITLE
How to scan C language code through this plugin

### ISSUE THREAD

**Issue by preddymm** [SonarOpenCommunity/sonar-cxx#2300]
Hello,

I am not able to scan the C language code. Can someone help me in how to scan it?
I followed every instruction as shown and I am able to do it for C++ but not for C.
Can someone walk through me how to do it?.
I really appreciate your help here.

Thanks

**Comment by guwirth** [comment]
Hello @preddymm,

what exactly is not working?

1. Please turn debug info on to get more information in the LOG file: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-Debug-Information
2. First step is to read (index) source code files: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code. Important is to define the right file suffixes: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.file.suffixes. At the end of page **Scan Source Code** you get help how to read the LOG file.
3. Next step is then https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files

Hope this helps!

Regards,

**Comment by preddymm** [comment]
Hello @guwirth,

Thanks for your quick response.
I am trying to integrate the SonarQube with Jenkins server.
When I try using this plugin for C++ code it was bale to identify the C++ code and able to scan. When I follow the same steps to scan the C code, it is not able to identify the C code. I tried using this extensions as well in sonar.properties file "sonar.cxx.file.suffixes=.c,.h" and I made the File changes in SonarQube server as well.
I am not sure is there any specific things to do to scan the C code. Please help me out.

Thanks

**Comment by guwirth** [comment]
Hello @preddymm,

I’m sorry can’t help you without getting more information.
Please create LOG files and provide the error messages.

Regards,

**Comment by preddymm** [comment]
Could you provide me some documentation on what steps do I need to follow only on targeting the C language?


Thanks,
Chennakeshwar
