### ISSUE TITLE
Uppercase file paths in Xunit reports are changed to lowercase.

### ISSUE THREAD

**Issue by jnicol31** [SonarOpenCommunity/sonar-cxx#2302]
**Describe the bug**
Our tests sources are located in a subdirectory `<subcomponent>/TESTS/<test_dir>`.
However, the Xunit sensor expects them to be in `<subcomponent>/tests/<test_dir>`
In the end, tests fail to be mapped with their test sources, leading to poor information on the UI.

**Example**:
```xml
<testcase result="fail" name="test_something" filename="somecomponent/TESTS/sometest/tst_something.cpp">
```

In the logs:
```
INFO: Processing xUnit report '/home/jenkins/workspace/.../branch/build/report/test_report_something.xml'
WARN: Cannot find the file '/home/jenkins/workspace/.../branch/somecomponent/tests/sometest/tst_something.cpp' in project 'TestProject' with baseDir '/home/jenkins/workspace/.../branch/', skipping
```

**To Reproduce**
1. Move your tests source to an uppercase directory
2. Set your `sonar.tests` property accordingly
3. Update some tests so that they fail or are skipped 
4. Launch the tests and the SQ analysis
5. Watch the logs to find: `WARN: Cannot find the file '<lower cased path>' in projetc <project> with baseDir ...` 

**Expected behavior**
- No errror in logs.
- The failed tests and their source are shown in the UI

**Desktop:**
 - OS: Linux
 - SonarQube version: 9.2.1.49989
 - cxx plugin version: 2.0.6 (build 2921)
 - sonar-scanner version: 4.6.2.2472-linux
 
**Additional context**
The issue seems to be in cxx-sensors/src/main/java/org/sonar/cxx/sensors/tests/xunit/XunitReportParser.java, line 132: why is the resolved path converted to lower case ? (commit 2c2ecbdee70d095d798fb96c1afd1234e7ff9429)

**Comment by guwirth** [comment]
Hello @jnicol31,

thanks for your feedback!

I'd have to take a closer look at that. Think the reason was Windows and Visual Studio? On Windows paths are normally case insensitiv and Visual Studio convert always all paths to lower case. 

https://github.com/SonarOpenCommunity/sonar-cxx/blob/b6a8f3ac3cee5f57a5b8d86206259321fb0dbc99/cxx-sensors/src/main/java/org/sonar/cxx/sensors/tests/xunit/XunitReportParser.java#L132

Regards,

**Comment by guwirth** [comment]
Hi @jnicol31,

not sure if we need to make it lowercase, inside of
https://github.com/SonarOpenCommunity/sonar-cxx/blob/b6a8f3ac3cee5f57a5b8d86206259321fb0dbc99/cxx-sensors/src/main/java/org/sonar/cxx/sensors/tests/xunit/CxxXunitSensor.java#L126
this seems to be already handled
https://github.com/SonarOpenCommunity/sonar-cxx/blob/b6a8f3ac3cee5f57a5b8d86206259321fb0dbc99/cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/CxxReportSensor.java#L70

Regards,

**Comment by jnicol31** [comment]
Hi @guwirth,

thank you for your feedback. I agree with you. The only use I can see  to make it lowercase here is avoiding duplications of test files in Windows in the `testFiles` map field in 

https://github.com/SonarOpenCommunity/sonar-cxx/blob/b6a8f3ac3cee5f57a5b8d86206259321fb0dbc99/cxx-sensors/src/main/java/org/sonar/cxx/sensors/tests/xunit/XunitReportParser.java#L42 

if the case of the paths was to be inconsistent, which might throw an exception in 

https://github.com/SonarOpenCommunity/sonar-cxx/blob/b6a8f3ac3cee5f57a5b8d86206259321fb0dbc99/cxx-sensors/src/main/java/org/sonar/cxx/sensors/tests/xunit/CxxXunitSensor.java#L126 

or distort statistics if a file was to be saved twice.

I wonder whether `java.nio.file.Path` would be a decent replacement for the `testFiles` map key type (not sure about the consistency of the `equals()` and `hashCode()` methods of all implementations...). Otherwise, lower case shall be applied only on non-NIX platforms...

**Comment by guwirth** [comment]
Hi @jnicol31,

thanks for your proposal, also think using path is the better choice:
https://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#equals(java.lang.Object)

Regards,

**Comment by jnicol31** [comment]
Great ! I will submit a pull request in the next few days to fix this.

Regards,
