### ISSUE TITLE
C and C++ languages are  not able to identified with this plugin

### ISSUE THREAD

**Issue by preddymm** [SonarOpenCommunity/sonar-cxx#2308]
Hi,

This plugin was not able to identify the C and C++ code.

I have included this sonar properties as well
[Sample debug file.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/8052243/Sample.debug.file.txt)

sonar.sources=/var/jenkins_home/jobs/bbu-sonar-2/workspace
sonar.sourceEncoding=UTF-8
sonar.cxx.file.suffixes=.cxx,.cpp,.cc,.c,.hxx,.hpp,.hh,.h
sonar.verbose=true

I also enabled the file suffixes in SonarQube UI for all the langauges by following this wiki page
https://github-wiki-see.page/m/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.file.suffixes

[Sample debug file.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/8052240/Sample.debug.file.txt)

I also attached the sample debug file as per your suggestion. Could you please get back to me ASAP.

Thanks

**Comment by guwirth** [comment]
Hi @preddymm,

thanks for your feedback. 

Some of the issues are because of unknown keywords (e.g. `__attribute__`):
```
00:01:30.618 23:38:55.583 DEBUG: [/var/jenkins_home/jobs/bbu-sonar-2/workspace/libffasn1/asn1gser_dec.c:66]:    syntax error: static __attribute__ ( ( format ( printf , 2 , 3 ) ) ) 
```
Please read:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces

That not all include paths are known is not that critical:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.includeDirectories

I see a lot of issues in lines with `->` operator. I will verify this…
```
00:01:30.285 23:38:55.250 DEBUG: [/var/jenkins_home/jobs/bbu-sonar-2/workspace/enb.c:89864]: skip declaration: list_for_each ( c_el , & s -> cell_list ) {
```
But more likely the unknown `list_for_each` is the issue…

Regards,

**Comment by preddymm** [comment]
Hi @guwirth,

Thanks for your quick response.
What configuration settings do you recommend to make this plugin to scan my C and C++ code?

Thanks

**Comment by guwirth** [comment]
Hi @preddymm,

recommended way is normally to provide missing macros with `forceInclude`. 
Samples: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/cxx-sensors/src/main/resources/macros

Regards,

**Comment by preddymm** [comment]
I am unsure how to use macros with this plugin. Could you please pass me the direct parameters to use in sonar.properties?.

Thanks

**Comment by guwirth** [comment]
Hi,

please have a look to the Wiki: https://github.com/SonarOpenCommunity/sonar-cxx/wiki

- **Macros**: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.defines
- There is also the hint to prefer **forceInclude**: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.forceIncludes

Regards,

**Comment by preddymm** [comment]
I tried to use the Macros in couple of ways, it still didn't worked for me. Could you please help me out? I am just a beginner in using the SonarQube server.

I saw that this plugin has a ability to do  json database compilation process similar to developer edition. Could you explain me the process how to do it. I am not seeing the buildwrapper to download here. Is there any alternative for buildwrapper here?


Thanks

**Comment by guwirth** [comment]
Hi @preddymm,

Please have a look to: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.jsonCompilationDatabase

Regards,

**Comment by preddymm** [comment]
@guwirth 
I need your help on predefined macros
Could you give me an example for this  "preprocessor cannot find include file '#include <stdio.h>'" how to define it and where to add after that.

Thanks

**Comment by guwirth** [comment]
Hi @preddymm,

please have a look to our Wiki:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.includeDirectories
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.defines
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Predefined-Macros

Regards,

**Comment by zdg123456** [comment]
@guwirth 
您好，我也遇到了无法识别C语言的问题C++ Parser can't read code.Declaration is skipped
报错如下：
ERROR: Undefined functionlike macro '__has_attribute' assuming 0 
ERROR: Undefined functionlike macro '__has_attribute' assuming 0 
ERROR: Undefined functionlike macro '__has_extension' assuming 0 
ERROR: Undefined functionlike macro 'KERNEL_VERSION' assuming 0 
c语言插件版本：sonar-c-plugin-1.3.2.1853.jar
C++插件版本：sonar-cxx-plugin-2.0.7.3119.jar
