### ISSUE TITLE
Parsing error when two template closing delimiter are used together without separator ">>"

### ISSUE THREAD

**Issue by slnj** [SonarOpenCommunity/sonar-cxx#2318]
Getting parsing error in this case:
_**FAILS:**_
```
auto foo( A<int>* p ) 
{
    auto a = f(std::shared_ptr<A<int>>(p));
}
```
But If change ">>" by "> >" ( adding one separator between ">" then parsing is ok )
_**OK:**_
```
auto foo( A<int>* p ) 
{
    auto a = f(std::shared_ptr<A<int> >(p));
} 
```
Also if f() call is removed , ">>" without separator is accepted.
_**OK:**_
```
auto foo( A<int>* p ) 
{
    auto a = std::shared_ptr<A<int>>(p);
}
```

**Comment by guwirth** [comment]
Seems to be a problem in:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/src/main/java/org/sonar/cxx/channels/RightAngleBracketsChannel.java

**Comment by slnj** [comment]
Seems each < should initialize its own parentheseLevel variable.
Maybe change parentheseLevel to a int stack, push a 0 when a < is found, and pop when > is found, ++ top element when '(' found and -- on ')', and the top value being checked at line 79 for consume initialization.

**Comment by guwirth** [comment]
Hi @slnj,

thanks for your feedback.

I have a fix for your issue, but I'm not sure if this is a fix for all cases. Please test it and give me feedback. The code implements:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/dox/Right_Angle_Brackets_N1757_05-0017.html

I always try to find a solution with minimal impact to avoid destroying other things.

Regards,

**Comment by guwirth** [comment]
Hi @slnj,

there is a new version for testing:
https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

Regards,

**Comment by slnj** [comment]
Excellent!!
With this, all parsing error on my code are gone!!! 

Thanks & Regards
Santiago

**Comment by guwirth** [comment]
@slnj Thx for your valuable input!
