### ISSUE TITLE
There is no jar package for version 2.1.0

### ISSUE THREAD

**Issue by phywym** [SonarOpenCommunity/sonar-cxx#2322]
Hi sonar-cxx plugin developers,
Our sonar version is 9.1 x. It is incompatible with sonar cxx of version 2.0.6, which makes sonar unable to connect and start.
On this page ：https://github.com/SonarOpenCommunity/sonar-cxx/releases
There is no jar package for version 2.1.0，Can you send it to me? My email is penghy@300624.cn，Or give me a download address。
I need it very urgently，Please help me。

Thanks
phywym

**Comment by phywym** [comment]
11

**Comment by guwirth** [comment]
Hi @phywym,

there is only a first beta for SQ 9.x, but you can give it a try:
https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-2.1.x-beta1

Regards,
