### ISSUE TITLE
Plugin key is missing from manifest

### ISSUE THREAD

**Issue by andreas63741** [SonarOpenCommunity/sonar-cxx#2323]
I tried to install the sonar-cxx plugin on your server with latest sonarqube 8.9.7 LTS. But SonarQube will not start with it. 

I tried 2.0.6 and 2.0.7 (beta) version of the plugin, so cxx-sslr-toolkit-2.0.6.2925.jar + sonar-cxx-plugin-2.0.6.2925.jar and cxx-sslr-toolkit-2.0.7.3113.jar + sonar-cxx-plugin-2.0.7.3113.jar.

I have also read carefully before the Setup and Upgrade guide. Nevertheless no chance to bring my server up and running with this plugin installed. After deleting the plugin from ./extensions/plugins the server starts again.

There I found a similar help request:
https://community.sonarsource.com/t/c-community-plugin-plugin-key-is-missing-from-manifest/56904

web.log ERROR message (see also attached file):

`2022.02.24 11:16:04 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed
java.lang.NullPointerException: Plugin key is missing from manifest
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
...
2022.02.24 11:16:04 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2022.02.24 11:16:04 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
`

 - OS: Centos7 (lastest version)
 - SonarQube version: 8.9.7.52159
 - cxx plugin version: 2.0.6 or 2.0.7 (beta)

 
[sonar-cxx-plugin-failed_to_load.log](https://github.com/SonarOpenCommunity/sonar-cxx/files/8131975/sonar-cxx-plugin-failed_to_load.log)

Thank you for support.

**Comment by guwirth** [comment]
Hi @andreas63741,

most likely you copied also the sslr-toolkit into the plugin folder, see discussion here:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Install-the-Plugin

Regards,

**Comment by andreas63741** [comment]
Yes, you are right. Now it works fine (tried 2.0.7). Thank you and sorry for the inconvenience.
