### ISSUE TITLE
Seems Sonar-cxx might be interfering with SonarSource CFamily plugin.

### ISSUE THREAD

**Issue by VishwasKulkarni** [SonarOpenCommunity/sonar-cxx#2351]
I have a project which has kotlin, java and C++ code. Java and Kotlin code smells are working fine, but when it comes to C++ I am getting following error.

=========================

cd control
cmake -S . -B . 
build-wrapper-linux-x86-64 --out-dir ../build_output  cmake --build . --target clean
cd ..

sonar-scanner \
  -Dsonar.projectKey=<rootProj> \
  -Dsonar.host.url=<url> \
  -Dsonar.login=<login> \
  -Dsonar.branch.name=${BRANCH} \
  -Dsonar.java.binaries=controller/** \
  -Dsonar.java.libraries=**/** \
  -Dsonar.c.file.suffixes=- \
  -Dsonar.cpp.file.suffixes=.h,.cc,.cpp,.cxx,.c++,.hh,.hpp,.hxx,.h++,.ipp \
  -**Dsonar.cfamily.threads=$(nproc)** \
  -Dsonar.cfamily.cache.enabled=false \
  -Dsonar.cfamily.build-wrapper-output=build_output

=========================

=========================

Error during SonarQube Scanner execution **13:13:59** ERROR: Language of file 'controller/CMakeFiles/3.18.1/CompilerIdCXX/CMakeCXXCompilerId.cpp' can not be decided as the file matches patterns of both sonar.lang.patterns.cxx : **/*.cpp and sonar.lang.patterns.cpp : **/*.h,**/*.cc,**/*.cpp,**/*.cxx,**/*.c++,**/*.hh,**/*.hpp,**/*.hxx,**/*.h++,**/*.ipp

===========================

Trails:
I added "-Dsonar.cxx.file.suffixes=- " to disable CXX and tried again but got below error.

===================

13:15:48 ERROR: Error during SonarQube Scanner execution
13:15:48 java.lang.IllegalStateException: The "build-wrapper-dump.json" file was found empty. Please make sure that:
13:15:48   * you are using the latest version of the build-wrapper and the CFamily analyzer
13:15:48   * your compiler is supported
13:15:48   * you are wrapping your build correctly
13:15:48   * you are wrapping a full/clean build
13:15:48   * if you are building your project inside a Docker container, build-wrapper is wrapping the build process inside the container and not wrapping the external Docker process
13:15:48 	at com.sonar.cpp.plugin.CFamilySensor.process(CFamilySensor.java:442)
13:15:48 	at com.sonar.cpp.plugin.CFamilySensor.execute(CFamilySensor.java:175)
13:15:48 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)

====================

Response from SonarSource support channel:
**the sonar-cxx plugin is not supported by SonarSource, I recommend either uninstalling it or referring to their support channel if interferes with the SonarSource CFamily plugin.**

**Comment by guwirth** [comment]
Hi @VishwasKulkarni,

this is the wrong forum, you are using the **cfamily** plugin from SonarSource.
https://community.sonarsource.com/

Regards,

**Comment by guwirth** [comment]
Hi @VishwasKulkarni,

in case you have admin rights: yes.

![grafik](https://user-images.githubusercontent.com/6077367/162169786-e6d8c321-9e8e-4c32-b9e7-2d0709466151.png)

Regards,

**Comment by VishwasKulkarni** [comment]
Thank you :)
