### ISSUE TITLE
Does this plugin support C analysis in addition to C++?

### ISSUE THREAD

**Issue by felipeleonfernandez** [SonarOpenCommunity/sonar-cxx#2365]
Hi there!

I was wondering if this SonarQube plugin does supports C analysis in addition to C++.

Thanks in advance!

**Comment by felipeleonfernandez** [comment]
As I can see there's a sensor called Cppcheck which supports C/C++ static code analysis. Can anyone confirm if this is correct?

**Comment by guwirth** [comment]
Hi @felipeleonfernandez,

> … does supports C analysis in addition to C++.

It’s in most cases possible to analyze also C code. The C grammar is similar to C++. But it’s at the end then all the same language `cxx`. 

https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.file.suffixes

Please read also https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code for understanding the basics and for troubleshooting. 

> As I can see there's a sensor called Cppcheck which supports C/C++ static code analysis. Can anyone confirm if this is correct?

Think our Wiki should answer this question: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cppcheck.reportPaths

Regards,

**Comment by felipeleonfernandez** [comment]
> Hi @felipeleonfernandez,
> 
> > … does supports C analysis in addition to C++.
> 
> It’s in most cases possible to analyze also C code. The C grammar is similar to C++. But it’s at the end then all the same language `cxx`.
> 
> https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.file.suffixes
> 
> Please read also https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code for understanding the basics and for troubleshooting.
> 
> > As I can see there's a sensor called Cppcheck which supports C/C++ static code analysis. Can anyone confirm if this is correct?
> 
> Think our Wiki should answer this question: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cppcheck.reportPaths
> 
> Regards,

I was looking at it, the issue was just to confirm that.

Thank you!
