### ISSUE TITLE
How to check the results of an analysis?

### ISSUE THREAD

**Issue by felipeleonfernandez** [SonarOpenCommunity/sonar-cxx#2367]
Hello there!

I've just installed the plugin and the Sonar analysis it is executed in a Jenkins pipeline. I'm using some examples of /sonar-cxx/integration-tests/testdata folder. The executions end well but when I check the results in SonarQube (for example for indexing_project) I'm getting the same all the time:
![image](https://user-images.githubusercontent.com/40802509/166896902-ce9e56a3-1ecc-404e-9c8d-cff8e398f7e8.png)

As you can see I'm not getting bugs, vulnerabilities, etc. I don't if there's a possibility to make an analysis of a code with this kind of issues to check the analysis is correctly done.

Thanks in advance!

**Comment by felipeleonfernandez** [comment]
I'm not getting the same in coverage and duplications, I was talking about bugs, vulnerabilities, debt, etc.
![image](https://user-images.githubusercontent.com/40802509/166898111-3a218f9b-2161-458e-bd78-ae11bf8a32c2.png)

**Comment by guwirth** [comment]
Hello @felipeleonfernandez,

please follow the steps:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files

Use the project _Hello World_ for an initial test:
https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/hello_world

Turn **debug info** on to get more feedback:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-Debug-Information

Hope this helps!

Regards,

**Comment by guwirth** [comment]
Hi @felipeleonfernandez,

in 90% of problems with issues the paths does not fit:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Troubleshooting-Reports

Regards,

**Comment by felipeleonfernandez** [comment]
> Hi @felipeleonfernandez,
> 
> in 90% of problems with issues the paths does not fit: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Troubleshooting-Reports
> 
> Regards,

I've just checked the quality profiles and they are not configured:

![image](https://user-images.githubusercontent.com/40802509/166911983-01aaaa0f-ef98-4f9d-a6a4-03a9e08f5ff7.png)

**Comment by guwirth** [comment]
Hi @felipeleonfernandez,

> I've just checked the quality profiles and they are not configured:

That’s by intention:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles

Regards,

**Comment by felipeleonfernandez** [comment]
> Hi @felipeleonfernandez,
> 
> > I've just checked the quality profiles and they are not configured:
> 
> That’s by intention: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles
> 
> Regards,

Thank you for the info, good measure to not make performing issues, I'm gonna activate them and make more tests.

**Comment by felipeleonfernandez** [comment]
Hi,

Now I'm getting Debt and Code Smells, but no Bugs, Vulnerabilities or Security Hotspots. To check that the analyzed code does have one of them I've write the code below:

```
#include <iostream>
#include <stdio.h>
#include "component1.hh"

typedef enum {false, true} bool;

int main(int argc, char* argv[])
{

    bool x = false;
    if(x > true){
        printf("x is true.");
    }else{
        printf("x is false.");
    }
    
    std::cout << "Here is main" << std::endl;
    return Bar().foo();
}
```

As you can see I'm evaluating the x variable using ">" being boolean but I'm not getting a bug there when I'm using a Quality Profile with that rule activated.

**Comment by guwirth** [comment]
Hi @felipeleonfernandez,

The cxx plugin is reading the Cppcheck results and forwarding it to SQ.
If you are looking into the Cppcheck report, do you see the issue there (analyse the code in the Cppcheck GUI)?

If not it's an Cppcheck problem...

Regards,

**Comment by felipeleonfernandez** [comment]
Hi!

I've just analyzed this piece of code:

```
int x = 0;
int y = 5 / x;
```

As you can see there are a division by zero, and there's an active rule that must cause to get a bug:

![image](https://user-images.githubusercontent.com/40802509/167082771-1708ac46-b055-4e98-8861-288e54c19ebb.png)

But there's nothing:

![image](https://user-images.githubusercontent.com/40802509/167083105-c6ad788f-61ca-409f-a59b-d70fae19c497.png)

**Comment by guwirth** [comment]
Hi,

> division by zero

Is the issue in the report file?

Regards,

**Comment by felipeleonfernandez** [comment]
> Hi,
> 
> > division by zero
> 
> Is the issue in the report file?
> 
> Regards,

Hi,

I'm getting this:
```
09:21:19.233 INFO: Sensor CXX Cppcheck report import [cxx]
09:21:19.234 DEBUG: Searching 'sonar.cxx.cppcheck.reportPaths' files with Ant pattern '[report.xml]'
09:21:19.239 DEBUG: Search files(s) in path(s): '/home/jenkins/work/workspace/torredecontrolosp/sonarscanner-tests/report.xml'
09:21:19.249 WARN: Property 'sonar.cxx.cppcheck.reportPaths': cannot find any files matching the Ant pattern(s) '/home/jenkins/work/workspace/torredecontrolosp/sonarscanner-tests/report.xml'
```

In the sonar-project.properties file I've indicated:
`sonar.cxx.cppcheck.reportPaths=report.xml`

I don't know if I'm missing something.

**Comment by felipeleonfernandez** [comment]
> Hi,
> 
> Did you run Cppcheck before running the scanner? Do you get an XML Cppcheck report file with your issues? ---- up to here that has nothing to do with cxx plugin Is the resulting report stored under `/home/jenkins/work/workspace/torredecontrolosp/sonarscanner-tests/report.xml`?
> 
> Regards,

Hi,

I didn't. Now I've done it and it seems to work well.
Last question: why is an external analyzer needed to get issues like Bugs, Vulnerabilities or Security Hotspots?

Thanks for your attention!

**Comment by guwirth** [comment]
Hi,

_"SonarQube C++ Community plugin (cxx plugin): This plugin adds C++ support to SonarQube with the focus on integration of existing C++ tools. "_ : https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Design-Guidelines

This is the big difference to the commercial plugin. They have a build-in analysis. Our design decision was to use already existing tools. This avoids reinventing the wheel and a lot of people like to use there existing tools.

Regards,
