### ISSUE TITLE
[newbe] support request

### ISSUE THREAD

**Issue by ikeas68** [SonarOpenCommunity/sonar-cxx#2370]
hello 
i try to use this plug for parsing one only cpp file
with an simple error (line too long)
but i have no result found
how i can have support for help me

or find a sample documentation step by step for 
- define rules
- check cpp file or other

thanks

**Comment by guwirth** [comment]
Hi,

please have a look to our Wiki.
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code

Regards,
