### ISSUE TITLE
[newbe] source code for external plugins 

### ISSUE THREAD

**Issue by ikeas68** [SonarOpenCommunity/sonar-cxx#2372]
hello
i try to made an external plugins for sonarqube-cxx version 1.3.3 and sonarqube 7.9.6
using with sonar.cxx.other.reportPath
[Extending-the-code-analysis](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis)
but the source code i have find is not correct with this sonarqube version
where i can find something ?

**Comment by guwirth** [comment]
Hi @ikeas68,

for SQ 7.9 I would use latest cxx plugin version 2.0:
https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-2.0.7
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compatibility-Matrix

You can find the source code for older versions under:
https://github.com/SonarOpenCommunity/sonar-cxx/tags
https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-1.3.3

Regards,

**Comment by ikeas68** [comment]
thanks but my problem is to understand usage of external code analyser
this sample : https://github.com/SonarOpenCommunity/cxx-custom-checks-example-plugin/tree/master/src
not work with sonarcube 7.9.6

i must create an system for logiscope c++  checker and using sonar.cxx.other.reportPath for specify path of data
- read fileS generated by logiscope 
- transform data for sonarqube with my own rules
- insert check result to sonarqube

if i have a sample for custom check running with my sonarqube version i can do it

**Comment by guwirth** [comment]
Hi @ikeas68,

It depends which version of SQ you have. In case of the **commercial version** you have to read only the report from your  **logiscope c++ checker**. Recommended way is to convert it to the **Generic Issue Format** and read it with this sensor then:
https://docs.sonarqube.org/latest/analysis/generic-issue/

In case of the **community version** you have to read in the source code with a C++ plugin first, this step is called indexing (e.g. cxx plugin):
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code

Second step is than to read the corresponding report file:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files

Here you also have two possibilities:
1. Use the Other sensor: 
     a. First you have to create rule definitions: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.other.rules
     b. Then you have to convert the **logiscope c++ checker** output into the format of **Other** https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.other.reportPaths and read it with the scanner.
2. Second possibility is to write an own sensor, an easy sample is https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/cppcheck. To write an own plugin/sensor the starting point is:
https://docs.sonarqube.org/latest/extend/developing-plugin/

Regards,

**Comment by guwirth** [comment]
@ikeas68 how does the logiscope c++ checker output look like? Could you provide an sample?

**Comment by ikeas68** [comment]
see zip file
- "tcpnetworkservice analyse" is output of logiciscope
       -  .dat are metrics
       - .xml ar error (like cppcheck)
       - .csv code analysing
- "tcpnetworkservice source" is souce code
[Sonar Elements.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/8697164/Sonar.Elements.zip)

i must adding some rules to find error with analysing cols in .dat 
for sample if ap_mhf number > 300 && ap_pof < .2
and same comput for .csv file

**Comment by ikeas68** [comment]
for information
i use the same scanner definition (same command line for all)
i have compil code of cxx 1.3.3
and it's work when i change name after compilation to sonar-cxx-plugin-1.3.3.2051.jar
if i change name to sonar-cxx-plugin-1.3.4.jar not working

if i try to use the 2.0.7 version of cxx "sonar-cxx-plugin-2.0.7.3119.jar"
i have
08:03:18.332 DEBUG: 'CXX Cppcheck report import' skipped because there is no related file in current project

**Comment by guwirth** [comment]
Hi @ikeas68,

you are mixing up different problems:
1) cover.xml is from gcovr, you have to use the https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cobertura.reportPaths to read it.
2) For cppcheck....xml use https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cppcheck.reportPaths. If it's not working most likly the path does not fit or rules are not activated in your profile. See hints in Wiki.
3) TcpNetworkService_Rule_Violation.csv is the file with the logiscope c++ checker violations. Think fastest is to write a small tool converting it to https://docs.sonarqube.org/latest/analysis/generic-issue/ and read it with this sensor. In this case rules are generated on the fly and you need no "rules file". 

Hope this helps.

Regards,

**Comment by ikeas68** [comment]
ok i have find a solution by creating my own sonarqube plugins based on cnes frama-c plugins
https://logiciels.cnes.fr/fr/content/plugins-sonarqube-du-cnes
i work correctly
i have made a sensor for parsing my .dat file
i can find rulkes define in logiscope-rule.xml like this
<rule>
		<key>LOGISCOPE.ERROR</key>
		<name>Logiscope error</name>
		<internalKey>*</internalKey>
		<description>This rule is not directly linked to a problem in the code, but it exists to alert users that an error occurred when running Logiscope or reading Logiscope reports.
		</description>
		<severity>CRITICAL</severity>
		<cardinality>SINGLE</cardinality>
		<status>READY</status>
		<type>BUG</type>
		<tag>value</tag>
		<remediationFunction>CONSTANT_ISSUE</remediationFunction>
		<remediationFunctionBaseEffort>30min</remediationFunctionBaseEffort>		
</rule>
for the moment i havn't find how i can add in xml new node like
<javascript>alpha > 10</javascript>
		<line>5</line>
		<usage>fun</usage>
and find them in sensor 
Collection<ActiveRule> activeRules = 
    			sensorContext.activeRules()
    						.findByLanguage(LogiscopeLanguage.KEY);
    	for(ActiveRule rule : activeRules) {
    		LOGGER.debug(" - " + rule.ruleKey() + " params = " + rule.params().size() );
    		Map<String, String> m = rule.params();
    		for(String s : m.keySet())
    		{
    			LOGGER.debug(" - " + s );
    		}
    	}
i am a newbe and i don"t understand for the moment how i can find my own node, javascript, line usage

**Comment by ikeas68** [comment]
thanks it's not a problem with cnes-frama-c-plugins lol
just only how i can define my own rule for the moment an how i can pass from ActiveRules to rules define in xml with my own paramaters

i have a invers strategy for parsing my logiscope file
using rules and for each line check if rule applyed an if true set error

**Comment by guwirth** [comment]
Hi @ikeas68,

maybe this helps: https://community.sonarsource.com/t/createrepository-vs-createexternalrepository/26102

Regards,
