### ISSUE TITLE
Sonarqube is showing all cppcheck errors as codesmell

### ISSUE THREAD

**Issue by msilvestre** [SonarOpenCommunity/sonar-cxx#2379]
Hi sorry to create an issue for this, but didn't find the community to clarify my questions,

Is this normal (the subject I mean).

Thank you

**Comment by guwirth** [comment]
Hi @msilvestre,

> didn't find the community to clarify my questions,

Which plugin are you using to read C++ code? Which sensor (configuration property) are you using to read the Cppcheck issues?

Regards,

**Comment by guwirth** [comment]
Hi @msilvestre,

for the **cxx plugin** the Cppcheck rules are defined here:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/cppcheck.xml

Search for `<type>…</type>`. In case there is no type, default is `CODE_SMELL`. You can see and filter this also on your SonarQube server in the profile you are using for scanning. 

> Sonarqube is showing all cppcheck errors as codesmell

Not all rules are classified `CODE_SMELL`. 

Regards,

**Comment by guwirth** [comment]
Hi,

the `id` of `error` of the **report file** is mapped to the `rule` `key` of the **rule file**, then this is used:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/cppcheck.xml

Regards,
