### ISSUE TITLE
Cannot parse __has_builtin

### ISSUE THREAD

**Issue by godambrosio** [SonarOpenCommunity/sonar-cxx#2395]
**Describe the bug**
The CXX sensor is ignored due to an error: Cannot parse '#if (__has_builtin(__builtin_FILE) and __has_builtin(__builtin_LINE))', ignoring...

**To Reproduce**
1. Start sonarqube scanner 
2. Build the application
3. End the sonarqube scanner 

**Expected behavior**
Sensor CXX is executed

**Screenshots**
![Capture](https://user-images.githubusercontent.com/8494720/173838995-a20a3537-8bd7-4588-b88c-355a4be04b51.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - SonarQube version: 8.9.8.54436 Developer Edition
 - cxx plugin version: 2.1 (build 229)
 - sonar-scanner version: 4.6.2.2472

**Comment by guwirth** [comment]
Please read:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors

Some more hints:
https://clang.llvm.org/docs/LanguageExtensions.html

Sample:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.defines
```
    __has_builtin(a) 0\n\
    __has_cpp_attribute(a) 0\n\
    __has_include(a) 0\n\
    __is_identifier 0\n\
```
