### ISSUE TITLE
Disable cxx-plugin during sonar-maven-plugin execution

### ISSUE THREAD

**Issue by entrix** [SonarOpenCommunity/sonar-cxx#2412]
Hello everyone!

My case is very rare but may you know the solution. i didn't find a clear answer to my problem.

I have an old physical node with CentOS 6 32-bit environment on which maven build with sonar-maven-plugin is executing. On the other side I have Sonar Server Version 8.9.8 (build 54436). Because of the environment is 32-bit only java 1.8 fits for execution. Then sonar starts sonar-cxx plugin which has been previously compiled with java 11. Soon after sonar:sonar goal is started it fails: 

`[exec] [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project <project>: The plugin [cxx] does not support Java 1.8.0_272: org/sonar/plugins/cxx/CxxPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file `

And the question - Does it possible to disable cxx-plugin via properties file or maven plugin configuration in any way on the node?

Thanks in advance!

**Comment by guwirth** [comment]
Hello @entrix,

I fear there is no solution to turn off a plugin during execution of the scanner. SonarSource is working on a solution to suppress languages https://portal.productboard.com/sonarsource/3-sonarqube/c/158-remove-languages-from-an-instance

See also:
* #2301
* #2171

It's important to understand:
* there are two processes running: SQ server and SQ scanner
   * https://docs.sonarqube.org/8.9/requirements/requirements/
   * sever side must anyway be Java 11
* both processes can use different Java versions
* you can install more than one Java version in parallel on a machine
* Java versions are normally backward compatible
  * I would try also with Java 11 on scanner side: side by side installation
  * The cxx plugin requires Java 11 on scanner and server side: install JDK 11 (e.g http://jdk.java.net/archive/) and update JAVA_HOME during sonar-maven-plugin execution to point to the installation directory.

Regards,

**Comment by entrix** [comment]
Sorry for long response,
 @guwitrth,thank you for the clarification!

Java 11 installation is not possible because node has 32 bit architecture - in other words there is necessary to build custom JDK 11 build in 32-bit environment. I didn't find a precompiled one.

But the problem resolved just by replacing cached plugin by another one on the node. One jar file was just replaced by another.
