### ISSUE TITLE
Including sonar.cxx.vc.reportPaths for C++/CLI

### ISSUE THREAD

**Issue by fuchsde** [SonarOpenCommunity/sonar-cxx#2416]
Hello,

I want to use sonar-cxx to analyze my C++/CLI code. The files get indexed with language "cxx". I also configured the `sonar.cxx.vc.reportPaths` according to the [wiki](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.vc.reportPaths). Before starting the sonar scanner, I made sure that the Visual Studio log file exists.

During the scan I get the following message, which excludes the Visual Studio log file:

`DEBUG: 'CXX Visual C++ compiler report import' skipped because there is no related rule activated in the quality profile`

1. What am I missing to include the warnings from Visual Studio log file into SonarQube?
2. What is in general the best way or linter for C++/CLI to include code smells and issues into SonarQube using sonar-cxx?

**Comment by guwirth** [comment]
Hello @fuchsde,

please have a look to the two wiki pages:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles

Most likely the rules are not activated in your Quality Profile.

Regards,

**Comment by fuchsde** [comment]
Hello @guwirth,

You where right - the problem where the quality profiles on SonarQube.

Best regards,
Dennis
