### ISSUE TITLE
How to configure rules to fall into one of the “Security Category” subcategory

### ISSUE THREAD

**Issue by falconhunter80** [SonarOpenCommunity/sonar-cxx#2417]
Hi everyone,

I am modifying sonar-cxx 2.0.7 in order to implement a new rules repository and a new parser to scan a third party XML report.
Because a new rules repository is used by the third party tool, I have also included a new XML rules set to create the repository based on this third party rules set (about 4.000 rules).
I am using Sonarqube Community Edition Version 8.9.9 and SonarScanner 4.3.0.2102

I am checking that the new rules repository is included into SonarQube coding rules set as a new repository with the fields properly assigned (e.g. severity, type, …). 

I am realising that “Security Category” in SQ issues page has subcategories (OWASP, CWE, ...) and built-in rules for other languages are placed into them. There is a subset of rules in the new repository that are “Security Category” related. So, I am interested to filter by this tabs in order to generate my own filters.

My question is how can rules be defined to fall into the “Security Category” subtabs, i.e. “OWASP Top 10” or CWE or “SANS Top 25”.

I have reviewed built-in tags defined in this link: [Built-in Rule Tags | SonarQube Docs](https://docs.sonarqube.org/latest/user-guide/built-in-rule-tags/). I have set some tags, such “owasp” via UI web, not by xml file. But it seems it is not working. Rules are only fallen  on Security Category → Sonar Source tab.

Below is an example of the fields which I am set for each rule into XML rules map file:

```
	<rule>
		<key>CWE-125-a</key>
		<name>Avoid accessing arrays out of bounds</name>
		<description>Avoid accessing arrays out of bounds</description>
		<tag>cwe</tag>
		<internalKey>CWE-125-a</internalKey>
		<severity>CRITICAL</severity>
		<type>VULNERABILITY</type>
		<remediationFunction>LINEAR</remediationFunction>
		<remediationFunctionGapMultiplier>5min</remediationFunctionGapMultiplier>
	</rule>
```

I do not know if another tag must be used or there is another field what I am not using that is used to this behaviour (e.g. <param>).
I also know that the use of [org.sonar.api.server.rule.RulesDefinitionXmlLoader](https://javadocs.sonarsource.org/9.9.0.229/org/sonar/api/server/rule/RulesDefinitionXmlLoader.html) class is deprecated since 9.0. 

Thanks in advance.
David

**Comment by guwirth** [comment]
Hi @falconhunter80,

I'm also not familiar how they are doing it, but it is for sure not only the tag. Looking to https://docs.sonarqube.org/latest/extend/adding-coding-rules/ typee must be **Vulnerability**  or **Hotspot** and a corresponding tag must be set.

It also seems that you need an Enterprise version to use this feature?
https://www.sonarsource.com/plans-and-pricing/
https://docs.sonarqube.org/latest/user-guide/security-reports/

But I think best is to ask SonarSource in their community:
https://community.sonarsource.com/

Regards,
