### ISSUE TITLE
Could I use the SonarQube CE with CXX ?

### ISSUE THREAD

**Issue by williehao** [SonarOpenCommunity/sonar-cxx#2425]
I've installed the 8.8 version with the Sonarqube server but I always got the warning message as the following picture.
Environment
1. Linux
2. 8.8 version 
3.  sonar-scanner-cli-4.7.0.2747 version 
4. cppcheck-2.7 version 

Questions: 
1. Can I use 8.8 version or need to downgrade 7.*?
2.  scanner version is okay or not?
3.  cppcheck version is okay or not? 

![image](https://user-images.githubusercontent.com/15116422/191150354-ae0219d8-a5a4-4b8d-9963-1707f3d20606.png)
![image](https://user-images.githubusercontent.com/15116422/191150810-e5c01849-2271-433a-b457-b54d0972dd29.png)
![image](https://user-images.githubusercontent.com/15116422/191154044-6e050197-02f5-4472-867f-9775735f8d3f.png)
![image](https://user-images.githubusercontent.com/15116422/191154253-86f668a7-d955-4d91-8dab-4a74f36d2439.png)

Thanks,
Willie

**Comment by guwirth** [comment]
Hi @williehao,

> Can I use 8.8 version or need to downgrade 7.*?

You can use 8.8, best is to use the latest snapshot: https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/latest-snapshot

> scanner version is okay or not?

Yes, scanner version must match with SQ version.

> cppcheck version is okay or not?

Yes, see https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cppcheck.reportPaths

> SCM provider

In case you do not use a SCM:
```INI
# disable SCM support
sonar.scm.disabled=true
```

> C++ files warning

Message: "C++ cannot be analyzed with current SonarQube edition. Please consider upgrading...". SonarQube issues this message when an input file with the file extension .c, .cc, .cpp, .cxx or .c++ is read in the Community Edition. 
**Select "Dismiss permanently" to continue without the message.**

Regards,

**Comment by guwirth** [comment]
Hi @williehao,

in case of no issues you must most likely enable the rules in your profile:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files
  * **https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles**

Regards,
