### ISSUE TITLE
Which one is a dynamic code analysis tool and how to use it 

### ISSUE THREAD

**Issue by williehao** [SonarOpenCommunity/sonar-cxx#2428]
Which one is a dynamic code analysis tool?
1. Cppcheck 
2. GCC/G++ 
3. Visual Studio and Core Guideline Checker 
4. Clang Static Analyzer 
5. Clang-Tidy 
6. Infer 
7. PC-Lint 
8. RATS 
9. Valgrind
10 Vera++ 
11. Dr. Memory 

PS: please give me an example for testing 

Thanks,
Willie

**Comment by guwirth** [comment]
Hi @williehao,

here is a good overview about dynamic code analysis tools: https://github.com/analysis-tools-dev/dynamic-analysis

Most of the tool above (including the other plugins from SonarQube) are static code analysis tools.

In case you like to include any other tool:
* you have to create a machine readable report
* import the results with e.g.
   * [Generic Issue Import Format](https://docs.sonarqube.org/latest/analysis/generic-issue/) 
   * [sonar.cxx.other.reportPaths](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.other.reportPaths)

Hope this helps.

Regards,
