### ISSUE TITLE
Allow Visual Studio to connect to SonarQube/sonar-cxx 

### ISSUE THREAD

**Issue by bsdooby** [SonarOpenCommunity/sonar-cxx#2429]
When installing the SonarLinter extension in Visual Studio 2022, a connection to a SonarQube server is refused, as no language extension, compatible with the installation(s), is present...

**Comment by guwirth** [comment]
Hi @bsdooby,

I’m sorry but the cxx plugin does not support SonarLint:
https://www.sonarsource.com/products/sonarlint

The input for the cxx plugin are external tools like Cppcheck or ClangTidy, it makes no sense to call them over the linter.

Regards,

**Comment by bsdooby** [comment]
Tools (such as cppcheck, vera++, cpplint, clang-tidy, and others) are installed by this add-on (SonarLint). Therefore, reports could be sent to the SonarQube backend with the sonar-cxx plug-in, as is done when using a custom pipeline (e.g., in GitLab).

**Comment by guwirth** [comment]
Hi,

looking to the [SonarSource c++ plugin](https://www.sonarqube.org/features/multi-languages/cpp/) this is an own independent static code analyser. The cxx plugin forwards only the result of other tools (strictly speaking, the previously created reports) to SonarSource. This means that you need to run the tools beforehand anyway to get the report.

> Tools (such as cppcheck, vera++, cpplint, clang-tidy, and others) are installed by this add-on (SonarLint)

No, the cxx plugin does not install any tools. Maybe that page helps: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files

SonarLint is an IDE extension for local analysis : https://www.sonarsource.com/products/sonarlint/

Regards,

**Comment by bsdooby** [comment]
Hi,

The checker/linter tools mentioned are installed locally by the SonarLint
extension, not sonar-cxx; ;) But one could then start an analysis run via
Visual Studio directly, and send the logs to the SonarQube server (without
pipelining it thru a GitLab instance). Current problem: the connector (as
part of the SonarLint extension) does not recognize the sonar-cxx as a
legit language extension on the SonarQube instance. If my analysis is
correct.

**Comment by guwirth** [comment]
Hi,

> the connector (as part of the SonarLint extension) does not recognize the sonar-cxx

SonarSource support only their own plugins and no others.

But as mentioned before, the cxx plugin does not run external tools, it only reads the resulting reports. Even if the SonarLinter would support the cxx plugin, you would have to run the external tools before running the linter yourself.

Regards

**Comment by bsdooby** [comment]
Hi Günter

Thanks for clarifying...That's a pity (that SonarSource only support their
own stuff).
At least the community edition of SonarSource is FOSS, and your plugin
sonar-cxx.

Thank you for your work!

Grüsse aus Bern
Peter
