### ISSUE TITLE
Clang-tidy reports never upload source

### ISSUE THREAD

**Issue by byronfa** [SonarOpenCommunity/sonar-cxx#2447]
**Describe the bug**
_(Sorry.. not sure where else to go with this.. I must be missing something?  I've fought this on and off but don't know what i'm missing...)_

sonarqube version:   9.6.0.59041
clang-cxx plugin:   2.1 (build 253)

Given a clang-tidy output log with output like the following, my uploads into sonarqube always produce pathing warnings, and I get clang-tidy info reports into the database, but never any code upload.   (I can see the clang-tidy warnings, but not where they belong)

(clang-tidy.log)

`/home/build/workspace/project/components/3rdparty/libusb/libusb/os/threads_posix.c:60:6: warning: variable 'r' is not initialized [cppcoreguidelines-init-variables]
        int r;
            ^
              = 0`

I always get 
`WARN: Cannot find the file '/home/build/workspace/project/components/3rdparty/libusb/libusb/os/threads_posix.c' in project 'elem-clangtidy' with baseDir '/home/build/workspace', skipping`

It seems like i'm getting mixtures of the code obeying (or not) relative inclusion paths and getting confused?

Is this obvious to anyone?   

Thanks

**Comment by nmgwddj** [comment]
the same problem:
```
WARN: Cannot find the file '/Users/jj.deng/Documents/yunxin/ne_phoenix/src/ne_comm/encrypt/encrypt/sm2_encrypt_imp.cpp' in project 'ne-phoenix' with baseDir '/Users/jj.deng/Documents/yunxin/ne_phoenix', skipping
WARN: Cannot find the file '/Users/jj.deng/Documents/yunxin/ne_phoenix/src/ne_comm/encrypt/encrypt/encrypt_utli.cpp' in project 'ne-phoenix' with baseDir '/Users/jj.deng/Documents/yunxin/ne_phoenix', skipping
WARN: Cannot find the file '/Users/jj.deng/Documents/yunxin/ne_phoenix/src/ne_comm/encrypt/encrypt/encrypt_utli.cpp' in project 'ne-phoenix' with baseDir '/Users/jj.deng/Documents/yunxin/ne_phoenix', skipping
```

**Comment by byronfa** [comment]
I tried sonarqube 8.9 and sonar-cxx 2.0.7.    (client system is linux, server is running windows 2002).

'Same problem.

I've had this working for me previously.. but.. its been months ago and now that I've returned to the problem I can't recall what I had different when I was getting source uploaded into sonarqube along with the clang-tidy issues.

**Comment by guwirth** [comment]
Hi,

first step is to read the wiki:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.clangtidy.reportPaths

Most likely it’s an path issue. File path in report must match to indexed source file:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Troubleshooting-Reports

Regards,

**Comment by nmgwddj** [comment]
> Ok! I think I got it. I'm going to close the question out while I go rummage. Thank you so much @guwirth for your suggestions... I spent time digging and running through everything one by one.
> 
> On the surface.. I may have had my sonar.inclusions set wrong.
> 
> (On that note.. does github have a 'buy the person a beer' button?)
> 
> Thanks again...

Cloud you share your `sonar-project.properties`?

I have the same problem.

**Comment by guwirth** [comment]
Hi @nmgwddj,

this is a sample project from our integration tests: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/clangtidy_project

Regards,

**Comment by guwirth** [comment]
Hi @byronfa,

> WARN: Cannot find the file '/home/build/workspace/project/components/3rdparty/libusb/libusb/os/threads_posix.c' in project 'elem-clangtidy' with baseDir '/home/build/workspace', skipping

The warning shows always baseDir independent if path is absolute or relative.

Regards,

**Comment by nmgwddj** [comment]
I replaced the run-clang-tidy.py script as the official version. Now it works normally. I also forgot where I got the incorrect script.
https://github.com/llvm-mirror/clang-tools-extra/blob/master/clang-tidy/tool/run-clang-tidy.py
