### ISSUE TITLE
Question: Is it possible to import partial results?

### ISSUE THREAD

**Issue by jaype87** [SonarOpenCommunity/sonar-cxx#2476]
Hi,

I have a couple of projects that I'd like to import into SonarQube.
Currently the build is setup in such a way, that each build task is a separate job. That means that I don't have all reports that I'd like to import available at the same time.

Is it possible to run the scanner multiple times on partial results (e.g. once on test coverage, once on clang-tidy) and only update the respective data or will I end up with only those results from the latest import?

Thanks
Jaype

**Comment by guwirth** [comment]
Hi @jaype87,

thanks for your question.

Sorry, but this is not possible. For a scan, all data must always be available at the same time. This is typically solved by collecting the reports of the CI/CD systems centrally and then transferring them together to SonarQube in an extra step. Each scan generates a new version event.

This is not a limitation of the cxx plugin but of SonarQube.

Regards

**Comment by jaype87** [comment]
Hi @guwirth,

thanks for the quick reply. Looks like I'll have to add another build step to gather the results.

Regards
