### ISSUE TITLE
MISRA Measurement Results 0, Is it correct?

### ISSUE THREAD

**Issue by ujkim** [SonarOpenCommunity/sonar-cxx#2480]
**Describe the bug**
I'm using the version below.

SonarQube Community Edition 8.9.7 LTS
cppcheck uses version 2.7 and sonar-cxx received version 2.0.7.

I downloaded the file in the extensions/plugin path and it was printed out that it was installed normally in SonarQube Marketplace.

The measurement was attempted by adding the properties settings below.
I tried Scan by adding the misra rule added as cxx, but 0 bugs were detected for C++ code with 80 to 90,000 lines.

sonar.cxx.cppcheck.reportPaths=cppcheck.xml
sonar.cxx.file.suffixes=.cxx,.cpp,.cc,.c,.hxx,.hpp,.hh,.h
sonar.exclusions=**/packages/**, **/Library/**
sonar.sourceEncoding=UTF-8

I also checked the log that it was indexed as follows in logging.
indexed with language 'cxx'

One slightly suspicious part is the log below.
INFO: Sensor CXX Cppcheck report import [cxx] (done) | time=324ms
INFO: Sensor Zero Coverage Sensor (done) | time=195ms

WARN: Missing blame information for the following files:
WARN: * cppcheck.xml

Is there any way to know if the misra rule measurement is correct?
I find it hard to believe that zero has been detected through 500 rules.

**To Reproduce**
1. cppcheck starts scan (cppcheck.exe" --cppcheck-build-dir=sonarqube --xml-version=2 . 2> cppcheck.xml)
2. Check on SonarQube UI, but, No detected.

**Expected behavior**
Detected Bug Outputs

**Screenshots**
![image](https://user-images.githubusercontent.com/36093636/215038110-5471312f-ec8a-4f1f-bfda-f48b80086ec2.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - SonarQube version: 8.9.7
 - cxx plugin version: 2.0.7
 - sonar-scanner version: 4.6.2.2472

**Comment by guwirth** [comment]
Hi @ujkim,

please have a look to:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cppcheck.reportPaths, especially Troubleshooting
* Are the rules activated (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles)?
* Double check your Cppcheck report file if there are MISRA issues you are missing in the UI.

Hope that helps.

Regards,

**Comment by ujkim** [comment]
@guwirth Thanks for guide!

I checked the troubleshooting information.
I checked all the procedures below and added MISRA Rule.
  - https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles 
![image](https://user-images.githubusercontent.com/36093636/215376315-3c7f0fa0-3221-4cac-94b1-4d714ca5d2c4.png)

Additional records of rules were also checked through Changelog.
![image](https://user-images.githubusercontent.com/36093636/215376357-ae8040e9-3714-4629-ad24-3a07c232dd33.png)

I would like to ask a question about "Detect and fix parsing errors" among troubleshooting items.
 - https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors

Actually, when I checked the log, there was a record as below in the Final Report record.
`01:01:57.910 INFO: Executing post-job 'Final report'
01:01:57.910 WARN: Preprocessor: 7023 include directive error(s). This is only relevant if parser creates syntax errors. The preprocessor searches for include files in the with 'sonar.cxx.includeDirectories' defined directories and order.
01:01:57.910 WARN: Source code parser: 789 syntax error(s) detected. Syntax errors could cause invalid software metric values. Root cause are typically missing includes, missing macros or compiler specific extensions.`


I added 500 MISRA Rules, and I received 0 detection results. Is there a possibility that the above issue affected?

**Comment by guwirth** [comment]
Hi @ujkim,

> I added 500 MISRA Rules, and I received 0 detection results. Is there a possibility that the above issue affected?

The cxx plugin is using the result of the external static code analysis tool Cppcheck. It’s important to configure this tool in the right way. Therefore the question „ Double check your Cppcheck report file if there are MISRA issues you are missing in the UI?“.

The plugin is analyzing the code only to derive code metrics. In case of missing includes the metrics could be wrong but this has no impact on (the number of) issues. 

Regards,

**Comment by ujkim** [comment]
Thank you so much for your reply @guwirth !

I feel like i'm shoveling something.. ㅜ.ㅜ;

I understood what you said that cxx plugin means that the result depends on the value of cppcheck.xml.
(The cxx plugin metric measurement results depend on the cppcheck report file.)

According to your advice, I checked the cppcheck report, and there were many errors as below.
`<?xml version="1.0" encoding="UTF-8"?>
<results version="2">
    <cppcheck version="2.7"/>
    <errors>
        <error id="syntaxError" severity="error" msg="syntax error" verbose="syntax error">
            <location file="ABCTest\TestABC.cpp" line="27" column="1"/>
        </error>
        <error id="syntaxError" severity="error" msg="syntax error" verbose="syntax error">
            <location file="DependencyABCTest\BasicTests.cpp" line="39" column="1"/>
        </error>
`

Does this mean that I set something wrong?

Best Regards,

**Comment by guwirth** [comment]
Hi @ujkim,

`syntax error` means always the parser can't read the code. Typically your code is not supported (maybe new C/C++ standard, specific extensions of your environement, ...) or unkown macros lead to this problem (unknown macros are typically the result of missing includes). You can find some more details here: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors.

In your case I would use the Cppcheck UI to isolate the problem. Open one of the files with syntax error (e.g. ABCTest\TestABC.cpp) and play around with it.

Regards,

**Comment by guwirth** [comment]
Hi @ujkim!

Hint: The link : https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors is only to understand the problem. You have to solve it with Cppcheck!

Regards,

**Comment by guwirth** [comment]
@ujkim Please open again if still an issue.

**Comment by ujkim** [comment]
Sorry for late reply! @guwirth 


I checked with cppcheck GUI.
I don't seem to understand the google test signature.
For example, even if you use only a name like TEST_P, it is caught as a syntax error.

**Comment by guwirth** [comment]
@ujkim think the best is to ask in the Cppcheck community for help:
https://sourceforge.net/p/cppcheck/discussion/
