### ISSUE TITLE
C++/CLI scan lexer error leads to no metrics

### ISSUE THREAD

**Issue by fuchsde** [SonarOpenCommunity/sonar-cxx#2490]
**Describe the bug**
I have a C++/CLI project, which I'm scanning using Sonar-CXX. All files I want to analyze, get indexed with cxx. Nevertheless for every file I'm getting `Lexer error: Unable to lex string source code.` I guess due to that failure, I don't see any metrics (Lines of Code, Bugs, Code, Duplications) on SonarQube.

- The MsBuild report gets imported properly by Sonar-CXX and I can see the results on SonarQube.
- The code coverage report gets imported properly and I can see the results on SonarQube.

The scanner execution finishes with `EXECUTION SUCCESS`.

How can I determine, why the lexer fails? Encoding seems to be fine.

**Expected behavior**
The lexer parses the source files and does not file. Metrics will be visible on SonarQube.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SonarQube version: 8.9.10
 - cxx plugin version: 2.0.7.3119
 - sonar-scanner version: 4.6.2.2472

**Comment by guwirth** [comment]
Hi @fuchsde,

thanks for your feedback.

Error comes from here and is for sure the reason you get no metrics. There should be normally also a source code snippet visible?
https://github.com/SonarOpenCommunity/sonar-cxx/blob/8198eb759e6a534bf0da209be6247ef1197962cd/cxx-sslr/sslr-core/src/main/java/com/sonar/cxx/sslr/impl/Lexer.java#L114

Can you provide a LOG file with more details (please turn debug info on)?
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-Debug-Information

> The` scanner execution finishes with EXECUTION SUCCESS.

That’s normal
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.errorRecoveryEnabled

First guess: Maybe special file encoding?

Regards,

**Comment by fuchsde** [comment]
Hi @guwirth ,

thanks for the fast reply. 

I run my scanner using `-X -Dsonar.verbose=True`, however I can't provide the LOG file. Why? It prints the whole content of all my files to the log file.

Example:

`13:45:24.180 DEBUG: 'MyFile.cpp' generated metadata with charset 'UTF-8'`
`13:45:24.190 ERROR: Unable to parse file: MyFile.cpp`
`13:45:24.190 ERROR: Lexer error: Unable to lex string source code "**... whole file content ...**"`
`13:45:24.200 DEBUG: 'Public API' metric for 'MyFile.cpp': total=0, undocumented=0` 

Yes I had issues with the encodings of my files. I open all files that had issues and converted the encoding from Windows-1252 to UTF-8.

For some files - 17 / 258  - I'm still getting `13:45:23.583 WARN: Invalid character encountered in file ASecondFile.cpp at line 194 for encoding UTF-8. Please fix file content or configure the encoding to be used using property 'sonar.sourceEncoding'.` 

I'm using `sonar.sourceEncoding=UTF-8`.

**Comment by guwirth** [comment]
Hi @fuchsde,

* Is it possible to share one of the files?
* In case you can't share the LOG file try to reproduce the problem with the `cxx-sslr-toolkit-X.Y.Zjar`. Start the tool, load one of your files and select `Parse Source Code`. You should see the same problem. Try then to reduce the file step by step to find the critical code snippet.
* Interesting question is also: In case you convert one of the files to plain ASCII, do you also have the the problem then?

Regards,

**Comment by fuchsde** [comment]
Hi @guwirth,

as usual you hints are amazing input.

I could boil my problem down to the "MsBuild.log" file which I'm using for my [report path](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.msbuild.reportPaths) to avoid defining `sonar.cxx.includeDirectories` and `sonar.cxx.defines` manually. **I used the flag `/maxcpucount` to generate "MsBuild.log. This was causing my issue of not seeing the metrics."** 

I can now see my lines of code as well as duplications. The lexer erros are gone. However now I'm struggeling with ~10.000 "C++ skip parser error". How can I get ride of them? Defines and include should come from my MsBuild.log, but I see many `... preprocessor cannot find include file ...` messages in the SonarScanner Debug log.

**Comment by guwirth** [comment]
Hi @guwirth,

> However now I'm struggeling with ~10.000 "C++ skip parser error". How can I get ride of them? 

maybe you start with reading this pages in the Wiki:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors

**Hint:** Since the cxx plugin only reads macros from the include files in order to parse the code syntactically in a correct way, it is often better to provide the missing macros instead of reading in all include files. Reading many include files (e.g. STL, Boost, MFC, ATL, ...) often slows down the analysis considerably. The recommendation is to include only include files for your own code.

Regards,

**Comment by guwirth** [comment]
@fuchsde by the way: Don't understand what `/maxcpucount` has to do with an lexer encoding error?

**Comment by fuchsde** [comment]
@guwirth I have the feeling, that due to `/maxcpucount` switch, the MsBuild.log file looks different and can not be parsed correctly by sonar-cxx. Consequently `sonar.cxx.includeDirectories` and `sonar.cxx.defines` are missing completely and analysis fails. That's the only explanation I can come up with.

**Comment by guwirth** [comment]
> I have the feeling, that due to /maxcpucount switch, the MsBuild.log file looks different and can not be parsed correctly

@fuchsde maybe you can create MsBuild.log with and without `/maxcpucount` and compare the LOG files what is different?

Which version of Visual Studio are you using? Which platform toolset are you using?
https://github.com/SonarOpenCommunity/sonar-cxx/blob/cf02ccac1c0bcd6db4cfb1e38af01f65420fd605/cxx-squid/src/main/java/org/sonar/cxx/config/MsBuild.java#L190

**Comment by fuchsde** [comment]
@guwirth the only difference I figured out: The logs are out of order due to multiple processes and they have a suffix `ProcessNumer>`, but I guess you are handling this behavior.

**Comment by guwirth** [comment]
> The logs are out of order due to multiple processes and they have a prefix ProcessNumer>, but I guess you are handling this behavior.

@fuchsde Yes should be handled. Maybe you can provide a snippet of your msbuild.log to verify the regex.
