### ISSUE TITLE
Plugin key is missing from manifest

### ISSUE THREAD

**Issue by nedmark** [SonarOpenCommunity/sonar-cxx#2494]
I have copied to my plugins directory:
cxx-sslr-toolkit-2.1.0.428.jar
sonar-cxx-plugin-2.1.0.428.jar
Then came the error with missing key.
 After removing cxx-sslr-toolkit-2.1.0.428.jar, from my plugin directory, it works again.

The cxx plugin seems to be active, but I am not sure if I can use it, or?
![image](https://user-images.githubusercontent.com/30747283/225122633-011488e6-2374-41ec-93be-0c71d74dfc9b.png)

**Before you create a new issue**
- Is it really a _cxx-plugin_ issue or a general _SonarQube_ issue? To track _SonarQube_ issues use the [community from SonarSource](https://community.sonarsource.com/) please.
- Please read the [Wiki](https://github.com/SonarOpenCommunity/sonar-cxx/wiki) first, maybe you will find a solution there.
- Please [turn debug info on](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information) and reproduce your issue. The debug info in the log file could help to solve or locate the issue.
- Please check if there is not already a [bug report](https://github.com/SonarOpenCommunity/sonar-cxx/issues) for your issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - SonarQube version: [e.g. 8.7.0]
 - cxx plugin version: [e.g. 2.0.0]
 - sonar-scanner version: [e.g. 4.6.0.2311]
 
**Additional context**

**Comment by guwirth** [comment]
Hi @nedmark,

thanks for your feedback. 

The `cxx-sslr-toolkit` is not a SonarQube plugin, see
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Install-the-Plugin

Regards,
