### ISSUE TITLE
Default quality rules

### ISSUE THREAD

**Issue by xhpohanka** [SonarOpenCommunity/sonar-cxx#2521]
I understand that all quality rules are off by default. Does there exist any _standard_ or _good enough_ set of rules to start with or am I expected to go over all rules one by one and check what to enable.

thanks

**Comment by guwirth** [comment]
Hi @xhpohanka,

> Does there exist any standard or good enough set of rules to start

There is no standard, this is user (use case) specific. I would recommend you to turn on all the rules of the tool you are using and start an initial analysis. Depending on the quality of your code, you can keep all the rules enabled or limit yourself to the ones you want to start with.

Regards,

**Comment by xhpohanka** [comment]
ok, thanks for info... :)
