### ISSUE TITLE
xml parsing

### ISSUE THREAD

**Issue by CCGK369** [SonarOpenCommunity/sonar-cxx#2543]
How does it parse the XML report of cppcheck and classify bugs and vulnerabilities? What is used as identification? If I add new rules to cppcheck, can it still parse? Do I need to add it again in this plugin?

**Comment by guwirth** [comment]
Hi @CCGK369,

the cxx plugin is using this rules file for Cppcheck:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/cppcheck.xml

For every new Cppcheck version we have to extend the rules and release a new cxx plugin version. 

In case you wanna extend the rules on the fly, this is the better way:
https://docs.sonarqube.org/latest/analyzing-source-code/importing-external-issues/generic-issue-import-format/

Regards,
