### ISSUE TITLE
Plugin is not working with SonarQube Version 10

### ISSUE THREAD

**Issue by Syntax3r** [SonarOpenCommunity/sonar-cxx#2548]
I have tried this plugin with the SonarQube Version 10 but it doesn't detect any issue in C++ files.. however I have implemented it on the Project.

**Comment by guwirth** [comment]
Hi @Syntax3r,

the plugin is not tested and released with SQ 10. We are supporting only LTS versions. 

https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compatibility-Matrix

Regards,

**Comment by Syntax3r** [comment]
It's working perfectly. I actually forget to set the value of **[sonar.cxx.file.suffixes]** under Administration > CXX.
Thanks for the quick response

**Comment by guwirth** [comment]
@Syntax3r thx for your feedback.

Usually the API is changed during the development of SQ 10.x, which can lead to incompatibility of the plugin.
