### ISSUE TITLE
cppcheck plugin/tool  with sonarQube binding

### ISSUE THREAD

**Issue by fayaz988** [SonarOpenCommunity/sonar-cxx#2561]
**While writing C++ Code in Visual Studio, I'm always doing SonarQube analysis to see my new code SonarQube issues, then only I can identify new code sonar issues and then fixing new issues, it eats lot of time for SonarQube Analysis using CICD pipeline. cppcheck is working outside IDE as CLI but it is unlike sonarLint error list, sonarLint shows issues with date of issue created as per SonarQube server analysis**

**Why can't we update the existing cppcheck tool which analyses new code  and same time show the issues from SonarQube server as well(Date column as show in screen shot) with project binding from SonarQube, like how we have sonarLint with SonarQube Binding projects it shows both new code issues as well old code issuesI think it is better to have this support which helps cppcheck plugin for SonarQube community edition users.
![image](https://github.com/SonarOpenCommunity/sonar-cxx/assets/84303429/47e24c00-3dd8-4687-8a98-2672d735f88b)**

**Right now i am using Sonar Link tool which same as SonarLint but it doesn't show new code issues.**

**I think it is better to have this support which helps cppcheck plugin for SonarQube community edition users.**

**Comment by guwirth** [comment]
Hi @fayaz988,

There are different things to keep in mind:
* The cxx plugin is not a static code analyzer, it’s only an interface reading already existing reports from other static code analyzer and forward it to SonarQube. That’s different with other plugins, especially the SonarSource plugins which are real static code analysis tools and can therefore be used standalone. 
* SonarLint is a tool from SonarSource supporting their own plugins only. There is no way to add other plugins.
* SonarLink was mainly written to support also other plugins, especially the cxx plugin. Main idea behind it is to move the time consuming static code analysis to a server without blocking your local machine. After analysis is done you can see the results in your local IDE.

Regards,

**Comment by akshats01** [comment]
So, like you said the cxx plugin is not a static code analyzer, it’s only an interface reading already existing reports from other static code analyzer and forward it to SonarQube. Is it possible to use any (existing) plugin which would work along side my visual studio 2019, and instead of forwarding a reading from the existing reports to SonarQube, it forwards the reading to my error list debugger?

**Comment by fayaz988** [comment]
> Hi @fayaz988,
> 
> There are different things to keep in mind:
> 
> * The cxx plugin is not a static code analyzer, it’s only an interface reading already existing reports from other static code analyzer and forward it to SonarQube. That’s different with other plugins, especially the SonarSource plugins which are real static code analysis tools and can therefore be used standalone.
> * SonarLint is a tool from SonarSource supporting their own plugins only. There is no way to add other plugins.
> * SonarLink was mainly written to support also other plugins, especially the cxx plugin. Main idea behind is to move the time consuming static code analysis to a server without blocking your local machine. After analysis is done you can see the results in your local IDE.
> 
> Regards,

Thanks for reply, i have one more question that I can see different rules repository on SonarQube from cxx plugin as below, will cppcheck (standalone plugin or tool) generate report as per these repositories. how it works?
![image](https://github.com/SonarOpenCommunity/sonar-cxx/assets/84303429/f60b1a59-3997-4be3-ab80-52ffbeb0f16c)

**Comment by guwirth** [comment]
Hi @akshats01,

> Is it possible to use any (existing) plugin which would work along side my visual studio 2019,

You need a VisualStudio plugin for Cppcheck. Maybe best is to ask in the Cppcheck forum: https://cppcheck.sourceforge.io/, something like this https://github.com/VioletGiraffe/cppcheck-vs-addin/releases/tag/1.5

Regards,

**Comment by guwirth** [comment]
Hi @fayaz988,

> issues also listed related other repos like SonarQube cxx how this is happening?

Issues are reported in reports from a specific tool, are read by one sensor and are visible in the corresponding repo. Best is to verify the LOG file to see what happens https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-Debug-Information

Regards,

**Comment by akshats01** [comment]
> Hi @akshats01,
> 
> > Is it possible to use any (existing) plugin which would work along side my visual studio 2019,
> 
> You need a VisualStudio plugin for Cppcheck. Maybe best is to ask in the Cppcheck forum: https://cppcheck.sourceforge.io/, something like this https://github.com/VioletGiraffe/cppcheck-vs-addin/releases/tag/1.5
> 
> Regards,

I understand, but as per my needs, cppcheck is not able to show the codesmells that i can view on the sonarqube cxx plugin. So i wanted to use this cxx plugin as an extension on my visual studio. But i suppose there is no possible way to achieve that.

**Comment by guwirth** [comment]
Hi @akshats01,

> So i wanted to use this cxx plugin as an extension on my visual studio. But i suppose there is no possible way to achieve that.

I’m sorry but I’m not aware of a solution for your problem.

Regards,
