### ISSUE TITLE
Preprocessor cannot find include file...

### ISSUE THREAD

**Issue by TAsUjxnMIL** [SonarOpenCommunity/sonar-cxx#2562]
Hello together,
I currently get following message during debug mode:
`DEBUG: [C:\qnx660\target\qnx6\usr\include\sys\cpuinline.h:36]: preprocessor cannot find include file '#include _NTO_CPU_HDR_(cpuinline.h)`
How to remove these kind of messages? As you can see I am working with QNX.

**Comment by guwirth** [comment]
Hi @TAsUjxnMIL,

please have a look in our Wiki:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors

Regards,
