### ISSUE TITLE
Exception while running CppDepend.SonarQube.RuleRunner.exe

### ISSUE THREAD

**Issue by thaikal** [SonarOpenCommunity/sonar-cxx#2581]
Hello,

Currently running
- SonarQube community edition version 8.9.10 LTS (zip), 
- CppDepend version 2022.1.0.27 with developer license, 
- Sonar Scanner version 4.7.0.2747 on Windows 10 machine. 
- Installed plugins are “sonar-cxx-cppdepend-community-1” and “sonar-cxx-plugin-1.3.3.2051”. 
I have created sonar-project.properties and cppDependSln.cdproj files,where I have the .sln defined, with the necessary options and rules included. When running the scanner through my source code, I receive the following exception:

> INFO: Executing command: E:/Sources/CppDepend2022.1/CppDepend.SonarQube.RuleRunner.exe E:/cppDependSln.cdproj E:\cppdepend-report.xml
> INFO: ----------------------------------------------------------------------
> INFO:    Exception while running CppDepend.SonarQube.RuleRunner.exe
> INFO:    Please read the message that shows the reason.
> INFO: Cannot run analysis without a Build Machine license.
> INFO: ----------------------------------------------------------------------
> INFO:
> INFO: ***** NDepend.SonarQube.RuleRunner.exe Help *****
> INFO:
> INFO: NDepend.SonarQube.RuleRunner.exe is meant to be called by the SonarQube infrastructure.
> INFO:
> INFO: It has two mandatory command line arguments.
> INFO: - The first one is the absolute file path of the NDepend project file (file name extension .ndproj)
> INFO: - The second one is the absolute file path of the XML output file (file name extension .xml)
> INFO: The project gets analyzed, active coding rules are executed,
> INFO: and the XML output file contains rules violations data read by the SonarQube infrastructure.
> INFO:
> INFO: Coding rules configured are the compilable and active coding rules, with all parent groups active as well, defined in any of these locations:
> INFO: - The NDepend project file
> INFO: - Rule File(s) referenced by the project file
> INFO: - Source code analyzed
> INFO:
> INFO: This executable displays messages about its activity on the console.
> INFO: - Analysis execution messages.
> INFO: - Rules violated (in red) or not violated (in green).
> INFO:
> INFO: This executable returns a non-zero exit code if it fails.
> INFO: In such situation, an explicit error message is shown on the console.
> INFO: ----------------------------------------------------------------------

Although I have defined in the cppDependSln.cdproj file the following rule
`<NDepend IsCProject="false" IsPhysical="false" AppName="sln" Platform="DotNet"`

Any idea what seems to be the problem exactly?
I have this issue posted on [SonarSource Community](https://community.sonarsource.com/t/exception-while-running-cppdepend-sonarqube-rulerunner-exe/102550) and it was suggested upgrading to `9.9.2 LTS`, but I'd like to know why am I facing this issue on SonarQube `8.9.10 LTS` and not `8.9.6`?

Thanks in advance!

**Comment by guwirth** [comment]
Hello @thaikal,

this has nothing to do with the cxx plugin. The plugin is not calling any external tools, it’s reading only the resulting reports.

You try to call CppDepend.SonarQube.RuleRunner.exe without a Build Machine license, you have a developer license only.

Contact CppDepend for more help.

Regards,

> INFO: Executing command: E:/Sources/CppDepend2022.1/CppDepend.SonarQube.RuleRunner.exe E:/cppDependSln.cdproj E:\cppdepend-report.xml
> INFO: ----------------------------------------------------------------------
> INFO:    Exception while running CppDepend.SonarQube.RuleRunner.exe
> INFO:    Please read the message that shows the reason.
> **INFO: Cannot run analysis without a Build Machine license.**
> INFO: ----------------------------------------------------------------------
