### ISSUE TITLE
Sonar read xml file of CppCheck check by MISRA2012;But there is no corresponding misra warning

### ISSUE THREAD

**Issue by gaolonglong11** [SonarOpenCommunity/sonar-cxx#2587]
cppcheck checks the code using misra rules; The generated xml file; sonar reads xml files; But there is no corresponding misra warning

**Comment by guwirth** [comment]
Hi @gaolonglong11,

please have a look to
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Troubleshooting-Reports
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles
Is the rule activated in your profile?

Only rules listed in the XML file are supported
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/cppcheck.xml

Regards,

**Comment by vscodeenv** [comment]
Thank you very much for your reply. I confirm that the XML file generated by cppckeck command contains items that do not conform to MISRA rules, but the format of XML is different from what you said. I would like to ask if there is an xml format conversion tool

**Comment by guwirth** [comment]
Hi @vscodeenv,

for me the resulting XML reports seems to have the same format: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cppcheck.reportPaths#example-of-a-report-file

In https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/cppcheck.xml I found the error id:

![image](https://github.com/SonarOpenCommunity/sonar-cxx/assets/6077367/1ac92df1-a774-48ae-8538-bc8d2290a2ed)

Is the rule enabled in your quality profile?
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles

Turn debug information on to get more information:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-Debug-Information

Regards,

**Comment by vscodeenv** [comment]
Thank you for your reply. Here are some screenshots of my Settings
![图片1](https://github.com/SonarOpenCommunity/sonar-cxx/assets/149743356/bb12fda5-53d6-4a89-aac3-bf3c6b655586)
![图片2](https://github.com/SonarOpenCommunity/sonar-cxx/assets/149743356/7b6d11b9-212c-4a11-a31e-574c48648c36)

**Comment by vscodeenv** [comment]
![图片3](https://github.com/SonarOpenCommunity/sonar-cxx/assets/149743356/43de0126-ef63-47b4-ace5-f227625accb6)
![图片4](https://github.com/SonarOpenCommunity/sonar-cxx/assets/149743356/d36b7b9a-caa7-4815-9f34-3f2390c23e06)

**Comment by vscodeenv** [comment]
I have checked that the output xml file by cppcheck contains some information about MISRA rules, and sonarqube has also done some Settings through some network tutorials, so I can see some code smells, but there is no corresponding MISR rule conflict prompt, please help me to check whether other places need to be set, thank you very much! Looking forward to your reply!

**Comment by vscodeenv** [comment]
I see MISRA rules in the rules created by sonarqube. My sonarqube version is 8.9.10; Plugin-sona-xx-plugin-2.0.7.3119; Gotlab16.3

**Comment by vscodeenv** [comment]
![图片5](https://github.com/SonarOpenCommunity/sonar-cxx/assets/149743356/f9c64c5d-3379-4332-b9a9-3c490756121e)

**Comment by guwirth** [comment]
Hi @vscodeenv,

I would start with turning debug info on and than look into the .LOG file.
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-Debug-Information

How to interpret the result is described here:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files#understanding-the-scanner-log-file

Regards,

**Comment by vscodeenv** [comment]
![图片2](https://github.com/SonarOpenCommunity/sonar-cxx/assets/149743356/45a4a3c0-c8c5-4e9c-885d-a5ce18c3934a)
感谢您的提醒，我在输出里面看到了这个，改了路径以后好像就可以看到违反misra的规则在sonarqube里面

**Comment by vscodeenv** [comment]
![图片3](https://github.com/SonarOpenCommunity/sonar-cxx/assets/149743356/ddf75284-5fae-4186-91e2-99a5165bba9e)

**Comment by vscodeenv** [comment]
你看看这样是否就没有问题了，非常感谢！非常感谢！困扰我很久了！

**Comment by vscodeenv** [comment]
Thanks for your reminding. I saw this in the output. After changing the path, it seems that misra's rules are violated in sonarqube
Please see if there is no problem in this way. Thank you very much! Thank you very much! It's been bothering me for a long time!
