### ISSUE TITLE
Unable to get coverage  report when using Sonar.cxx plugin

### ISSUE THREAD

**Issue by KaurKamaljeet** [SonarOpenCommunity/sonar-cxx#2592]
**Before you create a new issue**
- Is it really a _cxx-plugin_ issue or a general _SonarQube_ issue? To track _SonarQube_ issues use the [community from SonarSource](https://community.sonarsource.com/) please.
- Please read the [Wiki](https://github.com/SonarOpenCommunity/sonar-cxx/wiki) first, maybe you will find a solution there.
- Please [turn debug info on](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information) and reproduce your issue. The debug info in the log file could help to solve or locate the issue.
- Please check if there is not already a [bug report](https://github.com/SonarOpenCommunity/sonar-cxx/issues) for your issue.

**Describe the bug**
Hey Team. This is the first time I am using Sonar.cxx plugin for a C project. I added the the cxx suffix key so Sonar is able to identify the file but it does not show any coverage. Covered lines are 0.

Is there any other configuration that I need to enable for coverage ?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - SonarQube version: [e.g. 8.7.0]
 - cxx plugin version: [e.g. 2.0.0]
 - sonar-scanner version: [e.g. 4.6.0.2311]
 
**Additional context**

**Comment by guwirth** [comment]
Hi @KaurKamaljeet,

please read the wiki first to understand how the plugin is working. The cxx plugin need external tools to work. 

https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Troubleshooting-Coverage

Regards,

**Comment by KaurKamaljeet** [comment]
Hello @guwirth,
Thank you for your response.
I added cobertura sensor for code coverage in sonar.properties but result is still the same.

sonar.cxx.cobertura.reportPaths=coverage.xml

**Comment by KaurKamaljeet** [comment]
<img width="1011" alt="EAE3C8E8-2BA8-4D30-AD31-D8655C30964D" src="https://github.com/SonarOpenCommunity/sonar-cxx/assets/44301714/e8a34ce5-2d23-4ab9-9d8b-885efc5f371a">

**Comment by guwirth** [comment]
Hi,

maybe you can compare your report with the sample here:
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cobertura.reportPaths

The code for the sensor is here:
https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/coverage/cobertura


Other idea: Do you read a .cpp file? Is the file indexed?

Regards,

**Comment by KaurKamaljeet** [comment]
Found the issue. My coverage report was not being generated in the cobertura xml format. It was using —Sonarqube instead of —cobertura. After changing that I am getting coverage.

Thanks a lot for all the help
