### ISSUE TITLE
plugin issue: The plugin [cxx] does not support Java 1.8.0_212

### ISSUE THREAD

**Issue by amine95bz** [SonarOpenCommunity/sonar-cxx#2595]
I'm using SonarQube to perform scans on two of my projects. One of them requires the CXX plugin for a complete analysis. However, after installing the plugin on my instance (v8.9.1), the other project(should be run with java 1.8.x) encountered the following issue. I'm seeking assistance in finding a solution to this problem.

`21:23:07 [ERROR] Failed to execute goal org.sonarsource.scanner.maven: sonar-maven-plugin:3.4.1.1168: sonar (default-cli) on project nxdh-parent: The plugin [cxx] does not support Java 1.8.0_212: org/sonar/plugins/cxx/CxxPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 -> [Help 1]
[ERROR]`
Now, I am trying to find a solution to run the SonarQube stage with JDK version 11. Here is the current configuration of the stage:

`stage('Sonar') {
    environment {
        SCANNER_HOME= tool 'sonarscanner'
    }
    agent {
        docker {
            label 'sonar'
            image "artifact.me.com/docker/jdk/jdk-11:latest"
            args "-itd -v ${SCANNER_HOME}:/var/sonarScanner --privileged=true"
        }
    }
    steps {
        withSonarQubeEnv('SonarQube') {
            withVault([configuration: configuration, vaultSecrets: secrets]) {
                sh "/var/sonarScanner/bin/sonar-scanner -D ..."
            }
        }
    }
}`

However, the build stucks when this stage is reached.

**Comment by guwirth** [comment]
Hi,

this plugin is only supporting Java 11 and Java 17:
https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-2.1.0

> The plugin requires Java 11 or Java 17 on scanner side: install a Java version (e.g http://jdk.java.net/archive/) and update JAVA_HOME to point to the installation directory.

Regards,
