### ISSUE TITLE
Change rule keys containing non standard characters

### ISSUE THREAD

**Issue by jenspopp** [SonarOpenCommunity/sonar-cxx#2596]
Due to a stupid question there is now a ticket to change rule key validation:

https://sonarsource.atlassian.net/browse/SONAR-21052

This affects all keys that have any character not in regex ^[\\w]+$ which is [a-zA-Z0-9_]. This means, any key of e.g. the gcc compiler plugin will need to be changed to match this regex (e.g., replace - with _)

Others need to be checked...

The changes will need to mainly be in the rule definition / creation and in the scanner sending the issues. Any non matching character needs to be replaced before use in sonar.

**Comment by guwirth** [comment]
> Léo Geoffroy February 15, 2024 at 4:53 PM
> 
> It is unclear right now what is expected.
> We do apply restriction on the rule key for custom rules, but it seems that there are no valid reason why we do so. On the other side, plugin-api doesn’t apply any kind of validation on the rule key, and there was no issue with that.
> Maybe it would be better that the custom rule creation complies with the plugin-api (which mean, no validation?)
> I’ll check with plugin-api guild if it is expected that there are no validation
> 
> Edit: No more information on that, Language team generally sticks with an internal naming convention for ruleKeys, and nothing is enforced at plugin-api level
> 

https://sonarsource.atlassian.net/browse/SONAR-21052 ticket was closed.
