### ISSUE TITLE
Very little security rules and security hotspot rules

### ISSUE THREAD

**Issue by tenghunghong** [SonarOpenCommunity/sonar-cxx#2623]
Hi , I have installed the SonarQube- Cxx Scanner into my exsisting Sonarqube System. I did a successful scan which was great but Im a little confuse on the rules. I notice that the scan for my projects has very little security rules and 0 security hotspot rules. Would it be possible that i am missing something or i loaded something wrongly ?

**Comment by guwirth** [comment]
Hi @tenghunghong,

the focus of the cxx plugin is the integration of third party tools. The plugin read their resulting reports only. So result depends on the used tools. 

Think https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files is a good starting point in our Wiki. 

Regards,
