### ISSUE TITLE
 can you update xx-custom-checks-example-plugin for Sonar 9.9 TLS 

### ISSUE THREAD

**Issue by smileQiny** [SonarOpenCommunity/sonar-cxx#2624]
hi guwirth：
I found that the example plugin shown in the https://github.com/SonarOpenCommunity/sonar-cxx/wiki/CXX-Custom-Rules is too old. The pom still relies on the old sonar-cxx, and the cxx in the code has also changed, which is very unfriendly to a newcomer who wants to use CXX-Custom-Rules. Can you update CXX-Custom-Rules for 9.9TLS?

**Comment by guwirth** [comment]
Hi @smileQiny,

you are right the sample is outdated. The original maintainer @jmecosta does not support it anymore. I can have a look but I have less time at the moment so it can take some time.

Depending what you wanna do https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/importing-external-issues/generic-issue-import-format/ could be an alternative.

Regards,

**Comment by smileQiny** [comment]
thinks
