### ISSUE TITLE
How to define program language

### ISSUE THREAD

**Issue by SvenLie** [SonarOpenCommunity/sonar-cxx#2641]
Hi,

I have not found a way to tell sonar-cxx that it is C code and not C++ code. Is this possible so that it does not apply C++ rules?

Best regards,
SvenLie

**Comment by guwirth** [comment]
Hello @SvenLie,

thanks for your question.
* Description of the plugin: SonarQube C++ Community plugin (cxx plugin): This plugin adds C++ support to SonarQube with the focus on integration of existing C++ tools. 
* The grammar we are using is supporting C/C++ and some variants: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-compiler-specific-extensions
   * https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Source-Code
   * https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors
* To define which files you like to include you can use: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.file.suffixes
* You have to decide by your own which rules makes sense in your context, there is no predefined C quality profile:
   * https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Scan-Report-Files
   * https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Manage-Quality-Profiles

Regards,
