### ISSUE TITLE
cppcheck report v2 is parsing with CppcheckParserV1

### ISSUE THREAD

**Issue by maxstreichert** [SonarOpenCommunity/sonar-cxx#266]
Hello,
I have a problem with the cppcheck sensor. My cppcheck report was created in xml-version=2 format, but sonar-runner parses it with CppcheckParserV1 (see below). Issues in the report don't appear in sonarqube. What's going wrong?

034:28,013       [java] 10:41:00.956 INFO  - Processing report 'u:\IfrsRkWin32x64\ifrsRK.\cppcheck_ifrsRK.xml'
034:28,013       [java] 10:41:00.956 INFO  - cppcheck V2 - Parsing report 'u:\IfrsRkWin32x64\ifrsRK.\cppcheck_ifrsRK.xml'
034:28,314       [java] 10:41:01.175 INFO  - cppcheck V1 - Parsing report 'u:\IfrsRkWin32x64\ifrsRK.\cppcheck_ifrsRK.xml'
034:28,314       [java] 10:41:01.177 INFO  - CppCheck issues processed = 0
034:28,315       [java] 10:41:01.178 INFO  - Added report 'u:\IfrsRkWin32x64\ifrsRK.\cppcheck_ifrsRK.xml' (parsed by: CppcheckParserV1)

**Comment by amaigil2** [comment]
Does the step of parsing include a report to the DB - so that a failure there might influence the result of the parsing step??

**Comment by wenns** [comment]
Yes, it does. I also stumbled over this some weeks ago. We have to separate parsing and storing in Sonar.
