### ISSUE TITLE
Squid preprocessor error and the sonar scanner procedure will be stuck

### ISSUE THREAD

**Issue by recursively** [SonarOpenCommunity/sonar-cxx#2666]
In some specific projects, the sonar scanner process will be stuck when enabling the **sonar.cxx.squid.disabled=false** option and the output will be like the below. I think there should be some mechanism to handle the preprocessor exceptions instead of being stuck forever.

The output:

```
INFO: Sensor CXX [cxx]
WARN: preprocessor error evaluating expression '' for token 'IDENTIFIER: __GNUC_PREREQ', assuming 0
WARN: preprocessor error evaluating expression '' for token 'IDENTIFIER: __GNUC_PREREQ', assuming 0
WARN: preprocessor error evaluating expression '' for token 'IDENTIFIER: BOOST_WORKAROUND', assuming 0
WARN: preprocessor error evaluating expression '' for token 'IDENTIFIER: BOOST_WORKAROUND', assuming 0
WARN: Cannot parse 'R"/"PTPD_PROGNAME".status"', ignoring...
WARN: Cannot parse ';
int applyConfigTemplates(dictionary *dict, char *templateNames, char *files);
PtpEnginePreset getPtpPreset(int presetNumber, RunTimeOpts* rtOpts);
void dumpConfigTemplates();

#endif /* PTPD_CONFIGDEFAULTS_H_ */
R"/"PACKAGE_NAME"/templates.conf"', ignoring... 
WARN: preprocessor error evaluating expression '' for token 'IDENTIFIER: BOOST_WORKAROUND', assuming 0
WARN: preprocessor error evaluating expression '' for token 'IDENTIFIER: BOOST_PP_CONFIG_FLAGS', assuming 0
WARN: preprocessor error evaluating expression '' for token 'IDENTIFIER: BOOST_PP_CONFIG_EDG', assuming 0
WARN: preprocessor error evaluating expression '' for token 'IDENTIFIER: BOOST_PP_CONFIG_FLAGS', assuming 0
WARN: preprocessor error evaluating expression '' for token 'IDENTIFIER: BOOST_PP_CONFIG_STRICT', assuming 0
WARN: preprocessor error evaluating expression '' for token 'IDENTIFIER: __GNUC_PREREQ__', assuming 0
WARN: preprocessor error evaluating expression '' for token 'IDENTIFIER: __GNUC_PREREQ', assuming 0
```

**Comment by guwirth** [comment]
Hello @recursively,

thanks for the feedback.

> I think there should be some mechanism to handle the preprocessor exceptions instead of being stuck forever.

I can't see a exception in the LOG file, can you provide please:
* the exception text you are talking about
* a source code sample to reproduce the problem

Thx & regards

**Comment by guwirth** [comment]
@recursively: please read https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors

**Comment by recursively** [comment]
> @recursively: please read https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors

Thank you for your comment, I have checked this document, but It doesn't seem to be helpful for my issue. 

In addition to the warnings above, I also encountered the following errors:

INFO: Sensor CXX [cxx]
ERROR: preprocessor: undefined function-like macro 'BOOST_WORKAROUND' assuming 0
ERROR: preprocessor: undefined function-like macro 'BOOST_WORKAROUND' assuming 0
WARN: Cannot parse 'R"/"PTPD_PROGNAME".status"', ignoring...
WARN: Cannot parse ';
int applyConfigTemplates(dictionary *dict, char *templateNames, char *files);
PtpEnginePreset getPtpPreset(int presetNumber, RunTimeOpts* rtOpts);
void dumpConfigTemplates();

#endif /* PTPD_CONFIGDEFAULTS_H_ */
R"/"PACKAGE_NAME"/templates.conf"', ignoring...
ERROR: preprocessor: undefined function-like macro 'BOOST_WORKAROUND' assuming 0
ERROR: preprocessor: undefined function-like macro 'BOOST_PP_CONFIG_FLAGS' assuming 0
ERROR: preprocessor: undefined function-like macro 'BOOST_PP_CONFIG_EDG' assuming 0
ERROR: preprocessor: undefined function-like macro 'BOOST_PP_CONFIG_FLAGS' assuming 0
ERROR: preprocessor: undefined function-like macro 'BOOST_PP_CONFIG_STRICT' assuming 0


It's difficult to reproduce the problem because there are thousands of macros in the project, and all those macros have the same names as they are mentioned in the log, I don't know how they caused this problem.

I have tried the cxx rule **cxx:ParsingErrorRecovery**, but those errors or warnings still cannot be skipped. Once the preprocessor-related exceptions occur, the sonar scanner process will be stuck and it won't continue or stop.

**Comment by guwirth** [comment]
Hi @recursively,

> ERROR: preprocessor: undefined function-like macro 'BOOST_WORKAROUND' assuming 0

Means the preprocessor is finding a `BOOST_WORKAROUND(symbol, test)` without knowing this macro. You have to provide the macro definition or header file. Sample from Boost https://www.boost.org/doc/libs/1_46_0/boost/detail/workaround.hpp

> WARN: Cannot parse 'R"/"PTPD_PROGNAME".status"', ignoring...

Maybe you can provide more code from this (search for `PTPD_PROGNAME` in your code) to better understand the issue.

Regards,

**Comment by recursively** [comment]
Thank you @guwirth ,

Is there any possible proposal to bypass the macro check errors? If there are too many unknown macros, it will be very difficult to define them one by one. it's better to provide a warning rather than causing the process to hang indefinitely without termination.

**Comment by guwirth** [comment]
Hi @recursively,

> Is there any possible proposal to bypass the macro check errors?

No. The macros are necessary that the preprocessor can create syntactically correct code for the following grammar check. In case of syntax error the parser runs into error recovery which is the root cause for the slow parsing.

I recommend you to provide a minimal set of macros to get better results. Two samples:
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/macros/GxxMacros.h
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/macros/VS10Macros.h

Regards,

**Comment by guwirth** [comment]
Sample:
```C++
#define BOOST_WORKAROUND(...)
#define PTPD_PROGNAME "dummy"
```

Add this to a header file and include it with 
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.forceIncludes

**Comment by recursively** [comment]
Got it, I will try to add some macros by myself, thanks! @guwirth
