### ISSUE TITLE
Unable to run sonar-scanner with cppdepend

### ISSUE THREAD

**Issue by taheri1395** [SonarOpenCommunity/sonar-cxx#2687]
Hi

Currently running SonarQube Data Center edition version 10.4.1, CppDepend version 2024.1, Sonar Scanner version 5.0.1 on Windows 10 machine. Installed plugins are “sonar-cxx-cppdepend-community-1”. I have created myproject.csproj files and I integrated this sonar with cppdepend and active all rules in sonarqube.

I want to run sonar-scanner with this command, It is running successfully but this is not getting files or lines of code:

`sonar-scanner.bat -D"sonar.token=***" -D"sonar.projectKey=test" -D"sonar.cpp.cppdepend.projectPath="C:\user\Demo.cdproj"`

It seems that it does not recognize the  `-D sonar.cpp.cppdepend.projectPath` command.

Please help me handle this problem.

**Comment by guwirth** [comment]
Hi @taheri1395,

Please ask Cppdepend for help: https://www.cppdepend.com/documentation/sonarqube-community-integration-cppdepend

For SQ 10.4 you have to use https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-2.2.0-beta.2, see compatibility matrix https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compatibility-Matrix.

The cxx configuration supports only these configuration settings https://github.com/SonarOpenCommunity/sonar-cxx/wiki/CXX-Analysis-Parameters. 

Hope that helps!

Regards,
