### ISSUE TITLE
Add LLVM-18 Support

### ISSUE THREAD

**Issue by opajonk** [SonarOpenCommunity/sonar-cxx#2705]
First check if there is not already a [feature request](https://github.com/SonarOpenCommunity/sonar-cxx/issues) for your idea. - :heavy_check_mark: 

**Is your feature request related to a problem? Please describe.**
Currently, some rules that Clang-Tidy 17/18 supports cannot be reported into SonarQube since the plugin does not support them.

**Describe the solution you'd like**
Basically, do what [this commit](https://github.com/SonarOpenCommunity/sonar-cxx/commit/ef161e05ec1d627ed88863a6a0f47542cb28efbe) did for LLVM-16.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by opajonk** [comment]
Maybe this is a really simple job for someone who knows the plugin and has the setup required at hand. If not, I can try it, though.

**Comment by guwirth** [comment]
Hi @opajonk,

Please have a look to #2640 which is part of https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/latest-snapshot.

Should close this request?

Regards,

**Comment by opajonk** [comment]
Oh well, sorry - I somehow did not see that one. Of course it does ;-) 

I checked at least for `bugprone-empty-catch` which was the reason for me asking, and it is in the description. Thanks!

**Comment by opajonk** [comment]
As a follow-up I created https://github.com/SonarOpenCommunity/sonar-cxx/pull/2640 to port this to SQ-10 (which is the version we are using already)
