### ISSUE TITLE
How were the gcc rules generated?

### ISSUE THREAD

**Issue by reddwarf69** [SonarOpenCommunity/sonar-cxx#2720]
https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/cxx-sensors/src/tools has plenty of tools to generate the files stored in https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/cxx-sensors/src/main/resources. But it strangely lacks one for compiler-gcc.xml.

What's the process to update those rules?

**Comment by guwirth** [comment]
Hi @reddwarf69,

the cxx plugin has a longer history and different maintainers. The sensors are contributed and updated by different people and not all rulesets are up to date. The gcc rules were updated 3 years ago the last time. There is also no script to generate them.

I would be happy if you could have a look and update the rules.

Regards,

**Comment by guwirth** [comment]
In case you create a new rule file avoid setting default values to keep the XML small.

**Comment by reddwarf69** [comment]
I was looking at the format of the xml, and noticed it has been deprecated since SonarQube 9.0 (https://javadocs.sonarsource.org/latest/org/sonar/api/server/rule/RulesDefinitionXmlLoader.html / https://sonarsource.atlassian.net/browse/SONAR-14908).

Is the plan to keep supporting these xml files, just copying RulesDefinitionXmlLoader into sonar-cxx when they remove it?

**Comment by guwirth** [comment]
Hi @reddwarf69,

I like to continue with the XML format and we have already a local copy:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/10371d39e5d6d0aabc5598edfae358188cd4b385/cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/RulesDefinitionXmlLoader.java#L214

Regards,

**Comment by cmorve-te** [comment]
I was looking at the specific warnings, and I am surprised lines ending with `[-Wformat-overflow=]`, for which the regex will match `-Wformat-overflow=` to the id capture group... actually end up appearing as `compiler-gcc:-Wformat-overflow` in SonarQube. What's happening here, why isn't the trailing `=` a problem?

**Comment by guwirth** [comment]
Hi @cmorve-te,

> What's happening here, why isn't the trailing = a problem?

this is doing the magic
https://github.com/SonarOpenCommunity/sonar-cxx/blob/717b92a8171c5b6813e1acffa7c7c32bd8d76f7b/cxx-sensors/src/main/java/org/sonar/cxx/sensors/compiler/gcc/CxxCompilerGccSensor.java#L112

Regards,

**Comment by cmorve-te** [comment]
My employer has to approve, but I will create a PR with the gcc rules updated for 14.2.0 and a python script to create them "soon".

This issue can be closed, since the question was answered: "There is also no script to generate them."
