### ISSUE TITLE
SonarQube 10 artefacts

### ISSUE THREAD

**Issue by anotherandi** [SonarOpenCommunity/sonar-cxx#2721]
Hi @guwirth,

with the "Latest Snapshot" Release for V 2.1.3, the artefacts of the SQ-10 Snasphot were dropped.
I'd kindly ask you to provide Snapshot Releases for 2.1.x (SQ-9) and 2.2.x (SQ-10) in parallel.
May you could also provide a new 2.2.x-beta-x?

Thanks a lot!

**Comment by guwirth** [comment]
Hi @anotherandi,

> May you could also provide a new 2.2.x-beta-x?

I’m working on it. Problem is that with the SonarScanner 6.x our integration tests are no more working. There are (many incompatible) changes …

https://github.com/SonarOpenCommunity/sonar-cxx/pull/2718
https://github.com/SonarOpenCommunity/sonar-cxx/actions/runs/10432539159

Regards,

**Comment by guwirth** [comment]
@anotherandi you can find last successful builds always here:
* https://github.com/SonarOpenCommunity/sonar-cxx/actions/workflows/cxx-ci.yml
  * https://github.com/SonarOpenCommunity/sonar-cxx/actions/runs/10421530640
    * JAR_Files
