### ISSUE TITLE
Update Clang-Tidy support to released version 19.1.0

### ISSUE THREAD

**Issue by opajonk** [SonarOpenCommunity/sonar-cxx#2778]
**Is your feature request related to a problem? Please describe.**
The [current list of Clang-Tidy Checks](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/clangtidy.xml) does not include some of the checks described in the [Clang-Tidy 19.1.0 Release Notes](https://releases.llvm.org/19.1.0/tools/clang/tools/extra/docs/ReleaseNotes.html#new-checks), for example `bugprone-pointer-arithmetic-on-polymorphic-object`.

**Describe the solution you'd like**
The Clang-Tidy Checks supported by the plugin should be updated to at least the state of the Clang-Tidy 19.1.0 release.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by opajonk** [comment]
I am not sure, but maybe this is a simple thing to do. I noticed some Python scripts that seem to be related to updating this XML file?

**Comment by guwirth** [comment]
Hi @opajonk,

we usually don't apply minor changes, we wait until a new major version of the tool is released.

We have scripts with which you can extract the rules, but unfortunately you still have to do some things manually:
- https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/tools/generate_clangtidy_resources.cmd
- https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/tools/generate_clangtidy_resources.sh
- for hints: https://github.com/SonarOpenCommunity/sonar-cxx/issues/2739#issuecomment-2337394587
- last update LLVM 19 support https://github.com/SonarOpenCommunity/sonar-cxx/pull/2640 https://github.com/SonarOpenCommunity/sonar-cxx/issues/2705

Regards,

**Comment by opajonk** [comment]
Here comes the fun part (I also did not know this first): the "stable major release" of LLVM [is always](https://www.phoronix.com/news/LLVM-N-1-Stable-Versioning) a "N.1.0", resembling what GCC does since its "5.X" releases. Hence, 19.1.0 is the first stable release of the 19.X release series...

**Comment by opajonk** [comment]
Anyway, I started to try this out myself. *Something* is happening :smile: I will file a PR if this leads to anything useful...

**Comment by opajonk** [comment]
Let's see if I did things correctly :crossed_fingers:
