### ISSUE TITLE
clang: Handle old C++ standard aliases

### ISSUE THREAD

**Issue by cmorve-te** [SonarOpenCommunity/sonar-cxx#2816]
clangtidy.xml includes, for example, both a [clang-diagnostic-c++1y-extensions](https://github.com/SonarOpenCommunity/sonar-cxx/blob/1c56e693b8d3297b94eadc5b301c1fe8d90bde73/cxx-sensors/src/main/resources/clangtidy.xml#L35748) rule and a [clang-diagnostic-c++14-extensions](https://github.com/SonarOpenCommunity/sonar-cxx/blob/1c56e693b8d3297b94eadc5b301c1fe8d90bde73/cxx-sensors/src/main/resources/clangtidy.xml#L21259) rule. They are logically the same rule, though.

If somebody is scanning the output of an old version of clang, and "clang-diagnostic-c++1y-extensions" is found, it should probably be treated as a clang-diagnostic-c++14-extensions match.

AFAICT this applies to the following rules

- C++14
clang-diagnostic-c++1y-extensions -> clang-diagnostic-c++14-extensions

- C++17
clang-diagnostic-c++1z-compat -> clang-diagnostic-c++17-compat
clang-diagnostic-c++1z-compat-mangling -> clang-diagnostic-c++17-compat-mangling
clang-diagnostic-c++1z-extensions -> clang-diagnostic-c++17-extensions

- C++20
clang-diagnostic-c++2a-compat -> clang-diagnostic-c++20-compat
clang-diagnostic-c++2a-compat-pedantic -> clang-diagnostic-c++20-compat-pedantic
clang-diagnostic-c++2a-extensions -> clang-diagnostic-c++20-extensions

- C++23
clang-diagnostic-c++2b-extensions -> clang-diagnostic-c++23-extensions
clang-diagnostic-pre-c++2b-compat -> clang-diagnostic-pre-c++23-compat
clang-diagnostic-pre-c++2b-compat-pedantic -> clang-diagnostic-pre-c++23-compat-pedantic

- C++26
clang-diagnostic-c++2c-compat -> clang-diagnostic-c++26-compat
clang-diagnostic-c++2c-extensions -> clang-diagnostic-c++26-extensions
clang-diagnostic-pre-c++2c-compat -> clang-diagnostic-pre-c++26-compat
clang-diagnostic-pre-c++2c-compat-pedantic -> clang-diagnostic-pre-c++26-compat-pedantic

**Comment by guwirth** [comment]
Normally, the sensors support all the rules of the current version and also those of the previous versions. With cxx 2.2.x we can think about cleaning up and removing outdated rules. For me, the decisive factor is always which version of the tool is included in larger Linux distributions. These rules should at least be supported:
- Ubuntu 22.04.5 LTS => clang 14?
- Debian 11 “Bullseye” => clang 11?

1. Can someone give more feedback of which clang versions are in use?
2. For example, could we only support the clang 14 rules and remove all older rules?

**Comment by guwirth** [comment]
Mapping a rule ID can lead to an issue being moved from old code to [new code](https://docs.sonarsource.com/sonarqube/latest/core-concepts/clean-as-you-code/about-new-code/). See also [Issue identification mechanisms](https://docs.sonarsource.com/sonarqube/latest/user-guide/issues/solution-overview/) to learn how new issues are calculated. In some cases the mechanism is doing a [backdating](https://docs.sonarsource.com/sonarqube/latest/user-guide/issues/solution-overview/#issue-backdating-new-issues-raised-on-old-code).

In case we are doing a mapping the correct way is to register the mapping during repository creation.

**RulesDefinition**:
https://github.com/SonarSource/sonar-plugin-api/blob/bb901cd17c9ab2cf2df18e0ad9062188e5afc543/plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java#L605

**CxxClangTidyRuleRepository**:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/24f35c775a945010a18d300c2d53bbd088a56b93/cxx-sensors/src/main/java/org/sonar/cxx/sensors/clangtidy/CxxClangTidyRuleRepository.java#L45

**Comment by guwirth** [comment]
Asking SonarSource for details to deprecated rules: https://community.sonarsource.com/t/handling-of-deprecated-rules/131032

**Comment by guwirth** [comment]
@cmorve-te I'm playing around with it to find a correct solution.

**Comment by guwirth** [comment]
@cmorve-te: I played around with it, see description above.

I tend to the following solution:
1) Mark deprecated rules in the repository (XML) with deprecated. This means old/new rule/key is in the repository.
2) Do no mapping in the sensor. People using older versions of the tool see the rules as deprecated. Others using the latest version get the issues with new rule/key.
3) After some time remove the deprecated rules from repository (XML) and creating a mapping with [addDeprecatedRuleKey](https://javadocs.sonarsource.org/latest/org/sonar/api/server/rule/RulesDefinition.Rule.html#deprecatedRuleKeys()) where a successor is available. If still old key is used it can be made visible with [CXX Unknown Rule](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/CXX-Unknown-Rule)

**Comment by cmorve-te** [comment]
> Mark deprecated rules in the repository (XML) with deprecated. This means old/new rule/key is in the repository.

What do we achieve with this?
It seems to me the deprecated thing is something Sonar can do because the tool (SonarQube) that creates the "warnings" and the thing that creates the rules (SonarQube) are the same thing. I don't think I see the point when third-party tools are creating the warnings.

It's a way of saying "we will stop supporting your old toolchain soon". But C++ developers would be happy to be able to use coroutines, modules and the latest and the greatest, if they are using an old toolchain it's because it's imposed by an external entity. Telling them "it's old" it's not going to change anything, they will just say "I know, I wish I could update it".

> Do no mapping in the sensor. People using older versions of the tool see the rules as deprecated. Others using the latest version get the issues with new rule/key.

Do we want people updating their toolchain to get a "new" issue that's actually the same one that already existed, just with a different name?

Some people will be using multiple toolchains (building for different targets), they will get the same issue duplicated, with different names.



What's the problem with your original idea of just adding the addDeprecatedRuleKey rule now (deleting the standalone old one)? From what I understand:
- All the existing "clang-diagnostic-c++1y-extensions" issues will magically transform into "clang-diagnostic-c++14-extensions". I would argue this is good, not a problem.
- If you use the new toolchain, everything will be directly "clang-diagnostic-c++14-extensions".
- If you use the old toolchain, new issues will still be "clang-diagnostic-c++14-extensions" (not sure if this requires also manual mapping in the plugin, but it would be added if needed)
- If you use both the old and new toolchains, it will be a single issue: clang-diagnostic-c++14-extensions, not duplicated.

**Comment by cmorve-te** [comment]
> What's the problem with your original idea of just adding the addDeprecatedRuleKey rule now (deleting the standalone old one)?

i.e. https://github.com/SonarOpenCommunity/sonar-cxx/pull/2824/files seems fine to me. Isn't it?

**Comment by guwirth** [comment]
> i.e. #2824 seems fine to me. Isn't it?

@cmorve-te Yes #2824 implements everything it needs, old rules have been removed, [addDeprecatedRuleKey](https://javadocs.sonarsource.org/latest/org/sonar/api/server/rule/RulesDefinition.Rule.html#deprecatedRuleKeys()) ensures that new rules are not accidentally displayed as New Code and a mapping in the sensor (if the old rule is used by an older tool version).

So far so good. During implementation, however, I noticed how time-consuming this is to implement and will be to maintain in the future. I am currently happy if the rule sets are reasonably up-to-date. Maintaining the mapping as well as the rule sets at 3 places is very time-consuming.

Hence the simplified suggestion with the Deprecated mark in the XML (is then only one place), and if you remove the rule and there is a successor, mark in the repository via `addDeprecatedRuleKey`. Maybe we could also put this in XML (with an extra tag), then it would also be in one place.

I find the mapping in the sensor difficult. Where do we document this? Everyone who has rule A in the report must also know that this is mapped to rule B?

**Comment by cmorve-te** [comment]
> So far so good. During implementation, however, I noticed how time-consuming this is to implement and will be to maintain in the future. I am currently happy if the rule sets are reasonably up-to-date. Maintaining the mapping as well as the rule sets at 3 places is very time-consuming.

Correct me if I'm wrong.

The normal updating process is
1. Update your llvm repository checkout to the new version
2. Run clangtidy_createrules.py
3. Copy&paste the output of clangtidy_createrules.py into clangtidy.xml (there is the idea of splitting this file into two, clang-tidy and clang compiler, files; but so far is this)
4. Check the diff to see if any rule has been removed
    - If you see removed rules, add them to [add_old_clangtidy_rules](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/tools/clangtidy_createrules.py#L350) / [add_old_diagnostics_rules](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/tools/clangtidy_createrules.py#L567). These functions serve as documentation for the list of old rules.
    - Re-run clangtidy_createrules.py, and verify no rules are removed now
5. Update the number of warnings in CxxClangTidyRuleRepositoryTest.java
6. Commit

Handling rule renames adds:
- In 4, if you see a rule removed, before adding it to [add_old_clangtidy_rules](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/tools/clangtidy_createrules.py#L350) / [add_old_diagnostics_rules](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/tools/clangtidy_createrules.py#L567), check whether a new rule exists that's actually the old rule renamed.
- If it's a renamed rule, don't add the old one to [add_old_clangtidy_rules](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/tools/clangtidy_createrules.py#L350) / [add_old_diagnostics_rules](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/tools/clangtidy_createrules.py#L567), let it disappear from clangtidy.xml; but add it to mapDeprecatedRules().

So handling renamed rules would be basically no different that handling old rules: add them to one list.


In PR#2824 I see the renamed rules list duplicated in mapDeprecatedRules() and prepareRule(). But the list can probably be created only once, and then have both mapDeprecatedRules() and prepareRule() look into the single list, no? This single list would serve as the documentation of renamed rules.

Potentially the rules in [add_old_clangtidy_rules](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/tools/clangtidy_createrules.py#L350) / [add_old_diagnostics_rules](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/tools/clangtidy_createrules.py#L567) could be marked as deprecated, and some policy to remove them created. But so far, there are:
- Two old clang-tidy rules (and I think clang-analyzer-core.DynamicTypePropagation has never been a real warning)
- 18 old clang rules, plus 14 renamed rules

So it looks manageable? The only renamed rules so far have been regarding new C++ standards, so it's just 3-4 rules renamed every 3 years.


FWIW there are also, in gcc
- 5 renamed rules: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/java/org/sonar/cxx/sensors/compiler/gcc/CxxCompilerGccSensor.java#L122
- 3 old rules: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/tools/gcc_createrules.py#L38


> I find the mapping in the sensor difficult. Where do we document this? Everyone who has rule A in the report must also know that this is mapped to rule B?

Not sure I got this part. What "report" are you talking about here?
AFAIU, for users, anywhere where there was a reference to clang-diagnostic-c++1y-extensions they will now see clang-diagnostic-c++14-extensions. There is nothing they need to do, right?

**Comment by guwirth** [comment]
Hi @cmorve-te,

Your points are all not wrong. However, from past experience, I would like to manage this in one place. My idea is to manage this all in the XML rules file.

**default rule with status=READY (READY is default and not necessary in XML):** 
```XML
<rules>
  <rule>
    <key>AAA</key>
    ...
    <status>READY</status>
  </rule>
</rules>
```
**rule is deprecated but still supported:** 
```XML
<rules>
  <rule>
    <key>AAA</key>
    ...
    <status>DEPRECATED</status>
  </rule>
</rules>
```
**replaced by new rule:** 
```XML
<rules>
  <rule>
    <key>BBB</key>
    <deprecatedKey>AAA</deprecatedKey>
    ...
    <status>READY</status>
  </rule>
</rules>
```
Extension would be to read `RulesDefinition` also on scanner side to create mapping (AAA => BBB):
https://github.com/SonarOpenCommunity/sonar-cxx/blob/e8aeeb30151ec9921977e02089509c4ce9f4844a/cxx-sensors/src/main/java/org/sonar/cxx/sensors/utils/RulesDefinitionXml.java#L38

Regards,

**Comment by cmorve-te** [comment]
Very much like the idea of having RulesDefinitionXml reading extensions for this from the XML.

Not so sure about the XML being the root of this information. I would consider the XML just an autogenerated file, from the Python script. So any information in the XML would come from the script, which would be the actual root source for this information.

I would like the script to generate the xml as-it-is (or at least as much as possible) because that helps

- Verify the xml is correct, by just re-running the script
- When updating, where you don't want to have to think "this part of the diff was already there" vs "this part of the diff is an actual update". When re-running the Python script with a new version of llvm ideally you would want the whole diff to be "updates".

**Comment by cmorve-te** [comment]
Alternatively, the information could be directly in the XML, but somehow separated, at the top. So you would have a part of the XML managed by hand vs a part auto-generated by the script, avoiding the "already there vs already there diff" problem?

```
<!-- Previous Rule Name -->
<rule_renames>
  <rule_rename>
    <new_name>clang-diagnostic-c++14-extensions</new_name>
    <old_name>clang-diagnostic-c++1y-extensions</old_name>
  </rule_rename>
</rule_renames>
<!-- Rules-->
<rules>
  <!-- Old Rules -->
  <rule>
    <key>old rule</key>
    ...
    <status>DEPRECATED</status>
  </rule>
  <!-- Actual Rules -->
  <rule>
    <key>clang-diagnostic-c++14-extensions</key>
    ...
    <status>READY</status>
  </rule>
</rules>
```
This would allow the script to just generate "Actual Rules", and you would look at the diff only there.
Nobody is going to be a fan of having the information of clang-diagnostic-c++14-extensions split into two places, though...

**Comment by cmorve-te** [comment]
I don't know a better place to ask...

When do you plan to release 2.2.0 final? And, related, any reason not to use V2.2.0-beta.9 in production today?

I am pushing to start using this plugin internally in our company. I was just trying to get the gcc/llvm warnings updated first to start clean. Now V2.2.0-beta.9 seems to have everything we want, but it may need some convincing to get something labelled "beta" installed.

The only listed known issue is "SonarQube 10.x is significantly slower than SonarQube 9.9 LTS", which I think it's a generic issue with SonarQube 10.x unrelated to sonar-cxx anyway, right?

**Comment by guwirth** [comment]
@cmorve-te

> When do you plan to release 2.2.0 final?

With SQ 10.x LTS. In the past we released the plugin only for LTS versions. For other versions the API is typically not stable enough. For my understanding next version 10.9 could be the LTS version (https://community.sonarsource.com/t/inquiry-regarding-sonarqube-10-x-lts-release-date/111939). 

> any reason not to use V2.2.0-beta.9 in production today?

No, the testing is exactly the same.
