### ISSUE TITLE
Automated deployment with Travis CI

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#293]
Would be good to provide results of Travis CI for download:
* positive build result of a pull request: as alpha version
* positive build results of master branch: as a beta version
* tag of master branch: as release version

Found this
* http://docs.travis-ci.com/user/deployment/releases/
* http://docs.travis-ci.com/user/deployment/custom/

Is someone familiar with Travis CI and knows more details?

**Comment by wenns** [comment]
AFAIR, last time I looked into this issue I came to the conclusion that one needs a dummy git tag aka release for that, which then will be continuously overwritten with the last build artifact from Travis.

**Comment by jmecosta** [comment]
Cant we authorize everyone to see pre releases until we get your proposal going

**Comment by guwirth** [comment]
You have to publish the release (pre-release) otherwise others can't see it. Point is that this is always manuall effort. Would not do it. Question is also if we do this only for trunk or also for branches? Who is updating and maintaining this after each PR and merge?

**Comment by jmecosta** [comment]
seems github does not like me pressing publish as it does not work, anyway my best proposal would be to get travis to produde artifacts, also for feature branches. official release its best to still be under user control...

**Comment by guwirth** [comment]
It is AppVeyor and not Travis - but working. Link in README.md:
https://ci.appveyor.com/project/jorgecosta/sonar-cxx/build/artifacts
