### ISSUE TITLE
Changes of the xunit feature

### ISSUE THREAD

**Issue by wenns** [SonarOpenCommunity/sonar-cxx#309]
@jmecosta, @guwirth, @Typz, @Bertk 

Currently, I am in progress of validating the xunit-feature (importing the test execution metrics), i.e. writing integration tests, writing a grammar for the input format etc. I have a couple of findings so far:
- As well the JUnit (version 4.14) as Googletest (version 1.6) produce reports which begin with the tag 'testsuites'. Current implementation is able to consume it, because it ignores the root tag, just to the testssuite tag, iterates over all testcases and import them. Given a report with _multiple_ testsuite-tags in it, it will _ignore_ all but the first one.

**I think I will change this behaviour to a more sane one "loop over all testsuite-tags"**
- We've introduced the filename attribute as a means to locate the test resources. Using this tag (and the knowledge which test resides in which file) one can augment the report putting such attributes holding paths to the right files into right places in the report. Now, it is only accepted in the **testsuite**-tag, which seems to be wrong, as at makes the assumption that all testcases  belonging to the same testsuite reside in the same source file. Which is clearly wrong. 

**I think we should move the attribute down into the testcase tags**
- The XML samples used in the unit tests do not conform to the schema in full extend. Some dont use "testsuites" as root tag. Some contain attributes which neither JUnit nor Googletest produce.

**My plan is to correct those file to conform to the grammar**

Comments, ideas, objections?

**Comment by wenns** [comment]
Documentation: https://github.com/wenns/sonar-cxx/wiki/Get-test-execution-metrics
While writing it, I had *again* a strong feeling that we should support filename-tag at testcase level and stop to misuse classname for holding the filename. This inconsequence cannot be explained sanely in the dox and thats a strong symptom... 

I want to change this and also improve the logging (as jmecosta suggested) before the release.

@guwirth then you can begin to test it with your boost-toolchain.

**Comment by jmecosta** [comment]
@wenns have you been able to parse gtest source files. for some reason i
cant get those ones parsed properly and am not sure if that was the case in
earlier releases... does not look to be include headers since all those can
be found. for example ::testing cannot be parsed... do we have any bdd with
such configuration, i look to the existing one but there is no includes,
macros definition to support those..

another thing, i notice that when supplying the filename tag the sensor
still constructs the AST for those resources. can you remind me again why
do we need to do that, and just not trust user gives the correct source
files?

**Comment by wenns** [comment]
Parsing gtest source files: the BDD setups dont include gtests, thus gtests source files arent parsed. The AST-based lookup works in my scenarios without parsing those.

Skipping parsing & building lookup table in case filename-attributes are provided for all testcases:
i think we can do that.

**Comment by jmecosta** [comment]
ok i can prepare the bdd with test case filename attribute

**Comment by guwirth** [comment]
Hello @wenns thank you for the documenation.

Reading the wiki page I have some hints/questions:
1. Simple and detailed mode: Which one is the default? 
2. In case I use 'filename' tag, do I have to define also 'sonar.tests' property or is filename tag sufficient in this case?
3. Using classname for filename is confusing. Maybe providing a stylesheet for translation would be easier/more clear?
4. Supported reports: Tag filename is missing in the example.
5. Supported reports: Are nested testsuites allowed/supported?
6. Which is the easiest possible configuration? Use ```sonar.sources=.``` and ```sonar.tests=.``` ? Is there a problem reading sources as source & test?

**Comment by guwirth** [comment]
> sonar.sources=. and sonar.tests=. ? Is there a problem reading sources as source & test?

ERROR: Caused by: File [relative=x/y.cpp, abs=D:/x/y.cpp] can't be indexed twice. Please check that inclusion/exclusion patterns produce disjoint sets for main and test files

> Simple and detailed mode: Which one is the default? 

```
sonar.cxx.xunit.provideDetails=true
```

Tests with boosttest-1.x-to-junit-1.0.xsl

* Test 1: sonar.cxx.xunit.provideDetails=false => working
* Test 2:  nested testsuites => is working

boost unit test source:
```XML
<TestLog>
  <TestSuite name="MyTest">
    <TestSuite name="UnitTestCanCommands">
      <TestCase name="Test_CAN_SEND_MESSAGE_NoCanID">
        <TestingTime>856000</TestingTime>
      </TestCase>
```
after transformation:
```XML
<testsuite tests="86" errors="0" failures="0" name="MergedTestSuite" skipped="0">
  <testcase classname="MyTest.UnitTestCanCommands." name="Test_CAN_SEND_MESSAGE_NoCanID" time="0.856"/>
```
* Test 3: sonar.cxx.xunit.provideDetails=true ==> no results, which is not amazing because there is no filename in the report.

Tests open:
* try to add file to boost test report

**Comment by jmecosta** [comment]
check this
https://github.com/jmecosta/sonar-cxx/blob/bullseye-it/integration-tests/testdata/googletest_bullseye_vs_project/sonar-project.properties

that one has tests and sources configured properly

**Comment by guwirth** [comment]
Thx, below lines are doing the trick. Files must be unique assigned to sources or tests:
```
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=file:**/**/PathHandling.Test/**
sonar.exclusions=file:**/**/PathHandling.Test/**
```
@jmecosta But what is the **file:** for. Found it with and without in in SQ help files?

**Comment by jmecosta** [comment]
Likely one refers to folders and the other one to files.. Not 100% sure

**Comment by wenns** [comment]
Hi guwirth, thanks for the notes/hints. Lets look at them one by one

> 1. Simple and detailed mode: Which one is the default? 
Will mention

> 2. In case I use 'filename' tag, do I have to define also 'sonar.tests' property or is filename tag sufficient > in this case?
sonar.tests is needed in any case. Will make it more clear.

> 3. Using classname for filename is confusing. Maybe providing a stylesheet for translation would be 
> easier/more clear?
This is heritage, which is first left in place for the sake of backwards compatibility. Right know I change the code because I also dislike this 'feature'. As I already wrote somewhere...

> 4. Supported reports: Tag filename is missing in the example.
Will add and mark as optional via inline comment

> 5. Supported reports: Are nested testsuites allowed/supported?
Will mention

> 6. Which is the easiest possible configuration? Use sonar.sources=. and sonar.tests=. ? Is there a 
> problem reading sources as source & test?
You've already answered this: the source and test file sets should be disjoint.

I'll try to close the holes.

**Comment by wenns** [comment]
> @jmecosta But what is the file: for. Found it with and without in in SQ help files?

Looks like the protocol specifier. I do not use it.

**Comment by guwirth** [comment]
```
sonar.cxx.includeDirectories=C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/include, \\\
C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A/Include, \\\
../Packages/gtestmock.1.7.2/build/native/include, \\\
../Packages/gtestmock.1.7.2/build/native/include/googletest
```

@jmecosta Found this in your example. Wondering why there are 3 backslashes (```\\\```) at the end of line (and not 2 or 4 or ```\n\```)?

**Comment by guwirth** [comment]
> Simple and detailed mode: Which one is the default? 

@wenns: Would change default to simple mode, Its much easier to configure and easier to use for beginners.

**Comment by jmecosta** [comment]
on windows at least, for include directories
\\ -> gets only the first include definition
\n\ -> works the same way as \\\

for macros
\\\ -> does not work
\n\ -> works

seems \n\ can be used everywhere... i likely put \\\ for includes directories likely because was the first ones to get in the file way before the current release. i wanted the includes to be in different lines and the wiki only suggests comma separated

**Comment by wenns** [comment]
> @wenns: Would change default to simple mode, Its much easier to configure and easier to use for  
> beginners.

All right, I'll change the default. Jorge voted for this, too.

**Comment by guwirth** [comment]
documented:
https://github.com/wenns/sonar-cxx/wiki/Supported-configuration-properties
https://github.com/wenns/sonar-cxx/wiki/Get-test-execution-metrics
