### ISSUE TITLE
Make the unit test import compatible with Sonarqube's >= 4.2

### ISSUE THREAD

**Issue by wenns** [SonarOpenCommunity/sonar-cxx#313]
The plugin uses 'virtual' files (i.e. file objects in Sonar without according files on the FS) for storing test execution statistics when the unit test resource cannot be located in Sonar. Those virtual fallbacks do not work with newer Sonar's anymore (>=4.2, AFAIR). 

This causes serious issues in practice as it essentially drops every testcase which cannot be 'located', i.e. assigned to a test resource in Sonar.

The solution is:
Provide a new, more stable mode for importing the tests which doesnt care about the actual test resources in Sonar and just parses the reports, counts the numbers and stores them in context of the project itself. This is already sufficient for e.g. defining quality gates based on those metrics. Drilling down to details wont be possible, of course.

People who _need_ testcase details can help the plugin by injecting the filename attribute into the testsuite-flags, as ever.

**Comment by wenns** [comment]
@guwirth, @jmecosta: I made all suggested changes in code and dox.

**Comment by jmecosta** [comment]
ok. https://github.com/wenns/sonar-cxx/pull/352 should still be ok after this. no prob
