### ISSUE TITLE
New metric showing the quality of projects setup: 'parsing success ratio'

### ISSUE THREAD

**Issue by wenns** [SonarOpenCommunity/sonar-cxx#322]
Its difficult to get complex codebases to get parsed by the plugin completely. Usually a set of files fail to parse, especially If the project hasnt been setup accurately. The consequence is that theyre excluded from consideration, generating a certain error in the metric values. 

A new metric, something like 'parsing success ratio' (number of files which failed to parse / number of all files) could be used to track the 'quality of projects setup'.

First mentioned in #316

**Comment by guwirth** [comment]
@wenns Could you provide a solution by 2015-04-19 for this? If not we remove it from 0.9.3.

**Comment by guwirth** [comment]
no contributors, close this
