### ISSUE TITLE
CXX-DEPENDENCIES: Cyclic dependency violations

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#362]
How is this working? @Typz can you provide some docu please?

**Comment by jmecosta** [comment]
@guwirth is this enough?

http://www.sonarqube.org/fight-back-design-erosion-by-breaking-cycles-with-sonar/

**Comment by Bertk** [comment]
The support of DSM ist discontinued since SQ5.2 (see https://jira.sonarsource.com/browse/SONAR-6553).

**Comment by jmecosta** [comment]
@guwirth should we close as wont fix?
