### ISSUE TITLE
define SonarQube Java profile and quality gate for C++ Community plugin

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx#370]
I feel we shall use SonarQube also for the Java source code of the C++ Community plugin itself but I do not want to use the pre-defined Java profiles. We also should define a Quality Gate for pull requests.
What do you think?

**Comment by wenns** [comment]
Would love to do that. But how to do it in an automatic way?

**Comment by jmecosta** [comment]
Define a integration test to run in the current code base with a quality
get configured via the rest api?

**Comment by wenns** [comment]
Ok, lets think about that. On Travis, we get a completely naked node every time. The SQ instance is setup every time anew. To check the PR's against a Quality Gate, one could do: 

1 install java-plugin on this instance
2 install a build breaker plugin
3 configure a Quality Gate 
4 run the analysis via sonar-runner directly from the travis.yml file

1 and 2 can be probably done via e.g. curl and a restart afterwards. Or, alternatively, via wget'ing the jars directly into extensions/plugins & restart. 3 can be done via restoring of a backuped profile?. 
Or, maybe just replacing the database with a prepared one.
4 is justs running the command.

Hmm. We can give it a try, I suppose...

**Comment by jmecosta** [comment]
1. no need. its installed when you first start with a empty instance...
2. likely wget and place the plugin in the extensions (prevents the need to
restart the server)
3. i would go like this
https://github.com/jmecosta/sonar-cxx/blob/bdd/bullseye-and-custom-rules/integration-tests/features/test_create_rules_and_bullseye_import.feature
its a bit verbose but once we have it ready the maintenace is less then
having to recreate a db when testing in multiple sonar versions. same for
quality gate http://nemo.sonarqube.org/api_documentation#api/qualitygates

**Comment by jmecosta** [comment]
3. restore might be a better idea
http://nemo.sonarqube.org/api_documentation#api/profiles has we can also
have this in our ones instances

**Comment by wenns** [comment]
Having spent a couple of thoughts on this, Im not that enthusiastic anymore. First, one doesnt have history, and cannot monitor differential metrics such as "added TD". Second, you cannot deal with false positives. Third: fixing the issues for the PR authors will be difficult. I cannot tell people: 'dude, your PR has <some issues>; plz look at <somewhere> and fix the stuff'. It would involve setting up an instance which is configured exaclty as the Travis one etc.

To do cool stuff, we would need a permanently running SQ instance. Me thinks.

But it was an interesting thought experiment ;)

**Comment by jmecosta** [comment]
The issue is that I can not find such service currently
http://stackoverflow.com/questions/15715812/free-sonar-instanse-for-open-sourced-projects
unless we ask in nemo :) and besides even if there were you would not be
able to run against pull request likely. So the benefit of running in
Travis is there, perhaps the quality gate could be configured to no blocker
and critical and majors only. But of course the best would be a dedicated
instance

**Comment by Bertk** [comment]
This will be helpful http://www.sonarqube.org/github-pull-request-analysis-helps-fix-the-leak/

**Comment by jmecosta** [comment]
Yep we need to enable this. We have been using already for some time sonar
for stash plugin and it definitely its great addition

**Comment by guwirth** [comment]
no solution available
