### ISSUE TITLE
Report files outside of project base directory not read in

### ISSUE THREAD

**Issue by abbeyj** [SonarOpenCommunity/sonar-cxx#425]
I have an .xml report that's located outside of the project base directory.  I'm trying to reference this file via sonar.cxx.coverage.reportPath.

Using a relative path that includes ".." doesn't work.  It seems this is internally canonicalized to the absolute path and then it fails to be able to find anything when searching for this file under the project base dir.  Say that I'm running with a project base directory of /foo/bar and my report is /baz/report.xml.  If I specify sonar.cxx.coverage.reportPath=../../baz/report.xml then this is first turned into /foo/bar/../../baz/report.xml and then into /baz/report.xml which is the correct path.  However searching for this file fails since the search is forced to only consider files under the project base dir.

Using an absolute path doesn't work.  The leading slash is ignored and the path is treated as a relative path anyway.  So if I specify sonar.cxx.coverage.reportPath=/baz/report.xml, it doesn't look for /baz/report.xml but instead looks for /foo/bar/baz/report.xml which doesn't exist.

I'll attach an example project to demonstrate this.

**Comment by abbeyj** [comment]
Apparently I can't attach files so I've uploaded it here: http://files.stardrifter.org/pub/report_outside_base_dir.tar.gz

Use it like this:
$ tar xzvf report_outside_base_dir.tar.gz
$ cd report_outside_base_dir/base_dir
$ make

It will build the sample program, run it to generate coverage data, run gcovr to generate an xml report (one directory up from the base directory) and then run sonar-runner.  After this you can verify that coverage information was not read in as main.cpp will show as having no coverage.  The sonar-project.properties file included in the .tar.gz uses a relative path.  You can change it to an absolute path and the coverage report still will not be read in.

**Comment by guwirth** [comment]
Files outside of project root (where your configure file is) are not supported. 
See config: https://github.com/wenns/sonar-cxx/wiki/Supported-configuration-properties
and wiki: https://github.com/wenns/sonar-cxx/wiki/Path-and-path-separator-issues

**Comment by abbeyj** [comment]
That first link doesn't say anything about files having to be inside the project root.  Only that relative paths are required, and I've demonstrated above that relative paths don't work.

In any case, my report outputs are not located in the project root and I can't easily change that in the short term.  Consider this a Request For Enhancement instead of a bug if you must.

**Comment by wenns** [comment]
Thanks for reporting. This limitation (reports should be underneath projects root) is kind of technical one, AFAIR there were issues with the ant routines we use for finding the reports. Conceptually, nothing really speaks for having the actual report outside, as long the content follows the requirements. I'll look at this.

**Comment by jfallot** [comment]
Allowing absolute report paths could be a way to help here (see issue #344)...
I am currently still working with my sonar-cxx fork where I implemented that small change

**Comment by guwirth** [comment]
Maybe you can provide a pull request to see your solution.

**Comment by jmecosta** [comment]
#683

**Comment by guwirth** [comment]
Should be solved with #683
