### ISSUE TITLE
Custom SquidCheck

### ISSUE THREAD

**Issue by schiean** [SonarOpenCommunity/sonar-cxx#527]
Hi,

At our company we have defined some custom checks in java classes (extends SquidCheck<Grammar>). For now I use a locally forked cxx. However we also implement the same checks for Java. And the sonar-java plugin allowed us to separate those checks in a separate plugin (so we don't have to use a local fork). I would prefer to just install default sonar-java and default sonar-cxx in combination with a company-checks plugin which contains our checks for cxx and java.

I created a class that implements RulesDefinition and does the following:
  NewRepository repo = context.createRepository(REPOSITORY_KEY, KEY);
  repo.setName(REPOSITORY_NAME);
 RulesDefinitionAnnotationLoader annotationLoader = new RulesDefinitionAnnotationLoader();
 annotationLoader.load(repo, checks);
 repo.done();

This seems to work for Cxx rules to get them in the sonar-rule repository. Also they are activated in my profile, yet they don't seem to be included by CXX-squid when sonar-runner is being run.
(The rule does work in a local-cxx-checks fork..)

How can i provide my own rules to the CxxSquidSensor ?

Kind Regards,
Arjen

**Comment by guwirth** [comment]
See #467 and #521. 

Which additional checks do you have? Can you share them?

**Comment by schiean** [comment]
>> Which additional checks do you have? Can you share them?

Most of them are really specific to our company coding conventions, they are adjusted versions of function complexity check and function size check. The only one I think that might be of interest, is one that 'counts the number of parameters/arguments to a function and above a certain threshold triggers an issue'. If you want I could provide that check to this repo.

As for my question, I don't really understand the relation to the tickets you linked. But I am pretty new to Cxx so maybe it should have been obvious, however could you explain a little more ?

Below is an example of one of my rules/checks. The system.out is there for debug purpose. It does get printed when it is packaged in cxx-checks, but not when it is packaged in my company-plugin.

	@Rule(key = "...", name = "..", description = "..", tags = { ".." })
	@NoSqale
        @ActivatedByDefault
	public class ParamCountCheck extends SquidCheck<Grammar> {

		@Override
		public void init() {
			subscribeTo(CxxGrammarImpl.functionDefinition);
		}

		@Override
		public void leaveNode(AstNode node) {
			int nrOfParams = count(node);
			System.out.println("Debug, "+printName(node)+" has params:"+nrOfParams);
			// create issues
		}
}

**Comment by guwirth** [comment]
I think you can use an XML file and the XmlLoader from the links or the way you did it above. For second one you need the SQ API 4.5 or later. You should check our POM files for the packages.

Probably it is better to ask such questions in the SQ forum.

**Comment by schiean** [comment]
I think I have found the problem; why my JavaChecks work, but not my CxxChecks. For Java, the Java Sensor has something called a CheckRegistrar which is used to runtime provide custom checks to the Sensor for batch analysis. However for Cxx, the CxxSquidSensor has a fixed set of checks (CheckList.getChecks()). And there does not seem to be a way for me to register my own checks from within my own plugin to the CxxSquidSensor.

So it seems custom Cxx checks in Java are not supported from other jars. Cxx custom checks in XML are supported but that's not what I'm interested in. Adding support for custom Cxx check in Java might be hard because of classloader stuff..

Is this correct ? Or am I still missing something.

**Comment by guwirth** [comment]
> the Java Sensor has something called a CheckRegistrar

Don't know this. Maybe you can provide a link to code/example. Maybe we can also add it.

**Comment by schiean** [comment]
There is an example project:
https://github.com/SonarSource/sonar-examples/tree/master/plugins/java-custom-rules

And this shows that besides registering the rule to the NewRepository repo =   
context.createRepository(REPOSITORY_KEY, KEY);

They also register it to a RegistrarContext.

https://github.com/SonarSource/sonar-examples/blob/master/plugins/java-custom-rules/src/main/java/org/sonar/samples/java/MyJavaFileCheckRegistrar.java
Which then provides it to the sonar-java-plugin.

I tried to access CxxSquidSensor (with small adjustment to inject my own checks) from my own plugin, to realize something similar, but it is not on its classpath at runtime, unless I package it with my plugin, but that would not be the right way of course. So I presume the RegistrarContext solves this problem of interaction between plugins??

**Comment by guwirth** [comment]
They are always only talking about Java checks: https://github.com/SonarSource/sonar-java/blob/master/java-squid/src/main/java/org/sonar/plugins/java/api/CheckRegistrar.java. 
Wondering how a check could work for two languages because they have different grammars?

**Comment by guwirth** [comment]
> And there does not seem to be a way for me to register my own checks from within my own plugin to the CxxSquidSensor.

Or do you have own cxx rules?

**Comment by schiean** [comment]
We indeed use copies of the checks, one for Java , one for C++. Although the code is relatively comparable, the Grammar implementations aren't :-)

And the CheckRegistrar seems to be Java only at this moment. But I hoped someone here knew a way to do something similar for cxx; to supply a separately packaged check to the CxxSquidSensor.

**Comment by guwirth** [comment]
* This seems to be the base class https://github.com/SonarSource/sonar-java/blob/master/java-squid/src/main/java/org/sonar/plugins/java/api/CheckRegistrar.java but it is marked as @Beta. The thing I don't understand is this ```Iterable<Class<? extends JavaCheck```. Do you know what this JavaCheck class is?
* In the sample they derive in the own plugin from the CheckRegistrar and add their own checks there: https://github.com/SonarSource/sonar-examples/blob/master/plugins/java-custom-rules/src/main/java/org/sonar/samples/java/MyJavaFileCheckRegistrar.java. ```register``` method is called during an analysis to get the classes to use to instantiate checks. There is also the ```import org.sonar.plugins.java.api.CheckRegistrar;``` and ```import org.sonar.plugins.java.api.JavaCheck;```
* maybe we also need something like ```package org.sonar.plugins.java.api;``` => ```package org.sonar.plugins.cxx.api;```? In best case you can copy & paste the files from Java plugin and rename Java with Cxx.

Seems that at the moment only you needs this? So maybe it is the easiest you try to extend our plugin with the CheckRegistrar and we will merge it then.

**Comment by schiean** [comment]
A custom check in Java implements quite some interfaces:
- JavaFileScanner -> JavaCheck
- TreeVisitor-> JavaCheck

JavaCheck is a marker interface for org.sonar.squidbridge.api.CodeVisitor
https://github.com/SonarSource/sonar-java/blob/master/java-squid/src/main/java/org/sonar/plugins/java/api/JavaCheck.java

A Cxx Check is a SquidCheck which is a CodeCheck which is a CodeVisitor

So there is a very high level common marker interface.

I'm not quite sure a plain copy paste of the Registrar would solve the problem, as I think the CxxSquidSensor also needs to somehow get the data from that registrar.

**Comment by felipebz** [comment]
I've added support to custom checks in my plugin (https://github.com/felipebz/sonar-plsql) based on the sonar-javascript plugin and it wasn't too hard.

To allow custom checks we have to:
- move all public API to the org.sonar.plugins.cxx.api package (see http://docs.sonarqube.org/display/DEV/Plugin+Class+Loader and https://github.com/SonarSource/sonarqube/blob/0ae5ddd039e29094eee818370fe34810d3a225f7/sonar-core/src/main/java/org/sonar/core/platform/PluginLoader.java#L96)
- provide a way for custom plugins to register checks
- handle these custom checks in CxxSquidSensor

I will send a pull request with the changes, so it will be easier to discuss.

**Comment by schiean** [comment]
Hi,

I finally had the time to check it out. I used the provided example project as reference for separating my rules from my local cxx-fork to a new custom-rules-project.
And it seems to work well !!
Thank you for implementing this feature !!

Regards,
Arjen
