### ISSUE TITLE
Integrate Clang-Tidy

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#548]
clang-tidy is a clang-based C++ linter tool. Its purpose is to provide an extensible framework for diagnosing and fixing typical programming errors, like style violations, interface misuse, or bugs that can be deduced via static analysis. clang-tidy is modular and provides a convenient interface for writing new checks (http://clang.llvm.org/extra/clang-tidy.html)

Integrate this tool like Cppcheck.

**Comment by guwirth** [comment]
no contributors, close this

**Comment by jimmyharris** [comment]
Was this effectively a request for someone to contribute this as an integration?

**Comment by jmecosta** [comment]
Are you interested? ;)

**Comment by jimmyharris** [comment]
I am interested in having the feature. But It may be a while before I can get resources to implement it. Also I am by no means a Java developer.

**Comment by jmecosta** [comment]
The major work that needs doing is raising the rule set for clang. The
approach is to reuse the reports, so if you have the rules I can create the
sensor

**Comment by jimmyharris** [comment]
I think it would basically be a copy paste job from the clang sensor since it uses the same error formatting libraries. We would just have to copy the rule documentation into the appropriate format.

**Comment by bjd** [comment]
I did some work for clang-tidy integration a couple of months ago. It seemed to work ok for my use case but I never got round to really finish it. It may still be useful though: https://github.com/bjd/sonar-cxx/commits/clang-tidy

**Comment by jmecosta** [comment]
Wow nice that's already a very good starting point. If you don't mind I can
try integrate it

**Comment by bjd** [comment]
Sure, go ahead. It is based on older revision of sonarcxx and I did not keep track of recent changes, but hopefully it will still integrate without too much trouble.

**Comment by jmecosta** [comment]
@guwirth i will give a go on integrating this

**Comment by jmecosta** [comment]
done in #1076

**Comment by guwirth** [comment]
@jimmyharris @jmecosta @bjd @wichtounet @Bertk merged to main. You can give it a try...

**Comment by jmecosta** [comment]
@guwirth will once i get llvm/clang/clang-tidy compiling in windows. seeems a impossible task

**Comment by bjd** [comment]
I ran a quick test, unfortunately it runs into an exception:
```
ERROR: Failed to parse clang-tidy report: {}
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.charAt(String.java:646) ~[na:1.8.0_45]
	at org.sonar.plugins.cxx.clangtidy.CxxClangTidySensor.processReport(CxxClangTidySensor.java:75) ~[sonar-cxx-plugin-0.9.8-SNAPSHOT.jar:na]
	at org.sonar.plugins.cxx.utils.CxxReportSensor.execute(CxxReportSensor.java:83) [sonar-cxx-plugin-0.9.8-SNAPSHOT.jar:na]
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53) [sonar-scanner-engine-shaded-6.0.jar:na]
...
```
The report file looks like this:
```
/home/bdijkstra/dev/test/include/DatamodelHandler.h:1:1: warning: header is missing header guard [llvm-header-guard]
^
```
The issue is that it sees the line with '^' as a relative path and attempts to check for drive letter separator ':' in second position.

**Comment by wichtounet** [comment]
@guwirth I'll try to test it in the coming day, but I very use clang-tidy anymore. Maybe I don't know how to use it, but it is way too slow. It is generally slower than the equivalent compilation and since it uses only one thread, in the end it is way slower than the compilation. For the simplest of my libraries, it takes 1 minute and a half.

**Comment by bjd** [comment]
The exception can be easily fixed by adding a length check as very short lines can't be a valid issue report anyway:
```
diff --git a/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/clangtidy/CxxClangTidySensor.java b/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/clangtidy/CxxClangTidySensor.java
index aedaff4..0026cf4 100644
--- a/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/clangtidy/CxxClangTidySensor.java
+++ b/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/clangtidy/CxxClangTidySensor.java
@@ -72,6 +72,8 @@ public class CxxClangTidySensor extends CxxReportSensor {
 
       while (scanner.hasNextLine()) {
         String line = scanner.nextLine().trim();
+       if (line.length() < 2)
+         continue;
         if (line.startsWith("/") || line.charAt(1) != ':') {
           // does not start with drive letter, but can be relative path
           CreateIssueInLineNoDriveLetter(context, line, p);
```

**Comment by jmecosta** [comment]
@bjd i will push a fix asap, weird the unit tests dont crash

**Comment by jmecosta** [comment]
fixed here #1088

**Comment by wichtounet** [comment]
I just tried it. Everything seems to work fine :+1: 

Anyone knows how to fix problems with with clang-tidy and the compilation database when the paths are different from one computer to the other ?

**Comment by jmecosta** [comment]
i havent played with that, but cant it provide relative paths instead of absolute paths?

**Comment by wichtounet** [comment]
@jmecosta I'm using Bear to generate the compilation database and it does not seem to have any option for relative paths. I also tried cleaning the file myself to make it relative, but then it didn't work on the other computer. Once the version of sonar-cxx is ready, I'll simply create a script to replace the path from one to another.

**Comment by jmecosta** [comment]
@wichtounet yep thats a way, the way i handle with all this. Because its not only the compile db, also the coverage information and issues location has the same problem, is to run the analysis always in same folder in the build farm. So the checkout folders are always in e:\src

**Comment by xstarcto** [comment]
@wenns, @wichtounet , would you please share some simple steps to use clang-tidy with sonar-cxx ?
i can not make it pass.  is there some steps for references ?

**Comment by xstarcto** [comment]
and may i know when the 0.9.8 release version is officially out
