### ISSUE TITLE
Multi compiler warning support

### ISSUE THREAD

**Issue by KevinArturia** [SonarOpenCommunity/sonar-cxx#578]
I would like to be able to get the warning from both MS Visual Studio and clang in my project.
I don't think this is currently possible.
Is it?

**Comment by jmecosta** [comment]
Nop, but clang is in the pipeline to be implemented at some point

**Comment by KevinArturia** [comment]
I am currently using clang and it runs not so bad with gcc regex (apart some unrecognized warnings) but my question was more to be able to have the warning of both Mac and Windows in the same project.

**Comment by jmecosta** [comment]
It should support multiple reports given that they are produced before hand

**Comment by guwirth** [comment]
@KevinArturia If you are using already clang, do you know how to create a list with all supported warnings and errors? With other tools there is a command line option for this.

**Comment by jmecosta** [comment]
Or maybe not, not completely sure that you can specify both visual studio
and gcc at same time. But don't see why cant this be implemented also if not

**Comment by KevinArturia** [comment]
@guwirth: no I don't know. After googling a bit I found [this github](https://github.com/macmade/SeriousCode) which you might already know.

**Comment by KevinArturia** [comment]
Any feedback concerning my original question?

Is it something that could be implemented in the future or should I just use 2 different projects?

**Comment by guwirth** [comment]
Seems from other to be less need currently?

**Comment by guwirth** [comment]
no contributors, close this
