### ISSUE TITLE
C++ grammar refactoring

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#593]
Align grammar with latest C++ standard.

e.g. @Bertk By the way, the sequence of the statements within *postfixExpression* is not correct and the definition for ```postfix-expression [ braced-init-list ]```is missing. New parser errors occurred after moving *primary-expression* to the binginning of the rule and I stopped this activity.
Excerpt from N4527 Annex A Grammar summary:
```
postfix-expression:
primary-expression
postfix-expression [ expression ]
postfix-expression [ braced-init-list ]
postfix-expression ( expression-listopt)
simple-type-specifier ( expression-listopt)
typename-specifier ( expression-listopt)
simple-type-specifier braced-init-list
typename-specifier braced-init-list
postfix-expression . templateopt id-expression
postfix-expression -> templateopt id-expression
postfix-expression . pseudo-destructor-name
postfix-expression -> pseudo-destructor-name
postfix-expression ++
postfix-expression --
dynamic_cast < type-id > ( expression )
static_cast < type-id > ( expression )
reinterpret_cast < type-id > ( expression )
const_cast < type-id > ( expression )
typeid ( expression )
typeid ( type-id )
```

**Comment by guwirth** [comment]
From @Bertk: By the way, the C++ standard (n4527) defines

class-name:
          identifier
          simple-template-id
but we use :

      b.firstOf(
        simpleTemplateId,
        b.sequence(b.optional("::"), IDENTIFIER)
        )
      );

**Comment by guwirth** [comment]
There are some lines which shall be checked as well - I feel the b.optional("::") should be removed:

    Line 960:     b.rule(usingDirective).is(b.optional(attributeSpecifier), CxxKeyword.USING, CxxKeyword.NAMESPACE, b.optional("::"), b.optional(nestedNameSpecifier), namespaceName, ";");
    Line 1461:             b.sequence(b.optional("::"), b.optional(nestedNameSpecifier), typeName, b.optional("^")),
    Line 1462:             b.sequence(b.optional("::"), b.optional(nestedNameSpecifier), CxxKeyword.TEMPLATE, templateId, "^")
    Line 1519:         b.sequence(b.optional("::"), b.optional(nestedNameSpecifier), innerSimpleTemplateId),
    Line 1520:         b.sequence(b.optional("::"), b.optional(nestedNameSpecifier), CxxKeyword.TEMPLATE, innerSimpleTemplateId),

**Comment by guwirth** [comment]
Some of the issues are fixed/improved with #743. Bigger refactoring is difficult without having better parser error information #476.

**Comment by guwirth** [comment]
@Bertk there are also some issues from you solved. Maybe you can also test it?

**Comment by Bertk** [comment]
I did a small test and it is OK. Did anybody check the performance impact? I got the impression the analysis takes some minutes more but this might also related to other modifications.
I will do some more tests in the evening.

**Comment by jmecosta** [comment]
for me now its also ok,  did not see any impact in this small project i run

![image](https://cloud.githubusercontent.com/assets/1041352/13379893/b5b33e16-de3b-11e5-95e6-93941e9899bf.png)
