### ISSUE TITLE
variadic macros - no argument for ellipsis creates preprocessor parser error

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx#605]
The sample on MSDN for variadic macros will create a parser error.
https://msdn.microsoft.com/en-us/library/ms177415.aspx

excerpt from sample to reproduce the Parser error:
```
#include <stdio.h>
#define EMPTY
#define MACRO(s, ...) printf(s, __VA_ARGS__)

int main() {
    MACRO("hello, world\n");

    MACRO("error\n", EMPTY); // would cause error C2059, except VC++ 
                             // suppresses the trailing comma

}
```

**Comment by guwirth** [comment]
Expecation: The Visual C++ implementation will suppress a trailing comma if no arguments are passed to the ellipsis.
