### ISSUE TITLE
CxxXunitSensor in a multimodule project

### ISSUE THREAD

**Issue by Zetten** [SonarOpenCommunity/sonar-cxx#612]
We've realised (after not paying attention for a while) that we're not getting test execution reports for our C++ tests. It's not a vital feature of our SQ usage, but it used to work and I'm trying to narrow down why it doesn't now.

I'm not sure of the intent behind f2cedf713c2b70d511941f6665fd66b95aa1d9e8 and the general idea behind overriding `shouldExecuteOnProject` in the [CxxXunitSensor](https://github.com/wenns/sonar-cxx/blob/531e805204836f0fe955fcac14390b875c35db4e/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/xunit/CxxXunitSensor.java#L118). The commit message from @jmecosta introducing the override just states "prevent simple mode from running in all modules" and I can't figure out why that's desirable.

As it stands, we can't get simple test execution reports in our multi-module project by any means. I haven't yet investigated getting detailed reports but this still seems like a regression. We're using a proper Maven project structure, so I guess a Sonar-Runner approach might treat modules differently and that's the source of the discrepancy. It would be nice to restore the simple reports for our use case.

Simply removing the overridden `shouldExecuteOnProject` method seems to result in the desired behaviour for our project, but I wouldn't submit a PR for this without fully understanding the original approach.

**Comment by jmecosta** [comment]
I think some commit has been made later to fix some kind of corner case,
however the original idea was to support the visual studio bootstrapper
that creates modules. Indeed I don't think we have a maven test for this,
but feel free to create a PR to handle your use case. If it does not brake
the existent integration test it should be fine to merge.

The flag you mention I think it's to prevent every module to call all
sensors every time.

**Comment by Zetten** [comment]
After removing `shouldExecuteOnProject` (so it uses the default, which just checks for the existence of CXX files) the ITs still seem to run fine. The test reports for both googletest_project and boosttest_project are stored successfully.

I'll do a few more internal tests with a few other C/C++ projects, including a multi-module project using sonar-runner, and see if there's anything else that comes up. If it's clean I'll push for a PR.

**Comment by Zetten** [comment]
Ok, everything seemed fine after some additional tests, so I created PR #617.

Please do check it out and try it locally though; I only tested in SQ 4.5.5 and with a few projects, so I'd be interested to see if it acts differently in any other configurations.

**Comment by guwirth** [comment]
Integration test for PR is failing.

**Comment by jmecosta** [comment]
And it's failing on the multi module test, so you need it make sure that
test is passing

**Comment by Bertk** [comment]
Beside the fix for multi module project support the CxxXunitSensor should be improved to handle test results from multiple report files e.g. cppunit, gtest for a component as well.
* refactor shouldExecuteOnProject (b4e7893) 
* add a BatchExtension similar to UnitTestResultsAggregator 
(see https://github.com/SonarCommunity/sonar-dotnet-tests-library/blob/master/src/main/java/org/sonar/plugins/dotnet/tests/UnitTestResultsAggregator.java)
* enhance path detection for multi module projects (getReports)

**Comment by guwirth** [comment]
please try again with 0.9.5:
* improved multi module support => #695
* allow to specify absolute paths for reports. to support msbuild runner #683
