### ISSUE TITLE
Use java.nio.file.path instead of org.apache.commons.io.FilenameUtils

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#621]
@Bertk: Yes, we should use more Java 7 methods and replace this Strings class with Path class. I also feel we should remove dependency to org.apache.commons.io.FilenameUtils in CxxReportSensor.java and use java.nio.file.path.
https://docs.oracle.com/javase/tutorial/essential/io/pathOps.html
https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html

**Comment by guwirth** [comment]
@Bertk: What is the advantage?

**Comment by Bertk** [comment]
Currently we use strings for paths and file names. Java 7 has a rich feature set for file&path and especially the relativize method (http://docs.oracle.com/javase/7/docs/api/java/nio/file/Path.html#relativize(java.nio.file.Path)  which is helpful for the sensors. I expect some cleaner code and we should use nio methods or SQ InputFile in org.sonar.plugins.cxx.utils.

I also want to investigate a problem with CppCheck sensor which did not create issues for sources in sub-folders.

**Comment by jmecosta** [comment]
#683 should use nio lib

**Comment by guwirth** [comment]
@bertk why did you close this? I still found some places where `org.apache.commons.io.FileUtils` is in use?

https://github.com/SonarOpenCommunity/sonar-cxx/search?utf8=%E2%9C%93&q=org.apache.commons.io.FileUtils&type=
