### ISSUE TITLE
The report processing should be more stable / error tolerant

### ISSUE THREAD

**Issue by wenns** [SonarOpenCommunity/sonar-cxx#63]
The analysis terminates in an uncontrolled way. A better solution is to log a warning and continue.
Samples:
Exception in thread "main" org.sonar.batch.bootstrapper.BootstrapException: org.sonar.api.utils.SonarException: Cannot feed the data into sonar, details: 'com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog
at [row,col
{unknown-source}]: [1,0]'
at org.sonar.runner.Runner.delegateExecution(Runner.java:210)
at org.sonar.runner.Runner.execute(Runner.java:84)
at org.sonar.runner.Main.main(Main.java:67)
Caused by: org.sonar.api.utils.SonarException: Cannot feed the data into sonar, details: 'com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog
at [row,col {unknown-source}

**Comment by amai2012** [comment]
I just see this error with 0.9.5.
Was this ticket supposed to deal with it? Or ist the hint to use -e/-X the best available option?

```
0:11:35[ 51m12.32s]       [java] 00:11:33.528 INFO  - Parsing 'other' format
00:11:35[ 51m12.32s]       [java] INFO: ------------------------------------------------------------------------
00:11:35[ 51m12.33s]       [java] INFO: EXECUTION FAILURE
00:11:35[ 51m12.33s]       [java] INFO: ------------------------------------------------------------------------
00:11:35[ 51m12.33s]       [java] Total time: 1:10.849s
00:11:35[ 51m12.55s]       [java] Final Memory: 29M/454M
00:11:35[ 51m12.55s]       [java] INFO: ------------------------------------------------------------------------
00:11:35[ 51m12.55s]       [java] ERROR: Error during Sonar runner execution
00:11:35[ 51m12.55s]       [java] ERROR: Unable to execute Sonar
00:11:35[ 51m12.55s]       [java] ERROR: Caused by: Cannot feed the data into sonar, details: 'com.ctc.wstx.exc.WstxEOFException: Unexpected EOF in prolog
00:11:35[ 51m12.55s]       [java]  at [row,col {unknown-source}]: [1,38]'
00:11:35[ 51m12.55s]       [java] ERROR: Caused by: Unexpected EOF in prolog
00:11:35[ 51m12.55s]       [java]  at [row,col {unknown-source}]: [1,38]
00:11:35[ 51m12.55s]       [java] ERROR: 
00:11:35[ 51m12.55s]       [java] ERROR: To see the full stack trace of the errors, re-run SonarQube Runner with the -e switch.
00:11:35[ 51m12.55s]       [java] ERROR: Re-run SonarQube Runner using the -X switch to enable full debug logging.
```

**Comment by jmecosta** [comment]
Is this random or is the file you are trying to parse corrupted?  If that's
the case its good that you get exceptions like this

**Comment by guwirth** [comment]
Please have a look here: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

Other possibility could also be wrong encoding of file?

**Comment by amai2012** [comment]
Thanks.
I could not verify the file immediately, it's a temporary artefact in an automatic buildjob and deleted afterwards by default. I've added the debug switches and tonight the job was successful...
