### ISSUE TITLE
travis needs to be hooked up again to new location

### ISSUE THREAD

**Issue by jmecosta** [SonarOpenCommunity/sonar-cxx#663]
@guwirth seems the travis build is not running at the moment. only the appveyour buid, can you setup yourself an new account?

**Comment by guwirth** [comment]
Working for PR again. For main branch still open.

**Comment by guwirth** [comment]
After update of link icon is working too:
[![Build Status](https://travis-ci.org/SonarOpenCommunity/sonar-cxx.svg?branch=master)](https://travis-ci.org/SonarOpenCommunity/sonar-cxx)
