### ISSUE TITLE
Replace cppncss with another tool (CCCC, CLOC)

### ISSUE THREAD

**Issue by wenns** [SonarOpenCommunity/sonar-cxx#67]
The cppncss tool analysis most of the times fails because the CPP file parsing is skipped if a MACRO or DEFINE is unknown. The tool does not use the definitions from include files and the high effort to define everything (ON_NOTIFY, END_MESSAGE_MAP, AFX_MSG_MAP, WINAPI, HRESULT, ...) makes this analysis problematic. I already disabled this part off CXX Plug-In.
Please use different tool which can handle windows sources or creates results without high effort customizing.
Check:
http://cccc.sourceforge.net/
http://cloc.sourceforge.net/
http://www.dwheeler.com/sloccount/

**Comment by Hacaca** [comment]
So the cppncss was not replaced, but it is just not supported anymore? Is there any way how to load CCCC xml with sonar-cxx into sonar project database?
