### ISSUE TITLE
Update Center links are incorrect

### ISSUE THREAD

**Issue by patrickjmccarty** [SonarOpenCommunity/sonar-cxx#670]
Bug in plugin version 0.9.4:
Within SonarQube, going to System > Update Center > and clicking to expand C++ (Community) shows a Homepage link and Issue Tracker link.

The Homepage link is incorrect; it currently goes to http://docs.codehaus.org/display/SONAR/CXX+PLUGIN which dumps me at SQ's generic Documentation page.

The Issue Tracker link works, but it ends up getting redirected to a different location, so it should probably be updated as well so it doesn't rely on the redirect?
Link is: https://github.com/wenns/sonar-cxx/issues?state=open
Ends up at: https://github.com/SonarOpenCommunity/sonar-cxx/issues?q=is%3Aopen

**Comment by guwirth** [comment]
This plugin us not supported by the update center. For SonarSource this plugin is a competitor to their own commercial C++ plugin and therefore excluded.

**Comment by jmecosta** [comment]
I think this was because of the move to an organization. Once you install
the plugin it will be in update center. We need to fix the poms to point to
the correct place now.

**Comment by jmecosta** [comment]
You can assign to me, I will check

**Comment by patrickjmccarty** [comment]
@jmecosta Regarding the homepage link, searching the source for CXX+Plugin, I found it two files:
[sonar-cxx-plugin\pom.xml](https://github.com/SonarOpenCommunity/sonar-cxx/blob/a1b1d8797dbfb9d00701d2b357fd4d4b7e59101c/sonar-cxx-plugin/pom.xml#L17)
[sonar-cxx-plugin\src\samples\SampleProject2\Readme](https://github.com/SonarOpenCommunity/sonar-cxx/blob/a1b1d8797dbfb9d00701d2b357fd4d4b7e59101c/sonar-cxx-plugin/src/samples/SampleProject2/Readme#L29)

Also found a number of instances of github.com/wenns that could be updated since you were replacing those with github.com/SonarOpenCommunity.

**Comment by jmecosta** [comment]
right, ive updated all those now, and in my test server everything works properly.... thanks

**Comment by guwirth** [comment]
@jmecosta can we close this?
