### ISSUE TITLE
sonarqube is not starting after oracle has been configured

### ISSUE THREAD

**Issue by dinesh25** [SonarOpenCommunity/sonar-cxx#671]
Hi,
configs:
RHEL 7,
sonarqube 5.1.1
java version "1.7.0_85"
ojdbc6.jar - loaded in /extensions/jdbc-driver/oracle/
Oracle Database 11g Enterprise Edition Release 11.2.0.2.0 - 64bit Production<created sonar/sonar in DB>

After I did some settings to sonar.properties, the sonarqube is not running. 

my sonar.properties file: <settings that i have changed alone for oracle support>

sonar.jdbc.url=jdbc:oracle:thin:@<myip>:<port>/ABCDB
sonar.jdbc.driverClassName:oracle.jdbc.driver.OracleDriver
sonar.jdbc.schema:ABCSCH
sonar.jdbc.validationQuery:select 1 from dual

i have created table space ABCSCH under ABCDB. 
After the above edit, i restarted ./sonar.sh restart. 
if i do ./sonar.sh status,
i see the sonar is running, 

but if i type the ipAdd:port in the browser, the window says "Connection refused". 
Note: it was working good until i configured oracle details. 

my sonar.log entries:
  1 TERM trapped.  Shutting down.
  2 2015.11.04 18:33:14 INFO  app[o.s.p.m.TerminatorThread] Process[search] is stopping
  3 2015.11.04 18:33:15 INFO   es[o.s.p.StopWatcher]  Stopping process
  4 2015.11.04 18:33:15 INFO   es[o.elasticsearch.node]  [sonar-1446641989029] stopping ...
  5 2015.11.04 18:33:15 INFO   es[o.elasticsearch.node]  [sonar-1446641989029] stopped
  6 2015.11.04 18:33:15 INFO   es[o.elasticsearch.node]  [sonar-1446641989029] closing ...
  7 2015.11.04 18:33:25 INFO   es[o.elasticsearch.node]  [sonar-1446641989029] closed
  8 2015.11.04 18:33:25 WARN   es[o.s.p.ProcessEntryPoint]  Fail to start search
  9 org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution (shutting down) on org.elastics    earch.action.support.master.TransportMasterNodeOperationAction$3@2dbd9301
 10         at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:62) ~[elasticsearc    h-1.4.4.jar:na]
 11         at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821) ~[na:1.7.0_85]
 12         at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372) ~[na:1.7.0_85]
 13         at org.elasticsearch.action.support.master.TransportMasterNodeOperationAction.innerExecute(TransportMasterNodeOpe    rationAction.java:130) ~[elasticsearch-1.4.4.jar:na]
 14         at org.elasticsearch.action.support.master.TransportMasterNodeOperationAction.doExecute(TransportMasterNodeOperat    ionAction.java:88) ~[elasticsearch-1.4.4.jar:na]
 15         at org.elasticsearch.action.support.master.TransportMasterNodeOperationAction.doExecute(TransportMasterNodeOperat    ionAction.java:43) ~[elasticsearch-1.4.4.jar:na]
 16         at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:75) ~[elasticsearch-1.4.4.jar:na    ]
 17         at org.elasticsearch.client.node.NodeClusterAdminClient.execute(NodeClusterAdminClient.java:77) ~[elasticsearch-1    .4.4.jar:na]
 18         at org.elasticsearch.client.support.AbstractClusterAdminClient.health(AbstractClusterAdminClient.java:127) ~[elas    ticsearch-1.4.4.jar:na]
 19         at org.elasticsearch.action.admin.cluster.health.ClusterHealthRequestBuilder.doExecute(ClusterHealthRequestBuilde    r.java:92) ~[elasticsearch-1.4.4.jar:na]
 20         at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91) ~[elasticsearch-1.4.4.jar:    na]
 21         at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65) ~[elasticsearch-1.4.4.jar:    na]
 22         at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:73) ~[elasticsearch-1.4.4.jar:na]
 23         at org.sonar.search.SearchServer.isReady(SearchServer.java:51) [sonar-search-5.1.1.jar:na]
 24         at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:80) ~[sonar-process-5.1.1.jar:na]
 25         at org.sonar.search.SearchServer.main(SearchServer.java:80) [sonar-search-5.1.1.jar:na]
 26 2015.11.04 18:33:25 INFO  app[o.s.p.m.TerminatorThread] Process[search] is stopped
 27 <-- Wrapper Stopped
 28 --> Wrapper Started as Daemon
 29 Launching a JVM...
 30 Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
 31   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
 32
 33 2015.11.04 18:33:27 INFO  app[o.s.p.m.JavaProcessLauncher] Launch process[search]: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.    85-2.6.1.2.el7_1.x86_64/jre/bin/java -Djava.awt.headless=true -Xmx1G -Xms256m -Xss256k -Djava.net.preferIPv4Stack=true -X    X:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+Heap    DumpOnOutOfMemoryError -Djava.io.tmpdir=/opt/sonarqube-5.1.1/temp -cp ./lib/common/*:./lib/search/* org.sonar.search.Sear    chServer /tmp/sq-process6421816216678733392properties
 34 2015.11.04 18:33:27 INFO   es[o.s.p.ProcessEntryPoint]  Starting search
 35 2015.11.04 18:33:27 INFO   es[o.s.s.SearchServer]  Starting Elasticsearch[sonarqube] on port 9001
 36 2015.11.04 18:33:27 INFO   es[o.elasticsearch.node]  [sonar-1446642207003] version[1.4.4], pid[2808], build[c88f77f/2015-    02-19T13:05:36Z]
 37 2015.11.04 18:33:27 INFO   es[o.elasticsearch.node]  [sonar-1446642207003] initializing ...
 38 2015.11.04 18:33:27 INFO   es[o.e.plugins]  [sonar-1446642207003] loaded [], sites []
 39 2015.11.04 18:33:29 INFO   es[o.elasticsearch.node]  [sonar-1446642207003] initialized
 40 2015.11.04 18:33:29 INFO   es[o.elasticsearch.node]  [sonar-1446642207003] starting ...
 41 2015.11.04 18:33:30 INFO   es[o.e.transport]  [sonar-1446642207003] bound_address {inet[/0.0.0.0:9001]}, publish_address     {inet[/ip:9001]}
 42 2015.11.04 18:33:30 INFO   es[o.e.discovery]  [sonar-1446642207003] sonarqube/E8QMlCCYSFKY_0O2y41GWg
 43 2015.11.04 18:33:33 INFO   es[o.e.cluster.service]  [sonar-1446642207003] new_master [sonar-1446642207003][E8QMlCCYSFKY_0    O2y41GWg][bl4ul199][inet[/ip:9001]]{rack_id=sonar-1446642207003}, reason: zen-disco-join (elected_as_master)
 44 2015.11.04 18:33:33 INFO   es[o.elasticsearch.node]  [sonar-1446642207003] started
 45 2015.11.04 18:33:33 INFO   es[o.e.gateway]  [sonar-1446642207003] recovered [6] indices into cluster_state

please guide me in setting up the oracle db support for sonar.

Thank you:)

**Comment by dinesh25** [comment]
missed it,
-bash-4.2$ java -version
java version "1.7.0_85"
OpenJDK Runtime Environment (rhel-2.6.1.2.el7_1-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)

this is my java version.

Thanks:)

**Comment by jmecosta** [comment]
can you please explain why do you think we can support this cases? this project is for questions related with sonar-cxx plugin. 

Head to gougle groups https://groups.google.com/forum/#!forum/sonarqube and post you question there. 

thank you

**Comment by dinesh25** [comment]
My apologies for writing in a wrong forum. Thankyou for redirecting me to the right one,

Thanks:)

**Comment by jmecosta** [comment]
No problem
