### ISSUE TITLE
The GNU __attribute__ mechanism causes failure to parse

### ISSUE THREAD

**Issue by WilliamKF** [SonarOpenCommunity/sonar-cxx#672]
16:03:17.241 ERROR - Unable to parse file: /Users/name/src/Botan/src/selftest/selftest.h
16:03:17.241 ERROR - Parse error at line 23 column 29:

   16: namespace Botan {
   17: 
   18: 
   19: 
   20: 
   21: 
   22: 
  -->  __attribute__ ( ( visibility ( "default" ) ) )voidconfirm_startup_self_tests(Algorithm_Factory&af);
   24: 
   25: 
   26: 
   27: 
   28: 
   29: 
   30: __attribute__ ( ( visibility ( "default" ) ) )boolpasses_self_tests(Algorithm_Factory&af);

**Comment by WilliamKF** [comment]
Workaround, add a "Force includes" file that contains:

    #define __attribute__(x)

**Comment by guwirth** [comment]
This is a gcc specific extension. Add https://github.com/SonarOpenCommunity/sonar-cxx/blob/b2939383d59f3327efaafcc328225d68e3f67c3d/sonar-cxx-plugin/src/main/resources/macros/GxxMacros.h as described here https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces.
