### ISSUE TITLE
Failure to parse Botan header file Botan/build/include/botan/buf_comp.h

### ISSUE THREAD

**Issue by WilliamKF** [SonarOpenCommunity/sonar-cxx#673]
Using Botan v1.10.10 on Mac OS X I get a parse error when running analysis:

17:00:47.052 ERROR - Parse error at line 80 column 11:

   65: data()), str.size());
   66:          }
   67: 
   68: 
   69: 
   70: 
   71: 
   72:       void update(byte in) { add_data(&in, 1); }
   73: 
   74: 
   75: 
   76: 
   77: 
   78: 
   79: 
  -->        void final(byte out[]) { final_result(out); }
   81: 
   82: 
   83: 
   84: 
   85: 
   86: 
   87:       SecureVector<byte> final()
   88:          {
   89:          SecureVector<byte> output(output_length(

I commented out line 80, and it fails at line 87 instead.  Commenting out line 72 doesn't help either.

I'm unclear on what the issue is that is causing the parse error.

**Comment by guwirth** [comment]
Starting with C++11 final is a keyword: http://en.cppreference.com/w/cpp/language/final.

**Comment by WilliamKF** [comment]
Is there a way to force C++03 syntax, and thus allow final?

**Comment by guwirth** [comment]
No I'm sorry. Currently we have only one grammar for all. I would recommend you to avoid C++11/14 keywords also in older code. Sooner or later you will have the problem with your code anyway.

**Comment by Typz** [comment]
One trick is #define final to something else, e.g. __final: This way the parser only sees a regular symbol.

This is used in the plugin to allow c++ reserved keywords in C files.

**Comment by WilliamKF** [comment]
According to this: http://stackoverflow.com/a/33587390/115751 final is only reserved in certain contexts where it was not valid in C++03, so it would seem the parser is rejecting valid C++11 code.

**Comment by guwirth** [comment]
**final** and **override** have a special meaning: http://en.cppreference.com/w/cpp/keyword and are no keywords.

**Comment by guwirth** [comment]
@WilliamKF you can try #675
