### ISSUE TITLE
SonarQube 5.2: configured rules not downloaded for analysis (using sonar-runner)

### ISSUE THREAD

**Issue by BobSilent** [SonarOpenCommunity/sonar-cxx#677]
Hi,

after switching to SonarQube 5.2 no c++ rules get downloaded from quality profile:
- installed plugin
- enabled additional Microsoft Compiler Rules 

when starting the Runner with -X option, and some additional debug information in plugin 
sonar-cxx-plugin\src\main\java\org\sonar\plugins\cxx\compiler\CxxCompilerSensor.java
```java
  public boolean shouldExecuteOnProject(Project project) {
	CxxUtils.LOG.info("shouldExecuteOnProject super: {}", super.shouldExecuteOnProject(project));
	
	CxxUtils.LOG.info("shouldExecuteOnProject getActiveRules size: {}", profile.getActiveRules().size());
	CxxUtils.LOG.info("shouldExecuteOnProject rulesRepositoryKey:  {}", getCompilerParser().rulesRepositoryKey());
	CxxUtils.LOG.info("shouldExecuteOnProject rulesRepositoryKey size:  {}", profile.getActiveRulesByRepository(getCompilerParser().rulesRepositoryKey()).size());
	boolean flag = !profile.getActiveRulesByRepository(getCompilerParser().rulesRepositoryKey()).isEmpty();
	CxxUtils.LOG.info("shouldExecuteOnProject flag:  {}", flag);
	
    return super.shouldExecuteOnProject(project)
      && flag;
  }
```

I get the following output in sonar 5.2
```
shouldExecuteOnProject super: true
shouldExecuteOnProject getActiveRules size: 510
shouldExecuteOnProject rulesRepositoryKey:  compiler-vc
shouldExecuteOnProject rulesRepositoryKey size:  0
shouldExecuteOnProject flag:  false
```

With Sonar 5.1.2 the output is the following:
```
shouldExecuteOnProject super: true
shouldExecuteOnProject getActiveRules size: 1041
shouldExecuteOnProject rulesRepositoryKey:  compiler-vc
shouldExecuteOnProject rulesRepositoryKey size:  531
shouldExecuteOnProject flag:  true
```

The difference in getActiveRules size is the number of c++ rule activated.

In addition I see in the Debug output the following information:
```
Download: http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&amp;activation=true&amp;qprofile=c++-12310&amp;p=1&amp;ps=500
Download: http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&amp;activation=true&amp;qprofile=cs-79137&amp;p=1&amp;ps=500
```

which seems to be new with sonar 5.2.

Executing in Browser:
http://localhost:9000/api/rules/search?f=repo,name,severity,lang,internalKey,templateKey,params,actives&amp;activation=true&amp;qprofile=**c++**-12310&amp;p=1&amp;ps=500

i get an empty result, but escaping the language key in qprofile name from c++ to c%2B%2B
returns the correct results
http://localhost:9000/api/rules/search?f=repo,name,severity,lang,internalKey,templateKey,params,actives&amp;activation=true&amp;qprofile=**c%2B%2B**-12310&amp;p=1&amp;ps=500

or is this an issue for SonarQube itself?

**Comment by guwirth** [comment]
SQ 5.2 is not supported with 0.9.4, see release notes: https://github.com/SonarOpenCommunity/sonar-cxx/releases

**Comment by BobSilent** [comment]
ok, than take this as initial test and analysis ;)

**Comment by jmecosta** [comment]
seems a issue with sq 5.2, see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/sonarqube/ZPJJlmz3Esk/9wBgworPBwAJ


can you rename the profile to confirm it works?

**Comment by BobSilent** [comment]
unfortunately you cannot simply rename the profile, as the name is generated from the plugin internal language key + profile name + internal id 
and at least your language key is set to c**++**
```java 
public class CxxLanguage extends AbstractLanguage {
  public static final String DEFAULT_SOURCE_SUFFIXES = ".cxx,.cpp,.cc,.c";
  public static final String DEFAULT_HEADER_SUFFIXES = ".hxx,.hpp,.hh,.h";
  public static final String DEFAULT_C_FILES = "*.c,*.C";
  public static final String KEY = "c++";
```

**Comment by jmecosta** [comment]
Seems to me that we can't rename the language key, because it will brake many of peoples profiles . so unless they fix this in 5.2.1 I don't think we can support this version.

@guwirth what do you think

**Comment by guwirth** [comment]
Commercial plugin is using 'cpp' as language key. So which options do we have
1. stay with c++
2. use also cpp
3. use cxx

Not sure which impact this would have?
* sonar-project.properties files have to be changed?
* profile has to be exported manually patched and imported again?
* impact on history data?
* ...

To be honest: on my side the interest for SQ 5.2 is currently low. Would anyway wait a little bit until everything is a little bit more perfected.

**Comment by jmecosta** [comment]
we need to update to 5.2, there is this provision feature there that we must take on board. i will try backup/patch/restore to see if there some issues that we were not aware.

anyway the upgrade to 5.2 api we need to do, because it will still be used in later versions

**Comment by guwirth** [comment]
> we (my company) need to update to 5.2 ... anyway the upgrade to 5.2 api we need to do, because it will still be used in later versions

Agree wholeheartedly. Question is only if effort is not lower if other did this step already and we can look how they did it?

> there is this provision feature there that we must take on board

What is this exactly? Could you provide a link to a description please.

**Comment by jmecosta** [comment]
we are using sonar as part of our code review policy, with stash. we rely use feature branches and we run analysis in each branch. the problem earlier was that the profiles were not inherited between branches so different results would be possible. now with 5.2 you can create projects and associate profile before a analysis is run solving this problem.

we have already here a good example of an upgrade to follow:
https://github.com/SonarCommunity/sonar-issue-assign/pull/8
