### ISSUE TITLE
Preprocessor #if code incorrect

### ISSUE THREAD

**Issue by WilliamKF** [SonarOpenCommunity/sonar-cxx#678]
The C preprocessor is not correctly processing complex rules.  The following example is processed incorrectly:

    #define SDS_ARCH_darwin_15_i86

    #ifdef SDS_ARCH_freebsd_61_i86
    #include <sys/endian.h>
    #elif defined(SDS_ARCH_darwin_15_i86)
    #include <libkern/OSByteOrder.h> // Incorrectly not taken.
    #elif defined(SDS_ARCH_winxp) || defined(SDS_ARCH_Interix)
    #else
    #include <byteswap.h>  // Incorrectly taken
    #endif

**Comment by guwirth** [comment]
Could you do some more testing please:
 is this working: #define SDS_ARCH_darwin_15_i86 **1**

**Comment by WilliamKF** [comment]
Yeah, I had already tried that, doesn't help.

**Comment by guwirth** [comment]
we need more low level tests: https://github.com/SonarOpenCommunity/sonar-cxx/blob/2105e6eec7b3d8fc60acc9e0eaacfa05e02e024e/cxx-squid/src/test/java/org/sonar/cxx/lexer/CxxLexerWithPreprocessingTest.java

**Comment by guwirth** [comment]
@WilliamKF  Solution #692
