### ISSUE TITLE
Custom report

### ISSUE THREAD

**Issue by gyllidor** [SonarOpenCommunity/sonar-cxx#679]
Hi!

How can I configure sonar-cxx with custom report from my local application?
Report similar to unit tests report. Actually I can compose this report like googletest.xml and set sonar.cxx.xunit.reportPath to this file but this "slot" is already in use.
What alternatives can I try?

Thanks in advance!

**Comment by jmecosta** [comment]
do you want to import unit tests or issues?

**Comment by gyllidor** [comment]
It's some kind of autotests and report format looks like in unit tests.
For example I can generate this: 
<testsuites tests="1" failures="0" disabled="0" errors="0" timestamp="0" time="0.0" random_seed="1" name="AllTests">
  <testsuite name="some_wrappers" tests="1" failures="0" disabled="0" errors="0" time="0.0">
    <testcase name="my_wrapper1" status="run" time="0.0" classname="someclass" />
  </testsuite>
</testsuites>

But this is not a unit tests (in my case it's wrappers), just I used same tags and format like in google tests. And it will be cool if I can import it to Sonar (How much wrappers and which of them was failed/success).

**Comment by jmecosta** [comment]
nop, we dont have anything in place to import custom random metrics into sonar. imo they should not belong in this plugin. however if you want to display tests as wrappers it should be ok to use the unit test sensor (but i suppose this is not your goal)

what i recomend is for you to create your own plugin and reuse the unit test sensor in this plugin. create a simple widget and display your metric. check this out:

https://github.com/SonarSource/sonar-widget-lab/tree/master/src/main/java/org/codehaus/sonar/plugins/widgetlab

or if you dont need widget, if table is enough than it should be also enough to just save the measures.

**Comment by gyllidor** [comment]
Thanks for the help!

Think I will try to reuse the unit test sensor.
