### ISSUE TITLE
CxxCompilerVcParser: Default Regex not working

### ISSUE THREAD

**Issue by BobSilent** [SonarOpenCommunity/sonar-cxx#684]
Default Regex does not work for me

```java
public static final String DEFAULT_REGEX_DEF = "^.*[\\\\,/](.*)\\((\\d+)\\)\\x20:\\x20warning\\x20(C\\d+):(.*)$";
```

I have to adapt it to 
```
sonar.cxx.compiler.regex=^.*[\\\\,/](.*)\\((\\d+)\\)\\x20*:\\x20warning\\x20(C\\d+):(.*)$
```

as there is no space before the ": warning" 
filename.c(276): warning C4334: '<<' : result of 32-bit shift implicitly converted to 64 bits

**Comment by Bertk** [comment]
Please check the source.
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/compiler/CxxCompilerVcParser.java

Microsoft modified the compiler warning output in VC 9.0, 10.0, 12.0 and therefore the regular expression is configurable.

**Comment by guwirth** [comment]
Think we should document this on https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/CxxPlugin.java?

**Comment by BobSilent** [comment]
I would suggest to at least go on always with latest Conpiler Warnings or with none and force/inform the user to set the value (maybe with some examples in wiki).

Otherwise it is really tricky to find why no findings are found, especially as the example regex on 
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties
is not so self explained to know what should be matched.

**Comment by jmecosta** [comment]
documented here #806
