### ISSUE TITLE
CxxVCppBuildLogParser.java cannot parse x64 log

### ISSUE THREAD

**Issue by BobSilent** [SonarOpenCommunity/sonar-cxx#685]
as in Code, is searched for

```java
if (line.contains("\\bin\\CL.exe")) {
```

but the commandline for x64 CL looks like
```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64\CL.exe  /c ...
```
in log file

**Comment by jmecosta** [comment]
Ok thanks, we can add the support for this for next version. Meanwhile best is to locally modify and build the plugin
