### ISSUE TITLE
Details about undocumented APIs ? 

### ISSUE THREAD

**Issue by wichtounet** [SonarOpenCommunity/sonar-cxx#687]
Hi, 

It would be great if we could see which public APis elements are not documented. Currently, only their number is published. If the file is small, it is quite easy to pinpoint what is not documented, but if the file is large, this becomes rather tedious. 

Thanks

**Comment by guwirth** [comment]
@wichtounet is this check not already doing this: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/UndocumentedApiCheck.java?
If not: What's missing?

**Comment by wichtounet** [comment]
Nothing is missing, I missed it :s  I don't know how I didn't find this violation :(

Thanks a lot, it works like a charm.
