### ISSUE TITLE
Indentation within namespace blocks (again)

### ISSUE THREAD

**Issue by Zetten** [SonarOpenCommunity/sonar-cxx#689]
I haven't had a chance to dig into our particular AST to find out what's going on, but we're again seeing some bugs in the indentation check.

We run with indentNamespace=false and get a violation on the comment line here:
```
namespace foo
{
/** This docstring triggers an issue.
 * ...
 */
class Bar
{
    ... // correctly indented code
}
}
```

All the actual code within the namespace is validated correctly; e.g. it doesn't think the class declaration is wrong. It's just that comment (and the thousands of others like it :smile:).

Replacing ''node.is(CxxGrammarImpl.namespaceBlock)" with "node.getParent().is(...)" (i.e. partially reverting PR #506) seems to work around the issue without failing any tests but as I say I haven't yet investigated in depth - it's probably not that simple...

**Comment by guwirth** [comment]
leftover of "grammar refactoring #743": bug in indentation check
