### ISSUE TITLE
[Vera++] Cannot find the file, even it exists

### ISSUE THREAD

**Issue by GosuKapu** [SonarOpenCommunity/sonar-cxx#690]
Hey, I have strange issue, Vera generates report successfully, but when sonar tries to analyze it, cannot find the code file, even that file exists. In the code below i put "..." instead of real path, to make code shorter.

    [sonar:sonar] 09:00:23.712 INFO  - Processing report 'C:\...\report.xml'
    [sonar:sonar] 09:00:23.712 INFO  - Parsing 'Vera++' format
    [sonar:sonar] 09:00:23.712 INFO  - Vera++ processes file = C:\...\analyzingFile.h
    [sonar:sonar] 09:00:23.713 WARN  - Cannot find the file 'C:\...\analyzingFile.h', skipping violations
    [sonar:sonar] 09:00:23.713 INFO  - Vera++ rule violations processed = 0

I have no idea, and Internet is useless in this case :(

**Comment by jmecosta** [comment]
Is the file imported to sonar? Issues can only be raised against files that
reside inside the sonar project.

**Comment by guwirth** [comment]
@GosuKapu  Please read also this :https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues

**Comment by GosuKapu** [comment]
@jmecosta Yes, I have all files imported to sonar.
@guwirth Thanks for the link, I checked everything, I use backslashes in reports (Windows) and path to my reports is absolute.

**Comment by jmecosta** [comment]
next question is to know what version of the plugin are you using, and what version of sonar

**Comment by GosuKapu** [comment]
Sonar: 4.5.4
Plugin: 0.9.4

**Comment by jmecosta** [comment]
can you run with -X to get more information in log, your config is fine

**Comment by guwirth** [comment]
How to create log file: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

**Comment by GosuKapu** [comment]
Hey, I will run and post log later, right now I do not have access to the computer with project and Vera for a couple of days.

**Comment by GosuKapu** [comment]
My friend found a solution... There should be written, that in paths your plugin is casesensitive.

**Comment by jmecosta** [comment]
It's not the plugin, its the platform. In the end java that dictates those
rules. But good that you that you found the solution. By the way with debug
log it might have given some hint about that since it prints the paths of
the imported files in log

**Comment by jmecosta** [comment]
@GosuKapu by the way, if you are running in windows you could try https://github.com/SonarOpenCommunity/sonar-cxx-msbuild-tasks/releases/download/1.1/CxxSonarQubeMsbuidRunner.zip it should make you life a bit easier since it runs the vera for you
