### ISSUE TITLE
Document Custom SquidCheck in Wiki

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#691]
How to use Custom SquidChecks #527 should be documented in Wiki.

**Comment by jmecosta** [comment]
@felipebz @guwirth ive move the code provided by @felipebz to https://github.com/SonarOpenCommunity/cxx-custom-checks-example-plugin i will document this in wiki https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis

**Comment by jmecosta** [comment]
documented now

**Comment by guwirth** [comment]
:+1: it's ok but would be better to list all in a table VS2010...VS2015

**Comment by jmecosta** [comment]
@guwirth done.

**Comment by guwirth** [comment]
@jmecosta thx
