### ISSUE TITLE
CxxReportSensor.java: file not found for issue

### ISSUE THREAD

**Issue by BobSilent** [SonarOpenCommunity/sonar-cxx#693]
Hi,

the visualStudio c++ compiler writes the compiler warnings without absolute path information into the log file, if the source file (which has an issue) belongs to my vcxproj. 
Example
```
  aaa.cpp
  bbb.cpp
  ccc.cpp
C:\FULLPATH_TO_GLOBAL_INCLUDE\Include\ddd.h(xx): warning C4239: nonstandard extension used : 'argument' : conversion from 'CString' to 'CString &' (ccc.cpp)
          A non-const reference may only be bound to an lvalue
ccc.cpp(yyy): warning C4239: nonstandard extension used : 'argument' : conversion from 'CString' to 'CString &'
          A non-const reference may only be bound to an lvalue
```

unfortunately the source file ccc.cpp is not found, as in
CxxReportSensor.java (sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/utils/CxxReportSensor.java)

```java
  private void saveViolation(Project project, SensorContext context, String ruleRepoKey,
    String filename, String line, String ruleId, String msg) {
    Issuable issuable = null;
    int lineNr = 0;
    // handles file="" situation -- file level
    if ((filename != null) && (filename.length() > 0)) {
      String root = reactor.getRoot().getBaseDir().getAbsolutePath();
```

you are using 
```java
      String root = reactor.getRoot().getBaseDir().getAbsolutePath();
```
for resolving the root directory,
if I change it to 

```java
	  String root = fs.baseDir().getAbsolutePath();
```
everything can be resolved.
also other sensors, e.g. java use fs.baseDir
 sonar-java/java-surefire/src/main/java/org/sonar/plugins/surefire/api/SurefireUtils.java
 sonar-java/java-jacoco/src/main/java/org/sonar/plugins/jacoco/JaCoCoOverallSensor.java

Some other side aspects: i am using the following directory structure
```
\sonar-project.properties (*)
├───module1
│       module1.vcxproj (**)
│       sonar-project.properties
│
├───module2
│       module2.vcxproj
│       sonar-project.properties
│
├───module3
│       module3.vcxproj
│       sonar-project.properties
│
└───module4...
```
(*) one root project properties
(**) module properties, in parallel to the vcxproj

reactor.getRoot().getBaseDir().getAbsolutePath() is always "\" same as location of (*)
fs.baseDir().getAbsolutePath() is e.g. "\module1" location of module1 directory (**)

Why do you use "reactor.getRoot().getBaseDir()"?
Can it be changed to "fs.baseDir()"

**Comment by jmecosta** [comment]
@Bertk you use this kind of module structure, i tough you had no issues with this. @guwirth perhaps we should use the same approach as the report lookup, use reactor to lookup from root of the project and if not found search using the fs.baseDir to get to root of the module.

@BobSilent i dont think using your suggestion will cover all scenarios we support, you can try to make a pull request and see if the integration tests pass, pretty sure they dont

**Comment by guwirth** [comment]
On this page https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues is also a description how MultiModule setup should work. I don't use it so I have no experience with it.

**Comment by Bertk** [comment]
Please use 'FC' compiler option (https://msdn.microsoft.com/en-us/library/19z1t1wy.aspx) which creates full path information in the VC log files. We use the multi module configuration and use identical names in several projects which is ambiguous without the full path.

**Comment by guwirth** [comment]
>,reactor.getRoot().getBaseDir().getAbsolutePath() is always "\" same as location of ()
fs.baseDir().getAbsolutePath() is e.g. "\module1" location of module1 directory (*) Why do you use "reactor.getRoot().getBaseDir()"? Can it be changed to "fs.baseDir()"

My feeling is also that fs.baseDir().getAbsolutePath() is right?

**Comment by Bertk** [comment]
Do we have a PR? I want to test it and maybe this might also be useful for #509.
Today I can only create the issues from reports but the "Dependency Structure Matrix" was not available.
There might be also an impact on MSBuild runner or the deprecated VS Solution bootstrapper plug-in which we should avoid.

**Comment by jmecosta** [comment]
Can the multi module sample we have in integrations test be used to check
this?

**Comment by guwirth** [comment]
@all see test with #695 and comments there

**Comment by guwirth** [comment]
please try again with 0.9.5:
* improved multi module support => #695
* allow to specify absolute paths for reports. to support msbuild runner #683
