### ISSUE TITLE
gcovr report failed to import due to filepaths in xml report

### ISSUE THREAD

**Issue by chrismik** [SonarOpenCommunity/sonar-cxx#694]
While this may or may not be an issue with the sonar-cxx plugin. It should be at least documented on the wiki so others do not use the wrong version of gcovr.

From 2013:
http://sonarqube-archive.15.x6.nabble.com/With-community-C-plugin-can-t-see-cobertura-coverage-results-td5019173.html

I have the following installed:  Sonarqube 5.1.2; sonar-cxx 0.9.4; and gcovr 3.2 installed. 

This is what I from using the sonar-runner on the Sample2 example project:
`
12:08:19.415 INFO  - Processing report '/opt/dev/sonarqube-deps/sonar-cxx-master/sonar-cxx-plugin/src/samples/SampleProject2/build/gcovr-report.xml'`
`12:08:19.415 INFO  - Parsing 'Cobertura' format`
`12:08:19.417 INFO  - Added report '/opt/dev/sonarqube-deps/sonar-cxx-master/sonar-cxx-plugin/src/samples/SampleProject2/build/gcovr-report.xml' (parsed by: CoberturaParser) to the coverage data`
`12:08:19.417 WARN  - Cannot find the file '/opt/dev/sonarqube-deps/sonar-cxx-master/sonar-cxx-plugin/src/samples/SampleProject2/component1.cc', ignoring coverage measures
`
...

In order to correct this error you have use the correct version of gcovr (i.e. the latest does not work):

The gcovr generated report needs to be modified as such (correct the path) for sonar-runner to ingest it:
ORG: `<class branch-rate="0.5" complexity="0.0" filename="component1.cc" line-rate="0.954545454545" name="component1_cc">`
MOD: `<class branch-rate="0.5" complexity="0.0" filename="src/lib/component1.cc" line-rate="0.954545454545" name="src/lib/component1_cc">`

**Comment by guwirth** [comment]
Have you read this https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues?

**Comment by chrismik** [comment]
Thanks. I have now read the provided link and still do not believe it addresses what is needed.
The provided link tells me either:
a) what is required for reports "Relative paths defined in configuration file are always relative to root folder". Such that it's on you to ensure external tools meet the requirement.
b) the Sample2 sonar configuration files should be updated to include modules if that will resolve this issue.

The issue is if you do not install gcovr version 2.4 (or older) you will not get coverage reports on the supplied example project Sample2 (which you hope will work out of the box).

A note can be provided within the installation documentation (wiki or readme files) to say:
gcov coverage reports requires gcovr version <= 2.4  (as newer versions will not work with Sample2).
pip install gcovr==2.4 
(current lastest version 3.2 does not meet the sonar-cxx requirements with paths in the generated xml reports and will not work).

I will also add an issue to the gcovr project as not providing proper paths seems not very useful. It should provide at-least a cmd line argument to provide relative paths within the xml reports).

**Comment by chrismik** [comment]
I add a note to : https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Coverage-tracers

**Comment by guwirth** [comment]
Correction of the procedure of coverage report and as I experienced, there is no issue for gcovr version > 2.4.
