### ISSUE TITLE
Deactivated rules after update to latest version

### ISSUE THREAD

**Issue by chrissy25** [SonarOpenCommunity/sonar-cxx#696]
Hi,

yesterday we updated our CXX plugin to the latest version. In our quality profiles there were some changes I do not really understand. Some rules were deactivated and I am not able to activate them again, although I can see the rules. Do you know why?

![image](https://cloud.githubusercontent.com/assets/7090420/11586784/a10326fc-9a75-11e5-85ed-0f6a77a91349.png)

**Comment by jmecosta** [comment]
What version did you update from? Some of the rules had their keys updated
so this is expected behaviour. However it's weird that you can't enable the
new ones, check from the deactivated rules if there are rules that have
similar names. They should be easy to spot.

**Comment by chrissy25** [comment]
Okay, now the activation worked ... maybe just a temporary problem with Sonar itself.
Just two rules I was not able to find
"Avoid too complex function" and "Avoid too complex source file"
Are those rules still available?

**Comment by jmecosta** [comment]
they are called:

files should not be to complex, and functions should not be to complex..

**Comment by chrissy25** [comment]
Thanks for your support :)

**Comment by jmecosta** [comment]
No prob. Good it helped
