### ISSUE TITLE
Why do we need an own msbuild runner?

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#699]
Like to understand why we need an own msbuild runner? In case of sonar-runner there is only one. What is different / special for our cxx plugin?

@jmecosta maybe you can answer this?

**Comment by jmecosta** [comment]
it works :)

**Comment by jmecosta** [comment]
now a bit more seriously, it patches the existing one to enable the import of include files. and the main benefit is that i will run the static analysis and configure the msbuild buildlog to be take into analysis.

with this one, you dont need any configuration to actually have very good results from first run.

all is automatic, it will install all tools for you also.

**Comment by jmecosta** [comment]
also the sonar-runner has always had very good record of supporting any language, the dotnet tools have always been very resilient to support anything other than their own languages. the wrapper ive created patchs the target files to allow also to import project files that i need for msbuild plugin.

**Comment by jmecosta** [comment]
and i forgot one important thing, the msbuild runner will not take into consideration any settings from sonar.properties file. the wrapper will read your existing file for you and convert it to the msbuild runner specific format that is actually quite different
