### ISSUE TITLE
Is QAC supported ?

### ISSUE THREAD

**Issue by schiean** [SonarOpenCommunity/sonar-cxx#703]
I was wondering if there is any support for integrating QAC / QACPP with Sonar CXX. At this moment we use Jenkins to build our C++ projects and view our QAC warnings, and use SonarQube with sonar-cxx to watch code coverage and other metrics. It would be nice if the QAC reports could be integrated into sonarqube like cppcheck and valgrind.
Is there any guide on how to do this ?
Or is this not possible yet ?

**Comment by jmecosta** [comment]
you can follow the guide https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis if there is something you can use or:

https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis#usage-of-unsupported-code-checkers

we create one profile for those and given that the output format is correct they will be imported. we use this for cpplint, intel inspector and a few internal rules

**Comment by jmecosta** [comment]
by the way, feel free to document your final profile in this page: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis#resources
