### ISSUE TITLE
Unable to parse "__pragma(warning(push, 0))"

### ISSUE THREAD

**Issue by smackinnon89** [SonarOpenCommunity/sonar-cxx#704]
Hello,

Sonar-cxx fails to parse pragma warnings as seen below.
     10:20:52.375 ERROR - Parse error at line 5 column 19:

    -->  __pragma ( warning ( push , 0 ) )

Info:
https://msdn.microsoft.com/en-us/library/d9x1s805.aspx

Pragma warning push/pop is often used to temporarily suppress a particular warning, for example:

    __pragma(warning(push))
    __pragma(warning(disable: 4127))
    __pragma(warning(pop))

**Comment by guwirth** [comment]
```__pragma``` is a compiler specific extension, see https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces how to handle it.

Use ```sonar.cxx.defines``` or ```sonar.cxx.forceIncludes``` to mock it, examples are here: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/sonar-cxx-plugin/src/main/resources/macros.

**Comment by smackinnon89** [comment]
Great, thanks a lot @guwirth.
