### ISSUE TITLE
parser error during marco resolving

### ISSUE THREAD

**Issue by schroeca** [SonarOpenCommunity/sonar-cxx#705]
I'm using your plug-in to parse **SystemC** source code. Which is fully compliant to the C++ standard.

The following source code leads to an parser error.

First file:
```C++
SC_METHOD(sc_method1);
```
The **SystemC** macro **SC_METHD** is defined in sc_modules.h which looks like this:

```C++
#define declare_method_process(handle, name, host_tag, func)        \
    {		                                                    \
        ::sc_core::sc_process_handle handle =                      \
	    sc_core::sc_get_curr_simcontext()->create_method_process( \
		name,  false, SC_MAKE_FUNC_PTR( host_tag, func ), \
		this, 0 ); \
        this->sensitive << handle;                                        \
        this->sensitive_pos << handle;                                    \
        this->sensitive_neg << handle;                                    \
    }

#define SC_METHOD(func)                                                       \
    declare_method_process( func ## _handle,                                  \
                            #func,                                            \
                            SC_CURRENT_USER_MODULE,                           \
                            func )

```

If I paste the resolved macro directly in my source file, everything works fine.
If I use the **SC_METHOD** macro i get an error.

My SonarQube version is: 4.5.6
My Plubin version is: 0.9.4

**Comment by guwirth** [comment]
Please use the sslr toolkit to reduce the problem/example: https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-0.9.4/sslr-cxx-toolkit-0.9.4.jar

Remove all parts not needed to reproduce it, e.g.:

```C++
#define declare_method_process(handle, name, func)        \
    {		                                                    \
        int handle = f(name, SC_MAKE_FUNC_PTR(func)); \
    }

#define SC_METHOD(func)                                                       \
    declare_method_process( func ## _handle,                                  \
                            #func,                                            \
                            func )
```

**Comment by schroeca** [comment]
I'm very sorry but I'm not a SonarQube Admin and it is not possible to remove anything from the define statements.

I'm also not sure how to use this sslr toolkit.

I tried to reproduce the behaviour with different modifications of the define statements.

It seems that the **"::"**sc_core:: ... which is necessary to be sure that it is referenced to the global namespace causes the parser crash

**Comment by guwirth** [comment]
reproducible with this:

```C++
#define SC_METHOD(func) declare_method_process( func ## _handle, #func, func )
SC_METHOD(test);
```
Problem is the `#func` after `func ## _handle`.
