### ISSUE TITLE
Which commenting syntax shall be used for cxx:UndocumentedApi?

### ISSUE THREAD

**Issue by schroeca** [SonarOpenCommunity/sonar-cxx#706]
Where can I find information on which commenting syntax is recognized by the rule checker for **cxx:UndocumentedApi**?

**Comment by guwirth** [comment]
An example is on the rule page in SQ: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/resources/org/sonar/l10n/c%2B%2B/rules/cxx/UndocumentedApi.html

**Comment by schroeca** [comment]
Is it also possible to redefined the rule to use standard C++ comments?

**Comment by lcintrat** [comment]
@schroeca What do you mean by "standard C++ comments"?

**Comment by schroeca** [comment]
For example:

```C++
// comment for the class
class Test1 {

  // comment for functions
  void func1();

  double mem1;  // comment for member
}
```

**Comment by lcintrat** [comment]
Those are comments, not documentation. The purpose of the sensor is to estimate generated API documentation, which is usually generated by a tool such as Doxygen. I don't know if there is a tool that generates documentation from raw comments. By the way, Doxygen syntax relies on "standard C++ comments" ;)

**Comment by schroeca** [comment]
ok thx for the explanation.
