### ISSUE TITLE
usage of numbers in case statement

### ISSUE THREAD

**Issue by schroeca** [SonarOpenCommunity/sonar-cxx#712]
I always get an issue reported if I'm using a number in an case statement.
This is no issue from my point of view.

Is it possible to configure the rule check for magic numbers to ignore switch/case statements?

**Comment by Bertk** [comment]
No, you cannot exclude switch statements but you can define exceptions see https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/MagicNumberCheck.java.

**Comment by guwirth** [comment]
Please reopen if still a problem.
