### ISSUE TITLE
No "External rules definition" textbox

### ISSUE THREAD

**Issue by GosuKapu** [SonarOpenCommunity/sonar-cxx#714]
Greetings,
I need to import analysis data from Visual Studio analyze tool. Wanted to create custom rules to make it work, but I do not have "External rules definition" textbox, as stated here: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis#usage-of-unsupported-code-checkers

Any ideas?
![no-code-rules-extend](https://cloud.githubusercontent.com/assets/3708504/11840746/8b2d1f7c-a3f8-11e5-9211-2a78c4abad3f.png)

**Comment by guwirth** [comment]
Which version of the plugin, SonarQube and Java are you using?

**Comment by GosuKapu** [comment]
Sonar: 4.5.4
Plugin: 0.9.4
Java: 1.7.0

**Comment by jmecosta** [comment]
Are you changing those at project level or global level? Those should be only at global level. You need to be system admin

**Comment by GosuKapu** [comment]
Oh, ok :/ I am changing it at project level. Thanks.

**Comment by jmecosta** [comment]
No prob. Don't forget to restart server after changing rules.
