### ISSUE TITLE
Fix integration tests for SQ 5.2/5.3+

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#721]
Integration tests are no more working with SQ 5.2/5.3+.
@jmecosta do you have some time to fix it?

**Comment by guwirth** [comment]
@jmecosta what exactly must be done here?
As far as I understand we have to wait until analysis is finished on server side before we can request for the results? Is there something in the rest API supporting this?

**Comment by jmecosta** [comment]
yes we must wait for the analysis to complete before requesting the analysis results. ive done this in the cxx runner.

https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/blob/master/CxxSonarQubeMsbuidRunner/SonarRunnerPhases.fs#L194

the log will give the rest call to check the results, so we just need a get request and parse the results. however i am afraid a few other things might need to be adjusted in the rest calls

a quick workaround would be to put a wait, sleep of 1 min (more than enough) in the python script. that should give us already an idea about what needs to be change.

i am in middle of doing a release for the visual studio extension, i try to work on this after i finish what i am doing

**Comment by jmecosta** [comment]
@guwirth quick analysis:

test_success_density > seems it does not exist in 5.3 (i will remove)
package_tangles and package_tangles_index > likely removed because the all the cycles features have been removed. (i will remove)
coverage -> there seems to be some changes (i am ensure why needs to be investigated) likely  sonar.source and sonar.tests have made the cause this

**Comment by jmecosta** [comment]
class_complexity also changed from 6 to 7, that one is odd also

**Comment by guwirth** [comment]
I think we should create issues / ask in the SQ newsgroup before we remove/change something. Currently it's an SQ5.3 beta only and not clear if bug or feature. 

Especially the *test_success_density* is strange for me. Observing technical debt all unit tests should always be green.

**Comment by jmecosta** [comment]
yep, test_success_density i can still find in core metrics https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/measures/CoreMetrics.java#L453 so it seems really  a issue. do you mind raising the issue in  newsgroup? 

i will revert the test density, the tangle things are deprecated

**Comment by guwirth** [comment]
I will create an issue.

**Comment by guwirth** [comment]
@jmecosta is this the way to wait for a finished analysis?
http://www.google.com/url?q=http%3A%2F%2Fdocs.sonarqube.org%2Fdisplay%2FSONAR%2FBreaking%2Bthe%2BCI%2BBuild&sa=D&sntz=1&usg=AFQjCNGFJgbpImq1xr9LLxsRXzg-wKiJxA

**Comment by jmecosta** [comment]
yes this is the way ive implemented also with the cxx wrapper

https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/blob/master/CxxSonarQubeMsbuidRunner/SonarRunnerPhases.fs#L271

**Comment by guwirth** [comment]
@jmecosta do you have some time to fix this? would be good to verify SQ 5.3 also in our integration tests.

**Comment by jmecosta** [comment]
What should I do regarding the metrics differences?  Ignore them, update them

**Comment by guwirth** [comment]
@jmecosta first of all I would fix the API usage to wait until server finished analysis. This is independent from results
Then we have to think about if we still wanna be backward compatible or 0.9.5 is for SQ 5.3+ only? Current problem I see that they are changing things very fast with a clear break between SQ 5.2+  and earlier versions.

**Comment by jmecosta** [comment]
5.3 should still be compatible with last LTS and it is in current version.
I think this version should still be running the its for those versions
since there improvements regarding the grammar and the reports that people
need.

IMO maybe disable those metrics  differences and enable in the next LTS and
drop support then?

Yes the ci check can be done already.  I try to work on that soon.

**Comment by jmecosta** [comment]
@guwirth i am working on this on this weekend. hopefully its ready tomorrow. sorry for the delay

**Comment by guwirth** [comment]
closed with #682
