### ISSUE TITLE
NUnit test result support

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#722]
Support NUnit test file format: https://github.com/nunit/nunit/wiki/XML-Formats

* V2 Test Results
 * sample: http://nunit.org/files/testresult_25.txt
 * schema: http://nunit.org/files/testresult_schema_25.txt

* V3 Test Results
 * sample: http://nunit.org/files/testresult_30.txt

Does someone have already an XMLT to convert NUnit to JUnitReport?

**Comment by jmecosta** [comment]
Are you doing c++cli? There are parsers available in dotnet side that you
can reuse

**Comment by guwirth** [comment]
No we have plain C++ code with COM interfaces. For testing this we are using NUnit.

> Am 28.12.2015 um 13:52 schrieb Jorge Costa <notifications@github.com>:
> 
> Are you doing c++cli? There are parsers available in dotnet side that you
> can reuse

**Comment by jmecosta** [comment]
Suppose there is no harm on using the already available parsers. C++cli is
already supported so suppose nunit reports could also be supported

**Comment by guwirth** [comment]
Found this:
* http://www.wrightfully.com/sonarqube-plugin-for-existing-nunit-reports-work-in-progress/
* http://sonarqube-archive.15.x6.nabble.com/sonar-dev-NUnit-reuseReport-support-td5019719.html

Our current approach is to convert other formats with XSLT to JUnit. I would like to continue with this approach. 

> Am 28.12.2015 um 14:13 schrieb Jorge Costa <notifications@github.com>:
> 
> Suppose there is no harm on using the already available parsers. C++cli is
> already supported so suppose nunit reports could also be supported
>

**Comment by jmecosta** [comment]
Ok in that case I don't have any xslt for this sorry. By the way the dotnet
tests library contains also the implementation for nunit 2 and nunit 3 is
in a PR from me.

**Comment by guwirth** [comment]
Could also extend this https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/xunit/MSTestResultsProvider.java
