### ISSUE TITLE
expression parser errors

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx#728]
This code snipped creates parser errors if the commented-out source code lines are used.

- typeid() compare
- missing parenthesis 

@guwirth, @jmecosta Shouldn't this be improved?

```cpp
template <typename Real>
Real PiEstimator<Real>::operator()()
{
  struct cudaDeviceProp     deviceProperties;

  // Get device properties
  cudaResult = cudaGetDeviceProperties(&deviceProperties, m_device);

//if (typeid(Real) == typeid(double)) 
//  {
//    return -1;
//  }

  if ((deviceProperties.major < 1) || ((deviceProperties.major == 1) && (deviceProperties.minor < 3)))
    {
      return -1;
    }

//if   (deviceProperties.major < 1) || ((deviceProperties.major == 1) && (deviceProperties.minor < 3))
//  {
//    return -1;
//  }

//original expression from CudaSamples/MC_EstimatePiInlineP_vs2013/src/piestimator.cu 
//if (typeid(Real) == typeid(double) &&
//   (deviceProperties.major < 1 || (deviceProperties.major == 1 && deviceProperties.minor < 3)))
//   {
//     throw std::runtime_error("Device does not have double precision support");
//   }
}
```

**Comment by guwirth** [comment]
@bertk could you reduce this to a minimal failing sample please.
> typeid() compare

typeid compare should be fixed.
> missing parenthesis

Precondition for the plugin is syntactical correct code.  Only thing you can do is turning ErrorRecovery on.

**Comment by Bertk** [comment]
After looking on some details the  ```typeid()``` operator should be also be defined as CxxKeyword (http://en.cppreference.com/w/cpp/keyword).

This fails:
```cpp
#include <typeinfo>    // for 'typeid'

int main() 
{
printf("Precision:      %s\n", (typeid(double) == typeid(double)) ? "double" : "single");
}

```
or
```cpp
#include <typeinfo>    // for 'typeid'

int main() 
{
  boolean isDouble = (typeid(double) == typeid(double));
}
```

**Comment by guwirth** [comment]
A newer c++ standard draft version is here: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/dox/2015-07-24_cpp_std_draft.pdf => 2.11 Keywords: typeid is a keyword.

Remember that we changed this because of CLI support: #586

**Comment by Bertk** [comment]
I did not a complete rework of the ```postfixExpression``` but with this solution the typeid keyword is back. Please check this commit af46c7e797d088a4c77268ec96573881f284bf12.

There are some lines which shall be checked as well - I feel the ```b.optional("::")``` should be removed:
```
	Line 960:     b.rule(usingDirective).is(b.optional(attributeSpecifier), CxxKeyword.USING, CxxKeyword.NAMESPACE, b.optional("::"), b.optional(nestedNameSpecifier), namespaceName, ";");
	Line 1461:             b.sequence(b.optional("::"), b.optional(nestedNameSpecifier), typeName, b.optional("^")),
	Line 1462:             b.sequence(b.optional("::"), b.optional(nestedNameSpecifier), CxxKeyword.TEMPLATE, templateId, "^")
	Line 1519:         b.sequence(b.optional("::"), b.optional(nestedNameSpecifier), innerSimpleTemplateId),
	Line 1520:         b.sequence(b.optional("::"), b.optional(nestedNameSpecifier), CxxKeyword.TEMPLATE, innerSimpleTemplateId),
```

**Comment by guwirth** [comment]
Would merge it and do bigger refactoring of grammar later on in one step. Think we have to compare our version step by step with latest standard again.

**Comment by jmecosta** [comment]
Which raises again the clang question :)

**Comment by Bertk** [comment]
@jmecosta Clang might not support extension like C++/cli or CUDA kernel function. I also like the idea to use the AST parser from clang - it is less effort to stay up-to-date with the C++ standard :sunglasses:  but the effort to migrate is **unknown** :worried:

**Comment by jmecosta** [comment]
Yep I agree with that also, but it would be great if we could pull that one
off
