### ISSUE TITLE
MSTestResultsProvider not documented

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#731]
Documentation for `sonar.cxx.vstest.reportsPaths` missing. 

https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/xunit/MSTestResultsProvider.java

**Comment by guwirth** [comment]
sonar-dotnet-tests-library has been extended to support also NUnit: https://github.com/SonarSource/sonar-dotnet-tests-library/commit/ca40d1730215bc148e3b6888d6f2e09924adf7c8
Maybe we should also do this?
See also #722

**Comment by jmecosta** [comment]
either way, xslt or a new parser. i suppose the fastest is to reuse the implementation int sonar-dotnet-tests

**Comment by guwirth** [comment]
documented: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties

**Comment by guwirth** [comment]
documented:https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties
