### ISSUE TITLE
alias template can only be inline documented

### ISSUE THREAD

**Issue by wichtounet** [SonarOpenCommunity/sonar-cxx#736]
Hi, 

I just discovered that alias templates can only be documented with inline comment (after member documentation). 

This does not show an issue: 

    template <typename T>
    using intrinsic_type = typename intrinsic_traits<T>::intrinsic_type; ///< DOCUMENTATION

But this is shown as undocumented API:

    /*!
     * \brief DOCUMENTATION
     */
    template <typename T>
    using intrinsic_type = typename intrinsic_traits<T>::intrinsic_type;

I think that the second should be supported since it is the only form that allows to document the template parameters.

**Comment by guwirth** [comment]
An example is on the rule page in SQ: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/resources/org/sonar/l10n/c%2B%2B/rules/cxx/UndocumentedApi.html

**Comment by lcintrat** [comment]
Hi @wichtounet,

You are right, the second form should not count as an issue.

**Comment by wichtounet** [comment]
Just tested and works fine :)

It saved me 2 days of technical debt :)

**Comment by lcintrat** [comment]
Good to know :)

Ty for the report :+1:
