### ISSUE TITLE
Vote: Update C++ plugin roadmap

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx#738]
@guwirth: This information does not mention the latest version.
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Roadmap

**Comment by guwirth** [comment]
Yes you are right. Think the whole wiki it's a little bit outdated.

**Comment by guwirth** [comment]
Any ideas how to proceed?

* SQ 5.3 support
* remove deprecated APIs
* support of C++17
* grammar refactoring
* support of Clang tools
* improve wiki
* add NUnit support
* ...

**Comment by jmecosta** [comment]
i would focus on supporting 5.3 since we dont have anything running in >
5.2 versions. should not be a hard thing to pull.

clang and c++17 by themselfs are topics for a single release imo

**Comment by tyrel** [comment]
SQ 5.3 please! It's beautiful.

**Comment by jmecosta** [comment]
works fine with 5.3 if you use the latest snapshot.
https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

**Comment by tyrel** [comment]
Thanks, the snapshot looks good.

**Comment by guwirth** [comment]
@tyrel could you share your experience with 0.9.5 snapshot and SQ 5.3 with us please?

**Comment by guwirth** [comment]
**V0.9.5:**
* SQ 5.3 support
* remove deprecated APIs
* bugfixing

**Comment by tyrel** [comment]
@guwirth certainly. It seems to work fine. You can see the build log here https://gitlab.com/kulshan-concepts/zebu3/builds/626972 and the results here http://cloud.kulshanconcepts.com:9000/overview?id=171.

**Comment by guwirth** [comment]
Thx good to hear.

**Comment by jmecosta** [comment]
Is that cloud service something we could use to check the quality of our code?

**Comment by tyrel** [comment]
@jmecosta Do you mean to check the quality of sonar-cxx itself? I could look into donating access to the machine for that.

**Comment by jmecosta** [comment]
There were some discussion about this in past, I saw in the link the word cloud thought we could use also something like this to check the quality of the cxx plugin.  Is that your own service?

**Comment by tyrel** [comment]
It's an OpenStack virtual machine hosted by DreamCompute, running Ubuntu. It doesn't cost me very much and it's more that enough for my needs right now.

**Comment by jmecosta** [comment]
Alright now I got it. I think we would need something like that, but since you are paying it might not work for us :(
