### ISSUE TITLE
Eclipse integration plugin

### ISSUE THREAD

**Issue by rsantamaria80** [SonarOpenCommunity/sonar-cxx#740]
Hi!

I would like to know if there is a plan to develop a plugin or tool to be able to run an analysis on-the-fly in Eclipse, as SonaLint does.

Will this plugin be able to be used joinly with SonarLint in the future?

Thank you!

**Comment by jmecosta** [comment]
No, I think the chances are very slim as this is not a official plugin.  If
you were using visual studio you could use the vssonarextension. Buy
eclipse is a completely different ball game
