### ISSUE TITLE
SQ 5.4: now requires the metrics complexity_in_classes  and complexity_in_functions

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#747]
**Problem: value of class complexity is different with SQ 5.2+**

SQ support: Thanks for the project, we've been able to investigate and could understand your issue. As we're computing the complexity per class in a different way, the value can now be different but this come in fact from another issue : the plugin doesn't compute the measure 'complexity_in_classs' so there's a fallback mechanism to use the complexity instead. 

But this is not the right way to do : we should only rely on the complexity_in_classes and not anymore rely on the complexity. This will be done by https://jira.sonarsource.com/browse/SONAR-7169.

* link https://groups.google.com/forum/#!topic/sonarqube/8hV4EUauzJE
* related to #721

**Comment by guwirth** [comment]
https://groups.google.com/forum/#!topic/sonarqube/vNMe3cMuYwg
Julien Lancelot: ndeed, there were a change in the way class_complexity and function_complexity are computed : they now required the metrics complexity_in_classes  and complexity_in_functions. 
Please have a look at this JIRA ticket for more details : https://jira.sonarsource.com/browse/SONAR-7169.

**Comment by guwirth** [comment]
This is a blocker for SQ 5.4. Someone an idea/sample from another plugin how to calculate **complexity_in_classes**?

**Comment by mjdetullio** [comment]
Possibly the Flex plugin https://github.com/SonarSource/sonar-flex/blob/master/sonar-flex-plugin/src/main/java/org/sonar/plugins/flex/FlexSquidSensor.java

**Comment by guwirth** [comment]
@mjdetullio thanks. Found also one in https://github.com/SonarSource/sonar-javascript/blob/5986d8a76ba40b3f0f35514a0808a9f89b6a7488/javascript-frontend/src/main/java/org/sonar/javascript/metrics/MetricsVisitor.java

**Comment by guwirth** [comment]
Also with final SQ5.4 still a problem https://travis-ci.org/SonarOpenCommunity/sonar-cxx/jobs/114902000
