### ISSUE TITLE
Why didn't find the checks for naming convention in sonar-cxx-plugin-0.9.4.jar

### ISSUE THREAD

**Issue by myloveperonjj** [SonarOpenCommunity/sonar-cxx#762]
SonarQube 5.1.2  have not found in Repository c++ SonarQube c++?

not found:
FileNameCheck: file name check support 
MethodNameCheck: method name check support 
FunctionNameCheck: function name check support 
ClassNameCheck: class name check support

**Comment by myloveperonjj** [comment]
Do I need to modify this file?

https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/CheckList.java

**Comment by Bertk** [comment]
I have no idea why the checks are not activated. Adding the checks to the list should fix it.
By the way, the naming check should be moved to a subdirectory to separate this group of check from the others (see Java plug-in naming checks: https://github.com/SonarSource/sonar-java/tree/master/java-checks/src/main/java/org/sonar/java/checks/naming) .

**Comment by guwirth** [comment]
@myloveperonjj yes must be part of checklist. Like also the idea to move it to a subfolder.
@myloveperonjj do you wanna provide a PR or should I do it the next days?

**Comment by guwirth** [comment]
will do it
