### ISSUE TITLE
"External checkers report" not working

### ISSUE THREAD

**Issue by GosuKapu** [SonarOpenCommunity/sonar-cxx#767]
Greetings,
I have prepared Visual Studio Analysis C++ report, converted it to "External checkers report" format, and put the path to it in Web UI. I have also all needed rules.
When I start analysis - it looks like nothing is happening. Tried to run Sonar with -X option. When I e.g. type wrong Vera++ report path, there is error that file do not exists. But when I type wrong External report path, no error is shown. Also when the path is correct, no information is shown. It looks like the whole "External checkers report" feature is ignored.

Sonar: 4.5.4
Plugin: 0.9.4
Java: 1.7.0

**Comment by jmecosta** [comment]
can you past the log around this part:

[11:28:34] :		 [Step 3/3] 11:28:34.493 INFO  - Parsing 'other' format

**Comment by GosuKapu** [comment]
Sadly, there is none of them. I have external rules and external reports specified. But... I do not see my custom rules, so that might be a problem.
Cannot I use external reports with built-in rules to test it?
![external reports](https://cloud.githubusercontent.com/assets/3708504/12615867/689b7b6c-c508-11e5-92b4-ece5bae01405.png)
![external rules](https://cloud.githubusercontent.com/assets/3708504/12615868/68a13ae8-c508-11e5-90d3-a6681e7ed4c1.png)

**Comment by jmecosta** [comment]
Yes you have the rules but are they enabled in the quality profile. It's
not enough to add the XML to the web. You need to restart the server and
then enable them in the profile

**Comment by guwirth** [comment]
@GosuKapu is this issue solved? Can we close it?

**Comment by GosuKapu** [comment]
Ye, please close it.
