### ISSUE TITLE
Support documentation API check on subset of files

### ISSUE THREAD

**Issue by LegalizeAdulthood** [SonarOpenCommunity/sonar-cxx#770]
We have a large source tree with a chunk of the source tree including header files for an SDK that we publish to customers.  I'd like to focus the documentation metrics on the SDK header files, but currently the metric is gathered on the entire tree.

Provide a way for me to focus the API documentation metric on a subset of files, with your typical inclusion/exclusion filter mechanism.

Another motivation for this is that you might include 3rd party libraries in your source tree and you don't want the API metric to be recorded for 3rd party files.

**Comment by guwirth** [comment]
Without testing: my expectation is that the sensor is taking only files inside the project into account. If you are excluding source files they are also not imported and counted. So I don't really understand your point?

**Comment by LegalizeAdulthood** [comment]
As I mentioned in the original description, we have a large source tree of which a subset is a set of public headers for an SDK.  I only care about documentation on the SDK headers, not the entire tree.

**Comment by guwirth** [comment]
Why do you not create an own project/view for the SDK only?
