### ISSUE TITLE
Does this plugin support C too?

### ISSUE THREAD

**Issue by davewichers** [SonarOpenCommunity/sonar-cxx#772]
Given that C++ is a superset of C, if was hoping it does, but wanted to check.
 
And if there is project introduction or FAQ, it might be helpful to include the answer to this question there as well, for others to see.

Thanks, Dave

**Comment by guwirth** [comment]
* should normally work with C. Think you have to set `sonar.cxx.cFilesPatterns`, see https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties
* read also: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces
