### ISSUE TITLE
environment variables are not working in multi-module projects

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#773]
Support environment are not working in multi-module projects:
* leftover from: **Support environment variables and system properties in configuration files** #716

**Comment by jmecosta** [comment]
@guwirth can be closed.

**Comment by guwirth** [comment]
@jmecosta why? Is it working now?

**Comment by jmecosta** [comment]
tough so, #777 was not handling all possible cases. did you disable some it because of this? dont remember anymore

**Comment by jmecosta** [comment]
ok this was about the vars being not replaced, its likely still broken
