### ISSUE TITLE
Cannot find reports with relative Ant globbing

### ISSUE THREAD

**Issue by mjdetullio** [SonarOpenCommunity/sonar-cxx#775]
Environment:
- SQ 5.3
- 2ba787e23cb791a414391150fa269b45fa38e454 (latest from master at time of writing)
- Multi-module project

This multi-module project is analyzed using the SQ Gradle Scanner.  When all said and done, the settings end up looking something like this:

```
sonar.modules=module1,module2
...
module2.sonar.sources=dir1,dir2,dir3,dir4
module2.sonar.exclusions=**/build/**,**/cppcheck.xml
module2.sonar.cxx.cppcheck.reportPath=**/cppcheck.xml
```

The reports most certainly exist in the tree (and they have correct ownership and 0644 perms):

```
$ find . -name cppcheck.xml
./module2/dir1/build/cppcheck.xml
./module2/dir2/cppcheck.xml
./module2/dir3/build/cppcheck.xml
./module2/dir4/build/cppcheck.xml
```

But here's what I get in the analysis:

```
-------------  Scan module2
Base dir: /path/to/project/module2
Working dir: /path/to/project/build/sonar/com.mycompany.project_module2
Source paths: dir1, dir2, dir3, dir4
Source encoding: ISO-8859-1, default locale: en_US
Index files
Excluded sources: 
  */build/**
  **/cppcheck.xml
82 files indexed
...
omitted for brevity
...
Sensor CxxCppCheckSensor
Using pattern '**/cppcheck.xml' to find reports
Unprocessed root directory '/path/to/project/module2'
Unprocessed report file '**/cppcheck.xml'
Processed root directory '/path/to/project/module2'
Processed report file '**/cppcheck.xml'
Cannot find a report for 'sonar.cxx.cppcheck.reportPath=**/cppcheck.xml'
Sensor CxxCppCheckSensor (done) | time=29ms
```

As you can see, the property makes its way to the sensor correctly but something goes wrong when actually searching for the files.  There are no exceptions when walking the tree.  I don't know exactly where the problem in the code is without attaching a debugger, but it's within this stack: https://github.com/SonarOpenCommunity/sonar-cxx/blob/2ba787e23cb791a414391150fa269b45fa38e454/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/utils/CxxUtils.java#L119 with ```CxxFileFinder.FindFiles``` turning up an empty Collection.

**Comment by jmecosta** [comment]
Hi

This has been heavily refactored in this version so there might be
something still not working. Could you run with debug info on so we can
check what the lookup printing looks like.

**Comment by mjdetullio** [comment]
The provided logs are the extent of the debug logs for the sensor.

**Comment by jmecosta** [comment]
Ok, This should be supported indeed, ** turns the scanner into a recursive scanner so it should have found the reports. We need to check the it test again
