### ISSUE TITLE
c++ keywords not defined (e.g. and, or, ...)

### ISSUE THREAD

**Issue by schroeca** [SonarOpenCommunity/sonar-cxx#778]
c++ keywords can not be used in source file --> leads to an parser error

**This will crash:**

``` c++
void test()
{
    if (a == 3 and b == 5)
    {

    }
}
```

**This will work:**

``` c++
void test()
{
    if (a == 3 && b == 5)
    {

    }
}
```

**Comment by guwirth** [comment]
@schroeca yes not supported yet
possible workarround `#define and &&`

**Comment by guwirth** [comment]
Link to description: https://en.m.wikipedia.org/wiki/Operators_in_C_and_C%2B%2B#C.2B.2B_operator_synonyms.
This link sounds more like a preprocessor extension? Maybe we have to double check with standard.

**Comment by guwirth** [comment]
There are two possibilities to solve this:
* force include a header file with the defines like iso646.h https://en.m.wikipedia.org/wiki/C_alternative_tokens
* add it to preprocessor as predefined macros

What are you thinking?

**Comment by schroeca** [comment]
I will include the iso646.h. That seems to be the easiest solution on this.

Thx

**Comment by lcintrat** [comment]
While working on #761, I saw that `override` is not part of `CxxKeyword` too.

**Comment by guwirth** [comment]
For override and final see https://github.com/SonarOpenCommunity/sonar-cxx/pull/675

**Comment by lcintrat** [comment]
Oh ok, good to know !

**Comment by guwirth** [comment]
Solution is to use `iso646.h` header file.
