### ISSUE TITLE
error evaluating expression

### ISSUE THREAD

**Issue by schroeca** [SonarOpenCommunity/sonar-cxx#779]
I tried to analyze my systemc source code with your current master code.

it seems that the preprocessor has some issue with the boost lib used in systemc-2.3.1

https://github.com/aseemm/Accellera-SystemC/search?utf8=%E2%9C%93&q=SC_BOOST_WORKAROUND

```
15:00:15.200 WARN  - Error evaluating expression '( ( __MWERKS__ != 0 ) && ( 1 % ( ( ( __MWERKS__ SC_BOOST_TESTED_AT ( 0x3202 ) ) ) + 1 ) ) )' for AstExp 'IDENTIFIER: SC_BOOST_WORKAROUND', assuming 0
```

I was not able to find any further information by debugging or using sslr-toolkit.

**Comment by guwirth** [comment]
@schroeca are you able to provide a small sample to reproduce the problem?

**Comment by schroeca** [comment]
I tried to create a short example but it is not that easy.
The easiest way would be to copy the SC_BOOST_WORKAROUND defines in a seperate file.

For me that worked and i was able to create to same behaviour

**Comment by guwirth** [comment]
There was already a fix for BOOST_WORKAROUND see https://github.com/SonarOpenCommunity/sonar-cxx/pull/422. Don't know what is different? Which version of boost are you using?

**Comment by schroeca** [comment]
I do not understand the solution of issue #422. Do I have to set some defines?

**Comment by guwirth** [comment]
Please reopen if still an issue.
