### ISSUE TITLE
stop analysis at specific hierarchy level

### ISSUE THREAD

**Issue by schroeca** [SonarOpenCommunity/sonar-cxx#781]
Is it possible to stop analysis of source code which is not within my project (external libs, ...)

**Comment by guwirth** [comment]
@schroeca stop is not possible
* but you can narrow the focus http://docs.sonarqube.org/plugins/servlet/mobile#content/view/6951775
* `sonar.exclusions` property to exclude source code files
* files outside of root are anyway ignored
