### ISSUE TITLE
 trying to get c++ pc-lint reports into sonar

### ISSUE THREAD

**Issue by hemalbavisi** [SonarOpenCommunity/sonar-cxx#782]
*My Configuration:*
* FlexLint Version 9.0
* SonarQube Version 5.3
* sonar-cxx-plugin 0.94
* sonar-runner 2.3

I have only the profile "Sonar Way" (C++) and manually activated all the rules that are applicable for PC-Lint. I have provided all the output for your reference. It would be great if you can provide quick support regarding this. 

Output of lint.xml
`<?xml version="1.0" ?>
<results>
<message><file>.\lib\mylib.h</file> <line>1</line> <type>Note</type> <code>9026</code> <desc>Function-like macro, 'ADD', defined [MISRA 2012 Directive 4.9, advisory]</desc></message>
<message><file>.\src\main.c</file> <line>10</line> <type>Note</type> <code>9075</code> <desc>external symbol 'main(void)' defined without a prior declaration [MISRA 2012 Rule 8.4, required]</desc></message>
<message><file>.\src\main.c</file> <line>20</line> <type>Note</type> <code>9016</code> <desc>pointer arithmetic other than array indexing used [MISRA 2012 Rule 18.4, advisory]</desc></message>
<message><file>.\src\main.c</file> <line>20</line> <type>Warning</type> <code>416</code> <desc>Likely creation of out-of-bounds pointer (12 beyond end of data) by operator 'ptr+int' [Reference: file .\src\main.c: lines 15, 18, 20] [MISRA 2012 Rule 1.3, required], [MISRA 2012 Rule 18.1, required]</desc></message>
<message><file>.\src\main.c</file> <line>15</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>18</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>20</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>21</line> <type>Warning</type> <code>415</code> <desc>Likely access of out-of-bounds pointer (12 beyond end of data) by operator 'unary *' [Reference: file .\src\main.c: lines 15, 18, 20] [MISRA 2012 Rule 1.3, required], [MISRA 2012 Rule 18.1, required]</desc></message>
<message><file>.\src\main.c</file> <line>15</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>18</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>20</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>23</line> <type>Warning</type> <code>415</code> <desc>Likely access of out-of-bounds pointer (12 beyond end of data) by operator 'unary *' [Reference: file .\src\main.c: lines 15, 18, 20] [MISRA 2012 Rule 1.3, required], [MISRA 2012 Rule 18.1, required]</desc></message>
<message><file>.\src\main.c</file> <line>15</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>18</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>20</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>24</line> <type>Note</type> <code>9029</code> <desc>Mismatched essential type categories for binary operator [MISRA 2012 Rule 10.4, required]</desc></message>
<message><file>.\src\main.c</file> <line>24</line> <type>Note</type> <code>9029</code> <desc>Mismatched essential type categories for binary operator [MISRA 2012 Rule 10.4, required]</desc></message>
<message><file>.\src\main.c</file> <line>24</line> <type>Info</type> <code>845</code> <desc>The left argument to operator '&amp;&amp;' is certain to be 0 [Reference: file .\src\main.c: lines 11, 24]</desc></message>
<message><file>.\src\main.c</file> <line>11</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>24</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>24</line> <type>Info</type> <code>774</code> <desc>Boolean within 'if' always evaluates to False [Reference: file .\src\main.c: lines 11, 24] [MISRA 2012 Rule 14.3, required]</desc></message>
<message><file>.\src\main.c</file> <line>11</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>24</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>30</line> <type>Info</type> <code>801</code> <desc>Use of goto is deprecated [MISRA 2012 Rule 15.1, advisory]</desc></message>
<message><file>.\src\main.c</file> <line>31</line> <type>Warning</type> <code>415</code> <desc>Likely access of out-of-bounds pointer (12 beyond end of data) by operator 'unary *' [Reference: file .\src\main.c: lines 15, 18, 20] [MISRA 2012 Rule 1.3, required], [MISRA 2012 Rule 18.1, required]</desc></message>
<message><file>.\src\main.c</file> <line>15</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>18</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>20</line> <type>Info</type> <code>831</code> <desc>Reference cited in prior message</desc></message>
<message><file>.\src\main.c</file> <line>9</line> <type>Note</type> <code>9003</code> <desc>could define variable 'test' (line 9, file .\src\main.c) at block scope [MISRA 2012 Rule 8.9, advisory]</desc></message>
</results>
`
Project Properties
`sonar.sourceEncoding=UTF-8

sonar.cxx.compiler.parser=GCC
sonar.cxx.compiler.reportPath=*.log
sonar.cxx.compiler.charset=UTF-8
sonar.cxx.compiler.regex=^(.*):([0-9]+):[0-9]+: warning: (.*)\\[(.*)\\]$

sonar.cxx.includeDirectories = lib, C:/MinGW/include, C:/MinGW/lib/gcc/mingw32/4.8.1/include
sonar.cxx.suffixes.sources = .c
sonar.cxx.suffixes.headers = .h
sonar.cxx.cFilesPatterns = *.c, *.C
sonar.cxx.pclint.reportPath = lint.xml
sonar.cxx.cppcheck.reportPath =report.xml`

Sonarqube build script output 
`Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.
REMOVE PREVIOUS BUILD
PCLINT
CHECKER
Checking src\main.c...
BUILDING
BUILD SUCCESS
INFO: Scanner configuration file: c:\sonar-scanner\conf\sonar-runner.properties
INFO: Project configuration file: c:\sonar-examples\projects\languages\c\c-sonar-runner\sonar-project.properties
INFO: SonarQube Scanner 2.5
INFO: Java 1.8.0_74 Oracle Corporation (32-bit)
INFO: Windows 8.1 6.3 x86
INFO: Error stacktraces are turned on.
DEBUG: cache: C:\Users\hemal_bavishi.AVINS\.sonar\ws_cache\http%3A%2F%2Flocalhost%3A9000\global
INFO: User cache: C:\Users\hemal_bavishi.AVINS\.sonar\cache
DEBUG: Extract sonar-runner-batch in temp...
DEBUG: Get bootstrap index...
DEBUG: Download: http://localhost:9000/batch_bootstrap/index
DEBUG: Get bootstrap completed
DEBUG: Create isolated classloader...
DEBUG: Start temp cleaning...
DEBUG: Temp cleaning done
DEBUG: Execution getVersion
DEBUG: Execution start
DEBUG: Publish global mode
DEBUG: cache: C:\Users\hemal_bavishi.AVINS\.sonar\ws_cache\http%3A%2F%2Flocalhost%3A9000\global
INFO: Load global repositories
DEBUG: GET 200 http://localhost:9000/batch/global | time=78ms
INFO: Load global repositories (done) | time=141ms
INFO: User cache: C:\Users\hemal_bavishi.AVINS\.sonar\cache
INFO: Load plugins index
DEBUG: GET 200 http://localhost:9000/deploy/plugins/index.txt | time=0ms
INFO: Load plugins index (done) | time=16ms
DEBUG: Load plugins
DEBUG: Load plugins (done) | time=16ms
DEBUG: API compatibility mode is enabled on plugin Redmine [redmine] (built with API lower than 5.2)
DEBUG: API compatibility mode is enabled on plugin C++ (Community) [cxx] (built with API lower than 5.2)
DEBUG: API compatibility mode is enabled on plugin Java [java] (built with API lower than 5.2)
DEBUG: API compatibility mode is enabled on plugin Git [scmgit] (built with API lower than 5.2)
DEBUG: API compatibility mode is enabled on plugin Checkstyle [checkstyle] (built with API lower than 5.2)
DEBUG: API compatibility mode is enabled on plugin SVN [scmsvn] (built with API lower than 5.2)
DEBUG: Plugins:
DEBUG:   * Redmine 0.2 (redmine)
DEBUG:   * C++ (Community) 0.9.4 (cxx)
DEBUG:   * Java 3.10 (java)
DEBUG:   * Git 1.1 (scmgit)
DEBUG:   * Checkstyle 2.4 (checkstyle)
DEBUG:   * SVN 1.2 (scmsvn)
INFO: Default locale: "en_GB", source code encoding: "UTF-8"
DEBUG: Work directory: C:\sonar-examples\projects\languages\c\c-sonar-runner\.sonar
DEBUG: Execution getVersion
DEBUG: Execution execute
INFO: Process project properties
DEBUG: Process project properties (done) | time=0ms
DEBUG: cache: C:\Users\hemal_bavishi.AVINS\.sonar\ws_cache\http%3A%2F%2Flocalhost%3A9000\5.3\projects\org.sonarqube%3Ac-simple-sq-scanner
INFO: Load project repositories
DEBUG: GET 200 http://localhost:9000/batch/project.protobuf?key=org.sonarqube%3Ac-simple-sq-scanner | time=31ms
INFO: Load project repositories (done) | time=110ms
INFO: Apply project exclusions
DEBUG: Available languages:
DEBUG:   * c++ => "c++"
DEBUG:   * Java => "java"
INFO: Load quality profiles
DEBUG: GET 200 http://localhost:9000/api/qualityprofiles/search.protobuf?projectKey=org.sonarqube%3Ac-simple-sq-scanner | time=31ms
INFO: Load quality profiles (done) | time=47ms
INFO: Load active rules
DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=c%2B%2B-avin_c-37405&p=1&ps=500 | time=484ms
DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=c%2B%2B-avin_c-37405&p=2&ps=500 | time=437ms
DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=c%2B%2B-avin_c-37405&p=3&ps=500 | time=406ms
DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=c%2B%2B-avin_c-37405&p=4&ps=500 | time=375ms
DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=c%2B%2B-avin_c-37405&p=5&ps=500 | time=235ms
DEBUG: GET 200 http://localhost:9000/api/rules/search.protobuf?f=repo,name,severity,lang,internalKey,templateKey,params,actives&activation=true&qprofile=java-sonar-way-68517&p=1&ps=500 | time=204ms
INFO: Load active rules (done) | time=2265ms
INFO: SCM provider autodetection failed. No SCM provider claims to support this project. Please use sonar.scm.provider to define SCM of your project.
INFO: Publish mode
DEBUG: Start recursive analysis of project modules
INFO: -------------  Scan C :: Simple Project :: SonarQube Scanner
INFO: Language is forced to c++
INFO: Load server rules
DEBUG: GET 200 http://localhost:9000/api/rules/list.protobuf | time=375ms
INFO: Load server rules (done) | time=417ms
DEBUG: Initializers :
INFO: Base dir: C:\sonar-examples\projects\languages\c\c-sonar-runner
INFO: Working dir: C:\sonar-examples\projects\languages\c\c-sonar-runner\.sonar
INFO: Source paths: src
INFO: Source encoding: UTF-8, default locale: en_GB
INFO: Index files
DEBUG: Declared extensions of language c++ were converted to sonar.lang.patterns.c++ : **/*.c,**/*.h
DEBUG: Declared extensions of language Java were converted to sonar.lang.patterns.java : **/*.java,**/*.jav
DEBUG: Language of file 'src/main.c' is detected to be 'c++'
INFO: 1 files indexed
INFO: Quality profile for c++: AVIN_C
INFO: Redmine issues sensor will not run as some parameters are missing.
INFO: JaCoCoSensor: JaCoCo report not found : C:\sonar-examples\projects\languages\c\c-sonar-runner\target\jacoco.exec
INFO: JaCoCoItSensor: JaCoCo IT report not found: C:\sonar-examples\projects\languages\c\c-sonar-runner\target\jacoco-it.exec
DEBUG: Code colorizer, supported languages: c++
DEBUG: Sensors : Lines Sensor (wrapped) -> QProfileSensor -> CxxSquidSensor -> CxxCoverageSensor -> CxxCppCheckSensor -> CxxPCLintSensor -> CxxCompilerSensor -> SCM Sensor (wrapped) -> Code Colorizer Sensor (wrapped) -> CPD Sensor (wrapped)
INFO: Sensor Lines Sensor (wrapped)
INFO: Sensor Lines Sensor (wrapped) (done) | time=0ms
INFO: Sensor QProfileSensor
INFO: Sensor QProfileSensor (done) | time=16ms
INFO: Sensor CxxSquidSensor
DEBUG: Using pattern '*.log' to find reports
DEBUG: Parse build log  file 'C:\sonar-examples\projects\languages\c\c-sonar-runner\log.log'
DEBUG: Parse build log OK: includes: '1' defines: '1'
DEBUG: storing include root: 'C:\sonar-examples\projects\languages\c\c-sonar-runner\lib'
DEBUG: storing include root: 'C:\MinGW\include'
DEBUG: storing include root: 'C:\MinGW\lib\gcc\mingw32\4.8.1\include'
DEBUG: [C:\sonar-examples\projects\languages\c\c-sonar-runner\src\main.c:3]: processing #include <mylib.h>, resolved to file 'C:\sonar-examples\projects\languages\c\c-sonar-runner\lib\mylib.h'
DEBUG: finished preprocessing 'C:\sonar-examples\projects\languages\c\c-sonar-runner\src\main.c'
DEBUG: Metric lines is an internal metric computed by SonarQube. Provided value is ignored.
DEBUG: Skipping dependency to file 'mylib.h', because it is'nt part of this project
INFO: Directory: 'src' Cycles:0 Feedback cycles:0 Tangles:0 Weight:0.0
INFO: Project 'org.sonarqube:c-simple-sq-scanner' Cycles:0 Feedback cycles:0 Tangles:0 Weight:0.0
INFO: Sensor CxxSquidSensor (done) | time=219ms
INFO: Sensor CxxCoverageSensor
DEBUG: Zeroing coverage information for untouched files
INFO: Sensor CxxCoverageSensor (done) | time=0ms
INFO: Sensor CxxCppCheckSensor
INFO: Processing report 'report.xml'
INFO: Parsing 'Cppcheck V2' format
INFO: Added report 'report.xml' (parsed by: CppcheckParserV2)
INFO: CppCheck Errors processed = 0
INFO: Sensor CxxCppCheckSensor (done) | time=93ms
INFO: Sensor CxxPCLintSensor
INFO: Processing report 'lint.xml'
INFO: Parsing 'PC-Lint' format
INFO: PC-Lint errors processed = 0
INFO: Sensor CxxPCLintSensor (done) | time=16ms
INFO: Sensor CxxCompilerSensor
DEBUG: Using pattern '*.log' to find reports
INFO: Processing report 'C:\sonar-examples\projects\languages\c\c-sonar-runner\log.log'
INFO: Scanner 'GCC' initialized with report 'C:\sonar-examples\projects\languages\c\c-sonar-runner\log.log', CharSet= 'UTF-8'
INFO: Parsing 'GCC' format
DEBUG: Using pattern : '^(.*):([0-9]+):[0-9]+: warning: (.*)\[(.*)\]$'
INFO: C++ compiler Warnings processed = 0
INFO: Sensor CxxCompilerSensor (done) | time=0ms
INFO: Sensor SCM Sensor (wrapped)
INFO: No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
INFO: Sensor SCM Sensor (wrapped) (done) | time=0ms
INFO: Sensor Code Colorizer Sensor (wrapped)
INFO: Sensor Code Colorizer Sensor (wrapped) (done) | time=16ms
INFO: Sensor CPD Sensor (wrapped)
INFO: DefaultCpdEngine is used for c++
DEBUG: Populating index from [moduleKey=org.sonarqube:c-simple-sq-scanner, relative=src/main.c, basedir=C:\sonar-examples\projects\languages\c\c-sonar-runner]
DEBUG: Detection of duplications for [moduleKey=org.sonarqube:c-simple-sq-scanner, relative=src/main.c, basedir=C:\sonar-examples\projects\languages\c\c-sonar-runner]
INFO: Sensor CPD Sensor (wrapped) (done) | time=31ms
INFO: Analysis report generated in 47ms, dir size=64 KB
INFO: Analysis reports compressed in 15ms, zip size=18 KB
DEBUG: Upload report
DEBUG: POST 200 http://localhost:9000/api/ce/submit?projectKey=org.sonarqube:c-simple-sq-scanner&projectName=C%20::%20Simple%20Project%20::%20SonarQube%20Scanner | time=47ms
INFO: Analysis report uploaded in 47ms
INFO: ANALYSIS SUCCESSFUL, you can browse http://localhost:9000/dashboard/index/org.sonarqube:c-simple-sq-scanner
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at http://localhost:9000/api/ce/task?id=AVLz58ziexSFfHl6Cnvd
DEBUG: Report metadata written to C:\sonar-examples\projects\languages\c\c-sonar-runner\.sonar\report-task.txt
DEBUG: Post-jobs :
INFO: Analysis report generated in C:\sonar-examples\projects\languages\c\c-sonar-runner\.sonar\batch-report
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 6.756s
INFO: Final Memory: 43M/113M
INFO: ------------------------------------------------------------------------
DEBUG: Execution getVersion
DEBUG: Execution stop 
`

**Comment by guwirth** [comment]
@hemalbavisi
* please try to turn debug info on to get more information https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information
* try to set `sonar.sources`
* paths in report are relative, maybe using wrong baseDir https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues
* for testing you can also try with absolute paths

**Comment by hemalbavisi** [comment]
Thanks for your help! I am now able to see list of issues generated by PC-Lint on local host.
