### ISSUE TITLE
Custom cppcheck issue is not shown in Sonarqube

### ISSUE THREAD

**Issue by Ipod12321** [SonarOpenCommunity/sonar-cxx#786]
This is the code i am analysing.
`
ETRACE(foo,bar);
int i;
// some comment
`

I added this custom rule to the cppcheck.
`<?xml version="1.0"?>
<rule version="1.0">
 <pattern>(ETRACE)</pattern>
 <message>
 <id>DONOTUSE</id>
 <severity>error</severity>
 <summary>The ETRACE function should not be used anymore</summary>
 </message>
</rule>
`

Thats the report i get it looks lika any other cppcheck issue
`
<?xml version="1.0" encoding="UTF-8"?>
-<results version="2">
<cppcheck version="1.66"/>
-<errors>
-<error verbose="The ETRACE function should not be used anymore" msg="The ETRACE function should not be used anymore" severity="error" id="DONOTUSE">
<location line="22" file="projectDirectory\Code.cpp"/>
</error>
</errors>
</results>
`

The problem is that the plugin doesnt show this issue in the Sonarqube gui even its in the report file. Is there a reason why this custom issue isnt shown.

**Comment by jmecosta** [comment]
And the rule is enabled after you restart the server

**Comment by Ipod12321** [comment]
No the rule is not even shown i cannot  add it into the quality profile

**Comment by jmecosta** [comment]
You need to restart the server to make the rules effective

**Comment by Ipod12321** [comment]
i did restarted the server more than once but the rule doesnt show up

**Comment by jmecosta** [comment]
Ok, so what version of the plugin are you using.?

**Comment by Ipod12321** [comment]
i use version 0.9.4 of the plugin and sonarqube version 4.5.6
Do i have to link the xml file with the rule somewhere because if  i changed this key 
<sonar.cxx.cppcheck.customRules>
nothing changed

**Comment by jmecosta** [comment]
Seems you are not using the correct format, check the wiki sections extending code analysis

**Comment by Ipod12321** [comment]
i am using the format thats required for cppcheck

**Comment by jmecosta** [comment]
Cppcheck!? You need to use the format that we defined?

**Comment by Ipod12321** [comment]
Why ?

**Comment by Ipod12321** [comment]
If i use your format cppcheck cannot find the issues and in your format i cannot define a regex

**Comment by jmecosta** [comment]
Try

**Comment by Ipod12321** [comment]
Where do i have to enter the regex then ?

**Comment by jmecosta** [comment]
These should not be any reger,

**Comment by Ipod12321** [comment]
How am i able to say for example the developers should not use Etrace() if not with a regex

**Comment by jmecosta** [comment]
What cppcheck do you use. The plugin has no logic like that, you run cppcheck outside as you want and feed the report back, if the report is having the correct xml format then the issues should appear in dashboard

**Comment by Ipod12321** [comment]
i am using cppcheck version 1.66

**Comment by Ipod12321** [comment]
the strange thing is that the report has the correct xml format but the issue does not appear in the dashboard

**Comment by jmecosta** [comment]
You don't have the rule in the profile, again you need to follow the wiki
and define the external rules there. Restart the server and enable the
rule. After that they should appear

**Comment by Ipod12321** [comment]
i did everything like in the wiki

**Comment by Ipod12321** [comment]
![image](https://cloud.githubusercontent.com/assets/17431198/13256600/a58c8978-da4b-11e5-86d6-0e748eabc7d1.png)

**Comment by jmecosta** [comment]
No you did not, the format is not correct.  Check the wiki for the correct
format

**Comment by Ipod12321** [comment]
![image](https://cloud.githubusercontent.com/assets/17431198/13256743/338a66d2-da4c-11e5-93ed-60a454e197f8.png)
like this

**Comment by jmecosta** [comment]
Yep thats better

**Comment by Ipod12321** [comment]
wait a moment

**Comment by Ipod12321** [comment]
Just a quick note there in the wiki the description field is optional but if you dont have a description the sonar qube server wont start. You should move this to the required fields
<description>
       <![CDATA[The description]]>
     </description>

**Comment by jmecosta** [comment]
done. thanks
