### ISSUE TITLE
Is there a sonar.cxx.maxWait directive to increased the Sonar runner analysis time to avoid timeout?

### ISSUE THREAD

**Issue by raingod800** [SonarOpenCommunity/sonar-cxx#787]
Dear All,

I am trying to run sonar runner on my project. When I include only a few modules, it runs fine, but when I include the whole project (4 million lines), it leads to sonar runner timing out. IT is also because a number of files have more than 100 duplicates, so takes time for analysis.

We see this:

Sensor CPD Sensor (done) | time=41291ms
INFO: Analysis report generated in 62129ms, dir size=304 MB
INFO: Analysis reports compressed in 29239ms, zip size=69 MB
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 10:56.092s
INFO: Final Memory: 157M/3033M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: Fail to request http://localhost:9000/api/ce/submit?projectKey=org.CxxPlugin:LTE&projectName=C%20::%20LTE%20::%20All%20Code
ERROR: Caused by: Read timed out

I tried this:
sonar.cxx.maxWait=300000

But it doesn't seem to work unfortunately. IS there a way for me to increase the timeout to allow the analysis to continue for longer please?

Also, is there a way for me to capture the sonar runner output to analyse it? i would like to understand which files have timeouts.  Is there a log file which is created or can be created capturing all the output? As the amount of output is huge, i can't use the command window to scroll all the output

Many thanks!
Kind Regards,
Gaurav

**Comment by guwirth** [comment]
Hi,

Which version of SonarQube and the plugin are you using?

Regards

**Comment by raingod800** [comment]
Sonarqube version is 5.3 and plug-in version is 0.9.4 please

Thanks for your help
Kind Regards,
Gaurav

**Comment by guwirth** [comment]
Hi,

with SQ 5.3 the analysis is running on server side. The files are transferred to the server. Do you think timeout is on server or on local side?

Regards

**Comment by raingod800** [comment]
I am running everything locally currently on my machine, server is running
on one command window and I am running sonar-runner.bat on the other
command window.

I think due to sheer number of files, it times out as it passes if i reduce
the number of modules i give in one go.

So i was wondering if I can increase this timeout so that sonar-runner can
run longer please

Thanks for your help,
Kind Regards,
Gaurav

**Comment by guwirth** [comment]
Hi,

I never had this issue. But maybe you can look here:

* sonar.ws.timeout http://docs.sonarqube.org/plugins/servlet/mobile#content/view/6951296
* http://sonarqube-archive.15.x6.nabble.com/Sonar-5-1-Timeout-error-td5034655.html
* conf/sonar.properties sonar.jdbc.maxWait

Regards
