### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by zabettina** [SonarOpenCommunity/sonar-cxx#792]
What about a new official release, e.g. a compatible release for SonarQube 5.3?
The last release was 0.9.4 for SonarQube 5.1.2 last October.
I really would like to update my SonarQube, but only if this plugin is working together with it.
If I build from source code now, will it work with 5.3?
Cheers
Bettina

**Comment by jmecosta** [comment]
hi,

you dont need to build, just get the last snapshot build from: https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts 

it is compatible with 5.3. 
jc

**Comment by zabettina** [comment]
Thank you Jorge, that's good to know.
Bettina

**Comment by jmecosta** [comment]
no problem, i think we should be almost ready for a new release. so hopefully it will not be long. i will close this, since the release should be tracked in another issue
