### ISSUE TITLE
Support CWE ids from cppcheck 

### ISSUE THREAD

**Issue by amai2012** [SonarOpenCommunity/sonar-cxx#794]
Upcoming version cppcheck 1.73 is going to support mapping of it's messages to CWE Ids (https://cwe.mitre.org/). The error messages in XML format 2 got a new attributes _cwe_ accordingly.
Can those be displayed by Sonar?

**Comment by jmecosta** [comment]
probably a good idea to use tags? the current rule xml definition can be
augmented to include tags, and when new rules are created that related with
CWE than tag is automatically generated?

**Comment by Bertk** [comment]
I will prepare a PR with the modified rules
- add CWE tag
- add CWE details to rule
- add CWE URL to rule
We did this for other rule repositories already.

**Comment by Bertk** [comment]
Please check PR #797

**Comment by guwirth** [comment]
Solved with #797

**Comment by amai2012** [comment]
Thanks for implementing this quickly!
