### ISSUE TITLE
naming convention for functions should ignore name of class

### ISSUE THREAD

**Issue by jmecosta** [SonarOpenCommunity/sonar-cxx#795]
should we ignore the name of the class in function names?
![image](https://cloud.githubusercontent.com/assets/1041352/13506736/370baed6-e188-11e5-90bf-187e51341a83.png)

**Comment by jmecosta** [comment]
yep this is a bug, when i run in debug it raises issues against className because in this case that the first getFirstAncestor. i will prepare pr request

**Comment by jmecosta** [comment]
@guwirth actually i am not sure about this. when i look at the ast in the toolkit the function name comes up has className so probably somehting wrong in the grammar?

![image](https://cloud.githubusercontent.com/assets/1041352/13520361/5597f444-e1e8-11e5-8482-6e3ad3c2379d.png)

**Comment by jmecosta** [comment]
@guwirth ok, so i think the issue is that it sees 
void MyClass::too_long_function_name_because_it_has_more_than_30_characters_2() {} as a function. however this is a method and should only be checked by the MethodCheckClass?

**Comment by jmecosta** [comment]
#796 add pr to show the issue

**Comment by guwirth** [comment]
@jmecosta there is MethodCheckClass and FunctionNameCheck:
 Both should check without namespace and class names => last part behind last :

**Comment by jmecosta** [comment]
@guwirth but they should also check and ignore those right? Can you check the tests in pr #796 to see what you think.

**Comment by guwirth** [comment]
@jmecosta please try #798

**Comment by jmecosta** [comment]
@guwirth most of the things are ok. only one case remains. 

the constructors of class should not be checked against methodName since they should follow the class name instead.

other than its its good

**Comment by guwirth** [comment]
@jmecosta I'm aware that the solution is not perfect. But we are doing only a syntax check and no semantic test. Detecting a ctor or dtor especially if outside of class it's a little bit more complicated. Maybe someone has time to do this?

remaining #800

**Comment by jmecosta** [comment]
thought the solution was easier to do then that, anyway thanks for the other fix.
