### ISSUE TITLE
Copyright year change causes failure of cxx:FileHeader

### ISSUE THREAD

**Issue by netnode** [SonarOpenCommunity/sonar-cxx#802]
Having the cxx:FileHeader rule use a fixed template is causing us isses where different source files have different copyright formats.

E.G.
Copyright 2016
Copyright 2014, 2016
Copyright 2012 - 2014

Would it be possable to make this template a regular expression so these date changes could be made configurable?

**Comment by guwirth** [comment]
Maybe you can use https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/FileRegularExpressionCheck.java or https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/LineRegularExpressionCheck.java instead.

**Comment by netnode** [comment]
Cheers, I'll take a look at them.
Looks like the Java version of this check was updated to allow regular expressions I've just found.
https://jira.sonarsource.com/browse/SONARJAVA-656

**Comment by guwirth** [comment]
Request to support regular expressions in https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/FileHeaderCheck.java

**Comment by Bertk** [comment]
I prepared a solution for this issue already (76933d52ba69b000aa0a288c685b80b08400cd9e) and prepare the PR after some tests are done.

**Comment by Bertk** [comment]
solved with #807.
