### ISSUE TITLE
Standard headers

### ISSUE THREAD

**Issue by netnode** [SonarOpenCommunity/sonar-cxx#803]
I'm parsing a medium sized c project and have followed the advise about not passing sonarqube the paths to the c standard header since it has knowledge of them built in.  

However it's creating issues against not being able to find them and I can not find a way to suppress the cxx:MissingIncludeFile to ignore just these standard c headers.

I want to keep the rule enabled so I find other parsing issues but not have the issues raised for these standard headers.  Should I be including the path to them in the sonar.cxx.includeDirectories?

**Comment by guwirth** [comment]
Currently there is always a message if check MissingIncludeFile is not able to find a header file. As far as I know there is no possibility to suppress this. 

> Should I be including the path to them in the sonar.cxx.includeDirectories?

You can try but analysis could be slower then.
