### ISSUE TITLE
Start release procedure for cxx plugin 0.9.5 (SQ5.3 and SQ5.4 support) 

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#805]
Hi everyone,

We like to start the [release procedure](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Release-Procedure) for cxx plugin 0.9.5. Besides many [fixes and enhancements](https://github.com/SonarOpenCommunity/sonar-cxx/issues?q=is%3Aissue+milestone%3A%22M+0.9.5%22+is%3Aclosed) main focus is the SQ5.3 and SQ5.4 support. There are still some [open issues](https://github.com/SonarOpenCommunity/sonar-cxx/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22M+0.9.5%22). Please support us to close them before next release.

As usual we start with a release candidate (RC1)  and keep it for testing a week. RC1 will be available tomorrow morning (2016-03-14).

Regards,

**Comment by guwirth** [comment]
@all: thanks for your updates yesterday
@jmecosta could you attach the binaries to the release please.

**Comment by jmecosta** [comment]
@guwirth do we need to upgrade the version from snapshot to rc? or its just a small thing

**Comment by jmecosta** [comment]
@guwirth its best, ive update the versions in pom.xml. Now it become RC2, so its not messed up with a already existing tag

**Comment by guwirth** [comment]
@all please test cxx pluging [v0.9.5-RC2](https://github.com/SonarOpenCommunity/sonar-cxx/releases) and give us feedback.
We will close testing period next Sunday.

**Comment by jmecosta** [comment]
@guwirth try to play with https://github.com/GitTools/GitReleaseManager to get automatic release notes, and the tool is failing because the labels are applied a bit like randomly, mostly the question are not supposed to be included in the 0.9.5?

i would propose the each issue that is in 0.9.4 has at least one of the follwoing labels:
bug
enhancement
documentation

if not applicable then they should removed from the millestone

this should save a bit of time creating the release notes.

**Comment by guwirth** [comment]
Still think we should spend the time to create the release notes manually. Most of the issues have no speaking captions.

**Comment by jmecosta** [comment]
Ok in that case this makes no difference.  never mind then

**Comment by guwirth** [comment]
@all no news are good news?  Did someone some test with this version?

**Comment by jmecosta** [comment]
We have been using this version for some time now, so for us it's in
quality

**Comment by guwirth** [comment]
@all: release procedure nearly done
remaining points:
* add enhancements to release notes
* not all new features are described in wiki
* create final POM without RC

**Comment by jmecosta** [comment]
Can we start by cleaning the labels, now we have so many questions attached
to this milestone that's hard to have a clear picture what remains to be
document.

Imo we should have only 3 labels, bug, enhancement and documentation.  Were
doc label can be included along with feature or bugfix.

We should have temp label for doc ready needs review so people can comment
on it.

**Comment by guwirth** [comment]
@jmecosta points which should be documented are marked already with 'docu request'. So should be easy to filter.

**Comment by jmecosta** [comment]
I've done a few ones already, I mark waiting reply.

**Comment by guwirth** [comment]
Open: https://github.com/SonarOpenCommunity/sonar-cxx/issues?q=label%3A%22docu+request%22+milestone%3A0.9.5

**Comment by guwirth** [comment]
@all: release 0.9.5 draft finished to review. Please have a look if something is missing or wrong...

**Comment by mjdetullio** [comment]
Running on SQ 5.4 and so far everything is good :+1:

**Comment by guwirth** [comment]
@mjdetullio thanks for your feedback

**Comment by guwirth** [comment]
@Bertk any feedback from your side?
If ok would release then.

**Comment by guwirth** [comment]
@all final step would be to remove -RC2 from pom's and release.

Has someone still a blocking issue?
If not I will release after lunch.

**Comment by guwirth** [comment]
@jmecosta final step is upload of binaries. Maybe you can do this. 
@all please do some advertisement for the new version. 

**Thanks and Happy Easter to all of you!**

**Comment by jmecosta** [comment]
good present just before Easter.  I will upload the binaries after dinner.
Happy Easter

**Comment by jmecosta** [comment]
all done. 0.9.6-SNAPSHOT also now in master.
