### ISSUE TITLE
v0.9.6 goals?

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#818]
Hi,

After the release of v0.9.5 the question is how to proceed with v0.9.6?

My proposal is to focus on the next LTS version SQ 5.6 (27/May/16) and cut all old dependencies and tests:
* update POMs and dependencies to SQ 5.2+
* update all APIs and remove APIs/functionality marked as deprecated
* remove Travis and AppVeyor tests & versions for versions < SQ 5.2
* release v0.9.6 for SQ 5.6 only

What's your opinion? Which features are missing?
Looking forward to get your feedback...

Regards,
Günter

**Comment by jmecosta** [comment]
:+1: to LTS and remove deprecated APIs

new feature will likely appear while this is developed

**Comment by Bertk** [comment]
:+1: remove deprecated APIs and refer to API 5.5 or 5.6 (see [MMF-185](https://jira.sonarsource.com/browse/MMF-185), [MMF-184](https://jira.sonarsource.com/browse/MMF-184) and [SONAR-6393](https://jira.sonarsource.com/browse/SONAR-6393)).
The C++ Community plug-in shall use the new rules format only.
