### ISSUE TITLE
Header files not indexed

### ISSUE THREAD

**Issue by yolani** [SonarOpenCommunity/sonar-cxx#829]
Hi there,

i have a question about the indexed files, i am not really sure if it's supposed to be like this or if i'm doing something wrong.

i am using "sonar.cxx.other.reportPath" to feed some issues from additional tools used in my working environment into the analysis. for source files this is working very well. however i recently wanted too create an issue in a header file and i get 
"13:52:59.277 WARN  - Cannot find the file 'some_header_file.h', skipping violations"
Of cource i triple-checked, but i am absolutely sure the file exists and that it is included in an indexed source file.

so my question is, is there any way to create issues for header file?

Regards,

Christian

**Comment by jmecosta** [comment]
hi
when it comes to saving issues on files there is no difference between source or headers files. please  double check if you can find the file in the web ui. looks like its not there. also, if you have multimodule configuration then if trying to assign a issue to a header that is in a different module will show that warning however it should be correctly imported in the own module.

**Comment by yolani** [comment]
now it get's even stranger. i just discovered that i can not see any header file in the web-ui. i am sure this was working in the past. on the other hand, during the analysis the header file is definitely present, because otherwise i would get some "can not find include for..." warning from the plugin. so my sonar.cxx.includeDirectories seems to be correct. and i did not play with "sonar.cxx.suffixes.headers" either.

any ideas?

**Comment by jmecosta** [comment]
likely your exclusions are not well set, run in debug and look at the index source part it should give you hints about how you have your exclusions set, also it should tell you if the file is index or not and what folders are index

**Comment by guwirth** [comment]
The feature is working for sure. Maybe a configuration issue?  Is  sonar.cxx.suffixes.headers in your config file?

**Comment by yolani** [comment]
Hello there,

i think i discovered my problem. my headers where not included in sonar.sources, i just specified sonar.cxx.includeDirectories to point to my include directories, which are different from the source directories.

after adding the headers to sonar.sources the .h-Files are showing up correctly in the gui. so my problem is solved, but is this working as intended or should headers be indexed based on include hierarchies?

**Comment by jmecosta** [comment]
hi,

this is as intended, sonar.sources is core prop to index files. includeDirectories is additional prop from our side to aid on parsing files index by sonar.sources. It must be used for example for system directories that you dont wont to index

**Comment by yolani** [comment]
thanks for the quick answer, so everything is fine and this issue can be closed.

thanks for the help.

**Comment by jmecosta** [comment]
no problem. thanks
