### ISSUE TITLE
Unable to find resource error when using header files

### ISSUE THREAD

**Issue by dinesh25** [SonarOpenCommunity/sonar-cxx#844]
Hi, 
configs: 
Red Hat Enterprise Linux Server release 7.1
sonarqube-5.1.1
sonar-runner-2.4
java version "1.7.0_25"
i have installed sonar-cxx-plugin-0.9.4-RC3.jar plugin.

I am running cppcheck and providing the report to sonar for analysis. 
without includes, sonar is able to parse the cppcheck's report and build the dashboard.

As i wanted to provide information to sonar about the include files, so that if any issues gets resolved. 

i used the attribute sonar.cxx.includeDirectories, to provide the path names of include directories.
here sonar still produces the dash board successfully, but i get errors saying,
**00:56:21 00:53:49.736 WARN  - Unable to find resource '/proj1/app/loc/inc/abc.H' to create a dependency with 'src/abcf.cxx'**

but the file is available in the above said path /proj1/app/loc/inc/abc.H. 
but the special thing to note here is , this /proj1/app/loc/inc location i have not mentioned in  sonar.cxx.includeDirectories, instead i mentioned as /loc/inc as /loc/inc is a soft link that points to /proj1/app/loc/inc. 

/loc/inc is a folder which contains all headers linked from many dirs from different path location.
sonar was able to pick up the header file's exact path, that is listed above in the error, but not sure why it reports as " unable to find resource" despite the file is actually present. 

please guide me in proceeding further.

regards,
Dinesh

**Comment by jmecosta** [comment]
Hi please update to last release 0.9.5 the message you see is expected and
it's not suppose to be analysed. It will be removed in the next version of
the plugin

**Comment by dinesh25** [comment]
Hi,
Thank you for the immediate response. Did you mean to say like 0.9.5 will resolve my issue? 

regards,
Dinesh

**Comment by jmecosta** [comment]
No, just saying you should disregard the message

**Comment by dinesh25** [comment]
Thank you, and upgrading to 0.9.5 , will it mark as a difference in the metrics(in dash board) when running for the same source code as did with 0.9.4, as i see the release note says it has improved in LOC counting and complexity measure improvements?

**Comment by jmecosta** [comment]
yes, you might see some differences. however as release notes say it expected due to improved parsing experience

**Comment by dinesh25** [comment]
Thank you :)

**Comment by jmecosta** [comment]
your welcome.

**Comment by dinesh25** [comment]
Hi,
Please let me know the significance of using sonar.cxx.includeDirectories. PLease clarify.

regards,
Dinesh

**Comment by jmecosta** [comment]
sonar.cxx.includeDirectories is used to look for header files, so it can be used to help the parser to create a AST. it has the same effect as -Ifolder when you are compiling

**Comment by dinesh25** [comment]
But here in the above case, as the warning pops out saying 
**00:56:21 00:53:49.736 WARN - Unable to find resource '/proj1/app/loc/inc/abc.H' to create a dependency with 'src/abcf.cxx'**
does the parser is creating AST in the above case? or this feature is yet to be implemented? 

regards,
Dinesh

**Comment by jmecosta** [comment]
you can disregard that specific message, it will be removed in the next
version of the plugin. that feature is a specic feature about depedency
handling that the core does not support anymore
