### ISSUE TITLE
Clazy support

### ISSUE THREAD

**Issue by Nick0001** [SonarOpenCommunity/sonar-cxx#847]
For C++/Qt there is
- https://github.com/KDE/clazy
- https://github.com/Krazy-collection/krazy

Are there plans to support these?

**Comment by jmecosta** [comment]
not really, however in this case i would suggest using the external sensor to import those in sonar. https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis#usage-of-unsupported-code-checkers since this seems to be a bit Qt specific.

**Comment by guwirth** [comment]
@Nick0001 what's exactly the problem with clazy? Isn't it possible to mock the differences like described here https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces?

**Comment by guwirth** [comment]
@Nick0001 please reopen if still an issue.
