### ISSUE TITLE
V0.9.6   jdk1.7 can not be use

### ISSUE THREAD

**Issue by wangluoabc** [SonarOpenCommunity/sonar-cxx#865]
V0.9.6 

StringJoiner is jdk1.8 feature

location:
CxxPreprocessor.java

 private String serialize(List<Token> tokens, String spacer) {
    StringJoiner js = new StringJoiner(spacer);
    for (Token t : tokens) {
      js.add(t.getValue());
    }

**Comment by jmecosta** [comment]
Yep we don't support 1.7 any more see 
https://github.com/SonarOpenCommunity/sonar-cxx/commit/3ae548479eccb7c3dd60a297a3a6c9c167d48db4
