### ISSUE TITLE
Detect unwanted/deprecated APIs?

### ISSUE THREAD

**Issue by amai2012** [SonarOpenCommunity/sonar-cxx#869]
I would like to track usage of certain APIs which developers should not use anymore (but can't be removed at once in legacy code). So at least I would like to visualize the current usage and hope it's decreasing slowly.
Any ideas how this could be achieved? (my current approach is to search the source in my buildjob and compare the number to the previous run) I cannot rely on cppcheck - since the APIs are either not deprecated by any standard or just in 3rd party libraries.

**Comment by Bertk** [comment]
Maybe you can implement it like Microsoft is doing it with [banned.h](http://download.microsoft.com/download/2/e/b/2ebac853-63b7-49b4-b66f-9fd85f37c0f5/banned.h) and use force include to activate it. Should be easy to implement for additional APIs and the compiler warnings can be used to monitor it. But this works only fot VC++.

**Comment by guwirth** [comment]
@amai2012 two other possibilities:
* you can use a check to search for a regular expression:
  * in a line: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/LineRegularExpressionCheck.java
 * or in the whole file: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/FileRegularExpressionCheck.java
* other possibility is to use the XPath check: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/XPathCheck.java

These checks are template rules and you are able to define individual messages for them.
