### ISSUE TITLE
Compatibility with SonarQube 5.5

### ISSUE THREAD

**Issue by jtpereyda** [SonarOpenCommunity/sonar-cxx#871]
The [matrix](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix) indicates that v0.9.5 works with SQ 5.4. [This discussion](https://github.com/SonarOpenCommunity/sonar-cxx/issues/818) indicates that v0.9.5 will only support SQ 5.6.

If I'm on a 5.5 install, could I reasonably expect sonar-cxx to mostly work, or is my only option to downgrade?

Likewise, would SQ 5.5 work with v0.9.5?

**Comment by jtpereyda** [comment]
I tried it on a test install and managed to upload cppcheck via sonar-cxx, so I take it it's at least somewhat compatible.

**Comment by guwirth** [comment]
@jtpereyda to the time of the release of 0.9.5 there was no SQ5.5 available. You can find the tested versions here https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix. But I would expect that 0.9.5 is also working with SQ5.5. The discussion is more about the internal SQ API usage. 0.9.5 is compatible to last 4.5 LTS API and 0.9.6 will use new features of 5.6 LTS API and is therefore no more backward compatible.

**Comment by jtpereyda** [comment]
@guwirth Thank you, I appreciate it. I'll update if I run into any issues, but I suspect I'll upgrade to 5.6 not too long after it comes out.
