### ISSUE TITLE
Lexer error

### ISSUE THREAD

**Issue by Psychoboy** [SonarOpenCommunity/sonar-cxx#872]
Not sure if this is a configuration issue or not. I have all the include folders specified. Macros I believe I have specified correctly as well.

Almost every file says the same error:

Unable to parse file: Path\File.h\cpp
Lexer error; Unable to lex uril: path\file.h\cpp.

I have ran it with -X to get the full debug log but nothing is showing in the log. No other warnings or errors. Just these 2 errors every time right after each other.

Any idea's where I should look?

**Comment by guwirth** [comment]
@Psychoboy never saw this message before? Please create a more complete log file as described here https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information:

sonar-runner -X -e -Dsonar.verbose=true ... > sonar-runner.log 2>&1

and copy it to this issue. Interesting is also your configuration file and the information which version of the plugin and SonarQube you are using.

**Comment by guwirth** [comment]
@Psychoboy please reopen if still an issue
