### ISSUE TITLE
sonar cxx.0.9.4+ - SQ 4.5.2 - cppcheck - skipping all violations

### ISSUE THREAD

**Issue by kgiloo** [SonarOpenCommunity/sonar-cxx#875]
**scope: cxx 0.9.4(or 0.9.5) - SQ 4.5.2**

sonar cxx **0.9.2** parses cppcheck issues without problem. 
sonar cxx **0.9.4** does not find src files although they do exist.

sonar log:
> 
 [exec] 10:54:59.083 INFO  - Processing report 'cppcheck_mandelbrot_121647_sonar.xml'
 [exec] 10:54:59.083 INFO  - Parsing 'Cppcheck V2' format
  [exec] 10:54:59.180 WARN  - **Cannot find the file** '**D:\Jenkins\mandelbrot\mandelbrot\cppchecktest.cpp**', **skipping violations**

**sonar-project.properties (cppcheck):**
`
sonar.cxx.cppcheck.reportPath=cppcheck_mandelbrot_121647_sonar.xml
sonar.cxx.cppcheck.execPath=C:\PROGRA~2\Cppcheck\CPPCHECK.EXE
sonar.cxx.cppcheck.checks=all
sonar.cxx.cppchecks=all
sonar.cxx.cppcheck.xmlversion=2
`

cppcheck_mandelbrot_121647_sonar.xml located in root (i.e: D:\Jenkins\mandelbrot)
**cppcheck_mandelbrot_121647_sonar.xml:**
`
<?xml version="1.0" encoding="UTF-8"?>
<results version="2">
    <cppcheck version="1.72"/>
    <errors>
        <error id="unusedAllocatedMemory" severity="style" msg="Variable &apos;pI&apos; is allocated memory that is never used." verbose="Variable &apos;pI&apos; is allocated memory that is never used.">
            <location file="mandelbrot/cppchecktest.cpp" line="19"/>
        </error>
`

**Comment by jmecosta** [comment]
how does the rest of the confiuration looks like? this is about how files
are imported to sonar. if you look in the ui you will see that
*cppchecktest.cpp
is likely in a different place from were you think.*

*are you using some sort of multi module configuration?*

**Comment by kgiloo** [comment]
below the structure... In **D:\Jenkins\mandelbrot\mandelbrot** are located the src files. 
Note that i also tried by replacing in the cppcheck report the relative paths by absolute but no change. 
Weird like sonar constructs the good path but complaining it does not exist. 
Just wondering what has changed since 0.9.2 in this matter? 

![mandelbrot](https://cloud.githubusercontent.com/assets/9213451/15648869/8a8ab9c4-266d-11e6-818a-db357fd3c5bf.png)



**sonar-project.properties:**
sonar.sources=.
sonar.exclusions=
sonar.language=c++
sonar.sourceEncoding=UTF-8
sonar.jdbc.url=jdbc:mysql://localhost:3306/sonar?useUnicode=true&amp;characterEncoding=utf8
sonar.cxx.includeDirectories=.,D:/3rdParty/Qt/4.8.2/include,D:/3rdParty/Qt/4.8.2/include/QtCore,D:/3rdParty/Qt/4.8.2/include/QtGui,D:/3rdParty/Qt/4.8.2/include/QtXml,D:/3rdParty/Qt/4.8.2/include/QtDesigner,D:/3rdParty/Qt/4.8.2/include/ActiveQt

sonar.scm-stats.period1=180
sonar.scm.url=scm:svn:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

sonar.cxx.errorRecoveryEnabled=True

sonar.cxx.cppcheck.reportPath=cppcheck_mandelbrot_121647_sonar.xml
sonar.cxx.cppcheck.execPath=C:\PROGRA~2\Cppcheck\CPPCHECK.EXE
sonar.cxx.cppcheck.checks=all
sonar.cxx.cppchecks=all
sonar.cxx.cppcheck.xmlversion=2

**Comment by jmecosta** [comment]
supose cppcheck reports lacks : <location file="*mandelbrot/*
mandelbrot/cppchecktest.cpp" line="19"/>

you cppcheck run script seems to be creating warings from wrong working dir

or you can try instead of sonar.sources=.
sonar.sources=*mandelbrot *

**Comment by kgiloo** [comment]
Thanx for your help, but the problem was somewhere else. 
I recompiled the 0.9.4 and add some misc logs into saveViolation (CxxReportSensor.java)

...
  [exec] INFO: Project configuration file: **D:\JENKINS**\mandelbrot\sonar-project.properties
...
 [exec] 16:16:14.939 INFO  - Processing report 'cppcheck_mandelbrot_121647_sonar.xml'
     [exec] 16:16:14.939 INFO  - Parsing 'Cppcheck V2' format
     [exec] 16:16:15.041 WARN  - root **'D:\JENKINS\mandelbrot**\.'
     [exec] 16:16:15.041 WARN  - normalizePathFull:filePath '**D:\Jenkins\mandelbrot**\mandelbrot\cppchecktest.cpp'
     [exec] 16:16:15.041 WARN  - normalPath 'D:\Jenkins\mandelbrot\mandelbrot\cppchecktest.cpp'
     [exec] 16:16:15.043 WARN  - Cannot find the file 'D:\Jenkins\mandelbrot\mandelbrot\cppchecktest.cpp', skipping violations

Note that the root path is different from the one found in normalPath, which shouldn't make any difference on windows (case unsensitive **JENKINS** vs **Jenkins**). However it does make a huge difference! Therefore cxx plugin complained that it cannot find the path (warning quite confusing in this case IMHO)...

Giving the  project configuration file as  **D:\Jenkins**\mandelbrot\sonar-project.properties solved the problem.

**Comment by jmecosta** [comment]
ok, good you found. not sure if we can improve tought, since you are passing the project file via property? usually the best approach is to change to path where the file is and run the analysis from there

**Comment by guwirth** [comment]
@kgiloo please read also: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues
