### ISSUE TITLE
Manual Test SQ 5.6 RC2 with plugin v0.9.6

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#880]
* SQ 5.6 RC2 is available for testing
* SQ 5.6 RC2 API is available but no other plugin is using it yet. They are all still on 4.5.x (see POM files of Java, Javascript and CSharp). Don't know when they are planning to upgrade?
* We are using 5.6 SQ and API now and all deprecated APIs seems still to work? Build works, Unit Tests work, Integration Tests work.

Know issues: #878, #879 

**Issue to track initial manual test**

**Comment by guwirth** [comment]
@jmecosta there was a CI problem with AppVeyor on master branch. Build with PR was ok. Can you start a rebuild please.

**Comment by jmecosta** [comment]
ive just commit something to readme :) faster then tring to find password of super user. by the way ive sent some credetials to your gmail. so you can acesss appveyour also. can you confirm that you got them by the way ?

**Comment by jmecosta** [comment]
@guwirth run most of our projects in the test server, and the only prob was the java 8 update. once it was done things were really well and even performace wise there are not major problems. for me +1 for this update

**Comment by guwirth** [comment]
> Know issues: #878, #879

@jmecosta But these two issues should be there?

**Comment by jmecosta** [comment]
@guwirth yes they are, at least the rules in the profile and the code have them. no problems so far.

```
[20:21:50] :		 [Step 1/1] INFO: Project 'xxxxx' Cycles:0 Feedback cycles:0 Tangles:0 Weight:0.0
```
