### ISSUE TITLE
API Documentation on template function

### ISSUE THREAD

**Issue by GMercat** [SonarOpenCommunity/sonar-cxx#886]
Hi,

With this implementation : 

```
class TestClass {

[...]

public:
/**
 * @brief DOCUMENTATION
 */
template <class T>
void functionTest();
};
```

I have _"Undocumented API: functionTest"_, and i don't understand why ?

Thank you in advance for your answer. 

sonarqube : v5.4
sonar-cxx : v0.9.5

**Comment by GMercat** [comment]
I think it's the same bug referenced into "Issues with undocumented API detetction" #890.

G.

**Comment by guwirth** [comment]
@GMercat should be fixed with latest snapshot. Please test and give us feedback.

**Comment by GMercat** [comment]
@guwirth, sorry for the delay. I tested with latest snapshot and this bug is fixed.
But i have now an other bug about 'Undocumented API'.

In test.h file:
```
template <class U>
class TestClass {

[...]

public:
/**
 * @brief DOCUMENTATION
 */
template <class T>
void functionTest();
};

#include "test.impl.h"
```

In test.impl.h file:
```
[...]

/**
 * @brief DOCUMENTATION
 */
template <class U>
template <class T>
void TestClass::functionTest();
```

I have "Undocumented API: functionTest" on TestClass::functionTest in "test.impl.h" ?

sonarqube : v5.6.3
sonar-cxx : v0.9.7-SNAPSHOT (git commit: 0b185964ee6b19e1194bffb635a390afa83b77a5)

**Comment by GMercat** [comment]
@guwirth Do you want me to open a new issue or you will reopen this one ?

**Comment by guwirth** [comment]
@GMercat yes please create a new one.
