### ISSUE TITLE
Inner sub-modules/preoject are not being analyzed by sonar-cxx plugin

### ISSUE THREAD

**Issue by renjithhp** [SonarOpenCommunity/sonar-cxx#888]
I have a C++ project analyzed on SonarQube 5.4 with sonar-cxx plugin. It is a big project, I have set the sonar.sources property to the root directory of project. But some of the inner modules/sub-projects are not being analyzed and listed in SonarQube. the root projects are listed and upto 2 or 3 levels of inner projects are also listed, but those the 4th level inner modules are not being analyzed. I can't figure it why? Is there any way I can tell the SonarQube or cxx plugin to fetch all the modules in a project.

Thanks for any suggestions

**Comment by guwirth** [comment]
> But some of the inner modules/sub-projects are not being analyzed and listed in SonarQube.

I'm not aware that there is a "level" limitation.

Maybe one of these problems:
* there is an exclude in your configuration
* Sensor not able to read a source file. Add debug logging to get more information: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information
* Path problems, see: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues

By the way: is it a "normal" or a multi-module project?

**Comment by renjithhp** [comment]
I think it is a multi-module project. Is there anything I need to do with that?

**Comment by guwirth** [comment]
@renjithhp configuration: http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner
