### ISSUE TITLE
Why my StartSonar.bat is failed?

### ISSUE THREAD

**Issue by springadele** [SonarOpenCommunity/sonar-cxx#889]
I installed SonarQube for TFS2015.2 follow this article:["集成TFS Build生成与SonarQube获取代码分析结果	"](http://www.cnblogs.com/danzhang/p/5205610.html)
However,when I start the "StartSonar"  service,it's failed, just like 
[error pic](https://social.msdn.microsoft.com/Forums/getfile/877153)

the logs are:
```
"jvm 1    | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
jvm 1    |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
jvm 1    |
jvm 1    | 2016.06.16 15:14:33 INFO  app[o.s.p.m.JavaProcessLauncher] Launch process[search]: C:\Program Files\Java\jre1.8.0_91\bin\java -Djava.awt.headless=true -Xmx1G -Xms256m -Xss256k -Djava.net.preferIPv4Stack=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=C:\sonarqube-5.3\temp -cp ./lib/common/*;./lib/search/* org.sonar.search.SearchServer C:\Users\USERNAME~1\AppData\Local\Temp\sq-process4895770889147481876properties
jvm 1    | 2016.06.16 15:14:40 INFO  app[o.s.p.m.Monitor] Process[search] is upjvm 1    | 2016.06.16 15:14:40 INFO  app[o.s.p.m.JavaProcessLauncher] Launch process[web]: C:\Program Files\Java\jre1.8.0_91\bin\java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djruby.management.enabled=false -Djruby.compile.invokedynamic=false -Xmx768m -Xms256m -XX:MaxPermSize=160m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Djava.io.tmpdir=C:\sonarqube-5.3\temp -cp ./lib/common/*;./lib/server/*;C:\sonarqube-5.3\lib\jdbc\mssql\sqljdbc41.jar org.sonar.server.app.WebServer C:\Users\USERNAME~1\AppData\Local\Temp\sq-process3775501114923191128properties
jvm 1    | 2016.06.16 15:15:06 INFO  app[o.s.p.m.TerminatorThread] Process[search] is stopping
jvm 1    | 2016.06.16 15:15:07 INFO  app[o.s.p.m.TerminatorThread] Process[search] is stopped"
```

**Comment by guwirth** [comment]
@springadele please remove cxx plugin and try again.
* seems it's a SonarQube framework or installation issue which you can better address here: http://www.sonarqube.org/get-support/
* current installation instruction is here: http://docs.sonarqube.org/display/SONAR/Installing+the+Server

**Comment by springadele** [comment]
@guwirth I remove “sonar-csharp-plugin-5.3.jar” from the plugin and try again,it's still the same error.

**Comment by guwirth** [comment]
@springadele This forum is about `C++ (Community) [cxx]` plugin. So please uninstall and try again. If still an issue ask here: http://www.sonarqube.org/get-support/.

**Comment by SecurityIsIllusion** [comment]
Installation:

https://github.com/SonarSource/sonar-.net-documentation/blob/master/doc/installation-and-configuration.md

Setting up DB:
https://github.com/SonarSource/sonar-.net-documentation/blob/master/doc/additional-configurations.md

DB drivers:
https://docs.sonarqube.org/display/SONAR/Installing+the+Server
