### ISSUE TITLE
parser fails with "throw(...)" exception specification 

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx#892]
The parser fails with exception specification like 
```cpp
int myfunc() throw(...){}
```
Without "..." everything is fine

```cpp
int myfunc1() throw(){
}
int myfunc2() throw(int){
}
```
see also https://msdn.microsoft.com/en-us/library/wfa0edys.aspx

**Comment by guwirth** [comment]
```
exception-declaration:
   attribute-specifier-seqopt type-specifier-seq declarator
   attribute-specifier-seqopt type-specifier-seq abstract-declaratoropt
   ...
```

**Comment by guwirth** [comment]
Seems to be a Microsoft specific extension?

**Comment by Bertk** [comment]
Yes, this is "Nonstandard Behavior" (see also https://msdn.microsoft.com/en-us/library/x84h5b78.aspx)

**Comment by Bertk** [comment]
This modification will solve the issue
```java
    b.rule(typeIdList).is(
      b.firstOf(
        b.sequence(typeId, b.optional("..."), b.zeroOrMore(",", typeId, b.optional("..."))), // C++ 
        "..."// Microsoft extension
      )
    ); 
```

**Comment by guwirth** [comment]
```
b.rule(dynamicExceptionSpecification).is(
   CxxKeyword.THROW, "(", b.optional(b.firstOf(
      typeIdList, // C++
      "..." // Microsoft extension
    )), ")"
);
```

**Comment by Bertk** [comment]
Actually I am not sure whether "..." is not a synonym for any type in this context. 
see also http://en.cppreference.com/w/cpp/language/try_catch

> The catch-all clause catch(...) matched exceptions of any type.

The [Exception Specifications (throw) (C++) ](https://msdn.microsoft.com/en-us/library/wfa0edys.aspx)documentation on MSDN uses ```...``` instead ```typeIdList```
