### ISSUE TITLE
Request for contribution to keep cxx plugin alive

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#896]
Hi folks,

With SQ 5.6 API there are some bigger changes and many APIs are marked deprecated. We are looking for contributors helping us keeping the plugin up to date. All deprecated APIs are marked already with @todo, so they are easy to find.

During the last years many cool features found there way into the plugin. In case the APIs are deprecated and nobody maintains them there is no other way as to remove the features.

**So I like to ask you all for your support keeping this plugin alive!**

Thanks in advance & Regards,
Günter

**Comment by jmecosta** [comment]
@guwirth start doing something for this in #903

**Comment by guwirth** [comment]
@jmecosta good to hear/see that you are working on this. Think others do the same at the moment, so e.g. JavaScript is a good sample to see what's necessary (https://github.com/SonarSource/sonar-javascript).

**Comment by jmecosta** [comment]
we have also dot-net-tests plugin and java plugin are already using the new API. any way ive most remove the stuff from the sonar-cxx-plugin module. but i am ensure if i want to touch the squid part, at least the grammar i think i will brake it so badly.

**Comment by jmecosta** [comment]
@guwirth think i cover most of the things, however as i mentioned the stuff that touches the grammar i did not touch. mostly we need to provide our own preprocessor. the other is related with symbol and highliting api, seems we need to create a highliting visitor but i did not went far on trying to adapt the sonar-javascript.

i will still do a couple refactorings related with the new InputFile api and then try again the highliting. if i am unable, do you think you can take look

**Comment by guwirth** [comment]
Hi @jmecosta thanks a lot for spending your time. Upgrading 187 files was for sure a lot of effort! Will have a first look and review this evening.
> if i am unable, do you think you can take look

Think is the best to merge your changes first before continue with other things.

**Comment by guwirth** [comment]
@all with #913 there are bigger changes on the plugin. Many APIs have been updated to latest SQ 5.6. Please test and give feedback.

**Comment by guwirth** [comment]
Hi folks,

SQ 5.6, SQ 6.0 and SQ 6.1 should be supported with current snapshot of cxx plugin 0.9.7 now. After closing the remaining issues we can release a new version.

I'm interested in your feedback:
* Are you already using the snapshot? With which SQ version?
* Which features (sensor) are you using already successfully? Where do you still have problems?
* What's missing?

Looking forward to hear from you (or even better get pull requests from you). 

Best regards,
Günter

**Comment by jmecosta** [comment]
Great, did you manage to remove all deprecated stuff out,  or is there
something sill missing? We are at the moment upgrading to 6.0 all our
plugins will test more when having a running  sonar

**Comment by guwirth** [comment]
> did you manage to remove all deprecated stuff out

All except the preprocessor. But is still supported in 6.1-RC1. There are also still some questions open and to verify, e.g. unit test detail support #906, and force zero coverage #909, ...

**Comment by jmecosta** [comment]
Alright, I would launch a vote for 906 and 909 and implement straight away
based on feedback, as they should be easy fixes

**Comment by jmecosta** [comment]
@guwirth  6.0 in test server running smoothly with last snapshot, visible changes are in the duplication side of things but i am aware of the new calculation.

#906 is gone and can be closed because there is no more such support in core. If they decide to change that in future we can implement it again
#909 should not prevent a release at this point, we could work on this after the release? Or is this needs really to be handled for this?
#959 might need to be included also

+1 for starting release

**Comment by guwirth** [comment]
@jmecosta thx for testing. 
* Which sensor are you using in your setup?
* Would also try to close some of the bugs before a release

**Comment by jmecosta** [comment]
compiler, rats, vera, cxxlint, external sensor, unittest, bullseye coverage, just upgrade our production server to 6.0 results look good so far
