### ISSUE TITLE
All files are not getting listed

### ISSUE THREAD

**Issue by dinesh25** [SonarOpenCommunity/sonar-cxx#899]
Hi ,
I am using the below versions:
sonarqube-5.1.1
sonar-runner-2.4
RHEL 7
plugin: sonar-cxx-plugin-0.9.5.jar

**my concern as below:**
i have analysed, 2677 c/cpp files , and this number is updated in dashboard as well. when i click this(2677) number under FILES, all these files are NOT listed. only a 10+ files is being listed.
why all 2677 files is not being listed when i click the FILES number hyperlink. 
is there a way to list all files ? how can i do that?

please guide me.

regards,
Dinesh.

**Comment by jmecosta** [comment]
is this something only that happens only for c++? sonar 5.6 has this show more thing in the end.

![image](https://cloud.githubusercontent.com/assets/1041352/16517399/d2a50fd0-3f85-11e6-9177-7a1fba5f54d9.png)

**Comment by dinesh25** [comment]
Does sonar 5.1 doesnt have this feature of "show more" ?
PFA the screen shot 
![image](https://cloud.githubusercontent.com/assets/15211377/16517997/1a26b364-3f9e-11e6-8e3f-4976f0684c38.png)

**Comment by jmecosta** [comment]
you have a scroll bar on the left? insnt that what you are looking for? any the size of that is not configurable and is part of the core. and Given that is not longer found in more recent versions of SQ i think you are out of luck,.

**Comment by dinesh25** [comment]
So i need to update the SQ to latest to get the option "show more". ?

**Comment by jmecosta** [comment]
5.6 is the last LTS so you should consider. be carefull with #898 and backup your database before you do

**Comment by dinesh25** [comment]
Thank you Jmecosta :)

**Comment by jmecosta** [comment]
no prob
