### ISSUE TITLE
Add coverage reports based on the tool Testwell CTC++

### ISSUE THREAD

**Issue by Londran** [SonarOpenCommunity/sonar-cxx#900]
Hello,
Did not know how to get into contact with you guys. So the think is I would like to write a custom parser for another format of coverage reports based on the tool Testwell CTC++.

I have written one for SQ v4.5, but it always interfered with your zeroCoverage thingy, thus I had to deal with errors. To avoid this, I want to cooperate.

Best regards,
Sebastian/Londran.

**Comment by jmecosta** [comment]
hi,

i dont see why not, please cr pr so people can review. if it does not brake anything it should be safe to merge.

br,
jorge costa

**Comment by Londran** [comment]
I guess pr is a pull request when I am finished, but what is cr?

Best regards,
Sebastian/Londran

**Comment by jmecosta** [comment]
create :)

**Comment by guwirth** [comment]
@Londran you are welcome. We are always looking always for contributors.
* code for coverage parser should be placed here: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/coverage
* derive your own parser from this class: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/coverage/CxxCoverageParser.java
* for a sample see e.g. https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/coverage/BullseyeParser.java

**Comment by guwirth** [comment]
@Londran are you providing a solution? Is there still interest from your side?

**Comment by Londran** [comment]
We are currently working on a corbertura converter (converting our 
reports into corbertura-style xml).

If we succeed, I will tell you. Otherwise, we will do the direct approach.

BR,
Sebastian.


---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by guwirth** [comment]
@Londran ok. Close this meanwhile. Reopen it if needed again.

Only a hint from my side: xUnit/JUNIT is typically the default. Would recommend you to convert to this format.
