### ISSUE TITLE
Support for 64-bit integer-suffix

### ISSUE THREAD

**Issue by zabulus** [SonarOpenCommunity/sonar-cxx#904]
I have multiple entries in log:
```INFO: Cannot decode the number '9223372036854775807i64' falling back to value '1' instead```

**Comment by zabulus** [comment]
I think the root cause is following function:
https://github.com/SonarOpenCommunity/sonar-cxx/blob/dba73e4a863ba66bad553dceea3dd63683af8ca2/cxx-squid/src/main/java/org/sonar/cxx/preprocessor/ExpressionEvaluator.java#L466

**Comment by guwirth** [comment]
@zabulus think `9223372036854775807i64` is not a valid integer literal, integer-suffix `i64` is unkown.
http://en.cppreference.com/w/cpp/language/integer_literal

Which compiler is supporting this?

**Comment by guwirth** [comment]
Ok it's Microsoft specific: https://msdn.microsoft.com/de-de/library/00a1awxf%28v=vs.120%29.aspx

```
64-bit integer-suffix:
    i64 LL ll
```

**Comment by guwirth** [comment]
@zabulus please try with latest snapshot and give us feedback.
