### ISSUE TITLE
Files encoded with UCS-2 with BOM are not processed

### ISSUE THREAD

**Issue by zabulus** [SonarOpenCommunity/sonar-cxx#905]

**Comment by jmecosta** [comment]
you need to specify the sonar.sourceEncoding to be able to process those!

**Comment by guwirth** [comment]
Reading files with different encodings is a SQ core feature (setting see comment from @jmecosta above).

**Comment by zabulus** [comment]
> you need to specify the sonar.sourceEncoding to be able to process those!

Oh, sorry. I'll go read the docs for msbuild runner for this options. Thanks.
