### ISSUE TITLE
Unit test failure details not reported with SQ 5.6?

### ISSUE THREAD

**Issue by kgiloo** [SonarOpenCommunity/sonar-cxx#906]
With SQ **4.5.2** and cxx**0.9.4** i had all the details of unit test errors:

![sonar-uts-sample](https://cloud.githubusercontent.com/assets/9213451/16564387/7532949c-4207-11e6-805b-fbd76fbfc4d2.png)

`
sonar.sources=.
sonar.exclusions=mandelbrot/uts/**
sonar.tests=L:/Jenkins/mandelbrot/mandelbrot/uts
sonar.cxx.xunit.reportPath=uts_121865.xml
sonar.cxx.xunit.provideDetails=true
`

Upgraded sonar db from 4.5.2 to **5.6** + sonar cxx **0.9.6**.
no more details nor widget... is it supposed to work also with SQ 5.6 or did i miss something?

verbose -X: does not report anything bad:

> [exec] 16:23:00.180 INFO  - Sensor CxxXunitSensor
>      [exec] 16:23:00.194 INFO  - Processing report 'L:\Jenkins\mandelbrot\uts_121865.xml'
>      [exec] 16:23:00.194 DEBUG - Transformation skipped: no xslt given
>      [exec] 16:23:00.246 INFO  - Parsing 'xUnit' format
>      [exec] 16:23:00.246 INFO  - Processing in 'detailled mode' i.e. with provideDetails=true
>      [exec] 16:23:00.247 DEBUG - Trying the input file for the testcase 'mandelbrotUT:mandelbrotUT_01.Test1/mandelbrotUT_01.Test1' ...
>      [exec] 16:23:00.247 DEBUG - Performing the 'filename'-based lookup using the value 'L:\Jenkins\mandelbrot\mandelbrot\uts\uts_01.cpp'
>      [exec] 16:23:00.247 DEBUG - ... found! The input file is '[moduleKey=my:key_af_mandelbrot, relative=mandelbrot/uts/uts_01.cpp, basedir=L:\Jenkins\mandelbrot]'
> 
>

**Comment by jmecosta** [comment]
unfortunelly this feature is no longer supported by core and there is no feature replacing it. i am removing this detailed mode from code so its clear.

**Comment by guwirth** [comment]
Only docu update open: I close this.
