### ISSUE TITLE
cppcheck install

### ISSUE THREAD

**Issue by MattSom** [SonarOpenCommunity/sonar-cxx#907]
Hello,

Sorry if this is not the best place to ask for help, it's not an issue report.
I am a quite new to SQ, just installed it a day ago. I've copied the snapshot jar (#898 - was an issue for me as well) in the plugin folder, but my test on the sample project made 0 reports. 
( https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/sonar-cxx-plugin/src/samples/SampleProject )
I guess I need some Running Tools to make some results, so my goal is to get cppcheck operational with SQ first. Unfortunately after reading the installation guide, I'm completely lost about what to do next.

![test](http://i.imgur.com/RNE3ENo.png?1)

If I understand this interface properly, I need to give a path. According to a previous thread here (#786) I choose the output.xml name, so this should be the cppcheck's xml report directly in the projects root folder, right?

Could someone help me to clarify the following steps with more details?

    - to call it from the projects root directory
    - to pass all include directories (using -I <path>) as otherwise the analysis will be incomplete
    that the parameter matches the sonar.sources list in sonar-project.properties
    - to create a XML-report using the parameter --xml-version=2 for version 2 or --xml for version 1. Both versions are supported, version 2 is the default.
    - to get the report from the standard error channel

Thank you very much!

Edit:
https://github.com/SonarQubeCommunity/sonar-cppcheck
There is a cppcheck plugin as I see. Is it compatible with cxx?

**Comment by guwirth** [comment]
Hi @MattSom, maybe that helps:
* sample: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata/cppcheck_with_absolute_paths_project
* How to run cppcheck: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers
* Path issues: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues

**Comment by MattSom** [comment]
Thanks for the fast the respone @guwirth, I examined your links thoroughly.

Since then I've made some progress:

First of all I am using Ubuntu.

https://github.com/SonarQubeCommunity/sonar-cppcheck
This plugin is now installed. I am completely new to cppcheck as well, but managed to figure out some basics:

   - now using the " cppcheck --xml --xml-version=2 --enable=all <path1> <path2> 2>samplecppcheck.xml " code sample I can generate the cppcheck xml result file in the root folder.

  - also managed to realize the meaning of the sonar.cppcheck.reportPath property. I use the sonar.cppcheck.reportPath=cppcheck-report.xml, and set the Cppcheck report(s) bracket to this name as well in the General settings at C++(community) section. (The picture I attached in my first post).

   - I ran the sonar-scanner on the Sample project mentioned above and on the "cppcheck_with_absolute_paths_project sample" code sample as you have suggested. Still when looking at the results the cppchecks error says 0. Checking the xml file it shows a couple of errors though. 
![screenshot from 2016-07-06 16 29 18](https://cloud.githubusercontent.com/assets/20301758/16621727/94637520-4397-11e6-8c97-be45f1743318.png)

I feel something with cppcheck is still wrong with my configurations.
I attach the xml report on the cppcheck procejt sample. 
[cppcheck-report.xml.zip](https://github.com/SonarOpenCommunity/sonar-cxx/files/350081/cppcheck-report.xml.zip)

What am I missing here?

**Comment by guwirth** [comment]
Hi @MattSom. 

Turn logging on https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information and have a look to the log file:
* are the source files read to db
* are the rules activated
* is the plugin able to find the report
* is the plugin able to match the issues (right paths)

Plugin is first reading the files into db and then sensor match issues to files in db.

Regards

**Comment by MattSom** [comment]
Hello @guwirth 

This morning I made some acquaintances with the logging thanks to the link you've provided. 
Running sonnar-scanner -X, I found this:

INFO: Sensor CxxCppCheckSensor (wrapped)
DEBUG: Normalized report includes to '[/home/matyesz/Documents/Cpp_Test/cppcheck_test/cppcheck-report.xml]'
INFO: Scanner found '1' report files
INFO: Parser will parse '1' report files
INFO: Processing report '/home/matyesz/Documents/Cpp_Test/cppcheck_test/cppcheck-report.xml'
DEBUG: Parsing 'Cppcheck V2' format
INFO: Added report '/home/matyesz/Documents/Cpp_Test/cppcheck_test/cppcheck-report.xml' (parsed by: CppcheckParserV2)
DEBUG: CppCheck Errors processed = 0
INFO: CppCheck Errors processed = 0
INFO: Sensor CxxCppCheckSensor (wrapped) (done) | time=144ms

The interesting thing is before the xml reported by cppcheck SQ detected 0 issues all together, now it says 7. It is the same 7 issues, the xml report talks about. So it seems it does truly detect the xml, just not signing it to the cppcheck error section.

![screenshot from 2016-07-07 10 52 33](https://cloud.githubusercontent.com/assets/20301758/16647742/f57aae8e-4430-11e6-803b-ea79d8b8228e.png)

![screenshot from 2016-07-07 10 44 23](https://cloud.githubusercontent.com/assets/20301758/16647699/c277297c-4430-11e6-91b2-46a210aee8b2.png)

**Comment by guwirth** [comment]
Hi @MattSom 

```
INFO: Added report '/home/matyesz/Documents/Cpp_Test/cppcheck_test/cppcheck-report.xml' (parsed by: CppcheckParserV2)
```
Means plugin is able to read report with format V2.

* Are the source files visible in SQ UI?
* Are there issues in the report?
* if yes: does path in report match with real position on system running sonar-scanner?
* play around with slash/backslash upper/lower case:  https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues

Regards,
