### ISSUE TITLE
Xpath rule in SQ 5.6 deprecated

### ISSUE THREAD

**Issue by jmecosta** [SonarOpenCommunity/sonar-cxx#908]
- investigate, remove from profile or port.

**Comment by guwirth** [comment]
SQ 5.6: XML utilities org.sonar.api.utils.StaxParser and XpathParser are deprecated as plugins can now embed and use their own 3rd-party libraries

http://docs.sonarqube.org/display/DEV/API+Changes

* Xpath rule is deprecated
* remove it

**Comment by jmecosta** [comment]
Remove I supose, I double check and we mostly use reg expression on lines,
xpath is much harder to setup since you need to sslr toolkit.

**Comment by guwirth** [comment]
Removed with #913
