### ISSUE TITLE
figure out what to do with forceZeroCoverage feature that does not work anymore in batch side

### ISSUE THREAD

**Issue by jmecosta** [SonarOpenCommunity/sonar-cxx#909]
- drop?
- or move to server side.

**Comment by guwirth** [comment]
Found this. Seems to work different now.
* Force coverage to 0%: https://jira.sonarsource.com/browse/MMF-166
* New executable_lines_data metric: https://jira.sonarsource.com/browse/SONAR-5772

**Comment by jmecosta** [comment]
Cool thanks, that will do and we should be dropping the force coverage to
zero. If I understood properly even the bullseye model should work properly

**Comment by guwirth** [comment]
Did some first tests over the weekend and get different coverage numbers (e.g. 19% coverage instead 5% before). Seems `forceZeroCoverage` is still needed. Will create a call in the SQ forum to ask why [MMF-166](https://jira.sonarsource.com/browse/MMF-166) is not working.
