### ISSUE TITLE
support properties for reports for modules like module.sonar.cxx.cppcheck.reportpath

### ISSUE THREAD

**Issue by jmecosta** [SonarOpenCommunity/sonar-cxx#910]
seems in 5.6 we need to pass the module key as in context.filesystem().module().key() and append the default property key

**Comment by guwirth** [comment]
@jmecosta Don't catch this, can you make a sample please?

**Comment by guwirth** [comment]
@jmecosta can we close this one? If not can you explain what this should do?

**Comment by jmecosta** [comment]
if remember correctly a user was using heavily modules and submodules and setting project reports paths in this kind of format

module1.sonar.cxx.cppcheck.reportpath=module1.xml
module2.sonar.cxx.cppcheck.reportpath=module2.xml

our current implementation will always search for sonar.cxx.cppcheck.reportpath so you cannot set different paths for different modules. you can go around this and simplify this a lot.

it all comes up with someone having time to implement this, should not be big effort tought. 

i would keep it open mark it "up for grabs" if someone is interested they can implement it or i can do it when i have a bit of time
