### ISSUE TITLE
track development on test case details feature in sonarque 5.6

### ISSUE THREAD

**Issue by jmecosta** [SonarOpenCommunity/sonar-cxx#911]
detail mode is gone, this was testing that. from what i see there is still lacking on server side to display at least the test names. from the java plugin they use this still: https://github.com/SonarSource/sonar-java/blob/master/java-surefire/src/main/java/org/sonar/plugins/surefire/SurefireJavaParser.java#L157 

however if i look at the https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/test/MutableTestPlan.java#L23 its seems to be going away. 

So likely test metrics will become only numbers and no details.

**Comment by MattSom** [comment]
Hi @jmecosta 

Could you tell mo more about this detail mode, or provide a link where it is explained? Should I turn it off somewhere then?

Thank you very much!

**Comment by jmecosta** [comment]
@MattSom this feature is no longer available in 5.6. we just keep this open to see if it comes back in later versions. the doc for pre 5.6 is here https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-test-execution-metrics

**Comment by guwirth** [comment]
The setting `sonar.cxx.xunit.provideDetails` is no longer supported:
* code in Xunit sensor is already removed
* todo: update wiki
