### ISSUE TITLE
GNU C++ compiler Guide

### ISSUE THREAD

**Issue by MattSom** [SonarOpenCommunity/sonar-cxx#912]
Hello,

As I mentioned in a previous post (#907), I am eniterly new to SQ. I would like to make my analyses more and more detailed with integrating the Running Tools as suggested: 
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Running-tools

The G++ part is also not clear to me, sorry if I miss something obvious here again. I have to work with Ubuntu at the moment, thus VS is no good for me, and purely G++ from terminal is a thing I've never used before. As a beginner I find the installation guides here sometimes far too laconic, so I would just need some suggestions whether I'm on the right track here.

As I interpreted the brief guide linked above, I understand I need to build the project to be analysed later in SQ and use the reports created by G++ to do so.

After examining a bit the official GNU site I think I am going to need this for the configuration:
     % mkdir objdir
     % cd objdir
     % srcdir/configure [options] [target]

So this is where I need to set the '-fdiagnostics-show-option' option I guess. I do not understand the target option here though. Also don't know what CFLAGS, CPPFLAGS should mean here. Should I pass these to the compiler somehow?

Capture the warnings into a file and setting config properties will be figured out in the meantime I think however "Activate the rules from the rule repository "compiler-gcc"" is still shady. Do I need to activate these search results? 
![screenshot from 2016-07-07 13 36 49](https://cloud.githubusercontent.com/assets/20301758/16652019/f174a58a-4447-11e6-94b8-d0d8dea0a8f9.png)

Apologies for the long post again, I hope I won't make a nuisance of myself. :) 

Regards

**Comment by guwirth** [comment]
> As I interpreted the brief guide linked above, I understand I need to build the project to be analysed later in SQ and use the reports created by G++ to do so.

@MattSom this plugin is working different compared to others:
* First step is always to run a tool (compiler, cppcheck, unit test coverage, ...) to create a report file.
* Second step is to forward the report to SQ. This plugin is doing in most of the cases no own analysis. It's only responsible for aggregating and visualising the data.

In case of gcc you have to forward the resulting LOG file with the settings
```
sonar.cxx.compiler.parser=GCC
sonar.cxx.compiler.reportPath = ...
sonar.cxx.compiler.regex = ...
sonar.cxx.compiler.charset = ...
```
Regards,

**Comment by guwirth** [comment]
@MattSom please reopen if still an issue
