### ISSUE TITLE
stop feeding unit test metrics in the cxx plugin

### ISSUE THREAD

**Issue by jmecosta** [SonarOpenCommunity/sonar-cxx#914]
seems we will not be able to use the plugin in a context where there are multiple languages with multiple tests technologies. for example the cxx plugin and c# plugin will not work in projects that contain tests. currently what happens is the following

- both sensors will try to import unit test metrics at top level project. one will fail with duplicated meaasure execption
- saving measures inside the modules looks sonar does not aggregate those to top level project, so only if navigating modules we will see something relevant.

proposal:
- remove the unit and dot net stuff
- create a new plugin or use http://docs.sonarqube.org/display/PLUG/Generic+Test+Coverage

**Comment by guwirth** [comment]
> seems we will not be able to use the plugin in a context where there are multiple languages with multiple tests technologies.

* First of all I think that is a special use case. Most users do not use the multi language support. 
* think also it's a general problem all other plugins supporting test and coverage metrics will also have. Think we should have a look how they are solving it. Maybe ask in the forum. 
* Different test technologies are easy to solve. Report must follow unique filename pattern (e.g. Boost Test *.boost.xml). Each sensor can read then only his files. This is how it is already working today.
* multiple languages: each plugin must handle its own files only. The c++ plugin .cpp files only; the csharp .cs and so one. Same must be valid for handling test and coverage reports: assign metrics only to files which belongs to this language plugin.
* last but not least: if someone don't wanna use our sensors he can disable it by assigning no values to the config items.

So I'm against removing it.

**Comment by jmecosta** [comment]
it makes sense when earlier we pointed a test to resource. this seems that will be removed and we will have sonar only showing the ammout of existent unit tests. for that reason a top level sensor is enought to cover all scenarios. 

by far and c# + C++/CLI + c++  scenario is not at all a uncommon scenario, its somethign you will find in almost microsoft shop. Being the msbuild runner atm the default for such scenarios these will for sure come up in future.

however as you mention anyone can just disable those features in the C++ plugin, so is not at all a blocking problem in most cases. 

we in our case are unable to use the c++ plugin because of this problem, so we should document this limitaion in the wiki.

**Comment by jmecosta** [comment]
created a solution for us https://github.com/jmecosta/sonarqube-unittest-plugin
