### ISSUE TITLE
Parser failed to parse those code

### ISSUE THREAD

**Issue by qduyang** [SonarOpenCommunity/sonar-cxx#915]
Hi,

Please help checking the attached parser failures that all cause affected files' lines to be 0.

Sonar-cxx version: 0.9.6 (latest)
Sonarqube version: 5.6 (latest)

Let me know if need more information.

![sonar-cxx-paser-error-1](https://cloud.githubusercontent.com/assets/5174044/16977353/2201ff8c-4e88-11e6-8e38-b87a20804ff6.png)
![sonar-cxx-paser-error-2](https://cloud.githubusercontent.com/assets/5174044/16977355/2202d344-4e88-11e6-84d7-a8046f95f570.png)
![sonar-cxx-paser-error-3](https://cloud.githubusercontent.com/assets/5174044/16977352/22003846-4e88-11e6-9853-a485d04c5d12.png)
![sonar-cxx-paser-error-4](https://cloud.githubusercontent.com/assets/5174044/16977350/21fe83fc-4e88-11e6-8a14-4908e8ac8369.png)
![sonar-cxx-paser-error-5](https://cloud.githubusercontent.com/assets/5174044/16977354/2201eb82-4e88-11e6-8ecf-6ed778840a27.png)
![sonar-cxx-paser-error-6](https://cloud.githubusercontent.com/assets/5174044/16977356/2206e42a-4e88-11e6-82b2-caddc752d1b8.png)

**Comment by guwirth** [comment]
@qduyang please try to download and use the cxx toolkit from here: https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-0.9.6/sslr-cxx-toolkit-0.9.6.jar. With this toolkit you can play around with the code to isolate the problem.

* read https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors
* a fast workaround is also to use error recovery: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Error-Recovery

**Comment by qyangdu** [comment]
Thanks @guwirth, after fixed all the 'cannot find source' errors and defined some external macroes, the parser failures unfortunately still exist.

but the error recovery helped skipped the errors.

**Comment by guwirth** [comment]
@qduyang could you provide a simple sample created with the cxx-toolkit to reproduce the problem please?

**Comment by guwirth** [comment]
@qduyang please reopen if still an issue
