### ISSUE TITLE
report result error

### ISSUE THREAD

**Issue by ilovezhibin** [SonarOpenCommunity/sonar-cxx#916]
![image](https://cloud.githubusercontent.com/assets/6346578/17044323/a0cdc6f6-4ff1-11e6-95db-e6718a5e6f54.png)
like this:sonar.cxx.cppcheck.reportPath=report1.xml,report2.xml
but it can't work,you sure split by comma?

**Comment by guwirth** [comment]
Hi @ilovezhibin, code reading the property is here
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/utils/CxxReportSensor.java#L129
* https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/config/Settings.java#L241

Would turn debugging on to see which reports are read:
* https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information

Regards,
