### ISSUE TITLE
preprocessor operator "defined" not supported

### ISSUE THREAD

**Issue by jeremfg** [SonarOpenCommunity/sonar-cxx#920]
It seems the "defined" preprocessor operator is not supported.
I get the following in my logs:

14:25:48.491 WARN  - Error evaluating expression '' for AstExp 'IDENTIFIER: defined', assuming 0

**Comment by guwirth** [comment]
@jeremfg this means typically that a symbol the preprocessor is parsing is undefined. The preprocessor set the value to 0 then. Pleases turn debug information on to get more information (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information).
Think there are macros missing for your environment: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces

**Comment by jeremfg** [comment]
@guwirth,
I agree this error usually means that a symbol is undefined. However, this would be an illegal name for a preprocessor symbol in the first place!!

'defined' is kinda of a preprocessor keyword, an operator used in conjunction with the likes of `#if`, `#elif`.... It is used to do things such as:
`#if defined (__vax__) || defined (__ns16000__)`
If I was to use such a name for a macro, the compiler wouldn't like it.

> You may define any valid identifier as a macro, even if it is a C keyword. The preprocessor does not know anything about keywords. This can be useful if you wish to hide a keyword such as const from an older compiler that does not understand it. **However, the preprocessor operator defined ([see Defined](https://gcc.gnu.org/onlinedocs/cpp/Defined.html#Defined)) can never be defined as a macro**, and C++'s named operators ([see C++ Named Operators](https://gcc.gnu.org/onlinedocs/cpp/C_002b_002b-Named-Operators.html#C_002b_002b-Named-Operators)) cannot be macros when you are compiling C++.

https://gcc.gnu.org/onlinedocs/cpp/Macros.html

Now I do not consider myself a specialist of the C language, but the this look like a bug to me in the plugin.

**Comment by guwirth** [comment]
> It seems the "defined" preprocessor operator is not supported.

@jeremfg looking to the code:
* preprocessor keywords: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/src/main/java/org/sonar/cxx/api/CppKeyword.java
* preprocessor grammar with `defined`: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/src/main/java/org/sonar/cxx/preprocessor/CppGrammar.java#L312
* found also some unit tests: https://github.com/SonarOpenCommunity/sonar-cxx/blob/a227c90869df67023deeecbb3e43148d6eb7a3ae/cxx-squid/src/test/java/org/sonar/cxx/preprocessor/CppGrammarTest.java#L336

`defined`is very common in header files. Don't believe that it is not supported in general?
Could you provide a reduced sample where the problem occurs please?

**Comment by jeremfg** [comment]
Thanks a lot for pointing this all out,

I'll see if I can provide a sample that show it failing.

**Comment by jeremfg** [comment]
Your feedback has proven quite useful as I was able to better understand the debug output.
I was mistaken, it really was a missing define to be provided via **sonar.cxx.defines**.

What confused me was the fact I would see the line `14:25:48.491 WARN - Error evaluating expression '' for AstExp 'IDENTIFIER: defined', assuming 0` appear dozen of times, as if it happened every time the keyword was encountered. A wrong assumption!

Turns out it was always happening on the same header file included everywhere internally by ASF (Atmel Software Framework). It appears we don't need this define when we compile so it caused a discrepancy between what we pass to the compiler and what we pass to sonar. Adding the missing define as extra for sonar analysis alone solved it.

Furthermore, I've noticed that particular file, `io.h`, uses a different mechanism that relies on values for specific macros. If they are not defined, this would result in `#if ()` with empty parentheses, thus explaining the empty `''` expression in the error message.

Thanks for your help!

**Comment by Bertk** [comment]
The grammer for defined operator has to be checked because it shall only be used for #if or #elif directive (see https://msdn.microsoft.com/en-us/library/ew2hz0yd(VS.80).aspx). This limitation is not implemented in current preprocessor grammar.
