### ISSUE TITLE
Understanding lex error consequences

### ISSUE THREAD

**Issue by jeremfg** [SonarOpenCommunity/sonar-cxx#922]
I'm looking for some help understanding our biggest issue currently with sonar-cxx usage.
I believe this **could** be related to #676 but I'm not sure...

This all relates to whether or not I decide to include some paths via **sonar.cxx.includeDirectories** which requires paths outside of the project directory.

We use gcc-arm and the command below to dynamically obtain the list of default include directories before passing them to sonar
`gcc -v -x c -E /dev/null 2>&1`

If I don't pass the gcc directories, I get statistics that makes sense (Lines of codes, code coverage percentage, etc.). However I will get multiple errors because it cannot find included files such as `stdint.h`, `stdbool.h`, `stddef.h`, etc.

Adding the gcc directories fixes the file that aren't being found. However it completely screws up the statistics. I get 10% line count of what I used to have, which causes statistics such as code coverage to grow artificially high and such. It seems that most of the files aren't being analyzed anymore for issues.

What led me to believe there's a link with #676 is the fact that I now get a message that seems to come from the dependency analyser
`Unable to find resource xxxx to create a dependency with...`,
My understanding is that it's now fixed (by removing the feature from sonar-cxx) with SonarQube 5.0+ and the later changes in sonar-cxx to support SQ's 5.6 API.

In any case, it didn't made much sense in my head that a failure from the dependency analyser would cause a unrecoverable error that would prevent the parsing of files for other issue analysis. Even with `sonar.cxx.errorRecoveryEnabled=true`.

However, I later noticed that I also get a bunch of new errors in this form after adding the 3 GCC directories to **sonar.cxx.includeDirectories**:
```
19:46:22.917 ERROR - Unable to parse file: C:\git\smv6-6lr-core\include\log6lrCore.h
19:46:22.918 ERROR - Lexer error: Unable to lex url: file:/C:/git/smv6-6lr-core/include/log6lrCore.h
```

I believe this is the real issue that screws up my statistics and prevents most files from being analyzed.

Sorry for the long-winded post, I'm trying to explain my thought process and where I'm at with all this. My questions:

1. Is my thinking in any way correct? Or am I completely off?
2. Are the parsing/lexer errors the probable root cause of screwed up statistics and incomplete analysis?
3. Have any idea or clue as to why adding extra directories (outside of the project *hint*) might cause the parser/lexer to fail at reading/parsing most files **within** our project? Perhaps the same issue with absolute paths outside the project as encountered by the dependency analyser when the other plugins follow `#include` directives?
4. Any suggestion on how to investigate this any further if it's something else entirely?

Currently we prefer the failure of failing to find standard c headers (and all it's consequences like missing macros and multiple other `syntax error, skip` errors) than having screwed up statistics and very few files analysed.

P.S. Currently using SQ 4.5.4 and sonar-cxx 0.95

**Comment by guwirth** [comment]
Hello @jeremfg,

some hints:
* Normally it is not necessary to add system include path or path of libraries like Boost. Adding this libraries is only slowing down the parsing time.
* The better way is to add or mock macros to have valid code afterwards: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces
* See also: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors
* Here are some samples:
  * https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/resources/macros/VS10Macros.h
  * https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/resources/macros/GxxMacros.h

Hope this helps.

Regards,

**Comment by jeremfg** [comment]
Understood. I'll have a look at mocking the rest instead of trying to include it, but there's a lot of it ;-)

Does this mean you usually "live" with the fact you're gonna get errors for every `#include` that aren't found? Or is there a common way of dealing with this as well?

Time isn't really an issue, when compared to cppcheck which takes ages to complete.

Still curious though... Is there an issue with absolute paths outside the project that affects more than the dependency analyser?

**Comment by guwirth** [comment]
> Does this mean you usually "live" with the fact you're gonna get errors for every #include that aren't found? 

Yes. As long as the parser is able to understand the **syntax** the headers are not needed. The point with the cxx plugin is anyway that most metrics come from external tools e.g. cppcheck, unit test tool, coverage tool, ...

> Time isn't really an issue, when compared to cppcheck which takes ages to complete.

Also cppcheck we are using without system header files (think this is the recommended way).

> Still curious though... Is there an issue with absolute paths outside the project that affects more than the dependency analyser?

Our integration tests have some projects with realtive and absolute paths inside and outside of project root. So I'm not aware of any issues.

**Comment by jeremfg** [comment]
> Yes.

Perhaps we should create an option to silence this kind of errors then? Considering this is the intended behavior+usage of the plugin.
I'm thinking of the hypothetical scenario where you want to detect errors from the console during build and fail it when they occur, like Jenkin's plugins or even SQ's build breaker.

> Also cppcheck we are using without system header files (think this is the recommended way).

I didn't even dare to try adding the system headers to cppcheck ;)

> Our integration tests have some projects with realtive and absolute paths inside and outside of project root. So I'm not aware of any issues.

Ok, still no idea why the parser failed to parse internal project files when I previously had paths outside my project set in the `sonar.cxx.includeDirectories` property. It's no longer the case so perhaps it's related to something else like mixed Path styles which works with one part of cxx and not with others. Always a bit hard to track path styles with a combination of Java, Windows and MSYS.

**Comment by guwirth** [comment]
> Understanding lex error consequences

* First I would play around with https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-0.9.6/sslr-cxx-toolkit-0.9.6.jar. With this tool you can try out which grammar is supported an which not.
* cox plugin is
  * Using the internal preprocessor first. Relative and absolute paths are supported for includes. In case of relative paths it is using sonar.cxx.includeDirectories to create absolute paths. Trying it one after the other from left to right. This step is creating the resulting source code. 
  * Next step is to create the AST with the parser. This is only a syntax check without a semantic check.
  * source files must be always below root (header files can be outside)
  * issues in report files must point always to an existing source file / line number
