### ISSUE TITLE
Support for _Pragma operator (C99)

### ISSUE THREAD

**Issue by jeremfg** [SonarOpenCommunity/sonar-cxx#924]
I'm encountering a parsing issue with a macro expansion that results into a `_Pragma` operator being generated.

**C99** introduced the `_Pragma` operator to solve the issue where a macro cannot expand into a `#pragma` directive.
[GCC's documentation on the subject](https://gcc.gnu.org/onlinedocs/cpp/Pragmas.html)

Is it supposed to be supported currently by sonar-cxx? I haven't noticed anything to support this...

EDIT: I confirm that the workaround is to mock `_Pragma` with a define.

**Comment by guwirth** [comment]
@jeremfg `_Pragma` is a C99 feature and easy to mock with `#define _Pragama(...)`. So I think we should not extend the preprocessor grammar and close this issue.

**Comment by jeremfg** [comment]
I'm fine with that.
