### ISSUE TITLE
Parsing error with union nested within struct (C99)

### ISSUE THREAD

**Issue by jeremfg** [SonarOpenCommunity/sonar-cxx#925]
I've attached example [union.c](https://github.com/SonarOpenCommunity/sonar-cxx/files/400335/union.c.txt) and [union.h](https://github.com/SonarOpenCommunity/sonar-cxx/files/400338/union.h.txt) that triggers the parsing failure.

From my test, it seems that it doesn't like the fact that the union's member is accessed directly to assign a value during initialization:
```C
const Astruct aVariable =
{
		10,
--->  	.aUnion.bMember = 0,
		13
};
```

However, when initialized implicitely like shown below, it works:
```C
const Astruct aVariable =
{
		10,
		{0},
		13
};
```

**Comment by guwirth** [comment]
@jeremfg there are some compiler/C99 specific extensions supported but not all from C99, see: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-compiler-specific-extensions

**ISO C99: Designated Initializers** (https://gcc.gnu.org/onlinedocs/gcc/Designated-Inits.html)
Support of cascaded structures/unions seems to be  missing: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-squid/src/main/java/org/sonar/cxx/parser/CxxGrammarImpl.java#L1265

**Comment by jeremfg** [comment]
@guwirth,
> there are some compiler/C99 specific extensions supported but not all from C99

I had overlooked that page because of its title. I see there is a ISO section too now and not just compiler-specific stuff. Thanks!

**Comment by guwirth** [comment]
@jeremfg took a little bit longer to find some time to fix it. Should work now with latest snapshot. Please try and give us feedback. Are there any other C99 issues?

Latest snapshot: https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts
