### ISSUE TITLE
Incompatible with sonar 6.0

### ISSUE THREAD

**Issue by guoxiao** [SonarOpenCommunity/sonar-cxx#926]
The following exception is thrown:
```
java.lang.NoSuchMethodError: org.sonar.api.platform.ServerFileSystem.getExtensions(Ljava/lang/String;[Ljava/lang/String;)Ljava/util/List;
	at org.sonar.plugins.cxx.utils.CxxAbstractRuleRepository.define(CxxAbstractRuleRepository.java:66) ~[na:na]
	at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:54) ~[sonar-server-6.0.jar:na]
	at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:97) ~[sonar-server-6.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	
```

**Comment by guwirth** [comment]
Hi @guoxiao thx for your feedback.
The plugin is not tested with SQ 6.0. There are still many deprecated APIs in use which are removed with 6.0 now. In your case https://github.com/SonarOpenCommunity/sonar-cxx/blob/f1750011185fc77f53807f8115afc859b8144a0d/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/utils/CxxAbstractRuleRepository.java#L70. We are working on this but I think it will still take some time. 
Regards

**Comment by ociotec** [comment]
Is there any plan to support SQ 6.0?
Thanks for the great effort all of you do 👍

**Comment by jmecosta** [comment]
we should support 6.0 at some point, but atm we are working on removing deprected apis. after the transitions to 6.0 should be faster

**Comment by guwirth** [comment]
@ociotec you can try with #942. There is currently an AppVeyor CI issue. If this is solved we will merge it.

**Comment by ociotec** [comment]
Thanks a lot! @guwirth I will check it as soon as a new release is available.

**Comment by vanjor** [comment]
good job! expecting for it!

**Comment by mohanss08** [comment]
Hi Team, 

I have query regarding SonarQube-5.6.6(LTS) with sonar-cfamily-plugin Version - 4.8.0

Our Environment details as follows:

SonarQube Server Version - 5.6.6 (64-Bit). 
Operating System – Ubuntu - 14.04.5 LTS (64-Bit). 
mysql  Ver - 14.14 Distrib 5.6.33. 
sonar-cfamily-plugin Version - 4.8.0.7665 and SonarQube C++ Community Plugin Version - 0.9.7

Problem Description:

I have both sonar-cfamily-plugin Version - 4.8.0.7665 and SonarQube C++ Community Plugin Version - 0.9.7 installed, when I tried to start the sonar service, it shows below error.

Also I have tried to previous versions as well, However in all problem is same.  Also observed under General Settings-->C / C++ / Objective-C--> CppCheck tab not appear, Whereas in our previous version of SonarQube-5.1 and (sonar-cpp-plugin-3.2.jar) server, I can see this.

So kindly guide me how to configure the same with SonarQube-5.6.6(LTS).

Rgds,
Mohan

**Comment by jmecosta** [comment]
@guoxiao you cant have both the plugins installed, you need to pick one. If you are paying for the c familiy plugin please keep using it. If you have question regarding with sonar-cpp-plugin please contact their support

**Comment by mohanss08** [comment]
Hi JME,

Actually i have tired only with - (SonarQube C++ Community Plugin Version - 0.9.7) plugin. it was failed to start the service, it was showing below error,

2017.05.25 10:30:24 ERROR web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
org.sonar.api.utils.MessageException: The rule 'cppcheck:uninitVar' is invalid : Constant/issue functions must only have a non empty base effort 

Hence installed 1st sonar-cfamily-plugin Version - 4.8.0.7665  then copied only (SonarQube C++ Community Plugin Version - 0.9.7) jar file to plugin directory, then tried it failed with same error.

Just wanted to know any other dependency plugins do i need install?

-Mohan

**Comment by mohanss08** [comment]
Does it has any dependency with C# plugin, Bcoz i have (sonar-csharp-plugin-5.10.1.1411.jar) installed.

**Comment by mohanss08** [comment]
Tried after removing of sonar-csharp-plugin-5.10.1.1411.jar file and installed with - sonar-cxx-plugin-0.9.7.jar. still unable to start the service. still it failed with below errors.

2017.05.25 13:22:51 ERROR web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
org.sonar.api.utils.MessageException: The rule 'cppcheck:uninitVar' is invalid : Constant/issue functions must only have a non empty base effort 
2017.05.25 13:22:51 ERROR web[o.a.c.c.StandardContext] One or more listeners failed to start. Full details will be found in the appropriate container log file
2017.05.25 13:22:51 ERROR web[o.a.c.c.StandardContext] Context [] startup failed due to previous errors

**Comment by mohanss08** [comment]
![sonarqube-5 6 6_plugins](https://cloud.githubusercontent.com/assets/11677589/26441717/3a76a38c-414f-11e7-8efb-3a80b707a8e6.png)

with these attached picture plugins, i am able to start the service.

**Comment by mohanss08** [comment]
Even tried only with sonar-crowd-plugin-2.0.jar and sonar-cxx-plugin-0.9.7, Still unable to start the service. It fails with the same error.
