### ISSUE TITLE
[question] Build Wrapper

### ISSUE THREAD

**Issue by aqdevcdr** [SonarOpenCommunity/sonar-cxx#927]
Are there any plans to develop a build-wrapper for the sonar-cxx plugin, like the one used by the commercial version?

Thank you!

**Comment by Bertk** [comment]
Hi,
the C++ community plug-in has a build log file parser for VC++ (see **Retrieving compiler information from buildlog** https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers). 
I saw some limitations with build-wrapper for cross platform builds and the build log parser is an alternative approach. Unfortunately only VC++ is supported today.

Best regards
Bert
