### ISSUE TITLE
Is it possible to exclude some files from undocumented API metric ? 

### ISSUE THREAD

**Issue by wichtounet** [SonarOpenCommunity/sonar-cxx#931]
Hi, 

I have documentation issues ignored on some of my files. For instance: 

```
# Ignore all undocumented API issues on test headers
sonar.issue.ignore.multicriteria.noapitest.ruleKey=cxx:UndocumentedApi
sonar.issue.ignore.multicriteria.noapitest.resourceKey=test/include/*
```

However, I was wondering if it was also possible to exclude them from the undocumented API metric ? Currently they are showing as undocumented and making the metric useless. 

I'm using the last version of the plugin and Sonar 5.6. 

Thanks

**Comment by jmecosta** [comment]
metrics and issues are generated in different places, so i am not aware of any method within core or plugin to do this. likely it would can be possible but needs some coding up on the place where the metric is generated and check the those properties.

**Comment by wichtounet** [comment]
That is what I feared and it was confirmed by SonarQube :(

Thanks :)
