### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#932]
Mail to Travis:
```
Dear support team,

Our build on Travis is no more working.

To verify the problem I did a “Restart Build” of a in the past working commit.
This one is also failing now.
https://travis-ci.org/SonarOpenCommunity/sonar-cxx/builds/149108793

Could you have a look please why it is failing now?
Are there any changes on the Travis system?

Thanks for your help.
```

**Comment by guwirth** [comment]
Answer from Travis:

Thank you for getting in touch and sorry to hear you're having problems.

We had a major incident concerning our build images on August 9th where we decided to roll forward with new and fairly untested build images.
You can read about it here https://blog.travis-ci.com/2016-08-16-gce-images-precise-trusty-outage/

My first thought is that it might be related to your builds suddenly failing. 
Can you confirm that they started failing around that time?

If so, we can further investigate what is causing the error and report back to our infrastructure team so they can fix it.

Sorry for the troubles!

**Comment by guwirth** [comment]
**Answer from Travis:**

Thanks for the email. Can you tell from the logs *why* SonarQube fails to start? I looked at the log files you dump in "after_failure", but they are not particularly instructive.

**Comment by guwirth** [comment]
Looking to the LOG file you see:
```
starting SonarQube ... FAILED
Cannot start SonarQube from '/tmp/sonarqube-5.6', exiting
```
https://travis-ci.org/SonarOpenCommunity/sonar-cxx/jobs/149108794#L2978

The LOG from SonarQube is some lines below, here I can’t see an error:
https://travis-ci.org/SonarOpenCommunity/sonar-cxx/jobs/149108794#L2983

For my understanding it fails in travis.yml:
```
script:
        - mvn install -DskipTests=true
        - mvn test
        - RAILS_ENV=production PATH=$PATH:/tmp/sonar-scanner-2.6/bin TestDataFolder=~/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata behave --no-capture
```     
Behave is using
https://github.com/SonarOpenCommunity/sonar-cxx/blob/aa3241ac44bb3ca96963a3ad245483cd15e6373a/integration-tests/features/environment.py 
which is failing in line 83: https://github.com/SonarOpenCommunity/sonar-cxx/blob/aa3241ac44bb3ca96963a3ad245483cd15e6373a/integration-tests/features/environment.py#L83
starting SonarQube is in https://github.com/SonarOpenCommunity/sonar-cxx/blob/aa3241ac44bb3ca96963a3ad245483cd15e6373a/integration-tests/features/environment.py#L158
```
def start_sonar(sonarhome):
    sys.stdout.write(INDENT + "starting SonarQube ... ")
    sys.stdout.flush()
    now = time.time()
    start_script(sonarhome)
    if not wait_for_sonar(50, is_webui_up):
        sys.stdout.write(RED + "FAILED\n" + RESET)
        return False

    sys.stdout.write(GREEN + "OK, duration: %03.1f s\n" % (time.time() - now)
                     + RESET)
    return True
```
Which is failing now. Maybe the problem is the 50s timeout?
Is your system slower now?

**Comment by guwirth** [comment]
After commit 'wait 60s for SonarQube start (instead of 50s) ' (https://github.com/SonarOpenCommunity/sonar-cxx/commit/cccaee43e9cf1eec098db5e2abee67b87187b752) it seems to work again.

@all: please rebase your pull requests

**Comment by guwirth** [comment]
Mail to Travis:

I did some more tests:

* Uploading a branch which is green after build; merging it to master => red on master?
* Create a new branch of another branch which was green => red after new pull request?

Any ideas?

**Comment by jmecosta** [comment]
Is this caused by timeout? Or the server does actually not start? Or we
don't know?

**Comment by guwirth** [comment]
@jmecosta looking to the LOG file building and running the unit tests is always working. The problem is the detection of the start of SonarQube.
* I played around with the timeout times (increased it from 50s to 120s) - without success
* I changed the HTTP response detection (waiting not only for 200) - without success
* I verified the LOG file of the SonarQube start: no error in the LOG file

Problems seems to be that:
* SQ server is not starting properly (without error message in the LOG file)?
* or that server is not answering on the HTTP request?

**Comment by SonarOpenCommunityAdmin** [comment]
in the condition:

def is_webui_up():
    try:
        return urllib.urlopen(SONAR_URL).getcode() == 200
    except IOError:
        return False

try to put a logging for the error code that is returned or print the exception that we get. and run behave with debug information on. behave.exe --no-capture

**Comment by guwirth** [comment]
@jmecosta we are always in `IOError` with message
`[Errno socket error] [Errno -2] Name or service not known`

**Comment by guwirth** [comment]
Got mail from Travis to ry this https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
