### ISSUE TITLE
Lines of Code reporting a sizable difference after sonar/plugin upgrade

### ISSUE THREAD

**Issue by rohit-venkat** [SonarOpenCommunity/sonar-cxx#936]
Hi, 
We have been using the V0.9.1 version of the plugin, with an older version of Sonar. We decided to upgrade to Sonar 6.0 and the V0.9.6 version of the plugin. The LOC on the initial installation reported 1.6 million lines of code, but the new version reports 600K. I did notice there was a change to LOC component  in Version V0.9.5. but what was changed? This has us worried that the metrics that we are collecting may not be accurate. The scanned Source code hasn't changed by that big an extent. 

![image](https://cloud.githubusercontent.com/assets/20080658/18064101/7bfa5eaa-6df3-11e6-8e26-5f32c6c405cf.png)

Thanks

**Comment by guwirth** [comment]
Hello @rohit-venkat I'm sorry but SQ 6.0 is not supported yet. We are aware of problems and using not up to date APIs (see also #926 and https://github.com/SonarOpenCommunity/sonar-cxx/wiki/SonarQube-compatibility-matrix).

**Comment by rohit-venkat** [comment]
Hey @guwirth Thanks for getting back to me.. I had a quick look at our sonar instance, it looks like we are running Sonar version 5.6 with the V0.9.6 version of the plugin my apologies.

**Comment by jmecosta** [comment]
So what was the previous version you were using? Such a big drop I've only
seen when test files metrics stop counting to the stats

**Comment by guwirth** [comment]
@rohit-venkat looking to your screenshot
* the number of directories and files is nearly the same
* the number of LOC is even higher
* only CLOC is lower

Could also be that the parser is not able to parse the files and detect the source code? maybe you should turn logging on to see what's going on internally: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information. If parsing is the problem have a look to: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Dealing-with-compiler-specific-code-pieces.

Other idea is to enable `sonar.cxx.errorRecoveryEnabled=True` (https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors).

**Comment by rohit-venkat** [comment]
To answer @jmecosta , we were using Sonar 4.5.1 and the V0.9.1 version of the plugin. 
@guwirth I'll give the both options a try. and get back to you folks. Thanks
