### ISSUE TITLE
Ignoring/excluding warnings from squidsensor

### ISSUE THREAD

**Issue by sandeepm** [SonarOpenCommunity/sonar-cxx#948]
Hi,

I have a jenkins jobs that grabs some c source , conducts cppcheck on it and starts sonar analysis. 
The cppcheck completes successfully and then upon execution of sonar scanner, I am seeing errors like below-

INFO: Sensor Sonar-Sonargraph-Plugin [3.5] (done) | time=1ms
INFO: Sensor CxxSquidSensor
WARN: [/usr/include/x86_64-linux-gnu/gnu/stubs.h:7]: cannot find the sources for '# include <gnu/stubs-32.h>'
WARN: [/home/jenkins/workspace/source/main.c:51]: syntax error, skip 'A_proginfo'
WARN: [/home/jenkins/workspace/source/main.c:134]: syntax error, skip 'main'
WARN: [/home/jenkins/workspace/source/main.c:150]: syntax error, skip 'c'
..

At this stage I am only interested in conducting the cppcheck on the source and getting the sonar scanner to go through the cppcheck reports and use/display the data from cppcheck without conducting any build or further checks.

Is there a way to prefereably configure the cxx plugin to only go through cppcheck results and display that data instead of doing further checks on source code as its trying to do above? 
If not is there a way to exclude the above warnings or disable them through the sonar.properties file?

Fyi following are my current settings - 

sonar.projectKey=com.jtest.sample:some-test
sonar.projectName=all::test
sonar.projectVersion=3.1
sonar.sources=workspace/source
sonar.cxx.cFilesPatterns=.c
sonar.cxx.c.suffixes.sources=.c
sonar.cxx.cppcheck.reportPath=reports/cppcheck/*.xml
sonar.cxx.includeDirectories=/usr/include/pcap/,/usr/include/x86_64-linux-gnu/sys/,/usr/include/x86_64-linux-gnu/,/usr/lib/gcc/x86_64-linux-gnu/4.8/include,/usr/include/,/usr/include/libxml2/
sonar.cxx.errorRecoveryEnabled=True

**Comment by guwirth** [comment]
> Is there a way to prefereably configure the cxx plugin to only go through cppcheck results and display that data instead of doing further checks 

Hi @sandeepm it's not possible without reading the source file. SQ must first read the sources into the database and in a second step the sensors are assigning issues to the source files. Issues for not existing sources (line numbers) are ignored.

Would set `sonar.cxx.errorRecoveryEnabled=True` to read in also files which could not be parsed without errors. See also https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors.

```
WARN: [/usr/include/x86_64-linux-gnu/gnu/stubs.h:7]: cannot find the sources for '# include '
WARN: [/home/jenkins/workspace/source/main.c:51]: syntax error, skip 'A_proginfo'
```

You can ignore these warnings but some SQ core metrics are worse then (LOC, CLOC, COMPLEXITY, ...).

**Comment by sandeepm** [comment]
Thansk @guwirth . Will try as per  https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Detect-and-fix-parsing-errors.
