### ISSUE TITLE
Plugin can not install

### ISSUE THREAD

**Issue by MarkAtIntemo** [SonarOpenCommunity/sonar-cxx#95]
What could be the problem here ??
Below the logfile trace.
OS: Ubuntu 12.04.3 LTS (Updated)

2013.12.24 12:40:18 INFO  o.s.a.Connectors  HTTP connector is enabled on port 9000
2013.12.24 12:40:18 INFO  o.a.c.h.Http11Protocol  Initializing ProtocolHandler ["http-bio-0.0.0.0-9000"]
2013.12.24 12:40:18 INFO  o.a.c.c.StandardService  Starting service Tomcat
2013.12.24 12:40:18 INFO  o.a.c.c.StandardEngine  Starting Servlet Engine: Apache Tomcat/7.0.42
2013.12.24 12:40:19 INFO  o.a.c.s.ContextConfig  No global web.xml found
2013.12.24 12:40:20 INFO  o.s.s.p.ServerImpl  SonarQube Server / 4.0 / 2145d0b3cf5d8148b9a29ce3d186b725a0648185
2013.12.24 12:40:20 INFO  o.s.c.p.Database  Create JDBC datasource for jdbc:mysql://localhost:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
2013.12.24 12:40:23 INFO  o.s.s.p.DefaultServerFileSystem  SonarQube home: /opt/sonar
2013.12.24 12:40:23 INFO  o.s.s.p.DefaultServerFileSystem  Deploy dir: /opt/sonar/web/deploy
2013.12.24 12:40:23 INFO  org.sonar.INFO  Install plugins...
2013.12.24 12:40:23 ERROR o.s.s.p.PlatformLifecycleListener  Fail to start server
java.lang.IllegalStateException: Unable to read plugin manifest from jar : /opt/sonar/extensions/plugins/sonar-cxx-plugin-0.9.jar
<------>at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:115) ~[sonar-update-center-common-1.8.jar:na]
<------>at org.sonar.core.plugins.PluginInstaller.extractMetadata(PluginInstaller.java:109) ~[sonar-core-4.0.jar:na]
<------>at org.sonar.server.plugins.PluginDeployer.registerPlugin(PluginDeployer.java:102) ~[PluginDeployer.class:na]
<------>at org.sonar.server.plugins.PluginDeployer.loadUserPlugins(PluginDeployer.java:97) ~[PluginDeployer.class:na]
<------>at org.sonar.server.plugins.PluginDeployer.start(PluginDeployer.java:72) ~[PluginDeployer.class:na]
<------>at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_27]
<------>at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.6.0_27]
<------>at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.6.0_27]
<------>at java.lang.reflect.Method.invoke(Method.java:622) ~[na:1.6.0_27]
<------>at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110) ~[picocontainer-2.14.3.jar:na]
<------>at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89) ~[picocontainer-2.14.3.jar:na]
<------>at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84) ~[picocontainer-2.14.3.jar:na]
<------>at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169) ~[picocontainer-2.14.3.jar:na]
<------>at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132) ~[picocontainer-2.14.3.jar:na]
<------>at org.picocontainer.behaviors.Stored.start(Stored.java:110) ~[picocontainer-2.14.3.jar:na]
<------>at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1015) ~[picocontainer-2.14.3.jar:na]
<------>at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1008) ~[picocontainer-2.14.3.jar:na]
<------>at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:766) ~[picocontainer-2.14.3.jar:na]
<------>at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:91) ~[sonar-plugin-api-4.0.jar:na]
<------>at org.sonar.server.platform.Platform.startDatabaseConnectors(Platform.java:245) ~[Platform.class:na]
<------>at org.sonar.server.platform.Platform.init(Platform.java:193) ~[Platform.class:na]
<------>at org.sonar.server.platform.PlatformLifecycleListener.contextInitialized(PlatformLifecycleListener.java:35) ~[PlatformLifecycleListener.class:na]
<------>at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939) ~[tomcat-embed-core-7.0.42.jar:7.0.42]
<------>at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434) ~[tomcat-embed-core-7.0.42.jar:7.0.42]
<------>at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[tomcat-embed-core-7.0.42.jar:7.0.42]
<------>at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559) ~[tomcat-embed-core-7.0.42.jar:7.0.42]
<------>at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549) ~[tomcat-embed-core-7.0.42.jar:7.0.42]
<------>at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) ~[na:1.6.0_27]
<------>at java.util.concurrent.FutureTask.run(FutureTask.java:166) ~[na:1.6.0_27]
<------>at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146) ~[na:1.6.0_27]
<------>at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.6.0_27]
<------>at java.lang.Thread.run(Thread.java:701) ~[na:1.6.0_27]
Caused by: java.util.zip.ZipException: error in opening zip file
<------>at java.util.zip.ZipFile.open(Native Method) ~[na:1.6.0_27]
<------>at java.util.zip.ZipFile.<init>(ZipFile.java:132) ~[na:1.6.0_27]
<------>at java.util.jar.JarFile.<init>(JarFile.java:151) ~[na:1.6.0_27]
<------>at java.util.jar.JarFile.<init>(JarFile.java:115) ~[na:1.6.0_27]
<------>at org.sonar.updatecenter.common.PluginManifest.<init>(PluginManifest.java:110) ~[sonar-update-center-common-1.8.jar:na]
<------>... 31 common frames omitted
<-- Wrapper Stopped

**Comment by swatithakare** [comment]
How to get permission to a specific jar file/maven dependency

**Comment by jmecosta** [comment]
@swatithakare can you share the build error in the sonar.log? assuming that you cover the:

- Check if the .jar achive is consistent and can be unpacked via unzip.
- Look at permissions, especially: does the user sonar runs with has enough permissions to read the jar file?

**Comment by swatithakare** [comment]
Thank you  jmecosta for your quick response
1 .jar can be unpacked via unzip
2 How can I check the permissions ?

**Comment by swatithakare** [comment]
[sonar.txt](https://github.com/SonarOpenCommunity/sonar-cxx/files/649029/sonar.txt)

**Comment by jmecosta** [comment]
But that's from jdoctor plugin, not this plugin

**Comment by jmecosta** [comment]
I don't know, you can try to ask in sonar Google groups since this is a
general development question

**Comment by swatithakare** [comment]
Ok fine.  Thank you for your help :)
