### ISSUE TITLE
JDK 9 not supported (building the plugin)

### ISSUE THREAD

**Issue by ociotec** [SonarOpenCommunity/sonar-cxx#957]
Just an small issue regarding the wiki about building the plugin.

With Ubuntu 16.04 I was not able to build the plugin, after a few tests I achieved just switching back from JDK 9 to 8.

Please consider to indicate this as a requirement in the wiki (now only JDK 7 or greater is required).

Thanks.

**Comment by guwirth** [comment]
Hi @ociotec Java 9 is not released yet (http://www.java9countdown.xyz). We do not test it. Will add a hint to the release notes.
