### ISSUE TITLE
Public API should be documented

### ISSUE THREAD

**Issue by rlucca** [SonarOpenCommunity/sonar-cxx#958]
Hi there,

I'm getting this violation in this code. Is it correct?

C.h:
class C {
    public:
         int get();
};

C.cpp:
/** Return 42 */
int C::get() { return 42; }

**Comment by guwirth** [comment]
Hi @rlucca, that's the normal behavior. It detects public API. Public and visible are the header files in C/C++.  Would anyway recommend to document always in header files. Also other tools like tooltips from VS are looking there.

**Comment by rlucca** [comment]
I understand your point. My question is because for doxygen it is valid document a public API in CPP files.

**Comment by guwirth** [comment]
@rlucca think doxygen and this sensor have different goals. The goal of doxygen is to create a complete documentation this sensor tries to find documented/undocumented public API. Comments in source code files are not public and visible for others.
