### ISSUE TITLE
CppCheck 1.75 support

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#963]
Support of latest CppCheck 1.75 version.

**Comment by Bertk** [comment]
@guwirth 
I checked the cppcheck V1.75 already and could not find additional checks ( rules). The next version 1.76 is due in 4 days and we should check this release (http://trac.cppcheck.net/query?status=closed&group=resolution&milestone=1.76)

**Comment by guwirth** [comment]
@Bertk ok.  Was not clear for me that you already checked it.  Thx. Will close it and add 1.75 label to release notes.
