### ISSUE TITLE
Compilers wiki page incorrect for g++? 

### ISSUE THREAD

**Issue by jcgarnier** [SonarOpenCommunity/sonar-cxx#965]
Dear all,

I just configured this excellent sonar-cxx plugin for my project built with g++. 
I struggled a bit with the regex presented in this [page](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Compilers).
The page states that this should be the regex: 

> sonar.cxx.compiler.regex=^(.*):([0-9]+):[0-9]+: warning: (.*)\\[(.*)\\]$

While after debugging for a moment I figured out I needed this regex:
> sonar.cxx.compiler.regex=^(.*):([0-9]+): warning: (.*)\\[(.*)\\]$

Is sonar-cxx expecting some other g++ flags that are not documented?
Or maybe the page needs a small update (note: I realize I can edit the page, I didn't try, I think it goes beyond my privileges ...)

Thank you for the clarification,
Jc

**Comment by guwirth** [comment]
Hi @jcgarnier thanks for your feedback. I'm VC user and can't tell you what's right. Googling a little bit I found both formats: with and without column number. So I don't know if there was a change? Feel free to add your version to the wiki. Please add also the gcc version you are using (like below with VC).

**Comment by jcgarnier** [comment]
Hi @guwirth ,
I edited the page. I didn't find a nice way to use a table as in the VC example you suggested, because I do not know with which version gcc changed its default behavior and removed/added the column number, and an option of gcc can disable the column number as well. So the first column size was expanding too much for my taste ...

Feel free to improve it.

Greetings,
Jc

**Comment by guwirth** [comment]
@jcgarnier thx for your update
