### ISSUE TITLE
How to analyze all lines of code ? 

### ISSUE THREAD

**Issue by wichtounet** [SonarOpenCommunity/sonar-cxx#973]
Hi, 

I just figured out that not all code is counted as code due to preprocessor. In my current project, I have a lot of code that is conditionally activated by the user using macros. 

By defining the macros of conditional code, I was able to make Sonar count more code (+5K...) which also made me realize that this code was not analyzed before and gave +10d of debt :cry: However, there is still the code that is on the other part of the condition (the #else) that is not analyzed. 

Is there anyway I can make Sonar analyze all this code ? In my tests, I do compile and test the program under all possible conditions. Ideally, I could analyze the project several times and concatenate the results, but I guess that something like this would be very hard (impossible?) to implement. 

Thanks

**Comment by guwirth** [comment]
Hi,

There is currently no way to do this.

* Typically there are a lot of definition done by the preprocessor. I fear trying to analyse everything in one run will result in a lot of syntax errors?
* doing it like cppcheck would mean to run the analyser several times with different combinations to hit all paths

Regards

**Comment by guwirth** [comment]
@wichtounet  I close this, please reopen if still an issue.
