### ISSUE TITLE
SonarQube Scanner Analysis behind reverse proxy failing

### ISSUE THREAD

**Issue by Saravanavel04** [SonarOpenCommunity/sonar-cxx#975]
Dear Techies,

We have SonarQube in AWS cloud (Ex: http://awssonar:9000/sonar/), running behind Spring boot proxy(on port 80 ) and we are running SonarQube scanner from a local system.  We do not have direct access to SonarQube server, it is routed only through proxy server.

Sonar-scanner.properties on local machine points to proxy URL –Ex:  http://proxysonar/sonar that is internally redirected to awssonar on 9000.

Analysis of project happens successfully and reports are available in .sonar local folder. In  the console, we also see that the reports got successfully uploaded to SonarQube server. However, inside awssonar, we are not able to see the report zip inside <SonarQube server>/data/ce/reports.

Due to this, Background Task of SonarQube is failing with Zip exception. And hence we are not able to see the results on the Web dashboard.

We are using SonarQube 5.6.1 with SonarQube Scanner 2.8. We have also tried combinations of SonarQube 6.0, SonarQube Scanner 2.6. We use Java, JavaScript, CSharp and CSS plugins for analysis.

AWS servers are Windows 2012 servers. Local machine is Windows 7. All machines have JDK 1.8.xx.

**Comment by jmecosta** [comment]
Hi

This issue tracker is to be used for the c++ cxx plugin,  your problem is
related with SonarQube core. So I recommend opening a query in
stackoverflow or sonar Google groups to address this problem
