### ISSUE TITLE
FYI: Starting preparation of 0.9.7 release

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#978]
Hi everyone,

Like to start the 0.9.7 release preparation. The 0.9.7 release is a bigger step. There are many API changes. So I would like to ask all for testing and feedback.
- release for SQ 5.6, 6.0 and 6.1
- I marked all remaining issues: 0.9.7 or 'subsequent release'. Some [bugs / issues are still open (see issue tracker)](https://github.com/SonarOpenCommunity/sonar-cxx/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.9.7).
- update of Wiki / documentation is open
- testing feedback is open
- target date is 30th of October

What are you thinking? Any other points?

Regards,
Günter

**Comment by jmecosta** [comment]
@guwirth still push the ignore invalid issues

**Comment by guwirth** [comment]
Some first feedback from my side:
* try to convert our projects from SQ V5.1.2, cxx plugin 0.9.5 to SQ V5.6.3, cxx plugin 0.9.7-SNAPSHOT

**findings:**
* **Coverage** is different because of no more working `forceZeroCoverage` (#909).
* **Duplications** are increased because (#953, #941, #946). Need to be verified again.
* **Technical debt** is lower because of deprecated SQALE quality model (`sonar.cxx.other.sqales`, #858, #856). Will test again with new file format: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis#the-format-of-the-rules-file
* **Unit Test Success (%)** is no more supported (think API has be removed by core).

**Comment by GoGus85** [comment]
Hi,
We're running SonarQube 6.0, I'm trying to find the compatible release which according to the matrix is 0.9.7-SNAPSHOT. Does this defer that I should download and compile the sources on my own?

**Comment by guwirth** [comment]
@GoGus85 on our root page is a download link to the build of the latest snapshot: https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

**Comment by GoGus85** [comment]
Thank you, worked fine!

**Comment by rohit-venkat** [comment]
@guwirth Is there an target release date for 9.7?

**Comment by guwirth** [comment]
@rohit-venkat Maybe by end of the year. But you can download and use latest snapshot from here: https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts
We are interested in your feedback.

**Comment by guwirth** [comment]
@all please do final testing. If possible we try to release 0.9.7 by end of the year.
* Integration tests on SQ6.2 are failing but plugin should work. Problem are removed metrics / changed coverage handling.

**Comment by rohit-venkat** [comment]
@guwirth We have been using the 9.7 snapshot on a Test Sonar instance(Version 5.6), for a few weeks now. Saw a few differences compared to the 9.6 version of the plugin. We noticed a LOC issue on the 9.6, that was reporting 500K lines lower than usual, 9.7 seemed to have brought back the count to around what I was expecting, So it is looking good. 

Probably a trivial issue but I did notice the history graph for LOC on the 9.7 installation was going from 2mil to 2mil on the y axis. I'll try to get you a screen shot in some time..

**Comment by thygizmo** [comment]
Hi, I tried getting the 0.9.7 snapshot from the provided url but without success:

https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

Is it still accessible?

Cheers,
Gizmo

**Comment by jmecosta** [comment]
https://ci.appveyor.com/api/buildjobs/mxtxkxslvbk70nsb/artifacts/sonar-cxx-plugin%2Ftarget%2Fsonar-cxx-plugin-0.9.7-SNAPSHOT.jar

On Thu, 22 Dec 2016, 17:26 thygizmo, <notifications@github.com> wrote:

Hi, I tried getting the 0.9.7 snapshot from the provided url but without
success:

https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx/branch/master/artifacts

Is it still accessible?

Cheers,
Gizmo

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/SonarOpenCommunity/sonar-cxx/issues/978#issuecomment-268822270>,
or mute the thread

**Comment by thygizmo** [comment]
Hi,
It was taking ages to load. Probably some DNS cache resolving issue on my side.

In the end I managed to get the snapshot jar file!

Thanks João!
PS: Votos de um feliz natal e própero Ano Novo :) Obrigado uma vez mais!

**Comment by jmecosta** [comment]
Boa, feliz natal e próspero ano novo também pra ti

Abraço

**Comment by guwirth** [comment]
@all preparation done: v0.9.7-RC1 created, documents updated
@jmecosta can you upload jar files to RC1 release please?

**Comment by jmecosta** [comment]
@guwirth done

**Comment by guwirth** [comment]
@jmecosta thx

**Comment by jmecosta** [comment]
@guwirth no prob, Happy new year also
