### ISSUE TITLE
cxx compiler report - code issue in sonar qube

### ISSUE THREAD

**Issue by iamthegD** [SonarOpenCommunity/sonar-cxx#981]
Hi,

I successfully setup the warning eater from my msbuild log file and I have a question regarding the code issues its supposed/should create ?

In my build log I see : C++ compiler Warnings processed = 2
Which leads me to think I should see 2 code smell or something along those lines. 
I'm I missing something or its how should it work ?

Excuse if the format/pertinence is not great, I am not too familiar with github. If this is not appropriate feel free to delete/send to good place.

Thanks for your time.

**Comment by guwirth** [comment]
Hi @iamthegD, looking at the code: https://github.com/SonarOpenCommunity/sonar-cxx/blob/0abe151386820b6d3dfcf2a760880f63637f3902/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/utils/CxxReportSensor.java#L84 it is the number of issues/violations in the report file. If the issues/violations in the report file are invalid (wrong filename, wrong line number, ...) it could be that you can't see them in SQ (see also https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues).

**Comment by guwirth** [comment]
But looking a little bit closer to this I think the info is too early in the code: https://github.com/SonarOpenCommunity/sonar-cxx/blob/0abe151386820b6d3dfcf2a760880f63637f3902/sonar-cxx-plugin/src/main/java/org/sonar/plugins/cxx/utils/CxxReportSensor.java#L91, should be after `...save()`.

@jmecosta maybe you can move it together with #758.

**Comment by iamthegD** [comment]
thanks for the quick info.

Turns out the specific warning I introduced in my code were not turned on by default in the quality gates.

For other who will experience the same problem, look for the C#### values you need ahead of time :)
