### ISSUE TITLE
Extract this magic number 'nullptr' into a constant, variable declaration or an enum.

### ISSUE THREAD

**Issue by tomikais** [SonarOpenCommunity/sonar-cxx#986]
'nullptr' is detected as a magic number (Magic number should not be used). 

It is possible to add 'nullptr' to the rule exception list to fix it. But I think it's better to fix the rule detection directly in the Cxx plugin!?

**Comment by guwirth** [comment]
Hi @tomikais 
* which version of the plugin are you using?
* The code for this is here https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/MagicNumberCheck.java. Don't understand why **nullptr** is handled as a magic number? Could you provide a sample please.
* maybe the preprocessor is converting nullptr to 0 or NULL?

**Comment by tomikais** [comment]
Hi @guwirth 

I'm using the latest version 0.9.6.

`void InterfaceTestGui::resetGui()
{
  m_ui->txtXmlSend->clear();
  m_ui->txtXmlResult->clear();
  m_ui->txtXmlResultFormated->clear();
 
  m_ui->lblXmlInputPath->clear();
  m_ui->lblXmlOutputPath->clear();
 
  m_sendXmlFile = ""; 
  m_resultXmlFile = ""; 
 

  setCurrentFile(nullptr); // Extract this magic number 'nullptr' into a constant, variable declaration or an enum.
  statusBar()->showMessage(tr("GUI reset complete"), DISPLAY_TIME_STATUS_BAR);
}`

Regards
