### ISSUE TITLE
How to find the symbol definition in the head file

### ISSUE THREAD

**Issue by WoolenWang** [SonarOpenCommunity/sonar-cxx#991]
when i try to find the source file function using snoar-cxx is very great.
but when i try to find the definition of symbol in function body , i got trouble.
here is how i try::
> 		File one_file = new File("F:\\download\\lua-5.2.3\\src\\lapi.c");
> 		CxxConfigurationModel cfg_module = new CxxConfigurationModel();
> 		String file_str = Files.toString(one_file, cfg_module.getCharset());
> 		AstNode astNode = cfg_module.getParser().parse(file_str);
>              AstNodeXPathQuery xpath = AstNodeXPathQuery.create("//functionDefinition")
>               ArrayList list = xpath.selectNodes(astNode)

i can find the function ast node in the c source file.
when the c source file function is like::
test.c::

>   static const luaL_Re max(int a, int * b)
>   {
>  	int * xx = NULL;
>  	int ** bb = NULL;
>  	**luaL_Re** aaa = {0};
>      return a>b?a:b;
>   }

the struct definition is  in the head file::
test.h::

>  typedef struct luaL_Reg {
>    const char *name;
>    lua_CFunction func;
>  } luaL_Reg;

how can i find the header definition ast node using snoar-cxx when it is in the head file (all i have is a symbol keyword like "luaL_Reg" which i found in the c source )

**Comment by WoolenWang** [comment]
using the config setting for the include files doesn't help to get the struct define in the head file::

>     CxxConfiguration config = new CxxConfiguration(getCharset());
>     config.setErrorRecoveryEnabled(false);
>     String include[] = {"F:\\download\\lua-5.2.3\\src"};
>     config.setIncludeDirectories(include);

so i don't known how to get the symbol definition ast node , any body can help me ? thanks a lot~!

**Comment by guwirth** [comment]
@WoolenWang first of all I think we need a little bit more context to understand what you like to do.

In general:
* in C/C++ the preprocessor is first creating one output file from the .c/.cpp and all includes
* In a second step the parser creates an AST. To understand this better our [sslr-cxx-toolkit](https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-0.9.6/sslr-cxx-toolkit-0.9.6.jar) is very helpful. Insert your code and have a look to the resulting AST. 
* Searching for something you have to search for a AST node pattern in the AST. Have a look to the checks, there are some samples for this: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/cxx-checks/src/main/java/org/sonar/cxx/checks

**Comment by guwirth** [comment]
@WoolenWang I close this, please reopen if still an issue.
