### ISSUE TITLE
Integrate Valgrind (a GNU tool for memory check) reports with SonarQube

### ISSUE THREAD

**Issue by SuryaPractise** [SonarOpenCommunity/sonar-cxx#994]
Hi team,

With reference to  #987,

I followed the steps given in sonar wiki. I was able to generate the Valgrind report, but when I ran sonar-scanner, I couldn’t trace any logs related to Valgrind and also on the dashboard. Not sure if I miss something.

Any help much appreciated.

Thanks,
Surya

**Comment by guwirth** [comment]
Hi @SuryaPractise,

things you can try:
* check if the valgrind rules are enabled
* turn debugging log items on to see
  * if plugin is able to read your file
  * is able to read the issues in the log file
  * https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Get-debug-information
* if sensor is able to find the file it's mostly a path issue: https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Path-and-path-separator-issues

Regards

**Comment by guwirth** [comment]
@SuryaPractise I close this - if still an iusse reopen it.
