### ISSUE TITLE
syntax error, skip '__namespace'

### ISSUE THREAD

**Issue by sreeramk08** [SonarOpenCommunity/sonar-cxx#995]
Thanks for such a wonderful plugin.  Eventhough the Analysis is Successful, I'm not sure what to make of these warnings.   

These warnings are printed on the sonar-scanner STDOUT 

**WARN: [/home/jenkins/workspace/Sonar/LIS/src/CORE/CCPARSE/lib/Factory.C:39]: syntax error, skip '__namespace'**

whenever Sonar comes across code that looks like this? Everything within the namespace block is posted as a syntax error on STDOUT.  

#include <CCPARSE/Factory.H>
namespace CCPARSE {

**Comment by guwirth** [comment]
@sreeramk08 Looking to the error message `namespace` seems to be replaced by `__namespace`. This is the case if `sonar.cxx.cFilesPatterns` is used, see https://github.com/SonarOpenCommunity/sonar-cxx/blob/985c0d7849dffe25eff00aa692bcbd4a1d972e63/cxx-squid/src/main/java/org/sonar/cxx/preprocessor/StandardDefinitions.java#L62

**Comment by sreeramk08** [comment]
guwirth,

  Thanks for the reply.  I do see that sonar.cxx.cFilesPatterns is set to *.c,*.C and I don't seem to be able to remove that (by design I suppose).  So, I have to use the sonar.cxx.cFilesPatterns option. 

  To fix the problem, are you suggesting all .C files having namespace be replaced with __namespace?  Is there a way to ignore that check?  I tried looking up the rules and searching for some keywords, but haven't been able to find such a rule either.  

thanks again
Sam

**Comment by guwirth** [comment]
* First question: is your code c or c++?
* idea of this `sonar.cxx.cFilesPatterns` was to replace C++ keywords with a placeholder to be able to parse also C code
* As far as I know C does not support namespaces? So using namespace keyword in a C file is wrong? ...and the syntax error right?

Why not parsing all with `sonar.cxx.suffixes.sources=.cxx,.cpp,.cc,.c` and removing `sonar.cxx.cFilesPatterns`?

**Comment by sreeramk08** [comment]
Guwirth, 
   Thank you so much!  Once I renamed the files as .cpp instead of .C, then error went away!  I'll take this to the team and ask them to consider this change. 

   I want to see if there is a rule in Sonarqube that will show this problem as an issue/bug/code smell instead of just printing it on stdout.  :)

thanks again!
Sam

**Comment by guwirth** [comment]
@sreeramk08 good  to hear that your problem is solved. You can try this checks:
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/ParsingErrorCheck.java
* https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/ParsingErrorRecoveryCheck.java
