### ISSUE TITLE
coverage issues with SQ6.2

### ISSUE THREAD

**Issue by guwirth** [SonarOpenCommunity/sonar-cxx#999]
Integration tests measuring coverage are no more running with SQ6.2 (see log files of IT tests).

**Comment by jmecosta** [comment]
@guwirth this is expected, the coverage format will not be supported as it is now. i think we need to release 0.9.7 to support versions up to 6.1. and start 0.9.8 that supports 6.2 and above

**Comment by guwirth** [comment]
This SQ strategie is like a pain in the ass. Adding, removing changing, .... without any benefit for the users just wanna see the Technical Debt. Created a forum item: https://groups.google.com/forum/#!topic/sonarqube/_B0Tnz3TyUA

**Comment by guwirth** [comment]
@jmecosta current 0.9.7 is not usable for use because #909 is missing. Without 'forceZeroCoverage' resulting values are unusable.

**Comment by jmecosta** [comment]
#909 it will only work if we implement a loc visitor and retrive the lines location. then mixed that with the coverage and reconstruct it. server side support forget about because they just remove the all thing

**Comment by guwirth** [comment]
@jmecosta saw a solution in e.g. 
* https://github.com/SonarSource/sonar-javascript/blob/master/sonar-javascript-plugin/src/main/java/org/sonar/plugins/javascript/lcov/LCOVCoverageSensor.java#L128
* https://github.com/SonarSource/sonar-python/blob/master/sonar-python-plugin/src/main/java/org/sonar/plugins/python/coverage/PythonCoverageSensor.java#L82

**Comment by jmecosta** [comment]
@guwirth those solutions seems to treat all lines as executable lines. I think that will also cause invalid coverage measures numbers. i think we really a LOC visitor and save only the lines that have code.
